### PR TITLE
Add pre-push hook

### PR DESCRIPTION
**Pull request by akalin-keybase**
The pre-commit hook can't be used as a pre-push hook
since it relies on git diff.

Also, clean up pre-commit hook.

### CODE REVIEW

**Comment by akalin-keybase** [comment]
Any ideas on how to avoid the code duplication? Includes won't work since these files will be symlinked. Although from the Makefile invocation it seems that $PWD is the root directory of the repo? Or are we just assuming that git commands are run from there? Hmm...

**Comment by oconnor663** [comment]
It looks like the hooks [will always run in the root of the repo](https://stackoverflow.com/questions/7065224/in-a-git-hook-is-the-current-working-directory-guaranteed-to-be-within-the-git-r). So maybe we could just assume relative paths resolve from there?

We could also try to `source` other scripts in the repo relative to a `readlink` or `realpath` on the `$BASH_SOURCE`? The main annoying thing about doing that is that those commands work differently on Mac and Linux.

**Comment by akalin-keybase** [comment]
Agh, another constraint I forgot about is that these files are also symlinked to from the kbfs repo -- so if we include stuff from these files, that won't work anymore. :/

So I think duplicating the code here is the least bad thing to do, at least for now.

**Comment by oconnor663** [comment]
The kbfs repo links to hooks that are defined in client? :|

**Comment by akalin-keybase** [comment]
The KBFS repo doesn't have any links, but the current practice is to just use client's hooks:

```
lrwxr-xr-x   1 akalin  staff    67 May 29  2015 pre-push -> /Users/akalin/go/src/github.com/keybase/client/git-hooks/pre-commit
```

**Comment by oconnor663** [comment]
:+1:

**Comment by akalin-keybase** [comment]
Per our discussion, added comments re. factoring out common code in the future, but pushing as-is for now.

**Pull request closed without merging**
