### PR TITLE
Add Confirmed boolean to DeleteConversation RPC

### PR DESCRIPTION
**Pull request by akalin-keybase**
This is so that the GUI can handle the confirmation dialog itself, and
then just call the RPC as a final step.

### CODE REVIEW

**Comment by akalin-keybase** [comment]
Oops, not quite ready yet...

**Comment by akalin-keybase** [comment]
Ah, thanks! I was gonna try adding a unit test for it.

**Comment by akalin-keybase** [comment]
@mmaxim added tests, PTAL!

**Comment by mmaxim** [comment]
You should copy the setup functions for these tests from the other tests in the file, you shouldn't need to set up inbox source and company manually. Let me know if you want to talk more about it, but that stuff should be handled automatically.

**Pull request merged**
