### PR TITLE
Integrate Tracker popup with RemoteComponent

### PR DESCRIPTION
**Pull request by MarcoPolo**
Has the tracker popup use the `RemoteComponent` to spawn a popup window when getting a tracker request.

## To Use
open the main app, and type `kbstage id --delegate-identify-ui max` in the terminal. It should spawn a window with the tracker popup information (it might take a bit to start the id stuff on the go side).

## Caveat
The main window needs to be open, it's not enough to have something on the menu bar.
This can be fixed in the next PR

## Potential ~~Pugs~~ Bugs
If you close the window manually the component might still think it's mounted, so maybe there should be a callback you pass into `RemoteComponent` something like `onClose`

@keybase/react-hackers

### CODE REVIEW

**Comment by cjb** [comment]
If I close the main window and then try to exit the app, I get:

screenshot from 2015-11-24 17-37-34

**Comment by cjb** [comment]
Oh, there's a typo but not in this PR:

`action tracker:udpateProofState`

**Comment by cjb** [comment]
Saw this after doing a few identifies in a row (but none at the same time as each other):
```
Uncaught Error: Could not call remote function `emit`. Check that the function signature is correct. Underlying error: Attempting to call a function in a renderer window that has been closed or released. Function provided here: remote-component-loader.js:67:19.
Error: Could not call remote function `emit`. Check that the function signature is correct. Underlying error: Attempting to call a function in a renderer window that has been closed or released. Function provided here: remote-component-loader.js:67:19.
    at callFunction (/Users/cjb/go/src/github.com/keybase/client/desktop/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/browser/lib/rpc-server.js:185:13)
    at EventEmitter.<anonymous> (/Users/cjb/go/src/github.com/keybase/client/desktop/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/browser/lib/rpc-server.js:280:14)
    at emitMany (events.js:108:13)
    at EventEmitter.emit (events.js:182:7)
    at EventEmitter.<anonymous> (/Users/cjb/go/src/github.com/keybase/client/desktop/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/browser/api/lib/web-contents.js:95:27)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
```

**Comment by cjb** [comment]
I see the same bug with the first identify after Electron launch not opening a new window on both OS X and Linux.

On OS X, the first identify causes Electron to raise its main window to the front, but there's no new window created.

**Comment by cjb** [comment]
Started digging.  Each time I run `keybase id --delegate-identify-ui chris`, this element gets rendered twice:
```html
      return (
        <RemoteComponent
          windowsOpts={{
            width: 700,
            height: 700
          }}
          waitForState
          component='tracker'/>
      )
```
.. once immediately at the start of the run (and this is where it blinks open and closed immediately), and once after the proofs have finished checking.

Huh, now this time around the window didn't open after either of the two calls to render(), even though it rendered the <RemoteComponent>.  It usually comes up on the second render(), but not always.

**Comment by cjb** [comment]
Oh, here's where it flashes open and closed:
```js
    const windowsOpts = {width: 500, height: 300, fullscreen: false, ...this.props.windowsOpts,}
    this.remoteWindow = new BrowserWindow(windowsOpts)
    this.closed = false

    this.remoteWindow.hide()

    this.remoteWindow.on('needProps', () => {
      this.remoteWindow.emit('hasProps', {...this.props})
    })
```
Instead of showing and then hiding it, we should add `show: false` to the windowsOpts to avoid the blink.

Will keep looking through to hasProps to see whether we get them, and why we decide not to show().

**Comment by cjb** [comment]
Huh!  I commented out all the calls to remoteWindow.show() and focus() that I can find, and the window still appears eventually, so I obviously haven't tracked down the code path that's ultimately responsible for making that happen.  It gets shown at the same time as `tracker:markActive`, but the reducer for that action doesn't seem to do anything special..

**Comment by cjb** [comment]
BTW this is in the tracker's console:
```
Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `ProofsRender`. See https://fb.me/react-warning-keys for more information.
```

**Comment by cjb** [comment]
I found the divergence.  In remote-component-loader.js:
```js
      // Maybe we need to wait for the state to arrive at the beginning
      if (props.waitForState && !this.state.loaded) {
        console.log('A')
        const unsub = store.subscribe(() => {
          console.log('B')
          currentWindow.show()
          this.setState({props: props, loaded: true})
          unsub()
        })
      }
```
On some runs, we see "A B B" and the window shows, in response to the first identify call.

But in other identify first runs, we only see "A".  So something about a newly-created window is making store.subscribe() act flaky, as I see it.

**Comment by cjb** [comment]
Oh.  Is it just a race where we call subscribe() while we're getting proof updates sent to the store at the same time, and if the proofs all finish before we register our subscribe() handler then it never fires and the window never shows?

**Comment by MarcoPolo** [comment]
Spent a bit trying to fix the javascript error popups you get when:

1. You close the main window, and then close the tracker popup

2. You refresh the main window, and then close the tracker popup

But I kept getting bit by some subtleties. I'm going to focus on that next. and the related issue of the caveat mentioned in the PR. 

What I'm going to try first is to see if we can keep the main window alive (just hide it when you close it) and then do most processing from there.

There also seems some undefined behavior if you close the tracker popup mid identify, so that needs to be looked at too.
 
With those issues listed, is there anything else that should prevent this PR from getting merged?

take another look please @keybase/react-hackers

**Comment by cjb** [comment]
LGTM, getting this in and taking on remaining bugs in new stories and PRs works for me!

Want to fix the tracker:udpateProofState typo? I know it's not yours..

**Pull request merged**
