### PR TITLE
disk caching for UPAKs

### PR DESCRIPTION
**Pull request by maxtaco**
- expose methods for chat like LookupUsernameAndDevice
- some light testing, but didn't go overboard here.
- inspected by hand that it seems to do the right thing.

### CODE REVIEW

**Comment by maxtaco** [comment]
I didn't go overboard in testing, but I think it's good enough for now. @mmaxim do you want to take a look?

**Comment by keybase-ci-visdiff** [comment]
The commits 2f934d5a075d...3dd13fd62328 introduce visual changes on linux. <details><summary>:mag_right: 1 changed</summary>

 * Changed: **Chat_Input-Emoji_Open** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1481685962207-2f934d5a075d-3dd13fd62328-linux/Chat_Input-Emoji_Open-2f934d5a075d.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1481685962207-2f934d5a075d-3dd13fd62328-linux/Chat_Input-Emoji_Open-3dd13fd62328.png)  
   Chat_Input-Emoji_Open comparison
</summary>

**Comment by keybase-ci-visdiff** [comment]
The commits 2f934d5a075d...ab98e319f96d introduce visual changes on linux. <details><summary>:mag_right: 1 changed</summary>

 * Changed: **Chat_Input-Emoji_Open** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1481727172905-2f934d5a075d-ab98e319f96d-linux/Chat_Input-Emoji_Open-2f934d5a075d.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1481727172905-2f934d5a075d-ab98e319f96d-linux/Chat_Input-Emoji_Open-ab98e319f96d.png)  
   Chat_Input-Emoji_Open comparison
</summary>

**Comment by keybase-ci-visdiff** [comment]
The commits 2f934d5a075d...7fc027e83cb3 introduce visual changes on linux. <details><summary>:mag_right: 1 changed</summary>

 * Changed: **Chat_Input-Emoji_Open** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1481730213877-2f934d5a075d-7fc027e83cb3-linux/Chat_Input-Emoji_Open-2f934d5a075d.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1481730213877-2f934d5a075d-7fc027e83cb3-linux/Chat_Input-Emoji_Open-7fc027e83cb3.png)  
   Chat_Input-Emoji_Open comparison
</summary>

**Comment by keybase-ci-visdiff** [comment]
The commits 2f934d5a075d...49eee05e130a introduce visual changes on linux. <details><summary>:mag_right: 1 changed</summary>

 * Changed: **Chat_Input-Emoji_Open** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1481730699457-2f934d5a075d-49eee05e130a-linux/Chat_Input-Emoji_Open-2f934d5a075d.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1481730699457-2f934d5a075d-49eee05e130a-linux/Chat_Input-Emoji_Open-49eee05e130a.png)  
   Chat_Input-Emoji_Open comparison
</summary>

**Pull request merged**
