### PR TITLE
repro chat crash on deleted user

### PR DESCRIPTION
**Pull request by maxtaco**
This test yields the chat failure on a deleted user, where the failure comes as a result of a UPAK load in a team load.  This PR won't pass CI since there's no fix for the bug yet. That fix is a server-fix and a complementary client-side fix.

### CODE REVIEW

**Comment by maxtaco** [comment]
Thanks @patrickxb  -- I'll merge this in when the PR that @oconnor663 is reviewing gets a thumb, since CI won't pass without it.

**Comment by oconnor663** [comment]
Done.

**Comment by maxtaco** [comment]
thanks @oconnor663 !

**Comment by keybase-ci-visdiff** [comment]
The commits ed4bf6a713ae...b2471c93d4b1 introduce visual changes on linux. <details><summary>:mag_right: 1 changed</summary>

 * Changed: **Markdown-emoji** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1505749274200-ed4bf6a713ae-b2471c93d4b1-linux/Markdown-emoji-ed4bf6a713ae.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1505749274200-ed4bf6a713ae-b2471c93d4b1-linux/Markdown-emoji-b2471c93d4b1.png)  
   Markdown-emoji comparison
</summary>

**Pull request merged**
