### PR TITLE
proof confirmation/pending page

### PR DESCRIPTION
**Pull request by chrisnojima**
@keybase/react-hackers

### CODE REVIEW

**Comment by keybase-ci-visdiff** [comment]
:mag_right: The commits 0f74479f1182...896f44a87718 introduced some visual changes on linux:
 * Added: **My_Profile_Confirm_or_Pending-Pending_dns**  
   My_Profile_Confirm_or_Pending-Pending_dns rendered
 * Added: **My_Profile_Confirm_or_Pending-Pending_Hacker_News**  
   My_Profile_Confirm_or_Pending-Pending_Hacker_News rendered
 * Added: **My_Profile_Confirm_or_Pending-Confirm_http**  
   My_Profile_Confirm_or_Pending-Confirm_http rendered
 * Added: **My_Profile_Confirm_or_Pending-Confirm_Twitter**  
   My_Profile_Confirm_or_Pending-Confirm_Twitter rendered
 * Added: **My_Profile_Confirm_or_Pending-Confirm_Reddit**  
   My_Profile_Confirm_or_Pending-Confirm_Reddit rendered
 * Added: **My_Profile_Confirm_or_Pending-Confirm_Github**  
   My_Profile_Confirm_or_Pending-Confirm_Github rendered
 * Added: **My_Profile_Confirm_or_Pending-Confirm_Coinbase**  
   My_Profile_Confirm_or_Pending-Confirm_Coinbase rendered
 * Added: **My_Profile_Confirm_or_Pending-Confirm_Bitcoin** [(view)](https://keybase-app-visdiff.s3.amazonaws.com/1468878749109-0f74479f1182-896f44a87718-linux/My_Profile_Confirm_or_Pending-Confirm_Bitcoin-896f44a87718.png)
 * Removed: **My_Profile_Confirm_Or_Pending-Confirm_Twitter** [(view original)](https://keybase-app-visdiff.s3.amazonaws.com/1468878749109-0f74479f1182-896f44a87718-linux/My_Profile_Confirm_Or_Pending-Confirm_Twitter-0f74479f1182.png)
 * Removed: **My_Profile_Confirm_Or_Pending-Confirm_Github** [(view original)](https://keybase-app-visdiff.s3.amazonaws.com/1468878749109-0f74479f1182-896f44a87718-linux/My_Profile_Confirm_Or_Pending-Confirm_Github-0f74479f1182.png)

**Comment by chromakode** [comment]
Looks like the proof overlay images need a white background fill so the platform icon doesn't show through.

**Comment by chromakode** [comment]
:+1:

**Comment by chrisnojima** [comment]
Yeah there's a comment about needing to swap the assets

**Pull request merged**
