### PR TITLE
add all media button to attachment popup menu, mobile fullscreenview

### PR DESCRIPTION
**Pull request by joshblum**
image
image
image

cc @adamjspooner @cecileboucheron

### CODE REVIEW

**Comment by hyperobject** [comment]
the button doesn't show up in the popup menu for exploding messages, but maybe that's intentional?

**Comment by joshblum** [comment]
Oops not intentional, will fix

**Comment by cecileboucheron** [comment]
Can we add a verb and say "View all media"?

**Comment by joshblum** [comment]
Fwiw this matches what WhatsApp does, don’t think it’s necessary

**Pull request merged**
