### PR TITLE
limit flow damage

### PR DESCRIPTION
**Pull request by chrisnojima**
We're currently really suffering from this issue: https://github.com/facebook/flow/issues/4797
So flow doesn't hose our machines (as much) lets limit it to 1 core

@keybase/react-hackers 
cc: @mmaxim  @cecileboucheron

### CODE REVIEW

**Comment by cjb** [comment]
How much slower is it (in the normal, not runaway case)?

**Comment by chrisnojima** [comment]
unclear. this is hopefully temporary. the current state makes things pretty unusable and it happens fairly often

**Comment by mmaxim** [comment]
Yeah I'm confused how this isn't affecting the whole frontend team more. How do you all use Flow? I have it in my editor, so I find it is always going to 100% if I am in JS file. Do you all not see that?

**Comment by akalin-keybase** [comment]
I also have it in my editor, and I notice it most when running `flow status` synchronously (and it hangs). It should also be running it in the background, but for some reason I don't notice that spiking CPU.

**Pull request merged**
