### PR TITLE
Add detailed instructions for running on Android

### PR DESCRIPTION
**Pull request by akalin-keybase**

### CODE REVIEW

**Comment by akalin-keybase** [comment]
FYI, I'm using NDK 16 (since I installed today), and existing stuff might still work because NDK 15 is installed.

Although I'm not sure how kbfs is still building for mobile, since it would fail when trying to use an old go-framed-msgpack-rpc.

**Comment by akalin-keybase** [comment]
Reverted gomobile changes and changed instructions to downgrade NDK to r15. PTAL @chrisnojima

**Comment by akalin-keybase** [comment]
I believe so. If it's still working for you, perhaps you have an old checkout of kbfs.

**Comment by akalin-keybase** [comment]
@mmaxim for core changes.

**Comment by mmaxim** [comment]
I think if you merge master you'll get that vendor change from @songgao

**Comment by akalin-keybase** [comment]
Thanks @mmaxim, rebased on master. PTAL @chrisnojima!

**Comment by akalin-keybase** [comment]
Merging this despite code freeze since this only changes documentation.

**Pull request merged**
