### PR TITLE
Use updated react-native-push-notification

### PR DESCRIPTION
**Pull request by akalin-keybase**
Also target SDK 28 for Android.

Fix problem with jcenter.

### CODE REVIEW

**Comment by akalin-keybase** [comment]
One thing I noticed while testing is that the default notification settings are to make a sound and have a badge, but not to have a pop up. If we want to preserve the pop up behavior, I'd have to make another react-native-push-notification PR to use IMPORTANCE_HIGH.

**Comment by chrisnojima** [comment]
yeah lets maintain what it was doing, we can merge this still and do that in a second pr so we can get some feedback on this

**Comment by akalin-keybase** [comment]
Actually, I'd better update react-native-push-notification first -- there doesn't seem to be a way to programmatically 'upgrade' the setting for a notification channel once it's created, so anyone who's downloaded a build with the current channel settings would be stuck with it until they manually fix it.

**Comment by akalin-keybase** [comment]
Okay, updated react-native-push-notification to use IMPORTANCE_HIGH and updated the commit on this, PTAL!

**Pull request merged**
