### PR TITLE
Join subteam temporarily after creating it to setup chat

### PR DESCRIPTION
**Pull request by patrickxb**

### CODE REVIEW

**Comment by maxtaco** [comment]
This is suboptimal if the next the user does is to join the sigchain.  Then the sub team has join, leave join.   Can we at least change create sub team to have a parameter that can be specified if the user wants to be in the subteam.  And in the case no “leave”?

**Comment by mmaxim** [comment]
That doesn't actually solve the problem. We need to have someone create the general channel so that the people that to join the team can chat right away without having to do anything. We need the creator to get in there, create #general, drop a system message in there, and the peace out. I think this is the easiest thing to do code-wise on our side, and it doesn't involve any UI changes at all either.

**Comment by maxtaco** [comment]
Now I am confused. AFK but I want to edit my above comment when I get a moment.

**Comment by patrickxb** [comment]
We had a meeting with design and frontend and this was the solution we came up with at the meeting.

**Comment by mmaxim** [comment]
oh I think I see what you are saying. We could just aadd an option to createteam to join the created subteam and then skip all this join/leave stuff? It would still need UI support, but seems like maybe not such a hard change to make

**Comment by maxtaco** [comment]
Yes.  Sorry to be incoherent.

Easy to fix on the CLI.

**Comment by maxtaco** [comment]
We can make it opt out.

**Comment by mmaxim** [comment]
Coyne wanted the default to be you aren’t in the subteam for a variety of reasons, and seemed very sad and dejected when contemplating a world in which the default was you joined after create. We should probably just talk in person on Monday

**Comment by maxtaco** [comment]
Ok thanks

**Comment by maxtaco** [comment]
(Ok, nonsensical comment updated...)

**Comment by dabura667** [comment]
> seemed very sad and dejected when contemplating a world in which the default was you joined after create

Passion about the project is great. Good for Coyne for being passionate! :+1:

**Comment by patrickxb** [comment]
Ok, I've added a field to the RPC to allow joining the subteam when creating it.  It's exposed in the CLI.

Also, joins to #general no longer show a join system message.

The create team system message isn't rendered in the GUI, but is in the CLI.

PTAL

**Comment by patrickxb** [comment]
@keybase/react-hackers need some flow help here on rpc change.

**Comment by mmaxim** [comment]
Pending CI

**Comment by patrickxb** [comment]
@keybase/react-hackers never mind, i think i fixed it myself.

**Pull request merged**
