### PR TITLE
Tweaks keybase extension

### PR DESCRIPTION
**Pull request by cecileboucheron**
* Updated chat + placeholder icons
* Updated our blues and greens
* Copy and text style tweaks
@malgorithms 
@keybase/react-hackers

### CODE REVIEW

**Comment by joshblum** [comment]
could you run through this QA list: 
https://github.com/keybase/client/tree/master/browser#quick-qa-check

I don't think any of these changes will break anything but sometimes the website designs change so we can fix any issues before releasing. Also anything worth changing in our descriptions/photos:
https://chrome.google.com/webstore/detail/keybase/ognfafcpbkogffpmmdglhbjboeojlefj
https://addons.mozilla.org/en-US/firefox/addon/keybase-for-firefox/

otherwise these changes lgtm, once it's merged i can deploy in the chrome/firefox app stores.

**Comment by cecileboucheron** [comment]
I just added more tweaks and went through your QA list again after that - all is good except the HN and Facebook ones not showing up when logged in.

**Comment by joshblum** [comment]
i'll fixup the broken endpoints in a separate PR

**Comment by mlsteele** [comment]
I haven't looked at what this branch changes, but fyi facebook button looks bananas on master.

image

**Comment by joshblum** [comment]
logged out view looks good :/

screen shot 2018-07-23 at 4 51 55 pm

@cecileboucheron wasn't able to test it since it wasn't showing up once https://github.com/keybase/client/pull/12930, would you mind doing another pass?

**Comment by mlsteele** [comment]
If I have assessed it correctly it should always show up when visited via direct link https://www.facebook.com/ccoyne77. If that's not true then https://github.com/keybase/client/pull/12930 won't fix it. Lmk

**Comment by cecileboucheron** [comment]
@mlsteele This branch won't solve this positioning issue you describe - we should file a new ticket for it.
@joshblum Removed bundle.js 👍

**Pull request merged**
