### PR TITLE
Check for blank session token

### PR DESCRIPTION
**Pull request by mlsteele**
Not sure how to tell whether this is the real cause or how to test it.
@mmaxim

### CODE REVIEW

**Comment by mmaxim** [comment]
@patrickxb Is there a better error we should be throwing in this case?

**Comment by patrickxb** [comment]
hmm, you could make more checks in the LocalSession block.

if s.IsLoggedIn() { token = ...; uid = ... }

then once you get out if token is empty you could return LoginRequiredError?

But I'm not sure what you're trying to fix exactly.

**Comment by mmaxim** [comment]
Goal is to stop all the authentication requests to Gregor with blank session tokens.

**Comment by mmaxim** [comment]
I thought since we had all the logged in checks for trying to connect to Gregor that we would never make it this far.

**Comment by patrickxb** [comment]
yeah, I'm confused how it could be empty.

**Comment by mlsteele** [comment]
I'm not sure this ever does happen. My thinking was that if this doesn't hurt, and we deploy it, then we'll know a bit more based on whether the blanks disappear from the gregor logs.

Only other idea I've thought of is to get the IPs of the offending requests and figure which users they are and see if there happen to be log sends. Seems hard.

**Comment by patrickxb** [comment]
Ok, in that case use whatever error you'd like to that will be easy to find in the log.

**Comment by mmaxim** [comment]
Can we have the text be like "blank session would have been sent to gregor" or something?

**Comment by mlsteele** [comment]
sure, done

**Pull request merged**
