### PR TITLE
Send frontend paymentNotification when gregor msg handled

### PR DESCRIPTION
**Pull request by patrickxb**

### CODE REVIEW

**Comment by mmaxim** [comment]
This is an IBM because we can't miss it?

**Comment by patrickxb** [comment]
OOBM should be fine.  I'll change it.

**Comment by patrickxb** [comment]
@keybase/react-hackers can you fix this?  CI complaining.  thank you!

**Comment by chrisnojima** [comment]
looking

**Comment by chrisnojima** [comment]
@patrickxb that should fix it. i assume we want these notifications...

**Pull request merged**
