### PR TITLE
test to make sure service errors on identify failure

### PR DESCRIPTION
**Pull request by songgao**
@patrickxb Is this what you had in mind?

Although we are not plumbing through TLFIdentifyBehavior in service yet. It's currently always using `TLFIdentifyBehavior_CHAT_CLI`, which is to error on identify failure

Thanks!

### CODE REVIEW

**Comment by songgao** [comment]
@patrickxb No it doesn't; it tests that the `chat_local.go` works as expected. There are tests for the service-identify side in https://github.com/keybase/client/pull/4467 though.

I guess it wouldn't hurt to have some tests to practice the identify side as well ... do you think I should do it in service using FakeUser, or as integration tests?

**Comment by patrickxb** [comment]
@maxtaco @mmaxim what do you think?

My initial thought was just to have a test with a real (fake) user w/ broken proofs hitting the new service identify code and making sure chat was ok.  But I don't want to create additional work if you guys are fine with the mock.

**Comment by maxtaco** [comment]
I agree with @patrickxb's thinking, I think we need that test especially.

**Comment by mmaxim** [comment]
Yeah agree.

**Comment by songgao** [comment]
OK; working on it; thanks guys!

**Comment by songgao** [comment]
Closing in favor of https://github.com/keybase/kbfs-server/pull/157

**Pull request closed without merging**
