### PR TITLE
Revert back to Dokan 0.8 drivers.

### PR DESCRIPTION
**Pull request by zanderz**
Give up on updating drivers without uninstall.

I tried the following:
- upgrading from an install containing dokan 1.0.0RC2 drivers
- upgrading from an install containing dokan 0.8 drivers
- installing on a clean machine
- installing on a clean machine except leftover dokan.sys file
- 32 bit Windows 7

With Marco's pending fix we may be close to back in biz.
@maxtaco @taruti

### CODE REVIEW

**Comment by zanderz** [comment]
@maxtaco do I need a thumbsup before building with this, or shall I go ahead? We're just about all ready.

**Comment by maxtaco** [comment]
I'm good if @taruti is good

**Comment by taruti** [comment]
LGTM

In future it would be nice to have some kind of automated testing for Windows installers as there are so many things that can go wrong. But getting this out first makes sense.

**Comment by zanderz** [comment]
That would be so great. I was just asking Marco and Gabriel whether there
was any framework for automatically driving Electron UI s like there used
to be for win32. If you know of a robotic way to test an installer with a
driver that requires uac, I'd like to hear more.

**Pull request merged**
