### PR TITLE
plumb version through

### PR DESCRIPTION
**Pull request by chrisnojima**
@gabriel

### CODE REVIEW

**Comment by chrisnojima** [comment]
@keybase/react-hackers

**Comment by maxtaco** [comment]
@chrisnojima if you rebase that should solve the C/I bug

**Comment by chrisnojima** [comment]
what CI bug?

**Comment by maxtaco** [comment]
One of your travis builds failed.  Obviously no fault of your own.

**Comment by MarcoPolo** [comment]
:+1:

**Pull request merged**
