### PR TITLE
skip TestFlipManagerStartFlip

### PR DESCRIPTION
**Pull request by mmou**
failed in recent master build

### CODE REVIEW

**Comment by joshblum** [comment]
Cc @mmaxim

**Comment by mmaxim** [comment]
Is this actually broken? I don’t want this test skipped if it failed once

**Comment by mmou** [comment]
alright that's fine. it caused a recent master build to fail, and ctrl-f-ing #test-flakes shows 14 flakes since feb 8 (last 18 days)

**Comment by strib** [comment]
A new failure here: https://ci.keyba.se/job/client/job/PR-22751/4/execution/node/3326/log/

**Pull request closed without merging**
