### PR TITLE
Oxford comma

### PR DESCRIPTION
**Pull request by chromakode**

### CODE REVIEW

**Comment by chromakode** [comment]
:sheep: @keybase/react-hackers

**Comment by cjb** [comment]
I like how we leave the doubly-incorrect "OSX" on the same line :)

**Comment by cjb** [comment]
:thumbsup:

**Comment by chromakode** [comment]
@cjb Oops, fixed! The whole reason I noticed this was because @gabriel  fixed the "macOS" thing (https://github.com/keybase/client/commit/69a6416972b186069c81137206eab1d1c1913874) :)

**Comment by gabriel** [comment]
As long as you don't put 2 spaces after a period, I'm ok with oxford commas

**Pull request merged**
