### PR TITLE
support default variants

### PR DESCRIPTION
**Pull request by chrisnojima**
I used this to test that flow is able to handle this correctly with this

```
import type {BodyPlaintext, BodyPlaintextV1, BodyPlaintextV2, BodyPlaintextUnsupported} from '../constants/types/flow-types-chat'
const bodyPlaintext1: BodyPlaintext = {
  version: 1,
  v1: {
    messageBody: {
      messageType: 1, text: null,
    },
  },
}
const bodyPlaintext2: BodyPlaintext = {
  version: 2,
  v2: {
    messageBody: {
      messageType: 8,
      attachmentuploaded: null,
    },
  },
}
const bodyPlaintextDefault: BodyPlaintext = {
  version: 3,
  'default': {
    vi: {
      crit: true,
    },
  },
}
const all = [bodyPlaintext1, bodyPlaintext2, bodyPlaintextDefault]

all.forEach(a => {
  switch (a.version) {
    case 1:
      const v1: ?BodyPlaintextV1 = a.v1
      console.log(a.v1, v1)
      break
    case 2:
      const v2: ?BodyPlaintextV2 = a.v2
      console.log(a.v2, v2)
      break
    default:
      const unsup: ?BodyPlaintextUnsupported = a.default
      console.log(a.default.vi.crit, unsup)
      break
  }
})
```

### CODE REVIEW

**Comment by chrisnojima** [comment]
There are 2 commits, the first one is actually adding a default for the variant type (needed by the new avdl file.) The second commit is just some template cleanup in the generator which results in no changes in the output js

**Comment by chrisnojima** [comment]
@keybase/react-hackers

**Comment by chrisnojima** [comment]
They have a default for unsupported types in messaging. See the base branch

**Comment by maxtaco** [comment]
The reasoning is pretty subtle, and came out of our "future-proofing" of old clients.

In this [protocol](https://github.com/keybase/client/blob/maxtaco/unsupported-future/protocol/avdl/chat1/local.avdl#L215-L218), we're thinking about what happens if we have a client that only supports `V2` of the protocol, and a message is received from a client that sends in `V3`.  The `V2` client can dereference `mb.V3.versionInfo.crit` without knowing exactly what `V3` is going to look like, to know if it should complain to the front end that a version upgrade is required.  If that bit isn't set, then the client is safe is ignore the message.   Note when `V3` is implemented, `PlaintextV3` has to be a superset of `PlaintextUnsupported` to allow the "probe into the future" feature to work.

**Comment by chrisnojima** [comment]
all yours @maxtaco

**Pull request merged**
