### PR TITLE
Add revoke proof dumb component

### PR DESCRIPTION
**Pull request by MarcoPolo**
@keybase/react-hackers

### CODE REVIEW

**Comment by keybase-ci-visdiff** [comment]
:mag_right: The commits 5ef011aad56a...6e13ca15529e introduced some visual changes on linux:
 * Added: **Revoke_Proof-Website**  
   Revoke_Proof-Website rendered
 * Added: **Revoke_Proof-Twitter**  
   Revoke_Proof-Twitter rendered
 * Added: **Revoke_Proof-Reddit**  
   Revoke_Proof-Reddit rendered
 * Added: **Revoke_Proof-Hacker_News**  
   Revoke_Proof-Hacker_News rendered
 * Added: **Revoke_Proof-Git_Hub**  
   Revoke_Proof-Git_Hub rendered
 * Added: **Revoke_Proof-DNS**  
   Revoke_Proof-DNS rendered
 * Added: **Revoke_Proof-Coinbase**  
   Revoke_Proof-Coinbase rendered
 * Added: **Revoke_Proof-Bitcoin** [(view)](https://keybase-app-visdiff.s3.amazonaws.com/1469059503516-5ef011aad56a-6e13ca15529e-linux/Revoke_Proof-Bitcoin-6e13ca15529e.png)

**Comment by chrisnojima** [comment]
says 'genericWebsite' needs to say http/https/dns

**Comment by chrisnojima** [comment]
needs to say @twitter and not twitter

**Comment by keybase-ci-visdiff** [comment]
:mag_right: The commits 5ef011aad56a...df9dc1c5a7c2 introduced some visual changes on linux:
 * Added: **Revoke_Proof-https_website**  
   Revoke_Proof-https_website rendered
 * Added: **Revoke_Proof-Website**  
   Revoke_Proof-Website rendered
 * Added: **Revoke_Proof-Twitter**  
   Revoke_Proof-Twitter rendered
 * Added: **Revoke_Proof-Reddit**  
   Revoke_Proof-Reddit rendered
 * Added: **Revoke_Proof-Hacker_News**  
   Revoke_Proof-Hacker_News rendered
 * Added: **Revoke_Proof-Git_Hub**  
   Revoke_Proof-Git_Hub rendered
 * Added: **Revoke_Proof-DNS**  
   Revoke_Proof-DNS rendered
 * Added: **Revoke_Proof-Coinbase** [(view)](https://keybase-app-visdiff.s3.amazonaws.com/1469133904988-5ef011aad56a-df9dc1c5a7c2-linux/Revoke_Proof-Coinbase-df9dc1c5a7c2.png)
 * Added: **Revoke_Proof-Bitcoin** [(view)](https://keybase-app-visdiff.s3.amazonaws.com/1469133904988-5ef011aad56a-df9dc1c5a7c2-linux/Revoke_Proof-Bitcoin-df9dc1c5a7c2.png)

**Comment by chrisnojima** [comment]
- [ ] should say 'Are you sure you want to revoke your Twitter identity?'

**Comment by chrisnojima** [comment]
@MarcoPolo please compare these screens to zeplin

**Comment by keybase-ci-visdiff** [comment]
:mag_right: The commits 5c04598fbf64...457b8ea04ed2 introduced some visual changes on linux:
 * Added: **Revoke_Proof-https_website**  
   Revoke_Proof-https_website rendered
 * Added: **Revoke_Proof-Website**  
   Revoke_Proof-Website rendered
 * Added: **Revoke_Proof-Twitter**  
   Revoke_Proof-Twitter rendered
 * Added: **Revoke_Proof-Reddit**  
   Revoke_Proof-Reddit rendered
 * Added: **Revoke_Proof-Hacker_News**  
   Revoke_Proof-Hacker_News rendered
 * Added: **Revoke_Proof-Git_Hub**  
   Revoke_Proof-Git_Hub rendered
 * Added: **Revoke_Proof-DNS**  
   Revoke_Proof-DNS rendered
 * Added: **Revoke_Proof-Coinbase** [(view)](https://keybase-app-visdiff.s3.amazonaws.com/1469492222912-5c04598fbf64-457b8ea04ed2-linux/Revoke_Proof-Coinbase-457b8ea04ed2.png)
 * Added: **Revoke_Proof-Bitcoin** [(view)](https://keybase-app-visdiff.s3.amazonaws.com/1469492222912-5c04598fbf64-457b8ea04ed2-linux/Revoke_Proof-Bitcoin-457b8ea04ed2.png)

**Comment by chrisnojima** [comment]
- [ ] Should say 'Are you sure you want to revoke your Hacker News identity?'

**Comment by MarcoPolo** [comment]
Ugh, that was a typo in my switch statement, I did `hackerNews` instead of `hackernews` fixed now

**Comment by keybase-ci-visdiff** [comment]
:mag_right: The commits 5c04598fbf64...18c944232d33 introduced some visual changes on linux:
 * Added: **Revoke_Proof-https_website**  
   Revoke_Proof-https_website rendered
 * Added: **Revoke_Proof-Website**  
   Revoke_Proof-Website rendered
 * Added: **Revoke_Proof-Twitter**  
   Revoke_Proof-Twitter rendered
 * Added: **Revoke_Proof-Reddit**  
   Revoke_Proof-Reddit rendered
 * Added: **Revoke_Proof-Hacker_News**  
   Revoke_Proof-Hacker_News rendered
 * Added: **Revoke_Proof-Git_Hub**  
   Revoke_Proof-Git_Hub rendered
 * Added: **Revoke_Proof-DNS**  
   Revoke_Proof-DNS rendered
 * Added: **Revoke_Proof-Coinbase** [(view)](https://keybase-app-visdiff.s3.amazonaws.com/1469548835342-5c04598fbf64-18c944232d33-linux/Revoke_Proof-Coinbase-18c944232d33.png)
 * Added: **Revoke_Proof-Bitcoin** [(view)](https://keybase-app-visdiff.s3.amazonaws.com/1469548835342-5c04598fbf64-18c944232d33-linux/Revoke_Proof-Bitcoin-18c944232d33.png)

**Comment by chrisnojima** [comment]
👍

**Comment by keybase-ci-visdiff** [comment]
:mag_right: The commits 82b79d41ae57...fb7ff40b325d introduced some visual changes on linux:
 * Added: **Revoke_Proof-https_website**  
   Revoke_Proof-https_website rendered
 * Added: **Revoke_Proof-Website**  
   Revoke_Proof-Website rendered
 * Added: **Revoke_Proof-Twitter**  
   Revoke_Proof-Twitter rendered
 * Added: **Revoke_Proof-Reddit**  
   Revoke_Proof-Reddit rendered
 * Added: **Revoke_Proof-Hacker_News**  
   Revoke_Proof-Hacker_News rendered
 * Added: **Revoke_Proof-Git_Hub**  
   Revoke_Proof-Git_Hub rendered
 * Added: **Revoke_Proof-DNS**  
   Revoke_Proof-DNS rendered
 * Added: **Revoke_Proof-Coinbase** [(view)](https://keybase-app-visdiff.s3.amazonaws.com/1469566008713-82b79d41ae57-fb7ff40b325d-linux/Revoke_Proof-Coinbase-fb7ff40b325d.png)
 * Added: **Revoke_Proof-Bitcoin** [(view)](https://keybase-app-visdiff.s3.amazonaws.com/1469566008713-82b79d41ae57-fb7ff40b325d-linux/Revoke_Proof-Bitcoin-fb7ff40b325d.png)

**Pull request merged**
