### PR TITLE
Fix (t *Team) getDowngradedUsers

### PR DESCRIPTION
**Pull request by zapu**
Needed to merge https://github.com/keybase/keybase/pull/1478 again

but there might be more issues, I need to run entire test suite again.

### CODE REVIEW

**Comment by zapu** [comment]
I think it will also miss owner->admin downgrade.

**Comment by maxtaco** [comment]
You don't technically need a lease in that case.

**Comment by maxtaco** [comment]
Are you sure the problem isn't in the server? You only need a downgrade
lease if someone used to be an admin but now they are not.  Maybe the
assertion is too demanding on the server.

This is because only admins can make sigchain changes across chains.

**Comment by maxtaco** [comment]
And shoot I am sorry I didn't mention it. I ran the client tests on my
local server before I committed. It found a whole bunch of problems. I
should have suggested you do the same.

**Comment by zapu** [comment]
Totally my fault, I forgot how CI works. Thought it runs a bunch of things including client

Dnia 14.07.2017 o godz. 10:33 Maxwell Krohn <notifications@github.com> napisał(a):

> And shoot I am sorry I didn't mention it. I ran the client tests on my
> local server before I committed. It found a whole bunch of problems. I
> should have suggested you do the same.
>

**Comment by zapu** [comment]
So maybe the problem is indeed in the server, computing downgrades was already there. I assumed every membership change to a lesser role needs a lease. But if it's only admin->non admin; then I can just change the server. Thanks!

Dnia 14.07.2017 o godz. 10:33 Maxwell Krohn <notifications@github.com> napisał(a):

> And shoot I am sorry I didn't mention it. I ran the client tests on my
> local server before I committed. It found a whole bunch of problems. I
> should have suggested you do the same.
>

**Pull request closed without merging**
