### PR TITLE
Add PGP Import Key dumb component

### PR DESCRIPTION
**Pull request by cjb**
@keybase/react-hackers 

This is against @awendland's branch, and uses the <PgpIcon> component which it looks like will be going away.. maybe best to merge this in and then remove them all at once on a different branch?

Should generate a visdiff.

### CODE REVIEW

**Comment by keybase-ci-visdiff** [comment]
:mag_right: The commits 70415bb674d0...07be7480da11 introduced some visual changes on linux:
 * Added: **New_Proof_Website-DNS_or_File**  
   New_Proof_Website-DNS_or_File rendered
 * Added: **New_Proof_PGP_import-Import_PGP**  
   New_Proof_PGP_import-Import_PGP rendered
 * Added: **New_Proof_PGP-Import_or_Generate**  
   New_Proof_PGP-Import_or_Generate rendered
 * Added: **Choice_List-Two_Choices**  
   Choice_List-Two_Choices rendered

**Comment by keybase-ci-visdiff** [comment]
:mag_right: The commits 70415bb674d0...e780878532d3 introduced some visual changes on linux:
 * Added: **New_Proof_Website-DNS_or_File**  
   New_Proof_Website-DNS_or_File rendered
 * Added: **New_Proof_PGP_import-Import_PGP**  
   New_Proof_PGP_import-Import_PGP rendered
 * Added: **New_Proof_PGP-Import_or_Generate**  
   New_Proof_PGP-Import_or_Generate rendered
 * Added: **Choice_List-Two_Choices**  
   Choice_List-Two_Choices rendered

**Comment by keybase-ci-visdiff** [comment]
:mag_right: The commits 70415bb674d0...e780878532d3 introduced some visual changes on linux:
 * Added: **New_Proof_Website-DNS_or_File**  
   New_Proof_Website-DNS_or_File rendered
 * Added: **New_Proof_PGP_import-Import_PGP**  
   New_Proof_PGP_import-Import_PGP rendered
 * Added: **New_Proof_PGP-Import_or_Generate**  
   New_Proof_PGP-Import_or_Generate rendered
 * Added: **Choice_List-Two_Choices**  
   Choice_List-Two_Choices rendered

**Comment by keybase-ci-visdiff** [comment]
:mag_right: The commits 70415bb674d0...4dde292ba38c introduced some visual changes on linux:
 * Added: **New_Proof_Website-DNS_or_File**  
   New_Proof_Website-DNS_or_File rendered
 * Added: **New_Proof_PGP_import-Import_PGP**  
   New_Proof_PGP_import-Import_PGP rendered
 * Added: **New_Proof_PGP-Import_or_Generate**  
   New_Proof_PGP-Import_or_Generate rendered
 * Added: **Choice_List-Two_Choices**  
   Choice_List-Two_Choices rendered

**Comment by keybase-ci-visdiff** [comment]
:mag_right: The commits 70415bb674d0...038c09d9c0a4 introduced some visual changes on linux:
 * Added: **New_Proof_Website-DNS_or_File**  
   New_Proof_Website-DNS_or_File rendered
 * Added: **New_Proof_PGP_import-Import_PGP**  
   New_Proof_PGP_import-Import_PGP rendered
 * Added: **New_Proof_PGP-Import_or_Generate**  
   New_Proof_PGP-Import_or_Generate rendered
 * Added: **Choice_List-Two_Choices**  
   Choice_List-Two_Choices rendered
 * Changed: **Tracker-Logged_out** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1470690265386-70415bb674d0-038c09d9c0a4-linux/Tracker-Logged_out-70415bb674d0.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1470690265386-70415bb674d0-038c09d9c0a4-linux/Tracker-Logged_out-038c09d9c0a4.png)  
   Tracker-Logged_out comparison
 * Changed: **Search-Coming_soon** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1470690265386-70415bb674d0-038c09d9c0a4-linux/Search-Coming_soon-70415bb674d0.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1470690265386-70415bb674d0-038c09d9c0a4-linux/Search-Coming_soon-038c09d9c0a4.png)  
   Search-Coming_soon comparison
 * Changed: **Folders_TLF-Coming_Soon** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1470690265386-70415bb674d0-038c09d9c0a4-linux/Folders_TLF-Coming_Soon-70415bb674d0.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1470690265386-70415bb674d0-038c09d9c0a4-linux/Folders_TLF-Coming_Soon-038c09d9c0a4.png)  
   Folders_TLF-Coming_Soon comparison

**Comment by cjb** [comment]
Closing this one since its parent branch got merged in, will reopen against a diff branch.

**Pull request closed without merging**
