### PR TITLE
Plumb through onMouseEnter/Leave events on Button

### PR DESCRIPTION
**Pull request by akalin-keybase**
This makes the Follow button say 'Unfollow' on hover.

### CODE REVIEW

**Comment by akalin-keybase** [comment]
AFAICT, Button has never plumbed this through...

**Comment by chrisnojima** [comment]
i think we shouldn't do this plumbing. for all the hover stuff lets just use css (esp since its desktop only)

**Comment by akalin-keybase** [comment]
Hmm, how exactly can I use CSS for all the hover stuff? Seems like I'd have to use the :hover pseudo-class ( https://stackoverflow.com/a/19058486 ) but it looks pretty awkward to do in React: https://stackoverflow.com/a/28269935 . Plus I'd have to somehow make WaitingButton/Button understand hover properties and plumb that down. Am I missing something?

**Comment by chrisnojima** [comment]
We already have css for this. Look at our usage of classname

**Comment by akalin-keybase** [comment]
Hmm, OK, I looked at our usage of classname, but I think that using it makes the code more complicated. FollowButton would have to pass down classnames for the button container, the button label, and the progress indicator, or Button would need a new PrimaryGreenWithHover type. Then the styles would have to duplicate the style that's already in PrimaryGreenActive.

The waiting spinner's color depending on the type also makes it complicated to implement purely in CSS. I could try harder, I guess, but the current code which just switches the type and label of WaitingButton based on the hover state seems like the clearest to me.

**Comment by chrisnojima** [comment]
we can do this short term. longer term (with the new button style) i think we'll end up with a button.desktop.js that is more css based so we don't have to worry about overriding the inline styles

**Pull request merged**
