### PR TITLE
use getsubteams

### PR DESCRIPTION
**Pull request by chrisnojima**
@keybase/react-hackers this uses a new rpc that should be faster (but isn't?)
cc: @xgess

### CODE REVIEW

**Comment by xgess** [comment]
should be faster. i suspect fast enough. if it's still slow, there's another chunk of work `core` can do, but i'd rather not do it unless it's necessary.

**Comment by chrisnojima** [comment]
i think we do need to fix this. it takes 10 seconds for me to load that same team. so its not some random server load issue:

**Comment by chrisnojima** [comment]
screen shot 2018-12-28 at 4 01 34 pm

**Comment by keybase-travis** [comment]
Why is this slow?

**Pull request merged**
