### PR TITLE
Handle the case where there are warnings and we aren't already following

### PR DESCRIPTION
**Pull request by MarcoPolo**
If you weren't following someone and their id had warnings you were given the option to untrack or retrack. Neither make sense if you aren't already following someone.

This changes the action bar to look like:
screen shot 2015-12-03 at 6 10 43 pm

and the auto track is unchecked since not everything looked good.

@keybase/react-hackers

### CODE REVIEW

**Comment by chrisnojima** [comment]
lets not merge this until we can look at the wires and see what we decided in this scenario. i think we had something different than this

**Comment by chrisnojima** [comment]
@malgorithms let's discuss 2moro morning

**Comment by malgorithms** [comment]
yeah, we may never have covered it in the wires. not sure the visually correct answer, but what you end up doing in practice is putting into the tracker statement that you're ok with the broken one.

**Comment by chrisnojima** [comment]
I think we should maybe have a message that's like "this person has some
proofs we can't verify. Tracking will only trust verifiable proofs (or
something)

**Comment by cjb** [comment]
Just noticed this old PR still open -- do we still need to make progress on it?

**Comment by chrisnojima** [comment]
@malgorithms let's discuss this use case and what we should show. This pr has to be closed either way since the base branch has already been merged into master

**Comment by malgorithms** [comment]
Well, just like with the CLI, it should be possible to track someone even if 1 or more of their proofs is broken. But it shouldn't say "cbostrander added some identity proof" if you haven't tracked them before.

In the CLI I think we say something like "Some of foo's proofs couldn't be verified. Track the working proofs?"

**Pull request closed without merging**
