### PR TITLE
Visual tweaks on chat (2/2)

### PR DESCRIPTION
**Pull request by cecileboucheron**
…ment container

### CODE REVIEW

**Comment by keybase-ci-visdiff** [comment]
The commits ce0f90defd02...02129d541e43 introduce visual changes on linux. <details><summary>:mag_right: 6 changed</summary>

 * Changed: **Attachment_Message-Basic_Uploading** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486436969575-ce0f90defd02-02129d541e43-linux/Attachment_Message-Basic_Uploading-ce0f90defd02.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486436969575-ce0f90defd02-02129d541e43-linux/Attachment_Message-Basic_Uploading-02129d541e43.png)  
   Attachment_Message-Basic_Uploading comparison
 * Changed: **Attachment_Message-Basic_Generic_File_sent** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486436969575-ce0f90defd02-02129d541e43-linux/Attachment_Message-Basic_Generic_File_sent-ce0f90defd02.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486436969575-ce0f90defd02-02129d541e43-linux/Attachment_Message-Basic_Generic_File_sent-02129d541e43.png)  
   Attachment_Message-Basic_Generic_File_sent comparison
 * Changed: **Attachment_Message-Basic_Generic_File_Uploading** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486436969575-ce0f90defd02-02129d541e43-linux/Attachment_Message-Basic_Generic_File_Uploading-ce0f90defd02.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486436969575-ce0f90defd02-02129d541e43-linux/Attachment_Message-Basic_Generic_File_Uploading-02129d541e43.png)  
   Attachment_Message-Basic_Generic_File_Uploading comparison
 * Changed: **Attachment_Message-Basic_Generic_File_Failed** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486436969575-ce0f90defd02-02129d541e43-linux/Attachment_Message-Basic_Generic_File_Failed-ce0f90defd02.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486436969575-ce0f90defd02-02129d541e43-linux/Attachment_Message-Basic_Generic_File_Failed-02129d541e43.png)  
   Attachment_Message-Basic_Generic_File_Failed comparison
 * Changed: **Attachment_Message-Basic_Generic_File_Downloading** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486436969575-ce0f90defd02-02129d541e43-linux/Attachment_Message-Basic_Generic_File_Downloading-ce0f90defd02.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486436969575-ce0f90defd02-02129d541e43-linux/Attachment_Message-Basic_Generic_File_Downloading-02129d541e43.png)  
   Attachment_Message-Basic_Generic_File_Downloading comparison
 * Changed: **Attachment_Message-Basic_Generic_File_Downloaded** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486436969575-ce0f90defd02-02129d541e43-linux/Attachment_Message-Basic_Generic_File_Downloaded-ce0f90defd02.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486436969575-ce0f90defd02-02129d541e43-linux/Attachment_Message-Basic_Generic_File_Downloaded-02129d541e43.png)  
   Attachment_Message-Basic_Generic_File_Downloaded comparison
</summary>

**Comment by keybase-ci-visdiff** [comment]
The commits ce0f90defd02...02129d541e43 introduce visual changes on linux. <details><summary>:mag_right: 6 changed</summary>

 * Changed: **Attachment_Message-Basic_Uploading** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486517296459-ce0f90defd02-02129d541e43-linux/Attachment_Message-Basic_Uploading-ce0f90defd02.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486517296459-ce0f90defd02-02129d541e43-linux/Attachment_Message-Basic_Uploading-02129d541e43.png)  
   Attachment_Message-Basic_Uploading comparison
 * Changed: **Attachment_Message-Basic_Generic_File_sent** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486517296459-ce0f90defd02-02129d541e43-linux/Attachment_Message-Basic_Generic_File_sent-ce0f90defd02.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486517296459-ce0f90defd02-02129d541e43-linux/Attachment_Message-Basic_Generic_File_sent-02129d541e43.png)  
   Attachment_Message-Basic_Generic_File_sent comparison
 * Changed: **Attachment_Message-Basic_Generic_File_Uploading** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486517296459-ce0f90defd02-02129d541e43-linux/Attachment_Message-Basic_Generic_File_Uploading-ce0f90defd02.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486517296459-ce0f90defd02-02129d541e43-linux/Attachment_Message-Basic_Generic_File_Uploading-02129d541e43.png)  
   Attachment_Message-Basic_Generic_File_Uploading comparison
 * Changed: **Attachment_Message-Basic_Generic_File_Failed** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486517296459-ce0f90defd02-02129d541e43-linux/Attachment_Message-Basic_Generic_File_Failed-ce0f90defd02.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486517296459-ce0f90defd02-02129d541e43-linux/Attachment_Message-Basic_Generic_File_Failed-02129d541e43.png)  
   Attachment_Message-Basic_Generic_File_Failed comparison
 * Changed: **Attachment_Message-Basic_Generic_File_Downloading** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486517296459-ce0f90defd02-02129d541e43-linux/Attachment_Message-Basic_Generic_File_Downloading-ce0f90defd02.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486517296459-ce0f90defd02-02129d541e43-linux/Attachment_Message-Basic_Generic_File_Downloading-02129d541e43.png)  
   Attachment_Message-Basic_Generic_File_Downloading comparison
 * Changed: **Attachment_Message-Basic_Generic_File_Downloaded** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486517296459-ce0f90defd02-02129d541e43-linux/Attachment_Message-Basic_Generic_File_Downloaded-ce0f90defd02.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486517296459-ce0f90defd02-02129d541e43-linux/Attachment_Message-Basic_Generic_File_Downloaded-02129d541e43.png)  
   Attachment_Message-Basic_Generic_File_Downloaded comparison
</summary>

**Comment by cecileboucheron** [comment]
@keybase/react-hackers

**Comment by keybase-ci-visdiff** [comment]
The commits ce0f90defd02...c53541dd2f93 introduce visual changes on linux. <details><summary>:mag_right: 6 changed</summary>

 * Changed: **Attachment_Message-Basic_Uploading** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486593633253-ce0f90defd02-c53541dd2f93-linux/Attachment_Message-Basic_Uploading-ce0f90defd02.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486593633253-ce0f90defd02-c53541dd2f93-linux/Attachment_Message-Basic_Uploading-c53541dd2f93.png)  
   Attachment_Message-Basic_Uploading comparison
 * Changed: **Attachment_Message-Basic_Generic_File_sent** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486593633253-ce0f90defd02-c53541dd2f93-linux/Attachment_Message-Basic_Generic_File_sent-ce0f90defd02.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486593633253-ce0f90defd02-c53541dd2f93-linux/Attachment_Message-Basic_Generic_File_sent-c53541dd2f93.png)  
   Attachment_Message-Basic_Generic_File_sent comparison
 * Changed: **Attachment_Message-Basic_Generic_File_Uploading** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486593633253-ce0f90defd02-c53541dd2f93-linux/Attachment_Message-Basic_Generic_File_Uploading-ce0f90defd02.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486593633253-ce0f90defd02-c53541dd2f93-linux/Attachment_Message-Basic_Generic_File_Uploading-c53541dd2f93.png)  
   Attachment_Message-Basic_Generic_File_Uploading comparison
 * Changed: **Attachment_Message-Basic_Generic_File_Failed** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486593633253-ce0f90defd02-c53541dd2f93-linux/Attachment_Message-Basic_Generic_File_Failed-ce0f90defd02.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486593633253-ce0f90defd02-c53541dd2f93-linux/Attachment_Message-Basic_Generic_File_Failed-c53541dd2f93.png)  
   Attachment_Message-Basic_Generic_File_Failed comparison
 * Changed: **Attachment_Message-Basic_Generic_File_Downloading** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486593633253-ce0f90defd02-c53541dd2f93-linux/Attachment_Message-Basic_Generic_File_Downloading-ce0f90defd02.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486593633253-ce0f90defd02-c53541dd2f93-linux/Attachment_Message-Basic_Generic_File_Downloading-c53541dd2f93.png)  
   Attachment_Message-Basic_Generic_File_Downloading comparison
 * Changed: **Attachment_Message-Basic_Generic_File_Downloaded** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486593633253-ce0f90defd02-c53541dd2f93-linux/Attachment_Message-Basic_Generic_File_Downloaded-ce0f90defd02.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486593633253-ce0f90defd02-c53541dd2f93-linux/Attachment_Message-Basic_Generic_File_Downloaded-c53541dd2f93.png)  
   Attachment_Message-Basic_Generic_File_Downloaded comparison
</summary>

**Comment by keybase-ci-visdiff** [comment]
The commits ce0f90defd02...db05ecd5a611 introduce visual changes on linux. <details><summary>:mag_right: 9 changed</summary>

 * Changed: **Icon-Icon_Image** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486606690309-ce0f90defd02-db05ecd5a611-linux/Icon-Icon_Image-ce0f90defd02.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486606690309-ce0f90defd02-db05ecd5a611-linux/Icon-Icon_Image-db05ecd5a611.png)  
   Icon-Icon_Image comparison
 * Changed: **Chat_List-Normal** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486606690309-ce0f90defd02-db05ecd5a611-linux/Chat_List-Normal-ce0f90defd02.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486606690309-ce0f90defd02-db05ecd5a611-linux/Chat_List-Normal-db05ecd5a611.png)  
   Chat_List-Normal comparison
 * Changed: **Chat_List-Empty** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486606690309-ce0f90defd02-db05ecd5a611-linux/Chat_List-Empty-ce0f90defd02.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486606690309-ce0f90defd02-db05ecd5a611-linux/Chat_List-Empty-db05ecd5a611.png)  
   Chat_List-Empty comparison
 * Changed: **Attachment_Message-Basic_Uploading** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486606690309-ce0f90defd02-db05ecd5a611-linux/Attachment_Message-Basic_Uploading-ce0f90defd02.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486606690309-ce0f90defd02-db05ecd5a611-linux/Attachment_Message-Basic_Uploading-db05ecd5a611.png)  
   Attachment_Message-Basic_Uploading comparison
 * Changed: **Attachment_Message-Basic_Generic_File_sent** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486606690309-ce0f90defd02-db05ecd5a611-linux/Attachment_Message-Basic_Generic_File_sent-ce0f90defd02.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486606690309-ce0f90defd02-db05ecd5a611-linux/Attachment_Message-Basic_Generic_File_sent-db05ecd5a611.png)  
   Attachment_Message-Basic_Generic_File_sent comparison
 * Changed: **Attachment_Message-Basic_Generic_File_Uploading** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486606690309-ce0f90defd02-db05ecd5a611-linux/Attachment_Message-Basic_Generic_File_Uploading-ce0f90defd02.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486606690309-ce0f90defd02-db05ecd5a611-linux/Attachment_Message-Basic_Generic_File_Uploading-db05ecd5a611.png)  
   Attachment_Message-Basic_Generic_File_Uploading comparison
 * Changed: **Attachment_Message-Basic_Generic_File_Failed** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486606690309-ce0f90defd02-db05ecd5a611-linux/Attachment_Message-Basic_Generic_File_Failed-ce0f90defd02.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486606690309-ce0f90defd02-db05ecd5a611-linux/Attachment_Message-Basic_Generic_File_Failed-db05ecd5a611.png)  
   Attachment_Message-Basic_Generic_File_Failed comparison
 * Changed: **Attachment_Message-Basic_Generic_File_Downloading** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486606690309-ce0f90defd02-db05ecd5a611-linux/Attachment_Message-Basic_Generic_File_Downloading-ce0f90defd02.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486606690309-ce0f90defd02-db05ecd5a611-linux/Attachment_Message-Basic_Generic_File_Downloading-db05ecd5a611.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486606690309-ce0f90defd02-db05ecd5a611-linux/Attachment_Message-Basic_Generic_File_Downloading.png)
 * Changed: **Attachment_Message-Basic_Generic_File_Downloaded** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486606690309-ce0f90defd02-db05ecd5a611-linux/Attachment_Message-Basic_Generic_File_Downloaded-ce0f90defd02.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486606690309-ce0f90defd02-db05ecd5a611-linux/Attachment_Message-Basic_Generic_File_Downloaded-db05ecd5a611.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486606690309-ce0f90defd02-db05ecd5a611-linux/Attachment_Message-Basic_Generic_File_Downloaded.png)
</summary>

**Comment by keybase-ci-visdiff** [comment]
The commits ce0f90defd02...042f03ee2dc1 introduce visual changes on linux. <details><summary>:mag_right: 9 changed</summary>

 * Changed: **Icon-Icon_Image** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486668500632-ce0f90defd02-042f03ee2dc1-linux/Icon-Icon_Image-ce0f90defd02.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486668500632-ce0f90defd02-042f03ee2dc1-linux/Icon-Icon_Image-042f03ee2dc1.png)  
   Icon-Icon_Image comparison
 * Changed: **Chat_List-Normal** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486668500632-ce0f90defd02-042f03ee2dc1-linux/Chat_List-Normal-ce0f90defd02.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486668500632-ce0f90defd02-042f03ee2dc1-linux/Chat_List-Normal-042f03ee2dc1.png)  
   Chat_List-Normal comparison
 * Changed: **Chat_List-Empty** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486668500632-ce0f90defd02-042f03ee2dc1-linux/Chat_List-Empty-ce0f90defd02.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486668500632-ce0f90defd02-042f03ee2dc1-linux/Chat_List-Empty-042f03ee2dc1.png)  
   Chat_List-Empty comparison
 * Changed: **Attachment_Message-Basic_Uploading** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486668500632-ce0f90defd02-042f03ee2dc1-linux/Attachment_Message-Basic_Uploading-ce0f90defd02.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486668500632-ce0f90defd02-042f03ee2dc1-linux/Attachment_Message-Basic_Uploading-042f03ee2dc1.png)  
   Attachment_Message-Basic_Uploading comparison
 * Changed: **Attachment_Message-Basic_Generic_File_sent** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486668500632-ce0f90defd02-042f03ee2dc1-linux/Attachment_Message-Basic_Generic_File_sent-ce0f90defd02.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486668500632-ce0f90defd02-042f03ee2dc1-linux/Attachment_Message-Basic_Generic_File_sent-042f03ee2dc1.png)  
   Attachment_Message-Basic_Generic_File_sent comparison
 * Changed: **Attachment_Message-Basic_Generic_File_Uploading** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486668500632-ce0f90defd02-042f03ee2dc1-linux/Attachment_Message-Basic_Generic_File_Uploading-ce0f90defd02.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486668500632-ce0f90defd02-042f03ee2dc1-linux/Attachment_Message-Basic_Generic_File_Uploading-042f03ee2dc1.png)  
   Attachment_Message-Basic_Generic_File_Uploading comparison
 * Changed: **Attachment_Message-Basic_Generic_File_Failed** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486668500632-ce0f90defd02-042f03ee2dc1-linux/Attachment_Message-Basic_Generic_File_Failed-ce0f90defd02.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486668500632-ce0f90defd02-042f03ee2dc1-linux/Attachment_Message-Basic_Generic_File_Failed-042f03ee2dc1.png)  
   Attachment_Message-Basic_Generic_File_Failed comparison
 * Changed: **Attachment_Message-Basic_Generic_File_Downloading** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486668500632-ce0f90defd02-042f03ee2dc1-linux/Attachment_Message-Basic_Generic_File_Downloading-ce0f90defd02.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486668500632-ce0f90defd02-042f03ee2dc1-linux/Attachment_Message-Basic_Generic_File_Downloading-042f03ee2dc1.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486668500632-ce0f90defd02-042f03ee2dc1-linux/Attachment_Message-Basic_Generic_File_Downloading.png)
 * Changed: **Attachment_Message-Basic_Generic_File_Downloaded** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486668500632-ce0f90defd02-042f03ee2dc1-linux/Attachment_Message-Basic_Generic_File_Downloaded-ce0f90defd02.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486668500632-ce0f90defd02-042f03ee2dc1-linux/Attachment_Message-Basic_Generic_File_Downloaded-042f03ee2dc1.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486668500632-ce0f90defd02-042f03ee2dc1-linux/Attachment_Message-Basic_Generic_File_Downloaded.png)
</summary>

**Comment by keybase-ci-visdiff** [comment]
The commits ce0f90defd02...042f03ee2dc1 introduce visual changes on linux. <details><summary>:mag_right: 9 changed</summary>

 * Changed: **Icon-Icon_Image** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486674101811-ce0f90defd02-042f03ee2dc1-linux/Icon-Icon_Image-ce0f90defd02.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486674101811-ce0f90defd02-042f03ee2dc1-linux/Icon-Icon_Image-042f03ee2dc1.png)  
   Icon-Icon_Image comparison
 * Changed: **Chat_List-Normal** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486674101811-ce0f90defd02-042f03ee2dc1-linux/Chat_List-Normal-ce0f90defd02.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486674101811-ce0f90defd02-042f03ee2dc1-linux/Chat_List-Normal-042f03ee2dc1.png)  
   Chat_List-Normal comparison
 * Changed: **Chat_List-Empty** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486674101811-ce0f90defd02-042f03ee2dc1-linux/Chat_List-Empty-ce0f90defd02.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486674101811-ce0f90defd02-042f03ee2dc1-linux/Chat_List-Empty-042f03ee2dc1.png)  
   Chat_List-Empty comparison
 * Changed: **Attachment_Message-Basic_Uploading** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486674101811-ce0f90defd02-042f03ee2dc1-linux/Attachment_Message-Basic_Uploading-ce0f90defd02.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486674101811-ce0f90defd02-042f03ee2dc1-linux/Attachment_Message-Basic_Uploading-042f03ee2dc1.png)  
   Attachment_Message-Basic_Uploading comparison
 * Changed: **Attachment_Message-Basic_Generic_File_sent** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486674101811-ce0f90defd02-042f03ee2dc1-linux/Attachment_Message-Basic_Generic_File_sent-ce0f90defd02.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486674101811-ce0f90defd02-042f03ee2dc1-linux/Attachment_Message-Basic_Generic_File_sent-042f03ee2dc1.png)  
   Attachment_Message-Basic_Generic_File_sent comparison
 * Changed: **Attachment_Message-Basic_Generic_File_Uploading** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486674101811-ce0f90defd02-042f03ee2dc1-linux/Attachment_Message-Basic_Generic_File_Uploading-ce0f90defd02.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486674101811-ce0f90defd02-042f03ee2dc1-linux/Attachment_Message-Basic_Generic_File_Uploading-042f03ee2dc1.png)  
   Attachment_Message-Basic_Generic_File_Uploading comparison
 * Changed: **Attachment_Message-Basic_Generic_File_Failed** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486674101811-ce0f90defd02-042f03ee2dc1-linux/Attachment_Message-Basic_Generic_File_Failed-ce0f90defd02.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486674101811-ce0f90defd02-042f03ee2dc1-linux/Attachment_Message-Basic_Generic_File_Failed-042f03ee2dc1.png)  
   Attachment_Message-Basic_Generic_File_Failed comparison
 * Changed: **Attachment_Message-Basic_Generic_File_Downloading** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486674101811-ce0f90defd02-042f03ee2dc1-linux/Attachment_Message-Basic_Generic_File_Downloading-ce0f90defd02.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486674101811-ce0f90defd02-042f03ee2dc1-linux/Attachment_Message-Basic_Generic_File_Downloading-042f03ee2dc1.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486674101811-ce0f90defd02-042f03ee2dc1-linux/Attachment_Message-Basic_Generic_File_Downloading.png)
 * Changed: **Attachment_Message-Basic_Generic_File_Downloaded** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486674101811-ce0f90defd02-042f03ee2dc1-linux/Attachment_Message-Basic_Generic_File_Downloaded-ce0f90defd02.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486674101811-ce0f90defd02-042f03ee2dc1-linux/Attachment_Message-Basic_Generic_File_Downloaded-042f03ee2dc1.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486674101811-ce0f90defd02-042f03ee2dc1-linux/Attachment_Message-Basic_Generic_File_Downloaded.png)
</summary>

**Comment by keybase-ci-visdiff** [comment]
The commits 79f9c48d3acd...0801360b8680 introduce visual changes on linux. <details><summary>:mag_right: 9 changed</summary>

 * Changed: **Icon-Icon_Image** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486677071927-79f9c48d3acd-0801360b8680-linux/Icon-Icon_Image-79f9c48d3acd.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486677071927-79f9c48d3acd-0801360b8680-linux/Icon-Icon_Image-0801360b8680.png)  
   Icon-Icon_Image comparison
 * Changed: **Chat_List-Normal** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486677071927-79f9c48d3acd-0801360b8680-linux/Chat_List-Normal-79f9c48d3acd.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486677071927-79f9c48d3acd-0801360b8680-linux/Chat_List-Normal-0801360b8680.png)  
   Chat_List-Normal comparison
 * Changed: **Chat_List-Empty** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486677071927-79f9c48d3acd-0801360b8680-linux/Chat_List-Empty-79f9c48d3acd.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486677071927-79f9c48d3acd-0801360b8680-linux/Chat_List-Empty-0801360b8680.png)  
   Chat_List-Empty comparison
 * Changed: **Attachment_Message-Basic_Uploading** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486677071927-79f9c48d3acd-0801360b8680-linux/Attachment_Message-Basic_Uploading-79f9c48d3acd.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486677071927-79f9c48d3acd-0801360b8680-linux/Attachment_Message-Basic_Uploading-0801360b8680.png)  
   Attachment_Message-Basic_Uploading comparison
 * Changed: **Attachment_Message-Basic_Generic_File_sent** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486677071927-79f9c48d3acd-0801360b8680-linux/Attachment_Message-Basic_Generic_File_sent-79f9c48d3acd.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486677071927-79f9c48d3acd-0801360b8680-linux/Attachment_Message-Basic_Generic_File_sent-0801360b8680.png)  
   Attachment_Message-Basic_Generic_File_sent comparison
 * Changed: **Attachment_Message-Basic_Generic_File_Uploading** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486677071927-79f9c48d3acd-0801360b8680-linux/Attachment_Message-Basic_Generic_File_Uploading-79f9c48d3acd.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486677071927-79f9c48d3acd-0801360b8680-linux/Attachment_Message-Basic_Generic_File_Uploading-0801360b8680.png)  
   Attachment_Message-Basic_Generic_File_Uploading comparison
 * Changed: **Attachment_Message-Basic_Generic_File_Failed** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486677071927-79f9c48d3acd-0801360b8680-linux/Attachment_Message-Basic_Generic_File_Failed-79f9c48d3acd.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486677071927-79f9c48d3acd-0801360b8680-linux/Attachment_Message-Basic_Generic_File_Failed-0801360b8680.png)  
   Attachment_Message-Basic_Generic_File_Failed comparison
 * Changed: **Attachment_Message-Basic_Generic_File_Downloading** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486677071927-79f9c48d3acd-0801360b8680-linux/Attachment_Message-Basic_Generic_File_Downloading-79f9c48d3acd.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486677071927-79f9c48d3acd-0801360b8680-linux/Attachment_Message-Basic_Generic_File_Downloading-0801360b8680.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486677071927-79f9c48d3acd-0801360b8680-linux/Attachment_Message-Basic_Generic_File_Downloading.png)
 * Changed: **Attachment_Message-Basic_Generic_File_Downloaded** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486677071927-79f9c48d3acd-0801360b8680-linux/Attachment_Message-Basic_Generic_File_Downloaded-79f9c48d3acd.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486677071927-79f9c48d3acd-0801360b8680-linux/Attachment_Message-Basic_Generic_File_Downloaded-0801360b8680.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486677071927-79f9c48d3acd-0801360b8680-linux/Attachment_Message-Basic_Generic_File_Downloaded.png)
</summary>

**Pull request merged**
