### PR TITLE
iPad: Bring desktop-style split settings nav to iPad

### PR DESCRIPTION
**Pull request by cjb**
@keybase/react-hackers CC @keybase/design 

This PR harmonizes the Settings view between desktop and iPad.  Specifically:

* Git and Devices are moved into a new "More" tab with hamburger icon and desktop-style split subnav, replacing Settings, on both desktop and iPad.  Git and Devices are no longer main nav tabs anywhere now -- they were already subnavs of Settings on Phone, and now they are on iPad and Desktop too.
* Wallet is moved to the main nav on iPad.  It already was on Desktop.
* Phone is unaffected by all of this, so Wallet is still a More subnav item there.
* Badging: include Wallet badge number in More for Phone, don't include it for Desktop and iPad.

@chrisnojima, I know you've got a nav rework PR open affecting Git and Devices so I'll try to make this compatible with that.

Screenshots:

iPad: Bottom nav tabs changed to include Wallet and rename Settings to More, now uses new split-style subnav:

Screen Shot 2020-03-24 at 11 33 48 PM

iPad portrait:

Screen Shot 2020-03-24 at 11 33 50 PM

Desktop (Devices and Git are gone from the main subnav and moved inside More with the hamburger icon):

Screen Shot 2020-03-24 at 11 40 22 PM

Phone (unchanged):

Screen Shot 2020-03-24 at 11 21 42 PM

### CODE REVIEW

**Comment by jakob223** [comment]
We should also change the provisioning instructions to reflect the fact that devices is in a subnav.

**Comment by cecileboucheron** [comment]
@cjb 
• iPad looks great, can we make the settings side bar wider? 
• I don't think we should change desktop for now. We have a design ticket to explore ideas.

**Comment by thebearjew** [comment]
I also have a PR up for crypto tab on mobile. I can wait for this to merge, then rebase and resolve.
https://github.com/keybase/client/pull/23122
@cjb @cecileboucheron

**Comment by cjb** [comment]
@cecileboucheron @chrisnojima Thanks, backed out all the desktop changes and made the iPad nav wider.  Screenshot:

Screen Shot 2020-03-25 at 9 39 00 AM

**Comment by cecileboucheron** [comment]
@cjb Looks good! Any chance we can bring the nav icons, like on mobile? (sorry forgot to mention this in my previous comment)

**Comment by cjb** [comment]
@cecileboucheron Yep, done:

Screen Shot 2020-03-25 at 10 24 25 AM

**Comment by cecileboucheron** [comment]
👍🏻 lgtm!

**Comment by cjb** [comment]
thanks! @chrisnojima, ready for the JS review when you have time.

**Pull request merged**
