### PR TITLE
Fix log packaged

### PR DESCRIPTION
**Pull request by MarcoPolo**
we weren't forwarding the logs ever if it was a prod build, this lets us forward them now.

@keybase/react-hackers

### CODE REVIEW

**Comment by chrisnojima** [comment]
Why do we need fs extra?

**Comment by MarcoPolo** [comment]
https://github.com/keybase/client/blob/master/desktop/package.js#L11 maybe you had it installed globally?

**Comment by chrisnojima** [comment]
Hmm I forget. Maybe I deleted it by accident. I forget which api we needed.
I guess copy sync.

**Comment by chrisnojima** [comment]
:+1:

**Pull request merged**
