### PR TITLE
Run identifySelf on svc start, login

### PR DESCRIPTION
**Pull request by patrickxb**
There's a high probability that an identify on self will be needed in gui/mobile.  The default page on cold start is the user profile, and it's one of the top-level tabs throughout.

This patch runs identify on the self user when the service starts up and on login to prime the id cache.  It includes checking all the proofs as this is what GUI identify call does.

### CODE REVIEW

**Comment by maxtaco** [comment]
There already is something called the `FullSelfCacher`. A potential issue with his PR is that it throws away the result of `LoadUser` which might actually be useful.  I spent some time trying to tune that # of loads down to 1. This will increase it to 2.

**Comment by patrickxb** [comment]
Shouldn't identify2 use GetFullSelfer().WithSelf(...) then?

**Comment by patrickxb** [comment]
Also, identify2 uses upak loader, so wouldn't the Load be cached?

**Comment by maxtaco** [comment]
That might be a bad idea since it would have to hold the lock across
network calls.  Maybe there is no good way.

**Comment by maxtaco** [comment]
for a full identify with network calls it will fall back to the full user.  upak only on the fast path

**Pull request merged**
