### PR TITLE
renaming save secret option

### PR DESCRIPTION
**Pull request by chrisnojima**
@patrickxb from @malgorithms

### CODE REVIEW

**Comment by patrickxb** [comment]
is that cross-platform wording?  i know we don't have a secret store for anything except os x, but...

**Comment by chrisnojima** [comment]
AFAIK storing secrets on linux / etc is also a 'keychain'

**Comment by akalin-keybase** [comment]
I think we have a string in the platform-specific SecretStore implementations, so we should do that instead of hard-coding. I don't know if 'Keychain' is the right term for e.g. Android...

**Comment by akalin-keybase** [comment]
The function I was thinking of was `GetTerminalPrompt()` (which should really be renamed `GetSecretStoreTerminalPrompt()` so we can have `GetSecretStoreOptionLabel()` or something

**Comment by chrisnojima** [comment]
let's keep this simple and make the change for now. i don't think people will be confused (also: http://developer.android.com/reference/android/security/KeyChain.html)

**Comment by patrickxb** [comment]
sounds good.

**Pull request merged**
