### PR TITLE
fix broken install

### PR DESCRIPTION
**Pull request by chrisnojima**
Fixes the linux build (and others)

@keybase/react-hackers 

- [x] pointing to actual published version of node-framed-msg-pack since our pr was merged in. the old hash was deleted accidentally
- [x] moved shrinkpack into our deps. newer versions crash out

### CODE REVIEW

**Comment by cjb** [comment]
Tested that I can `npm i` on this branch on Linux successfully :thumbsup:

disturbing that newer shrinkpack is broken!

**Comment by chrisnojima** [comment]
well newer shrinkpack was having issues when i ran it, who knows. we def. don't need to be on the bleeding edge of that tool

**Comment by JamieMason** [comment]
@chrisnojima @cjb, really sorry that shrinkpack is causing you problems - would you mind opening an issue or describing here please what is happening? I'll do my best to get it fixed for you. Thanks.

**Comment by chrisnojima** [comment]
@JamieMason thanks for reaching out. I think shrinkpack is working, something was just messed up with our node_modules state which shrinkpack didn't like. i was firefighting and didn't want to dive into it further at the time but i've opened up this branch https://github.com/keybase/client/pull/4027 which updates us to the newest version which is working correctly. thanks!

**Pull request merged**
