### PR TITLE
Windows: Add icon for KBFS mount root

### PR DESCRIPTION
**Pull request by zanderz**
The Windows resource writing library didn't expose any way to add more than 1 icon, so we pulled in some of it. Should it have been forked instead?
image
@maxtaco @oconnor663

### CODE REVIEW

**Comment by zanderz** [comment]
Hi, ping. CircleCI failure is expected?

**Comment by oconnor663** [comment]
@zanderz do you have a minute to VC and help me understand what this resource library is doing?

**Comment by zanderz** [comment]
hi

**Comment by maxtaco** [comment]
ping @oconnor663 on the review

**Comment by oconnor663** [comment]
👍

**Pull request merged**
