### PR TITLE
Add waiting state to autoreset 'send again'

### PR DESCRIPTION
**Pull request by buoyad**
cc @keybase/y2ksquad 
send-again-waiting

### CODE REVIEW

**Comment by adamjspooner** [comment]
I'm not sure this is enough visual feedback. I proposed a green banner because you might miss the spinner. @cecileboucheron, do you have thoughts?

**Comment by buoyad** [comment]
I didn't see your proposal, there's a duplicate ticket. @adamjspooner what do you think of this spinner while in progress + a green banner at the top once it's done?

**Comment by buoyad** [comment]
With the banner:
send-again-waiting-banner

**Comment by adamjspooner** [comment]
Yup, this is great. 👍

**Pull request merged**
