### PR TITLE
Add stub for UnboxBytes32Any

### PR DESCRIPTION
**Pull request by patrickxb**
r? @maxtaco 

cc: @jzila

### CODE REVIEW

**Comment by maxtaco** [comment]
Random idea: Do you think KBFS might want to know which key worked for any reason?  Maybe the next RPC can be a direct unboxBytes32?

**Comment by patrickxb** [comment]
that's a good idea.  give me one min to add that.

**Comment by patrickxb** [comment]
Ok, added.

**Comment by maxtaco** [comment]
:+1: . There's a chance they might also ask for the *index* of the key in the array, but that depends on the code on the other side.  Anyways, can add that later if we need it?

**Comment by patrickxb** [comment]
Sure, I think this is enough to get started.

**Pull request merged**
