### PR TITLE
use UIDs, not usernames, for all internal teams machinery

### PR DESCRIPTION
**Pull request by maxtaco**
- upgrade AVDL TeamMember and TeamChangeReq to use UserVersions
- use UnmarshalJSON/MarshalJSON where possible
- various cleanups
- clean up chain parsing tests in chain_tests.go, and regenerate canned tests

### CODE REVIEW

**Comment by maxtaco** [comment]
Needs https://github.com/keybase/keybase/pull/1386 to pass CI.

@mlsteele you might want to take a look.  Hopefully it's not a grave conflict with your stuff.

**Comment by keybase-ci-visdiff** [comment]
The commits 58d2086310f0...801a3fb184c6 introduce visual changes on linux. <details><summary>:mag_right: 1 changed</summary>

 * Changed: **Tracker-New_user_Scroll_1** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1497240905872-58d2086310f0-801a3fb184c6-linux/Tracker-New_user_Scroll_1-58d2086310f0.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1497240905872-58d2086310f0-801a3fb184c6-linux/Tracker-New_user_Scroll_1-801a3fb184c6.png)  
   Tracker-New_user_Scroll_1 comparison
</summary>

**Comment by maxtaco** [comment]
BTW, passes locally for me when run against keybase/keybsae#1386

**Comment by keybase-ci-visdiff** [comment]
The commits 58d2086310f0...801a3fb184c6 introduce visual changes on linux. <details><summary>:mag_right: 1 changed</summary>

 * Changed: **Markdown-emoji** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1497274023359-58d2086310f0-801a3fb184c6-linux/Markdown-emoji-58d2086310f0.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1497274023359-58d2086310f0-801a3fb184c6-linux/Markdown-emoji-801a3fb184c6.png)  
   Markdown-emoji comparison
</summary>

**Pull request merged**
