### PR TITLE
only run updater on darwin and windows

### PR DESCRIPTION
**Pull request by songgao**
This should fix the spamming error message about updater on Linux.

### CODE REVIEW

**Comment by chrisnojima** [comment]
can i get come core sanity checks of this
cc: @patrickxb @mmaxim @zanderz @keybase/react-hackers

**Comment by chrisnojima** [comment]
@cjb

**Comment by heronhaye** [comment]
I can still repro with `chat api-listen`... @zapu, can you?

**Comment by zanderz** [comment]
LGTM - couldn't add my self as official GH reviewer

**Comment by patrickxb** [comment]
(I didn't try it like @heronhaye but change looks fine)

**Comment by songgao** [comment]
Talked to @heronhaye on chat. Merging!

**Pull request merged**
