### PR TITLE
you can just pass the path

### PR DESCRIPTION
**Pull request by chrisnojima**
@maxtaco pointed out we can just pass the path, waay better than https://github.com/keybase/client/pull/1378

@cjb

### CODE REVIEW

**Comment by cjb** [comment]
@chrisnojima @maxtaco @oconnor663 The reason I went with an array of search paths for the socketfile directory is that the service itself uses an array of search paths, falling back to `$HOME` if the `$XDG_*` variables are undefined on Linux:

https://github.com/keybase/client/blob/f1da498b176bcfe5793eedb6893f6f2c5890ba76/go/libkb/home.go#L64

An array lets us support that; choosing one static path doesn't.

So merging this PR without changing the dynamism in the service doesn't seem like the right idea.  I wonder if we could just stop using the `$XDG_` dirs on Linux.  I saw the point when we wanted ephemeral FS semantics from `$XDG_RUNTIME_DIR`, but now we don't anymore.  Anything wrong with `$HOME/.keybase` for all of our dirs?

Any other ideas?

**Comment by cjb** [comment]
It looks like Windows uses even more fallbacks than Linux ($APPDATA, $TEMP), so the change I just suggested doesn't seem to solve the problem of needing search paths.

**Comment by chrisnojima** [comment]
ok so given a single run we can only have one path (given the IRL conversation @maxtaco @cjb and I just had so this code is good i think. I'll make a ticket to expand the path lookup to match go

**Comment by chrisnojima** [comment]
https://keybase.atlassian.net/browse/DESKTOP-89

**Comment by cjb** [comment]
:thumbsup:

**Pull request merged**
