### PR TITLE
client: cmd_pgp_gen: add usernames to all emails

### PR DESCRIPTION
**Pull request by arjunravinarayan**
Closes keybase/keybase-issues#2446.

---
This change is [Reviewable](https://reviewable.io/reviews/keybase/client/3694)

### CODE REVIEW

**Comment by gabriel** [comment]
Circle CI failure is my fault. Fixing in master now.

**Comment by arjunravinarayan** [comment]
LMK which commit to rebase off of and force push.

**Comment by gabriel** [comment]
ok fixed in master

**Comment by arjunravinarayan** [comment]
Looks like the test succeeded, but failed on `uploadApp.sh` due to a lack of credentials. PTAL.

**Comment by cjb** [comment]
@arjunravinarayan ah, that's because it only gives the credentials to PRs written by team members (since otherwise you could gain access to them on your branch).  So don't worry about the test failures -- whoever reviews this change should perhaps open a new PR themselves in order to get a full test run to happen.

**Comment by arjunravinarayan** [comment]
That makes sense off your current workflow. However, it doesn't look like you're using appetize.io for any unit testing. You should probably change your circle.yml` to move the final `uploadApp.sh` from the `test` section to the [`deployment` section](https://circleci.com/docs/configuration/#deployment), so that external contributors can see green builds. It has to be reviewed and merged by a team member anyway, why add more overhead in accepting external PRs beyond the single click merge?

I'm happy to write more code if it's welcome. (Do you want to add a CLA for copyright ownership over external commits?)

**Comment by cjb** [comment]
@arjunravinarayan circleci actually does very limited testing for us -- we've also got a Jenkins setup that does a lot more, but it refuses to even begin a test of a PR from an unverified author (due to the same attack).

So, fixing the circle.yml sounds good, but isn't sufficient to make external contributor PRs mergeable as-is.  You're right that this is something we should work on to streamline the process.  So far we haven't got many public PRs.  :-)

(I think CLAs sound like unnecessary overhead for us, but that's a personal opinion, we haven't discussed it as a company yet.)

**Comment by maxtaco** [comment]
@patrickxb : can you review this?  thanks!

**Comment by maxtaco** [comment]
Actually LGTM.  I have a new PR here: https://github.com/keybase/client/pull/3838 to run through CI

**Pull request merged**
