### PR TITLE
Save/restore state (include dock), hide on start option

### PR DESCRIPTION
**Pull request by gabriel**
This allows us to restore app state (window visibility) properly.

### CODE REVIEW

**Comment by gabriel** [comment]
@keybase/react-hackers

**Comment by cjb** [comment]
Sorry, don't understand why this PR results in being able to restore window state properly.

**Comment by gabriel** [comment]
When the app starts the main window could be visible or hidden. The dock icon should be shown in either case. 

In the past we had logic to show and hide the dock icon depending of if the main window was shown, now we always show the dock icon, until they close the main part of the app.

**Comment by patrickxb** [comment]
If I quit the app (I know it doesn't really quit it...) via file->quit, cmd-q, the dock icon goes away.

I don't think it should come back if the app restarts automatically (say via an update).

**Comment by gabriel** [comment]
Yeah that fix is coming in another PR.

**Comment by gabriel** [comment]
I need this fix, otherwise the dock icon won't display when we re-launch after update and main window is hidden on start, which is a bug.

**Comment by cjb** [comment]
Both of these paragraphs describe the new behavior after applying this PR; but I could already see that by reading the code.  I was asking for something else: a description of *why* we need to make this behavior change.

> When the app starts the main window could be visible or hidden. The dock icon should be shown in either case.

That's not intuitive, right?  You'd expect the dock icon to be shown in the visible case and not shown in the hidden case.  So why is the counter-intuitive behavior necessary?

> In the past we had logic to show and hide the dock icon depending of if the main window was shown, now we always show the dock icon, until they close the main part of the app.

Why is that better?

**Comment by gabriel** [comment]
OK so:

- (1) On start, if main window is not visible, we show dock icon
- (2) On start, if main window is not visible, we don't show dock icon

It is possible the user was in either state before quiting. Either they closed main window and dock icon was still visible or they cmd+Q and dock icon wasn't visible.

I guess the right solution is to store the dock icon visiiblity in app state and restore that way too. That way the app is restored exactly as it was before quit/update.

**Comment by gabriel** [comment]
OK, thanks for the feedback. The fact that we weren't keeping track of dock visibility in `AppState` was also a problem.

I've changed this PR to be able to save and restore the dock visibility (if `KEYBASE_RESTORE_UI` is boolish, which will be set on updates) in another PR coming next.

To test restore `KEYBASE_RESTORE_UI=true npm start`.
To test without restore: `npm start`.
To test restore from app open: `KEYBASE_RESTORE_UI=true open /Applications/Keybase.app`

@MarcoPolo I changed the default dock visibility to true, hence the `isDockVisible = false` to `isDockHidden = false`. Dock visibility is now true by default (in the past it was false because we were menubar only).

**Comment by gabriel** [comment]
Also I'm a little uneasy about us maintaining dock visibility state (it could get out of sync if someone uses the app.dock API directly), so I made an PR here to get that from Electron itself here: https://github.com/electron/electron/pull/6683

**Comment by patrickxb** [comment]
Seems like having two apps would simplify all this...would get a lot for free.

**Comment by gabriel** [comment]
I think it's ok to be a single app, and has some benefits. If we had 2 apps we'd have some complexity around managing (UI) state and concurrency across the main window and menubar that is probably worse than having to manage the dock icon.

Also my concern about us managing dock visibility in `./dock-icon` isn't really too scary, we just have to be careful not to use `app.dock` APIs directly which we won't, and that PR will get merged eventually so it's all good.

**Comment by MarcoPolo** [comment]
@gabriel your electron PR got merged, want to update this to use that instead?

**Comment by gabriel** [comment]
We'll need to wait for next release, but it looks like they might release soon? (Schedule looks weekly).

I guess I'll hold off for a little bit to see.

**Comment by gabriel** [comment]
@chromakode `KEYBASE_START_UI=hideWindow` for linux boot

**Comment by gabriel** [comment]
Electron just got a new release.. Updating that first in a separate PR.

**Comment by gabriel** [comment]
Ok, using Electron 1.3.2 and `app.dock.isVisible()`... works well :)

**Comment by MarcoPolo** [comment]
👍

**Pull request merged**
