### PR TITLE
never block on anything firehose related

### PR DESCRIPTION
**Pull request by mmaxim**

### CODE REVIEW

**Comment by maxtaco** [comment]
If there was a reason to have these in the foreground, i forget....

**Comment by mmaxim** [comment]
It seems like Electron gets force slept by macOS in some circumstances so these calls block forever in that case. It seems better to queue them up in `NotifyRouter` land than on the critical path of this broadcast handler.

**Comment by mmaxim** [comment]
Or I guess this is just a normal UI RPC, so it would be queued up in a goroutine. I guess there is a downside they get out of ordered...

**Comment by mmaxim** [comment]
Could have a single goroutine firing them off I guess reading from a channel...

**Comment by mmaxim** [comment]
Not going to merge this

**Pull request closed without merging**
