### PR TITLE
Don't log push notification payload

### PR DESCRIPTION
**Pull request by buoyad**
This could contain sensitive data. r? @keybase/react-hackers

### CODE REVIEW

**Comment by mmaxim** [comment]
Oh this is the frontend

**Comment by buoyad** [comment]
@mmaxim a plaintext snippet of mine was logged

**Comment by mmaxim** [comment]
I still don’t think there is anything in there

**Comment by buoyad** [comment]
What do you mean?

**Comment by mmaxim** [comment]
Don’t you just have the encrypted payload there?

**Comment by akalin-keybase** [comment]
Hmm...that line seems to have been there forever.

**Comment by buoyad** [comment]
@mmaxim In the log [here](https://keybase.io/_/admin/logdump_viewer?738721851#8707c619471f20b53b177c1c) grep for `explode`

**Comment by mmaxim** [comment]
I’m not even sure this code runs for iOS, maybe if you tap it?

**Comment by mmaxim** [comment]
I’m on my phone I can’t grip anything

**Pull request merged**
