### PR TITLE
styling fixes

### PR DESCRIPTION
**Pull request by chrisnojima**
fixing weird whitespacing. removing margin from body. sizing tracker correctly in standalone. added font awesome to standalone

@keybase/react-hackers

### CODE REVIEW

**Comment by cjb** [comment]
@chrisnojima on Linux:

screenshot from 2015-12-01 11-58-43

**Comment by cjb** [comment]
I've seen the "Loading..." rendered instead of the footer component on OS X now too, though it was for a weird call to identify from KBFS.  (It's spamming us with identify calls at the moment, see KBFS-520.)

**Comment by cjb** [comment]
:thumbsup:

**Comment by chrisnojima** [comment]
I think we don't check ids of incoming calls so they can get routed to the
wrong Windows

**Comment by MarcoPolo** [comment]
:+1:

**Pull request merged**
