### PR TITLE
factor out proof support into a different directory (externals)

### PR DESCRIPTION
**Pull request by maxtaco**
- move some tests over too, since some of the libkb tests depends on external services
- initialize g.Services properly depending on context
- fixup tests, which all pass now

### CODE REVIEW

**Comment by patrickxb** [comment]
Can libkb.ProofError move too?

**Comment by maxtaco** [comment]
Some things from libkb still need it

**Comment by maxtaco** [comment]
FYI: @akalin-keybase, when this fix goes in, the `AssertionParseAndOnly`, `IsSocialAssertion` and `NormalizeSocialAssertions` will be available as before, but in `keybase/client/go/externals`

**Comment by maxtaco** [comment]
The circle-CI job will fail until we update KBFS accordingly (as suggested above)

**Comment by patrickxb** [comment]
LGTM

**Comment by maxtaco** [comment]
Merged by hand. Oh well. :(

**Pull request closed without merging**
