### PR TITLE
implement TlfVisibility filter on GetInbox

### PR DESCRIPTION
**Pull request by songgao**

### CODE REVIEW

**Comment by mmaxim** [comment]
Should there be a test for this?

**Comment by mmaxim** [comment]
@songgao what do you think about a test for this one?

**Comment by songgao** [comment]
Oops sorry Mike I missed your last comment. I'll add some tests in the morning!

**Comment by songgao** [comment]
@mmaxim so we don't really have a way to construct public conversation at client side yet. (We'd need to change TlfCryptKeys to also take a `isPrivate` parameters.) So there's not much to test in service for now, except that it's correctly passing the `TlfVisibility` parameter. Do you think we can have a separate ticket for finishing the implementation in client and add test in that ticket?

**Comment by mmaxim** [comment]
Sounds fine!

**Comment by songgao** [comment]
Thanks!

**Pull request merged**
