### PR TITLE
Fork npipe for dial bug fix

### PR DESCRIPTION
**Pull request by zanderz**
Demo program still pending before the npipe pull request is submitted to the package author. Again, this was the reason one out of every 15 or so CLI commands would fail.
@maxtaco @oconnor663

### CODE REVIEW

**Comment by oconnor663** [comment]
Where's the retry loop in question?

**Comment by maxtaco** [comment]
How about the bugfix in which you change `isPipeNotReady` to return `true` on the `INVALID HANDLE` error?  Why is this fix better than that fix?

**Comment by zanderz** [comment]
Jack: After looking for the 85th time I decided to also test for error_sem_timeout.  The loop in question, in the calling function, is [here](https://github.com/keybase/client/blob/zanderz/CORE-2952/go/vendor/github.com/keybase/npipe/npipe_windows.go#L130).

Max: There must have been some crossed wires; maybe I discussed such a solution back when I thought it was CreateFile() that was returning invalid handle in the bug case, but it turned out to be waitNamedPipe(). Changing it like you say would allow an invalid handle result from CreateFile() instead of breaking out of the calling wait loop, a scenario I haven't tested thoroughly, like this one. But I could start over with that if you prefer.

**Comment by maxtaco** [comment]
In my proposed fix, you error out of `dial()` but don't break out of the loop `DialTimeout` and will try again.  I guess I'm assuming you won't get a bad handle error the next time on `waitNamedPipe`

Your solution makes me a bit nervous because I don't know if it's OK, by the logic of this library, to call `CreateFile` without `waitNamedPipe` having succeeded.  Clearly they were trying to handle some case that we're paving right over.

**Comment by patrickxb** [comment]
Have you tried `Dial()` instead of `DialTimeout()`?

**Comment by zanderz** [comment]
Patrick: Dial() waits indefinitely; I switched to DialTimeout so a client could exit quickly if there was no server and it wasn't spawning one.

About the CreateFile/WaitNamedPipe order: I refer you to MSDN documentation showing CreateFile first: https://msdn.microsoft.com/en-us/library/windows/desktop/aa365592%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396

My own hunch about calling WaitNamedPipe first is so this package can return bad pipe name errors, and prevent you from opening a file if you send in such a path, but it's just a guess. And possibly WaitNamedPipe didn't return bad handle on earlier Windows - also a guess.

**Comment by patrickxb** [comment]
Yes, I saw that, but it looks much more straightforward.  Could handle the timeout on our side.

Just a thought, not trying to add work...

**Comment by maxtaco** [comment]
I don't want you to have to go through all of the testing again, I'm OK to leave it, though it makes my nervous that we're letting through any error that were previously caught.

BTW, are you going to upstream this patch?

**Comment by zanderz** [comment]
OK I tried this a few hundred times and I think it addresses both Max's concern and my concern with treating bad handle as a pipeNotReady condition. What do you think of this one?

Patrick: how do you timeout a blocking call like that? Won't that goroutine be orphaned or something>

**Comment by maxtaco** [comment]
👍

**Pull request merged**
