### PR TITLE
Update font icons

### PR DESCRIPTION
**Pull request by MarcoPolo**
@keybase/react-hackers

### CODE REVIEW

**Comment by chrisnojima** [comment]
I'm working on the ticket to update the icons now. If this is just updating
the font can we leave that out

**Comment by MarcoPolo** [comment]
Cool, this also fixes the todos for icons in search. I'll leave this open until you merge your stuff and rebase off that

**Comment by keybase-ci-visdiff** [comment]
:mag_right: The commits 5d583ba7bf72...90826fd52281 introduced some visual changes on linux:
 * Changed: **user_search-Normal** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1467155579111-5d583ba7bf72-90826fd52281-linux/user_search-Normal-5d583ba7bf72.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1467155579111-5d583ba7bf72-90826fd52281-linux/user_search-Normal-90826fd52281.png)  
   user_search-Normal comparison
 * Changed: **user_group-Chat_enabled** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1467155579111-5d583ba7bf72-90826fd52281-linux/user_group-Chat_enabled-5d583ba7bf72.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1467155579111-5d583ba7bf72-90826fd52281-linux/user_group-Chat_enabled-90826fd52281.png)  
   user_group-Chat_enabled comparison

**Comment by cjb** [comment]
retest this please

**Comment by keybase-ci-visdiff** [comment]
:mag_right: The commits dc3f5a6bd786...1d21699c48e7 introduced some visual changes on linux:
 * Changed: **user_search-Normal** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1467207004744-dc3f5a6bd786-1d21699c48e7-linux/user_search-Normal-dc3f5a6bd786.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1467207004744-dc3f5a6bd786-1d21699c48e7-linux/user_search-Normal-1d21699c48e7.png)  
   user_search-Normal comparison
 * Changed: **user_group-Chat_enabled** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1467207004744-dc3f5a6bd786-1d21699c48e7-linux/user_group-Chat_enabled-dc3f5a6bd786.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1467207004744-dc3f5a6bd786-1d21699c48e7-linux/user_group-Chat_enabled-1d21699c48e7.png)  
   user_group-Chat_enabled comparison

**Comment by keybase-ci-visdiff** [comment]
:mag_right: The commits dc3f5a6bd786...f7bbff1fbfd7 introduced some visual changes on win32:
 * Changed: **user_search-Normal** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1467207119802-dc3f5a6bd786-f7bbff1fbfd7-win32/user_search-Normal-dc3f5a6bd786.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1467207119802-dc3f5a6bd786-f7bbff1fbfd7-win32/user_search-Normal-f7bbff1fbfd7.png)  
   user_search-Normal comparison
 * Changed: **user_group-Chat_enabled** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1467207119802-dc3f5a6bd786-f7bbff1fbfd7-win32/user_group-Chat_enabled-dc3f5a6bd786.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1467207119802-dc3f5a6bd786-f7bbff1fbfd7-win32/user_group-Chat_enabled-f7bbff1fbfd7.png)  
   user_group-Chat_enabled comparison

**Comment by keybase-ci-visdiff** [comment]
:mag_right: The commits dc3f5a6bd786...f7bbff1fbfd7 introduced some visual changes on linux:
 * Changed: **user_search-Normal** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1467207337771-dc3f5a6bd786-f7bbff1fbfd7-linux/user_search-Normal-dc3f5a6bd786.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1467207337771-dc3f5a6bd786-f7bbff1fbfd7-linux/user_search-Normal-f7bbff1fbfd7.png)  
   user_search-Normal comparison
 * Changed: **user_group-Chat_enabled** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1467207337771-dc3f5a6bd786-f7bbff1fbfd7-linux/user_group-Chat_enabled-dc3f5a6bd786.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1467207337771-dc3f5a6bd786-f7bbff1fbfd7-linux/user_group-Chat_enabled-f7bbff1fbfd7.png)  
   user_group-Chat_enabled comparison

**Pull request closed without merging**
