### PR TITLE
Do all provisioning work in one transaction

### PR DESCRIPTION
**Pull request by maxtaco**
- This should fully prevent half-provisions
- Strip out some dead code here and there
- contextify SKB interface

### CODE REVIEW

**Comment by maxtaco** [comment]
@patrickxb can you take a look?

While testing I created a whole bunch more half-provisioned scenarios.  Basically if you ever cancel out of a login/provision path, you'd wind up in an unexpected state.  I think this is a pretty blunt solution to all of our problems. Let me know if you think it breaks anything. I did some minimal testing, and I need to do some more.

**Comment by patrickxb** [comment]
Seems like a good idea.  I can't think of anything that would break with this in place, but it would be nice if we could have a test that fails without this.  Could probably be done with a test ui that cancels the provisioning flow at some point after a config file is written with the device ID.

**Comment by maxtaco** [comment]
As usual, 3x more work to do the test than fix the bug.

**Comment by maxtaco** [comment]
I tried a bunch of hours to make a test to do this but failed (though it's quite easy to get stuck here by just interacting with the client).  In general, we need to fail after the `device_id` field is set in the config file (as you say above).  I think I got into this fix when I canceled out of GPG's pinentry during signing. Suggestions for how to simulate this in a test?  We'd need GPGKey::Sign to fail.  There might be earlier places to fail that would work just as well, open to suggestions.

**Comment by maxtaco** [comment]
Nevermind, I see it. My 10th attempt will work!

**Comment by maxtaco** [comment]
Ok, have something in this branch that passes here and fails on master.

**Pull request merged**
