### PR TITLE
WIP: Less thread jumping

### PR DESCRIPTION
**Pull request by chrisnojima**
- [x] Lock to bottom/jump to bottom on send
- [x] Only throw away single cache row height instead of all
- [x] Update react-virtualized
- [x] Only use componentDidUpdate
- [x] Debounce scroll handler for lockToBottom. Without this the new items will cause a callback before it comes, during, and after which causes the state to thrash on/off/on etc

### CODE REVIEW

**Comment by chrisnojima** [comment]
actually moving this back into a wip

**Comment by chrisnojima** [comment]
ok this is ready again. please actually test this in real convos

**Comment by mmaxim** [comment]
Best way to test this is to just create a thread with a bunch of markdown and attachments. Those are usually the ones I see this behavior in. Like make a thread with this interesting stuff in it, then have a test account send messages into it. 

Is this supposed to fix the thread jumping around if you are scrolled up and new messages are coming in?

**Comment by chrisnojima** [comment]
It should

**Comment by chrisnojima** [comment]
@keybase/react-hackers

**Comment by adamjspooner** [comment]
I've been running this branch for part of the day, and `#core` was still very jumpy for me with all activity this afternoon. It was _way_ better, but some jumps still happened. E.g., I was scrolling up to read messages I'd missed, a message came in, and I was jumped to the bottom. I was one message up from the end on a very large MySQL code block when it jumped.

**Comment by chrisnojima** [comment]
I'm not going I merge this if the measurement stuff is messed. I think the
jump stuff also relies on the removal of the throttle

**Comment by chrisnojima** [comment]
not worth debuging react virutalized anymore, just not good for our problem

**Pull request closed without merging**
