### PR TITLE
Handle team.clkr messages in service, rotate team keys

### PR DESCRIPTION
**Pull request by patrickxb**
This patch adds a gregor handler for team messages and handles the team.clkr message that requests team key rotation.

Some refactoring of the existing code to make it all fit together nicely.

There are tests of the Rotate function and handling rotate requests, one with a generation that should cause a rotate, one with a generation that shouldn't.

There is no end-to-end test that something like a device revoke ends up causing a team.clkr message.  I believe this is well tested on the api server side, and gregor message delivery is known to work.  I did test by hand and it worked.

### CODE REVIEW

**Comment by keybase-ci-visdiff** [comment]
The commits f903feeb938b...3576b8ad4a08 introduce visual changes on linux. <details><summary>:mag_right: 1 changed</summary>

 * Changed: **Tracker-New_user_Scroll_1** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1497038605315-f903feeb938b-3576b8ad4a08-linux/Tracker-New_user_Scroll_1-f903feeb938b.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1497038605315-f903feeb938b-3576b8ad4a08-linux/Tracker-New_user_Scroll_1-3576b8ad4a08.png)  
   Tracker-New_user_Scroll_1 comparison
</summary>

**Comment by keybase-ci-visdiff** [comment]
The commits bb4eba441b79...31af6bb6285e introduce visual changes on linux. <details><summary>:mag_right: 1 changed</summary>

 * Changed: **Tracker-New_user_Scroll_1** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1497293840782-bb4eba441b79-31af6bb6285e-linux/Tracker-New_user_Scroll_1-bb4eba441b79.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1497293840782-bb4eba441b79-31af6bb6285e-linux/Tracker-New_user_Scroll_1-31af6bb6285e.png)  
   Tracker-New_user_Scroll_1 comparison
</summary>

**Comment by patrickxb** [comment]
@maxtaco check out new test

Also, to do the test, I added notification for team key rotate to notify router.

@keybase/react-hackers i need some flow help.  new notify type.

**Comment by chrisnojima** [comment]
looking

**Comment by chrisnojima** [comment]
- [x] fixed flow

**Comment by keybase-ci-visdiff** [comment]
The commits bb4eba441b79...fe051492b4d6 introduce visual changes on linux. <details><summary>:mag_right: 1 changed</summary>

 * Changed: **Tracker-New_user_Scroll_1** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1497318014925-bb4eba441b79-fe051492b4d6-linux/Tracker-New_user_Scroll_1-bb4eba441b79.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1497318014925-bb4eba441b79-fe051492b4d6-linux/Tracker-New_user_Scroll_1-fe051492b4d6.png)  
   Tracker-New_user_Scroll_1 comparison
</summary>

**Pull request merged**
