### PR TITLE
pass breaksTracking bool on all incremental updates

### PR DESCRIPTION
**Pull request by maxtaco**

### CODE REVIEW

**Comment by maxtaco** [comment]
@keybase/react-hackers is this what you had in mind?  happy to tweak as you need it...

**Comment by maxtaco** [comment]
@keybase/react-hackers, hold off a few things to fix...

**Comment by maxtaco** [comment]
Ok, ready for a look...

**Comment by chrisnojima** [comment]
let's try it :+1:

**Pull request merged**
