### PR TITLE
add new CAs

### PR DESCRIPTION
**Pull request by songgao**

### CODE REVIEW

**Comment by maxtaco** [comment]
It's OK with me if it's OK with @mmaxim

**Comment by mmaxim** [comment]
I thought we were going to bundle the old and new CA?

**Comment by maxtaco** [comment]
I think I see them both.

**Comment by songgao** [comment]
Yeah this PR only adds new but doesn't remove the old ones. @mmaxim Anything wrong you saw there?

**Comment by songgao** [comment]
Is this good to merge? @maxtaco @mmaxim

**Pull request merged**
