### PR TITLE
Make <Input autocorrect={false}/> work and hook up to signup

### PR DESCRIPTION
**Pull request by cjb**
@keybase/react-hackers 

It looks like we didn't support autoCorrect on &lt;Input /&gt; at all, so I hooked that up.  Is there a shorter way to do the test?  Originally I wanted to do:
```js
           autoCorrect={this.props.autoCorrect || (!(password || passwordVisible))}
```
which doesn't work 'cause `this.props.autoCorrect` will evaluate false both when it's not been passed, and when it's been explicitly set to false to disable autoCorrect.

### CODE REVIEW

**Comment by chrisnojima** [comment]
mmm don't think so. you need hasOwnProps to capture if its set or not

**Comment by chrisnojima** [comment]
i wonder if we should set it to default to false actually

**Comment by chrisnojima** [comment]
@malgorithms thinks this makes sense. lets just do that too since we're in there. places where it should be on: full name, bio, location, paperkey entry

**Comment by cjb** [comment]
@chrisnojima Done!  Take a look?

**Comment by cjb** [comment]
Oh you just did, cool.

**Comment by gabriel** [comment]
We should double check paper key input for this doesn't go into an autocorrect or spelling dictionary on the device... Might be safer not to do this at all.

Scenario: Spanish keyboard, all the words don't match dictionary and get put in. Other app inspects dictionary to extract non-spanish words being showed in autocorrect.

In v2 or v3, we could do our own autocorrect from this where the corpus is the list of words we support :)

**Comment by malgorithms** [comment]
@gabriel  sounds reasonable to me.

**Pull request merged**
