### PR TITLE
Merge notification userInfo field

### PR DESCRIPTION
**Pull request by akalin-keybase**
This handles the Android plaintext notification case.

### CODE REVIEW

**Comment by mmaxim** [comment]
Does this break iOS?

**Comment by akalin-keybase** [comment]
I don't think so, although I'll double check. On iOS there's nothing in `userInfo`, so it'll work the same as before.

**Comment by akalin-keybase** [comment]
Yeap, verified that clicking on a plaintext notification in iOS still works.

**Pull request merged**
