### PR TITLE
Search bug fixes / refactors

### PR DESCRIPTION
**Pull request by chrisnojima**
@keybase/react-hackers

### CODE REVIEW

**Comment by chrisnojima** [comment]
Replaces https://github.com/keybase/client/pull/3414

**Comment by MarcoPolo** [comment]
anything diff from #3414?

**Comment by chrisnojima** [comment]
Really just a rebase of master and squish, no new logic

**Comment by MarcoPolo** [comment]
👍

**Comment by keybase-ci-visdiff** [comment]
:mag_right: The commits 853b1164e641...48814d234e0c introduced some visual changes on linux:
 * Added: **Search-Searching**  
   Search-Searching rendered
 * Added: **Search-Group_non_user_Out_of_invites**  
   Search-Group_non_user_Out_of_invites rendered
 * Added: **Search-Group_non_user_No_Avatar**  
   Search-Group_non_user_No_Avatar rendered
 * Added: **Search-Group_non_user_Has_Invite**  
   Search-Group_non_user_Has_Invite rendered
 * Added: **Search-Group_non_user**  
   Search-Group_non_user rendered
 * Added: **Search-Group**  
   Search-Group rendered
 * Added: **Search-Coming_soon**  
   Search-Coming_soon rendered
 * Added: **Search-Chat_enabled** [(view)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Search-Chat_enabled-48814d234e0c.png)
 * Changed: **Tracker-You_track_them** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Tracker-You_track_them-853b1164e641.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Tracker-You_track_them-48814d234e0c.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Tracker-You_track_them.png)
 * Changed: **Tracker-Whatevz** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Tracker-Whatevz-853b1164e641.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Tracker-Whatevz-48814d234e0c.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Tracker-Whatevz.png)
 * Changed: **Tracker-Unfollowed** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Tracker-Unfollowed-853b1164e641.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Tracker-Unfollowed-48814d234e0c.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Tracker-Unfollowed.png)
 * Changed: **Tracker-Platforms** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Tracker-Platforms-853b1164e641.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Tracker-Platforms-48814d234e0c.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Tracker-Platforms.png)
 * Changed: **Tracker-Only_one_proof** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Tracker-Only_one_proof-853b1164e641.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Tracker-Only_one_proof-48814d234e0c.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Tracker-Only_one_proof.png)
 * Changed: **Tracker-New_user_follows_me** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Tracker-New_user_follows_me-853b1164e641.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Tracker-New_user_follows_me-48814d234e0c.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Tracker-New_user_follows_me.png)
 * Changed: **Tracker-New_user** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Tracker-New_user-853b1164e641.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Tracker-New_user-48814d234e0c.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Tracker-New_user.png)
 * Changed: **Tracker-Logged_out** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Tracker-Logged_out-853b1164e641.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Tracker-Logged_out-48814d234e0c.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Tracker-Logged_out.png)
 * Changed: **Tracker-Followed** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Tracker-Followed-853b1164e641.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Tracker-Followed-48814d234e0c.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Tracker-Followed.png)
 * Changed: **Tracker-Changed_Broken_proofs_user_you_dont_follow** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Tracker-Changed_Broken_proofs_user_you_dont_follow-853b1164e641.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Tracker-Changed_Broken_proofs_user_you_dont_follow-48814d234e0c.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Tracker-Changed_Broken_proofs_user_you_dont_follow.png)
 * Changed: **Tracker-Changed_Broken_proofs** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Tracker-Changed_Broken_proofs-853b1164e641.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Tracker-Changed_Broken_proofs-48814d234e0c.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Tracker-Changed_Broken_proofs.png)
 * Changed: **Tracker-Barely_there** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Tracker-Barely_there-853b1164e641.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Tracker-Barely_there-48814d234e0c.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Tracker-Barely_there.png)
 * Changed: **Tracker-5_proofs** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Tracker-5_proofs-853b1164e641.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Tracker-5_proofs-48814d234e0c.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Tracker-5_proofs.png)
 * Changed: **Search_User_Pane-Unfollowed_Scrolling** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Search_User_Pane-Unfollowed_Scrolling-853b1164e641.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Search_User_Pane-Unfollowed_Scrolling-48814d234e0c.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Search_User_Pane-Unfollowed_Scrolling.png)
 * Changed: **Search_User_Pane-Unfollowed** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Search_User_Pane-Unfollowed-853b1164e641.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Search_User_Pane-Unfollowed-48814d234e0c.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Search_User_Pane-Unfollowed.png)
 * Changed: **Search_User_Pane-Followed** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Search_User_Pane-Followed-853b1164e641.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Search_User_Pane-Followed-48814d234e0c.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Search_User_Pane-Followed.png)
 * Changed: **Search_User_Pane-Changed** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Search_User_Pane-Changed-853b1164e641.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Search_User_Pane-Changed-48814d234e0c.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Search_User_Pane-Changed.png)
 * Changed: **Search_User_Pane-Broken_tracker_not_following** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Search_User_Pane-Broken_tracker_not_following-853b1164e641.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Search_User_Pane-Broken_tracker_not_following-48814d234e0c.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Search_User_Pane-Broken_tracker_not_following.png)
 * Changed: **Search_Non_User_Pane-Has_Invite** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Search_Non_User_Pane-Has_Invite-853b1164e641.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Search_Non_User_Pane-Has_Invite-48814d234e0c.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Search_Non_User_Pane-Has_Invite.png)
 * Changed: **Profile-Unfollowed_Scrolled** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Profile-Unfollowed_Scrolled-853b1164e641.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Profile-Unfollowed_Scrolled-48814d234e0c.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Profile-Unfollowed_Scrolled.png)
 * Changed: **Profile-Unfollowed_Profile_page** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Profile-Unfollowed_Profile_page-853b1164e641.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Profile-Unfollowed_Profile_page-48814d234e0c.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Profile-Unfollowed_Profile_page.png)
 * Changed: **Profile-Unfollowed_Folders_Expanded** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Profile-Unfollowed_Folders_Expanded-853b1164e641.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Profile-Unfollowed_Folders_Expanded-48814d234e0c.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Profile-Unfollowed_Folders_Expanded.png)
 * Changed: **Profile-Unfollowed_Few_Folders** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Profile-Unfollowed_Few_Folders-853b1164e641.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Profile-Unfollowed_Few_Folders-48814d234e0c.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Profile-Unfollowed_Few_Folders.png)
 * Changed: **Profile-Unfollowed** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Profile-Unfollowed-853b1164e641.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Profile-Unfollowed-48814d234e0c.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Profile-Unfollowed.png)
 * Changed: **Profile-Followed** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Profile-Followed-853b1164e641.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Profile-Followed-48814d234e0c.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Profile-Followed.png)
 * Changed: **Profile-Changed_Scrolled** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Profile-Changed_Scrolled-853b1164e641.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Profile-Changed_Scrolled-48814d234e0c.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Profile-Changed_Scrolled.png)
 * Changed: **Profile-Changed** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Profile-Changed-853b1164e641.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Profile-Changed-48814d234e0c.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/Profile-Changed.png)
 * Removed: **user_search-Normal** [(view original)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/user_search-Normal-853b1164e641.png)
 * Removed: **user_group-Chat_enabled** [(view original)](https://keybase-app-visdiff.s3.amazonaws.com/1468440793017-853b1164e641-48814d234e0c-linux/user_group-Chat_enabled-853b1164e641.png)

**Comment by MarcoPolo** [comment]
👍 👍

**Comment by keybase-ci-visdiff** [comment]
:mag_right: The commits 853b1164e641...ffdc48398ddf introduced some visual changes on linux:
 * Added: **Search-Searching**  
   Search-Searching rendered
 * Added: **Search-Group_non_user_Out_of_invites**  
   Search-Group_non_user_Out_of_invites rendered
 * Added: **Search-Group_non_user_No_Avatar**  
   Search-Group_non_user_No_Avatar rendered
 * Added: **Search-Group_non_user_Has_Invite**  
   Search-Group_non_user_Has_Invite rendered
 * Added: **Search-Group_non_user**  
   Search-Group_non_user rendered
 * Added: **Search-Group**  
   Search-Group rendered
 * Added: **Search-Coming_soon**  
   Search-Coming_soon rendered
 * Added: **Search-Chat_enabled** [(view)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Search-Chat_enabled-ffdc48398ddf.png)
 * Changed: **Tracker-You_track_them** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Tracker-You_track_them-853b1164e641.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Tracker-You_track_them-ffdc48398ddf.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Tracker-You_track_them.png)
 * Changed: **Tracker-Whatevz** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Tracker-Whatevz-853b1164e641.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Tracker-Whatevz-ffdc48398ddf.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Tracker-Whatevz.png)
 * Changed: **Tracker-Unfollowed** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Tracker-Unfollowed-853b1164e641.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Tracker-Unfollowed-ffdc48398ddf.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Tracker-Unfollowed.png)
 * Changed: **Tracker-Platforms** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Tracker-Platforms-853b1164e641.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Tracker-Platforms-ffdc48398ddf.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Tracker-Platforms.png)
 * Changed: **Tracker-Only_one_proof** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Tracker-Only_one_proof-853b1164e641.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Tracker-Only_one_proof-ffdc48398ddf.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Tracker-Only_one_proof.png)
 * Changed: **Tracker-New_user_follows_me** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Tracker-New_user_follows_me-853b1164e641.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Tracker-New_user_follows_me-ffdc48398ddf.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Tracker-New_user_follows_me.png)
 * Changed: **Tracker-New_user** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Tracker-New_user-853b1164e641.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Tracker-New_user-ffdc48398ddf.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Tracker-New_user.png)
 * Changed: **Tracker-Logged_out** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Tracker-Logged_out-853b1164e641.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Tracker-Logged_out-ffdc48398ddf.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Tracker-Logged_out.png)
 * Changed: **Tracker-Followed** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Tracker-Followed-853b1164e641.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Tracker-Followed-ffdc48398ddf.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Tracker-Followed.png)
 * Changed: **Tracker-Changed_Broken_proofs_user_you_dont_follow** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Tracker-Changed_Broken_proofs_user_you_dont_follow-853b1164e641.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Tracker-Changed_Broken_proofs_user_you_dont_follow-ffdc48398ddf.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Tracker-Changed_Broken_proofs_user_you_dont_follow.png)
 * Changed: **Tracker-Changed_Broken_proofs** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Tracker-Changed_Broken_proofs-853b1164e641.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Tracker-Changed_Broken_proofs-ffdc48398ddf.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Tracker-Changed_Broken_proofs.png)
 * Changed: **Tracker-Barely_there** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Tracker-Barely_there-853b1164e641.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Tracker-Barely_there-ffdc48398ddf.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Tracker-Barely_there.png)
 * Changed: **Tracker-5_proofs** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Tracker-5_proofs-853b1164e641.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Tracker-5_proofs-ffdc48398ddf.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Tracker-5_proofs.png)
 * Changed: **Search_User_Pane-Unfollowed_Scrolling** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Search_User_Pane-Unfollowed_Scrolling-853b1164e641.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Search_User_Pane-Unfollowed_Scrolling-ffdc48398ddf.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Search_User_Pane-Unfollowed_Scrolling.png)
 * Changed: **Search_User_Pane-Unfollowed** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Search_User_Pane-Unfollowed-853b1164e641.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Search_User_Pane-Unfollowed-ffdc48398ddf.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Search_User_Pane-Unfollowed.png)
 * Changed: **Search_User_Pane-Followed** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Search_User_Pane-Followed-853b1164e641.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Search_User_Pane-Followed-ffdc48398ddf.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Search_User_Pane-Followed.png)
 * Changed: **Search_User_Pane-Changed** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Search_User_Pane-Changed-853b1164e641.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Search_User_Pane-Changed-ffdc48398ddf.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Search_User_Pane-Changed.png)
 * Changed: **Search_User_Pane-Broken_tracker_not_following** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Search_User_Pane-Broken_tracker_not_following-853b1164e641.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Search_User_Pane-Broken_tracker_not_following-ffdc48398ddf.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Search_User_Pane-Broken_tracker_not_following.png)
 * Changed: **Search_Non_User_Pane-Has_Invite** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Search_Non_User_Pane-Has_Invite-853b1164e641.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Search_Non_User_Pane-Has_Invite-ffdc48398ddf.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Search_Non_User_Pane-Has_Invite.png)
 * Changed: **Profile-Unfollowed_Scrolled** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Profile-Unfollowed_Scrolled-853b1164e641.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Profile-Unfollowed_Scrolled-ffdc48398ddf.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Profile-Unfollowed_Scrolled.png)
 * Changed: **Profile-Unfollowed_Profile_page** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Profile-Unfollowed_Profile_page-853b1164e641.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Profile-Unfollowed_Profile_page-ffdc48398ddf.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Profile-Unfollowed_Profile_page.png)
 * Changed: **Profile-Unfollowed_Folders_Expanded** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Profile-Unfollowed_Folders_Expanded-853b1164e641.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Profile-Unfollowed_Folders_Expanded-ffdc48398ddf.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Profile-Unfollowed_Folders_Expanded.png)
 * Changed: **Profile-Unfollowed_Few_Folders** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Profile-Unfollowed_Few_Folders-853b1164e641.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Profile-Unfollowed_Few_Folders-ffdc48398ddf.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Profile-Unfollowed_Few_Folders.png)
 * Changed: **Profile-Unfollowed** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Profile-Unfollowed-853b1164e641.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Profile-Unfollowed-ffdc48398ddf.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Profile-Unfollowed.png)
 * Changed: **Profile-Followed** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Profile-Followed-853b1164e641.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Profile-Followed-ffdc48398ddf.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Profile-Followed.png)
 * Changed: **Profile-Changed_Scrolled** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Profile-Changed_Scrolled-853b1164e641.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Profile-Changed_Scrolled-ffdc48398ddf.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Profile-Changed_Scrolled.png)
 * Changed: **Profile-Changed** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Profile-Changed-853b1164e641.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Profile-Changed-ffdc48398ddf.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/Profile-Changed.png)
 * Removed: **user_search-Normal** [(view original)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/user_search-Normal-853b1164e641.png)
 * Removed: **user_group-Chat_enabled** [(view original)](https://keybase-app-visdiff.s3.amazonaws.com/1468503498915-853b1164e641-ffdc48398ddf-linux/user_group-Chat_enabled-853b1164e641.png)

**Pull request merged**
