### PR TITLE
add a new reported status for conversations CORE-5078

### PR DESCRIPTION
**Pull request by mmaxim**
Adds a new reported status for conversations. When setting it, we also call out to the API server to record the report.

### CODE REVIEW

**Comment by mmaxim** [comment]
Client will treat it as `unfiled` if it doesn't know what it is.

**Comment by mlsteele** [comment]
Sounds good. Gregor will want vendored that chat1/extras change.

**Comment by mmaxim** [comment]
Less code had to change this way, and it doesn't seem like a huge difference.

**Comment by cjb** [comment]
Cool, okay.  I think it would be a problem if we continued this pattern -- we're trusting the client to tell us it did something that it may not actually have done, and we're depending on a client (e.g. someone's cell phone) to have access to enough networking to be able to send us this trigger, which presumably won't be retried if it fails, even though it's an important message for us to get notified about.

But if it's just this time to hit a deadline, seems fine.

**Pull request merged**
