### PR TITLE
Mobile dumb user bio & actions DESKTOP 1169

### PR DESCRIPTION
**Pull request by awendland**
### Primary
Migrates the UserBio over from desktop over to mobile. Also migrates UserActions, which have been promoted from `shared/profile/` to `shared/common-adapters` where they are with all the other User* components (UserBio, UserProofs, UserCard, etc).

Actions has been minimally tested (no errors thrown on display), but needs the dumb profile to be implemented for proper testing.

screen shot 2016-06-27 at 1 45 48 pm
screen shot 2016-06-27 at 3 17 06 pm

Demo of ability to change line clamping:
screen shot 2016-06-27 at 1 46 02 pm

### Additional

* Standardize `https://keybase.io` to a variable so that it can be dynamically changed to reference `https://stage0.keybase.io` depending on runtime. This ensures that client links point to the same location that the keybase service is referencing.
* Implement the `lineClamp` property on native Text so that it is compliant with desktop Text.
* Ensure that `style.color` being applied to native meta gets applied to the Text element, not the wrapper Box

@keybase/react-hackers

### CODE REVIEW

**Comment by keybase-ci-visdiff** [comment]
:mag_right: The commits 4767426f8af8...763d94fea712 introduced some visual changes on win32:
 * Changed: **Profile-Unfollowed_Scrolled** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1467065973013-4767426f8af8-763d94fea712-win32/Profile-Unfollowed_Scrolled-4767426f8af8.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1467065973013-4767426f8af8-763d94fea712-win32/Profile-Unfollowed_Scrolled-763d94fea712.png)  
   Profile-Unfollowed_Scrolled comparison
 * Changed: **Profile-Unfollowed_Profile_page** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1467065973013-4767426f8af8-763d94fea712-win32/Profile-Unfollowed_Profile_page-4767426f8af8.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1467065973013-4767426f8af8-763d94fea712-win32/Profile-Unfollowed_Profile_page-763d94fea712.png)  
   Profile-Unfollowed_Profile_page comparison
 * Changed: **Profile-Unfollowed_Folders_Expanded** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1467065973013-4767426f8af8-763d94fea712-win32/Profile-Unfollowed_Folders_Expanded-4767426f8af8.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1467065973013-4767426f8af8-763d94fea712-win32/Profile-Unfollowed_Folders_Expanded-763d94fea712.png)  
   Profile-Unfollowed_Folders_Expanded comparison
 * Changed: **Profile-Unfollowed_Few_Folders** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1467065973013-4767426f8af8-763d94fea712-win32/Profile-Unfollowed_Few_Folders-4767426f8af8.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1467065973013-4767426f8af8-763d94fea712-win32/Profile-Unfollowed_Few_Folders-763d94fea712.png)  
   Profile-Unfollowed_Few_Folders comparison
 * Changed: **Profile-Unfollowed** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1467065973013-4767426f8af8-763d94fea712-win32/Profile-Unfollowed-4767426f8af8.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1467065973013-4767426f8af8-763d94fea712-win32/Profile-Unfollowed-763d94fea712.png)  
   Profile-Unfollowed comparison
 * Changed: **Profile-Followed** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1467065973013-4767426f8af8-763d94fea712-win32/Profile-Followed-4767426f8af8.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1467065973013-4767426f8af8-763d94fea712-win32/Profile-Followed-763d94fea712.png)  
   Profile-Followed comparison
 * Changed: **Profile-Changed_Scrolled** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1467065973013-4767426f8af8-763d94fea712-win32/Profile-Changed_Scrolled-4767426f8af8.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1467065973013-4767426f8af8-763d94fea712-win32/Profile-Changed_Scrolled-763d94fea712.png)  
   Profile-Changed_Scrolled comparison
 * Changed: **Profile-Changed** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1467065973013-4767426f8af8-763d94fea712-win32/Profile-Changed-4767426f8af8.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1467065973013-4767426f8af8-763d94fea712-win32/Profile-Changed-763d94fea712.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1467065973013-4767426f8af8-763d94fea712-win32/Profile-Changed.png)

**Comment by keybase-ci-visdiff** [comment]
:mag_right: The commits 4767426f8af8...763d94fea712 introduced some visual changes on linux:
 * Changed: **unlock_folders-Success** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1467066309321-4767426f8af8-763d94fea712-linux/unlock_folders-Success-4767426f8af8.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1467066309321-4767426f8af8-763d94fea712-linux/unlock_folders-Success-763d94fea712.png)  
   unlock_folders-Success comparison
 * Changed: **Profile-Unfollowed_Scrolled** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1467066309321-4767426f8af8-763d94fea712-linux/Profile-Unfollowed_Scrolled-4767426f8af8.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1467066309321-4767426f8af8-763d94fea712-linux/Profile-Unfollowed_Scrolled-763d94fea712.png)  
   Profile-Unfollowed_Scrolled comparison
 * Changed: **Profile-Unfollowed_Profile_page** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1467066309321-4767426f8af8-763d94fea712-linux/Profile-Unfollowed_Profile_page-4767426f8af8.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1467066309321-4767426f8af8-763d94fea712-linux/Profile-Unfollowed_Profile_page-763d94fea712.png)  
   Profile-Unfollowed_Profile_page comparison
 * Changed: **Profile-Unfollowed_Folders_Expanded** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1467066309321-4767426f8af8-763d94fea712-linux/Profile-Unfollowed_Folders_Expanded-4767426f8af8.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1467066309321-4767426f8af8-763d94fea712-linux/Profile-Unfollowed_Folders_Expanded-763d94fea712.png)  
   Profile-Unfollowed_Folders_Expanded comparison
 * Changed: **Profile-Unfollowed_Few_Folders** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1467066309321-4767426f8af8-763d94fea712-linux/Profile-Unfollowed_Few_Folders-4767426f8af8.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1467066309321-4767426f8af8-763d94fea712-linux/Profile-Unfollowed_Few_Folders-763d94fea712.png)  
   Profile-Unfollowed_Few_Folders comparison
 * Changed: **Profile-Unfollowed** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1467066309321-4767426f8af8-763d94fea712-linux/Profile-Unfollowed-4767426f8af8.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1467066309321-4767426f8af8-763d94fea712-linux/Profile-Unfollowed-763d94fea712.png)  
   Profile-Unfollowed comparison
 * Changed: **Profile-Followed** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1467066309321-4767426f8af8-763d94fea712-linux/Profile-Followed-4767426f8af8.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1467066309321-4767426f8af8-763d94fea712-linux/Profile-Followed-763d94fea712.png)  
   Profile-Followed comparison
 * Changed: **Profile-Changed_Scrolled** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1467066309321-4767426f8af8-763d94fea712-linux/Profile-Changed_Scrolled-4767426f8af8.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1467066309321-4767426f8af8-763d94fea712-linux/Profile-Changed_Scrolled-763d94fea712.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1467066309321-4767426f8af8-763d94fea712-linux/Profile-Changed_Scrolled.png)
 * Changed: **Profile-Changed** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1467066309321-4767426f8af8-763d94fea712-linux/Profile-Changed-4767426f8af8.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1467066309321-4767426f8af8-763d94fea712-linux/Profile-Changed-763d94fea712.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1467066309321-4767426f8af8-763d94fea712-linux/Profile-Changed.png)

**Comment by awendland** [comment]
All the visdiff issues are to fix design compliance with line clamping in desktop user bio pages. According to @cecileboucheron, only the tracker is supposed to be limited to 3 lines for bio information. The profile screen should provide the full user bio.

**Comment by MarcoPolo** [comment]
👍

**Pull request merged**
