### PR TITLE
vendor update keybase/go-framed-msgpack-rpc#117

### PR DESCRIPTION
**Pull request by songgao**

### CODE REVIEW

**Comment by songgao** [comment]
yeah .. but it's a bug, and client uses this to connect to gregor, so I updated it here anyway :)

**Comment by jzila** [comment]
Maybe this was actually the cause of the rekey flake earlier today.

**Comment by jzila** [comment]
cc @maxtaco

**Comment by maxtaco** [comment]
wishful thinking but it did flake back in december too!

**Comment by jzila** [comment]
If we get no `TestRekey` flakes in the next 2 years then we can close that bug.

**Comment by jzila** [comment]
Or teams, whichever comes first :P

**Comment by songgao** [comment]
@maxtaco The race condition this PR fixes existed long before the random backoff stuff. The random backoff just made it easier to fail. So it's still possible that it's the same issue!

**Pull request merged**
