### PR TITLE
Add padding in global error and attachment on iphone X

### PR DESCRIPTION
**Pull request by buoyad**
It's difficult/impossible to exit these situations because the close buttons currently go underneath the clock.

r? @keybase/react-hackers

### CODE REVIEW

**Comment by chrisnojima** [comment]
Rn actually has a safe view for this now. Dunno if it's in the rn version we use

**Comment by buoyad** [comment]
@chrisnojima was https://github.com/keybase/client/pull/8699 meant to do that? I'm not sure how the error/attachment popups relate to the route styling, I'll take a closer look at it later though

**Comment by buoyad** [comment]
Anyone have an idea of a good place to add the extra padding? Adding it [here](https://github.com/keybase/client/blob/master/shared/app/nav.native.js#L191) resulted in this effect:

image

@keybase/react-hackers

**Comment by buoyad** [comment]
@chrisnojima is taking this ticket to put the padding in the route tree. Closing this one

**Pull request closed without merging**
