### PR TITLE
Fix button letter spacing to match style guide

### PR DESCRIPTION
**Pull request by cjb**
@keybase/react-hackers @cecileboucheron

Before and after:

screenshot from 2016-03-04 16-24-19

screenshot from 2016-03-04 16-26-26

### CODE REVIEW

**Comment by chrisnojima** [comment]
whered all my spinners go

**Comment by cjb** [comment]
Just accidental bad screenshot timing :)

**Comment by cecileboucheron** [comment]
Looks good to me.
We're no longer using the small buttons actually, I don't know if we want
to remove them or not.

**Comment by cjb** [comment]
@chrisnojima points out that the 0.3px spacing in the style guide is supposed to apply to *all* text, not just buttons.  We didn't have it in use anywhere before.  So now I've moved it to apply to text instead of buttons.

**Comment by chrisnojima** [comment]
:+1:

**Pull request merged**
