### PR TITLE
Update fonts.

### PR DESCRIPTION
**Pull request by adamjspooner**
@keybase/react-hackers, this is a work in progress, but I'd appreciate some feedback.

I'm having trouble getting this working on Android; it defaults to Roboto (which actually looks pretty good in the app on Android).

### CODE REVIEW

**Comment by cecileboucheron** [comment]
🎉🎉🎉

**Comment by adamjspooner** [comment]
@keybase/react-hackers, this is ready for another look. It's working on Android, but I made changes to the components used in `Usernames` and am unsure of the implications. Things look good across the board (desktop, iOS, and Android).

**Comment by chrisnojima** [comment]
i don't think we want this chagne to usernames, lets discuss

**Comment by adamjspooner** [comment]
@keybase/react-hackers, this is ready for another look.

**Pull request merged**
