### PR TITLE
add explodedBy to handle explode now in the gui

### PR DESCRIPTION
**Pull request by joshblum**
If a message is "exploded now" have to make sure it makes it way to the gui to render this. Added who exploded the message during the supersedes transform
cc @buoyad

### CODE REVIEW

**Comment by mmaxim** [comment]
That worked pretty well! I am wondering how the UI will handle this as a message streams in though.

**Comment by joshblum** [comment]
yeah! the next ticket will address that we'll have to pipe ephemeralMetadata through the delete msg so they can handle

**Comment by mmaxim** [comment]
Yeah I've always wished we could just do everything here and the UI has to do nothing. I wonder how bad it would be if every new message they get triggers a reload.

**Comment by mmaxim** [comment]
Or like "hard" messages cause it to reload

**Comment by joshblum** [comment]
hmm would be good to see how it performed

**Pull request merged**
