### PR TITLE
phone/email home screen - client

### PR DESCRIPTION
**Pull request by heronhaye**
More or less done but we need new icons from design. And the routes are not great either because you can't actually do any of these things in mobile. So this is blocked until later.

### CODE REVIEW

**Comment by zapu** [comment]
cc @keybase/react-hackers

**Comment by zapu** [comment]
are there reasons not to merge this? I was a bit anxious after last TODO badge problems but after looking into TODO system again for "noemail" todos, I think we are safe.

**Comment by chrisnojima** [comment]
Why merge this if it's not done. We're releasing Monday

**Comment by zapu** [comment]
ok

**Comment by heronhaye** [comment]
We don't have icons

**Pull request closed without merging**
