### PR TITLE
workaround for kex2 flakes until real fix is in

### PR DESCRIPTION
**Pull request by maxtaco**
r? @jzila

### CODE REVIEW

**Comment by jzila** [comment]
Is it possible to do something like try <n> times until success? We do that in KBFS for some timing based tests.

**Comment by maxtaco** [comment]
I'd prefer the real fix of using the fake clock...

**Comment by jzila** [comment]
k, works for me.

**Comment by maxtaco** [comment]
The retry isn't the right idea, since in this case we're actually trying to test that timeouts are actually happening properly or not properly

**Comment by maxtaco** [comment]
In other words, we really want this to work everytime, not just once in a while...

**Pull request merged**
