### PR TITLE
Fix user service summary cache refreshers

### PR DESCRIPTION
**Pull request by zapu**
The refresher from loaduser was poisoning service summary cache with bad values.

Service summary cache is used for things like icons in "interesting people" and contact list.

### CODE REVIEW

**Comment by heronhaye** [comment]
(If that's not feasible lmk)

**Comment by zapu** [comment]
I think I know how to add a test now. I was working on it Friday night and it seemed like a test was hard to do then. I'll work on this, thanks

**Comment by zapu** [comment]
@heronhaye added a test, please take a look.

failure is in some kex2 test which I think Max is disabling

**Comment by maxtaco** [comment]
should be disabled on master

can you rebase and try again?

**Comment by maxtaco** [comment]
And actually, no, I haven't disabled this particular test. This is a different issue, UGGGGGGG:

```
panic: Log in goroutine after TestKex2Provision has completed

goroutine 187 [running]:
testing.(*common).logDepth(0xc000102600, 0xc000e80840, 0xb0, 0x3)
	C:/go/src/testing/testing.go:678 +0x40d
testing.(*common).log(...)
	C:/go/src/testing/testing.go:658
```

There's a Kex router still going after the test ends

**Pull request merged**
