### PR TITLE
Add loading state pane for search

### PR DESCRIPTION
**Pull request by MarcoPolo**
@keybase/react-hackers

### CODE REVIEW

**Comment by chromakode** [comment]
retest this please

**Comment by chromakode** [comment]
:+1:

**Comment by keybase-ci-visdiff** [comment]
:mag_right: The commits 6920f59ee0e1...7024d5fe3c1d introduced some visual changes on linux:
 * Added: **Loading_Pane-Normal**  
   Loading_Pane-Normal rendered

**Comment by keybase-ci-visdiff** [comment]
:mag_right: The commits 6920f59ee0e1...7024d5fe3c1d introduced some visual changes on win32:
 * Added: **Loading_Pane-Normal**  
   Loading_Pane-Normal rendered

**Comment by keybase-ci-visdiff** [comment]
:mag_right: The commits 1828166cd535...10b6a0babb3e introduced some visual changes on linux:
 * Added: **Loading_Pane-Normal**  
   Loading_Pane-Normal rendered

**Pull request merged**
