### PR TITLE
Fix showing help on first start

### PR DESCRIPTION
**Pull request by gabriel**
The showing the help on first start has been broken for a few months :O 

I think here: https://github.com/keybase/client/pull/3224

### CODE REVIEW

**Comment by gabriel** [comment]
@keybase/react-hackers

**Comment by chromakode** [comment]
:+1":

**Comment by gabriel** [comment]
@malgorithms Should we do a new getting started page and show to all people again? Or are we ok with new users from last few months not having seen that page?

(We could do a file creation check hack to determine if people have seen the page, but might not be worth that effort?)

**Comment by malgorithms** [comment]
I think we're ok with users not having seen that page.

**Pull request merged**
