### PR TITLE
Updated avdl-compiler version, compiled with it for

### PR DESCRIPTION
**Pull request by patrickxb**
more efficient DeepCopy (hopefully)

### CODE REVIEW

**Comment by patrickxb** [comment]
Trying...

**Comment by jzila** [comment]
@patrickxb I went through the output, and it looks like all the failing diffs are ones that you haven't committed changes to. All the diffs that you've committed updates to pass in `diff_test.sh`.

**Comment by patrickxb** [comment]
@jzila still no luck.

**Comment by patrickxb** [comment]
I did a `make clean` and now `make` picked up more files...

**Comment by maxtaco** [comment]
you definitely need to run `make clean && make` after this change. i have never had to deal with the package-lock thing before.

**Comment by maxtaco** [comment]
get package-lock.json out of there.  `make clean` was the right fix...

**Comment by maxtaco** [comment]
i'll put up a pr

**Comment by maxtaco** [comment]
let's use #13111 instead.

**Pull request closed without merging**
