### PR TITLE
Updater omnibus PR

### PR DESCRIPTION
**Pull request by oconnor663**
This is a mix of @gabriel's [digest branch](https://github.com/keybase/client/pull/1705), @MarcoPolo's [updater instructions branch](https://github.com/keybase/client/pull/1698), and some local changes for Arch/Linux. Please give a quick check, thanks!

Sincerely,
cjb and jack

### CODE REVIEW

**Comment by MarcoPolo** [comment]
:+1:

**Comment by gabriel** [comment]
After you merge this, you'll need to merge the release tool updates https://github.com/keybase/release/pull/1

or building will fail. That PR adds digest and publishedAt fields to update json.

**Comment by gabriel** [comment]
:+1:

**Comment by gabriel** [comment]
what's status on this?

**Comment by oconnor663** [comment]
@cjb and I ended up mixing this in with a bunch of other hacks, and I'm still cleaning up the result. Should have another PR to replace this one later today.

**Comment by gabriel** [comment]
We should probably close this?

**Comment by oconnor663** [comment]
Yep!

**Pull request closed without merging**
