### PR TITLE
Chat2: rolled up

### PR DESCRIPTION
**Pull request by chrisnojima**
This just collects all the entirely deleted files into one place

### CODE REVIEW

**Comment by chrisnojima** [comment]
@keybase/react-hackers

**Comment by chrisnojima** [comment]
- [ ] merge it all down
- [ ] remove red
- [ ] remove keybase button

**Comment by chrisnojima** [comment]
- [ ] zapu delete issue

**Comment by chrisnojima** [comment]
@keybase/react-hackers the last 2 commits were to fix storybook up w/ the new connected providers. i'm going to merge when the lights are green

**Comment by fordboss147** [comment]
Help build my website

**Pull request merged**
