### PR TITLE
use badge count for displaying the orange dot, and big team badge calculation DESKTOP-4775

### PR DESCRIPTION
**Pull request by mmaxim**
Patch does the following:

1.) Changes type in the store for the unread counts to store both the total unread count alongside the badge count. This allows us to render the rows as bold when there are unread messages, and then if any of the unread messages would trigger a badge (notification), then it gets an orange dot.
2.) Change big team badge calculation to use the badge count number instead of total unread.

@keybase/react-hackers

### CODE REVIEW

**Comment by keybase-ci-visdiff** [comment]
The commits f64b5dcc5b71...0edfc7ad32b2 introduce visual changes on linux. <details><summary>:mag_right: 9 changed</summary>

 * Changed: **Chat_Inbox-You_Rekey_Selected** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1505093126547-f64b5dcc5b71-0edfc7ad32b2-linux/Chat_Inbox-You_Rekey_Selected-f64b5dcc5b71.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1505093126547-f64b5dcc5b71-0edfc7ad32b2-linux/Chat_Inbox-You_Rekey_Selected-0edfc7ad32b2.png)  
   Chat_Inbox-You_Rekey_Selected comparison
 * Changed: **Chat_Inbox-You_Rekey** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1505093126547-f64b5dcc5b71-0edfc7ad32b2-linux/Chat_Inbox-You_Rekey-f64b5dcc5b71.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1505093126547-f64b5dcc5b71-0edfc7ad32b2-linux/Chat_Inbox-You_Rekey-0edfc7ad32b2.png)  
   Chat_Inbox-You_Rekey comparison
 * Changed: **Chat_Inbox-Selected_Normal** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1505093126547-f64b5dcc5b71-0edfc7ad32b2-linux/Chat_Inbox-Selected_Normal-f64b5dcc5b71.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1505093126547-f64b5dcc5b71-0edfc7ad32b2-linux/Chat_Inbox-Selected_Normal-0edfc7ad32b2.png)  
   Chat_Inbox-Selected_Normal comparison
 * Changed: **Chat_Inbox-Selected_Muted** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1505093126547-f64b5dcc5b71-0edfc7ad32b2-linux/Chat_Inbox-Selected_Muted-f64b5dcc5b71.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1505093126547-f64b5dcc5b71-0edfc7ad32b2-linux/Chat_Inbox-Selected_Muted-0edfc7ad32b2.png)  
   Chat_Inbox-Selected_Muted comparison
 * Changed: **Chat_Inbox-Part_Rekey_Selected** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1505093126547-f64b5dcc5b71-0edfc7ad32b2-linux/Chat_Inbox-Part_Rekey_Selected-f64b5dcc5b71.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1505093126547-f64b5dcc5b71-0edfc7ad32b2-linux/Chat_Inbox-Part_Rekey_Selected-0edfc7ad32b2.png)  
   Chat_Inbox-Part_Rekey_Selected comparison
 * Changed: **Chat_Inbox-Part_Rekey** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1505093126547-f64b5dcc5b71-0edfc7ad32b2-linux/Chat_Inbox-Part_Rekey-f64b5dcc5b71.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1505093126547-f64b5dcc5b71-0edfc7ad32b2-linux/Chat_Inbox-Part_Rekey-0edfc7ad32b2.png)  
   Chat_Inbox-Part_Rekey comparison
 * Changed: **Chat_Inbox-Normal** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1505093126547-f64b5dcc5b71-0edfc7ad32b2-linux/Chat_Inbox-Normal-f64b5dcc5b71.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1505093126547-f64b5dcc5b71-0edfc7ad32b2-linux/Chat_Inbox-Normal-0edfc7ad32b2.png)  
   Chat_Inbox-Normal comparison
 * Changed: **Chat_Inbox-Long_Top** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1505093126547-f64b5dcc5b71-0edfc7ad32b2-linux/Chat_Inbox-Long_Top-f64b5dcc5b71.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1505093126547-f64b5dcc5b71-0edfc7ad32b2-linux/Chat_Inbox-Long_Top-0edfc7ad32b2.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1505093126547-f64b5dcc5b71-0edfc7ad32b2-linux/Chat_Inbox-Long_Top.png)
 * Changed: **Chat_Inbox-Long_Bottom** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1505093126547-f64b5dcc5b71-0edfc7ad32b2-linux/Chat_Inbox-Long_Bottom-f64b5dcc5b71.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1505093126547-f64b5dcc5b71-0edfc7ad32b2-linux/Chat_Inbox-Long_Bottom-0edfc7ad32b2.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1505093126547-f64b5dcc5b71-0edfc7ad32b2-linux/Chat_Inbox-Long_Bottom.png)
</summary>

**Comment by keybase-ci-visdiff** [comment]
The commits f64b5dcc5b71...a4efadb6c30b introduce visual changes on linux. <details><summary>:mag_right: 9 changed</summary>

 * Changed: **Chat_Inbox-You_Rekey_Selected** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1505093756534-f64b5dcc5b71-a4efadb6c30b-linux/Chat_Inbox-You_Rekey_Selected-f64b5dcc5b71.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1505093756534-f64b5dcc5b71-a4efadb6c30b-linux/Chat_Inbox-You_Rekey_Selected-a4efadb6c30b.png)  
   Chat_Inbox-You_Rekey_Selected comparison
 * Changed: **Chat_Inbox-You_Rekey** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1505093756534-f64b5dcc5b71-a4efadb6c30b-linux/Chat_Inbox-You_Rekey-f64b5dcc5b71.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1505093756534-f64b5dcc5b71-a4efadb6c30b-linux/Chat_Inbox-You_Rekey-a4efadb6c30b.png)  
   Chat_Inbox-You_Rekey comparison
 * Changed: **Chat_Inbox-Selected_Normal** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1505093756534-f64b5dcc5b71-a4efadb6c30b-linux/Chat_Inbox-Selected_Normal-f64b5dcc5b71.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1505093756534-f64b5dcc5b71-a4efadb6c30b-linux/Chat_Inbox-Selected_Normal-a4efadb6c30b.png)  
   Chat_Inbox-Selected_Normal comparison
 * Changed: **Chat_Inbox-Selected_Muted** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1505093756534-f64b5dcc5b71-a4efadb6c30b-linux/Chat_Inbox-Selected_Muted-f64b5dcc5b71.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1505093756534-f64b5dcc5b71-a4efadb6c30b-linux/Chat_Inbox-Selected_Muted-a4efadb6c30b.png)  
   Chat_Inbox-Selected_Muted comparison
 * Changed: **Chat_Inbox-Part_Rekey_Selected** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1505093756534-f64b5dcc5b71-a4efadb6c30b-linux/Chat_Inbox-Part_Rekey_Selected-f64b5dcc5b71.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1505093756534-f64b5dcc5b71-a4efadb6c30b-linux/Chat_Inbox-Part_Rekey_Selected-a4efadb6c30b.png)  
   Chat_Inbox-Part_Rekey_Selected comparison
 * Changed: **Chat_Inbox-Part_Rekey** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1505093756534-f64b5dcc5b71-a4efadb6c30b-linux/Chat_Inbox-Part_Rekey-f64b5dcc5b71.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1505093756534-f64b5dcc5b71-a4efadb6c30b-linux/Chat_Inbox-Part_Rekey-a4efadb6c30b.png)  
   Chat_Inbox-Part_Rekey comparison
 * Changed: **Chat_Inbox-Normal** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1505093756534-f64b5dcc5b71-a4efadb6c30b-linux/Chat_Inbox-Normal-f64b5dcc5b71.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1505093756534-f64b5dcc5b71-a4efadb6c30b-linux/Chat_Inbox-Normal-a4efadb6c30b.png)  
   Chat_Inbox-Normal comparison
 * Changed: **Chat_Inbox-Long_Top** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1505093756534-f64b5dcc5b71-a4efadb6c30b-linux/Chat_Inbox-Long_Top-f64b5dcc5b71.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1505093756534-f64b5dcc5b71-a4efadb6c30b-linux/Chat_Inbox-Long_Top-a4efadb6c30b.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1505093756534-f64b5dcc5b71-a4efadb6c30b-linux/Chat_Inbox-Long_Top.png)
 * Changed: **Chat_Inbox-Long_Bottom** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1505093756534-f64b5dcc5b71-a4efadb6c30b-linux/Chat_Inbox-Long_Bottom-f64b5dcc5b71.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1505093756534-f64b5dcc5b71-a4efadb6c30b-linux/Chat_Inbox-Long_Bottom-a4efadb6c30b.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1505093756534-f64b5dcc5b71-a4efadb6c30b-linux/Chat_Inbox-Long_Bottom.png)
</summary>

**Comment by chrisnojima** [comment]
then you can merge, tnx!

**Comment by keybase-ci-visdiff** [comment]
The commits f64b5dcc5b71...61b2cbeccfc2 introduce visual changes on linux. <details><summary>:mag_right: 9 changed</summary>

 * Changed: **Chat_Inbox-You_Rekey_Selected** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1505139247675-f64b5dcc5b71-61b2cbeccfc2-linux/Chat_Inbox-You_Rekey_Selected-f64b5dcc5b71.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1505139247675-f64b5dcc5b71-61b2cbeccfc2-linux/Chat_Inbox-You_Rekey_Selected-61b2cbeccfc2.png)  
   Chat_Inbox-You_Rekey_Selected comparison
 * Changed: **Chat_Inbox-You_Rekey** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1505139247675-f64b5dcc5b71-61b2cbeccfc2-linux/Chat_Inbox-You_Rekey-f64b5dcc5b71.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1505139247675-f64b5dcc5b71-61b2cbeccfc2-linux/Chat_Inbox-You_Rekey-61b2cbeccfc2.png)  
   Chat_Inbox-You_Rekey comparison
 * Changed: **Chat_Inbox-Selected_Normal** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1505139247675-f64b5dcc5b71-61b2cbeccfc2-linux/Chat_Inbox-Selected_Normal-f64b5dcc5b71.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1505139247675-f64b5dcc5b71-61b2cbeccfc2-linux/Chat_Inbox-Selected_Normal-61b2cbeccfc2.png)  
   Chat_Inbox-Selected_Normal comparison
 * Changed: **Chat_Inbox-Selected_Muted** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1505139247675-f64b5dcc5b71-61b2cbeccfc2-linux/Chat_Inbox-Selected_Muted-f64b5dcc5b71.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1505139247675-f64b5dcc5b71-61b2cbeccfc2-linux/Chat_Inbox-Selected_Muted-61b2cbeccfc2.png)  
   Chat_Inbox-Selected_Muted comparison
 * Changed: **Chat_Inbox-Part_Rekey_Selected** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1505139247675-f64b5dcc5b71-61b2cbeccfc2-linux/Chat_Inbox-Part_Rekey_Selected-f64b5dcc5b71.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1505139247675-f64b5dcc5b71-61b2cbeccfc2-linux/Chat_Inbox-Part_Rekey_Selected-61b2cbeccfc2.png)  
   Chat_Inbox-Part_Rekey_Selected comparison
 * Changed: **Chat_Inbox-Part_Rekey** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1505139247675-f64b5dcc5b71-61b2cbeccfc2-linux/Chat_Inbox-Part_Rekey-f64b5dcc5b71.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1505139247675-f64b5dcc5b71-61b2cbeccfc2-linux/Chat_Inbox-Part_Rekey-61b2cbeccfc2.png)  
   Chat_Inbox-Part_Rekey comparison
 * Changed: **Chat_Inbox-Normal** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1505139247675-f64b5dcc5b71-61b2cbeccfc2-linux/Chat_Inbox-Normal-f64b5dcc5b71.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1505139247675-f64b5dcc5b71-61b2cbeccfc2-linux/Chat_Inbox-Normal-61b2cbeccfc2.png)  
   Chat_Inbox-Normal comparison
 * Changed: **Chat_Inbox-Long_Top** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1505139247675-f64b5dcc5b71-61b2cbeccfc2-linux/Chat_Inbox-Long_Top-f64b5dcc5b71.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1505139247675-f64b5dcc5b71-61b2cbeccfc2-linux/Chat_Inbox-Long_Top-61b2cbeccfc2.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1505139247675-f64b5dcc5b71-61b2cbeccfc2-linux/Chat_Inbox-Long_Top.png)
 * Changed: **Chat_Inbox-Long_Bottom** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1505139247675-f64b5dcc5b71-61b2cbeccfc2-linux/Chat_Inbox-Long_Bottom-f64b5dcc5b71.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1505139247675-f64b5dcc5b71-61b2cbeccfc2-linux/Chat_Inbox-Long_Bottom-61b2cbeccfc2.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1505139247675-f64b5dcc5b71-61b2cbeccfc2-linux/Chat_Inbox-Long_Bottom.png)
</summary>

**Pull request merged**
