### PR TITLE
Send notification when autoclaim complete

### PR DESCRIPTION
**Pull request by patrickxb**
cc @chrisnojima @buoyad

### CODE REVIEW

**Comment by patrickxb** [comment]
How would stellard know that all the autoclaims are complete?

This is for DESKTOP-8573.

**Comment by mlsteele** [comment]
Oh I didn't realize this is a notification for all of the outstanding ones completing.

Still, on the server that's [this case](https://github.com/keybase/keybase/blob/master/go/stellard/server.go#L1475).

**Comment by mlsteele** [comment]
Hopefully the gui is only waiting for this for users who just created a wallet on that device. Cause for users with a wallet ACR might run before the gui connects.

**Comment by patrickxb** [comment]
I believe that's the flow.  The user accepts the disclaimer and then the GUI waits.  Currently they just wait for 6s.  with this notification, i believe they can be more precise.

**Comment by mlsteele** [comment]
If `AcquireAutoClaimLock` errors out then the gui will never show the wallet. I don't know about this strategy. Could just show the wallet and show the payments in the state they are in, which is claiming. Then work on making autoclaim faster.

**Comment by patrickxb** [comment]
GUI could wait for 6s or this notification, but that wouldn't solve the DESKTOP ticket since that is when someone looking at it after 6s, before autoclaim is done.

**Pull request closed without merging**
