### PR TITLE
missing .mpack file: RemoteSettingsRepairman

### PR DESCRIPTION
**Pull request by zanderz**
The "repairman" skipped files it thought were in both locations, but failed to identify that case when deleting the old version.

### CODE REVIEW

**Comment by zanderz** [comment]
Also: should we just remove this repairman? it is only for clients older than Feb 2017

**Comment by maxtaco** [comment]
I think we should remove it

**Comment by zanderz** [comment]
ok removed @maxtaco  (ci is broken in master right?)

**Comment by maxtaco** [comment]
I don't know, you'd have to ask...

**Pull request merged**
