### PR TITLE
Use fillLocalInfo when unboxing threads, include device name

### PR DESCRIPTION
**Pull request by patrickxb**
r? @mmaxim 

@songgao userInfoMapper didn't get device names before, this fixes that.

### CODE REVIEW

**Comment by patrickxb** [comment]
I already did.

**Comment by songgao** [comment]
I meant here: https://github.com/keybase/client/pull/4361/files#diff-0c741c719ee20a92e9bfc748635882a5R27

Sorry for lacking the link earlier. No seat on train so n cellphone today :(

**Comment by patrickxb** [comment]
Whoops, ok!

**Comment by patrickxb** [comment]
@songgao PTAL

**Pull request merged**
