### PR TITLE
Update go-framed-msgpack-rpc

### PR DESCRIPTION
**Pull request by akalin-keybase**
This includes debug tags, and
the fix for a hang on
cancellation.

### CODE REVIEW

**Comment by akalin-keybase** [comment]
@jzila vendoring normally will also pull in the debug tags change. We can keep that out of client longer, but that would make the vendored version diverge from the real one.

**Comment by jzila** [comment]
Let's pull it in.

**Comment by maxtaco** [comment]
:+1:

**Comment by akalin-keybase** [comment]
Appveyor failure seems unrelated, merging

**Pull request closed without merging**
