### PR TITLE
WIP1027 tracker thrashing

### PR DESCRIPTION
**Pull request by chrisnojima**
so i stopped here as i noticed a bug where i'd get multiple identify calls for the same person which confuses the issue. leaving this as a discussion point. unclear if we want to move forward.
@MarcoPolo want to discuss

### CODE REVIEW

**Comment by maxtaco** [comment]
Concurrent or sequential?

**Comment by keybase-ci-visdiff** [comment]
:mag_right: No visual changes found as a result of these commits.

**Comment by chrisnojima** [comment]
seems sequential. i'm looking at /keybase/private/chrisnojima,max,oconnor663 and i get an identify for max,oconnor663, then right after oconnor idenitifyUi.finish i get an idenitfyUi.start for oconnor

**Comment by maxtaco** [comment]
That sounds feasible. That pipelining logic is exetemely hair raising and
there is always the concern of what to do with errors.

Was there an error or call to action in the first case?

**Comment by chrisnojima** [comment]
Depends on what you mean by error. he does show as red because he has an
untracked deleted proof (as expected). I'll debug with patrick soon

**Comment by maxtaco** [comment]
Plus we don't hold any serializing locks over the lifetime of the tracker
window.  Only over the run of identify.  We don't have an accurate
mechanism to know if a tracker window is still open.  Consider crashes of
electron to see why this is a complicated problem.

**Comment by maxtaco** [comment]
Ok then it might be expected behavior.  We have a story for how to deal
with caching error conditions like the one you found but have been delaying
it since it is hair raising logic.

**Comment by chrisnojima** [comment]
let's chat about this in person

**Comment by chrisnojima** [comment]
i'm closing this. i think how the engine/server works is kinda confusing and maybe something that needs to be in engine itself maybe

**Pull request closed without merging**
