### PR TITLE
WIP: RN update to 0.46

### PR DESCRIPTION
**Pull request by chrisnojima**
This PR updates our RN to 0.46. This also means our react dependency got updated to 16 alpha which affects desktop also.
Additionally the update to 0.46 updates some tooling which allows us to see the dimensions of views in the react devtools which led me to discover some high level layout problems. This PR also addresses this. Before we had flex:1 screens which (depending on the contents) push the screens below the fold. This lead to bugs about things being cut off.

TODO:
- [x] ios sanity check
- [x] desktop 
- [x] android
- [x] smoketest ios
- [x] smoketest android
- [x] smoketest desktop

Known issues:
- [ ] Android has a weird underline on the inputs. This looks really bad on searchv3 as it has a green line going through the text. This seems like something bad on the native side as we're not passing anything to the component. The underlineColorAndroid setting is actually a different underline than what we're seeing here

notes:
- A lot of addons are dead / moved
https://github.com/facebook/react/issues/9207
No react-perf on desktop :(
- We got to kill our vendored FlatList!
- Popup list wasn't working with react 16, we needed to kill it anyways (material-ui) so i reimplemented it. It was only used in login

This changes enough things that we should defer until after searchv3

### CODE REVIEW

**Comment by cjb** [comment]
Have been running this branch, feels good to me.

**Comment by chrisnojima** [comment]
I think before this is merged we should run through the smoke test (and go
through all the dumb screens) and the same for desktop

**Comment by chrisnojima** [comment]
A lot of our layout was using flexGrow incorrectly which lead to content being rendered below the fold. At a top level I'm forcing the nav children to take up the full non-tabbar space

**Comment by chrisnojima** [comment]
replaced by this cleanup pr: https://github.com/keybase/client/pull/7759

**Pull request closed without merging**
