### PR TITLE
search: add a bleve storage plugin that uses the leveldb-over-billy storage

### PR DESCRIPTION
**Pull request by strib**
Bleve is an existing Go-based indexer and search engine, and this PR introduces a new bleve storage plugin that takes advantage of the existing `libfs` leveldb-over-billy-FS storage plugin.  The idea is that we will be able to build a search engine in KBFS where the storage graph looks like this:

```
Bleve search engine
         |
         V
      Leveldb
         |
         V
      libfs.FS
         |
         V
    local bserver
         |
         V
     local disk
```

The point of all this is that we have a fully-featured search engine (bleve), where the index is fully encrypted and stored in blocks to the local disk by KBFS.  This will hopefully give us the best of both worlds -- fast search using local data, but that local data is still encrypted at rest on the local disk.

This PR is a stepping stone to that by providing the last plugin needed to make the above graph work.  A future PR will do the work of hooking it all together and testing the bleve indexer and search as a whole.

It also re-vendors in our leveldb fork, which was updated with the latest master code from syndtr/goleveldb, since a new function there (`MakeBatch`) was needed.

Issue: HOTPOT-1262

### CODE REVIEW

**Comment by jzila** [comment]
Neat! Since this is using the local bserver, does that mean that the indexed blocks don't get synced?

**Comment by strib** [comment]
> Neat! Since this is using the local bserver, does that mean that the indexed blocks don't get synced?

@jzila correct, that's how it will work in a future commit -- the blocks will just be stored in local disk storage and stay there, just as when running kbfs in local mode.  This commit doesn't hook any of that up yet, though.

**Comment by strib** [comment]
(Assuming by "indexed blocks" you mean the blocks that are storing the index...)

**Comment by jzila** [comment]
Any reason not to sync the index?

**Comment by strib** [comment]
> Any reason not to sync the index?

Yes, it will be slow as molasses.  It basically amounts to a whole other copy of all the data in the TLF, and so uploading that every time there's a change, and downloading that every time you need to search, or trying to keep it in sync on every device, isn't realistic.

But further down the road, we'll likely let devices who don't have an index make a query RPC to ones that do (through the server), so those other devices can search on their behalf and return the results.

**Comment by jzila** [comment]
> It basically amounts to a whole other copy of all the data in the TLF

That doesn't seem like a very efficient index...I thought we could get bloom filter-powered solutions that get 1000x storage reduction for a ~1% false positive rate.

**Comment by strib** [comment]
Maybe if we built a custom search engine we could optimize it, maybe at the cost of extra indexing CPU or search features, but there are no plans for that.  Currently bleve actually costs more than the actual data size (7x I think?): https://github.com/blevesearch/bleve/issues/1186

**Comment by jzila** [comment]
Got it, I guess we can start with this and see where we end up.

**Pull request merged**
