### PR TITLE
Move InputCanceledError to libkb

### PR DESCRIPTION
**Pull request by akalin-keybase**
This will enable KBFS to remove yet another
dependency on client.

Also, change its status code to avoid conflicting
with CanceledError, which is probably why
https://keybase.atlassian.net/browse/KBFS-589
is happening again.

### CODE REVIEW

**Comment by akalin-keybase** [comment]
This is checked in KBFS here https://github.com/keybase/kbfs/blob/45e3c8487170a6e6fb2d977c6c86853bf6627b49/libkbfs/connection.go#L369 (added by @strib). That code is still used by the electron GUI, right?

**Comment by maxtaco** [comment]
I believe so. That was an important fix otherwise users would get murdered by login prompts they couldn't complete.

BTW, this fix looks good to me

**Comment by patrickxb** [comment]
Yes, this error needs to be propagated.

Moving to libkb LGTM

**Comment by akalin-keybase** [comment]
Okay, a couple more questions before I check this in.

Where exactly in the electron UI code is this or the equivalent status code (SCCanceled=237) used? I tried grepping but couldn't find it.

Also, I just noticed that InputCanceledError and CanceledError have the same code (SCCanceled) in ToStatus. But ImportStatusAsError in rpc_exim.go converts SCCanceled to CanceledError{}, so the only way KBFS would see InputCanceledError is (I think) if it used client.NewSecretUIProtocol directly, which uses SecretUI, which explicitly returns InputCanceledError directly. (And this stopped happening a little while ago, once we let the daemon delegate the secret UI.) Otherwise, if it instead receives an error over an RPC, then won't it get CanceledError{}?

So shouldn't I just rip out InputCanceledError and use CanceledError everywhere, and check for that instead on the KBFS side?

**Comment by patrickxb** [comment]
the status codes are in the protocol.  protocol/avdl/constants.avdl.

**Comment by patrickxb** [comment]
No, there should be a difference between InputCanceled and Canceled.

If the user cancels, then it should be InputCanceled and things like 

https://keybase.atlassian.net/browse/KBFS-589 

(which is coincidentally broken again) should handle the error differently.

If the same status code, then that is a bug.

**Comment by akalin-keybase** [comment]
Okay, sounds like it got broken again once we ripped out the local secret UI. I'll update this PR to fix it.

**Comment by akalin-keybase** [comment]
Okay, I updated this (and I'll update the server side when this goes in). In order to test this, it would also have to be vendored on the KBFS side first (to pull in the unwrapping code). I'll do a PR for that shortly, but PTAL!

**Comment by patrickxb** [comment]
LGTM!

**Comment by akalin-keybase** [comment]
one more change was needed -- I had to change pinentry.js to use the new scinputcanceled code. (thanks @cjb)

**Pull request closed without merging**
