### PR TITLE
Dumb Pinentry DESKTOP 841

### PR DESCRIPTION
**Pull request by awendland**
@keybase/react-hackers 

Create a dumb component demo for Pinentry to be displayed on the component sheet.

screen shot 2016-05-31 at 5 19 43 pm

### CODE REVIEW

**Comment by awendland** [comment]
It appears that there is a pre-existing bug in the PinentryRender component that causes it to always show the error text (at least I don't think I changed enough to introduce the bug).

**Comment by awendland** [comment]
screen shot 2016-05-31 at 5 35 53 pm

**Comment by MarcoPolo** [comment]
👍

**Comment by keybase-ci-visdiff** [comment]
:mag_right: :zap: These commits introduced some visual changes:
 * Added: **Pinentry-Show_Typing**  
   Pinentry-Show_Typing rendered
 * Added: **Pinentry-Normal**  
   Pinentry-Normal rendered

**Comment by keybase-ci-visdiff** [comment]
:mag_right: :zap: These commits introduced some visual changes:
 * Added: **Pinentry-With_Error**  
   Pinentry-With_Error rendered
 * Added: **Pinentry-Normal**  
   Pinentry-Normal rendered

**Pull request merged**
