### PR TITLE
Chat perf part 3

### PR DESCRIPTION
**Pull request by chrisnojima**
- [x] fix issue in branch perf-2 with avatars that are false in the cache always flickering
- [x] Make clickable box faster
- [x] Use more divs vs Boxes. We should discuss this. I think connect / shared classes should use Boxes so we can share that code but the .desktop code w/ Boxes is actually slightly slower and causes a lot of noise in the react perf logs
- [x] ShouldComponentUpdate for text

### CODE REVIEW

**Comment by chrisnojima** [comment]
@keybase/react-hackers

**Comment by keybase-ci-visdiff** [comment]
The commits 7b65cadf7907...073ab60295f7 introduce visual changes on linux. <details><summary>:mag_right: 6 changed</summary>

 * Changed: **Profile-Your_Profile_Proof_Menu** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1482115965288-7b65cadf7907-073ab60295f7-linux/Profile-Your_Profile_Proof_Menu-7b65cadf7907.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1482115965288-7b65cadf7907-073ab60295f7-linux/Profile-Your_Profile_Proof_Menu-073ab60295f7.png)  
   Profile-Your_Profile_Proof_Menu comparison
 * Changed: **Profile-Your_Profile_Pending_Proof_Menu_HN** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1482115965288-7b65cadf7907-073ab60295f7-linux/Profile-Your_Profile_Pending_Proof_Menu_HN-7b65cadf7907.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1482115965288-7b65cadf7907-073ab60295f7-linux/Profile-Your_Profile_Pending_Proof_Menu_HN-073ab60295f7.png)  
   Profile-Your_Profile_Pending_Proof_Menu_HN comparison
 * Changed: **Profile-Your_Profile_Pending_Proof_Menu_DNS** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1482115965288-7b65cadf7907-073ab60295f7-linux/Profile-Your_Profile_Pending_Proof_Menu_DNS-7b65cadf7907.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1482115965288-7b65cadf7907-073ab60295f7-linux/Profile-Your_Profile_Pending_Proof_Menu_DNS-073ab60295f7.png)  
   Profile-Your_Profile_Pending_Proof_Menu_DNS comparison
 * Changed: **Profile-Your_Profile_Pending_Proof_Menu** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1482115965288-7b65cadf7907-073ab60295f7-linux/Profile-Your_Profile_Pending_Proof_Menu-7b65cadf7907.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1482115965288-7b65cadf7907-073ab60295f7-linux/Profile-Your_Profile_Pending_Proof_Menu-073ab60295f7.png)  
   Profile-Your_Profile_Pending_Proof_Menu comparison
 * Changed: **Profile-Your_Profile_Broken_Proof_Menu** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1482115965288-7b65cadf7907-073ab60295f7-linux/Profile-Your_Profile_Broken_Proof_Menu-7b65cadf7907.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1482115965288-7b65cadf7907-073ab60295f7-linux/Profile-Your_Profile_Broken_Proof_Menu-073ab60295f7.png)  
   Profile-Your_Profile_Broken_Proof_Menu comparison
 * Changed: **Profile-Your_Profile_Broken** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1482115965288-7b65cadf7907-073ab60295f7-linux/Profile-Your_Profile_Broken-7b65cadf7907.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1482115965288-7b65cadf7907-073ab60295f7-linux/Profile-Your_Profile_Broken-073ab60295f7.png)  
   Profile-Your_Profile_Broken comparison
</summary>

**Comment by keybase-ci-visdiff** [comment]
The commits cd745debf710...70f068eef211 introduce visual changes on linux. <details><summary>:mag_right: 6 changed</summary>

 * Changed: **Profile-Your_Profile_Proof_Menu** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1482184647246-cd745debf710-70f068eef211-linux/Profile-Your_Profile_Proof_Menu-cd745debf710.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1482184647246-cd745debf710-70f068eef211-linux/Profile-Your_Profile_Proof_Menu-70f068eef211.png)  
   Profile-Your_Profile_Proof_Menu comparison
 * Changed: **Profile-Your_Profile_Pending_Proof_Menu_HN** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1482184647246-cd745debf710-70f068eef211-linux/Profile-Your_Profile_Pending_Proof_Menu_HN-cd745debf710.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1482184647246-cd745debf710-70f068eef211-linux/Profile-Your_Profile_Pending_Proof_Menu_HN-70f068eef211.png)  
   Profile-Your_Profile_Pending_Proof_Menu_HN comparison
 * Changed: **Profile-Your_Profile_Pending_Proof_Menu_DNS** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1482184647246-cd745debf710-70f068eef211-linux/Profile-Your_Profile_Pending_Proof_Menu_DNS-cd745debf710.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1482184647246-cd745debf710-70f068eef211-linux/Profile-Your_Profile_Pending_Proof_Menu_DNS-70f068eef211.png)  
   Profile-Your_Profile_Pending_Proof_Menu_DNS comparison
 * Changed: **Profile-Your_Profile_Pending_Proof_Menu** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1482184647246-cd745debf710-70f068eef211-linux/Profile-Your_Profile_Pending_Proof_Menu-cd745debf710.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1482184647246-cd745debf710-70f068eef211-linux/Profile-Your_Profile_Pending_Proof_Menu-70f068eef211.png)  
   Profile-Your_Profile_Pending_Proof_Menu comparison
 * Changed: **Profile-Your_Profile_Broken_Proof_Menu** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1482184647246-cd745debf710-70f068eef211-linux/Profile-Your_Profile_Broken_Proof_Menu-cd745debf710.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1482184647246-cd745debf710-70f068eef211-linux/Profile-Your_Profile_Broken_Proof_Menu-70f068eef211.png)  
   Profile-Your_Profile_Broken_Proof_Menu comparison
 * Changed: **Profile-Your_Profile_Broken** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1482184647246-cd745debf710-70f068eef211-linux/Profile-Your_Profile_Broken-cd745debf710.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1482184647246-cd745debf710-70f068eef211-linux/Profile-Your_Profile_Broken-70f068eef211.png)  
   Profile-Your_Profile_Broken comparison
</summary>

**Comment by chrisnojima** [comment]
@keybase/react-hackers bump

**Comment by MarcoPolo** [comment]
Did you try just having box export `React.DOM.div`?

Besides that 👍

**Comment by chrisnojima** [comment]
i'll try the dom thing

**Comment by chrisnojima** [comment]
sadly doesn't work, those things are functions which take different params. we could look into this further later i think. i quickly tried to use createElement but that is effectively the same as what we have now

**Comment by MarcoPolo** [comment]
okay sounds good.

**Pull request merged**
