### PR TITLE
separate not enabled calls with a newline

### PR DESCRIPTION
**Pull request by joshblum**
these files conflict a lot but shouldn't

### CODE REVIEW

**Comment by chrisnojima** [comment]
I did it on one line on purpose

**Comment by jakob223** [comment]
@chrisnojima it's frustrating to constantly have to rebase old PRs because of fake conflicts on this one line - why did you do it this way on purpose?

**Comment by chrisnojima** [comment]
This is a generated artifact. If you have conflicts just regenerate the code and do not merge it

**Comment by joshblum** [comment]
i've used it in the past as a reminder about the calls-enabled, i think it's nice that the RPC is greppable. is there any downside to leaving it expanded?

**Pull request merged**
