### PR TITLE
Use events instead of polling

### PR DESCRIPTION
**Pull request by MarcoPolo**
@keybase/react-hackers @zanderz 

A better approach to showing the window on Windows startup

### CODE REVIEW

**Comment by MarcoPolo** [comment]
tested on works for me on windows vm

**Comment by zanderz** [comment]
Wow, you made yourself an installer with Jenkins, too, I like it!
LGTM :thumbsup:

**Comment by chrisnojima** [comment]
so this works fine on windows / linux?

**Comment by MarcoPolo** [comment]
yeah

**Comment by chrisnojima** [comment]
:+1:

**Pull request merged**
