### PR TITLE
WIP folder fixes 

### PR DESCRIPTION
**Pull request by chrisnojima**
- [x] When I click through deeper into a public TLF, then click back, it sends me back to the private tab in scroll top position. It should bring me back to the same tab, with the same scrolling position I was in (this last point concerns the private tab as well).
- [x] After I ignore a public folder, it bumps me back to the private tab - should stay on public (same for Unignore)
- [x] Ignored folder sections should stay open if I opened them - right now they collapse if I go to an inner folder and go back

 Ignored folders:
- [ ] Avatars should be at 50% opacity (desktop done)
- [ ] Text that shows up when you expand: this looks semibold? Should be Lato regular (regular body small on dark)
Top tabs:
- [ ] change font weight of private/ and public/ to semibold
- [ ] When scrolling - maintain 1px line underneath the tabbed headers so it looks separated from the content below (see more general ticket  DESKTOP-1307 TO DO  to fix list dividers)
- [ ] Interior folder view:
- [ ] Add 64px padding around the text area so that longer folder names don't crash into the right-hand nav
- [ ] When the folder name wraps to two lines, it crashes into to avatars, and then when it wraps to three lines, it crashes into avatars + avatars then crash into back button (see attached). Let's have this area expand downward instead.
- [ ] Let's stack "open" and "ignore" buttons on top of each other with open on top, it's weird to have them next to each other with the Ignore first.
- [ ] Ignore button on private folders should follow the "Secondary for dark backgrounds" button style: https://zpl.io/2rqNgg
- [ ] Divider is missing underneath section divider, should be white 5% on dark blue and black 5% on white. See: https://zpl.io/Z1008aU. And it should also be here when closed: https://zpl.io/TyTsH. Devices tab also has it wrong (only when open).
- [ ] Little caret not aligned with section header. Push down of about 4px.
- [ ] Folder row: Open link should get underlined on hover
- [ ] Page background should be darkBlue3 (#0a3052) - the darkBlue (#195080) should only go on the row itself.
- [ ] Damier pattern on retina screens looks bad - we should use the @2x version on retina screens
- [ ] Row background should be darkBlue4
- [ ] Folder title should be white_40
- [ ] Avatars should sit on a midnightBlue background and then be turned down to 50% opacity (if no background, we will see the damier pattern behind, which we don't want)
- [ ] When on the public tab, the public/ title should be black 75% and the private/ title should be black 60%
- [ ] Open link missing on hover (white on white) - design: https://zpl.io/1G9mVx
- [ ] If you have a long folder list (I have a long list of public folders), clicking the ignore expands it but you don't see that it actually expanded until you scroll. Can we add in a little bit of scrolling (+ ease-in animation) upon click to expand and show you what just showed up? If this is unclear just swing by my desk and I'll explain 
Other:
- [ ] On avatars: Weird aliasing around avatar images that looks like a subtle white stroke around them (ticket   DESKTOP-1041 TO DO  )
- [ ] On group folders, avatar should be the group icon and expand to all avatars on hover with a nice ease-in animation
- [ ] Damier pattern on the left for ignored and locked private folders is a different one, I added it to the styleguide: https://zpl.io/1hpA2P (scroll all the way down) (take @2x version for retina screens too)
- [ ] Group icon and has-stuff icon for ignored or locked folders are different (darker) - assets available on the Zeplin sheet above.
- [ ] Ignored public folders style: (all detailed on Zeplin here: https://zpl.io/Z2p7znW - section Folder list item)
- [ ] Left column background should be yellowGreen3
- [ ] Folder title should be yellowGreen2_75 (< new color!)
- [ ] row background should be white_40
- [ ] Group icon and has-stuff icon are different (more faded) - assets available on the Zeplin sheet above.
- [ ] Avatars should be 50% opaque
- [ ] I clicked "ignore" on my own public folder and it let me! Ahh! Maybe we should not surface that button for my own personal, permanent folders, unless we plan to allow for this kind of ignoring?
- [ ] When I clicked "open folder" on an ignored folder it caused the app to seize up a bit - maybe just some weird latency caused by the fact that you're also "un-ignoring" it once you click it?
- [ ] * Inner ignored folder pages: should we add that text again? "This folder won't show up on your computer and  you won't receive alerts about it. "
- [ ] Check mobile

- [ ] ~~When I tab between folders in a the same app session, it should remember the scroll position of where I was - it looks like now it remembers the same scroll position for both tabs, so if I scroll one up, it scrolls the other tab up.~~ [a lot more work than we can do in this ticket]

### CODE REVIEW

**Comment by cjb** [comment]
Please put [skip-ci] in the PR subject to avoid unwanted CI builds, thanks.

**Comment by keybase-ci-visdiff** [comment]
:mag_right: The commits d8e38aa1b972...e1a6bbf03e9b introduced some visual changes on linux:
 * Changed: **Folders_TLF-Normal_Private** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1469546091163-d8e38aa1b972-e1a6bbf03e9b-linux/Folders_TLF-Normal_Private-d8e38aa1b972.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1469546091163-d8e38aa1b972-e1a6bbf03e9b-linux/Folders_TLF-Normal_Private-e1a6bbf03e9b.png)  
   Folders_TLF-Normal_Private comparison

**Comment by keybase-ci-visdiff** [comment]
:mag_right: The commits d8e38aa1b972...570fac544396 introduced some visual changes on linux:
 * Changed: **Menubar-Public_Truncated** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1469558170807-d8e38aa1b972-570fac544396-linux/Menubar-Public_Truncated-d8e38aa1b972.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1469558170807-d8e38aa1b972-570fac544396-linux/Menubar-Public_Truncated-570fac544396.png)  
   Menubar-Public_Truncated comparison
 * Changed: **Menubar-Public_Normal** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1469558170807-d8e38aa1b972-570fac544396-linux/Menubar-Public_Normal-d8e38aa1b972.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1469558170807-d8e38aa1b972-570fac544396-linux/Menubar-Public_Normal-570fac544396.png)  
   Menubar-Public_Normal comparison
 * Changed: **Menubar-Public_Menu_Showing** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1469558170807-d8e38aa1b972-570fac544396-linux/Menubar-Public_Menu_Showing-d8e38aa1b972.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1469558170807-d8e38aa1b972-570fac544396-linux/Menubar-Public_Menu_Showing-570fac544396.png)  
   Menubar-Public_Menu_Showing comparison
 * Changed: **Menubar-Private_Truncated** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1469558170807-d8e38aa1b972-570fac544396-linux/Menubar-Private_Truncated-d8e38aa1b972.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1469558170807-d8e38aa1b972-570fac544396-linux/Menubar-Private_Truncated-570fac544396.png)  
   Menubar-Private_Truncated comparison
 * Changed: **Menubar-Private_Normal** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1469558170807-d8e38aa1b972-570fac544396-linux/Menubar-Private_Normal-d8e38aa1b972.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1469558170807-d8e38aa1b972-570fac544396-linux/Menubar-Private_Normal-570fac544396.png)  
   Menubar-Private_Normal comparison
 * Changed: **Menubar-Private_Menu_Showing** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1469558170807-d8e38aa1b972-570fac544396-linux/Menubar-Private_Menu_Showing-d8e38aa1b972.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1469558170807-d8e38aa1b972-570fac544396-linux/Menubar-Private_Menu_Showing-570fac544396.png)  
   Menubar-Private_Menu_Showing comparison
 * Changed: **Folders_TLF-Normal_Public** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1469558170807-d8e38aa1b972-570fac544396-linux/Folders_TLF-Normal_Public-d8e38aa1b972.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1469558170807-d8e38aa1b972-570fac544396-linux/Folders_TLF-Normal_Public-570fac544396.png)  
   Folders_TLF-Normal_Public comparison
 * Changed: **Folders_TLF-Normal_Private** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1469558170807-d8e38aa1b972-570fac544396-linux/Folders_TLF-Normal_Private-d8e38aa1b972.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1469558170807-d8e38aa1b972-570fac544396-linux/Folders_TLF-Normal_Private-570fac544396.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1469558170807-d8e38aa1b972-570fac544396-linux/Folders_TLF-Normal_Private.png)

**Comment by keybase-ci-visdiff** [comment]
:mag_right: The commits d8e38aa1b972...07d4d9205e96 introduced some visual changes on linux:
 * Changed: **Menubar-Public_Truncated** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1469563180944-d8e38aa1b972-07d4d9205e96-linux/Menubar-Public_Truncated-d8e38aa1b972.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1469563180944-d8e38aa1b972-07d4d9205e96-linux/Menubar-Public_Truncated-07d4d9205e96.png)  
   Menubar-Public_Truncated comparison
 * Changed: **Menubar-Public_Normal** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1469563180944-d8e38aa1b972-07d4d9205e96-linux/Menubar-Public_Normal-d8e38aa1b972.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1469563180944-d8e38aa1b972-07d4d9205e96-linux/Menubar-Public_Normal-07d4d9205e96.png)  
   Menubar-Public_Normal comparison
 * Changed: **Menubar-Public_Menu_Showing** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1469563180944-d8e38aa1b972-07d4d9205e96-linux/Menubar-Public_Menu_Showing-d8e38aa1b972.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1469563180944-d8e38aa1b972-07d4d9205e96-linux/Menubar-Public_Menu_Showing-07d4d9205e96.png)  
   Menubar-Public_Menu_Showing comparison
 * Changed: **Menubar-Private_Truncated** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1469563180944-d8e38aa1b972-07d4d9205e96-linux/Menubar-Private_Truncated-d8e38aa1b972.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1469563180944-d8e38aa1b972-07d4d9205e96-linux/Menubar-Private_Truncated-07d4d9205e96.png)  
   Menubar-Private_Truncated comparison
 * Changed: **Menubar-Private_Normal** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1469563180944-d8e38aa1b972-07d4d9205e96-linux/Menubar-Private_Normal-d8e38aa1b972.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1469563180944-d8e38aa1b972-07d4d9205e96-linux/Menubar-Private_Normal-07d4d9205e96.png)  
   Menubar-Private_Normal comparison
 * Changed: **Menubar-Private_Menu_Showing** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1469563180944-d8e38aa1b972-07d4d9205e96-linux/Menubar-Private_Menu_Showing-d8e38aa1b972.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1469563180944-d8e38aa1b972-07d4d9205e96-linux/Menubar-Private_Menu_Showing-07d4d9205e96.png)  
   Menubar-Private_Menu_Showing comparison
 * Changed: **Folders_TLF-Normal_Public** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1469563180944-d8e38aa1b972-07d4d9205e96-linux/Folders_TLF-Normal_Public-d8e38aa1b972.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1469563180944-d8e38aa1b972-07d4d9205e96-linux/Folders_TLF-Normal_Public-07d4d9205e96.png)  
   Folders_TLF-Normal_Public comparison
 * Changed: **Folders_TLF-Normal_Private** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1469563180944-d8e38aa1b972-07d4d9205e96-linux/Folders_TLF-Normal_Private-d8e38aa1b972.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1469563180944-d8e38aa1b972-07d4d9205e96-linux/Folders_TLF-Normal_Private-07d4d9205e96.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1469563180944-d8e38aa1b972-07d4d9205e96-linux/Folders_TLF-Normal_Private.png)

**Pull request closed without merging**
