### PR TITLE
expose dns proof

### PR DESCRIPTION
**Pull request by chrisnojima**
@keybase/react-hackers originally we made dns proofs basically look 100% like web proofs, but they're not the same

### CODE REVIEW

**Comment by cjb** [comment]
Is the `else if` branch necessary?

**Comment by chrisnojima** [comment]
shouldn't be, i'll remove it

**Comment by chrisnojima** [comment]
updated @cjb

**Comment by cjb** [comment]
:thumbsup: (untested)

**Comment by chrisnojima** [comment]
i verified max's tracker looks fine and acts like i'd expect, merging

**Pull request merged**
