### PR TITLE
add txID to MessageClientHeader

### PR DESCRIPTION
**Pull request by mmou**

### CODE REVIEW

**Comment by mmaxim** [comment]
I don’t think so, this value is supposed to just  get used by the server.

**Comment by mlsteele** [comment]
(This project is already a mitigation against malicious senders)
Without that check the malicious sender can fool the server into fooling the recipient client. The sender sends 2000 XLM (txA) and then 1 XLM (txB) to the recipient. The sender sends two chat messages. On the outside are txA and txB. But on the inside both messages contain txA. To the recipient it looks like they received 4000 XLM.

**Comment by mmou** [comment]
actually using (and verifying) this new txid value is in a separate ticket!

**Comment by mlsteele** [comment]
CI has failed twice on kbfs-server

**Comment by joshblum** [comment]
Need to merge master to fix ci

**Pull request merged**
