### PR TITLE
Using images instead of font icon to avoid selection bugs

### PR DESCRIPTION
**Pull request by gabriel**
We've been trying to use CSS visibility: hidden to workaround user-select not working in Chrome (for copy/paste, see https://bugs.chromium.org/p/chromium/issues/detail?id=147490), but this doesn't work for selections from double or triple clicks, see https://keybase.atlassian.net/browse/DESKTOP-2542 and https://keybase.atlassian.net/browse/DESKTOP-2582.

We can avoid all these selection issues if we use an icon image instead of icon font character in this particular case for the message action button. Chrome will not consider it for copy/paste and all these selection issues/weirdness/bugs go away.

### CODE REVIEW

**Comment by keybase-ci-visdiff** [comment]
The commits b6c078b8b36a...2841e4a6ee67 introduce visual changes on linux. <details><summary>:mag_right: 30 changed</summary>

 * Changed: **Text_Message-sent_You** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Text_Message-sent_You-b6c078b8b36a.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Text_Message-sent_You-2841e4a6ee67.png)  
   Text_Message-sent_You comparison
 * Changed: **Text_Message-sent_Not_Following** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Text_Message-sent_Not_Following-b6c078b8b36a.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Text_Message-sent_Not_Following-2841e4a6ee67.png)  
   Text_Message-sent_Not_Following comparison
 * Changed: **Text_Message-sent_Following** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Text_Message-sent_Following-b6c078b8b36a.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Text_Message-sent_Following-2841e4a6ee67.png)  
   Text_Message-sent_Following comparison
 * Changed: **Text_Message-sent_Broken** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Text_Message-sent_Broken-b6c078b8b36a.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Text_Message-sent_Broken-2841e4a6ee67.png)  
   Text_Message-sent_Broken comparison
 * Changed: **Text_Message-pending_You** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Text_Message-pending_You-b6c078b8b36a.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Text_Message-pending_You-2841e4a6ee67.png)  
   Text_Message-pending_You comparison
 * Changed: **Text_Message-pending_Not_Following** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Text_Message-pending_Not_Following-b6c078b8b36a.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Text_Message-pending_Not_Following-2841e4a6ee67.png)  
   Text_Message-pending_Not_Following comparison
 * Changed: **Text_Message-pending_Following** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Text_Message-pending_Following-b6c078b8b36a.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Text_Message-pending_Following-2841e4a6ee67.png)  
   Text_Message-pending_Following comparison
 * Changed: **Text_Message-pending_Broken** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Text_Message-pending_Broken-b6c078b8b36a.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Text_Message-pending_Broken-2841e4a6ee67.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Text_Message-pending_Broken.png)
 * Changed: **Text_Message-from_revoked_device** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Text_Message-from_revoked_device-b6c078b8b36a.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Text_Message-from_revoked_device-2841e4a6ee67.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Text_Message-from_revoked_device.png)
 * Changed: **Text_Message-failed_You** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Text_Message-failed_You-b6c078b8b36a.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Text_Message-failed_You-2841e4a6ee67.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Text_Message-failed_You.png)
 * Changed: **Text_Message-failed_Not_Following** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Text_Message-failed_Not_Following-b6c078b8b36a.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Text_Message-failed_Not_Following-2841e4a6ee67.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Text_Message-failed_Not_Following.png)
 * Changed: **Text_Message-failed_Following** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Text_Message-failed_Following-b6c078b8b36a.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Text_Message-failed_Following-2841e4a6ee67.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Text_Message-failed_Following.png)
 * Changed: **Text_Message-failed_Broken** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Text_Message-failed_Broken-b6c078b8b36a.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Text_Message-failed_Broken-2841e4a6ee67.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Text_Message-failed_Broken.png)
 * Changed: **Stacked_Text_Message-Stacked_two_messages** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Stacked_Text_Message-Stacked_two_messages-b6c078b8b36a.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Stacked_Text_Message-Stacked_two_messages-2841e4a6ee67.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Stacked_Text_Message-Stacked_two_messages.png)
 * Changed: **Stacked_Text_Message-Stacked_someone_else_two_sent** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Stacked_Text_Message-Stacked_someone_else_two_sent-b6c078b8b36a.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Stacked_Text_Message-Stacked_someone_else_two_sent-2841e4a6ee67.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Stacked_Text_Message-Stacked_someone_else_two_sent.png)
 * Changed: **Stacked_Text_Message-Stacked_one_sent_one_pending** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Stacked_Text_Message-Stacked_one_sent_one_pending-b6c078b8b36a.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Stacked_Text_Message-Stacked_one_sent_one_pending-2841e4a6ee67.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Stacked_Text_Message-Stacked_one_sent_one_pending.png)
 * Changed: **Stacked_Text_Message-Stacked_one_sent_one_failed** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Stacked_Text_Message-Stacked_one_sent_one_failed-b6c078b8b36a.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Stacked_Text_Message-Stacked_one_sent_one_failed-2841e4a6ee67.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Stacked_Text_Message-Stacked_one_sent_one_failed.png)
 * Changed: **Icon-Icon_Image** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Icon-Icon_Image-b6c078b8b36a.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Icon-Icon_Image-2841e4a6ee67.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Icon-Icon_Image.png)
 * Changed: **Attachment_Message-Basic_Uploading** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Attachment_Message-Basic_Uploading-b6c078b8b36a.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Attachment_Message-Basic_Uploading-2841e4a6ee67.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Attachment_Message-Basic_Uploading.png)
 * Changed: **Attachment_Message-Basic_Preview_Image_Pending** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Attachment_Message-Basic_Preview_Image_Pending-b6c078b8b36a.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Attachment_Message-Basic_Preview_Image_Pending-2841e4a6ee67.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Attachment_Message-Basic_Preview_Image_Pending.png)
 * Changed: **Attachment_Message-Basic_Preview_Image_Not_Downloaded** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Attachment_Message-Basic_Preview_Image_Not_Downloaded-b6c078b8b36a.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Attachment_Message-Basic_Preview_Image_Not_Downloaded-2841e4a6ee67.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Attachment_Message-Basic_Preview_Image_Not_Downloaded.png)
 * Changed: **Attachment_Message-Basic_Preview_Image_Failed** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Attachment_Message-Basic_Preview_Image_Failed-b6c078b8b36a.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Attachment_Message-Basic_Preview_Image_Failed-2841e4a6ee67.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Attachment_Message-Basic_Preview_Image_Failed.png)
 * Changed: **Attachment_Message-Basic_Preview_Image_Downloaded** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Attachment_Message-Basic_Preview_Image_Downloaded-b6c078b8b36a.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Attachment_Message-Basic_Preview_Image_Downloaded-2841e4a6ee67.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Attachment_Message-Basic_Preview_Image_Downloaded.png)
 * Changed: **Attachment_Message-Basic_Not_loaded** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Attachment_Message-Basic_Not_loaded-b6c078b8b36a.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Attachment_Message-Basic_Not_loaded-2841e4a6ee67.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Attachment_Message-Basic_Not_loaded.png)
 * Changed: **Attachment_Message-Basic_Generic_File_sent** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Attachment_Message-Basic_Generic_File_sent-b6c078b8b36a.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Attachment_Message-Basic_Generic_File_sent-2841e4a6ee67.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Attachment_Message-Basic_Generic_File_sent.png)
 * Changed: **Attachment_Message-Basic_Generic_File_Uploading** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Attachment_Message-Basic_Generic_File_Uploading-b6c078b8b36a.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Attachment_Message-Basic_Generic_File_Uploading-2841e4a6ee67.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Attachment_Message-Basic_Generic_File_Uploading.png)
 * Changed: **Attachment_Message-Basic_Generic_File_Failed** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Attachment_Message-Basic_Generic_File_Failed-b6c078b8b36a.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Attachment_Message-Basic_Generic_File_Failed-2841e4a6ee67.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Attachment_Message-Basic_Generic_File_Failed.png)
 * Changed: **Attachment_Message-Basic_Generic_File_Downloading** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Attachment_Message-Basic_Generic_File_Downloading-b6c078b8b36a.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Attachment_Message-Basic_Generic_File_Downloading-2841e4a6ee67.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Attachment_Message-Basic_Generic_File_Downloading.png)
 * Changed: **Attachment_Message-Basic_Generic_File_Downloaded** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Attachment_Message-Basic_Generic_File_Downloaded-b6c078b8b36a.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Attachment_Message-Basic_Generic_File_Downloaded-2841e4a6ee67.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Attachment_Message-Basic_Generic_File_Downloaded.png)
 * Changed: **Attachment_Message-Basic_Downloading** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Attachment_Message-Basic_Downloading-b6c078b8b36a.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Attachment_Message-Basic_Downloading-2841e4a6ee67.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484861513739-b6c078b8b36a-2841e4a6ee67-linux/Attachment_Message-Basic_Downloading.png)
</summary>

**Comment by gabriel** [comment]
@keybase/react-hackers

**Comment by chrisnojima** [comment]
don't we actually intercept the copy command and process this stuff, can't we just clean it up there and not make this type of change

**Comment by chrisnojima** [comment]
https://github.com/keybase/client/blob/master/shared/chat/conversation/list.desktop.js#L341

**Comment by gabriel** [comment]
I think using images here instead of doing extra processing of the text is wayyyyy better.

**Comment by gabriel** [comment]
I was aware of the Selection object onCopyCapture and I actually went down the road of traversing the Selection object to get the text content. It was a bit of a rabbit whole, and eventually came to the conclusion swapping out 2 icon characters for images was a way easier fix/workaround.

**Comment by chrisnojima** [comment]
you can get the text and strip out the characters you don't have to go down the selection object

**Comment by chrisnojima** [comment]
can't we just move this action button into a different dom element so its not captured by the selection anyways

**Comment by gabriel** [comment]
I think I tried some alternate layouts without success given selections can occur across react-virtualized elements but I could have missed something. Maybe someone else wants to take a stab?

**Comment by chrisnojima** [comment]
lets chat on slack and not through pr comments

**Comment by chrisnojima** [comment]
also if i double click and copy i get my name and timestamp and a bunch of other crap so this whole thing is a bigger problem

**Pull request closed without merging**
