### PR TITLE
Fix TrackToken, Prove engines to use cached keys

### PR DESCRIPTION
**Pull request by patrickxb**
After paper provision, tracking works without passphrase
prompt.   Proofs should work too.

r? @maxtaco

### CODE REVIEW

**Comment by maxtaco** [comment]
was this code using older/outmoded interfaces to the secret keyring?

**Comment by patrickxb** [comment]
It was unlocking the locked key directly instead of using libkb.Keyrings functions.

Mainly because it was getting a locked key in order to get the signing KID for a tracking, proof statement then unlocking it later.

**Comment by maxtaco** [comment]
ah ok. so does it still get the locked key first?

**Comment by patrickxb** [comment]
It does.  I was going to change, but local tracks don't need the unlocked key, and I didn't want to screw around too much with something so critical.

**Comment by maxtaco** [comment]
👍

**Pull request merged**
