### PR TITLE
Show update type in UpdatePrompt

### PR DESCRIPTION
**Pull request by patrickxb**
r? @gabriel @maxtaco

### CODE REVIEW

**Comment by maxtaco** [comment]
And this comes all the way from the API server?

**Comment by patrickxb** [comment]
I talked to @gabriel about this.  Currently there's a json file in an s3 bucket and it has the update type.  The API server isn't being used for updates...

**Comment by gabriel** [comment]
yeah currently comes from update json in s3 bucket: https://s3.amazonaws.com/prerelease.keybase.io/update-darwin-prod.json

this file is created and uploaded automatically after each prerelease (and nightly) build

:ship:

**Comment by maxtaco** [comment]
:+1:

**Pull request merged**
