### PR TITLE
packaging: kbfs-beta is no longer needed

### PR DESCRIPTION
**Pull request by strib**
Issue: KBFS-1074

### CODE REVIEW

**Comment by strib** [comment]
r @oconnor663?
cc: @gabriel

**Comment by keybase-ci-visdiff** [comment]
:mag_right: No visual changes found as a result of these commits.

**Comment by oconnor663** [comment]
LGTM. If you want you could do a staging Linux build to test :-D

**Comment by gabriel** [comment]
lg2m

**Comment by keybase-ci-visdiff** [comment]
:mag_right: No visual changes found as a result of these commits.

**Pull request merged**
