### PR TITLE
Make following green again: Avoid stale bootstrap info with one more try

### PR DESCRIPTION
**Pull request by zanderz**
If bootstrap is attempted before the service has established contact with the server, stale info is returned from its cache and never refreshed. This adds an argument to indicate cached info, and a 1 time retry after 10 seconds in that case, which makes the following info fresh again.

To repro the original bug, stop all Keybase processes and erase the leveldb, then start the GUI. It will start the services and ask for bootstrap info before it has established server coms, getting stale/empty cache info, and all the usernames will be blue for those you follow. With this change, they're green again.

### CODE REVIEW

**Comment by zanderz** [comment]
so how do we know when it is refreshed? is there a mechanism already?

**Comment by chrisnojima** [comment]
we should get some kind of notification from core, dunno if an appropriate one exists already. maybe core should just tell us when teh follow state changes if its different than its cache cause then we'd need to do nothing

**Comment by zanderz** [comment]
Looks like reachability should do it, I'll try that

**Comment by zanderz** [comment]
@chrisnojima this is a lot simpler! Seems to also work.

**Comment by patrickxb** [comment]
Is there anything you wanted me to look at?  Looks like all JS.

**Comment by zanderz** [comment]
thanks @patrickxb , I had proposed a core change before this simpler one.

**Pull request merged**
