### PR TITLE
First time chat animation

### PR DESCRIPTION
**Pull request by gabriel**
Creates a header cell for the chat secure animation.
Made a `cellMessageStartIndex` constant for the cell messages offset.

In this PR, the secure chat header image is always present, so you'll see it if you scroll up all the way to the top (if all messages loaded). There is no special logic about whether the chat is new or not, (and if not new hiding it). We could add that in but might be unnecessary since maybe this is the desired behavior?

### CODE REVIEW

**Comment by gabriel** [comment]
@keybase/react-hackers 

cc @cecileboucheron

**Comment by keybase-ci-visdiff** [comment]
The commits 4fee5e945e13...e51d6729460f introduce visual changes on linux. <details><summary>:mag_right: 3 changed</summary>

 * Changed: **Icon-Icon_Image** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484775962070-4fee5e945e13-e51d6729460f-linux/Icon-Icon_Image-4fee5e945e13.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484775962070-4fee5e945e13-e51d6729460f-linux/Icon-Icon_Image-e51d6729460f.png)  
   Icon-Icon_Image comparison
 * Changed: **Chat_List-Normal** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484775962070-4fee5e945e13-e51d6729460f-linux/Chat_List-Normal-4fee5e945e13.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484775962070-4fee5e945e13-e51d6729460f-linux/Chat_List-Normal-e51d6729460f.png)  
   Chat_List-Normal comparison
 * Changed: **Chat_List-Empty** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484775962070-4fee5e945e13-e51d6729460f-linux/Chat_List-Empty-4fee5e945e13.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484775962070-4fee5e945e13-e51d6729460f-linux/Chat_List-Empty-e51d6729460f.png)  
   Chat_List-Empty comparison
</summary>

**Comment by keybase-ci-visdiff** [comment]
The commits 4fee5e945e13...9918a48cb9df introduce visual changes on linux. <details><summary>:mag_right: 3 changed</summary>

 * Changed: **Icon-Icon_Image** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484776394670-4fee5e945e13-9918a48cb9df-linux/Icon-Icon_Image-4fee5e945e13.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484776394670-4fee5e945e13-9918a48cb9df-linux/Icon-Icon_Image-9918a48cb9df.png)  
   Icon-Icon_Image comparison
 * Changed: **Chat_List-Normal** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484776394670-4fee5e945e13-9918a48cb9df-linux/Chat_List-Normal-4fee5e945e13.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484776394670-4fee5e945e13-9918a48cb9df-linux/Chat_List-Normal-9918a48cb9df.png)  
   Chat_List-Normal comparison
 * Changed: **Chat_List-Empty** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484776394670-4fee5e945e13-9918a48cb9df-linux/Chat_List-Empty-4fee5e945e13.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484776394670-4fee5e945e13-9918a48cb9df-linux/Chat_List-Empty-9918a48cb9df.png)  
   Chat_List-Empty comparison
</summary>

**Comment by cecileboucheron** [comment]
I think the GIF is only @1x, we should have it retina-friendly: https://cl.ly/3N150c2p2z2M

**Comment by cecileboucheron** [comment]
Also the one we see when loading an existing conversation should be the "Securing..." looping one - right now it's the "Secure connection established".

**Comment by gabriel** [comment]
I'll start another PR with these fixes.

**Pull request merged**
