### PR TITLE
Bundle any existing trace files during a log send

### PR DESCRIPTION
**Pull request by akalin-keybase**
Put it in a single .tar.gz to upload to the server.

### CODE REVIEW

**Comment by akalin-keybase** [comment]
Fixed CI, ready for review!

**Comment by akalin-keybase** [comment]
@patrickxb ptal, now the trace button is behind a secret handshake (#10705). Also r? @keybase/react-hackers for the js side

**Comment by patrickxb** [comment]
I'm still concerned about users sending in potentially sensitive data.

If the button to generate a trace file is now hidden and only admins will use it, it seems fine to get the trace files off via usb during performance testing.

@cjb i'm curious what you think.

**Comment by akalin-keybase** [comment]
Summarized today's discussion on the issue, but AFAIK @cjb is also on board.

**Pull request merged**
