### PR TITLE
Return immediately in GetSecretKeys RPC endpoint if in production

### PR DESCRIPTION
**Pull request by patrickxb**
r? @oconnor663 or @maxtaco

### CODE REVIEW

**Comment by keybase-ci-visdiff** [comment]
:mag_right: No visual changes found as a result of these commits.

**Comment by maxtaco** [comment]
👍

**Comment by oconnor663** [comment]
Thanks :+1:

**Comment by keybase-ci-visdiff** [comment]
:mag_right: No visual changes found as a result of these commits.

**Pull request merged**
