### PR TITLE
Fix push notifications screen

### PR DESCRIPTION
**Pull request by gabriel**
Fixed for smallest screen iPhone SE.

2017-04-10 at 2 31 pm

### CODE REVIEW

**Comment by gabriel** [comment]
@keybase/react-hackers

**Comment by gabriel** [comment]
@cecileboucheron maybe we want to make the graphic smaller

**Comment by cecileboucheron** [comment]
Ok I'll decrease the size a bit.
Unrelated: the "very" should be Semibold italic, not just italic.

**Comment by gabriel** [comment]
@cecileboucheron The "very" is BodySemiboldItalic. It appears making something italic makes it less bold?

**Comment by cecileboucheron** [comment]
Are the font files missing maybe? I'll make a ticket.
I reexported the illustration in smaller size (the name changed as a consequence).

**Comment by gabriel** [comment]
2017-04-10 at 3 14 pm

**Comment by cecileboucheron** [comment]
👍

**Pull request merged**
