### PR TITLE
Disable OS X builds, Jenkins will do them

### PR DESCRIPTION
**Pull request by cjb**
@jzila @oconnor663 r?

This PR takes out the conditionals for Linux vs. OS X and only runs the Linux sections, nothing else.

### CODE REVIEW

**Comment by oconnor663** [comment]
Do we need to update the "wait for CI" bits to expect a different set of test runs?

**Comment by oconnor663** [comment]
Other than that q, this LGTM.

**Comment by jzila** [comment]
Lgtm

**Comment by cjb** [comment]
Yes, I'll need to update those separately.  Thanks!

**Pull request merged**
