### PR TITLE
visdiff potential font & focus fixes

### PR DESCRIPTION
**Pull request by chromakode**
:eyeglasses: @keybase/react-hackers

### CODE REVIEW

**Comment by chrisnojima** [comment]
👍

**Comment by chromakode** [comment]
@MarcoPolo Flow doesn't know about the `document.fonts` API. Would you please take a gander at https://github.com/keybase/client/pull/3168/commits/c838d37143bd50efb01fc0045f300af08c41d075 and let me know if I've gone about this the right way?

**Comment by keybase-ci-visdiff** [comment]
:mag_right: The commits f8bd1e628d2c...13eb0bd20e4b introduced some visual changes:
 * Changed: **Username_Email_Login-Name_Error** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1466631365882-f8bd1e628d2c-13eb0bd20e4b/Username_Email_Login-Name_Error-f8bd1e628d2c.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1466631365882-f8bd1e628d2c-13eb0bd20e4b/Username_Email_Login-Name_Error-13eb0bd20e4b.png)  
   Username_Email_Login-Name_Error comparison

**Comment by chromakode** [comment]
This visdiff is somewhat expected. The "before" screenshot isn't running the `window.blur()` code :(

**Comment by chrisnojima** [comment]
Actually we shouldn't blur as we won't be able to tell when inputs look
wrong. Maybe lets do the style thing?

**Comment by chromakode** [comment]
@chrisnojima you mean for testing input focus styles? It doesn't look like we have any at the moment, otherwise they'd have shown in the visdiff. The problem with the `text-shadow` trick is that you specify the text color in the css rule -- the input text will no longer display its styled color.

**Comment by chrisnojima** [comment]
We could have a helper which wraps this which will apply color or the
shadow color so it would work. I mean our input components with the
floating text when focused with no input. Not a big deal though

**Comment by chromakode** [comment]
Yeah, we should definitely get screenshots of those input states. However, we're not covering them right now, so I think we should defer figuring that out and go with blurring for now, rather than change the way rendering works with a `text-shadow` hack.

I think that testing those focus states should be explicit. In the future, we should use something like the `afterMount` callback to deliberately focus the input element. In those specific cases we could manually focus the desired element and apply a hack to hide the cursor.

**Comment by chrisnojima** [comment]
thats fine

**Pull request merged**
