### PR TITLE
Wix Jenkins builds

### PR DESCRIPTION
**Pull request by zanderz**
This also ended up including installer changes for the new updater UI components. 
Took a long time but jenkins builds are finishing, with signed packages + updaters.

Picking on my Wix/XML volunteers again, @oconnor663 and @chrisnojima

### CODE REVIEW

**Comment by oconnor663** [comment]
I think my ability to review WiX code by myself is basically zero, but I'd be happy to go through it together on Monday if there are any parts you'd like to talk about.

**Comment by chrisnojima** [comment]
yeah lets do a review together quick

**Comment by zanderz** [comment]
Just trying to follow protocol and not merge anything without a review. How would you guys like to proceed? should I put a bunch of line comments in here first?

**Comment by chrisnojima** [comment]
lets just do a hangouts quick

**Comment by oconnor663** [comment]
:ship: :)

**Pull request merged**
