### PR TITLE
global devtools shortcut for admin only

### PR DESCRIPTION
**Pull request by chrisnojima**
@keybase/react-hackers @mlsteele

### CODE REVIEW

**Comment by oconnor663** [comment]
Is there another way to get at the tools besides this key chord? Even if it's buried in a menu somewhere, it would be nice to be able to do this on a friend's machine if they were having trouble.

**Comment by chrisnojima** [comment]
Just turn on admin mode

**Comment by oconnor663** [comment]
That requires a process restart, right? Interesting error messages might get lost? Or maybe I'm full of crap and it's all in the logs :)

**Comment by chrisnojima** [comment]
That's the tradeoff

**Pull request merged**
