### PR TITLE
make percent-1s explicit in the teams code

### PR DESCRIPTION
**Pull request by maxtaco**

### CODE REVIEW

**Comment by mlsteele** [comment]
Pushed what I hope is a fix to ` func (t *TeamSigChainState) FindActiveInvite(name, typ string) (*keybase1.TeamInvite, error) {` so it can handle the old version. Also there's something fishy about this TeamInviteType variant.

```
  enum TeamInviteCategory {
    NONE_0,
    UNKNOWN_1,
    KEYBASE_2,
    EMAIL_3,
    SBS_4
  }

  variant TeamInviteType switch (TeamInviteCategory c) {
    case UNKNOWN: string;
    case SBS: TeamInviteSocialNetwork;
    default: void;
  }
```

**Comment by mlsteele** [comment]
So.. I approve if this passes CI.

**Comment by maxtaco** [comment]
👍

**Comment by maxtaco** [comment]
Tracked on jira: CORE-5982

**Pull request merged**
