### PR TITLE
fix variable/method names in avdl

### PR DESCRIPTION
**Pull request by songgao**

### CODE REVIEW

**Comment by maxtaco** [comment]
This change is going to be very challenging to roll out without breaking
chat. All legacy clients will have failures.

**Comment by songgao** [comment]
Is it because of the codec name changes? Names in Go code doesn't change at all.

**Comment by maxtaco** [comment]
Wire representation is different and you are going to have rpc procedure
not found errors.

**Comment by songgao** [comment]
I see. So shall we drop this for now then?

**Comment by songgao** [comment]
Although on the other hand we haven't released chat yet ...

**Comment by maxtaco** [comment]
If it matters then it should be done now but everything will break when it
goes in.

Once chat is live we never can make breaking changes like this one.

**Comment by songgao** [comment]
closing in favor of #5004

**Comment by gabriel** [comment]
We could do it Monday when everyone is together? If not, we're stuck with it forever :(

**Comment by songgao** [comment]
Yeah; sounds good!

**Comment by patrickxb** [comment]
To be clear, there are users using chat outside the company even though it hasn't been released.  This will likely cause them issues.

**Comment by songgao** [comment]
Yeah but it's not even released, and this is the same level of break that we've done in the past for chat since the soft launch. If we ever want the name fixed, now is a better time tha later unless we count on a V2 in the future.

**Comment by maxtaco** [comment]
@malgorithms says it's OK to break chat at the moment...

**Pull request closed without merging**
