### PR TITLE
WIP NOT WORKING AT ALL

### PR DESCRIPTION
**Pull request by chrisnojima**
This is so i can take some notes as to where this is at.
Trying to get one bundle, just using the loopback/main which will start the daemon and kbfs. Starts the daemon in loopback mode and sets up the globalcontext such that getSocket returns the loopback channels and not a file based socket. We have a verndoring problem with client/kbfs where kbfs pulls in libkb also so same-objects are namespaced differently. attempting to blow away the conflicting vendor bundles but now waiting for fred to unify the go-frame-msgpack-rpc since they've diverged short term. pausing on this for now

### CODE REVIEW

**Comment by chrisnojima** [comment]
Update: So this build, i had to comment out the notification channel stuff. now we have to solve the problem of how does the js code talk to kbfs. here's the idea

we need a new protocol layer that understands these new client commands. we'll need to do things like ls/cat/mkdir etc. so we'll make a new avdl and protocols for these commands and find a way to inject this into the daemon. This way our wrapper code will just handle the init and handshake and how to deal with this code, but not have to peek into the msgpack decoding process and all of that since that already happens downstream in the daemon somewhere

**Comment by chrisnojima** [comment]
Also the vendoring thing was all done by hand. first blowing away all the stuff in my gopath, then moving all stuff from go/client and kbfs vendoring hoisted up, then bringing in the missing pieces. see if govend can do this for us sensibly

**Comment by strib** [comment]
@chrisnojima: Just FYI, if you're going to be expecting any update notifications to make their way to JS-land, you're going to have to cache the `libkbfs.Node` objects you care about in the same process as the Go (and potentially delete them from the cache once JS doesn't care about them anymore).  You're probably a long way off from thinking about those details, but just thought I'd mention it.

**Comment by chrisnojima** [comment]
Thanks for the heads up. Well likely have to build some kind of ref count
concept or something. For now I want ls /keybase/public/foo to work

**Comment by chrisnojima** [comment]
replaced by https://github.com/keybase/client/pull/2770

**Pull request closed without merging**
