### PR TITLE
Reset QR code on component mount

### PR DESCRIPTION
**Pull request by gabriel**
Reset QR code on component mount, as an alternative to https://github.com/keybase/client/pull/7371

### CODE REVIEW

**Comment by gabriel** [comment]
@keybase/react-hackers @chrisnojima

**Comment by keybase-ci-visdiff** [comment]
The commits 38572d55c1b8...8f360b354015 introduce visual changes on linux. <details><summary>:mag_right: 1 changed</summary>

 * Changed: **Tracker-New_user_Scroll_1** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1497466110758-38572d55c1b8-8f360b354015-linux/Tracker-New_user_Scroll_1-38572d55c1b8.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1497466110758-38572d55c1b8-8f360b354015-linux/Tracker-New_user_Scroll_1-8f360b354015.png)  
   Tracker-New_user_Scroll_1 comparison
</summary>

**Comment by chrisnojima** [comment]
i'm fine to do this just to close this out but i think its better philosophically for this to be driven by redux. 

1. This isn't like an uncontrolled input. In that case what you're typing doesn't really matter so it doesn't need to go into the store. All you care about is the ultimate output and not some temporary value. No external force will affect that value so its essentially invisible
1. Here we have ways in which this could be reset by external sources. The daemon could say its not valid, there could be some timeout, etc etc. If its in the component there's no good way for us to communicate this in (other than making some prop thats driven by redux, so why not just store this in redux in the first place)
1. If we wanted to test this logic it'll be easier to do it in redux

**Comment by keybase-ci-visdiff** [comment]
The commits e90914f4ba8b...d7fbe060368f introduce visual changes on linux. <details><summary>:mag_right: 1 changed</summary>

 * Changed: **Tracker-New_user_Scroll_1** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1497474665857-e90914f4ba8b-d7fbe060368f-linux/Tracker-New_user_Scroll_1-e90914f4ba8b.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1497474665857-e90914f4ba8b-d7fbe060368f-linux/Tracker-New_user_Scroll_1-d7fbe060368f.png)  
   Tracker-New_user_Scroll_1 comparison
</summary>

**Pull request merged**
