### PR TITLE
moving StatusCode enum into protocol to be shared

### PR DESCRIPTION
**Pull request by chrisnojima**
Also some code in pinentry didn't get ported over when we went to the unified remoteComponent so cancel wasn't working

@keybase/react-hackers

### CODE REVIEW

**Comment by chrisnojima** [comment]
The original update was here: https://github.com/keybase/client/commit/c48745ca9bcf72dcb40b20369cfaa78c8548901b#diff-f03422b48de305c44ff69d8a5e41df72

**Comment by MarcoPolo** [comment]
:+1:

**Comment by chrisnojima** [comment]
@patrickxb can you look at the protocol/go stuff

**Comment by patrickxb** [comment]
It's kind of weird that these constants are now defined in three places: iced, constants.go, and now protocol.

I'm guessing you did it this way to avoid changing core code from libkb.SCOk to keybase1.StatusCode_SCOk?

**Comment by chrisnojima** [comment]
I only want it in protocol really. before it was copied in 3 places (iced / constants / and in our js code). i left the constants.go enums so i didn't need to change the calling code but i'm happy to change that if you don't care

**Comment by chrisnojima** [comment]
also with it in protocol we could have iced pull it in also

**Comment by patrickxb** [comment]
One place would be ideal, but I'm fine with this as a transition toward that.

**Pull request merged**
