### PR TITLE
send up homeRefreshUI on gregor updates

### PR DESCRIPTION
**Pull request by maxtaco**
- trigger home screen refreshers whenever we get a home.update gregor IBM

### CODE REVIEW

**Comment by maxtaco** [comment]
cc: @buoyad, this is for when the server tells Electron/RN to refresh....

**Comment by buoyad** [comment]
ok great, we will call `homeGetScreen` when this comes in with `markViewed: false`

**Comment by maxtaco** [comment]
I think it is more like the the home screen is currently showing and this
comes in, then you should refresh the home screen

For instance if on your other device you add a paper key, that row can be
dismissed on this device.  I think you might event want markViewed:true if
in the foreground.

**Comment by maxtaco** [comment]
Event -> even

**Comment by buoyad** [comment]
OK, I made it so it will only call `homeGetScreen` if the screen is in the foreground, with `markViewed: true`. Will we also get a badgeState update when this happens?

**Comment by maxtaco** [comment]
The badge updates happen independently, so yes, using the same mechanism as normal

**Pull request merged**
