### PR TITLE
Properly hide the dock icon

### PR DESCRIPTION
**Pull request by MarcoPolo**
@keybase/react-hackers 

Fixes the dock icon to only show up when there is an active window (e.g. the main window is open)

~~Edit: This needs to include remote components, so I'm changing this to a WIP for now~~

Edit: Fixed for remote components

### CODE REVIEW

**Comment by MarcoPolo** [comment]
@keybase/react-hackers now it's ready for review, thanks!

**Comment by chrisnojima** [comment]
Haven't looked at the code yet but do we want this behavior in milestone 2?
Doesn't this imply there will be no icon.

**Comment by MarcoPolo** [comment]
There will still be a menu bar icon. This just hides the dock icon when there is no window open.

Currently it keeps the dock icon when there is no window open, and that's useless because you can't do anything with that dock icon except focus on an invisible window. but that's a bug, and it was meant to have the behavior that's implemented here

**Comment by chrisnojima** [comment]
:+1:

**Pull request merged**
