### PR TITLE
Hook up "Add phone" in account settings

### PR DESCRIPTION
**Pull request by buoyad**
- "Add phone" -> Add modal -> Verify modal -> Success
- Show "Check your inbox!" banner when you hit verify on an email address
- [x] Finish verification flow
- [x] Hook up "Verify" for phone numbers in dropdown

~@ keybase/y2ksquad~

### CODE REVIEW

**Comment by jzila** [comment]
@buoyad might want to remove the at-y2ksquad tag until this is ready for review.

**Comment by buoyad** [comment]
@keybase/y2ksquad

**Comment by buoyad** [comment]
@keybase/react-hackers bump, this is all behind a feature flag and I want to get a polish PR based off this into the release (#18176).

**Comment by buoyad** [comment]
@chrisnojima I agree, pushed a change to organize them into sections of 
```
[dispatch]
[state / derived state]
[selectors]
[effects]
[callbacks]
```

Hopefully that makes them a bit easier to read. In retrospect maybe these should have been classes, we can revisit later.

**Pull request merged**
