### PR TITLE
avoid undefined behavior in Go assignments

### PR DESCRIPTION
**Pull request by oconnor663**
r? @maxtaco 

The behind-the-scenes initialization behavior of `hashToBytes` is kind of the real problem here, and we might want to clean that up rather than just making this minimal fix.

### CODE REVIEW

**Comment by keybase-ci-visdiff** [comment]
:mag_right: No visual changes found as a result of these commits.

**Comment by keybase-ci-visdiff** [comment]
:mag_right: No visual changes found as a result of these commits.

**Comment by maxtaco** [comment]
👍

**Comment by oconnor663** [comment]
Landed as ca023e2d6f9192fd8e923f3113ae4a11cda8b53a.

**Pull request closed without merging**
