### PR TITLE
protocol: add hidden files filter for simplefs

### PR DESCRIPTION
**Pull request by strib**
Issue: KBFS-2797

### CODE REVIEW

**Comment by strib** [comment]
@songgao @jzila maybe one of you can help me with flow errors?  Not urgent though.  https://ci.keyba.se/job/client/job/PR-10996/1/execution/node/257/log/

**Comment by strib** [comment]
> except you'll need to provide a filter now in any calls to the protocol

You shouldn't _have_ to, it's an optional param that should default to 0.  Flow is just being picky I guess.

**Comment by jzila** [comment]
Unless you can specify default values for function parameters in the protocol, the autogenerated RPCs on the JS side will require all parameters.

**Comment by strib** [comment]
Understood, but that only applies to calls from JS, not from "any calls to the protocol".

Can someone help me fix it?

**Comment by strib** [comment]
Oh, actually you already gave me the exact place to fix.  Lemme try.

**Comment by jzila** [comment]
Yeah sorry I meant from JS.

**Comment by strib** [comment]
> Yeah sorry I meant from JS.

How quickly you've become completely JS-ified and left us lowly Golang folk behind!

**Comment by jzila** [comment]
:innocent:

**Comment by jzila** [comment]
The code you'll want to add is `    filter: RPCTypes.simpleFSListFilter.noFilter,`

Song and I can integrate it from there.

**Comment by strib** [comment]
> Would it be useful to have another level that only hides macOS and potentially Windows system stuff that's not supposed to be changed by user?

Maybe, I really don't know.  Let's get the current design done and see how annoying it is.

**Pull request merged**
