### PR TITLE
Adding updater to launchd list commands

### PR DESCRIPTION
**Pull request by gabriel**
```sh
> keybase launchd list
keybase.service: Running (pid=3514) [Keybase]
keybase.kbfs: Running (pid=93495) [KBFS]
keybase.updater: Running (pid=1026) [Updater]
```

and

```sh
> keybase launchd list --format=json
{
  "service": [
    {
      "version": "",
      "label": "keybase.service",
      "pid": "3514",
      "lastExitStatus": "",
      "bundleVersion": "",
      "installStatus": 0,
      "installAction": 0,
      "status": {
        "code": 0,
        "name": "OK",
        "desc": "",
        "fields": null
      }
    }
  ],
  "kbfs": [
    {
      "version": "",
      "label": "keybase.kbfs",
      "pid": "93495",
      "lastExitStatus": "",
      "bundleVersion": "",
      "installStatus": 0,
      "installAction": 0,
      "status": {
        "code": 0,
        "name": "OK",
        "desc": "",
        "fields": null
      }
    }
  ],
  "updater": [
    {
      "version": "",
      "label": "keybase.updater",
      "pid": "1026",
      "lastExitStatus": "",
      "bundleVersion": "",
      "installStatus": 0,
      "installAction": 0,
      "status": {
        "code": 0,
        "name": "OK",
        "desc": "",
        "fields": null
      }
    }
  ]
}
```

### CODE REVIEW

**Comment by gabriel** [comment]
cc @maxtaco

**Comment by gabriel** [comment]
cc @keybase/updater-hackers

**Comment by maxtaco** [comment]
👍

**Comment by chrisnojima** [comment]
👍

**Pull request merged**
