### PR TITLE
bump the Linux packaging build to Go 1.7

### PR DESCRIPTION
**Pull request by oconnor663**
@cjb

### CODE REVIEW

**Comment by cjb** [comment]
@oconnor663 I guess if we want to do this by the book: please could you file a @jzila ticket asking for the Jenkins Linux hosts to be updated to 1.7, and then merge this in once there's been a successful CI run with 1.7?

**Comment by oconnor663** [comment]
@cjb sounds like John did this earlier and builds haven't started tanking. Though I'm not sure how to confirm the Go version on Jenkins. Any suggestions?

**Comment by jzila** [comment]
Add `sh 'go version'` anywhere in the Jenkinsfile.

**Comment by oconnor663** [comment]
Bumping now that that one's landed.

**Comment by oconnor663** [comment]
https://ci.keybase.io/job/client/job/PR-3902/3/execution/node/202/log/ is looking good.

**Pull request merged**
