### PR TITLE
Spring cleanup, no functional changes

### PR DESCRIPTION
**Pull request by taruti**
+ x!=nil && len(x)>0 => len(x)>0, len works fine on nil
+ bytes.Equal instead of bytes.Compare
+ time.Since
+ regexps are nicer with raw strings

### CODE REVIEW

**Comment by zanderz** [comment]
LGTM but we should wait until CI is back online (right?). :thumbsup:

**Comment by maxtaco** [comment]
Looks like ci1 is totally down.  I can't access it from home... @cjb if you get a chance to kick it.  Otherwise I'll look at it first thing tomorrow morning.  Likely it ran out of disk space or some such.  It was working Friday afternoon

**Comment by cjb** [comment]
@maxtaco Was already kicking it. Should be back up now!

**Comment by maxtaco** [comment]
Thanks!!!   What was the cause of the stoppage btw?

**Comment by cjb** [comment]
You were right, disk full caused a kernel hang.

**Comment by taruti** [comment]
CI issues still?

**Comment by maxtaco** [comment]
i tried to kick the docker

**Comment by cjb** [comment]
nginx (in front of the docker) wasn't running on ci1, because it wasn't set to run on reboot and we rebooted, so I started it and added it to run at boot.  CI rerunning now.

**Comment by cjb** [comment]
CI has passed now.

**Pull request merged**
