### PR TITLE
Allow read access to active device keys outside of LoginState acctReq

### PR DESCRIPTION
**Pull request by patrickxb**
This PR pulls the cached device keys out of the Account object and puts them in an ActiveDevice object.

The ActiveDevice object allows anything to have read access to the cached device keys without having to go through a LoginState account request (which could be blocked behind another account request).

The ActiveDevice object is protected by a RWMutex and its set functions are only called within LoginState account requests.

This should help chat function when offline as it will be able to get the device keys.

### CODE REVIEW

**Comment by mmaxim** [comment]
What gain does `RWMutex` give here?

**Comment by patrickxb** [comment]
Multiple concurrent readers.  KBFS calls into this all the time, so could be some benefit to allow concurrent goroutines to read device keys.

**Comment by mmaxim** [comment]
So that would be a performance win over the previous situation, since the threads needed to synchronize on the channel?

**Comment by patrickxb** [comment]
Yes.

**Pull request merged**
