### PR TITLE
impl list-memberships --all

### PR DESCRIPTION
**Pull request by modalduality**

### CODE REVIEW

**Comment by modalduality** [comment]
@patrickxb, cc'ing because I restructured TeamList/MemberInfo structs in order to generalize to listing entries for other users

**Comment by keybase-ci-visdiff** [comment]
The commits e6efbd9e03d3...c17dd0f7241f introduce visual changes on linux. <details><summary>:mag_right: 1 changed</summary>

 * Changed: **Markdown-emoji** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1500501020359-e6efbd9e03d3-c17dd0f7241f-linux/Markdown-emoji-e6efbd9e03d3.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1500501020359-e6efbd9e03d3-c17dd0f7241f-linux/Markdown-emoji-c17dd0f7241f.png)  
   Markdown-emoji comparison
</summary>

**Comment by maxtaco** [comment]
@patrickxb can you take this review?

**Comment by maxtaco** [comment]
@modalduality can you rebase to fix the conflicts above?

**Comment by patrickxb** [comment]
Yes

**Comment by patrickxb** [comment]
@modalduality let me know when rebased and I'll try out the branch locally.  Thanks.

**Comment by modalduality** [comment]
@patrickxb Just rebased.

**Comment by patrickxb** [comment]
Is this change supposed to show invites, too?

**Comment by modalduality** [comment]
@patrickxb Looks like it's specified on the doc https://keybase.io/ccsandbox/team-internal-mvp but I don't think it's implemented for any command yet.

**Pull request merged**
