### PR TITLE
Cache InputCanceled for secret key unlock prompt

### PR DESCRIPTION
**Pull request by patrickxb**
If user cancels a prompt for a secret key, don't prompt
them again for 5 minutes.

r? @maxtaco

### CODE REVIEW

**Comment by maxtaco** [comment]
Let me hold off on review until we work out with Chris what the semantics should be.

**Comment by patrickxb** [comment]
Any updates?

**Comment by maxtaco** [comment]
@malgorithms says he prefers the U/X in which only KBFS-ops have a cached cancelation.  Keybase CLI opts shouldn't hit it.

**Comment by malgorithms** [comment]
there's a big distinction between a user-initiated call to `keybase`, which can only be done by hand or by some specific program that's written to run keybase commands, and KBFS operations, which happen for all kinds of casual/vague/confusing reasons from users' perspectives.

so if a user suddenly gets a KBFS pin entry and they don't want to deal with it, saying no shouldn't bother them with KBFS requests again.

but if they go try to run 'keybase login' or `keybase sign` or `keybase track` or something and it just fails withotu asking them for pin, I think that would be weird. The general consensus around the office here was the same.

**Comment by patrickxb** [comment]
Yes, understood.

It was a lot of typing, but I plumbed it through so that only the kbfs crypto service will use the input cancel cached value.

**Comment by patrickxb** [comment]
@maxtaco PTAL when you get a chance

**Comment by maxtaco** [comment]
:+1:  LGTM!

**Pull request merged**
