### PR TITLE
enable debug logging for kbfs part on mobile

### PR DESCRIPTION
**Pull request by songgao**
To help with debugging connection problems.

### CODE REVIEW

**Comment by jzila** [comment]
This shouldn't go out in the wild though. Phones have really slow secondary storage, and we already log way too much. I'm sure it's not helping our app performance as it is.

**Comment by jzila** [comment]
This turns on debug logging for all of kbfs, unless I'm missing something...

**Comment by songgao** [comment]
This is in the client/go/bind, so it's only in mobile right? Do we use that for desktop init as well?

**Comment by jzila** [comment]
That's my point, it's debug for all of KBFS in mobile, not just mdserver. I'm responding to this:
> mdserver doesn't do much on mobile

**Comment by songgao** [comment]
Oh I see. So your concern is in e.g. folder_branch_ops?

**Comment by jzila** [comment]
Yeah. Although maybe it isn't a big deal...not sure.

**Comment by songgao** [comment]
I think even with those, KBFS logs are still gonna be pretty small compared to already enabled debug logs from core side.

**Comment by patrickxb** [comment]
Can you just turn this on in a branch and make a mobile build with it for yourself?

All of this logging has been turned down on mobile (including the core logging, which is much sparser on mobile as compared to desktop).

I'm worried that if this goes into master, it won't be reverted and will make it into a public build.  If it's just for debugging, seems easy enough to just make your own mobile build from a branch.

**Comment by songgao** [comment]
Was it ever a problem that KBFS had too much log on mobile? With out this, there's barely useful information for KBFS on mobile at all. On one of Mike's logs, there were 3 `WARN kbfs` lines among 23082 lines in total. The rest are all mostly `DEBU keybase`.

**Comment by patrickxb** [comment]
Yes.

**Comment by songgao** [comment]
Could you please be more specific? I pulled an old iOS log (https://keybase.io/_/admin/logdump_viewer#4280cca9db554efeb675fa1c) and there doesn't seem to be much from KBFS:

```
%  cat /tmp/old2.txt | ag ' kbfs ' | wc
    355    4062   42253
%  cat /tmp/old2.txt | wc
  30110  340917 4370803
```

**Comment by patrickxb** [comment]
It was part of a larger PR to reduce debug logging on mobile in general:

https://github.com/keybase/client/pull/8169

On android it is especially painful.  Chris could melt an android phone with a rekey.

Since that change, this is the first time there has been a request for kbfs mobile debug logs.  

It seems like a good first step would be to make a build in a branch with kbfs debug logging on and try to repro the error there first before increasing logging in mobile in an admin build.

**Comment by songgao** [comment]
> Chris could melt an android phone with a rekey.

That makes sense. None of the logs I've looked at included rekeys. So that could be one of the main sources for the log flood. I think we'll need mobile KBFS logs eventually, especially when we start working on mobile KBFS features. So we'll need to strip mobile logs like core. But that's a larger change for the future.

I'll do the branch build tomorrow as you suggested. Thanks Patrick!

**Pull request closed without merging**
