### PR TITLE
fix full log send

### PR DESCRIPTION
**Pull request by mmaxim**
cc @adamjspooner

### CODE REVIEW

**Comment by chrisnojima** [comment]
This shouldn't be the fix. Checkbox should click

**Comment by mmaxim** [comment]
There is no onClick for CheckBox.

**Comment by mmaxim** [comment]
There is `onCheck`, but the intended behavior is not to switch that check box back and forth 7 times.

**Comment by chrisnojima** [comment]
I don't understand what you mean

**Comment by mmaxim** [comment]
There is no feature of `CheckBox` that handles clicks on the label text. Unless you are saying that is something we should add.

**Pull request merged**
