### PR TITLE
if clientprev is not specified, use local storage to figure it out CORE-4362

### PR DESCRIPTION
**Pull request by mmaxim**
If the frontend does not specify a previous message, use the previous message from local storage.

cc @chrisnojima

### CODE REVIEW

**Comment by keybase-ci-visdiff** [comment]
The commits 2c131a3fc396...c7a069074a03 introduce visual changes on linux. <details><summary>:mag_right: 1 changed</summary>

 * Changed: **unlock_folders-Single** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484021579063-2c131a3fc396-c7a069074a03-linux/unlock_folders-Single-2c131a3fc396.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484021579063-2c131a3fc396-c7a069074a03-linux/unlock_folders-Single-c7a069074a03.png)  
   unlock_folders-Single comparison
</summary>

**Comment by mmaxim** [comment]
No, but it's possible the GUI doesn't know how to look for them?

**Comment by mlsteele** [comment]
Hm, this PR causes these errors on the gui for one of my test convs.

```
forward-logs.desktop.js?e11f:120 Warning: flattenChildren(...): Encountered two children with the same key, `1484065645759`. Child keys must be unique; when two children share a key, only the first child will be used.
    in div (created by Grid)
    in div (created by Grid)
    in Grid (created by List)
    in List (created by CellMeasurer)
    in CellMeasurer (created by AutoSizer)
    in div (created by AutoSizer)
    in AutoSizer (created by ConversationList)
    in div (created by ConversationList)
    in ConversationList (created by Conversation)
    in div (created by Box)
    in Box (created by Conversation)
    in Conversation (created by ConversationContainer)
    in ConversationContainer (created by Connect(ConversationContainer))
    in Connect(ConversationContainer) (created by RenderRouteNode)
    in RenderRouteNode (created by RenderRoute)
    in div (created by ConversationList)
    in ConversationList (created by ConversationListContainer)
    in ConversationListContainer (created by Connect(ConversationListContainer))
    in Connect(ConversationListContainer) (created by RenderRouteNode)
    in RenderRouteNode (created by RenderRoute)
    in div (created by Box)
    in Box (created by Nav)
    in div (created by Box)
    in Box (created by Nav)
    in Nav (created by Connect(Nav))
    in Connect(Nav) (created by RenderRouteNode)
    in RenderRouteNode (created by RenderRoute)
    in RenderRoute (created by Main)
    in Main (created by Connect(Main))
    in Connect(Main)
    in div
    in Provider (created by Root)
    in MuiThemeProvider (created by Root)
    in Root
    in AppContainer
```

**Comment by mmaxim** [comment]
Yeah it seems like it doesn't work, I'm trying to fix it now.

**Pull request merged**
