### PR TITLE
fuzz: nuke unused and non-compiling dirs

### PR DESCRIPTION
**Pull request by strib**
cc: @keybase/hotpotatosquad

Issue: HOTPOT-479

### CODE REVIEW

**Comment by patrickxb** [comment]
I know I said to nuke this, but just curious, which ones don't compile?  could we just nuke those?

It might be nice to have this still in the repo in case we want to do some fuzzing in the future since it has instructions and hopefully a few examples that still work.

**Comment by strib** [comment]
@patrick at least three packages don't compile due to API changes in other parts of the code:
```
$ go build -tags gofuzz  ./...
# github.com/keybase/client/go/fuzz/saltpack_verify
saltpack_verify/fuzz.go:36:40: cannot use &fixed (type *[64]byte) as type []byte in argument to ed25519.Verify
saltpack_verify/fuzz.go:67:33: not enough arguments in call to saltpack.Verify
	have ([]byte, keyring)
	want (saltpack.VersionValidator, []byte, saltpack.SigKeyring)
saltpack_verify/fuzz.go:73:6: undefined: saltpack.KIDEqual
# github.com/keybase/client/go/fuzz/saltpack_sign
saltpack_sign/fuzz.go:108:28: not enough arguments in call to saltpack.Sign
	have ([]byte, *sigPrivKey)
	want (saltpack.Version, []byte, saltpack.SigningSecretKey)
saltpack_sign/fuzz.go:112:36: not enough arguments in call to saltpack.Verify
	have ([]byte, keyring)
	want (saltpack.VersionValidator, []byte, saltpack.SigKeyring)
saltpack_sign/fuzz.go:119:6: undefined: saltpack.KIDEqual
# github.com/keybase/client/go/fuzz/passphrase_stream
passphrase_stream/fuzz.go:14:43: not enough arguments in call to libkb.StretchPassphrase
	have (string, []byte)
	want (*libkb.GlobalContext, string, []byte)
```

Not sure I can fix them on my own, and it doesn't seem like anyone has used them in years.  What would you like to do with them?

**Comment by patrickxb** [comment]
ok, how about deleting them and keeping nacl_enc and pgp_key_read?  or even just nacl_enc.

would be nice to just have one example for the future.

what do you think?

**Comment by strib** [comment]
@patrick cool with me, how does it look now?

**Pull request merged**
