### PR TITLE
updating to electron 0.35.4 plus small dep updates

### PR DESCRIPTION
**Pull request by chrisnojima**
@MarcoPolo @cjb please test your stuff on your platforms (cjb esp. linux)

### CODE REVIEW

**Comment by cjb** [comment]
:thumbsup: tested on Linux

**Comment by chrisnojima** [comment]
- [ ] Option 'transformer' is deprecated, use stateTransformer instead for redux logger

**Comment by chrisnojima** [comment]
@cjb quick look, did some small fixups to make redux-logger the same version on both sides and some small fixes

**Comment by cjb** [comment]
:thumbsup:

**Comment by chrisnojima** [comment]
@keybase/react-hackers please reinstall your node_modules

**Pull request merged**
