### PR TITLE
Electron 3.0.2

### PR DESCRIPTION
**Pull request by chrisnojima**
- [x] osx
- [x] linux
- [x] windows

### CODE REVIEW

**Comment by chrisnojima** [comment]
@zanderz @mmaxim can we do a sanity check build of windows / linux

**Comment by cjb** [comment]
@chrisnojima Error: Failed to find Electron v3.0.2 for linux-x64 at https://kbelectron.keybase.pub/electron-download/v3.0.2/electron-v3.0.2-linux-x64.zip

**Comment by chrisnojima** [comment]
sorry upped the arm one by accident, fixed

**Comment by zanderz** [comment]
seems ok on  windows

**Pull request merged**
