### PR TITLE
Ipad support

### PR DESCRIPTION
**Pull request by neurosnap**
This PR add some support for ipad.  It scales the app to fit the screen of the tablet and allows for landscape orientation.

It also fixes an icon UI update.

Screen Shot 2019-05-06 at 8 52 05 PM
Screen Shot 2019-05-06 at 8 51 22 PM

I am also willing to build a split view for tablet, but I wanted to submit this first PR just to see if the maintainers would be receptive to an external contributor building better ipad support.  If so any advice would be appreciated!

### CODE REVIEW

**Comment by thams** [comment]
Cool, and thanks!

**Comment by miguelandres** [comment]
Any chance to get this reviewed by anyone in Keybase, this seems like a simple fix for one of my biggest issues with keybase

**Comment by Altonymous** [comment]
Wish I had term to learn some of this stuff, would love to resolve the conflicts to see if we could get this to go through.

**Comment by coreagile** [comment]
Boy would this be nice to have!!! Noticing there are conflicts that probably need resolving, too....

**Comment by glyph** [comment]
Thanks for working on this!  I was just sitting in a café with my fancy new (well okay new-*ish*) iPad Pro and got a couple of Keybase messages, and was somewhat distressed to see that i had to turn my head and crane my neck to even read the screen.  Those screenshots look beautiful!

**Comment by SerenadeX** [comment]
Why is this not being merged/worked on? This PR has been open for months and the changes are minimal.

**Comment by 0xGabi** [comment]
+1

**Comment by alexmarkley** [comment]
I’m also a bit perplexed as to why this isn’t getting visible traction.

As an iPad Pro user (and really, any iPad user with a hardware keyboard) the ability to rotate into landscape mode is a hard requirement, especially for an app that has such strong chat component.

What needs to be done to get this support introduced?

**Comment by hypery2k** [comment]
any news on that. Would like to support here

**Comment by neurosnap** [comment]
Yeah at this point I have stopped using keybase because I can't use the app on ipad.  It sucks but there are plenty of chat apps to choose from.

**Comment by MindTooth** [comment]
> Yeah at this point I have stopped using keybase because I can't use the app on ipad. It sucks but there are plenty of chat apps to choose from.

Yeah.  More about what they want, than what some of the users want.

_(Sorry for being direct.)_

**Comment by hypery2k** [comment]
besides the tone, it would just nice to have this PR merged. If it helps I can make a new PR from latest master

**Comment by heqian** [comment]
@neurosnap Could you please resolve the conflicts in this PR? (better chance to get merged I hope...)

**Comment by OrangutanGaming** [comment]
Might be worth making a new PR instead, could get some attention too

**Comment by nihaals** [comment]
This should probably be closed as it's now supported

**Pull request closed without merging**
