### PR TITLE
Tweaks on user switching

### PR DESCRIPTION
**Pull request by cecileboucheron**
@keybase/react-hackers

### CODE REVIEW

**Comment by cecileboucheron** [comment]
@jakob223 I can't manage to see the mobile version for this feature. Is it behind a feature flag on mobile?

**Comment by junderw** [comment]
Will this show a badge on users with currently unread notifications?

**Comment by cecileboucheron** [comment]
@junderw The first version of it won't have badges but it's on our roadmap.

**Comment by cecileboucheron** [comment]
@keybase/react-hackers Bump ^

**Comment by jakob223** [comment]
> @jakob223 I can't manage to see the mobile version for this feature. Is it behind a feature flag on mobile?

I think I answered this in chat, but in case I didn't: yes, it's behind a feature flag for now until we can polish it when IMP TOFU is finished.

**Pull request merged**
