### PR TITLE
Move saltpack to github.com/keybase/saltpack

### LINKED ISSUE #1872: Move saltpack to it's own repo?
Do we want to move saltpack out of `keybase/client/go` into `keybase/saltpack` since this is our "kitchen sink" repo and saltpack is a separate more standard-y thing?

### PR DESCRIPTION
**Pull request by jacobhaven**
This resolves #1872

The new saltpack repo can be found at https://github.com/keybase/saltpack

### CODE REVIEW

**Comment by jacobhaven** [comment]
@oconnor663 Do we want to vendor the github.com/keybase/saltpack repo or leave it as a regular dependency?

**Comment by maxtaco** [comment]
@jacobhaven we vendor all of the things...

**Comment by oconnor663** [comment]
Yeah definitely vendor. In the commit message here, could you please include the commands you used to make the split? Other than that, LGTM.

**Comment by maxtaco** [comment]
Looking into this appveyor breakage.  Seems like there was a recent regression that's reliably breaking all builds in kex2/ and those engines that depend on it. @zanderz do you have any theories on that?  Can we repro with just a windows build not via c/i? Seems like we just need to run `go test` in `kex2`?

**Comment by zanderz** [comment]
The breakage does not seem reliable; just now TestKex2Provision in engine, TestKex2Router in libkb and Test* in kex2 all passed for me against ci1.keybase.io, both in master and jacob/move-saltpack.

**Comment by maxtaco** [comment]
Hrmf.

**Comment by jacobhaven** [comment]
@oconnor663 Commands to make this split:
```
cd $GOPATH/src/github.com/keybase && cp -R client/ saltpack && cd saltpack/
git mv go/encoding/ go/saltpack/ && git commit -m "Move encoding/basex to saltpack" # Sadly, I think this destroys the history for encoding/
git filter-branch --prune-empty --subdirectory-filter go/saltpack/
git remote remove origin && git remote add origin git@github.com:keybase/saltpack.git
# Rewrite all github.com/keybase/client/go references
git commit -am "Rewrite saltpack and encoding/basex imports (and run goimports)"
git push # to keybase/saltpack
cd ../client/go
git checkout -b jacob/move-saltpack
git rm -rf saltpack encoding
# Rewrite all github.com/keybase/client/go/saltpack and github.com/keybase/client/go/encoding imports
git commit -am "Move saltpack to github.com/keybase/saltpack"
govendor add github.com/keybase/saltpack/encoding/basex
govendor add github.com/keybase/saltpack
git add vendor/ && git commit -m "Vendor github.com/keybase/saltpack"
git push --set-upstream origin jacob/move-saltpack # And open PR
```

**Comment by zanderz** [comment]
ok I see that on my local machine, this fails:
go test -count 100 -run TestReadDelayedWrite
but this passes:
go test -count 50 -run TestReadDelayedWrite
Also, these kex2 tests don't hit the API server, so it looks like some
timing issue on a bogged-down AppVeyor server?

**Comment by maxtaco** [comment]
We'll try to take a look into it, so those build/install instructions would be great (unless you want to take a crack)

**Comment by oconnor663** [comment]
@jacobhaven, do you know why a number of files (like `basex_test.go`) seem to be deleted entirely, rather than moved? Is that a quirk in how GitHub displays stuff, or could we have accidentally deleted them?

**Comment by jacobhaven** [comment]
@oconnor663 I don't think any files were deleted... https://github.com/keybase/saltpack/blob/master/encoding/basex/basex_test.go

**Comment by oconnor663** [comment]
Ah I guess what it is is that govendor doesn't include test files?

**Comment by jacobhaven** [comment]
Oh, yes. That's configurable, but it's probably the sane setting. https://github.com/keybase/client/blob/jacob/move-saltpack/go/vendor/vendor.json#L3

**Pull request merged**
