### PR TITLE
Follow prompt default-yes for no-proofs users

### PR DESCRIPTION
**Pull request by mlsteele**
Referencing https://github.com/keybase/client/issues/10553

_changed, see thread_

When following someone with `keybase follow` there is a `-y` option for the sure-footed to bypass prompts. Before this PR it bypassed
1. Is this the junderwood you wanted? [Y/n]

But did _not_ bypass

2. Some proofs failed; still follow junderwood? [y/N]
3. We found an account for junderwood, but they haven't proven their identity. Still follow them? [y/N]

There may be other prompts that I missed.

This change makes it so that case 3 defaults to yes `[Y/n]` and _is_ bypassed by `-y`. Case 2 is unchanged. The rationale here is that it if you are following a username with `-y` it's very likely ok with you that they have no proofs. Case 2 is more serious and it's helpful to encourage people to fix broken proofs.

cc @maxtaco in case you have an opinion

### CODE REVIEW

**Comment by zapu** [comment]
hopefully doesn't break any integration tests

**Comment by dabura667** [comment]
Suggestion:

If user passes -y and N-default broken proofs appear, throw an error and do not prompt.

-y should never block and accept user input, it should either exit 0 or exit non-0 (error out)

**Comment by dabura667** [comment]
```go
// Tracking statement doesn't exist or changed, lets prompt them with the details
if o.TrackOptions.BypassConfirm && promptDefault == libkb.PromptDefaultYes {
	result.IdentityConfirmed = true
	result.AutoConfirmed = true
	ui.G().Log.Info("Identity auto-confirmed via command-line flag")
} else {
	if result.IdentityConfirmed, err = ui.parent.PromptYesNo(PromptDescriptorTrackAction, prompt, promptDefault); err != nil {
		return
	}
}
```

This should check for bypass and defaultNo as well, and exit with nonzero code.

**Comment by junderw** [comment]
I agree with @dabura667 

perhaps add

```go
func keybaseExit(exitCode int) {
	logger.RestoreConsoleMode()
	os.Exit(exitCode)
}
```

similar to main.go and then do this:

```go
// Tracking statement doesn't exist or changed, lets prompt them with the details
if o.TrackOptions.BypassConfirm && promptDefault == libkb.PromptDefaultYes {
	result.IdentityConfirmed = true
	result.AutoConfirmed = true
	ui.G().Log.Info("Identity auto-confirmed via command-line flag")
} else if o.TrackOptions.BypassConfirm && promptDefault == libkb.PromptDefaultNo {
	keybaseExit(int(keybase1.ExitCode_NOTOK))
} else {
	if result.IdentityConfirmed, err = ui.parent.PromptYesNo(PromptDescriptorTrackAction, prompt, promptDefault); err != nil {
		return
	}
}
```

**Comment by junderw** [comment]
Maybe you should ui.G().Log.Warn something before exiting tho...

**Comment by junderw** [comment]
also, lol @ my name being used. I feel special :-)

**Comment by mlsteele** [comment]
Those are good ideas. But I don't want to make it harder for someone to get their work done by telling them what to run instead of letting them continue. What is the issue with a prompt in `-y`? Are you using this command in scripts?

**Comment by dabura667** [comment]
What is the point of -y?

To run in scripts.

So yes, the reason you don’t prompt for -y is because -y is traditionally used for scripts.

ie.

apt-get install -y nodejs

Will never prompt you, only fail or succeed.

**Comment by dabura667** [comment]
If the consensus is “we don’t want users to run follows in scripts” than this PR should be the removal of -y from follow.

**Comment by junderw** [comment]
Yes. Scripting is the goal of -y... if you don't think users should script this command, then remove the -y option.

Currently the only people benefitting from such an arg are people who can't be bothered to type y and hit enter... which.......... idk what percentage of Keybase users that also use the terminal are *THAT* lazy... but it is probably not that large of a population.

**Comment by mlsteele** [comment]
Ok now case 3 is still changed to be auto-yes. And the default-no options bail out with an error code to make scripting easier.

```
$ kbu follow cn10
▶ INFO Identifying cn10
You last followed cn10 on 2018-03-02 16:15:05 EST
✖ <CHANGED from "woop"> "iqjwdijwid" on twitter failed: No server-given hint for sig=ed6d1f099e12764735d1093843d2b57e8e8ce7139e1a861db6a6370c058200be0f (code=306)
Some proofs are failing. [I]gnore for 48h0m0s, [A]ccept these changes or [C]ancel?: C
▶ ERROR Input canceled

$ kbu follow cn10 -y
▶ INFO Identifying cn10
You last followed cn10 on 2018-03-02 16:15:05 EST
✖ <CHANGED from "woop"> "iqjwdijwid" on twitter failed: No server-given hint for sig=ed6d1f099e12764735d1093843d2b57e8e8ce7139e1a861db6a6370c058200be0f (code=306)
▶ ERROR Some proofs failed. Try again without '-y'
▶ ERROR Follow not confirmed
```

**Comment by dabura667** [comment]
@mlsteele
Sounds good.

Just to check: using Log.Error() in the way you did will cause a non-zero exit code, correct?

Logging to stderr is maybe good enough, but exiting with a non-zero code is intuitive.

You could check with

`kbu follow cn10 -y && echo ZeroExitedOops`

If echo doesn’t go off we’re good! :-)

**Comment by mlsteele** [comment]
Log.Error just logs. Something later on sets the status code because the result struct does not indicate success.

**Pull request merged**
