### PR TITLE
Dedup reactions in supersedes

### PR DESCRIPTION
**Pull request by joshblum**
changes the `ReactionMap` struct to hold a map of `{username: reactionMessageID}` instead of an array so we can easily dedup multiple reactions from the same user.

cc @buoyad

### CODE REVIEW

**Comment by mmaxim** [comment]
I made a comment on the ticket, but I'll just repeat here. I think we should probably solve this problem on the send side, it shouldn't be possible to get the same reaction our per message per user.

**Comment by joshblum** [comment]
commented on ticket

**Comment by mmaxim** [comment]
Wait now I’m confused. I think users should be able to react more than once, just not with the same emoji. This looks like it prevents me from adding multiple different reactions.

**Comment by joshblum** [comment]
You can still react more than once since you'll appear in different entries in the `reactionMap`, you just can't appear more than once under the same `reactionText` 
`{ reactionText : { username : messageID } }`

**Pull request merged**
