### PR TITLE
add menu to logged out view

### PR DESCRIPTION
**Pull request by chrisnojima**
@keybase/react-hackers you can't quit if logged out. this fixes that

### CODE REVIEW

**Comment by keybase-ci-visdiff** [comment]
:mag_right: :zap: These commits introduced some visual changes:
 * Changed: **Menubar-Logged_Out** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1464706902772-3c328a63b964-65d429121211/Menubar-Logged_Out-3c328a63b964.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1464706902772-3c328a63b964-65d429121211/Menubar-Logged_Out-65d429121211.png)  
   Menubar-Logged_Out comparison

**Comment by MarcoPolo** [comment]
👍

**Comment by keybase-ci-visdiff** [comment]
:mag_right: :zap: These commits introduced some visual changes:
 * Changed: **Menubar-Logged_Out** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1464722801434-9c96960c72d0-a3359e168d29/Menubar-Logged_Out-9c96960c72d0.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1464722801434-9c96960c72d0-a3359e168d29/Menubar-Logged_Out-a3359e168d29.png)  
   Menubar-Logged_Out comparison

**Comment by chromakode** [comment]
:+1:

**Pull request merged**
