### PR TITLE
Add install support for FreeBSD

### PR DESCRIPTION
**Pull request by wahjava**
The current snapshot of client does not compile on FreeBSD, courtesy: missing functions for FreeBSD in install package. This commit copies `install_linux.go`  to `install_freebsd.go`, replacing `linux` with `freebsd`, and seems to works fine.

It is tested on `FreeBSD 10.3 (amd64)`.

Thanks!

### CODE REVIEW

**Comment by cjb** [comment]
@wahjava Thanks for the PR!  Do you think it would work to rename install_linux.go to install_unix.go and put `+build linux,freebsd` in there?  It seems like it would be better not to duplicate the file if there are no changes and we can avoid it.

CC @gabriel

**Comment by wahjava** [comment]
Sure, that'll be better longer term. I can adapt my submission to this later today.

Thanks for the feedback.

**Comment by wahjava** [comment]
@cjb Updated the PR, and used `+build linux freebsd` constraints, unlike what you mentioned.

Let me know if you see any other issue.

Thanks!

**Comment by gabriel** [comment]
👍 

Testing in CI and will merge if passes

**Comment by gabriel** [comment]
This merges ok: https://github.com/keybase/client/pull/3552

**Comment by cjb** [comment]
@wahjava Thanks for the contribution! :confetti_ball:

**Pull request merged**
