### PR TITLE
fix foreground crash on iOS by eating SIGPIPE

### PR DESCRIPTION
**Pull request by mmaxim**
cc @MarcoPolo

### CODE REVIEW

**Comment by mmaxim** [comment]
Ok this works now...

**Comment by jzila** [comment]
FYI your builds will fail until you rebase.

**Comment by mmaxim** [comment]
The build was auto failing before since I was using an option not available on Linux, it seems like it is going now?

**Comment by jzila** [comment]
`kbfs-server` will fail as of ~15 minutes ago for anyone who doesn't rebase client as of ~2 minutes ago. I merged a temporarily breaking change to fix CI.

**Comment by mmaxim** [comment]
Ok I wasn't even making it that far, but just rebase'd. Thanks for the heads up!

**Comment by mmaxim** [comment]
@maxtaco I changed how the HTTP client is setup to do the same thing as our RPC conns.

**Pull request merged**
