### PR TITLE
Nuke gomobile before init

### PR DESCRIPTION
**Pull request by gabriel**
Including link to Android setup for React which was very helpful.
Also updating pods stuff.

### CODE REVIEW

**Comment by gabriel** [comment]
@MarcoPolo 
cc @keybase/updater-hackers

**Comment by MarcoPolo** [comment]
was removing the bin enough, or did you have to remove it from `pkg` or `src` too?

**Comment by keybase-ci-visdiff** [comment]
:mag_right: These commits introduced some visual changes:
 * Changed: **Profile-Followed** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1465856303631-5f6ff094e371-c06b6d727b9a/Profile-Followed-5f6ff094e371.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1465856303631-5f6ff094e371-c06b6d727b9a/Profile-Followed-c06b6d727b9a.png)  
   Profile-Followed comparison

**Comment by gabriel** [comment]
Removing the bin seemed enough... i also did `go get -u` so maybe that was the issue too?

**Pull request merged**
