### PR TITLE
verifyMerkleRootAndKBFS RPC

### PR DESCRIPTION
**Pull request by maxtaco**
- fetch a root by seqno and verify that it has the given merkle root

### CODE REVIEW

**Comment by maxtaco** [comment]
@strib --- pardon, I don't have a good way to test this, but I wonder what it looks like if you just plug it in.  Most of the code already existing, I just put some light wrappers and error checks around it.

**Comment by strib** [comment]
@maxtaco I plugged this into my code and am getting a failure trying to verify the HashMeta.  service logs:

```
2018-05-29T23:58:59.930740Z ▶ [DEBU keybase merkle.go:38] c0e - VerifyMerkleRootAndKBFS({Root:{Seqno:92 HashMeta:26ac83d337a925d9647ab61051e455fc5b534b81995ddb894c4b74fbe1c99893} ExpectedKBFSRoot:{Tree
ID:2 Root:88a365706bc42055ea09f167b3096048704832cdd5bad1c9083a67a6270d90b8d44026286c9f4fa168c4402763f29dbd1d5137ed13a3e14e5ad8d409886b1d93800122a241160610bcbe18438fd81864204facf90b1299b8722928d8dedc7c82ee214df9066c731c2bbad2a36e6f6ec418d67a770be86124aaf662d5c2919f8922986b652dd6505950a27072c44090cf498c6f1c6fa88c4fd3662d862ac58af7770ec668f5df66d121f795200d6a1b98221f628bc96ec6be6e57c6b88c481b24c10d9adb0d38c18b960e454862b1a2736e1ea17402a27473ce5b0de92ca17601}}) -> ERROR: Error checking merkle tree: wrong hash meta [tags:FID=NGIyM-yzlnYn3hdxz8Uv0A,MRKL=NnGUjxbzUNhk]
2018-05-29T23:58:59.930761Z ▶ [DEBU keybase merkle.go:100] c0f - MerkleHandler#VerifyMerkleRootAndKBFS -> Error checking merkle tree: wrong hash meta [time=268.504µs] [tags:FID=NGIyM-yzlnYn3hdxz8Uv0A,MRKL=NnGUjxbzUNhk]
```

But the hash I'm passing down, `26ac83d337a925d9647ab61051e455fc5b534b81995ddb894c4b74fbe1c99893`, is the same as the one that the API server reports:

```
$ keybase apicall -a seqno=92 -m get merkle/root
{"ctime":1527638318,"ctime_string":"2018-05-29T23:58:38.000Z","hash":"664afef3e611d67a63ef7dfe92897df88c57bf948860c7857a7df007168092e25ee041e6d99fc507e334cdd2f9a9a1072862389c284e21e85079670487d8a858","hash160":"c92e881afd83f1a987402cfdb4a8def376232147","hash_meta":"26ac83d337a925d9647ab61051e455fc5b534b81995ddb894c4b74fbe1c99893"...
```

**Comment by maxtaco** [comment]
i see the bug, sorry about that, i'll put up something that works in a little bit. thanks

**Comment by maxtaco** [comment]
You'll need to pull on kbweb too (https://github.com/keybase/keybase/pull/2502), but this should be better. I found a simple way to test half of this. LMK if it bombs out again, I can keep looking. Thanks.

**Comment by strib** [comment]
@maxtaco looks good now, passes my tests!

**Comment by strib** [comment]
Do you want a code review from me too?  I can try but haven't looked at this code before.

**Comment by maxtaco** [comment]
I tagged @zapu too

Good, glad it works....

**Pull request merged**
