### PR TITLE
Add "delete" for folders in the UI

### PR DESCRIPTION
**Pull request by jakob223**
Behind a feature flag - except I can't seem to get it to show for me now that I've put it behind the feature flag, even though the feature flag is set for me :(

### CODE REVIEW

**Comment by jakob223** [comment]
oops this is polluted with other work, will rebase

**Comment by jakob223** [comment]
Why is there a `.js.flow` file as well as the `.native.js` and the `.desktop.js` files? Is the flow compiled to JS by something in the build toolchain but the JS it's compiled into doesn't show up anywhere?

**Comment by songgao** [comment]
The flow file is because flow doesn’t understand the electron/native split. Flow file is not compiled to js. When you run flow if there’s a flow file flow just looks at that and not the actual files.

**Comment by songgao** [comment]
I think you need to add it to `__mocks__/feature-flags` too

**Comment by jakob223** [comment]
@songgao I thought you said __mocks__ only needed the flag for storyshots, and it looks like there isn't a story shot for this flow.

**Comment by songgao** [comment]
@jakob223 it still needs to satisfy the feature flag’s type, so even if no story touches it you’d still need it in there. (I think there’s a story for path-item-action; not sure if it currently exposes the Delete button though.)

**Pull request merged**
