### PR TITLE
Change from Jenkins to plain scripts for Windows release build

### PR DESCRIPTION
**Pull request by zanderz**
Note that the "ios3" machine in NY has a working VM but is set to build off this branch right now. Instructions to follow in /keybase/team/keybase.builds.windows
Will switch the SF one over on Monday
@maxtaco @keybase/react-hackers

### CODE REVIEW

**Comment by zanderz** [comment]
couple of tweaks and SF is working with this now - @maxtaco ?

**Comment by zanderz** [comment]
@maxtaco ?

**Comment by zanderz** [comment]
thanks. Open to adapting the .sh files instead or using something else.

**Comment by maxtaco** [comment]
@zanderz  let's talk this over in our meeting

**Pull request merged**
