### PR TITLE
Idea for logging test function

### PR DESCRIPTION
**Pull request by patrickxb**
This needs work, but we could do something like this to log the test function that is running.

@maxtaco @cjb @mmaxim @oconnor663

### CODE REVIEW

**Comment by maxtaco** [comment]
Seems easy enough and will do the trick

**Comment by keybase-ci-visdiff** [comment]
:mag_right: No visual changes found as a result of these commits.

**Comment by mmaxim** [comment]
👍

**Comment by patrickxb** [comment]
I added a flag.  So with this change you can now do 

    go test -test.func-names

and it will print the function name (provided it uses libkb.SetupTest, which is true for the vast majority of tests).

**Comment by patrickxb** [comment]
Note that this is imperfect as some tests call SetupTest multiple times, but it should point us in the right direction for any test issues...

**Comment by keybase-ci-visdiff** [comment]
:mag_right: No visual changes found as a result of these commits.

**Comment by maxtaco** [comment]
@cjb do you like this solution or yours better? This might be less
disruptive and we can run it everywhere not just ci.

**Comment by patrickxb** [comment]
I modified run_tests.sh in this branch to use the env var and tested locally.  Looked helpful.

**Comment by keybase-ci-visdiff** [comment]
:mag_right: No visual changes found as a result of these commits.

**Comment by patrickxb** [comment]
You can see it in action in this PR:

Using existing container
auth.......PASS
ok  	github.com/keybase/client/go/auth	0.023s
client.......PASS
ok  	github.com/keybase/client/go/client	0.013s
engine.......SetupTest github.com/keybase/client/go/engine.TestBTC /home/travis/gopath/src/github.com/keybase/client/go/engine/btc_test.go:31
SetupTest github.com/keybase/client/go/engine.testEngineWithSecretStore /home/travis/gopath/src/github.com/keybase/client/go/engine/common_test.go:243
SetupTest github.com/keybase/client/go/engine.TestCryptoSignED25519 /home/travis/gopath/src/github.com/keybase/client/go/engine/crypto_test.go:25
SetupTest github.com/keybase/client/go/engine.TestCryptoSignToString /home/travis/gopath/src/github.com/keybase/client/go/engine/crypto_test.go:48
SetupTest github.com/keybase/client/go/engine.TestCryptoSignED25519NoSigningKey /home/travis/gopath/src/github.com/keybase/client/go/engine/crypto_test.go:75
SetupTest github.com/keybase/client/go/engine.TestCryptoUnboxBytes32 /home/travis/gopath/src/github.com/keybase/client/go/engine/crypto_test.go:110
SetupTest github.com/keybase/client/go/engine.TestCryptoUnboxBytes32DecryptionError /home/travis/gopath/src/github.com/keybase/client/go/engine/crypto_test.go:182
SetupTest github.com/keybase/client/go/engine.TestCryptoUnboxBytes32NoEncryptionKey /home/travis/gopath/src/github.com/keybase/client/go/engine/crypto_test.go:197
SetupTest github.com/keybase/client/go/engine.TestCachedSecretKey /home/travis/gopath/src/github.com/keybase/client/go/engine/crypto_test.go:246

**Comment by cjb** [comment]
:thumbsup:

**Pull request merged**
