### PR TITLE
keybase1: emulate legacy SigIDBase export

### PR DESCRIPTION
**Pull request by maxtaco**
- always output 0x0f suffix in case client needs to downgrade

### CODE REVIEW

**Comment by maxtaco** [comment]
cc those affected by this bug: @jzila and @chrisnojima

**Comment by xgess** [comment]
hah. was just looking at this. was going to :+1:

**Comment by xgess** [comment]
@maxtaco did you test that this doesn't interact poorly with team chain links? the unmarshalling seems pretty safe, but marshalling always to the v1 seems like it could cause something unexpected over there. 
i guess we'll find out soon enough.  :)

**Comment by maxtaco** [comment]
This shouldn't affect teams at all, and plus, I figure it's safe because we used to do this on 5.2.0 and before.

**Pull request merged**
