### PR TITLE
Don't close a modal if a click that ended outside the modal started inside it

### PR DESCRIPTION
**Pull request by cjb**
@keybase/picnicsquad CC @keybase/react-hackers 

When we're showing a modal, we stop onClicks from inside the modal bubbling up to the "cover" opaque background.  Clicking on that background closes the modal.

But if a click starts inside the modal and ends on that background element, the onClick for the background fires.  So if you click and drag to select some text inside a modal but end outside of it, the modal closes.

Since onClick's not going to work, I went with using onMouseDown and onMouseUp and only treating it as a modal close if the click both started and ended inside the background element.

Am open to better ways of doing it, I was surprised I couldn't find anything more obvious to do.

### CODE REVIEW

**Comment by chrisnojima** [comment]
Doesn't onclick have the location?

**Comment by cjb** [comment]
@chrisnojima It has the end location, not the start location. We want to avoid firing the onClose depending on the start location.

**Comment by chrisnojima** [comment]
relative-popup-hoc also needs to be fixed

**Comment by chrisnojima** [comment]
here is my alternative implementation: https://github.com/keybase/client/pull/18930

**Comment by chrisnojima** [comment]
alternative merged

**Pull request closed without merging**
