### PR TITLE
Add user group for mobile

### PR DESCRIPTION
**Pull request by MarcoPolo**
@keybase/react-hackers 

IconType is now it's own separate type, the new version of flow seems to have changed how you were able to do IconProps.type :(

Preview:
screen shot 2016-06-09 at 5 56 14 pm

### CODE REVIEW

**Comment by chrisnojima** [comment]
i think the dummy data is slightly incorrect.
in the group view, if they are a keybase user it should use their keybase avatar and name and full name, no matter how you searched them.

I think this summarizes the view ( @cecileboucheron please verify )

If you're searching on keybase, you get the keybase avatar/username on the left. On the right you get their full name and something that matches (like their twitter username)
if you're searching on another platform. you get platform avatar/username on the left. On the right you get keybase avatar/username/fullname if they're on keybase, otherwise you get platform avatar/full name if available.

On the group results screen you get:
If they are a keybase user. keybase avatar/username/full name on the left
If they aren't a keybase user: platform avatar/username/full name on the left

**Comment by cecileboucheron** [comment]
@chrisnojima Correct, except one thing:
In: "if you're searching on another platform. you get platform avatar/username on the left."
Not platform avatar, platform logo (Twitter bird, Reddit alien, etc.). We want to keep the service logo on the left in the search results. If we can pull their avatar and name from the service, it goes on the right.

And then in the group results, if we can pull their avatar, we display it. If we can't, we use the Keybase placeholder avatar.

**Comment by MarcoPolo** [comment]
> And then in the group results, if we can pull their avatar, we display it. If we can't, we use the Keybase placeholder avatar.

What if we can't pull in their platform avatar, same placeholder?

**Comment by cecileboucheron** [comment]
Yeah I was referring to the platform avatar. If we can pull the platform avatar, we display it, and if we can't, we display the KB placeholder one.

**Comment by MarcoPolo** [comment]
bump @chrisnojima

**Comment by chrisnojima** [comment]
👍

**Pull request merged**
