### PR TITLE
Update Android splash screen.

### PR DESCRIPTION
**Pull request by adamjspooner**
@keybase/react-hackers, this is ready for review.

### CODE REVIEW

**Comment by hyperobject** [comment]
the left and right sides of the hexagon get cut off on my pixel 3a xl, intended?
Screenshot_20191108-095815

**Comment by adamjspooner** [comment]
@hyperobject, how does it look with those?

**Comment by hyperobject** [comment]
@adamjspooner hexagon fits now, but the keys are a little small on-device Screenshot_20191108-110616

**Comment by adamjspooner** [comment]
Can you share a screenshot of what it looks like on-device in the public release, please? 🙏

**Comment by hyperobject** [comment]
> Can you share a screenshot of what it looks like on-device in the public release, please? 🙏
whoops, sorry about that! here's what it looks like on my phone:
Screenshot_20191108-112610

**Comment by adamjspooner** [comment]
Thanks! 🙇

**Comment by adamjspooner** [comment]
@hyperobject, this is ready for another look.

**Comment by hyperobject** [comment]
the details still look a little small on-device but it's better for sure!
Screenshot_20191111-111527

**Pull request merged**
