### PR TITLE
updated acceptance rejection api and tests

### PR DESCRIPTION
**Pull request by AMarcedone**
Tests won't pass until new server is merged, but things are ok locally

### CODE REVIEW

**Comment by zapu** [comment]
cool, does it not flake anymore?

**Comment by AMarcedone** [comment]
looks like it doesn't :) I think I will merge the server PR, then wait for client master to start failing, then run CI again and merge this. 
Unless you think it's better to merge a skip to these tests first, so we don't annoy people with new master failures.

**Comment by zapu** [comment]
i can merge both tomorrow morning

**Comment by zapu** [comment]
I didn't realize serverside was not reviewed yet. I'm standing by then

**Pull request merged**
