### PR TITLE
propagate paper errors across retries

### PR DESCRIPTION
**Pull request by songgao**

### CODE REVIEW

**Comment by maxtaco** [comment]
@songgao who should review this?

**Comment by songgao** [comment]
@maxtaco could you please take a look? :)

**Comment by maxtaco** [comment]
HTTP 301
Location: @patrickxb

**Comment by maxtaco** [comment]
(I just won't have much time today or tomorrow :) )

**Comment by patrickxb** [comment]
I'll look in a bit.

**Comment by patrickxb** [comment]
LGTM

**Comment by songgao** [comment]
Thanks Patrick

**Pull request merged**
