### PR TITLE
Add additional log info for routeTree actions

### PR DESCRIPTION
**Pull request by chromakode**
:eyeglasses: @keybase/react-hackers

### CODE REVIEW

**Comment by chrisnojima** [comment]
instead of changing it so it has access to old state, why not just add a state log for this and not use action logging?

**Comment by chrisnojima** [comment]
(ie just add it here: https://github.com/keybase/client/blob/master/shared/constants/reducer.js#L47)

**Comment by chromakode** [comment]
@chrisnojima in light of our discussion on Slack, would you like me to make changes to this, or is it good to merge?

**Comment by chrisnojima** [comment]
You can merge

**Pull request merged**
