### PR TITLE
Remove dependency on testing from libkb

### PR DESCRIPTION
**Pull request by akalin-keybase**

### CODE REVIEW

**Comment by akalin-keybase** [comment]
Test code is still in libkb, but at least now we're not pulling in all of "testing".

**Comment by patrickxb** [comment]
Replacing testing.T with a logger doesn't seem equivalent to me.

Plus the logger doesn't implement the same interface as testing.T.  For example, now tc.T.Skip() doesn't compile.

**Comment by strib** [comment]
@patrickxb: why would anything not in a "_test.go" file need to do a `.Skip()`?  This is about removing the testing dependency from the library code, so it doesn't cause things that pull it in to print test flags on the command line.

**Comment by patrickxb** [comment]
It wouldn't.  But the TestContext is used by lots of tests in _test.go.  And with this change, it's tc.T variable is no longer *testing.T but a logger.

**Comment by strib** [comment]
Oh I see, thanks.  Guess we need to make a more expansive interface?  Or move the testcontext stuff into a separate package only used by tests.

**Comment by akalin-keybase** [comment]
Separate package won't work, because that package will depend on libkb, and libkb will depend on taht package.

We can expand the interface as needed, or define a new one that embeds TestLogBackend -- I don't think that's a problem. But we don't need it now.

Not sure why I had to change test files here, though...let me see if I can back that out.

**Comment by akalin-keybase** [comment]
Oh, right, the test files are passing `tc.T` around. Well, I can define a new interface that's basically `TB` now, or we can wait until we need the new methods. I don't think we'll need `tc.T.Skip` in test util functions anytime soon, though...

**Comment by patrickxb** [comment]
Just to clarify, the point of this is to avoid linking in the `testing` package?  Is that causing any issues, or just not ideal?

**Comment by strib** [comment]
Yes.  It causes this issue:

```
kbfsfuse --help
Usage of kbfsfuse:
  -bserver string
    	host:port of the block server (default "bserver.kbfs.keybase.io:443")
  -cpuprofile string
    	write cpu profile to file
  -debug
    	Print debug messages
  -label string
    	label to help identify if running as a service
  -localuser string
    	fake local user (used only with -server-in-memory or -server-root)
  -mdserver string
    	host:port of the metadata server (default "mdserver.kbfs.keybase.io:443")
  -memprofile string
    	write memory profile to file
  -mount-type string
    	mount type: default, force (default "force")
  -runtime-dir string
    	runtime directory
  -server-in-memory
    	use in-memory server (and ignore -bserver, -mdserver, and -server-root)
  -server-root string
    	directory to put local server files (and ignore -bserver and -mdserver)
  -test.bench string
    	regular expression to select benchmarks to run
  -test.benchmem
    	print memory allocations for benchmarks
  -test.benchtime duration
    	approximate run time for each benchmark (default 1s)
  -test.blockprofile string
    	write a goroutine blocking profile to the named file after execution
  -test.blockprofilerate int
    	if >= 0, calls runtime.SetBlockProfileRate() (default 1)
  -test.count n
    	run tests and benchmarks n times (default 1)
  -test.coverprofile string
    	write a coverage profile to the named file after execution
  -test.cpu string
    	comma-separated list of number of CPUs to use for each test
  -test.cpuprofile string
    	write a cpu profile to the named file during execution
  -test.memprofile string
    	write a memory profile to the named file after execution
  -test.memprofilerate int
    	if >=0, sets runtime.MemProfileRate
  -test.outputdir string
    	directory in which to write profiles
  -test.parallel int
    	maximum test parallelism (default 4)
  -test.run string
    	regular expression to select tests and examples to run
  -test.short
    	run smaller test suite to save time
  -test.timeout duration
    	if positive, sets an aggregate time limit for all tests
  -test.trace string
    	write an execution trace to the named file after execution
  -test.v
    	verbose: print additional output
  -version
    	Print version
```

**Comment by patrickxb** [comment]
Ok.  Can't `kbfsfuse` create its own `FlagSet`?

**Comment by akalin-keybase** [comment]
It can, but every executable that will depend on libkb will have to do a similar workaround. Seems cleaner to just fix the problem at the source, or at least paper it over closer to the course.

**Comment by akalin-keybase** [comment]
I'm resurrecting this PR. I changed it to define a `TestingTB` interface in libkb instead of relying on `logger.TestLogBackend`, and also removed an unnecessary `*testing.T` param in `go/teams/get.go`.

**Comment by akalin-keybase** [comment]
PTAL, @patrickxb

**Pull request merged**
