### PR TITLE
Thunderbolt icon color folder DESKTOP-1090

### PR DESCRIPTION
**Pull request by awendland**
Now the thunderbolt icon appropriately matches the text/desired color. This takes advantage of the new font icons implemented by @MarcoPolo.

**Look at these sweet examples of color matching:**

screen shot 2016-06-03 at 4 47 23 pm

screen shot 2016-06-03 at 4 47 40 pm

@keybase/react-hackers

### CODE REVIEW

**Comment by chrisnojima** [comment]
@chromakode any idea who no visdiff?

**Comment by chromakode** [comment]
@chrisnojima the build failed on flow before visdiff would run due to this weekend's flow breakage.

**Comment by keybase-ci-visdiff** [comment]
:mag_right: These commits introduced some visual changes:
 * Changed: **Menubar-Normal** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1465236925634-f45463d03e4a-d044ab695328/Menubar-Normal-f45463d03e4a.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1465236925634-f45463d03e4a-d044ab695328/Menubar-Normal-d044ab695328.png)  
   Menubar-Normal comparison
 * Changed: **Folders_TLF-Normal** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1465236925634-f45463d03e4a-d044ab695328/Folders_TLF-Normal-f45463d03e4a.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1465236925634-f45463d03e4a-d044ab695328/Folders_TLF-Normal-d044ab695328.png)  
   Folders_TLF-Normal comparison
 * Changed: **Files-Popup_Public** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1465236925634-f45463d03e4a-d044ab695328/Files-Popup_Public-f45463d03e4a.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1465236925634-f45463d03e4a-d044ab695328/Files-Popup_Public-d044ab695328.png)  
   Files-Popup_Public comparison
 * Changed: **Files-Popup_Private** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1465236925634-f45463d03e4a-d044ab695328/Files-Popup_Private-f45463d03e4a.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1465236925634-f45463d03e4a-d044ab695328/Files-Popup_Private-d044ab695328.png)  
   Files-Popup_Private comparison
 * Changed: **Files-Normal_Public** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1465236925634-f45463d03e4a-d044ab695328/Files-Normal_Public-f45463d03e4a.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1465236925634-f45463d03e4a-d044ab695328/Files-Normal_Public-d044ab695328.png)  
   Files-Normal_Public comparison
 * Changed: **Files-Normal_Private** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1465236925634-f45463d03e4a-d044ab695328/Files-Normal_Private-f45463d03e4a.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1465236925634-f45463d03e4a-d044ab695328/Files-Normal_Private-d044ab695328.png)  
   Files-Normal_Private comparison
 * Changed: **File-Normal_Public** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1465236925634-f45463d03e4a-d044ab695328/File-Normal_Public-f45463d03e4a.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1465236925634-f45463d03e4a-d044ab695328/File-Normal_Public-d044ab695328.png)  
   File-Normal_Public comparison
 * Changed: **File-Normal_Private_modified_by_self_long_file** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1465236925634-f45463d03e4a-d044ab695328/File-Normal_Private_modified_by_self_long_file-f45463d03e4a.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1465236925634-f45463d03e4a-d044ab695328/File-Normal_Private_modified_by_self_long_file-d044ab695328.png) [(diff)](http://keybase-app-visdiff.s3.amazonaws.com/1465236925634-f45463d03e4a-d044ab695328/File-Normal_Private_modified_by_self_long_file.png)
 * Changed: **File-Normal_Private_Long** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1465236925634-f45463d03e4a-d044ab695328/File-Normal_Private_Long-f45463d03e4a.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1465236925634-f45463d03e4a-d044ab695328/File-Normal_Private_Long-d044ab695328.png) [(diff)](http://keybase-app-visdiff.s3.amazonaws.com/1465236925634-f45463d03e4a-d044ab695328/File-Normal_Private_Long.png)
 * Changed: **File-Normal_Private** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1465236925634-f45463d03e4a-d044ab695328/File-Normal_Private-f45463d03e4a.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1465236925634-f45463d03e4a-d044ab695328/File-Normal_Private-d044ab695328.png) [(diff)](http://keybase-app-visdiff.s3.amazonaws.com/1465236925634-f45463d03e4a-d044ab695328/File-Normal_Private.png)

**Comment by chrisnojima** [comment]
👍 i'm fine with the small offsets, we can fix that up later if design is annoyed

**Pull request merged**
