### PR TITLE
Signup fixes

### PR DESCRIPTION
**Pull request by MarcoPolo**
@keybase/react-hackers 

A couple signup fixes, will really hammer it more tomorrow.

## Preview signup error page
screen shot 2016-03-22 at 8 34 23 pm

This screen isn't designed, but we really should almost never go in here. Only in cases where we didn't handle an error before hand.

### CODE REVIEW

**Comment by chrisnojima** [comment]
we should likely use the same scaffoldling the login error page does. At least have the back button to reset back to the beginning

**Comment by MarcoPolo** [comment]
> At least have the back button to reset back to the beginning

That's what the try again button does

**Comment by chrisnojima** [comment]
:+1: i just mean you can literally use the back button we have on all the other screens so it matches

**Comment by MarcoPolo** [comment]
screen shot 2016-03-23 at 3 17 49 pm

@chrisnojima updated

**Comment by chrisnojima** [comment]
:+1:

**Pull request merged**
