### PR TITLE
user-block when you chat-block an impteam 1on1 convo

### PR DESCRIPTION
**Pull request by xgess**
chat-blocking and user-blocking are confusingly very different things, and we have at least one log of someone who thought they blocked but they only chat-blocked. 

so, when a user chat-blocks (or reports) a 1-on-1 implicit conversation, also go ahead and user-block that person. this should only execute if it's two people in a non-team conversation, one of whom is the caller. 

i didn't implement unblocking. i figured this was unlikely to be a heavily demanded thing, it adds a bunch of complexity, and you can always manually unblock the person if you go their profile.

### CODE REVIEW

**Comment by xgess** [comment]
@keybase/picnicsquad

**Comment by strib** [comment]
@xgess in the ticket PICNIC-367 that I filed, I had blocked the user from their profile.  Does this PR still fix that case?  (From the description it seems like it's fixing something different.)

**Comment by xgess** [comment]
@strib the description of the ticket is fixed by https://github.com/keybase/keybase/pull/4337. this fixes the logdump that was linked. while not exactly a bug, this does fix something that's pretty unintuitive.

**Comment by strib** [comment]
Ah makes sense, I missed that one.  Thanks!

**Pull request merged**
