### PR TITLE
Add invite link section to non user info pane

### PR DESCRIPTION
**Pull request by MarcoPolo**
@keybase/react-hackers 

Hopefully the visdiff will show the changes.

But this adds sections for an invite link and an out of invites option.

We still need to hook those up, and it doesn't look like we have a system yet for requesting an invite code for a user (?)

### CODE REVIEW

**Comment by keybase-ci-visdiff** [comment]
:mag_right: The commits 84496723ca2f...877c66e8aa15 introduced some visual changes on win32:
 * Added: **Search_Non_User_Pane-Out_of_invites**  
   Search_Non_User_Pane-Out_of_invites rendered
 * Added: **Search_Non_User_Pane-Has_Invite**  
   Search_Non_User_Pane-Has_Invite rendered
 * Changed: **Login_Signed_Out-Error** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1467075050094-84496723ca2f-877c66e8aa15-win32/Login_Signed_Out-Error-84496723ca2f.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1467075050094-84496723ca2f-877c66e8aa15-win32/Login_Signed_Out-Error-877c66e8aa15.png)  
   Login_Signed_Out-Error comparison

**Comment by keybase-ci-visdiff** [comment]
:mag_right: The commits 84496723ca2f...877c66e8aa15 introduced some visual changes on linux:
 * Added: **Search_Non_User_Pane-Out_of_invites**  
   Search_Non_User_Pane-Out_of_invites rendered
 * Added: **Search_Non_User_Pane-Has_Invite**  
   Search_Non_User_Pane-Has_Invite rendered

**Comment by chrisnojima** [comment]
they can request invites on the web page

**Comment by chrisnojima** [comment]
👍

**Pull request merged**
