### PR TITLE
Expanded profile component & dumb sheet afterMount callback

### PR DESCRIPTION
**Pull request by chromakode**
:eyeglasses: @keybase/react-hackers 

Here's the full profile page, and a nifty new `afterMount` callback for dumb component to enable manipulation of state/DOM to exercise new permutations for screenshots (such as scrolling, as used here).

Remaining work (which should probably be ticketed):
 * Merge the FIXME'd `UserInfo` in `Friendships` with the `UserBio` definition. Will need to add `username` to the type.
 * Devices and key fingerprint aren't rendered yet, as per the original ticket.
 * There's a minor visual bug where the 1px space between usernames causes gaps in the hover underline. Spent some time whacking at this and couldn't find an easy solution. screen shot 2016-06-21 at 6 46 41 pm

### CODE REVIEW

**Comment by chromakode** [comment]
retest this please

**Comment by keybase-ci-visdiff** [comment]
:mag_right: The commits f050e025b323...ca091510d5ce introduced some visual changes:
 * Added: **Profile-Unfollowed_Scrolled**  
   Profile-Unfollowed_Scrolled rendered
 * Added: **Profile-Unfollowed_Folders_Expanded**  
   Profile-Unfollowed_Folders_Expanded rendered
 * Added: **Profile-Unfollowed_Few_Folders**  
   Profile-Unfollowed_Few_Folders rendered
 * Added: **Profile-Changed_Scrolled**  
   Profile-Changed_Scrolled rendered
 * Changed: **Search_User_Pane-Unfollowed_Scrolling** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1466562318074-f050e025b323-ca091510d5ce/Search_User_Pane-Unfollowed_Scrolling-f050e025b323.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1466562318074-f050e025b323-ca091510d5ce/Search_User_Pane-Unfollowed_Scrolling-ca091510d5ce.png)  
   Search_User_Pane-Unfollowed_Scrolling comparison
 * Changed: **Search_User_Pane-Unfollowed** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1466562318074-f050e025b323-ca091510d5ce/Search_User_Pane-Unfollowed-f050e025b323.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1466562318074-f050e025b323-ca091510d5ce/Search_User_Pane-Unfollowed-ca091510d5ce.png)  
   Search_User_Pane-Unfollowed comparison
 * Changed: **Search_User_Pane-Followed** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1466562318074-f050e025b323-ca091510d5ce/Search_User_Pane-Followed-f050e025b323.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1466562318074-f050e025b323-ca091510d5ce/Search_User_Pane-Followed-ca091510d5ce.png)  
   Search_User_Pane-Followed comparison
 * Changed: **Search_User_Pane-Changed** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1466562318074-f050e025b323-ca091510d5ce/Search_User_Pane-Changed-f050e025b323.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1466562318074-f050e025b323-ca091510d5ce/Search_User_Pane-Changed-ca091510d5ce.png) [(diff)](http://keybase-app-visdiff.s3.amazonaws.com/1466562318074-f050e025b323-ca091510d5ce/Search_User_Pane-Changed.png)
 * Changed: **Search_Non_User_Pane-Normal** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1466562318074-f050e025b323-ca091510d5ce/Search_Non_User_Pane-Normal-f050e025b323.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1466562318074-f050e025b323-ca091510d5ce/Search_Non_User_Pane-Normal-ca091510d5ce.png) [(diff)](http://keybase-app-visdiff.s3.amazonaws.com/1466562318074-f050e025b323-ca091510d5ce/Search_Non_User_Pane-Normal.png)
 * Changed: **Search_Non_User_Pane-No_Avatar** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1466562318074-f050e025b323-ca091510d5ce/Search_Non_User_Pane-No_Avatar-f050e025b323.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1466562318074-f050e025b323-ca091510d5ce/Search_Non_User_Pane-No_Avatar-ca091510d5ce.png) [(diff)](http://keybase-app-visdiff.s3.amazonaws.com/1466562318074-f050e025b323-ca091510d5ce/Search_Non_User_Pane-No_Avatar.png)
 * Changed: **Profile-Unfollowed** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1466562318074-f050e025b323-ca091510d5ce/Profile-Unfollowed-f050e025b323.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1466562318074-f050e025b323-ca091510d5ce/Profile-Unfollowed-ca091510d5ce.png) [(diff)](http://keybase-app-visdiff.s3.amazonaws.com/1466562318074-f050e025b323-ca091510d5ce/Profile-Unfollowed.png)
 * Changed: **Profile-Followed** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1466562318074-f050e025b323-ca091510d5ce/Profile-Followed-f050e025b323.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1466562318074-f050e025b323-ca091510d5ce/Profile-Followed-ca091510d5ce.png) [(diff)](http://keybase-app-visdiff.s3.amazonaws.com/1466562318074-f050e025b323-ca091510d5ce/Profile-Followed.png)
 * Changed: **Profile-Changed** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1466562318074-f050e025b323-ca091510d5ce/Profile-Changed-f050e025b323.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1466562318074-f050e025b323-ca091510d5ce/Profile-Changed-ca091510d5ce.png) [(diff)](http://keybase-app-visdiff.s3.amazonaws.com/1466562318074-f050e025b323-ca091510d5ce/Profile-Changed.png)
 * Removed: **Friendships-Following** [(view original)](http://keybase-app-visdiff.s3.amazonaws.com/1466562318074-f050e025b323-ca091510d5ce/Friendships-Following-f050e025b323.png)
 * Removed: **Friendships-Followers** [(view original)](http://keybase-app-visdiff.s3.amazonaws.com/1466562318074-f050e025b323-ca091510d5ce/Friendships-Followers-f050e025b323.png)

**Comment by chromakode** [comment]
This visdiff looks as expected. The search user pane profiles moved down a bit because we needed to make extra space for the sticky "back button" area at the top of the view, and wanted both the profile and the search panes to have the same layout.

**Comment by chrisnojima** [comment]
👍

**Pull request merged**
