### PR TITLE
minor visual tweaks [HOTPOT-149]

### PR DESCRIPTION
**Pull request by joshblum**
before:
Screen Shot 2019-06-14 at 3 03 22 PM
after:
Screen Shot 2019-06-14 at 2 53 58 PM

cc @keybase/hotpotatosquad

### CODE REVIEW

**Comment by chrisnojima** [comment]
i don't think we center text like this.
cc: @cecileboucheron

**Comment by joshblum** [comment]
if not we should change some of the other messages: 
image

**Comment by chrisnojima** [comment]
to further clarify. we center text but we don't center bulleted text

**Comment by joshblum** [comment]
@cecileboucheron updated as discussed in chat:
Screen Shot 2019-06-14 at 5 14 23 PM
Screen Shot 2019-06-14 at 5 21 36 PM
image

**Comment by joshblum** [comment]
@cecileboucheron as discussed over chat timestamp is now in a separate component so these message have a consistent font size/top margin

Screen Shot 2019-06-17 at 10 29 06 AM

**Pull request merged**
