### PR TITLE
Shrinked windows systray icon to 16x16

### PR DESCRIPTION
**Pull request by cecileboucheron**
@zanderz

### CODE REVIEW

**Comment by keybase-ci-visdiff** [comment]
The commits 97af84f3802c...6263a7912785 introduce visual changes on linux. <details><summary>:mag_right: 1 changed</summary>

 * Changed: **unlock_folders-No_paperkeys** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488324567968-97af84f3802c-6263a7912785-linux/unlock_folders-No_paperkeys-97af84f3802c.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488324567968-97af84f3802c-6263a7912785-linux/unlock_folders-No_paperkeys-6263a7912785.png)  
   unlock_folders-No_paperkeys comparison
</summary>

**Comment by keybase-ci-visdiff** [comment]
The commits 8e977c24e27c...6263a7912785 introduce visual changes on linux. <details><summary>:mag_right: 1 removed, 14 changed</summary>

 * Changed: **Popup_Attachment-Popup_Attachment_Message** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488407938961-8e977c24e27c-6263a7912785-linux/Popup_Attachment-Popup_Attachment_Message-8e977c24e27c.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488407938961-8e977c24e27c-6263a7912785-linux/Popup_Attachment-Popup_Attachment_Message-6263a7912785.png)  
   Popup_Attachment-Popup_Attachment_Message comparison
 * Changed: **Popup_Attachment-Popup_Attachment_Downloaded** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488407938961-8e977c24e27c-6263a7912785-linux/Popup_Attachment-Popup_Attachment_Downloaded-8e977c24e27c.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488407938961-8e977c24e27c-6263a7912785-linux/Popup_Attachment-Popup_Attachment_Downloaded-6263a7912785.png)  
   Popup_Attachment-Popup_Attachment_Downloaded comparison
 * Changed: **Popup-Following_Valid** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488407938961-8e977c24e27c-6263a7912785-linux/Popup-Following_Valid-8e977c24e27c.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488407938961-8e977c24e27c-6263a7912785-linux/Popup-Following_Valid-6263a7912785.png)  
   Popup-Following_Valid comparison
 * Changed: **Popup-Following_Revoked** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488407938961-8e977c24e27c-6263a7912785-linux/Popup-Following_Revoked-8e977c24e27c.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488407938961-8e977c24e27c-6263a7912785-linux/Popup-Following_Revoked-6263a7912785.png)  
   Popup-Following_Revoked comparison
 * Changed: **Folders_TLF-Normal_Public** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488407938961-8e977c24e27c-6263a7912785-linux/Folders_TLF-Normal_Public-8e977c24e27c.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488407938961-8e977c24e27c-6263a7912785-linux/Folders_TLF-Normal_Public-6263a7912785.png)  
   Folders_TLF-Normal_Public comparison
 * Changed: **Chat_Conversations_List-You_Rekey_Selected** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488407938961-8e977c24e27c-6263a7912785-linux/Chat_Conversations_List-You_Rekey_Selected-8e977c24e27c.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488407938961-8e977c24e27c-6263a7912785-linux/Chat_Conversations_List-You_Rekey_Selected-6263a7912785.png)  
   Chat_Conversations_List-You_Rekey_Selected comparison
 * Changed: **Chat_Conversations_List-You_Rekey** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488407938961-8e977c24e27c-6263a7912785-linux/Chat_Conversations_List-You_Rekey-8e977c24e27c.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488407938961-8e977c24e27c-6263a7912785-linux/Chat_Conversations_List-You_Rekey-6263a7912785.png)  
   Chat_Conversations_List-You_Rekey comparison
 * Changed: **Chat_Conversations_List-Selected_Normal** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488407938961-8e977c24e27c-6263a7912785-linux/Chat_Conversations_List-Selected_Normal-8e977c24e27c.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488407938961-8e977c24e27c-6263a7912785-linux/Chat_Conversations_List-Selected_Normal-6263a7912785.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488407938961-8e977c24e27c-6263a7912785-linux/Chat_Conversations_List-Selected_Normal.png)
 * Changed: **Chat_Conversations_List-Selected_Muted** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488407938961-8e977c24e27c-6263a7912785-linux/Chat_Conversations_List-Selected_Muted-8e977c24e27c.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488407938961-8e977c24e27c-6263a7912785-linux/Chat_Conversations_List-Selected_Muted-6263a7912785.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488407938961-8e977c24e27c-6263a7912785-linux/Chat_Conversations_List-Selected_Muted.png)
 * Changed: **Chat_Conversations_List-Part_Rekey_Selected** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488407938961-8e977c24e27c-6263a7912785-linux/Chat_Conversations_List-Part_Rekey_Selected-8e977c24e27c.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488407938961-8e977c24e27c-6263a7912785-linux/Chat_Conversations_List-Part_Rekey_Selected-6263a7912785.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488407938961-8e977c24e27c-6263a7912785-linux/Chat_Conversations_List-Part_Rekey_Selected.png)
 * Changed: **Chat_Conversations_List-Part_Rekey** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488407938961-8e977c24e27c-6263a7912785-linux/Chat_Conversations_List-Part_Rekey-8e977c24e27c.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488407938961-8e977c24e27c-6263a7912785-linux/Chat_Conversations_List-Part_Rekey-6263a7912785.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488407938961-8e977c24e27c-6263a7912785-linux/Chat_Conversations_List-Part_Rekey.png)
 * Changed: **Chat_Conversations_List-Normal** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488407938961-8e977c24e27c-6263a7912785-linux/Chat_Conversations_List-Normal-8e977c24e27c.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488407938961-8e977c24e27c-6263a7912785-linux/Chat_Conversations_List-Normal-6263a7912785.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488407938961-8e977c24e27c-6263a7912785-linux/Chat_Conversations_List-Normal.png)
 * Changed: **Chat_Conversations_List-Long_Top** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488407938961-8e977c24e27c-6263a7912785-linux/Chat_Conversations_List-Long_Top-8e977c24e27c.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488407938961-8e977c24e27c-6263a7912785-linux/Chat_Conversations_List-Long_Top-6263a7912785.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488407938961-8e977c24e27c-6263a7912785-linux/Chat_Conversations_List-Long_Top.png)
 * Changed: **Attachment_Popup-Following_Popup_Showing** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488407938961-8e977c24e27c-6263a7912785-linux/Attachment_Popup-Following_Popup_Showing-8e977c24e27c.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488407938961-8e977c24e27c-6263a7912785-linux/Attachment_Popup-Following_Popup_Showing-6263a7912785.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488407938961-8e977c24e27c-6263a7912785-linux/Attachment_Popup-Following_Popup_Showing.png)
 * Removed: **Text_Message-failure_reason** [(view original)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488407938961-8e977c24e27c-6263a7912785-linux/Text_Message-failure_reason-8e977c24e27c.png)
</summary>

**Comment by cecileboucheron** [comment]
@chromakode Updated!
@zanderz Can I let you double check and see if that still works well? I renamed the icons with "16" and tweaked the code.

**Comment by keybase-ci-visdiff** [comment]
The commits 3e6d6512af96...b45967383923 introduce visual changes on linux. <details><summary>:mag_right: 1 removed, 9 changed</summary>

 * Changed: **Folders_TLF-Normal_Public** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488846325642-3e6d6512af96-b45967383923-linux/Folders_TLF-Normal_Public-3e6d6512af96.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488846325642-3e6d6512af96-b45967383923-linux/Folders_TLF-Normal_Public-b45967383923.png)  
   Folders_TLF-Normal_Public comparison
 * Changed: **Chat_Conversations_List-You_Rekey_Selected** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488846325642-3e6d6512af96-b45967383923-linux/Chat_Conversations_List-You_Rekey_Selected-3e6d6512af96.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488846325642-3e6d6512af96-b45967383923-linux/Chat_Conversations_List-You_Rekey_Selected-b45967383923.png)  
   Chat_Conversations_List-You_Rekey_Selected comparison
 * Changed: **Chat_Conversations_List-You_Rekey** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488846325642-3e6d6512af96-b45967383923-linux/Chat_Conversations_List-You_Rekey-3e6d6512af96.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488846325642-3e6d6512af96-b45967383923-linux/Chat_Conversations_List-You_Rekey-b45967383923.png)  
   Chat_Conversations_List-You_Rekey comparison
 * Changed: **Chat_Conversations_List-Selected_Normal** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488846325642-3e6d6512af96-b45967383923-linux/Chat_Conversations_List-Selected_Normal-3e6d6512af96.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488846325642-3e6d6512af96-b45967383923-linux/Chat_Conversations_List-Selected_Normal-b45967383923.png)  
   Chat_Conversations_List-Selected_Normal comparison
 * Changed: **Chat_Conversations_List-Selected_Muted** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488846325642-3e6d6512af96-b45967383923-linux/Chat_Conversations_List-Selected_Muted-3e6d6512af96.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488846325642-3e6d6512af96-b45967383923-linux/Chat_Conversations_List-Selected_Muted-b45967383923.png)  
   Chat_Conversations_List-Selected_Muted comparison
 * Changed: **Chat_Conversations_List-Part_Rekey_Selected** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488846325642-3e6d6512af96-b45967383923-linux/Chat_Conversations_List-Part_Rekey_Selected-3e6d6512af96.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488846325642-3e6d6512af96-b45967383923-linux/Chat_Conversations_List-Part_Rekey_Selected-b45967383923.png)  
   Chat_Conversations_List-Part_Rekey_Selected comparison
 * Changed: **Chat_Conversations_List-Part_Rekey** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488846325642-3e6d6512af96-b45967383923-linux/Chat_Conversations_List-Part_Rekey-3e6d6512af96.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488846325642-3e6d6512af96-b45967383923-linux/Chat_Conversations_List-Part_Rekey-b45967383923.png)  
   Chat_Conversations_List-Part_Rekey comparison
 * Changed: **Chat_Conversations_List-Normal** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488846325642-3e6d6512af96-b45967383923-linux/Chat_Conversations_List-Normal-3e6d6512af96.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488846325642-3e6d6512af96-b45967383923-linux/Chat_Conversations_List-Normal-b45967383923.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488846325642-3e6d6512af96-b45967383923-linux/Chat_Conversations_List-Normal.png)
 * Changed: **Chat_Conversations_List-Long_Top** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488846325642-3e6d6512af96-b45967383923-linux/Chat_Conversations_List-Long_Top-3e6d6512af96.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488846325642-3e6d6512af96-b45967383923-linux/Chat_Conversations_List-Long_Top-b45967383923.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488846325642-3e6d6512af96-b45967383923-linux/Chat_Conversations_List-Long_Top.png)
 * Removed: **Text_Message-failure_reason** [(view original)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488846325642-3e6d6512af96-b45967383923-linux/Text_Message-failure_reason-3e6d6512af96.png)
</summary>

**Pull request merged**
