### PR TITLE
more right padding on mobile chat

### PR DESCRIPTION
**Pull request by zanderz**
Before:
simulator screen shot - iphone 6 - 2019-01-04 at 10 49 28

After:
simulator screen shot - iphone 6 - 2019-01-04 at 10 48 40

### CODE REVIEW

**Comment by mmaxim** [comment]
What does this do to attachments?

**Comment by mmaxim** [comment]
Also why do this? It looks better Before to me.

**Comment by cecileboucheron** [comment]
@mmaxim The text is too close to the right edge now.. This aligns it with the spacing with have in the header and in the nav.

**Comment by mmaxim** [comment]
What does this do to exploding messages, those already get pushed way over due to the clock and timer? The actual text is going to be like 60% across the screen.

**Comment by zanderz** [comment]
It seems that attachments and bomb icons aren't squished over as far as the text. IDK, it is @cecileboucheron 's ticket.
simulator screen shot - iphone 6 - 2019-01-04 at 11 53 47

**Comment by mmaxim** [comment]
Ok if that is the plan, sounds ok to me. Look like a separate bug though with exploding stuff and attachments.

**Pull request merged**
