### PR TITLE
add labelTooltip to Kb.Switch

### PR DESCRIPTION
**Pull request by songgao**

### CODE REVIEW

**Comment by songgao** [comment]
@keybase/react-hackers bump!

**Comment by songgao** [comment]
Oh good point; I guess it makes sense on desktop. On mobile that's the clicking area so can't really do that. Will update.

**Comment by jakob223** [comment]
tooltip

nitty nit: the tooltip is to the left of center on large texts. Feel free to decide it's not worth fixing if it's too hard.

**Comment by songgao** [comment]
> the tooltip is to the left of center on large texts.

That was an intentional change. My thought was that this way the tooltip would appear right above the actual switch. So if user hovers on the switch (as you mentioned) it'd be easier to see. If it's right aligned, the tooltip appears on the right side. Let me know if you don't agree!

**Pull request merged**
