### PR TITLE
Apply filter to teamnames for small teams

### PR DESCRIPTION
**Pull request by akalin-keybase**

### CODE REVIEW

**Comment by akalin-keybase** [comment]
Ah, ok.

**Comment by chrisnojima** [comment]
sorry I don't mean that we should necessarily close this pr. More that we do have a or which affects this flow and if that pr solves this (I don't recall) maybe we should imply it the same way

**Comment by chrisnojima** [comment]
Imply - implement

**Comment by akalin-keybase** [comment]
Took a look at that PR, and it looks like it doesn't do what this PR does.

**Comment by cjb** [comment]
+1 to merging in this PR since it solves a release bug simply (can't filter to small teams).

**Pull request merged**
