### PR TITLE
Undo nuke session.json PR et al

### PR DESCRIPTION
**Pull request by patrickxb**
This undoes #2279, #2257, and emergency commits to master 3ed03883ef26cb872f93744063e3120d7287c9d2 and 3f5393c7f51c9db8070aac72ad3d4100723973b8

Local tests pass...

r? @maxtaco 

cc @cjb @chrisnojima

### CODE REVIEW

**Comment by maxtaco** [comment]
Can you confirm fixes to the desktop and kbfs and Linux issues we have hit?
We might need an assist on the Linux issues.

**Comment by patrickxb** [comment]
@cjb can you help with linux?

i'll make an os x build locally.

**Comment by maxtaco** [comment]
I defer to @cjb or @chrisnojima

**Comment by cjb** [comment]
hm, we're still in a @oconnor663's machine build world on Linux, and I can't trigger a build until the Slackbot Linux story's done.  It might be easiest to wait for tomorrow morning's autobuild.

**Comment by patrickxb** [comment]
OS X app working as expected with this branch.

started up, logged in, manually killed service, launchctl restarted it, `ls /keybase/private/patrick` triggered pinentry.

**Comment by maxtaco** [comment]
Same goes for `keybase track foobob` after a restart?

**Comment by patrickxb** [comment]
@cjb so packaging/prerelease/build_app.sh is linux only?

**Comment by patrickxb** [comment]
@maxtaco yes on the track after restart.

**Comment by cjb** [comment]
@patrickxb Yes, OSX only.

Linux instructions are:

* You need the GPG key
* You need S3 credentials for `s3cmd` configured in your home dir
* KBFS needs to be cloned next to client
* Then run `packaging/linux/docker_build.sh prerelease`

But I'm reluctant to run them for the first time on another machine while Jack isn't around.  (I should've set up on my machine earlier.)

**Comment by cjb** [comment]
:thumbsup:

**Pull request merged**
