### PR TITLE
Add missing babel stage-2 preset npm module

### PR DESCRIPTION
**Pull request by dannysu**
Couldn't build on Arch Linux without this.

### CODE REVIEW

**Comment by oconnor663** [comment]
Hmm, I can build on Arch without this change, even with a totally clean Linux user. Here's what I'm doing:

```
git clone https://github.com/keybase/client
cd client/packaging/linux
./build_binaries.sh prerelease
```

Is that failing for you without the package.json change? Any idea what the difference could be?

**Comment by cjb** [comment]
I've seen that error before when I was using an older version of node+npm, maybe that's related?

**Comment by dannysu** [comment]
Using newest npm and from scratch again worked.

Sorry, I guess I must have missed a step somewhere.
I was using older node+npm but I did try switching to newest npm, checked the version, and built again.

**Comment by cjb** [comment]
No worries, I had to reinstall modules too.  @chrisnojima, think we should take this PR to avoid a confusing error for users of older Node?

**Comment by chrisnojima** [comment]
I don't think we should. We already include stage-1 which is a subset of stage-2,3 etc. It would be more confusing to have overlapping presets I think

**Pull request closed without merging**
