### PR TITLE
Script to install KBFuse from installer

### PR DESCRIPTION
**Pull request by gabriel**
Run `packaging/desktop/kbfuse.sh` as root (via sudo?), since installing the kext requires root access.

We use a OS level privileged helper tool to do this in the real app but this script can be used for build or test machines.

### CODE REVIEW

**Comment by gabriel** [comment]
@cjb @jzila

**Comment by jzila** [comment]
The script mentions a specific release. Can this instead query https://api.github.com/repos/keybase/client/releases/latest, and pull the latest release?

Additionally, why do we have multiple Darwin versions in the same release?
https://github.com/keybase/client/releases/tag/v1.0.16

**Comment by gabriel** [comment]
Instead of doing logic to query for latest asset, I added some documentation to update scripts for new installer builds. I think this is better, cause we can PR and test changes instead of stuff breaking if a new asset is uploaded that is broken (which takes no review).

There are multiple versions so old branches work. But probably don't need to keep for more than a few weeks max.

**Comment by jzila** [comment]
But why would we upload assets that haven't passed QA?

**Comment by gabriel** [comment]
Sometimes we do local test builds that we don't ship that point to specific installer versions, specifically for testing. I guess I could put them somewhere else other than github releases but it was easier to put there than to put somewhere else and then copy it there once we released it...

**Comment by jzila** [comment]
Right but those releases get put on S3, they don't need to be published on the github page, which should be kind of an official source of truth.

**Comment by gabriel** [comment]
I guess we already updated the macOS machines manually so this wasn't necessary. But maybe merge this in anyway?

**Pull request merged**
