### PR TITLE
Stop using relative cd to paths in travis.yml

### PR DESCRIPTION
**Pull request by cjb**
@oconnor663 @chrisnojima fixes broken master build

### CODE REVIEW

**Comment by keybase-ci-visdiff** [comment]
:mag_right: No visual changes found as a result of these commits.

**Comment by oconnor663** [comment]
This looks good. Would it also be safer to put all of our `cd`s in parens?

**Comment by oconnor663** [comment]
Ok we tried that and it was surprisingly ugly :p

**Comment by oconnor663** [comment]
I'd say if we have yet another `cd` bug we can come back to this and consider re-paren-ifying the whole thing. Until then, :+1:

**Pull request merged**
