### PR TITLE
handle 10 bad kex2 phrase attempts

### PR DESCRIPTION
**Pull request by maxtaco**

### CODE REVIEW

**Comment by patrickxb** [comment]
what's the change here besides moving to a function?

**Comment by maxtaco** [comment]
that we call `cancel()` after we fail 10x. before, the app just hung indefinitely

**Comment by patrickxb** [comment]
ok, thanks.  my human diff didn't see that.

**Comment by maxtaco** [comment]
sure thing.  yeah, i refactored so it was easier to forget to cancel on error.

**Pull request merged**
