### PR TITLE
return proper CA for kb-aws.net

### PR DESCRIPTION
**Pull request by songgao**

### CODE REVIEW

**Comment by maxtaco** [comment]
I am surprised we need this. Does KBFS vendor this in?

**Comment by maxtaco** [comment]
The existence of this domain is meant to be totally irrelevant to the users and user-facing clients.

**Comment by songgao** [comment]
@maxtaco Yeah; we use the same package as client: https://github.com/keybase/kbfs-server/blob/24b205366fe1dbdde5dbfea0150d22d0ddad5b51/serverutil/api_notifier_base.go#L82 Should we not?

**Comment by songgao** [comment]
I guess we could have a separate thing in `kbfs-server`. Closing!

**Pull request closed without merging**
