### PR TITLE
Mobile: Chat input

### PR DESCRIPTION
**Pull request by cjb**
@keybase/react-hackers 

Here's a simple implementation of the mobile chat input -- it's single line, since multiline would involve a separate button for submitting the written text and that's not in our screens.  It's hard to work on further until it's integrated, so let's get something basic in and iterate.

I found something surprising, maybe someone else knows the history here: we don't have anything bound to the `onSubmitEditing` prop (the callback for when you finish typing on an on-screen keyboard) on mobile, for any of our input widgets or in the common adapter.  So I added that prop to the Input component, and now pressing the return/finished button fires the callback.  Should we go through and add `onSubmitEditing` to our other mobile input components too, e.g. signup/login?  I think it's currently the case that you have to hit enter to make the keyboard go away on those screens, and then manually click the "Continue" button on each screen.

### CODE REVIEW

**Comment by keybase-ci-visdiff** [comment]
The commits e9038c9d12bb...5d58cdcf3617 introduce visual changes on linux. <details><summary>:mag_right: 1 removed</summary>

 * Removed: **Chat_Input-Empty** [(view original)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1487192772656-e9038c9d12bb-5d58cdcf3617-linux/Chat_Input-Empty-e9038c9d12bb.png)
</summary>

**Comment by chrisnojima** [comment]
I think we should use onEnterKeyDown instead, we essentially mean that to be the same thing, it should be plumbed through so it triggers it, but it don't think we need a different external api

**Comment by cjb** [comment]
@chrisnojima Ah, maybe a RN change then -- onEnterKeyDown doesn't fire.

**Comment by chrisnojima** [comment]
no i mean, that's our api. same as onClicked. the common-adapters have a more desktop centric api, but they need to be plumbed through to the native versions
so onClick is hooked up to onTouchTap or whatever and in this instance we want
onSubmitEditing to trigger the onEnterKeyDown callback if you have one

**Comment by cjb** [comment]
Oh, I get it, you're saying the Input adapter should pass onFinishEditing=this.props.onEnterKeyDown to the native input?

**Comment by cjb** [comment]
@chrisnojima Thanks! Made and tested that change.

**Comment by keybase-ci-visdiff** [comment]
The commits e9038c9d12bb...49ec75522ebd introduce visual changes on linux. <details><summary>:mag_right: 1 removed</summary>

 * Removed: **Chat_Input-Empty** [(view original)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1487260055472-e9038c9d12bb-49ec75522ebd-linux/Chat_Input-Empty-e9038c9d12bb.png)
</summary>

**Comment by cjb** [comment]
@chrisnojima bump

**Pull request merged**
