### PR TITLE
More log formatting

### PR DESCRIPTION
**Pull request by zanderz**
These are hard to find.
@maxtaco @patrickxb

### CODE REVIEW

**Comment by maxtaco** [comment]
Looks OK to me, @patrickxb look ok to you?

**Comment by patrickxb** [comment]
What does this fix?  Is there a jira ticket?

**Comment by zanderz** [comment]
Sometimes a line containing a percent sign gets logged and these places
where it is treated as a format string munge it up. I found the main ones
earlier but had missed these (possibly by running -standalone for
debugging). I knew Max saw these yesterday but I neglected to explain it to
you, sorry.

**Comment by maxtaco** [comment]
Agreed, this is a long-standing bug in logging that mangles URLs with %-decoding. So it's definitely an issue. The question is, is this solution OK? I think so, but just wanted to double-check.

**Comment by zanderz** [comment]
One contributing problem might be that in the logging library[ies], debug()
is a copy of debugf(), both using the first argument as a formatting
string, which is misleading and doesn't seem necessary.

**Comment by patrickxb** [comment]
Ok, LGTM.

**Pull request merged**
