### PR TITLE
Run all tests instead of exiting at first failure

### PR DESCRIPTION
**Pull request by zanderz**
What do you think of this @maxtaco ?

### CODE REVIEW

**Comment by maxtaco** [comment]
did you test it to work as planned?  looks good if it works!

**Comment by zanderz** [comment]
It was a big pain to make it work on Ubuntu (I learned that /bin/sh means Dash instead of Bash by default on Ubuntu) so maybe I will ask a mac person to try before I merge it.

**Comment by maxtaco** [comment]
if you need bash features then you should definitely as for bash
explicitly.  `#!/bin/bash` is probably good on most platforms....

**Comment by zanderz** [comment]
ok it works on Ubuntu and Windows with bash. should I merge it or have someone test it on Mac?

**Comment by maxtaco** [comment]
👍

**Pull request merged**
