### PR TITLE
add empty files to please the windows installer

### PR DESCRIPTION
**Pull request by xgess**
as part of our installation process, wix creates a database of things to delete on uninstall. the template that helps to generate this list assumes that every folder has a file in it, but every now and again, there comes along a folder that only contains folders. then it doesn't get marked for deletion and there's an error like this:

```
error LGHT0204: ICE64: The directory is in the user profile but is not listed in the RemoveFile table
```

so, rather than futz with the template (which is much more prone to me screwing something up), i added a bit to the build process. After generating all the files but before passing them to wix, recursively step through every directory and add an empty file if there arent any other files present. currently this only happens in one place, but hopefully this fix is future-proof enough that no one needs to come back to look at this message in the future.

### CODE REVIEW

**Comment by taruti** [comment]
Perhaps we should fix the template? This seems somewhat hacky. But of course if that is not possible, then this is the way to go.

**Comment by xgess** [comment]
> Perhaps we should fix the template? This seems somewhat hacky. But of course if that is not possible, then this is the way to go.

yeah - i did. my previous comment is a little disingenuous. i tried to tweak the template to add these RemoveFolder nodes for each directory instead of each file (and with various arguments to heat), but i couldn't get it to work. i'll give it another serious look though because you're right. this solution, while i learned a lot about windows batch scripting making it, is a good bit hackier than doing it directly in heat.

**Comment by taruti** [comment]
ok, lets do it.

**Comment by zapu** [comment]
is there something you'd like us to test on our machines before getting this in?

**Comment by xgess** [comment]
> is there something you'd like us to test on our machines before getting this in?

@zapu nah thanks. if it works to build the app on my machine and the build bot, i suspect we don't need more data points.

**Pull request merged**
