### PR TITLE
golangci-lint: disable `ifElseChain`

### PR DESCRIPTION
**Pull request by strib**
By popular vote.

### CODE REVIEW

**Comment by heronhaye** [comment]
It's very minor but I'm not a fan of singleCaseSwitch either. For cases where I'm switching on an enum but it only has one value right now. https://github.com/keybase/client/pull/18751/files#diff-b5f24cfde42ac5f61c23f2e532140669L24

Don't really mind either way though

**Comment by strib** [comment]
@heronhaye sure, though in cases like that it's easy enough to keep the linter happy by adding a default case with a log statement or something, which is arguably what you should be doing anyway for code clarity, to communicate that the single-case switch is intentional.

**Comment by strib** [comment]
(And actually, a comment in the `default` case seems fine too.)

**Comment by heronhaye** [comment]
good point. I could have moved the return statement into a default in that code as well

**Pull request merged**
