### PR TITLE
use int64 for chat attachment sizes

### PR DESCRIPTION
**Pull request by zanderz**

### CODE REVIEW

**Comment by maxtaco** [comment]
Delegate to @patrickxb

**Comment by patrickxb** [comment]
Could you test (manually) that downloading an attachment uploaded with the old protocol works with the new protocol?

**Comment by patrickxb** [comment]
Attachment stuff looks good to me.

Are the simplefs changes meant to be in a separate PR?

**Comment by zanderz** [comment]
I just did a download test, seems ok - did a binary compare for good measure.

**Comment by patrickxb** [comment]
re: download test: sounds good.

What about the simplefs changes?  Are those in this PR by accident?

**Comment by zanderz** [comment]
oh yeah, sorry. Part of the original bug was missing error output on the CLI, and I found another place or two to clean up while I was in there. Could make a separate PR if you want.

**Comment by patrickxb** [comment]
Looks good to me.

**Pull request merged**
