### PR TITLE
Fix extra background space on Android

### PR DESCRIPTION
**Pull request by cjb**
@keybase/react-hackers 

This PR reverts @chrisnojima's padding PR for iPhone X in favor of @buoyad's.  Seems to make things better on Android for me -- @MarcoPolo, what do you think about iOS?

### CODE REVIEW

**Comment by mmaxim** [comment]
Does it work on ipHone X?

**Comment by mmaxim** [comment]
I'll try it now.

**Comment by chrisnojima** [comment]
I think both did. This one is more isolated though so it didn't affect android and non x. We need to update react native for the larger fix so

**Comment by cjb** [comment]
Seeing this on iPhone non-X:

JSON value 'unset' of type NSString cannot be converted to a YGValue

**Comment by chrisnojima** [comment]
Just use undefined

**Pull request merged**
