### PR TITLE
Warn in add to team dialog when role 'owner' is selected

### PR DESCRIPTION
**Pull request by buoyad**
(removed screenshots of unused)
Also fixes some styling in this footer area and of course swaps out `owner` for `admin` in the RPC call in this case. r? @keybase/react-hackers

### CODE REVIEW

**Comment by chrisnojima** [comment]
spoke IRL about changing the ux of this a bit

**Comment by buoyad** [comment]
@chrisnojima updated to the new UX. There is one behavior that I find a little sketchy:
1. open add-to-team dialog -> select 'owner'
2. select a bunch of teams including a subteam or one you're an admin of
3. 'owner' sneakily flips to 'admin', you might not notice

I don't think it's _too_ bad because it doesn't result in a role higher than what you expected and the dropdown is right next to the submit button, increasing your chance of noticing. But it's there.

**Comment by buoyad** [comment]
image
image

**Comment by chrisnojima** [comment]
it does't have to flip for you, it can keep it and disable the 'ok' button

**Comment by buoyad** [comment]
How would the user know they have to go into the role picker to fix it?

**Pull request merged**
