### PR TITLE
Add new splash image

### PR DESCRIPTION
**Pull request by cjb**
@keybase/react-hackers 

Uses the same size image for all resolutions (and fits it to fill screen on both Android and iOS) -- it looked like this was the only image file on Zeplin, let me know if I missed a way to get retina images out of Zeplin and if we want to use that instead.

### CODE REVIEW

**Comment by MarcoPolo** [comment]
@cecileboucheron ^

**Comment by cecileboucheron** [comment]
@cjb I think we do need the @2x and @3x versions. In Zeplin when you export the asset in PNG it comes in 3 sizes.

And on Android, we would map them this way:
mdpi + hdpi => use the @1x 
xhdpi => use the @2x (this density needs to be added, seems to be missing)
xxhdpi => use the @3x

**Comment by cjb** [comment]
@cecileboucheron Thanks!  I couldn't see the assets in Zeplin though.

**Comment by cjb** [comment]
@cecileboucheron Done!

**Comment by MarcoPolo** [comment]
👍 Also I'm curious how this looks on the ipad.

**Comment by chrisnojima** [comment]
ipad is definitely a secondary concern for the mvp release

**Comment by cjb** [comment]
FWIW, you can click iPad in the Storyboard view and it seems to do the right thing:

screen shot 2017-04-20 at 2 34 20 pm

**Pull request merged**
