### PR TITLE
Import/Export DecryptionError

### PR DESCRIPTION
**Pull request by patrickxb**
r? @maxtaco

### CODE REVIEW

**Comment by patrickxb** [comment]
cc @strib

**Comment by keybase-ci-visdiff** [comment]
:mag_right: No visual changes found as a result of these commits.

**Comment by maxtaco** [comment]
👍

**Comment by maxtaco** [comment]
pls update `status_codes.iced` too!

**Comment by patrickxb** [comment]
I updated status_codes.iced at the same time.

**Pull request merged**
