### PR TITLE
smaller rows for widget. fixing some colors

### PR DESCRIPTION
**Pull request by chrisnojima**
@keybase/react-hackers updates to the widget to make it tighter space-wise

### CODE REVIEW

**Comment by keybase-ci-visdiff** [comment]
:mag_right: These commits introduced some visual changes:
 * Changed: **Menubar-Truncated** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1465332353495-da4da2eef1ea-cc5946feaa5d/Menubar-Truncated-da4da2eef1ea.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1465332353495-da4da2eef1ea-cc5946feaa5d/Menubar-Truncated-cc5946feaa5d.png)  
   Menubar-Truncated comparison
 * Changed: **Menubar-Normal** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1465332353495-da4da2eef1ea-cc5946feaa5d/Menubar-Normal-da4da2eef1ea.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1465332353495-da4da2eef1ea-cc5946feaa5d/Menubar-Normal-cc5946feaa5d.png)  
   Menubar-Normal comparison
 * Changed: **Folders_TLF-Normal** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1465332353495-da4da2eef1ea-cc5946feaa5d/Folders_TLF-Normal-da4da2eef1ea.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1465332353495-da4da2eef1ea-cc5946feaa5d/Folders_TLF-Normal-cc5946feaa5d.png)  
   Folders_TLF-Normal comparison

**Comment by chrisnojima** [comment]
accidentally affected folders view, fixing that now

**Comment by keybase-ci-visdiff** [comment]
:mag_right: These commits introduced some visual changes:
 * Changed: **Menubar-Truncated** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1465336338291-da4da2eef1ea-4b71796005d0/Menubar-Truncated-da4da2eef1ea.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1465336338291-da4da2eef1ea-4b71796005d0/Menubar-Truncated-4b71796005d0.png)  
   Menubar-Truncated comparison
 * Changed: **Menubar-Normal** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1465336338291-da4da2eef1ea-4b71796005d0/Menubar-Normal-da4da2eef1ea.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1465336338291-da4da2eef1ea-4b71796005d0/Menubar-Normal-4b71796005d0.png)  
   Menubar-Normal comparison
 * Changed: **Folders_TLF-Normal** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1465336338291-da4da2eef1ea-4b71796005d0/Folders_TLF-Normal-da4da2eef1ea.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1465336338291-da4da2eef1ea-4b71796005d0/Folders_TLF-Normal-4b71796005d0.png)  
   Folders_TLF-Normal comparison

**Comment by chrisnojima** [comment]
visbot looks fine

**Comment by MarcoPolo** [comment]
👍

**Comment by keybase-ci-visdiff** [comment]
:mag_right: These commits introduced some visual changes:
 * Changed: **Menubar-Truncated** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1465337742932-da4da2eef1ea-4b71796005d0/Menubar-Truncated-da4da2eef1ea.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1465337742932-da4da2eef1ea-4b71796005d0/Menubar-Truncated-4b71796005d0.png)  
   Menubar-Truncated comparison
 * Changed: **Menubar-Normal** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1465337742932-da4da2eef1ea-4b71796005d0/Menubar-Normal-da4da2eef1ea.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1465337742932-da4da2eef1ea-4b71796005d0/Menubar-Normal-4b71796005d0.png)  
   Menubar-Normal comparison
 * Changed: **Folders_TLF-Normal** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1465337742932-da4da2eef1ea-4b71796005d0/Folders_TLF-Normal-da4da2eef1ea.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1465337742932-da4da2eef1ea-4b71796005d0/Folders_TLF-Normal-4b71796005d0.png)  
   Folders_TLF-Normal comparison

**Comment by keybase-ci-visdiff** [comment]
:mag_right: These commits introduced some visual changes:
 * Changed: **Menubar-Truncated** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1465337748717-da4da2eef1ea-4b71796005d0/Menubar-Truncated-da4da2eef1ea.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1465337748717-da4da2eef1ea-4b71796005d0/Menubar-Truncated-4b71796005d0.png)  
   Menubar-Truncated comparison
 * Changed: **Menubar-Normal** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1465337748717-da4da2eef1ea-4b71796005d0/Menubar-Normal-da4da2eef1ea.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1465337748717-da4da2eef1ea-4b71796005d0/Menubar-Normal-4b71796005d0.png)  
   Menubar-Normal comparison
 * Changed: **Folders_TLF-Normal** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1465337748717-da4da2eef1ea-4b71796005d0/Folders_TLF-Normal-da4da2eef1ea.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1465337748717-da4da2eef1ea-4b71796005d0/Folders_TLF-Normal-4b71796005d0.png)  
   Folders_TLF-Normal comparison

**Comment by keybase-ci-visdiff** [comment]
:mag_right: These commits introduced some visual changes:
 * Changed: **Menubar-Truncated** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1465338747470-da4da2eef1ea-4b71796005d0/Menubar-Truncated-da4da2eef1ea.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1465338747470-da4da2eef1ea-4b71796005d0/Menubar-Truncated-4b71796005d0.png)  
   Menubar-Truncated comparison
 * Changed: **Menubar-Normal** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1465338747470-da4da2eef1ea-4b71796005d0/Menubar-Normal-da4da2eef1ea.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1465338747470-da4da2eef1ea-4b71796005d0/Menubar-Normal-4b71796005d0.png)  
   Menubar-Normal comparison
 * Changed: **Folders_TLF-Normal** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1465338747470-da4da2eef1ea-4b71796005d0/Folders_TLF-Normal-da4da2eef1ea.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1465338747470-da4da2eef1ea-4b71796005d0/Folders_TLF-Normal-4b71796005d0.png)  
   Folders_TLF-Normal comparison

**Comment by cjb** [comment]
retest this please

**Comment by cjb** [comment]
@chrisnojima :ship:

**Pull request merged**
