### PR TITLE
WIP: provisioning

### PR DESCRIPTION
**Pull request by chrisnojima**

### CODE REVIEW

**Comment by chrisnojima** [comment]
- [ ] waiting on some design discussion

**Comment by chrisnojima** [comment]
@cecileboucheron updated with your feedback, didn't update to new zeplin yet

**Comment by chrisnojima** [comment]
@cecileboucheron updated with zeplin stuff. this is just desktop so i didn't do the qr code scan overlay stuff yet. i'm going to start integrating this

**Comment by cecileboucheron** [comment]
* Submit button text should be green2 (not green) and BodyBigSemibold, not BodySemibold
* Icons for "Scan QR/Type text instead" should not be carrets - they're in the icon font
* In "phone adding <desktop>", instruction should say "computer", not "phone".
* add "." after "Ready to provision with (device name)"
* instruction: carrets aren't aligned with text

**Comment by chrisnojima** [comment]
Yeah I'm waiting till the end to do the icons

**Comment by chrisnojima** [comment]
@cecileboucheron updated w/ your fixes minus the font, i'll do that the very last step

**Comment by chrisnojima** [comment]
done

**Pull request closed without merging**
