### PR TITLE
journeycard open team

### PR DESCRIPTION
**Pull request by mlsteele**
Show different text for open teams

image

image

cc @keybase/react-hackers

### CODE REVIEW

**Comment by mlsteele** [comment]
CI failure looks unrelated.
```
TestInboxChatBlockingAlsoUserBlocks
panic: unexpected error adding user to team [recovered]
```

**Comment by maxtaco** [comment]
This is my issue, can you rebase it?

**Comment by mlsteele** [comment]
Either prettier changed or go failures can mask prettier failure

**Comment by mlsteele** [comment]
CI failure looks unrelated
```
    search_test.go:594: 
        	Error Trace:	search_test.go:594
        	            				search_test.go:616
        	            				search_test.go:981
        	            				server_test.go:294
        	            				search_test.go:442
        	Error:      	indexer reindexed
        	Test:       	TestChatSearchInbox
    test_logger.go:56: TEST FAILED: TestChatSearchInbox
```

**Pull request merged**
