### PR TITLE
Remove TestSubteamChats, add better test

### PR DESCRIPTION
**Pull request by zapu**
1. Remove TestSubteamChats in current form, do not try to create subteam and try to chat in it because it's very flaky. Systests is not a good place for chat testing.
2. New test tests both outcomes of `JoinSubteam` argument.
3. Fix a bug that I introduced where `CreatorAdded` return value was not being set properly.

### CODE REVIEW

**Comment by patrickxb** [comment]
I'm find with this, but I'm curious does TestSubteamCreate test anything we don't already test?  in teams/create_test.go there is TestCreateSubteam and friends.

**Comment by zapu** [comment]
Hmm right, adding few more assertions to `TestCreateSubteam` would cover what this is testing. However maybe `cli.TeamCreate` API test is worth it, for example nothing caught my breakage of `result.CreatorAdded`.

**Comment by patrickxb** [comment]
Ok, sounds good.

**Comment by zapu** [comment]
Thanks! I'll spend some more time trying "slow gregor" though.

**Pull request merged**
