### PR TITLE
replace all autogenerated text messages with new system messages CORE-6519

### PR DESCRIPTION
**Pull request by mmaxim**
Patch does the following:

1.) Create a new message type, `SYSTEM`, which will stand in for any message that is generated automatically by a user's client.
2.) There is no one system message, instead a system message is a variant type with the various types of system messages the client can send as types that variant can be. Right now we start out with the current 3 messages.
3.) Each system message contains no text, just the metadata for creating the messaging in the UI.
4.) @ and channel mention are calculated per type, and attached for the message.
5.) The JS code now has the logic for turning system messages into regular text messages, so that I can commit this to master and not break anything. When the frontend team works on this, that code will be replaced with the actual code to render the system messages. cc @cjb @chrisnojima.
6.) In the meantime, I have also shortened the messages for people being added to teams. I think our current one is too long, and every team I am on chooses to not show it. Now we just show a single line for added to team, and invite fulfilled on team. @malgorithms

### CODE REVIEW

**Comment by malgorithms** [comment]
cool!

**Comment by mmaxim** [comment]
Also I need to deploy Gregor before landing this, since that msg checking code happens on the server too (I already landed the patch).

**Comment by cjb** [comment]
Looks good! But we were already rendering join/leave messages in system boxes.. will those go back to fake-text messages after this PR? If so, perhaps we should add the frontend work to this PR before it's merged? No strong opinions, just wanted to think about it.

**Comment by mmaxim** [comment]
JOIN and LEAVE are unaffected by this change, just check out thread-content.js, thats all that changes on the JS side.

**Pull request merged**
