### PR TITLE
Reason is an IdentifyReason

### PR DESCRIPTION
**Pull request by mlsteele**
We already have a type for `IdentifyReason`, so use it instead of string.

### CODE REVIEW

**Comment by keybase-ci-visdiff** [comment]
The commits 414ccb626ab9...f7075dbf8e51 introduce visual changes on linux. <details><summary>:mag_right: 1 changed</summary>

 * Changed: **Markdown-emoji** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1504295921152-414ccb626ab9-f7075dbf8e51-linux/Markdown-emoji-414ccb626ab9.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1504295921152-414ccb626ab9-f7075dbf8e51-linux/Markdown-emoji-f7075dbf8e51.png)  
   Markdown-emoji comparison
</summary>

**Comment by mlsteele** [comment]
yeah @keybase-ci-visdiff I deleted those icons as part of this PR, thanks for the help.

**Comment by keybase-ci-visdiff** [comment]
The commits 414ccb626ab9...f7075dbf8e51 introduce visual changes on linux. <details><summary>:mag_right: 1 changed</summary>

 * Changed: **Markdown-emoji** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1504298033696-414ccb626ab9-f7075dbf8e51-linux/Markdown-emoji-414ccb626ab9.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1504298033696-414ccb626ab9-f7075dbf8e51-linux/Markdown-emoji-f7075dbf8e51.png)  
   Markdown-emoji comparison
</summary>

**Comment by keybase-ci-visdiff** [comment]
The commits 414ccb626ab9...f7075dbf8e51 introduce visual changes on linux. <details><summary>:mag_right: 1 changed</summary>

 * Changed: **Markdown-emoji** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1504300916449-414ccb626ab9-f7075dbf8e51-linux/Markdown-emoji-414ccb626ab9.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1504300916449-414ccb626ab9-f7075dbf8e51-linux/Markdown-emoji-f7075dbf8e51.png)  
   Markdown-emoji comparison
</summary>

**Comment by keybase-ci-visdiff** [comment]
The commits 414ccb626ab9...f7075dbf8e51 introduce visual changes on linux. <details><summary>:mag_right: 1 changed</summary>

 * Changed: **Markdown-emoji** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1504317844145-414ccb626ab9-f7075dbf8e51-linux/Markdown-emoji-414ccb626ab9.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1504317844145-414ccb626ab9-f7075dbf8e51-linux/Markdown-emoji-f7075dbf8e51.png)  
   Markdown-emoji comparison
</summary>

**Comment by keybase-ci-visdiff** [comment]
The commits 414ccb626ab9...f7075dbf8e51 introduce visual changes on linux. <details><summary>:mag_right: 3 changed</summary>

 * Changed: **Profile-Your_Profile_Proof_Menu** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1504464174049-414ccb626ab9-f7075dbf8e51-linux/Profile-Your_Profile_Proof_Menu-414ccb626ab9.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1504464174049-414ccb626ab9-f7075dbf8e51-linux/Profile-Your_Profile_Proof_Menu-f7075dbf8e51.png)  
   Profile-Your_Profile_Proof_Menu comparison
 * Changed: **Profile-Your_Profile_Pending_Proof_Menu** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1504464174049-414ccb626ab9-f7075dbf8e51-linux/Profile-Your_Profile_Pending_Proof_Menu-414ccb626ab9.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1504464174049-414ccb626ab9-f7075dbf8e51-linux/Profile-Your_Profile_Pending_Proof_Menu-f7075dbf8e51.png)  
   Profile-Your_Profile_Pending_Proof_Menu comparison
 * Changed: **Markdown-emoji** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1504464174049-414ccb626ab9-f7075dbf8e51-linux/Markdown-emoji-414ccb626ab9.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1504464174049-414ccb626ab9-f7075dbf8e51-linux/Markdown-emoji-f7075dbf8e51.png)  
   Markdown-emoji comparison
</summary>

**Pull request merged**
