### PR TITLE
Fix margins on QR code

### PR DESCRIPTION
**Pull request by gabriel**
Was causing scrollbar. Unneeded.

### CODE REVIEW

**Comment by gabriel** [comment]
@keybase/react-hackers

**Comment by keybase-ci-visdiff** [comment]
The commits 5753ede39e6e...81327f053a4a introduce visual changes on linux. <details><summary>:mag_right: 2 changed</summary>

 * Changed: **Code_Page-Show_Code_Mobile** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490996972835-5753ede39e6e-81327f053a4a-linux/Code_Page-Show_Code_Mobile-5753ede39e6e.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490996972835-5753ede39e6e-81327f053a4a-linux/Code_Page-Show_Code_Mobile-81327f053a4a.png)  
   Code_Page-Show_Code_Mobile comparison
 * Changed: **Code_Page-Show_Code** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490996972835-5753ede39e6e-81327f053a4a-linux/Code_Page-Show_Code-5753ede39e6e.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490996972835-5753ede39e6e-81327f053a4a-linux/Code_Page-Show_Code-81327f053a4a.png)  
   Code_Page-Show_Code comparison
</summary>

**Comment by gabriel** [comment]
Visdiff changes are the horizontal scrollbar going away.

**Comment by keybase-ci-visdiff** [comment]
The commits cdf37d5b0932...147ab4fd3602 introduce visual changes on linux. <details><summary>:mag_right: 2 changed</summary>

 * Changed: **Code_Page-Show_Code_Mobile** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1491242487730-cdf37d5b0932-147ab4fd3602-linux/Code_Page-Show_Code_Mobile-cdf37d5b0932.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1491242487730-cdf37d5b0932-147ab4fd3602-linux/Code_Page-Show_Code_Mobile-147ab4fd3602.png)  
   Code_Page-Show_Code_Mobile comparison
 * Changed: **Code_Page-Show_Code** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1491242487730-cdf37d5b0932-147ab4fd3602-linux/Code_Page-Show_Code-cdf37d5b0932.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1491242487730-cdf37d5b0932-147ab4fd3602-linux/Code_Page-Show_Code-147ab4fd3602.png)  
   Code_Page-Show_Code comparison
</summary>

**Pull request merged**
