### PR TITLE
Allow paperkey generation in oneshot mode

### PR DESCRIPTION
**Pull request by joshblum**
needed to prompt the user for their passphrase to perform lksec operations

### CODE REVIEW

**Comment by patrickxb** [comment]
It would be nice to not change the tests (or change as little as possible) when changing something like this so we could see that the tests that have been running for ages still pass, instead of also wondering if the new tests are the same as the old tests.  In a separate PR you could change the tests...

**Comment by patrickxb** [comment]
Can this ever run with a GUI?  

Because we can't just prompt for a passphrase whenever we want with the GUI.

**Comment by joshblum** [comment]
no problem, i'll split the test refactor to a separate pr. i tested with the gui/cli and both work with the password prompt

**Comment by patrickxb** [comment]
What about mobile?  

I guess there's no way to do one-shot in mobile...mobile definitely doesn't register a secret ui, though...

**Comment by joshblum** [comment]
the only way to get into oneshot is through the cli.. should i add some special casing for mobile?

**Comment by patrickxb** [comment]
I think so just to be safe.

**Comment by joshblum** [comment]
fixed

**Pull request merged**
