### PR TITLE
Use action parameter for wallet send from field

### PR DESCRIPTION
**Pull request by zanderz**

### CODE REVIEW

**Comment by zanderz** [comment]
createSetBuildingFrom has a from field, and it gets routed to here. I watched the from field come in in the debugger.

**Comment by buoyad** [comment]
@zanderz oh right, I had a brain fart. The reducers put all those fields in the store, so I think this should use `state.wallets.buildingPayment.from` if it's not empty and pass in `fromPrimaryAccount: true` if it is empty

**Comment by zanderz** [comment]
I have a couple of questions - doesn't the buildPayment RPC get called once for each of the 6 actions? is that intended? Also, can we be sure the reducer happens to put `from` in the state before the buildPayment promise is invoked with `from` ?

**Comment by buoyad** [comment]
Yeah, the reducers run first so `from` will be there. This gets called when the user updates any field on the send form.

**Comment by zanderz** [comment]
so, is this ok now?

**Comment by buoyad** [comment]
merging this for use in the remove load call PR

**Pull request merged**
