### PR TITLE
Fix tab switch in menubar

### PR DESCRIPTION
**Pull request by gabriel**
There was a of name collision for switchTab!

It was being set to `dispatch(switchTo(...)` but because `bindActionCreators` was declared later, it was overwritten by the `switchTab` declared in `actions/favorite.js`.

I renamed switchTab to favoriteSwitchTab and moved the `...bindActionCreators` to the first element.

### CODE REVIEW

**Comment by keybase-ci-visdiff** [comment]
The commits 317b9930e698...ccc71d3dfa48 introduce visual changes on linux. <details><summary>:mag_right: 1 changed</summary>

 * Changed: **Chat_Input-Emoji_Open** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1481323106731-317b9930e698-ccc71d3dfa48-linux/Chat_Input-Emoji_Open-317b9930e698.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1481323106731-317b9930e698-ccc71d3dfa48-linux/Chat_Input-Emoji_Open-ccc71d3dfa48.png)  
   Chat_Input-Emoji_Open comparison
</summary>

**Comment by gabriel** [comment]
@keybase/react-hackers

**Comment by keybase-ci-visdiff** [comment]
The commits 317b9930e698...721f0ee8fa4c introduce visual changes on linux. <details><summary>:mag_right: 1 changed</summary>

 * Changed: **Chat_Input-Emoji_Open** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1481323496751-317b9930e698-721f0ee8fa4c-linux/Chat_Input-Emoji_Open-317b9930e698.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1481323496751-317b9930e698-721f0ee8fa4c-linux/Chat_Input-Emoji_Open-721f0ee8fa4c.png)  
   Chat_Input-Emoji_Open comparison
</summary>

**Comment by gabriel** [comment]
bump

**Pull request merged**
