### PR TITLE
Signup part 4: storyshot

### PR DESCRIPTION
**Pull request by chrisnojima**
@keybase/react-hackers just the storyshot

This is part of a 4 part pr. It won't work until the 4th part: 
1. https://github.com/keybase/client/pull/12524
1. https://github.com/keybase/client/pull/12525
1. https://github.com/keybase/client/pull/12526
1. https://github.com/keybase/client/pull/12527

### CODE REVIEW

**Comment by cecileboucheron** [comment]
@chrisnojima 
Don't know if everything below is related to your changes but: 
* I would top-align content in pages so nothing moves when the keyboard pops up, kinda like in the login screens 
* Back button not working for me in sign up process
* inputs are too short (as discussed in pm) - let's do width 100%, max 460px
* space between label and input is too big, while space below avatar is too small:
image
* can we use the full-width version of our primary button for all Continue buttons in signup/login?
* It says "A public name for this device" - let's say "Set a public name..."
* Error screen looks clunky: paddings missing (outer and in between elements), header text is not centered, error message should show uppercase "E" and a period. 
image
* not related probably but labels should be semibold

**Comment by chrisnojima** [comment]
@cecileboucheron some fixes here: https://github.com/keybase/client/pull/12551

**Comment by zanderz** [comment]
I'm giving this a try. Logged in and provisioned with an old account, with no active devices for a few months, then got this dialog:
image
and when I click "paper key instead". I can't type anything into the resulting dialog:
image

**Comment by zanderz** [comment]
When provisioning one desktop machine running this branch from another machine, when it said to enter the text phrase from the other computer, clicking the button gave no feedback or spinner for several seconds before it took and was provisioned.

**Comment by chrisnojima** [comment]
This pr only addresses the signup screens. Not provisioning

**Comment by chrisnojima** [comment]
@keybase/react-hackers bump

**Comment by zanderz** [comment]
oh, whoops. Created an account ok, with the default "My Windows Device".

**Pull request merged**
