### PR TITLE
Ui pgp storage message

### PR DESCRIPTION
**Pull request by MarcoPolo**
@keybase/react-hackers 

Adds the UI's ability to show a popup giving the pgp purge message, and handles sending an ack back to the service.

Ack is sent back only when the user hits ok.

The choice was made here to use a separate store, so in the future when we remove this it won't be too hard to take out.

The name is confusingly pgp, if there is a better option I'm happy to change it.

## Preview

screen shot 2016-08-26 at 4 01 05 pm

### CODE REVIEW

**Comment by chrisnojima** [comment]
:+1: but to clarify its if they hit ok or close or some hot key to close. If the user dismisses in any way it submits

**Comment by MarcoPolo** [comment]
okay I'll make that change

**Comment by chrisnojima** [comment]
Doesn't it already work like that? You have both callbacks call the same
function

**Comment by MarcoPolo** [comment]
no, there's a payload with the option that says `{hitOk: boolean}`. If the user hits ok, it's set to true, otherwise false. It only sends the dismiss rpc if hitOk was true

**Comment by patrickxb** [comment]
Lgtm

**Pull request merged**
