### PR TITLE
stop BroadcastMessage repeat CORE-3137

### PR DESCRIPTION
**Pull request by mmaxim**
@maxtaco @oconnor663 

This patch includes a bunch of changes to Gregor in the `vendor` directory as well. The point here is to use `State` to check for `BroadcastMessage` on a message already in the client's local state. We also get rid of the `itemsByID` map in `gregorHandler` and instead use the `State` instead. Note the use of `FastLookupState`, which should make it all go quickly.

### CODE REVIEW

**Comment by cjb** [comment]
@mmaxim looks like this PR makes protocol changes without regenerating the protocol files (caught by JS tests)

**Comment by mmaxim** [comment]
@cjb I didn't make any protocol changes, but I vendored in Gregor which may have changed it's own protocol since the last time we updated it. Would that affect the tests?

**Comment by cjb** [comment]
@mmaxim Think so (but not sure) -- `cd protocol && make && git diff` should show you if there are changes that need to be committed.

**Comment by maxtaco** [comment]
👍

**Pull request merged**
