### PR TITLE
broke the fresh install case!

### PR DESCRIPTION
**Pull request by zanderz**
This is pretty serious - I broke the fresh install case with https://github.com/keybase/client/pull/10578, so I'd like to get this out very soon. The GUI can't start at all if app-state.json is not already present!

### CODE REVIEW

**Comment by mmaxim** [comment]
We should get some kind of fixed merged tonight and release tomorrow.

**Comment by zanderz** [comment]
ok. with isNaN()?

**Comment by chrisnojima** [comment]
Is that what happens? Isn't it undefined?

**Comment by akalin-keybase** [comment]
perhaps with `Number.isFinite()`, `Number.isInteger()`, or `Number.isSafeInteger()` plus `x >= 0` or something. See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isInteger

**Comment by chrisnojima** [comment]
It's not clear to me what's actually going wrong. I assume it's us having an empty object and setting undefined which causes bad behavior. Dunno why itd be nan. Typeof x === 'number' likely works

**Comment by zanderz** [comment]
I'm just asking how to do that check - `"x" in appState.state` ?

**Comment by chrisnojima** [comment]
You can use typeof cause it won't be number if it doesn't exist. Or you can use hasOwnProperty('x') but that can still fail if it's set to undefined

**Comment by chrisnojima** [comment]
The falsey check isnt good cause you drag your window to the left of the screen and not this code doesn't run

**Comment by mmaxim** [comment]
I'm surprised ES6 doesn't have http://coffeescript.org/#existential-operator

**Comment by chrisnojima** [comment]
Just existence isn't good enough. If it's a string it's invalid for exmple

**Comment by zanderz** [comment]
btw it did this:
```
Uncaught exception on main thread: TypeError: Error processing argument at index 0, conversion failure from #<Object>
    at t.default (C:\Users\morth\AppData\Local\Keybase\Gui\resources\app\desktop\dist\main.bundle.js:1:327752)
    at App.p.app.once (C:\Users\morth\AppData\Local\Keybase\Gui\resources\app\desktop\dist\main.bundle.js:1:326065)
    at Object.onceWrapper (events.js:293:19)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:194:7)
```
https://github.com/keybase/client/issues/10635

**Comment by mmaxim** [comment]
If we are actually worried about the `string` case, seems like you should check all the fields (since that seems to assume anything can get in here)

**Comment by chrisnojima** [comment]
I agree

**Pull request merged**
