### PR TITLE
Fix secure anim static png

### PR DESCRIPTION
**Pull request by gabriel**
Also fixing the static images so they are the last frame.

### CODE REVIEW

**Comment by gabriel** [comment]
@keybase/react-hackers

**Comment by chrisnojima** [comment]
we might want to ticket just generating this info instead of this hardcoded list of static assets

**Comment by keybase-ci-visdiff** [comment]
The commits fdae73e8e2c7...688201a119d6 introduce visual changes on linux. <details><summary>:mag_right: 2 changed</summary>

 * Changed: **Chat_List-Normal** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1485213251040-fdae73e8e2c7-688201a119d6-linux/Chat_List-Normal-fdae73e8e2c7.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1485213251040-fdae73e8e2c7-688201a119d6-linux/Chat_List-Normal-688201a119d6.png)  
   Chat_List-Normal comparison
 * Changed: **Chat_List-Empty** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1485213251040-fdae73e8e2c7-688201a119d6-linux/Chat_List-Empty-fdae73e8e2c7.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1485213251040-fdae73e8e2c7-688201a119d6-linux/Chat_List-Empty-688201a119d6.png)  
   Chat_List-Empty comparison
</summary>

**Comment by gabriel** [comment]
Yeah we need a convention for animated gifs like '-animated.gif' that will always have '-static.png' versions for those files.

**Comment by chrisnojima** [comment]
But static is that. If there's a static there's a non static version by
convention already

**Comment by keybase-ci-visdiff** [comment]
The commits fdae73e8e2c7...688201a119d6 introduce visual changes on linux. <details><summary>:mag_right: 2 changed</summary>

 * Changed: **Chat_List-Normal** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1485221881490-fdae73e8e2c7-688201a119d6-linux/Chat_List-Normal-fdae73e8e2c7.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1485221881490-fdae73e8e2c7-688201a119d6-linux/Chat_List-Normal-688201a119d6.png)  
   Chat_List-Normal comparison
 * Changed: **Chat_List-Empty** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1485221881490-fdae73e8e2c7-688201a119d6-linux/Chat_List-Empty-fdae73e8e2c7.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1485221881490-fdae73e8e2c7-688201a119d6-linux/Chat_List-Empty-688201a119d6.png)  
   Chat_List-Empty comparison
</summary>

**Pull request merged**
