### PR TITLE
Fix new flow errors

### PR DESCRIPTION
**Pull request by MarcoPolo**
@keybase/react-hackers 

This updates our flow version and fixes new errors.

There is a weird bug with implied true values in jsx filed here: https://github.com/facebook/flow/issues/1906

### CODE REVIEW

**Comment by chrisnojima** [comment]
👍

**Comment by cjb** [comment]
retest this please

**Comment by cjb** [comment]
(That was directed at Jenkins!)

**Comment by cjb** [comment]
retest this please

**Comment by cjb** [comment]
:ship:

**Pull request merged**
