### PR TITLE
QR code scanned should be transient

### PR DESCRIPTION
**Pull request by gabriel**
The qrCodeScanned should be part of component state instead of the store (since we don't reset provisioning state on cancel).

Also added a "Please wait..." once the QR code has scanned since it might take a few seconds for it to proceed.

### CODE REVIEW

**Comment by gabriel** [comment]
@keybase/react-hackers

**Comment by chrisnojima** [comment]
why don't we reset it in the store? doesn't it seem like it should be

**Comment by keybase-ci-visdiff** [comment]
The commits bb4eba441b79...1bbdc14275c2 introduce visual changes on linux. <details><summary>:mag_right: 1 removed</summary>

 * Removed: **Code_Page-Scanned_Code_Mobile** [(view original)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1497294628232-bb4eba441b79-1bbdc14275c2-linux/Code_Page-Scanned_Code_Mobile-bb4eba441b79.png)
</summary>

**Comment by gabriel** [comment]
In this case, I think its safer to make it transient (part of component state). Even if we did end up resetting it in the store, I think it's a good idea to do it this way?

**Comment by chrisnojima** [comment]
but if its transient we have a harder time controlling its state. also there's likely other stuff that should be reset also that needs to be

**Comment by gabriel** [comment]
Yeah, that seems like a better fix.. moving here:
https://github.com/keybase/client/pull/7380

**Comment by gabriel** [comment]
There are other scenarios where the QR code scanning needs to be reset (like when provisioning a computer from the mobile device).. https://keybase.atlassian.net/browse/DESKTOP-4043

I think this is a better fix since we don't have actions for all these scenarios.

Also I think qr code scanning being reset on component mount is appropriate since when this component is mounted it needs to be able to scan.

**Comment by keybase-ci-visdiff** [comment]
The commits bb4eba441b79...1bbdc14275c2 introduce visual changes on linux. <details><summary>:mag_right: 1 removed</summary>

 * Removed: **Code_Page-Scanned_Code_Mobile** [(view original)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1497392289038-bb4eba441b79-1bbdc14275c2-linux/Code_Page-Scanned_Code_Mobile-bb4eba441b79.png)
</summary>

**Comment by chrisnojima** [comment]
We should add those events. We want this stuff backed by redux

**Comment by gabriel** [comment]
Here is an alternative, where we reset this on componentDidMount: https://github.com/keybase/client/pull/7401

**Pull request closed without merging**
