### PR TITLE
Add tests to CI for Windows

### PR DESCRIPTION
**Pull request by zanderz**
This runs the tests against https://ci1.keybase.io though there is currently a new test failure, TestProvisionPaper:
https://ci.appveyor.com/project/keybase/client/build/1.0.889
@maxtaco @patrickxb

### CODE REVIEW

**Comment by maxtaco** [comment]
Excellent!  That test failure (I haven't looked since I don't have perms)
is likely due to an API server that doesn't have the key/owner endpoint and
just needs an update.  But great news!

**Comment by cjb** [comment]
Pulled API server and restarted it, give it another go?

**Comment by zanderz** [comment]
Still no:
https://ci.appveyor.com/project/keybase/client/build/1.0.894

**Comment by maxtaco** [comment]
well i'm fumbling in the dark.. how do i get permissions to see it?

**Comment by zanderz** [comment]
Login with github creds

**Comment by maxtaco** [comment]
The issue is as I guessed, but looks like it wasn't fixed:

```
	test_logger.go:51: api.go:129 + API GET request to https://ci1.keybase.io/_/api/1.0/key/owner.json?kid=012053b1bdc14bc246cbefb401060c4ee9d5e62cdf552adc1f6ca0c6cf41d28eab760a
	test_logger.go:51: api.go:118 | Cli wasn't found; remaking for cookied=false
	test_logger.go:51: api.go:199 | Result is: 404 Not Found
	test_logger.go:51: login_provision.go:767 an error occurred during
```

**Comment by maxtaco** [comment]
(And you do get a 404 for that link...)

**Comment by cjb** [comment]
My fault, sorry.  Try again now!

**Pull request merged**
