### PR TITLE
Resolve3 for Implicit Teams

### PR DESCRIPTION
**Pull request by modalduality**
Not really sure if this is on the right track.

### CODE REVIEW

**Comment by modalduality** [comment]
@maxtaco I think ready for review, waiting for mike's ticket to add tests

**Comment by maxtaco** [comment]
can you rename the PR?

**Comment by maxtaco** [comment]
looking good, need to handle the `iteam:bob,foo (conflicted copy #10)` case too

**Comment by maxtaco** [comment]
Not going to use this.

**Pull request closed without merging**
