### PR TITLE
speed up list-followers

### PR DESCRIPTION
**Pull request by maxtaco**
- use new endpoint
- strip out some features that we weren't using
- will need to make a second pass to retire a bunch of code.
- add a simple test

### CODE REVIEW

**Comment by patrickxb** [comment]
no more json output?  I don't care, just checking.

**Comment by maxtaco** [comment]
I decided to strip it out, yeah....

**Comment by patrickxb** [comment]
ok, then we should probably remove it on the other side too (list-tracking) for symmetry.

**Comment by patrickxb** [comment]
LGTM

**Comment by maxtaco** [comment]
To play devil's advocate, it kind of makes sense to show the PGP key and the identities on `list-tracking` because it's signed into your tracking statement.  And then the data is more complex, so you might actually want a JSON view of it.  In this case, we're returning a lot less, and it's all based on server trust.  So I could maybe go either way....

**Pull request merged**
