### PR TITLE
dont want systemd if started with custom home

### PR DESCRIPTION
**Pull request by heronhaye**

### CODE REVIEW

**Comment by maxtaco** [comment]
what do you think about specified via environment variable?

**Comment by heronhaye** [comment]
Doesn't seem to work for me.

```
% HOME=/home/md/hello keybase status
Username:      modalduality
```

**Comment by maxtaco** [comment]
I don't understand what you mean by "it doesn't work" --- does the repro not work, or the fix doesn't work?

**Comment by maxtaco** [comment]
Right, my point is that this fails:

```
HOME=/tmp/foo XDG_RUNTIME_DIR= keybase status
```

for the same reason that this fails:

```
keybase --home=/tmp/foo status
```

And therefore, we should disable systemd when we see `HOME` for the same reason we disable it when we see `--home`

**Comment by maxtaco** [comment]
@heronhaye I pushed another attempt ^?

**Comment by zapu** [comment]
Isn't `$HOME` always set? so it's difficult to tell a non-standard home. Can probably ask the system if `$HOME` is real home dir for current user (the one that's also in `/etc/passwd`)

**Comment by maxtaco** [comment]
Oh, @zapu, good point...

**Comment by heronhaye** [comment]
(not sure what we're doing here, will leave this PR open for now)

**Comment by heronhaye** [comment]
closing for now

**Pull request closed without merging**
