### PR TITLE
show ash on no ephermeral keys

### PR DESCRIPTION
**Pull request by chrisnojima**
@keybase/react-hackers

### CODE REVIEW

**Comment by chrisnojima** [comment]
then we need some flag

**Comment by joshblum** [comment]
i think the check should just be `isErrMsg && isExploding` if we don't want ash to show it's filtered on the core side already

**Comment by chrisnojima** [comment]
@joshblum ok so we have a flag for `explodingUnreadable` but it was only on for the pairwise error code. now its true if there's any err and its exploding. We force that string but we could plumb through other stuff. we can do that later

**Comment by chrisnojima** [comment]
sure, iw as just fixing a bug but if you want that to work i can change it further

**Comment by joshblum** [comment]
yeah these PRs are from the same ticket we should just fix fully or it will bust accidentally again..

**Comment by chrisnojima** [comment]
it won't bust, it'll just not show your custom message

**Comment by joshblum** [comment]
should show custom msgs

**Comment by chrisnojima** [comment]
done

**Comment by joshblum** [comment]
thx!

**Comment by chrisnojima** [comment]
@keybase/react-hackers bump, tiny change

**Pull request merged**
