### PR TITLE
Change notification sends

### PR DESCRIPTION
**Pull request by patrickxb**
All existing notifications will continue to be sent.  A follow-up
change should remove them.  Comments in place instructing what to
do.

1. TrackingChanged sent on track
2. KeyfamilyChanged sent when key family changes

r? @maxtaco 

cc @chrisnojima @strib

### CODE REVIEW

**Comment by maxtaco** [comment]
👍

**Comment by chrisnojima** [comment]
desktop side: https://github.com/keybase/client/pull/3176

**Comment by patrickxb** [comment]
@keybase/react-hackers flow errors here.   thanks.

**Comment by chrisnojima** [comment]
fixing

**Comment by chrisnojima** [comment]
fixed

**Comment by keybase-ci-visdiff** [comment]
:mag_right: The commits 40191f81f485...38adfa269cb0 introduced some visual changes on win32:
 * Changed: **Folders_Clear_History_Confirmation-Normal_Public** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1466780823434-40191f81f485-38adfa269cb0-win32/Folders_Clear_History_Confirmation-Normal_Public-40191f81f485.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1466780823434-40191f81f485-38adfa269cb0-win32/Folders_Clear_History_Confirmation-Normal_Public-38adfa269cb0.png)  
   Folders_Clear_History_Confirmation-Normal_Public comparison
 * Changed: **Folders_Clear_History_Confirmation-Normal_Private** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1466780823434-40191f81f485-38adfa269cb0-win32/Folders_Clear_History_Confirmation-Normal_Private-40191f81f485.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1466780823434-40191f81f485-38adfa269cb0-win32/Folders_Clear_History_Confirmation-Normal_Private-38adfa269cb0.png)  
   Folders_Clear_History_Confirmation-Normal_Private comparison
 * Changed: **Folders_Clear_History_Confirmation-Long_Name_Public** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1466780823434-40191f81f485-38adfa269cb0-win32/Folders_Clear_History_Confirmation-Long_Name_Public-40191f81f485.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1466780823434-40191f81f485-38adfa269cb0-win32/Folders_Clear_History_Confirmation-Long_Name_Public-38adfa269cb0.png)  
   Folders_Clear_History_Confirmation-Long_Name_Public comparison

**Comment by keybase-ci-visdiff** [comment]
:mag_right: The commits 40191f81f485...38adfa269cb0 introduced some visual changes on win32:
 * Changed: **Folders_Clear_History_Confirmation-Normal_Public** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1466785245867-40191f81f485-38adfa269cb0-win32/Folders_Clear_History_Confirmation-Normal_Public-40191f81f485.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1466785245867-40191f81f485-38adfa269cb0-win32/Folders_Clear_History_Confirmation-Normal_Public-38adfa269cb0.png)  
   Folders_Clear_History_Confirmation-Normal_Public comparison
 * Changed: **Folders_Clear_History_Confirmation-Normal_Private** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1466785245867-40191f81f485-38adfa269cb0-win32/Folders_Clear_History_Confirmation-Normal_Private-40191f81f485.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1466785245867-40191f81f485-38adfa269cb0-win32/Folders_Clear_History_Confirmation-Normal_Private-38adfa269cb0.png)  
   Folders_Clear_History_Confirmation-Normal_Private comparison
 * Changed: **Folders_Clear_History_Confirmation-Long_Name_Public** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1466785245867-40191f81f485-38adfa269cb0-win32/Folders_Clear_History_Confirmation-Long_Name_Public-40191f81f485.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1466785245867-40191f81f485-38adfa269cb0-win32/Folders_Clear_History_Confirmation-Long_Name_Public-38adfa269cb0.png)  
   Folders_Clear_History_Confirmation-Long_Name_Public comparison

**Comment by keybase-ci-visdiff** [comment]
:mag_right: The commits 40191f81f485...38adfa269cb0 introduced some visual changes on win32:
 * Changed: **Folders_Clear_History_Confirmation-Normal_Public** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1466789274947-40191f81f485-38adfa269cb0-win32/Folders_Clear_History_Confirmation-Normal_Public-40191f81f485.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1466789274947-40191f81f485-38adfa269cb0-win32/Folders_Clear_History_Confirmation-Normal_Public-38adfa269cb0.png)  
   Folders_Clear_History_Confirmation-Normal_Public comparison
 * Changed: **Folders_Clear_History_Confirmation-Normal_Private** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1466789274947-40191f81f485-38adfa269cb0-win32/Folders_Clear_History_Confirmation-Normal_Private-40191f81f485.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1466789274947-40191f81f485-38adfa269cb0-win32/Folders_Clear_History_Confirmation-Normal_Private-38adfa269cb0.png)  
   Folders_Clear_History_Confirmation-Normal_Private comparison
 * Changed: **Folders_Clear_History_Confirmation-Long_Name_Public** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1466789274947-40191f81f485-38adfa269cb0-win32/Folders_Clear_History_Confirmation-Long_Name_Public-40191f81f485.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1466789274947-40191f81f485-38adfa269cb0-win32/Folders_Clear_History_Confirmation-Long_Name_Public-38adfa269cb0.png)  
   Folders_Clear_History_Confirmation-Long_Name_Public comparison

**Pull request merged**
