### PR TITLE
Scrolling coins background on pending payments

### PR DESCRIPTION
**Pull request by buoyad**
pending-bg

The majority of this diffstat is from storyshots.
 
r? @keybase/react-hackers

### CODE REVIEW

**Comment by buoyad** [comment]
Yep, where aren't you seeing it?

**Comment by zanderz** [comment]
maybe these messages aren't the right kind?
image

**Comment by MarcoPolo** [comment]
O hmm, when I ran this just now, all my messages have this background applied to them!

**Comment by MarcoPolo** [comment]
nvm I was apparently on an old version of this branch lgtm

**Comment by buoyad** [comment]
Ah @zanderz sorry should've clarified, it's on the chat messages not the wallet page

**Pull request merged**
