### PR TITLE
conflict_resolver: prevent cancellation confusion

### PR DESCRIPTION
**Pull request by jakob223**
This fixes an issue where CR can temporarily look finished if the `cancelExistingLocked` call reduces the wait group counter to 0 before the `Add` call can increase it again.

Thanks @strib for helping figure out what was going on here.

Issue: KBFS-3726

### CODE REVIEW

**Comment by jakob223** [comment]
I was not. Do you have any ideas to induce this particular order of happenings? It seems extremely rare based on my trying to replicate it.

**Comment by strib** [comment]
Bummer.  No, I don't have any good ideas.  As long as this fix doesn't seem to induce other flakes though, it's definitely worth trying.

**Comment by jakob223** [comment]
There's another similar CR flake that I'm also looking into, and

**Comment by jakob223** [comment]
The "close and comment" button is in the place where one might expect a "never mind, don't comment" button to be..

**Pull request merged**
