### PR TITLE
use of variants in AVDL for chat

### PR DESCRIPTION
**Pull request by maxtaco**
First use of Variants in AVDL for chat. Check out the compiled code and how it's used.

### CODE REVIEW

**Comment by maxtaco** [comment]
(C/I will fail until I merge changes in keybase/node-avdl-compiler and keybase/node-avdl2json)

**Comment by mlsteele** [comment]
Looks great!
Are you going to merge those deps before this?

Two questions. This avdl:
```avdl
case METADATA:
    MessageConversationMetadata conversationMetadata;
```
generates a constructor `NewMessageBodyWithConversationMetadata`. It seems like that name is derived from the member name `conversationMetadata`. If in the future there were multiple members per case, then that might be a problem like `NewMessageBodyWithConversationMetadataAndEdit`.

What about instead generating the constructor name from the switch type `METADATA` like `NewMessageBodyWithMetadata`? That way, you can add members to the case without changing the constructor name. Also if you have a `case A,B:` it's clear from `NewFooWithA` what to set as `typ`.

Also why `typ` instead of `type`? Conflict with some language keyword?

**Comment by maxtaco** [comment]
> Are you going to merge those deps before this?

Yes, I was waiting on that until we know what we want the behavior of the compiler to be.

> If in the future there were multiple members per case, then that might be a problem like NewMessageBodyWithConversationMetadataAndEdit.

I don't think we should allow this feature. Worse comes to worse you can do the verbose thing:

```
variant Foo switch(int a) {
   case 1:
      v1Type v1;
   case 2:
      v1Type v2;
}
```

It's not ideal, but it's expressible.  Hmf.  It's a significant rewrite otherwise.

> What about instead generating the constructor name from the switch type METADATA like NewMessageBodyWithMetadata? That way, you can add members to the case without changing the constructor name. Also if you have a case A,B: it's clear from NewFooWithA what to set as typ.

I agree that it's good to avoid future code changes, but it wouldn't be too much of a rewrite to go through and fix what breaks in this case.  What we really want to avoid is non-backward-compatible on-the-wire changes.

> Also why typ instead of type? Conflict with some language keyword?

Yeah.  `type` is a reserved Keyword in Go I believe?

**Comment by mlsteele** [comment]
Ok, sounds good! 👍

**Comment by maxtaco** [comment]
@mlsteele in your proposal, we never use the identifiers in the case bodies at all.  So if we went with it, we should change the AVDL to:

```
variant foo switch (SomeEnumType t) {
   case BAR: bar;
   case BOO: boo;
   case BOOP, BIP: bip;
   default: def;
}
```
Where `bar`, `boo`, `bip` and `def` are *types*.

**Comment by mlsteele** [comment]
Looks great, 👍 
(after landing the compiler changes)

**Comment by maxtaco** [comment]
@chrisnojima I think I need some help with flow before this can go in.

**Pull request merged**
