### PR TITLE
fixing log send on linux and ripping out client log file code

### PR DESCRIPTION
**Pull request by oconnor663**
This is an example PR showing what gets deleted if we decide the client isn't responsible for understanding where logs go anymore. Two big chunks go away: all the "split log file" code, and all the log rotation code.

It's unclear how we'll want to actually accomplish log rotation if we do this. I'll get some more thoughts from you guys tomorrow, @cjb @patrickxb .

### CODE REVIEW

**Comment by maxtaco** [comment]
Where does the log file go on auto fork? Chris ball and I just used that
feature the they day.

Also Steve really needs to look at this too because of Windows changes.

What problem is this solving?

**Comment by oconnor663** [comment]
I think that the log file on autofork goes to `Env.GetLogFile()`. But Env think the service log goes to "keybase.log" while install_osx.go thinks it goes to "keybase.service.log". It could be that Env.go's idea of where the logs go is only relevant on Linux and Windows, but @patrickxb's thought was that we could get rid of it entirely. I'm not sure about the whole thing yet, other than that it's unfortunate to have so many different sources of truth for this one value.

**Comment by oconnor663** [comment]
The original issue that sent me down this rabbit hole is that `keybase log send` has the wrong log file name on Linux. We could punt on all of this and just update LogSend to do the right thing (it already has os-specific code), but I figured it was worth untangling.

**Comment by maxtaco** [comment]
Urg, I was worried this was going to be an issue. @malgorithms couldn't believe that we couldn't figure out where the log files were, but as you say, you don't know where your log is going if you're launched with output redirection.

I agree it's turned out to be a mess.  @gabriel has often expressed displeasure about the `--log-file` parameter.  But it's needed for autofork, otherwise there's no way to figure out where the log goes. And all of our other parameters are configurable via file, flags, or environment.

Anyways, long term, maybe the service should get more involved.  You launch the service and tell it where to put its log, and then it's smart about how to rotate, etc.

But I disagree that `--log-file` or `clt rotate` are dead.  I think they're both needed for autofork.

**Comment by gabriel** [comment]
Yeah I generally prefer convention over configuration. This is a core principle of certain projects (like rails), as a response to insane J2EE projects with config files everywhere :)

**Comment by oconnor663** [comment]
Abandoned in favor of https://github.com/keybase/client/pull/1880

**Pull request closed without merging**
