### PR TITLE
Add ChangeDisplayCurrencyLocal Stellar RPC

### PR DESCRIPTION
**Pull request by zapu**
Note: I did not remove `GetAccountDisplayCurrency` mock yet, even though it's not used by stellar code right now (calls `remote.GetAccountDisplayCurrency` instead of `s.remoter.`GetAccountDisplayCurrency). I suspect in the future some tests might be conducted in a way where kbweb doesn't even know about the account, so this mock could be brought back then.

### CODE REVIEW

**Comment by zapu** [comment]
```
   record CurrencyLocal {
     string description;  // "USD ($)", "CAD ($)", etc.
     string code;         // "USD", "CAD", etc.
     string symbol;       // "$"
     string name;         // "US Dollar", "Thai Baht", etc.
   }
   array<CurrencyLocal> getDisplayCurrenciesLocal(int sessionID);
```

@patrickxb  should `string code;` be of type `OutsideCurrencyCode` instead?

**Comment by patrickxb** [comment]
@zapu frontend requested plain strings whenever possible.  They also didn't ask for `code` or `name` I just included them, so they might get scrapped once they start using it, who knows.

**Comment by zapu** [comment]
so maybe `void changeDisplayCurrencyLocal(int sessionID, AccountID accountID, OutsideCurrencyCode currency);` should take string as currency as well?

**Comment by patrickxb** [comment]
let's ask them what they prefer

**Comment by buoyad** [comment]
Having both of type `OutsideCurrencyCode` makes it clear what the valid inputs to `changeDisplayCurrencyLocal` are, and where they should be sourced from.

**Pull request merged**
