### PR TITLE
Display full name in followers/followees

### PR DESCRIPTION
**Pull request by akalin-keybase**
Fix cut-off long names on mobile; now they're wrapped, which is less
bad.

Fix flow issue.

### CODE REVIEW

**Comment by akalin-keybase** [comment]
Example of wrapped long names (previously they were just truncated):

screen shot 2017-11-29 at 9 54 06 pm

**Comment by keybase-ci-visdiff** [comment]
The commits 8e36c6f44562...03f271b3859d introduce visual changes on linux. <details><summary>:mag_right: 20 changed</summary>

 * Changed: **Profile-Your_Profile_Proof_Menu** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1512022632567-8e36c6f44562-03f271b3859d-linux/Profile-Your_Profile_Proof_Menu-8e36c6f44562.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1512022632567-8e36c6f44562-03f271b3859d-linux/Profile-Your_Profile_Proof_Menu-03f271b3859d.png)  
   Profile-Your_Profile_Proof_Menu comparison
 * Changed: **Profile-Your_Profile_Pending_Proof_Menu_HN** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1512022632567-8e36c6f44562-03f271b3859d-linux/Profile-Your_Profile_Pending_Proof_Menu_HN-8e36c6f44562.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1512022632567-8e36c6f44562-03f271b3859d-linux/Profile-Your_Profile_Pending_Proof_Menu_HN-03f271b3859d.png)  
   Profile-Your_Profile_Pending_Proof_Menu_HN comparison
 * Changed: **Profile-Your_Profile_Pending_Proof_Menu_DNS** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1512022632567-8e36c6f44562-03f271b3859d-linux/Profile-Your_Profile_Pending_Proof_Menu_DNS-8e36c6f44562.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1512022632567-8e36c6f44562-03f271b3859d-linux/Profile-Your_Profile_Pending_Proof_Menu_DNS-03f271b3859d.png)  
   Profile-Your_Profile_Pending_Proof_Menu_DNS comparison
 * Changed: **Profile-Your_Profile_Pending_Proof_Menu** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1512022632567-8e36c6f44562-03f271b3859d-linux/Profile-Your_Profile_Pending_Proof_Menu-8e36c6f44562.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1512022632567-8e36c6f44562-03f271b3859d-linux/Profile-Your_Profile_Pending_Proof_Menu-03f271b3859d.png)  
   Profile-Your_Profile_Pending_Proof_Menu comparison
 * Changed: **Profile-Your_Profile_No_Proofs** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1512022632567-8e36c6f44562-03f271b3859d-linux/Profile-Your_Profile_No_Proofs-8e36c6f44562.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1512022632567-8e36c6f44562-03f271b3859d-linux/Profile-Your_Profile_No_Proofs-03f271b3859d.png)  
   Profile-Your_Profile_No_Proofs comparison
 * Changed: **Profile-Your_Profile_Following_Tab** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1512022632567-8e36c6f44562-03f271b3859d-linux/Profile-Your_Profile_Following_Tab-8e36c6f44562.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1512022632567-8e36c6f44562-03f271b3859d-linux/Profile-Your_Profile_Following_Tab-03f271b3859d.png)  
   Profile-Your_Profile_Following_Tab comparison
 * Changed: **Profile-Your_Profile_Empty** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1512022632567-8e36c6f44562-03f271b3859d-linux/Profile-Your_Profile_Empty-8e36c6f44562.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1512022632567-8e36c6f44562-03f271b3859d-linux/Profile-Your_Profile_Empty-03f271b3859d.png)  
   Profile-Your_Profile_Empty comparison
 * Changed: **Profile-Your_Profile_Broken_Proof_Menu** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1512022632567-8e36c6f44562-03f271b3859d-linux/Profile-Your_Profile_Broken_Proof_Menu-8e36c6f44562.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1512022632567-8e36c6f44562-03f271b3859d-linux/Profile-Your_Profile_Broken_Proof_Menu-03f271b3859d.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1512022632567-8e36c6f44562-03f271b3859d-linux/Profile-Your_Profile_Broken_Proof_Menu.png)
 * Changed: **Profile-Your_Profile_Broken** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1512022632567-8e36c6f44562-03f271b3859d-linux/Profile-Your_Profile_Broken-8e36c6f44562.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1512022632567-8e36c6f44562-03f271b3859d-linux/Profile-Your_Profile_Broken-03f271b3859d.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1512022632567-8e36c6f44562-03f271b3859d-linux/Profile-Your_Profile_Broken.png)
 * Changed: **Profile-Your_Profile** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1512022632567-8e36c6f44562-03f271b3859d-linux/Profile-Your_Profile-8e36c6f44562.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1512022632567-8e36c6f44562-03f271b3859d-linux/Profile-Your_Profile-03f271b3859d.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1512022632567-8e36c6f44562-03f271b3859d-linux/Profile-Your_Profile.png)
 * Changed: **Profile-Unfollowed_Scrolled** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1512022632567-8e36c6f44562-03f271b3859d-linux/Profile-Unfollowed_Scrolled-8e36c6f44562.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1512022632567-8e36c6f44562-03f271b3859d-linux/Profile-Unfollowed_Scrolled-03f271b3859d.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1512022632567-8e36c6f44562-03f271b3859d-linux/Profile-Unfollowed_Scrolled.png)
 * Changed: **Profile-Unfollowed_Profile_page** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1512022632567-8e36c6f44562-03f271b3859d-linux/Profile-Unfollowed_Profile_page-8e36c6f44562.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1512022632567-8e36c6f44562-03f271b3859d-linux/Profile-Unfollowed_Profile_page-03f271b3859d.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1512022632567-8e36c6f44562-03f271b3859d-linux/Profile-Unfollowed_Profile_page.png)
 * Changed: **Profile-Unfollowed_Folders_Expanded** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1512022632567-8e36c6f44562-03f271b3859d-linux/Profile-Unfollowed_Folders_Expanded-8e36c6f44562.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1512022632567-8e36c6f44562-03f271b3859d-linux/Profile-Unfollowed_Folders_Expanded-03f271b3859d.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1512022632567-8e36c6f44562-03f271b3859d-linux/Profile-Unfollowed_Folders_Expanded.png)
 * Changed: **Profile-Unfollowed_Few_Folders** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1512022632567-8e36c6f44562-03f271b3859d-linux/Profile-Unfollowed_Few_Folders-8e36c6f44562.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1512022632567-8e36c6f44562-03f271b3859d-linux/Profile-Unfollowed_Few_Folders-03f271b3859d.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1512022632567-8e36c6f44562-03f271b3859d-linux/Profile-Unfollowed_Few_Folders.png)
 * Changed: **Profile-Unfollowed_Changed_Proofs_unreachable** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1512022632567-8e36c6f44562-03f271b3859d-linux/Profile-Unfollowed_Changed_Proofs_unreachable-8e36c6f44562.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1512022632567-8e36c6f44562-03f271b3859d-linux/Profile-Unfollowed_Changed_Proofs_unreachable-03f271b3859d.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1512022632567-8e36c6f44562-03f271b3859d-linux/Profile-Unfollowed_Changed_Proofs_unreachable.png)
 * Changed: **Profile-Unfollowed_Changed_Proofs_deleted** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1512022632567-8e36c6f44562-03f271b3859d-linux/Profile-Unfollowed_Changed_Proofs_deleted-8e36c6f44562.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1512022632567-8e36c6f44562-03f271b3859d-linux/Profile-Unfollowed_Changed_Proofs_deleted-03f271b3859d.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1512022632567-8e36c6f44562-03f271b3859d-linux/Profile-Unfollowed_Changed_Proofs_deleted.png)
 * Changed: **Profile-Unfollowed** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1512022632567-8e36c6f44562-03f271b3859d-linux/Profile-Unfollowed-8e36c6f44562.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1512022632567-8e36c6f44562-03f271b3859d-linux/Profile-Unfollowed-03f271b3859d.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1512022632567-8e36c6f44562-03f271b3859d-linux/Profile-Unfollowed.png)
 * Changed: **Profile-Followed_Changed_Scrolled** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1512022632567-8e36c6f44562-03f271b3859d-linux/Profile-Followed_Changed_Scrolled-8e36c6f44562.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1512022632567-8e36c6f44562-03f271b3859d-linux/Profile-Followed_Changed_Scrolled-03f271b3859d.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1512022632567-8e36c6f44562-03f271b3859d-linux/Profile-Followed_Changed_Scrolled.png)
 * Changed: **Profile-Followed_Changed** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1512022632567-8e36c6f44562-03f271b3859d-linux/Profile-Followed_Changed-8e36c6f44562.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1512022632567-8e36c6f44562-03f271b3859d-linux/Profile-Followed_Changed-03f271b3859d.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1512022632567-8e36c6f44562-03f271b3859d-linux/Profile-Followed_Changed.png)
 * Changed: **Profile-Followed** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1512022632567-8e36c6f44562-03f271b3859d-linux/Profile-Followed-8e36c6f44562.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1512022632567-8e36c6f44562-03f271b3859d-linux/Profile-Followed-03f271b3859d.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1512022632567-8e36c6f44562-03f271b3859d-linux/Profile-Followed.png)
</summary>

**Comment by cecileboucheron** [comment]
This is making my day 💯

**Pull request merged**
