### PR TITLE
updated deps, removed babel-eslint from desktop

### PR DESCRIPTION
**Pull request by chrisnojima**
@keybase/react-hackers 

@gabriel can you test the new packager:

See https://github.com/electron-userland/electron-packager/releases/tag/v6.0.0
specifically 

   

> [darwin/mas] BREAKING: The sign parameter is now osx-sign (for better cross-platform compatibility) and optionally takes several of the same sub-parameters as electron-osx-sign

### CODE REVIEW

**Comment by cjb** [comment]
:thumbsup: (let's make sure to test electron-packager@6 builds carefully before they go public)

**Comment by chrisnojima** [comment]
yeah we need to test build on all platforms before this goes

- [ ] OS X Build verified @gabriel 
- [ ] Linux Build verified @oconnor663 
- [ ] Windows Build verified @zanderz

**Comment by chrisnojima** [comment]
No big rush on this, let's try and do this over the next couple of days or so, thanks!

**Comment by chrisnojima** [comment]
@gabriel want to do a test build of this branch
@zanderz want to do a test build of this branch

**Comment by chrisnojima** [comment]
@gabriel bump
@zanderz bump

**Comment by gabriel** [comment]
Builds ok.. we don't use packager osx-sign...

Also manually verified signed after build

```
kbmb ➜ ~/Temp codesign -vvvv Keybase.app
--prepared:/Users/gabe/Temp/Keybase.app/Contents/Frameworks/Keybase Helper NP.app
--validated:/Users/gabe/Temp/Keybase.app/Contents/Frameworks/Keybase Helper NP.app
--prepared:/Users/gabe/Temp/Keybase.app/Contents/Frameworks/Keybase Helper.app
--validated:/Users/gabe/Temp/Keybase.app/Contents/Frameworks/Keybase Helper.app
--prepared:/Users/gabe/Temp/Keybase.app/Contents/Frameworks/Keybase Helper EH.app
--validated:/Users/gabe/Temp/Keybase.app/Contents/Frameworks/Keybase Helper EH.app
--prepared:/Users/gabe/Temp/Keybase.app/Contents/Frameworks/Mantle.framework/Versions/Current/.
--validated:/Users/gabe/Temp/Keybase.app/Contents/Frameworks/Mantle.framework/Versions/Current/.
--prepared:/Users/gabe/Temp/Keybase.app/Contents/Frameworks/ReactiveCocoa.framework/Versions/Current/.--prepared:/Users/gabe/Temp/Keybase.app/Contents/Frameworks/Squirrel.framework/Versions/Current/.

--validated:/Users/gabe/Temp/Keybase.app/Contents/Frameworks/ReactiveCocoa.framework/Versions/Current/.--validated:/Users/gabe/Temp/Keybase.app/Contents/Frameworks/Squirrel.framework/Versions/Current/.

--prepared:/Users/gabe/Temp/Keybase.app/Contents/Frameworks/Electron Framework.framework/Versions/Current/.
--validated:/Users/gabe/Temp/Keybase.app/Contents/Frameworks/Electron Framework.framework/Versions/Current/.
Keybase.app: valid on disk
Keybase.app: satisfies its Designated Requirement

kbmb ➜ ~/Temp codesign -vvvv Keybase.app/Contents/SharedSupport/bin/keybase 
Keybase.app/Contents/SharedSupport/bin/keybase: valid on disk
Keybase.app/Contents/SharedSupport/bin/keybase: satisfies its Designated Requirement

kbmb ➜ ~/Temp codesign -vvvv Keybase.app/Contents/SharedSupport/bin/kbfs 
Keybase.app/Contents/SharedSupport/bin/kbfs: valid on disk
Keybase.app/Contents/SharedSupport/bin/kbfs: satisfies its Designated Requirement
```

**Comment by chrisnojima** [comment]
cool thanks guys. @cjb  should we pull the trigger 2moro

**Comment by cjb** [comment]
Yep! Want to merge in now so it's in Wed 9am test -> Fri 3pm public?

**Comment by cjb** [comment]
Merging in for Nojima.

**Comment by gabriel** [comment]
I had to put in the symlink to get the flow errors to fix... https://github.com/keybase/client/commit/83c5df6ae4ca6ba95377fed7552bba7b1843706d

Do we need to re-enable travis-ci/push checks for scenarios like this? :(

**Pull request merged**
