### PR TITLE
netbsd support in the client

### PR DESCRIPTION
**Pull request by heronhaye**
@atomicules

### CODE REVIEW

**Comment by atomicules** [comment]
Anything you need from me on this?

**Comment by atomicules** [comment]
Tested master and it builds and works fine (so for me this was upgrading from 4.4.0 to 4.5.0):

```
~/Code/Go/...go/keybase * master$ go111 install -tags production
~/Code/Go/...go/keybase * master$ keybase version
Client:  4.5.0
Service: 4.4.0
~/Code/Go/...go/keybase * master$ keybase chat ls
▶ WARNING Restarting after upgrade; service is running v4.4.0, while v4.5.0 is available
▶ INFO Restarting service...
▶ INFO Starting background server with pid=25672
[1]   [REDACTED]
[2]   [REDACTED]
[3]   [REDACTED]
[4]   [REDACTED]
```

**Comment by atomicules** [comment]
> Anything else we can do?

I can't think of anything. I'm not personally concerned with a GUI on BSDs. As long as I can keep the command line client working I'm happy, thank you.

**Comment by atomicules** [comment]
Fwiw I also cross compiled that latest master build to NetBSD arm and tried that on an NetBSD arm box and it worked there to; I didn't build on the arm box due in part to laziness - would need to also build golang there.

I did see one odd thing where it died, but it ran ok when I tried again:

```
ip-172-31-20-142$ ./keybase version
Client:  4.5.0
Service: 4.4.0
ip-172-31-20-142$ ./keybase chat ls
▶ WARNING Restarting after upgrade; service is running v4.4.0, while v4.5.0 is available
▶ WARNING Error in Stopping 2642 via RPC: EOF; trying fallback (kill via pidfile)
▶ WARNING Kill via pidfile failed: os: process already finished

▶ ERROR os: process already finished
ip-172-31-20-142$ ./keybase chat ls
▶ INFO Starting background server with pid=13602
[1]  [REDACTED]
[2]  [REDACTED]
[3]  [REDACTED]
[4]  [REDACTED]
```

You can see how lazy I was being as I couldn't even be bothered to put the executable in my `PATH`.

**Comment by heronhaye** [comment]
Hmm, weird. May be due to the upgrade, if it happens again let us know. Glad you got it working!

**Comment by heronhaye** [comment]
Oh, what about KBFS? Does fuse work on bsd? (although it is useful even without fuse via the git remote helper and `keybase fs` commands)

**Comment by atomicules** [comment]
Hmm... I have not looked at KBFS at all yet. I will take a look and report back. At the moment:

```
$ keybase fs ps
▶ ERROR Keybase services aren't running - KBFS client not found.
```

**Comment by heronhaye** [comment]
It is a different daemon, you have to build `go/kbfs/kbfsfuse` and run that in the background. I tried crosscompiling but it seems there are some differences in syscall methods that'd have to be special cased, but nothing unsurmountable.

There are some docs here: https://keybase.io/docs/kbfs, https://keybase.io/docs/kbfs/understanding_kbfs.

**Comment by atomicules** [comment]
@heronhaye Just to follow-up on the kbfs stuff. Someone [started on a branch for openbsd](https://github.com/bazil/fuse/pull/104) for bazil/fuse. OpenBSD and NetBSD are often pretty close so I will dig through that and see if it's possible to finish off and get working, but won't be a quick thing.

**Comment by heronhaye** [comment]
@atomicules Ah, thanks for looking into it. Let me know if you need any help getting that working on Keybase's side.

**Pull request merged**
