### PR TITLE
zapu's fixes for `keybase team create`

### PR DESCRIPTION
**Pull request by oconnor663**
r? @zapu (Kind of backwards but whatever :)

I just tested these after creating a user with `KEYBASE_UPGRADE_PER_USER_KEY=1`. Works great.

### CODE REVIEW

**Comment by zapu** [comment]
I've reran CI because it failed on some KBFS script, looking good now :)

**Comment by zapu** [comment]
How do I create a user to test this?

```
▶ [DEBU keybase standard.go:176] 093 - TeamCreateEngine -> ERROR: Not found
▶ [DEBU keybase engine.go:67] 094 - RunEngine(NewTeam) -> ERROR: Not found
```

Maybe we should re-error with something more descriptive? Unless user is never going to see this.

**Comment by oconnor663** [comment]
You have to set `KEYBASE_UPGRADE_PER_USER_KEY=1` during signup. Does that make the error go away?

**Comment by oconnor663** [comment]
The not found error has to do with loading keys in standalone mode. I'm on it.

**Comment by oconnor663** [comment]
@patrickxb, could you take a look at d0a3979 in particular?

**Comment by oconnor663** [comment]
Removed standalone mode fixes, so we can land this immediately.

**Pull request merged**
