### PR TITLE
Just show 'you are not qualified' if airdrop register returns an error, instead of black bar

### PR DESCRIPTION
**Pull request by cjb**
@keybase/react-hackers, CC @keybase/picnicsquad @keybase/design

This is what users'll see instead of a black bar if they're rejected after having all three rows green:

Screen Shot 2019-10-09 at 4 38 52 PM

Screen Shot 2019-10-09 at 4 40 46 PM

### CODE REVIEW

**Comment by cjb** [comment]
@jzila I think we might try to get it into tomorrow's desktop release...

**Comment by cecileboucheron** [comment]
LGTM. Is the text white in light mode?

**Comment by cjb** [comment]
@cecileboucheron Yup!

Screen Shot 2019-10-09 at 5 14 09 PM

**Comment by cjb** [comment]
Bummer, gonna have to merge this despite an unrelated CI fail in `TestUIInboxLoaderLayout`.

**Pull request merged**
