### PR TITLE
fix android back on root tabs

### PR DESCRIPTION
**Pull request by chrisnojima**
- [x] turn off back behavior on tabs
- [x] remove existing back behavior checks
- [x] stash last route so foregrounding android after backgrounding goes back to the original tab
- [x] don't initialize react again, which crashes out otherwise

### CODE REVIEW

**Comment by hyperobject** [comment]
it feels a little bad that the app gets completely killed when going back on a root tab (it's not in the multitasking menu anymore). most of the other apps i tried this on still kept the app in the multitasking view

**Comment by chrisnojima** [comment]
Try // MainActivity.java
@Override
public void invokeDefaultOnBackPressed() {
    moveTaskToBack(true);
}

**Comment by chrisnojima** [comment]
@hyperobject try now

**Comment by hyperobject** [comment]
@chrisnojima yeah that works much better

**Pull request merged**
