### PR TITLE
I forgot Facebook in the services map

### PR DESCRIPTION
**Pull request by oconnor663**
Can this data be generated from protocol instead?

r? @maxtaco @cjb

### CODE REVIEW

**Comment by oconnor663** [comment]
This was causing the wrong proof type (NONE) to show up in the identify RPCs.

**Comment by maxtaco** [comment]
oh noes where did this list come from!!! i was trying so hard to avoid any mention of `Twitter` outside of `proof_support_twitter`.  CAn it be fixed?  I'll do a blame on it.

**Comment by maxtaco** [comment]
I'd like to root this map out of KB altogether...  Can we do that, or is that a different ticket?

**Comment by maxtaco** [comment]
👍  for now

**Comment by oconnor663** [comment]
Filed https://keybase.atlassian.net/browse/CORE-3777

**Comment by oconnor663** [comment]
b861f8ae66ee68450001bc098f1c2b8a9e65b9c1

**Comment by maxtaco** [comment]
👍 Thank you!!!

**Pull request closed without merging**
