### PR TITLE
Navigate to folder tab on add/ignore

### PR DESCRIPTION
**Pull request by gabriel**
When opening folder, on mobile, we'll favoriteAdd. Open folder gets called from search on "Open private folder" or "Open public folder".

On folder add/ignore we should navigate to folder tab, not navigateUp since our current route might not be the folder tab.

### CODE REVIEW

**Comment by gabriel** [comment]
@keybase/react-hackers

**Comment by keybase-ci-visdiff** [comment]
The commits 19c56219ceea...703a2166e690 introduce visual changes on linux. <details><summary>:mag_right: 1 changed</summary>

 * Changed: **Tracker-New_user_Scroll_1** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1497649630846-19c56219ceea-703a2166e690-linux/Tracker-New_user_Scroll_1-19c56219ceea.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1497649630846-19c56219ceea-703a2166e690-linux/Tracker-New_user_Scroll_1-703a2166e690.png)  
   Tracker-New_user_Scroll_1 comparison
</summary>

**Comment by chrisnojima** [comment]
Don't have to but it's likely a smaller diff

**Comment by gabriel** [comment]
I would still need the navigate to folder code for the search open folder actions. I'm open to doing it from the components themselves instead of from the rpc event though, if you think it's worth it.

**Comment by chrisnojima** [comment]
i don't think i understand the flow you're talking about

**Comment by gabriel** [comment]
I don't think there is a way to open a folder on mobile anymore with new search. If we do in the future we might want to re-consider this PR.

**Pull request closed without merging**
