### PR TITLE
Inbox for teams part 1

### PR DESCRIPTION
**Pull request by chrisnojima**
This is the first part of the inbox for teams. Won't merge this until its all ready but so this can be split up / reviewed in pieces

- [x] New avatar prop 'teamname' which draws team avatars (with fallback and rpc calls)
- [x] Rendering simple rows (1:1, adhoc teams, simple teams)

Next pr will aggregate the channels for a single team

@keybase/react-hackers

### CODE REVIEW

**Comment by chrisnojima** [comment]
@keybase/react-hackers bump open for 4 days

**Comment by keybase-ci-visdiff** [comment]
The commits be67d807caab...a074ecece47e introduce visual changes on linux. <details><summary>:mag_right: 22 changed</summary>

 * Changed: **Search_user_input-Users_Text_Clear_Search** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503083225861-be67d807caab-a074ecece47e-linux/Search_user_input-Users_Text_Clear_Search-be67d807caab.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503083225861-be67d807caab-a074ecece47e-linux/Search_user_input-Users_Text_Clear_Search-a074ecece47e.png)  
   Search_user_input-Users_Text_Clear_Search comparison
 * Changed: **Search_user_input-Users_Text** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503083225861-be67d807caab-a074ecece47e-linux/Search_user_input-Users_Text-be67d807caab.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503083225861-be67d807caab-a074ecece47e-linux/Search_user_input-Users_Text-a074ecece47e.png)  
   Search_user_input-Users_Text comparison
 * Changed: **Search_user_input-Users_Add** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503083225861-be67d807caab-a074ecece47e-linux/Search_user_input-Users_Add-be67d807caab.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503083225861-be67d807caab-a074ecece47e-linux/Search_user_input-Users_Add-a074ecece47e.png)  
   Search_user_input-Users_Add comparison
 * Changed: **Icon-Icon_Image** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503083225861-be67d807caab-a074ecece47e-linux/Icon-Icon_Image-be67d807caab.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503083225861-be67d807caab-a074ecece47e-linux/Icon-Icon_Image-a074ecece47e.png)  
   Icon-Icon_Image comparison
 * Changed: **Chat_Participant_Rekey-Normal** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503083225861-be67d807caab-a074ecece47e-linux/Chat_Participant_Rekey-Normal-be67d807caab.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503083225861-be67d807caab-a074ecece47e-linux/Chat_Participant_Rekey-Normal-a074ecece47e.png)  
   Chat_Participant_Rekey-Normal comparison
 * Changed: **Chat_Inbox-You_Rekey_Selected** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503083225861-be67d807caab-a074ecece47e-linux/Chat_Inbox-You_Rekey_Selected-be67d807caab.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503083225861-be67d807caab-a074ecece47e-linux/Chat_Inbox-You_Rekey_Selected-a074ecece47e.png)  
   Chat_Inbox-You_Rekey_Selected comparison
 * Changed: **Chat_Inbox-You_Rekey** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503083225861-be67d807caab-a074ecece47e-linux/Chat_Inbox-You_Rekey-be67d807caab.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503083225861-be67d807caab-a074ecece47e-linux/Chat_Inbox-You_Rekey-a074ecece47e.png)  
   Chat_Inbox-You_Rekey comparison
 * Changed: **Chat_Inbox-Selected_Normal** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503083225861-be67d807caab-a074ecece47e-linux/Chat_Inbox-Selected_Normal-be67d807caab.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503083225861-be67d807caab-a074ecece47e-linux/Chat_Inbox-Selected_Normal-a074ecece47e.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503083225861-be67d807caab-a074ecece47e-linux/Chat_Inbox-Selected_Normal.png)
 * Changed: **Chat_Inbox-Selected_Muted** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503083225861-be67d807caab-a074ecece47e-linux/Chat_Inbox-Selected_Muted-be67d807caab.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503083225861-be67d807caab-a074ecece47e-linux/Chat_Inbox-Selected_Muted-a074ecece47e.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503083225861-be67d807caab-a074ecece47e-linux/Chat_Inbox-Selected_Muted.png)
 * Changed: **Chat_Inbox-Part_Rekey_Selected** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503083225861-be67d807caab-a074ecece47e-linux/Chat_Inbox-Part_Rekey_Selected-be67d807caab.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503083225861-be67d807caab-a074ecece47e-linux/Chat_Inbox-Part_Rekey_Selected-a074ecece47e.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503083225861-be67d807caab-a074ecece47e-linux/Chat_Inbox-Part_Rekey_Selected.png)
 * Changed: **Chat_Inbox-Part_Rekey** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503083225861-be67d807caab-a074ecece47e-linux/Chat_Inbox-Part_Rekey-be67d807caab.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503083225861-be67d807caab-a074ecece47e-linux/Chat_Inbox-Part_Rekey-a074ecece47e.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503083225861-be67d807caab-a074ecece47e-linux/Chat_Inbox-Part_Rekey.png)
 * Changed: **Chat_Inbox-Normal** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503083225861-be67d807caab-a074ecece47e-linux/Chat_Inbox-Normal-be67d807caab.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503083225861-be67d807caab-a074ecece47e-linux/Chat_Inbox-Normal-a074ecece47e.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503083225861-be67d807caab-a074ecece47e-linux/Chat_Inbox-Normal.png)
 * Changed: **Avatar-Normal_x_40** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503083225861-be67d807caab-a074ecece47e-linux/Avatar-Normal_x_40-be67d807caab.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503083225861-be67d807caab-a074ecece47e-linux/Avatar-Normal_x_40-a074ecece47e.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503083225861-be67d807caab-a074ecece47e-linux/Avatar-Normal_x_40.png)
 * Changed: **Avatar-Normal_x_16** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503083225861-be67d807caab-a074ecece47e-linux/Avatar-Normal_x_16-be67d807caab.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503083225861-be67d807caab-a074ecece47e-linux/Avatar-Normal_x_16-a074ecece47e.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503083225861-be67d807caab-a074ecece47e-linux/Avatar-Normal_x_16.png)
 * Changed: **Avatar-Mutual_Follow_x_40** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503083225861-be67d807caab-a074ecece47e-linux/Avatar-Mutual_Follow_x_40-be67d807caab.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503083225861-be67d807caab-a074ecece47e-linux/Avatar-Mutual_Follow_x_40-a074ecece47e.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503083225861-be67d807caab-a074ecece47e-linux/Avatar-Mutual_Follow_x_40.png)
 * Changed: **Avatar-Mutual_Follow_x_16** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503083225861-be67d807caab-a074ecece47e-linux/Avatar-Mutual_Follow_x_16-be67d807caab.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503083225861-be67d807caab-a074ecece47e-linux/Avatar-Mutual_Follow_x_16-a074ecece47e.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503083225861-be67d807caab-a074ecece47e-linux/Avatar-Mutual_Follow_x_16.png)
 * Changed: **Avatar-Follows_You_x_40** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503083225861-be67d807caab-a074ecece47e-linux/Avatar-Follows_You_x_40-be67d807caab.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503083225861-be67d807caab-a074ecece47e-linux/Avatar-Follows_You_x_40-a074ecece47e.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503083225861-be67d807caab-a074ecece47e-linux/Avatar-Follows_You_x_40.png)
 * Changed: **Avatar-Follows_You_x_16** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503083225861-be67d807caab-a074ecece47e-linux/Avatar-Follows_You_x_16-be67d807caab.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503083225861-be67d807caab-a074ecece47e-linux/Avatar-Follows_You_x_16-a074ecece47e.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503083225861-be67d807caab-a074ecece47e-linux/Avatar-Follows_You_x_16.png)
 * Changed: **Avatar-Following_x_40** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503083225861-be67d807caab-a074ecece47e-linux/Avatar-Following_x_40-be67d807caab.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503083225861-be67d807caab-a074ecece47e-linux/Avatar-Following_x_40-a074ecece47e.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503083225861-be67d807caab-a074ecece47e-linux/Avatar-Following_x_40.png)
 * Changed: **Avatar-Following_x_16** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503083225861-be67d807caab-a074ecece47e-linux/Avatar-Following_x_16-be67d807caab.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503083225861-be67d807caab-a074ecece47e-linux/Avatar-Following_x_16-a074ecece47e.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503083225861-be67d807caab-a074ecece47e-linux/Avatar-Following_x_16.png)
 * Changed: **Avatar-Fallback_x_40** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503083225861-be67d807caab-a074ecece47e-linux/Avatar-Fallback_x_40-be67d807caab.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503083225861-be67d807caab-a074ecece47e-linux/Avatar-Fallback_x_40-a074ecece47e.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503083225861-be67d807caab-a074ecece47e-linux/Avatar-Fallback_x_40.png)
 * Changed: **Avatar-Fallback_x_16** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503083225861-be67d807caab-a074ecece47e-linux/Avatar-Fallback_x_16-be67d807caab.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503083225861-be67d807caab-a074ecece47e-linux/Avatar-Fallback_x_16-a074ecece47e.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503083225861-be67d807caab-a074ecece47e-linux/Avatar-Fallback_x_16.png)
</summary>

**Comment by chrisnojima** [comment]
@cjb updated to support mobile and merged master a couple of times, ptal

**Comment by chrisnojima** [comment]
image

**Comment by keybase-ci-visdiff** [comment]
The commits be67d807caab...06a704975697 introduce visual changes on linux. <details><summary>:mag_right: 22 changed</summary>

 * Changed: **Search_user_input-Users_Text_Clear_Search** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503086537515-be67d807caab-06a704975697-linux/Search_user_input-Users_Text_Clear_Search-be67d807caab.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503086537515-be67d807caab-06a704975697-linux/Search_user_input-Users_Text_Clear_Search-06a704975697.png)  
   Search_user_input-Users_Text_Clear_Search comparison
 * Changed: **Search_user_input-Users_Text** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503086537515-be67d807caab-06a704975697-linux/Search_user_input-Users_Text-be67d807caab.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503086537515-be67d807caab-06a704975697-linux/Search_user_input-Users_Text-06a704975697.png)  
   Search_user_input-Users_Text comparison
 * Changed: **Search_user_input-Users_Add** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503086537515-be67d807caab-06a704975697-linux/Search_user_input-Users_Add-be67d807caab.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503086537515-be67d807caab-06a704975697-linux/Search_user_input-Users_Add-06a704975697.png)  
   Search_user_input-Users_Add comparison
 * Changed: **Icon-Icon_Image** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503086537515-be67d807caab-06a704975697-linux/Icon-Icon_Image-be67d807caab.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503086537515-be67d807caab-06a704975697-linux/Icon-Icon_Image-06a704975697.png)  
   Icon-Icon_Image comparison
 * Changed: **Chat_Participant_Rekey-Normal** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503086537515-be67d807caab-06a704975697-linux/Chat_Participant_Rekey-Normal-be67d807caab.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503086537515-be67d807caab-06a704975697-linux/Chat_Participant_Rekey-Normal-06a704975697.png)  
   Chat_Participant_Rekey-Normal comparison
 * Changed: **Chat_Inbox-You_Rekey_Selected** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503086537515-be67d807caab-06a704975697-linux/Chat_Inbox-You_Rekey_Selected-be67d807caab.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503086537515-be67d807caab-06a704975697-linux/Chat_Inbox-You_Rekey_Selected-06a704975697.png)  
   Chat_Inbox-You_Rekey_Selected comparison
 * Changed: **Chat_Inbox-You_Rekey** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503086537515-be67d807caab-06a704975697-linux/Chat_Inbox-You_Rekey-be67d807caab.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503086537515-be67d807caab-06a704975697-linux/Chat_Inbox-You_Rekey-06a704975697.png)  
   Chat_Inbox-You_Rekey comparison
 * Changed: **Chat_Inbox-Selected_Normal** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503086537515-be67d807caab-06a704975697-linux/Chat_Inbox-Selected_Normal-be67d807caab.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503086537515-be67d807caab-06a704975697-linux/Chat_Inbox-Selected_Normal-06a704975697.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503086537515-be67d807caab-06a704975697-linux/Chat_Inbox-Selected_Normal.png)
 * Changed: **Chat_Inbox-Selected_Muted** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503086537515-be67d807caab-06a704975697-linux/Chat_Inbox-Selected_Muted-be67d807caab.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503086537515-be67d807caab-06a704975697-linux/Chat_Inbox-Selected_Muted-06a704975697.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503086537515-be67d807caab-06a704975697-linux/Chat_Inbox-Selected_Muted.png)
 * Changed: **Chat_Inbox-Part_Rekey_Selected** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503086537515-be67d807caab-06a704975697-linux/Chat_Inbox-Part_Rekey_Selected-be67d807caab.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503086537515-be67d807caab-06a704975697-linux/Chat_Inbox-Part_Rekey_Selected-06a704975697.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503086537515-be67d807caab-06a704975697-linux/Chat_Inbox-Part_Rekey_Selected.png)
 * Changed: **Chat_Inbox-Part_Rekey** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503086537515-be67d807caab-06a704975697-linux/Chat_Inbox-Part_Rekey-be67d807caab.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503086537515-be67d807caab-06a704975697-linux/Chat_Inbox-Part_Rekey-06a704975697.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503086537515-be67d807caab-06a704975697-linux/Chat_Inbox-Part_Rekey.png)
 * Changed: **Chat_Inbox-Normal** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503086537515-be67d807caab-06a704975697-linux/Chat_Inbox-Normal-be67d807caab.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503086537515-be67d807caab-06a704975697-linux/Chat_Inbox-Normal-06a704975697.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503086537515-be67d807caab-06a704975697-linux/Chat_Inbox-Normal.png)
 * Changed: **Avatar-Normal_x_40** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503086537515-be67d807caab-06a704975697-linux/Avatar-Normal_x_40-be67d807caab.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503086537515-be67d807caab-06a704975697-linux/Avatar-Normal_x_40-06a704975697.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503086537515-be67d807caab-06a704975697-linux/Avatar-Normal_x_40.png)
 * Changed: **Avatar-Normal_x_16** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503086537515-be67d807caab-06a704975697-linux/Avatar-Normal_x_16-be67d807caab.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503086537515-be67d807caab-06a704975697-linux/Avatar-Normal_x_16-06a704975697.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503086537515-be67d807caab-06a704975697-linux/Avatar-Normal_x_16.png)
 * Changed: **Avatar-Mutual_Follow_x_40** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503086537515-be67d807caab-06a704975697-linux/Avatar-Mutual_Follow_x_40-be67d807caab.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503086537515-be67d807caab-06a704975697-linux/Avatar-Mutual_Follow_x_40-06a704975697.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503086537515-be67d807caab-06a704975697-linux/Avatar-Mutual_Follow_x_40.png)
 * Changed: **Avatar-Mutual_Follow_x_16** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503086537515-be67d807caab-06a704975697-linux/Avatar-Mutual_Follow_x_16-be67d807caab.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503086537515-be67d807caab-06a704975697-linux/Avatar-Mutual_Follow_x_16-06a704975697.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503086537515-be67d807caab-06a704975697-linux/Avatar-Mutual_Follow_x_16.png)
 * Changed: **Avatar-Follows_You_x_40** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503086537515-be67d807caab-06a704975697-linux/Avatar-Follows_You_x_40-be67d807caab.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503086537515-be67d807caab-06a704975697-linux/Avatar-Follows_You_x_40-06a704975697.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503086537515-be67d807caab-06a704975697-linux/Avatar-Follows_You_x_40.png)
 * Changed: **Avatar-Follows_You_x_16** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503086537515-be67d807caab-06a704975697-linux/Avatar-Follows_You_x_16-be67d807caab.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503086537515-be67d807caab-06a704975697-linux/Avatar-Follows_You_x_16-06a704975697.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503086537515-be67d807caab-06a704975697-linux/Avatar-Follows_You_x_16.png)
 * Changed: **Avatar-Following_x_40** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503086537515-be67d807caab-06a704975697-linux/Avatar-Following_x_40-be67d807caab.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503086537515-be67d807caab-06a704975697-linux/Avatar-Following_x_40-06a704975697.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503086537515-be67d807caab-06a704975697-linux/Avatar-Following_x_40.png)
 * Changed: **Avatar-Following_x_16** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503086537515-be67d807caab-06a704975697-linux/Avatar-Following_x_16-be67d807caab.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503086537515-be67d807caab-06a704975697-linux/Avatar-Following_x_16-06a704975697.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503086537515-be67d807caab-06a704975697-linux/Avatar-Following_x_16.png)
 * Changed: **Avatar-Fallback_x_40** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503086537515-be67d807caab-06a704975697-linux/Avatar-Fallback_x_40-be67d807caab.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503086537515-be67d807caab-06a704975697-linux/Avatar-Fallback_x_40-06a704975697.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503086537515-be67d807caab-06a704975697-linux/Avatar-Fallback_x_40.png)
 * Changed: **Avatar-Fallback_x_16** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503086537515-be67d807caab-06a704975697-linux/Avatar-Fallback_x_16-be67d807caab.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503086537515-be67d807caab-06a704975697-linux/Avatar-Fallback_x_16-06a704975697.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1503086537515-be67d807caab-06a704975697-linux/Avatar-Fallback_x_16.png)
</summary>

**Pull request merged**
