### PR TITLE
Default to sig v1 for now

### PR DESCRIPTION
**Pull request by patrickxb**

### CODE REVIEW

**Comment by mmaxim** [comment]
cc @maxtaco so you know what we are doing.

**Comment by mmaxim** [comment]
cc @joshblum

**Comment by maxtaco** [comment]
:+1:

**Comment by patrickxb** [comment]
To be clear, the sig v2 code by @joshblum is all good. 

It exposed a bug in an untested path in my recent sig chain changes.

**Comment by patrickxb** [comment]
Merging, will wait for master CI.  Tests passed locally.

**Pull request merged**
