### PR TITLE
check needed seqnos

### PR DESCRIPTION
**Pull request by mlsteele**
Use neededSeqnos when loading subteams.

### CODE REVIEW

**Comment by keybase-ci-visdiff** [comment]
The commits c25a1c285ca5...3d4fe3d85e9b introduce visual changes on linux. <details><summary>:mag_right: 1 changed</summary>

 * Changed: **Markdown-emoji** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1498597098325-c25a1c285ca5-3d4fe3d85e9b-linux/Markdown-emoji-c25a1c285ca5.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1498597098325-c25a1c285ca5-3d4fe3d85e9b-linux/Markdown-emoji-3d4fe3d85e9b.png)  
   Markdown-emoji comparison
</summary>

**Comment by keybase-ci-visdiff** [comment]
The commits c25a1c285ca5...c5c38dfcd898 introduce visual changes on linux. <details><summary>:mag_right: 1 changed</summary>

 * Changed: **Tracker-New_user_Scroll_1** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1498599128461-c25a1c285ca5-c5c38dfcd898-linux/Tracker-New_user_Scroll_1-c25a1c285ca5.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1498599128461-c25a1c285ca5-c5c38dfcd898-linux/Tracker-New_user_Scroll_1-c5c38dfcd898.png)  
   Tracker-New_user_Scroll_1 comparison
</summary>

**Comment by keybase-ci-visdiff** [comment]
The commits ced97978ff7b...f44ffb9e1622 introduce visual changes on linux. <details><summary>:mag_right: 1 changed</summary>

 * Changed: **Tracker-New_user_Scroll_1** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1498660404057-ced97978ff7b-f44ffb9e1622-linux/Tracker-New_user_Scroll_1-ced97978ff7b.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1498660404057-ced97978ff7b-f44ffb9e1622-linux/Tracker-New_user_Scroll_1-f44ffb9e1622.png)  
   Tracker-New_user_Scroll_1 comparison
</summary>

**Comment by keybase-ci-visdiff** [comment]
The commits ced97978ff7b...f44ffb9e1622 introduce visual changes on linux. <details><summary>:mag_right: 1 changed</summary>

 * Changed: **Tracker-New_user_Scroll_1** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1498666542135-ced97978ff7b-f44ffb9e1622-linux/Tracker-New_user_Scroll_1-ced97978ff7b.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1498666542135-ced97978ff7b-f44ffb9e1622-linux/Tracker-New_user_Scroll_1-f44ffb9e1622.png)  
   Tracker-New_user_Scroll_1 comparison
</summary>

**Comment by keybase-ci-visdiff** [comment]
The commits ccf3f71f9aad...fe39120bccba introduce visual changes on linux. <details><summary>:mag_right: 1 changed</summary>

 * Changed: **Tracker-New_user_Scroll_1** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1498677630194-ccf3f71f9aad-fe39120bccba-linux/Tracker-New_user_Scroll_1-ccf3f71f9aad.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1498677630194-ccf3f71f9aad-fe39120bccba-linux/Tracker-New_user_Scroll_1-fe39120bccba.png)  
   Tracker-New_user_Scroll_1 comparison
</summary>

**Comment by mlsteele** [comment]
Ok this is ready again.

**Pull request merged**
