### PR TITLE
SecureString for passphrase

### PR DESCRIPTION
**Pull request by gabriel**

### CODE REVIEW

**Comment by MarcoPolo** [comment]
tagging @keybase/react-hackers

**Comment by MarcoPolo** [comment]
Also this won't quite work because JSON.stringify and chrome dev tools can still read that value, you need to wrap it in a function. See this example:

http://www.es6fiddle.net/ikad18kf/

**Comment by gabriel** [comment]
oops thanks fixed... yeah i didn't cc anyone yet cause I was waiting to figure out how to test since we don't have that setup yet

**Comment by MarcoPolo** [comment]
ah okay makes sense! carry on :)

**Comment by gabriel** [comment]
@chrisnojima lmk if you want to get this merged in so you can use it on login... otherwise i'll wait until after login is in master so i can test

**Comment by chrisnojima** [comment]
go for it

**Comment by MarcoPolo** [comment]
Merging because I need this for signup passphrase

**Pull request merged**
