### PR TITLE
fix broken systests

### PR DESCRIPTION
**Pull request by maxtaco**

### CODE REVIEW

**Comment by maxtaco** [comment]
@patrickxb I'm going to go ahead an merge, but let me know if these are OK.  they should fix the broken tests in `systests/`

**Comment by patrickxb** [comment]
No, this is wrong.  With your change, the user will see two error messages.  

Those returns of the output messages were there for a reason.

**Comment by patrickxb** [comment]
See:

ERROR!

Sorry, you have a PGP private key that Keybase doesn't have a copy of.
You need to prove you're you. Any of these will unlock this computer:

   - reset your account and start fresh: https://keybase.io/#account-reset
   - install GPG and put your PGP private key on this machine and try again
   - go back and provision with another device or paper key

▶ ERROR No synced secret PGP key found on keybase.io


and


ERROR!

The server rejected your login attempt.

If you'd like to reset your passphrase, go to https://keybase.io/#password-reset

▶ ERROR Bad passphrase: server rejected login attempt

**Comment by maxtaco** [comment]
Gah, sorry.  I see.

Well unfortunately the systests are asserting an error from `Run()` in exactly this case.

We'll need some more machinery then.  I have an idea.

**Comment by maxtaco** [comment]
Ok, new PR up here: https://github.com/keybase/client/pull/1666

Here is sample output:

screen shot 2016-01-08 at 6 46 07 am

And...

screen shot 2016-01-08 at 6 46 25 am

**Pull request merged**
