### PR TITLE
Save tmp file in same directory as real file

### PR DESCRIPTION
**Pull request by patrickxb**
Fixes CORE-2066

r? @maxtaco

### CODE REVIEW

**Comment by maxtaco** [comment]
What is suffix here?

**Comment by patrickxb** [comment]
Device id

**Comment by maxtaco** [comment]
The orthodoxy is to have tmp files be non guessable to mitigate time to
check time to use attacks. Is this the case?

**Comment by patrickxb** [comment]
Why would device ID during provisioning be guessable?

**Comment by maxtaco** [comment]
it's in the user's public sigchain by now!

**Comment by maxtaco** [comment]
(or maybe not?)

**Comment by patrickxb** [comment]
Not when it is first saved.  

I really don't care what the suffix is, but I don't see the advantage of config_XXX.json versus config_YYY.json where XXX is random bytes and YYY is a random device id.

**Comment by maxtaco** [comment]
Ok.  As long as it is not guessable by another process on the machine.

**Pull request merged**
