### PR TITLE
small text changes

### PR DESCRIPTION
**Pull request by chrisnojima**
@keybase/react-hackers

### CODE REVIEW

**Comment by keybase-ci-visdiff** [comment]
:mag_right: The commits ee1854282315...7a8f170e9196 introduced some visual changes on win32:
 * Changed: **Folders_TLF-Coming_Soon** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1467911762101-ee1854282315-7a8f170e9196-win32/Folders_TLF-Coming_Soon-ee1854282315.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1467911762101-ee1854282315-7a8f170e9196-win32/Folders_TLF-Coming_Soon-7a8f170e9196.png)  
   Folders_TLF-Coming_Soon comparison

**Comment by keybase-ci-visdiff** [comment]
:mag_right: The commits ee1854282315...7a8f170e9196 introduced some visual changes on linux:
 * Changed: **unlock_folders-Single** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1467911953544-ee1854282315-7a8f170e9196-linux/unlock_folders-Single-ee1854282315.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1467911953544-ee1854282315-7a8f170e9196-linux/unlock_folders-Single-7a8f170e9196.png)  
   unlock_folders-Single comparison
 * Changed: **Folders_TLF-Coming_Soon** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1467911953544-ee1854282315-7a8f170e9196-linux/Folders_TLF-Coming_Soon-ee1854282315.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1467911953544-ee1854282315-7a8f170e9196-linux/Folders_TLF-Coming_Soon-7a8f170e9196.png)  
   Folders_TLF-Coming_Soon comparison

**Comment by MarcoPolo** [comment]
👍

**Comment by chrisnojima** [comment]
retest this please

**Comment by keybase-ci-visdiff** [comment]
:mag_right: The commits 78c79a6c9895...295821091d0e introduced some visual changes on win32:
 * Changed: **Folders_TLF-Coming_Soon** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468256789729-78c79a6c9895-295821091d0e-win32/Folders_TLF-Coming_Soon-78c79a6c9895.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468256789729-78c79a6c9895-295821091d0e-win32/Folders_TLF-Coming_Soon-295821091d0e.png)  
   Folders_TLF-Coming_Soon comparison

**Comment by keybase-ci-visdiff** [comment]
:mag_right: The commits 78c79a6c9895...295821091d0e introduced some visual changes on linux:
 * Changed: **Folders_TLF-Coming_Soon** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468256827209-78c79a6c9895-295821091d0e-linux/Folders_TLF-Coming_Soon-78c79a6c9895.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468256827209-78c79a6c9895-295821091d0e-linux/Folders_TLF-Coming_Soon-295821091d0e.png)  
   Folders_TLF-Coming_Soon comparison

**Pull request merged**
