### PR TITLE
Default for alwaysUpdate should be false

### PR DESCRIPTION
**Pull request by gabriel**
The prompt will only be called if updates.auto setting is false so that
should be the default.

### CODE REVIEW

**Comment by gabriel** [comment]
@keybase/react-hackers 

Fixes https://keybase.atlassian.net/browse/DESKTOP-313

**Comment by chrisnojima** [comment]
Don't we want to show it and also have the default to be true? We want ppl to auto update

**Comment by gabriel** [comment]
yeah this is a temp quick fix... we should probably take this though since this behavior is better than the existing?

**Comment by gabriel** [comment]
Or can wait till I do the real fix tomorrow...

**Comment by chrisnojima** [comment]
So what happens now? It just auto updates? Is this new behavior since i was seeing the updater previously? @cjb  thoughts?

**Comment by gabriel** [comment]
right now you have to deselect the auto updates checkbox everytime it comes up... otherwise you'll never see it again :)

**Comment by gabriel** [comment]
ok... i'll do the real fix tomorrow (which is remembering the setting but having it on by default, e.g. the first time)

(it so happens after you deselect it the first time, the setting becomes false and will always be false since the prompt only comes up if false after that, which i guess is a little confusing unless you are staring at the code)

**Comment by gabriel** [comment]
Fixed this for reals in other PR

**Pull request closed without merging**
