### PR TITLE
Folder ListView

### PR DESCRIPTION
**Pull request by gabriel**
Uses native ListView for folders.

### CODE REVIEW

**Comment by gabriel** [comment]
@keybase/react-hackers

**Comment by chrisnojima** [comment]
The list is below the tab bar when your list is long. On my device i can't see the ignored section

**Comment by chrisnojima** [comment]
In the screen shot i have rows below the last visible one
screen shot 2017-04-04 at 3 34 40 pm

**Comment by gabriel** [comment]
Fixed the TabView to flex correctly, which fixes ListView height.
Also fixed badging.

**Comment by gabriel** [comment]
Bump.

**Pull request merged**
