### PR TITLE
give Files on mobile a promotion

### PR DESCRIPTION
**Pull request by songgao**

### CODE REVIEW

**Comment by jzila** [comment]
@songgao I think we also need:
https://github.com/keybase/client/blob/01d5ad90e4fc0f43b88692abcf6b76836fc25b43/shared/actions/platform-specific/push.native.js#L64-L70

and:
https://github.com/keybase/client/blob/01d5ad90e4fc0f43b88692abcf6b76836fc25b43/shared/actions/config/index.js#L322

**Comment by songgao** [comment]
Hmm AFAIK nav2 is not supposed to use `navigateTo`. Have you tested this on a nav2 master build?

**Comment by jzila** [comment]
@songgao share text isn't hooked up, ignore that one. The other ones need the nav1 route changed though.

**Comment by jzila** [comment]
@songgao also I think you're right, that shouldn't be `navigateTo` anyway, it should be `createSwitchRouteDef`.

**Comment by songgao** [comment]
> The other ones need the nav1 route changed though.

Hmm I thought we were only gonna do it for nav2? There were issues with nav1 team routing which was why we switched them back.

**Comment by mmaxim** [comment]
@songgao This isn't using the right icon in the nav bar, the Files icon is too big.

**Comment by songgao** [comment]
@mmaxim oh sorry just saw this. Fixed in master.

**Pull request merged**
