### PR TITLE
Fix Set Public Name on native

### PR DESCRIPTION
**Pull request by MarcoPolo**

### CODE REVIEW

**Comment by cjb** [comment]
CC @keybase/react-hackers

**Comment by MarcoPolo** [comment]
I think this is related to having the box wrap the scrollview, and outer box not filling the screen properly.

I checked to make sure we aren't doing this anywhere else and it looked fine

**Comment by cjb** [comment]
@MarcoPolo some eslint errors

**Comment by cjb** [comment]
Gonna merge for @MarcoPolo so we can make a build, yell if that was a mistake.

**Pull request merged**
