### PR TITLE
Update the snap metadata to use go 1.8.3

### PR DESCRIPTION
**Pull request by elopio**

### CODE REVIEW

**Comment by abitrolly** [comment]
When it will reach stable/production grade to be installed with `snap install keybase`?

**Comment by elopio** [comment]
@abitrolly I wanted to add the GUI to the snap before moving it to stable. But that will take some time because I don't know much about electron.

However, right now this branch is the first step, because the build is failing so I'm not able to test the latest changes in the edge channel.

**Comment by abitrolly** [comment]
I am fine if keybase GUI is matured in unstable channel, but it would be nice to use CLI in stable already.

Do you know why builds are failing? That private Jenkins is not too informative.

**Comment by elopio** [comment]
I do not, but I am 99.99% sure they have nothing to do with my change.

**Comment by chrisglass** [comment]
Is there any update on this? It would be nice to have a snapped client.

I doubt the snapping is hooked in the CI so that cannot be the source of error here.

**Comment by om26er** [comment]
Hello, please land this to unblock the snap packaging.

**Comment by om26er** [comment]
@abitrolly ping

**Comment by abitrolly** [comment]
@om26er I am the wrong person to ping. Perhaps @oconnor663 can help.

**Comment by oconnor663** [comment]
Oh man, apologies for not seeing this PR. I can totally land it as is. Should we go ahead and bump it to Go 1.9.4?

**Comment by om26er** [comment]
> Should we go ahead and bump it to Go 1.9.4?

I think that should not be a problem, IMO. thoughts @elopio ?

**Comment by elopio** [comment]
Updated to 1.9.4, we can try that.

**Comment by oconnor663** [comment]
Thanks, sorry for the delay!

**Comment by om26er** [comment]
@elopio I built the snap today and it seems to only build the 'Keybase command line client', I am looking for the electron based client for my desktop, will that need separate work ?

**Comment by elopio** [comment]
yes. I'm not sure if we want both on the same snap or separate. But back when I was working on this I thought it would be better to first test and release the cli, and then take care of the GUI.

**Comment by Max4488** [comment]
https://bcmbenefits.net/?ref= is a changing situation in the world economy and financial markets.  They ensure that the returns are satisfactory and 100% risk free.  It is a cryptocurrency investment platform where investors make daily profits using the ROI (Return on investment) from what you've invested in the company, and they also offer 10% transfer commission with a minimum deposit of $ 100, the maximum of which depends on the investment plan you are investing in . Their tier is unlimited as the company has multiple investment plans that work well and each of the investment plans has its own percentage offer. Their withdrawal are fast to any external wallet. meaning that after 2 days of your investment, you can choose to withdraw both your capital and daily profits  .  You can even increase your investment by reloading your investment plan, making a new deposit or requesting a new withdrawal limit, you can choose to make a deposit as many times a day or at any time of your choice. You  Can make a deposit.  The higher your investment, the faster the returns you will receive in return will grow. They're very stable and profitable. And more stable during the withdrawal on every withdrawal transaction.

**Comment by Max4488** [comment]
https://bcmbenefits.net/?ref=max88
https://adviserinfo.sec.gov/firm/summary/146182

**Pull request merged**
