### PR TITLE
make the armor header and footer inline

### PR DESCRIPTION
**Pull request by oconnor663**
@maxtaco @malgorithms 

(There's a good chance this will fail a test somewhere.)

### Before

BEGIN SALTPACK MESSAGE.

kYM5h1pg6qz9UMn j6G7KB2OUinEheb Gu4oiGFwXwPiASu HGKGly3ND6HxSqG M1oyIAfmkRnh63t KTEruYC9SvgnpXF PjADlbCB6EWkEgS 3xW0vQABZtDH7cb KU94goDCE734rbk VV4Sqo7YXtK4HJ5 vfAweQ0Hry9qPUU 3RfWU0zYAkHOTQa 0YN8ZtC8n08hyYq qXGp8oQuRr5Yx9A tn6f0heVErJHvSs DJupDic0L4E3r30 2rFXxWleft71Lc8 Ec2Kqd7Lpusilhi qM40oQeqzOxHCcQ erNuweI9zNaQveM u00.

END SALTPACK MESSAGE.

### After

BEGIN SALTPACK MESSAGE. kYM5h1pg6qz9UMn j6G7KB2OUXnrO4U jxfvGbcfFn5zKNm KO7M8wGKChqAEn3 ZQ0UdHpjLbgaAa0 hOzeDbGdAnSCScz EYTmj5CLyqkmCJM yx4U2G8Dc0P23fP Fg9vodhYUS0s9Wr PgLtZDugm1Ta5su iC0Vxvi9YJfv6Rr 0o0MW6YvJFdhnXf lGdT9A098puYiZl WmJP4zOjfi2umcl niAd0ApQakZXWMS 994fdChBkVU50B1 588Cnmqsbn9t6Hs dZrkZvWl3lRWLql hznTg1vxpxSqvKR o0pJukffBy7tplM y00. END SALTPACK MESSAGE.

### CODE REVIEW

**Comment by maxtaco** [comment]
Looks good but yeah, fix up the tests.

**Comment by oconnor663** [comment]
@maxtaco looks like everything's passing. Weren't there some checked in armor blobs in a test somewhere though? I was expecting something to fail...

**Comment by maxtaco** [comment]
See `stream_classifer_test.go`.  Those are the old style armored-messages, which still pass the currently parser.  I'd just reformat them so that they're in the new style.

**Comment by oconnor663** [comment]
We'll need to completely replace those example blobs when we remove the old codepath from the classifier function. Will take care of that in a separate PR.

**Pull request merged**
