### PR TITLE
Linkify underscores in URLs

### PR DESCRIPTION
**Pull request by cjb**
@keybase/react-hackers 

Here's a quick timeboxed fix that makes https://printf.net/foo_bar linkify the whole thing, instead of just the part up to the `_`.  It does this at the cost of no longer italicizing `_https://printf.net_`.  But having an underscore in a URL work seems more important than having italic URLs working.

If you don't like this change (it's my first time changing the peg grammar), let me know and I can at least insert a TODO to clean it up later.

### CODE REVIEW

**Comment by keybase-ci-visdiff** [comment]
The commits 27afe20bcd07...fab06ac6fb0c introduce visual changes on linux. <details><summary>:mag_right: 1 changed</summary>

 * Changed: **Markdown-links** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486137660566-27afe20bcd07-fab06ac6fb0c-linux/Markdown-links-27afe20bcd07.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486137660566-27afe20bcd07-fab06ac6fb0c-linux/Markdown-links-fab06ac6fb0c.png)  
   Markdown-links comparison
</summary>

**Comment by keybase-ci-visdiff** [comment]
The commits 27afe20bcd07...8e141fcb4fa5 introduce visual changes on linux. <details><summary>:mag_right: 1 changed</summary>

 * Changed: **Markdown-links** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486138968001-27afe20bcd07-8e141fcb4fa5-linux/Markdown-links-27afe20bcd07.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1486138968001-27afe20bcd07-8e141fcb4fa5-linux/Markdown-links-8e141fcb4fa5.png)  
   Markdown-links comparison
</summary>

**Comment by chrisnojima** [comment]
I think we should likely fix this so you can mark up an entire link like _http://printf.net_ or whatever and disallow markup within it. Shouldn't be too hard to capture that in the grammar

site note: I understand the link parser has issues and will continue to so i think we should work on it in the context of having tickets (as this is lower priority vs the other stuff in this sprint).

**Comment by cjb** [comment]
Merging 'cause @chromakode and @chrisnojima suggested it.

**Pull request merged**
