### PR TITLE
Add header hoc to search in chat on mobile

### PR DESCRIPTION
**Pull request by MarcoPolo**

### CODE REVIEW

**Comment by cjb** [comment]
@MarcoPolo from 'Add Chat':

screen shot 2017-07-10 at 9 34 18 pm

**Comment by cjb** [comment]
@MarcoPolo I see a large vertical gap (like half the screen) between the conversation header and conversation itself on native in Add Chat on this branch, but I can't tell whether it's something on this branch or something that is now fixed in master but wasn't yet fixed when you branched.

**Comment by MarcoPolo** [comment]
@cjb updated!

**Comment by cjb** [comment]
@MarcoPolo can you merge in please?

**Pull request merged**
