### PR TITLE
Remove badges on folders when you click into them

### PR DESCRIPTION
**Pull request by cjb**
@keybase/react-hackers 

1) Adding or deleting a KBFS favorite was causing a navigateUp() in those sagas.  I moved the navigation outside of the sagas so that we can use them here without navigating.

2) We want to remove the "new" badge on a KBFS folder when you click on it in Folders, but!  Turns out that the way to remove the "new" badge is to add the folder as a favorite, *and* our concept of "Unignore folder" is a mapping onto adding it as a favorite -- that's how you unignore a folder.

So if we added a favorite every time we clicked on a folder, we'd keep unignoring that folder every time we clicked.  So we have to check that it's unignored, and that's it's "new" (to avoid unnecessary server round trips while you're clicking around) before favoriting it.

### CODE REVIEW

**Comment by chrisnojima** [comment]
i don't think we want to favorite it if you go in. i think the core side has a way to set this w/o favoriting

**Comment by cjb** [comment]
@mmaxim, what do you think?

**Comment by mmaxim** [comment]
Favoriting is the current way. With the FS mount, if you go into the folder, you favorite it. Seems reasonable here as well, especially since there is a call to action on the screen you land on.

**Comment by cjb** [comment]
Thanks.  @chrisnojima?

**Pull request merged**
