### PR TITLE
Updater dz2

### PR DESCRIPTION
**Pull request by gabriel**
@keybase/react-hackers

### CODE REVIEW

**Comment by cjb** [comment]
@gabriel let's attach screenshots showing the implementation vs Zeplin to PRs -- I'll do it here -- and use the story in the branch name (gabriel/DESKTOP-580-updatedz2):

update-impl

update1

update2

@cecileboucheron Want to do a review?

**Comment by cecileboucheron** [comment]
My comments below, and I updated the Zeplin screens - some info/colors were not showing up correctly. (Screens here: https://zpl.io/1JMYQG)

- The icons are wrong, they both (Update and Update paused) can be found in the "Icons (2)" sheet in the styleguide: https://zpl.io/1JMYQG
- The What's new text should be black75 (my bad, the transparency was set on the container), and the line height should be 21px, not 14px.
- The What's new container's border should be black10, not grey - not a big deal though. In general all our borders on light backgrounds will be black10 with an exception for list dividers (black5).
- The command line box is using the wrong colors, background should be darkBlue3 (#001b33) and text should be blue3 (#a8d7ff). 
- The "Update automatically" checkbox is using the old style, new component is detailed here: https://zpl.io/ZnImL4.
- On the update paused one, the title is Bold (font-weight: 700;), should be Semibold (600). The size and line-height are good.
- Letter spacing on the Ignore and Force buttons should be 0.3px. Fyi, we're applying this letter-spacing value everywhere, including on the Source Sans Pro texts.

**Comment by gabriel** [comment]
Fixed everything you mentioned except:
- "Letter spacing on the Ignore and Force buttons should be 0.3px"

I use buttons from style guide so when that gets fixed there it will be fixed everywhere.

2016-03-04 at 1 12 pm

**Comment by cecileboucheron** [comment]
Looks great, thank you!! 
Oh, one thing perhaps, looks like the color of the inline commands are wrong now:
screen shot 2016-03-04 at 4 18 08 pm
Should be darkBlue, unless it's a username or a string:
screen shot 2016-03-04 at 4 19 57 pm

**Comment by cjb** [comment]
Let's fix the style guide as we go, I've done it for this one: https://github.com/keybase/client/pull/2226

**Pull request merged**
