### PR TITLE
Protect G.Clock to fix race, add Clock(), SetClock()

### PR DESCRIPTION
**Pull request by patrickxb**
I found a race with the use of GlobalContext.Clock, and then found some inconsistent usage of G.GetClock() vs. G.Clock.

This fixes it all up, protects the clock member, and standardizes on G.Clock(), G.SetClock(...).

There is a slight chance this would have fixed the issue with fakeClock.BlockUntil(1) that we experienced in the rekey tests.

r? @maxtaco

### CODE REVIEW

**Comment by maxtaco** [comment]
Can you go back and see if you can clean up the test and if it works with
this fix?

**Comment by patrickxb** [comment]
Just tried and it had the same problem as yesterday.  

Not spending any more time on it, but I think this PR is valid and fixes races, potential future issues.

**Comment by maxtaco** [comment]
Ok thanks for trying

**Comment by maxtaco** [comment]
👍

**Pull request merged**
