### PR TITLE
Add the ability to add a final pure action creator to consume the res…

### PR DESCRIPTION
**Pull request by MarcoPolo**
…ult of the pureWorker 

@keybase/react-hackers 

@chrisnojima

### CODE REVIEW

**Comment by MarcoPolo** [comment]
I removed the need to pass in a selector, instead the pureWorker can optionally take a second argument for `state: TypedState`.

**Comment by MarcoPolo** [comment]
This should allow us to use more of these `takeEveryPure`s because we can now do something with the result (fire another action).

**Comment by chrisnojima** [comment]
i think i need this so i'm merging

**Comment by MarcoPolo** [comment]
> with passing the state its very close to a thunk signature....
it gets state and not a fn of getState. Very different! One is pure, the other isn't :)

**Pull request merged**
