### PR TITLE
Fix qr code screen for small screens on desktop

### PR DESCRIPTION
**Pull request by chrisnojima**

### CODE REVIEW

**Comment by keybase-ci-visdiff** [comment]
The commits 90cecf4d594d...80dc66478741 introduce visual changes on linux. <details><summary>:mag_right: 2 changed</summary>

 * Changed: **Code_Page-Show_Code_Mobile** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1489441093580-90cecf4d594d-80dc66478741-linux/Code_Page-Show_Code_Mobile-90cecf4d594d.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1489441093580-90cecf4d594d-80dc66478741-linux/Code_Page-Show_Code_Mobile-80dc66478741.png)  
   Code_Page-Show_Code_Mobile comparison
 * Changed: **Code_Page-Show_Code** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1489441093580-90cecf4d594d-80dc66478741-linux/Code_Page-Show_Code-90cecf4d594d.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1489441093580-90cecf4d594d-80dc66478741-linux/Code_Page-Show_Code-80dc66478741.png)  
   Code_Page-Show_Code comparison
</summary>

**Comment by keybase-ci-visdiff** [comment]
The commits 1a5d93b8a2ef...59031cfeacaa introduce visual changes on linux. <details><summary>:mag_right: 2 changed</summary>

 * Changed: **Code_Page-Show_Code_Mobile** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490114609777-1a5d93b8a2ef-59031cfeacaa-linux/Code_Page-Show_Code_Mobile-1a5d93b8a2ef.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490114609777-1a5d93b8a2ef-59031cfeacaa-linux/Code_Page-Show_Code_Mobile-59031cfeacaa.png)  
   Code_Page-Show_Code_Mobile comparison
 * Changed: **Code_Page-Show_Code** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490114609777-1a5d93b8a2ef-59031cfeacaa-linux/Code_Page-Show_Code-1a5d93b8a2ef.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490114609777-1a5d93b8a2ef-59031cfeacaa-linux/Code_Page-Show_Code-59031cfeacaa.png)  
   Code_Page-Show_Code comparison
</summary>

**Comment by chrisnojima** [comment]
@keybase/react-hackers

**Comment by chrisnojima** [comment]
@keybase/react-hackers bump

**Pull request merged**
