### PR TITLE
[ci-skip] Testing Jenkins skip

### PR DESCRIPTION
**Pull request by cjb**

### CODE REVIEW

**Comment by cjb** [comment]
@jzila Thanks, this works, what do you think?

I didn't do proper indentation, mainly because my editors can't seem to auto-indent groovy consistently, so I just invented a two-stop indent.. happy to do whatever you prefer here.

**Comment by jzila** [comment]
The indentation is kind of inconsistent, I'd rather indent everything in the else block by a full 4 spaces.

**Comment by jzila** [comment]
Lgtm otherwise

**Comment by cjb** [comment]
@jzila Thanks, did that I think -- does the new indentation look correct?

**Comment by jzila** [comment]
LGTM. Side note: GitHub's diffing algorithm seems less than ideal :(

**Comment by cjb** [comment]
Yeah :( Thanks!

**Pull request merged**
