### PR TITLE
Revert "App deps"

### PR DESCRIPTION
**Pull request by chrisnojima**
Reverts keybase/client#12212
@keybase/react-hackers inputs were busted

### CODE REVIEW

**Comment by zanderz** [comment]
why are the msi and incidental fix commits reverted too?

**Comment by chrisnojima** [comment]
what do you mean

**Comment by zanderz** [comment]
huh, nvm. The list of your commits makes it look like those were reverted, but the actual changes do not. LGTM!

**Comment by zanderz** [comment]
image
curious

**Pull request merged**
