### PR TITLE
regen emojis

### PR DESCRIPTION
**Pull request by joshblum**
Ran the following commands to generate new emojis that came in through https://github.com/iamcal/emoji-data/compare/c40da192db582084c783e2b6413b150114546ab0..13721cbc2828c3ce8100f8de237ad504c8ba346c

```
yarn
yarn gobuild-emoji
yarn build-emoji
```

### CODE REVIEW

**Review by mmaxim — APPROVED** [review]

**Comment by chrisnojima** [comment]
i don't think we should do this right now, lets discuss

**Comment by buoyad** [comment]
it doesn't render between emojis now but the mapping of name -> emoji is wrong

**Comment by chrisnojima** [comment]
please do not invest time in this pr

**Comment by bytefend** [comment]
"please do not invest time in this pr"

@chrisnojima I don't believe you should get say anymore on stuff like this. You've let the keybase community down enough. Why can't people work on what they want to?

**Comment by joshblum** [comment]
Closed in favor of #25148

**Pull request closed without merging**
