### PR TITLE
[DESKTOP-6888] fs: Disable PDF viewing on all platforms.

### PR DESCRIPTION
**Pull request by jzila**

### CODE REVIEW

**Comment by songgao** [comment]
Actually we could probably just kill that button, now that we have DetectContentType.

**Comment by jzila** [comment]
@songgao: I'm confused. Nowhere else is `PdfView` called, just in the spot I'm removing in this PR.

**Comment by songgao** [comment]
`TextView` uses webview too, and if the source is a PDF, it'd render it. But I just realized we might not be using that button, since the downstream don't use the fileVewType prop. So feel free to merge; I'll make a separate PR to remove those.

**Comment by jzila** [comment]
Test failures are due to `503` errors during `yarn install`. Merging anyway to unblock.

**Pull request merged**
