### PR TITLE
Desktop perf cleanup branch

### PR DESCRIPTION
**Pull request by chrisnojima**
This is a cleanup of https://github.com/keybase/client/pull/6019

### CODE REVIEW

**Comment by keybase-ci-visdiff** [comment]
The commits 97af84f3802c...bec140e86f3e introduce visual changes on linux. <details><summary>:mag_right: 10 changed</summary>

 * Changed: **Folders_TLF-Normal_Public** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488382533640-97af84f3802c-bec140e86f3e-linux/Folders_TLF-Normal_Public-97af84f3802c.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488382533640-97af84f3802c-bec140e86f3e-linux/Folders_TLF-Normal_Public-bec140e86f3e.png)  
   Folders_TLF-Normal_Public comparison
 * Changed: **Chat_Conversations_List-You_Rekey_Selected** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488382533640-97af84f3802c-bec140e86f3e-linux/Chat_Conversations_List-You_Rekey_Selected-97af84f3802c.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488382533640-97af84f3802c-bec140e86f3e-linux/Chat_Conversations_List-You_Rekey_Selected-bec140e86f3e.png)  
   Chat_Conversations_List-You_Rekey_Selected comparison
 * Changed: **Chat_Conversations_List-You_Rekey** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488382533640-97af84f3802c-bec140e86f3e-linux/Chat_Conversations_List-You_Rekey-97af84f3802c.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488382533640-97af84f3802c-bec140e86f3e-linux/Chat_Conversations_List-You_Rekey-bec140e86f3e.png)  
   Chat_Conversations_List-You_Rekey comparison
 * Changed: **Chat_Conversations_List-Selected_Normal** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488382533640-97af84f3802c-bec140e86f3e-linux/Chat_Conversations_List-Selected_Normal-97af84f3802c.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488382533640-97af84f3802c-bec140e86f3e-linux/Chat_Conversations_List-Selected_Normal-bec140e86f3e.png)  
   Chat_Conversations_List-Selected_Normal comparison
 * Changed: **Chat_Conversations_List-Selected_Muted** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488382533640-97af84f3802c-bec140e86f3e-linux/Chat_Conversations_List-Selected_Muted-97af84f3802c.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488382533640-97af84f3802c-bec140e86f3e-linux/Chat_Conversations_List-Selected_Muted-bec140e86f3e.png)  
   Chat_Conversations_List-Selected_Muted comparison
 * Changed: **Chat_Conversations_List-Part_Rekey_Selected** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488382533640-97af84f3802c-bec140e86f3e-linux/Chat_Conversations_List-Part_Rekey_Selected-97af84f3802c.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488382533640-97af84f3802c-bec140e86f3e-linux/Chat_Conversations_List-Part_Rekey_Selected-bec140e86f3e.png)  
   Chat_Conversations_List-Part_Rekey_Selected comparison
 * Changed: **Chat_Conversations_List-Part_Rekey** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488382533640-97af84f3802c-bec140e86f3e-linux/Chat_Conversations_List-Part_Rekey-97af84f3802c.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488382533640-97af84f3802c-bec140e86f3e-linux/Chat_Conversations_List-Part_Rekey-bec140e86f3e.png)  
   Chat_Conversations_List-Part_Rekey comparison
 * Changed: **Chat_Conversations_List-Normal** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488382533640-97af84f3802c-bec140e86f3e-linux/Chat_Conversations_List-Normal-97af84f3802c.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488382533640-97af84f3802c-bec140e86f3e-linux/Chat_Conversations_List-Normal-bec140e86f3e.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488382533640-97af84f3802c-bec140e86f3e-linux/Chat_Conversations_List-Normal.png)
 * Changed: **Chat_Conversations_List-Long_Top** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488382533640-97af84f3802c-bec140e86f3e-linux/Chat_Conversations_List-Long_Top-97af84f3802c.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488382533640-97af84f3802c-bec140e86f3e-linux/Chat_Conversations_List-Long_Top-bec140e86f3e.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488382533640-97af84f3802c-bec140e86f3e-linux/Chat_Conversations_List-Long_Top.png)
 * Changed: **Chat_Conversations_List-Long_Bottom** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488382533640-97af84f3802c-bec140e86f3e-linux/Chat_Conversations_List-Long_Bottom-97af84f3802c.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488382533640-97af84f3802c-bec140e86f3e-linux/Chat_Conversations_List-Long_Bottom-bec140e86f3e.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488382533640-97af84f3802c-bec140e86f3e-linux/Chat_Conversations_List-Long_Bottom.png)
</summary>

**Comment by keybase-ci-visdiff** [comment]
The commits 9a846ca050e1...6cbf913bdcd1 introduce visual changes on linux. <details><summary>:mag_right: 9 changed</summary>

 * Changed: **Folders_TLF-Normal_Public** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488385053689-9a846ca050e1-6cbf913bdcd1-linux/Folders_TLF-Normal_Public-9a846ca050e1.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488385053689-9a846ca050e1-6cbf913bdcd1-linux/Folders_TLF-Normal_Public-6cbf913bdcd1.png)  
   Folders_TLF-Normal_Public comparison
 * Changed: **Chat_Conversations_List-You_Rekey_Selected** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488385053689-9a846ca050e1-6cbf913bdcd1-linux/Chat_Conversations_List-You_Rekey_Selected-9a846ca050e1.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488385053689-9a846ca050e1-6cbf913bdcd1-linux/Chat_Conversations_List-You_Rekey_Selected-6cbf913bdcd1.png)  
   Chat_Conversations_List-You_Rekey_Selected comparison
 * Changed: **Chat_Conversations_List-You_Rekey** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488385053689-9a846ca050e1-6cbf913bdcd1-linux/Chat_Conversations_List-You_Rekey-9a846ca050e1.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488385053689-9a846ca050e1-6cbf913bdcd1-linux/Chat_Conversations_List-You_Rekey-6cbf913bdcd1.png)  
   Chat_Conversations_List-You_Rekey comparison
 * Changed: **Chat_Conversations_List-Selected_Normal** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488385053689-9a846ca050e1-6cbf913bdcd1-linux/Chat_Conversations_List-Selected_Normal-9a846ca050e1.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488385053689-9a846ca050e1-6cbf913bdcd1-linux/Chat_Conversations_List-Selected_Normal-6cbf913bdcd1.png)  
   Chat_Conversations_List-Selected_Normal comparison
 * Changed: **Chat_Conversations_List-Selected_Muted** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488385053689-9a846ca050e1-6cbf913bdcd1-linux/Chat_Conversations_List-Selected_Muted-9a846ca050e1.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488385053689-9a846ca050e1-6cbf913bdcd1-linux/Chat_Conversations_List-Selected_Muted-6cbf913bdcd1.png)  
   Chat_Conversations_List-Selected_Muted comparison
 * Changed: **Chat_Conversations_List-Part_Rekey_Selected** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488385053689-9a846ca050e1-6cbf913bdcd1-linux/Chat_Conversations_List-Part_Rekey_Selected-9a846ca050e1.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488385053689-9a846ca050e1-6cbf913bdcd1-linux/Chat_Conversations_List-Part_Rekey_Selected-6cbf913bdcd1.png)  
   Chat_Conversations_List-Part_Rekey_Selected comparison
 * Changed: **Chat_Conversations_List-Part_Rekey** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488385053689-9a846ca050e1-6cbf913bdcd1-linux/Chat_Conversations_List-Part_Rekey-9a846ca050e1.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488385053689-9a846ca050e1-6cbf913bdcd1-linux/Chat_Conversations_List-Part_Rekey-6cbf913bdcd1.png)  
   Chat_Conversations_List-Part_Rekey comparison
 * Changed: **Chat_Conversations_List-Normal** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488385053689-9a846ca050e1-6cbf913bdcd1-linux/Chat_Conversations_List-Normal-9a846ca050e1.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488385053689-9a846ca050e1-6cbf913bdcd1-linux/Chat_Conversations_List-Normal-6cbf913bdcd1.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488385053689-9a846ca050e1-6cbf913bdcd1-linux/Chat_Conversations_List-Normal.png)
 * Changed: **Chat_Conversations_List-Long_Top** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488385053689-9a846ca050e1-6cbf913bdcd1-linux/Chat_Conversations_List-Long_Top-9a846ca050e1.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488385053689-9a846ca050e1-6cbf913bdcd1-linux/Chat_Conversations_List-Long_Top-6cbf913bdcd1.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488385053689-9a846ca050e1-6cbf913bdcd1-linux/Chat_Conversations_List-Long_Top.png)
</summary>

**Comment by chrisnojima** [comment]
The visdiff is slightly different. the avatar loading behavior shows the background color (correct). Using the new faster usernames causes the comma spacing to be different by a pixel(ish)

**Comment by keybase-ci-visdiff** [comment]
The commits 9a846ca050e1...1d02ea889001 introduce visual changes on linux. <details><summary>:mag_right: 9 changed</summary>

 * Changed: **Folders_TLF-Normal_Public** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488389246133-9a846ca050e1-1d02ea889001-linux/Folders_TLF-Normal_Public-9a846ca050e1.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488389246133-9a846ca050e1-1d02ea889001-linux/Folders_TLF-Normal_Public-1d02ea889001.png)  
   Folders_TLF-Normal_Public comparison
 * Changed: **Chat_Conversations_List-You_Rekey_Selected** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488389246133-9a846ca050e1-1d02ea889001-linux/Chat_Conversations_List-You_Rekey_Selected-9a846ca050e1.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488389246133-9a846ca050e1-1d02ea889001-linux/Chat_Conversations_List-You_Rekey_Selected-1d02ea889001.png)  
   Chat_Conversations_List-You_Rekey_Selected comparison
 * Changed: **Chat_Conversations_List-You_Rekey** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488389246133-9a846ca050e1-1d02ea889001-linux/Chat_Conversations_List-You_Rekey-9a846ca050e1.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488389246133-9a846ca050e1-1d02ea889001-linux/Chat_Conversations_List-You_Rekey-1d02ea889001.png)  
   Chat_Conversations_List-You_Rekey comparison
 * Changed: **Chat_Conversations_List-Selected_Normal** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488389246133-9a846ca050e1-1d02ea889001-linux/Chat_Conversations_List-Selected_Normal-9a846ca050e1.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488389246133-9a846ca050e1-1d02ea889001-linux/Chat_Conversations_List-Selected_Normal-1d02ea889001.png)  
   Chat_Conversations_List-Selected_Normal comparison
 * Changed: **Chat_Conversations_List-Selected_Muted** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488389246133-9a846ca050e1-1d02ea889001-linux/Chat_Conversations_List-Selected_Muted-9a846ca050e1.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488389246133-9a846ca050e1-1d02ea889001-linux/Chat_Conversations_List-Selected_Muted-1d02ea889001.png)  
   Chat_Conversations_List-Selected_Muted comparison
 * Changed: **Chat_Conversations_List-Part_Rekey_Selected** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488389246133-9a846ca050e1-1d02ea889001-linux/Chat_Conversations_List-Part_Rekey_Selected-9a846ca050e1.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488389246133-9a846ca050e1-1d02ea889001-linux/Chat_Conversations_List-Part_Rekey_Selected-1d02ea889001.png)  
   Chat_Conversations_List-Part_Rekey_Selected comparison
 * Changed: **Chat_Conversations_List-Part_Rekey** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488389246133-9a846ca050e1-1d02ea889001-linux/Chat_Conversations_List-Part_Rekey-9a846ca050e1.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488389246133-9a846ca050e1-1d02ea889001-linux/Chat_Conversations_List-Part_Rekey-1d02ea889001.png)  
   Chat_Conversations_List-Part_Rekey comparison
 * Changed: **Chat_Conversations_List-Normal** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488389246133-9a846ca050e1-1d02ea889001-linux/Chat_Conversations_List-Normal-9a846ca050e1.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488389246133-9a846ca050e1-1d02ea889001-linux/Chat_Conversations_List-Normal-1d02ea889001.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488389246133-9a846ca050e1-1d02ea889001-linux/Chat_Conversations_List-Normal.png)
 * Changed: **Chat_Conversations_List-Long_Top** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488389246133-9a846ca050e1-1d02ea889001-linux/Chat_Conversations_List-Long_Top-9a846ca050e1.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488389246133-9a846ca050e1-1d02ea889001-linux/Chat_Conversations_List-Long_Top-1d02ea889001.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488389246133-9a846ca050e1-1d02ea889001-linux/Chat_Conversations_List-Long_Top.png)
</summary>

**Comment by chrisnojima** [comment]
retest this please

**Comment by chrisnojima** [comment]
(jenkins)

**Comment by keybase-ci-visdiff** [comment]
The commits 43e79c91ac1a...1d02ea889001 introduce visual changes on linux. <details><summary>:mag_right: 9 changed</summary>

 * Changed: **Folders_TLF-Normal_Public** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488396113288-43e79c91ac1a-1d02ea889001-linux/Folders_TLF-Normal_Public-43e79c91ac1a.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488396113288-43e79c91ac1a-1d02ea889001-linux/Folders_TLF-Normal_Public-1d02ea889001.png)  
   Folders_TLF-Normal_Public comparison
 * Changed: **Chat_Conversations_List-You_Rekey_Selected** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488396113288-43e79c91ac1a-1d02ea889001-linux/Chat_Conversations_List-You_Rekey_Selected-43e79c91ac1a.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488396113288-43e79c91ac1a-1d02ea889001-linux/Chat_Conversations_List-You_Rekey_Selected-1d02ea889001.png)  
   Chat_Conversations_List-You_Rekey_Selected comparison
 * Changed: **Chat_Conversations_List-You_Rekey** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488396113288-43e79c91ac1a-1d02ea889001-linux/Chat_Conversations_List-You_Rekey-43e79c91ac1a.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488396113288-43e79c91ac1a-1d02ea889001-linux/Chat_Conversations_List-You_Rekey-1d02ea889001.png)  
   Chat_Conversations_List-You_Rekey comparison
 * Changed: **Chat_Conversations_List-Selected_Normal** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488396113288-43e79c91ac1a-1d02ea889001-linux/Chat_Conversations_List-Selected_Normal-43e79c91ac1a.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488396113288-43e79c91ac1a-1d02ea889001-linux/Chat_Conversations_List-Selected_Normal-1d02ea889001.png)  
   Chat_Conversations_List-Selected_Normal comparison
 * Changed: **Chat_Conversations_List-Selected_Muted** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488396113288-43e79c91ac1a-1d02ea889001-linux/Chat_Conversations_List-Selected_Muted-43e79c91ac1a.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488396113288-43e79c91ac1a-1d02ea889001-linux/Chat_Conversations_List-Selected_Muted-1d02ea889001.png)  
   Chat_Conversations_List-Selected_Muted comparison
 * Changed: **Chat_Conversations_List-Part_Rekey_Selected** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488396113288-43e79c91ac1a-1d02ea889001-linux/Chat_Conversations_List-Part_Rekey_Selected-43e79c91ac1a.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488396113288-43e79c91ac1a-1d02ea889001-linux/Chat_Conversations_List-Part_Rekey_Selected-1d02ea889001.png)  
   Chat_Conversations_List-Part_Rekey_Selected comparison
 * Changed: **Chat_Conversations_List-Part_Rekey** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488396113288-43e79c91ac1a-1d02ea889001-linux/Chat_Conversations_List-Part_Rekey-43e79c91ac1a.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488396113288-43e79c91ac1a-1d02ea889001-linux/Chat_Conversations_List-Part_Rekey-1d02ea889001.png)  
   Chat_Conversations_List-Part_Rekey comparison
 * Changed: **Chat_Conversations_List-Normal** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488396113288-43e79c91ac1a-1d02ea889001-linux/Chat_Conversations_List-Normal-43e79c91ac1a.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488396113288-43e79c91ac1a-1d02ea889001-linux/Chat_Conversations_List-Normal-1d02ea889001.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488396113288-43e79c91ac1a-1d02ea889001-linux/Chat_Conversations_List-Normal.png)
 * Changed: **Chat_Conversations_List-Long_Top** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488396113288-43e79c91ac1a-1d02ea889001-linux/Chat_Conversations_List-Long_Top-43e79c91ac1a.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488396113288-43e79c91ac1a-1d02ea889001-linux/Chat_Conversations_List-Long_Top-1d02ea889001.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488396113288-43e79c91ac1a-1d02ea889001-linux/Chat_Conversations_List-Long_Top.png)
</summary>

**Pull request merged**
