### PR TITLE
Move 'revoke' to 'pgp revoke'

### PR DESCRIPTION
**Pull request by patrickxb**
r? @maxtaco @oconnor663

### CODE REVIEW

**Comment by maxtaco** [comment]
CAn you also make a note in `keybase gpg help` ?

**Comment by maxtaco** [comment]
Otherwise, :+1:

**Comment by oconnor663** [comment]
:ship:

**Comment by patrickxb** [comment]
Is the note ok?

**Comment by maxtaco** [comment]
I'd also add that it won't do a PGP-style revoke.

**Comment by maxtaco** [comment]
(that might be a fear people have.  after that, good with me...)

**Pull request merged**
