### PR TITLE
add a new RPC for making generic API server requests CORE-3245

### PR DESCRIPTION
**Pull request by mmaxim**
@maxtaco r?

### CODE REVIEW

**Comment by maxtaco** [comment]
👍 

@cjb, @mmaxim needs to wait for *7* CI successes, right?

**Comment by cjb** [comment]
retest this please

**Comment by cjb** [comment]
yep! they're building now.

**Comment by cjb** [comment]
There's an uncommitted protocol change -- this is because we changed the protocol generation tool since your PR, rather than because of a change you made.

**Pull request merged**
