### PR TITLE
visdiff: Include commit range checked in comment

### PR DESCRIPTION
**Pull request by chromakode**
:eyeglasses: @keybase/react-hackers

### CODE REVIEW

**Comment by keybase-ci-visdiff** [comment]
:mag_right: The commits 09ad1d1059a4...bd1afb98fe36 introduced some visual changes:
 * Changed: **Profile-Changed** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1466036082266-09ad1d1059a4-bd1afb98fe36/Profile-Changed-09ad1d1059a4.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1466036082266-09ad1d1059a4-bd1afb98fe36/Profile-Changed-bd1afb98fe36.png)  
   Profile-Changed comparison

**Comment by keybase-ci-visdiff** [comment]
:mag_right: The commits 09ad1d1059a4...106cf5daba19 introduced some visual changes:
 * Changed: **Profile-Changed** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1466036934844-09ad1d1059a4-106cf5daba19/Profile-Changed-09ad1d1059a4.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1466036934844-09ad1d1059a4-106cf5daba19/Profile-Changed-106cf5daba19.png)  
   Profile-Changed comparison

**Comment by cjb** [comment]
:thumbsup: % reverting the demo change

**Comment by keybase-ci-visdiff** [comment]
:mag_right: The commits ef58be1a3462...d08aa62bd3c3 introduced some visual changes:
 * Changed: **Profile-Changed** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1466100322258-ef58be1a3462-d08aa62bd3c3/Profile-Changed-ef58be1a3462.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1466100322258-ef58be1a3462-d08aa62bd3c3/Profile-Changed-d08aa62bd3c3.png)  
   Profile-Changed comparison

**Pull request merged**
