### PR TITLE
Extended config again windows

### PR DESCRIPTION
**Pull request by MarcoPolo**
@keybase/react-hackers 

Simply try getting the extended config and try one more time if we failed the first time.

### CODE REVIEW

**Comment by chrisnojima** [comment]
Does this actually work and if so can we just delay the first call if it's mostly a small timing issue?

**Comment by MarcoPolo** [comment]
yes tested it and it worked. (tested using `devEdit(['config','extendedConfig'], null)`)

Delaying the call would probably make it less rare, and but it would still be racey.

I think this makes the most sense because we are getting the information when we need it (if we didn't have it to begin with).

**Comment by MarcoPolo** [comment]
also handles the case where kbfs was down for some reason, and then brought back up while the app is still alive. It'll fail before kbfs is up, and after it'll succeed.

**Comment by chrisnojima** [comment]
Sure not saying we should remove the catch just wonder if delaying it 1
second makes it work 90% of the time

**Comment by MarcoPolo** [comment]
@chrisnojima bump

**Comment by chrisnojima** [comment]
👍

**Pull request merged**
