### PR TITLE
Drag and drop support

### PR DESCRIPTION
**Pull request by chrisnojima**
This adds drag drop support to the conversation

I had to make this a stateful component so the diff is kinda crazy, w=1 might help

### CODE REVIEW

**Comment by chrisnojima** [comment]
@keybase/react-hackers

**Comment by keybase-ci-visdiff** [comment]
The commits 0d05a46afa42...02e0ce15eab7 introduce visual changes on linux. <details><summary>:mag_right: 1 new</summary>

 * Added: **Colors-blue_5_60_rgba_50_159_254_0_6**  
   Colors-blue_5_60_rgba_50_159_254_0_6 rendered
</summary>

**Comment by chrisnojima** [comment]
@keybase/react-hackers bump

**Comment by keybase-ci-visdiff** [comment]
The commits 20b01774c618...b99b22221c58 introduce visual changes on linux. <details><summary>:mag_right: 1 new</summary>

 * Added: **Colors-blue_5_60_rgba_50_159_254_0_6**  
   Colors-blue_5_60_rgba_50_159_254_0_6 rendered
</summary>

**Pull request merged**
