### PR TITLE
The commapocalypse

### PR DESCRIPTION
**Pull request by chromakode**
The first two commits implement comma-dangle,

https://github.com/keybase/client/commit/1cdd7a6bf3b10036f778bc86baf4f841ed7fcd4d,
https://github.com/keybase/client/commit/a6addab71ac3308c74d7359cbfce5317f9ad636b,

I added `shared/constants/types/keybase-v1.js` to the `.eslintignore` because the code generator doesn't output trailing commas. I started working on updating the scripts to emit trailing commas, but then I realized we're already ignoring lint errors on the `/protocol` directory. If it's desirable to lint `keybase-v1.js`, I think the changes will be pretty trivial.

The last commit is a run of `eslint --fix .` on the current codebase. Once this is reviewed, let's find a time to merge it in this sprint when it'll create the fewest merge conflicts,

:eyeglasses: @keybase/react-hackers,

,

### CODE REVIEW

**Comment by maxtaco** [comment]
The solution to this problem is CoffeeScript, in which commas are optional-ish

**Comment by cjb** [comment]
:thumbsup:, but I thought we were gonna wait for some of (the largest of) our 10 open PRs to be merged in first, to avoid conflicts and missed changes

**Comment by cjb** [comment]
reiterating my :thumbsup:, :ship: :shipit:

**Comment by chromakode** [comment]
@keybase/react-hackers 

The commapocalypse is nigh! Here is how to update any outstanding PRs you have to automatically resolve merge conflicts:

## Updating existing branches

```
git fetch origin
git checkout yourbranch
```

Update your branch to the last commit before the comma style update. Resolve any normal merge conflicts.

```
git rebase origin/pre-trailing-comma
```

Resolve any outstanding eslint issues before proceeding.

```
./desktop/node_modules/.bin/eslint --cache .
```

Let's check out a new branch on which to stage this work.

```
git branch yourbranch-pre-commas  # used for sanity check below
git checkout -b yourbranch-commas
```

Rebase your branch after the commas update, throwing out conflicts caused by the reformatting, and running `eslint --fix` (you may need to change the path for your specific setup) to amend each commit.

```
git rebase -i origin/post-trailing-comma -X theirs -x "./desktop/node_modules/.bin/eslint --cache --fix . && git add -u && git commit --amend -C HEAD"
```

After this churns for a minute or two, your branch should now contain code that fits the style guide and cleanly merges against `master`. Your commits have been rebased on top of the comma style update, but you may want to rebase on to `master` again to pull in any new changes.

## Sanity check

It's a good idea to eyeball the resulting commits, but there's a simple way to check that this automatic process hasn't changed anything besides comma styling. If the result of running `eslint --fix` on your branch *before* the rebase is the same as after the rebase, we can be assured that the rebase conflict resolution didn't introduce any other changes.

```
git checkout yourbranch-pre-commas
./desktop/node_modules/.bin/eslint --cache --fix .
git diff yourbranch-commas
```

If there's no diff, you should be good to go! :ok_hand: Continue developing on the "yourbranch-commas" branch and force push it on top of your existing PR branch.

**Comment by keybase-ci-visdiff** [comment]
:mag_right: The commits 97dbe3edccac...83d61c5cef04 introduced some visual changes:
 * Changed: **Profile-Changed** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1466202413907-97dbe3edccac-83d61c5cef04/Profile-Changed-97dbe3edccac.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1466202413907-97dbe3edccac-83d61c5cef04/Profile-Changed-83d61c5cef04.png)  
   Profile-Changed comparison

**Comment by keybase-ci-visdiff** [comment]
:mag_right: The commits 0026806daa99...739712b4a53e introduced some visual changes:
 * Changed: **Profile-Changed** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1466205263574-0026806daa99-739712b4a53e/Profile-Changed-0026806daa99.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1466205263574-0026806daa99-739712b4a53e/Profile-Changed-739712b4a53e.png)  
   Profile-Changed comparison
 * Changed: **Device_Name-Waiting** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1466205263574-0026806daa99-739712b4a53e/Device_Name-Waiting-0026806daa99.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1466205263574-0026806daa99-739712b4a53e/Device_Name-Waiting-739712b4a53e.png)  
   Device_Name-Waiting comparison

**Pull request merged**
