### PR TITLE
expose proof state in proof checking

### PR DESCRIPTION
**Pull request by maxtaco**

### CODE REVIEW

**Comment by maxtaco** [comment]
r? @patrickxb 

@chrisnojima  needs this plumbed through for doing proofs in the UI

**Comment by patrickxb** [comment]
LGTM

**Comment by patrickxb** [comment]
./prove_check_test.go:63: assignment count mismatch: 3 = 4

**Comment by patrickxb** [comment]
LEBTM (looks even better to me)

**Comment by maxtaco** [comment]
Sorry I was letting CI do the testing since my laptop is quite puny

**Pull request merged**
