### PR TITLE
<Input> errors should use DZ2 red, not DZ1 red

### PR DESCRIPTION
**Pull request by cjb**
@keybase/react-hackers

### CODE REVIEW

**Comment by chrisnojima** [comment]
:+1:

**Comment by cjb** [comment]
screenshot from 2016-03-03 16-09-33

**Comment by cjb** [comment]
screenshot from 2016-03-03 16-12-29

**Comment by cecileboucheron** [comment]
The color is good, can we move it down a little bit though? Ideally the spacing above and below the checkbox should be the same. We can push up the checkbox if necessary.
Also the period at the end of the sentence is missing.

**Comment by cjb** [comment]
screenshot from 2016-03-03 16-27-37

**Comment by cjb** [comment]
@cecileboucheron Fixed, take another look.

**Comment by cecileboucheron** [comment]
Perfecto!

**Pull request merged**
