### PR TITLE
Electron 4.0.1

### PR DESCRIPTION
**Pull request by chrisnojima**
- [x] kbelectron keybase pub
- [x] windows
- [ ] linux
- [x] os x

### CODE REVIEW

**Comment by zanderz** [comment]
```
Downloading tmp-17176-0-electron-v4.0.0-win32-x64.zip
Error: GET https://kbelectron.keybase.pub/electron-download/v4.0.0/electron-v4.0.0-win32-x64.zip returned 404
```

**Comment by chrisnojima** [comment]
this is expected. this is a WIP (aka don't review this) and i didn't upload the binary to kbelectron

**Comment by zanderz** [comment]
oh whoops

**Comment by chrisnojima** [comment]
@zanderz lets try this now

**Comment by zanderz** [comment]
sanity checks OK, with widget and system toast and everything

**Comment by chrisnojima** [comment]
k works for me on os x
@keybase/react-hackers lets get this in soon

**Pull request merged**
