### PR TITLE
remove store dumping in action logger

### PR DESCRIPTION
**Pull request by chrisnojima**
@keybase/react-hackers @MarcoPolo our logging really lags out the electron process since its all async. we have action logging turned on for everyone always, let's make this lighter weight. i think we can see whats going on with just the actions for most cases so i'm whittling this down to just that for now. thoughts?

### CODE REVIEW

**Comment by cjb** [comment]
@chromakode Any idea what happened with this Travis PR build?

**Comment by MarcoPolo** [comment]
Hmmm I don't think this is the right solution. Looking at the store is pretty helpful when I look at debug logs.

If it's really slowing everything down we can print the diffs of before and after in the state (which might even be more useful).

**Comment by keybase-ci-visdiff** [comment]
:mag_right: No visual changes found as a result of these commits.

**Comment by chrisnojima** [comment]
the above was just to discuss, closing this for now.

**Pull request closed without merging**
