### PR TITLE
Add social assertion info to displayTLFCreateWithInvite

### PR DESCRIPTION
**Pull request by MarcoPolo**
@patrickxb 

Just added the social assertion info to be passed into the UI so we can be smart about the service name.

### CODE REVIEW

**Comment by patrickxb** [comment]
LGTM, but @maxtaco just made some changes to social assertions, so let's clear it with him as well to make sure as I'm not familiar with his changes.

**Comment by maxtaco** [comment]
My changes are orthogonal

**Comment by patrickxb** [comment]
Cool, then 🚢

**Comment by keybase-ci-visdiff** [comment]
:mag_right: These commits introduced some visual changes:
 * Changed: **Tracker-Nonuser_No_Link_Public** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1465247929385-b0e8ff3565a3-afcb097f8b6d/Tracker-Nonuser_No_Link_Public-b0e8ff3565a3.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1465247929385-b0e8ff3565a3-afcb097f8b6d/Tracker-Nonuser_No_Link_Public-afcb097f8b6d.png)  
   Tracker-Nonuser_No_Link_Public comparison
 * Changed: **Tracker-Nonuser_No_Link_Private** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1465247929385-b0e8ff3565a3-afcb097f8b6d/Tracker-Nonuser_No_Link_Private-b0e8ff3565a3.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1465247929385-b0e8ff3565a3-afcb097f8b6d/Tracker-Nonuser_No_Link_Private-afcb097f8b6d.png)  
   Tracker-Nonuser_No_Link_Private comparison
 * Changed: **Tracker-Nonuser_Link** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1465247929385-b0e8ff3565a3-afcb097f8b6d/Tracker-Nonuser_Link-b0e8ff3565a3.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1465247929385-b0e8ff3565a3-afcb097f8b6d/Tracker-Nonuser_Link-afcb097f8b6d.png)  
   Tracker-Nonuser_Link comparison

**Comment by keybase-ci-visdiff** [comment]
:mag_right: These commits introduced some visual changes:
 * Changed: **Tracker-Nonuser_No_Link_Public** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1465329586868-da4da2eef1ea-bbe3a1ea7523/Tracker-Nonuser_No_Link_Public-da4da2eef1ea.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1465329586868-da4da2eef1ea-bbe3a1ea7523/Tracker-Nonuser_No_Link_Public-bbe3a1ea7523.png)  
   Tracker-Nonuser_No_Link_Public comparison
 * Changed: **Tracker-Nonuser_No_Link_Private** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1465329586868-da4da2eef1ea-bbe3a1ea7523/Tracker-Nonuser_No_Link_Private-da4da2eef1ea.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1465329586868-da4da2eef1ea-bbe3a1ea7523/Tracker-Nonuser_No_Link_Private-bbe3a1ea7523.png)  
   Tracker-Nonuser_No_Link_Private comparison
 * Changed: **Tracker-Nonuser_Link** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1465329586868-da4da2eef1ea-bbe3a1ea7523/Tracker-Nonuser_Link-da4da2eef1ea.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1465329586868-da4da2eef1ea-bbe3a1ea7523/Tracker-Nonuser_Link-bbe3a1ea7523.png)  
   Tracker-Nonuser_Link comparison

**Comment by keybase-ci-visdiff** [comment]
:mag_right: These commits introduced some visual changes:
 * Changed: **Tracker-Nonuser_No_Link_Public** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1465354160224-da4da2eef1ea-bbe3a1ea7523/Tracker-Nonuser_No_Link_Public-da4da2eef1ea.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1465354160224-da4da2eef1ea-bbe3a1ea7523/Tracker-Nonuser_No_Link_Public-bbe3a1ea7523.png)  
   Tracker-Nonuser_No_Link_Public comparison
 * Changed: **Tracker-Nonuser_No_Link_Private** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1465354160224-da4da2eef1ea-bbe3a1ea7523/Tracker-Nonuser_No_Link_Private-da4da2eef1ea.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1465354160224-da4da2eef1ea-bbe3a1ea7523/Tracker-Nonuser_No_Link_Private-bbe3a1ea7523.png)  
   Tracker-Nonuser_No_Link_Private comparison
 * Changed: **Tracker-Nonuser_Link** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1465354160224-da4da2eef1ea-bbe3a1ea7523/Tracker-Nonuser_Link-da4da2eef1ea.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1465354160224-da4da2eef1ea-bbe3a1ea7523/Tracker-Nonuser_Link-bbe3a1ea7523.png)  
   Tracker-Nonuser_Link comparison

**Comment by cjb** [comment]
This has (separate) runs that passed on each of linux/osx/win, so I think you can just merge it now.

**Pull request merged**
