### PR TITLE
Disable V3 support for non-admin

### PR DESCRIPTION
**Pull request by joshblum**
cc @mmaxim @chrisnojima if we end up merging anything else into the current release let's get this in as well for better error handling

### CODE REVIEW

**Comment by mmaxim** [comment]
@malgorithms might have an opinion here, I personally have never been too concerned about what kind of error messages old clients get if they don't support something. I think Chris does care though, so might be worth discussing tomorrow morning.

**Comment by oconnor663** [comment]
Is there a way to disable it based on the message boxed version itself? LGTM in general, either way.

**Comment by joshblum** [comment]
are only exploding v3 or all new messages @oconnor663 ?

**Comment by oconnor663** [comment]
It should be only exploding messages: https://github.com/keybase/client/blob/master/go/chat/boxer.go#L1149-L1162

**Comment by joshblum** [comment]
ok cool i'll leave as is for now. i think we should merge in case we do another mobile release before we enable ephemeral support, if clients make it to that version they will have the better error msg experience. @malgorithms ?

**Comment by malgorithms** [comment]
> ok cool i'll leave as is for now. i think we should merge in case we do another mobile release before we enable ephemeral support, if clients make it to that version they will have the better error msg experience. @malgorithms ?

Unless I'm missing a reason not to do this, it sounds like only an improvement? So sounds good to me!

> @malgorithms might have an opinion here, I personally have never been too concerned about what kind of error messages old clients get if they don't support something.

My only concern is that - whenever possible - people should learn an erorr is because they're out of date. Not due to a server or client bug.   Exact wording otherwise doesn't matter...

he kinds of people who end up out of date typically either (1) turn the current device on rarely (a variety of reasons for that), (2) have ignored updates for some reason (either non-tech-savvy OR a security freak), or (3) are on linux. in each of these cases, if they get an error that feels like an app bug -- you know "couldn't unbox X" or "bad sigchain link" or whatever, that really may not make someone think "oh, it's my fault. maybe my app is out of date."

I understand sometimes it's hard to plan for these things, but I continue to think we should try to plan for them. If someone's app is out of date in a broken way we should expect to be able to let them know.

And I think this is especially true considering how fast we've been making old versions incompatible. We're doing things like making 2 month old versions of our app break, which is pretty extreme iteration.

**Pull request merged**
