### PR TITLE
remove unused react native libraries

### PR DESCRIPTION
**Pull request by mmaxim**
Removed libwebsocket, libvibration, and libgeolocation, which was enough to get things to build again.

cc @maxtaco

### CODE REVIEW

**Comment by mmaxim** [comment]
At this time I have no idea how to fix Go to make this work. If we are aiming to release this during this week, we probably need a quick change.

**Comment by chrisnojima** [comment]
Let's discuss in slack. I'm very worried about this

**Comment by maxtaco** [comment]
@chrisnojima it seems the issue is that our Go libraries have close to 16MB of text, and that breaks the "jump island" algorithm the linker uses.  But making the compiled Go code smaller is a huge undertaking, and we're not even sure it will work.  It's a shit situation

**Comment by chrisnojima** [comment]
gunna have to investigate. this is a very short term fix, we're going to just run into this again

**Comment by mmaxim** [comment]
We can talk about a longer term fix, I am not sure what else we can do though for the next release.

**Pull request closed without merging**
