### PR TITLE
Use keybase/go-codec/codec instead of ugorji/go/codec

### PR DESCRIPTION
**Pull request by akalin-keybase**
Update vendored saltpack and go-framed-msgpack-rpc,
so that they use keybase/go-codec/codec, too.

Also vendor github.com/cenkalti/backoff, which is now
a dependency of go-framed-msgpack-rpc.

Also make govendor ignore the solaris build tag because
of go-isatty.

### CODE REVIEW

**Comment by maxtaco** [comment]
Are we sucking in all of `sys/unix` just for `go-isatty`?

**Comment by akalin-keybase** [comment]
I guess so! :/

**Comment by maxtaco** [comment]
See edit BTW ^

**Comment by akalin-keybase** [comment]
Ah, you're right...seems like govendor doesn't know about build flags. Will remove.

**Comment by maxtaco** [comment]
Lots of Perl code in there :)

**Comment by akalin-keybase** [comment]
Okay, PTAL!

**Comment by maxtaco** [comment]
:+1:

**Comment by akalin-keybase** [comment]
(Also made govendor ignore solaris build tag.)

**Pull request closed without merging**
