### PR TITLE
Move some team stuff to teams protocol

### PR DESCRIPTION
**Pull request by mlsteele**
If anyone cares that the Go package is called `team` and the protocol is called `teams` now would be a good time to bring it up.
cc @patrickxb

### CODE REVIEW

**Comment by keybase-ci-visdiff** [comment]
The commits eddaf2ea2630...ed804fc618e8 introduce visual changes on linux. <details><summary>:mag_right: 1 changed</summary>

 * Changed: **Markdown-emoji** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1495556164199-eddaf2ea2630-ed804fc618e8-linux/Markdown-emoji-eddaf2ea2630.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1495556164199-eddaf2ea2630-ed804fc618e8-linux/Markdown-emoji-ed804fc618e8.png)  
   Markdown-emoji comparison
</summary>

**Comment by maxtaco** [comment]
I'd like them to be the same, thanks for mentioning it!

**Comment by mlsteele** [comment]
ah shoot, I merged this but forgot it hadn't been 👍 'd. I'm going to leave it in and make sure someone takes a look after the fact.

**Comment by patrickxb** [comment]
Looks fine to me

**Pull request merged**
