### PR TITLE
Shell completion

### PR DESCRIPTION
**Pull request by timfallmk**
A simple WIP PR to enable basic shell completion using `urfave/cli`'s built in [shell completion](https://github.com/urfave/cli#bash-completion) function.

The method has two parts:
 - An "autocomplete" script that, when sourced ([source is here](https://github.com/urfave/cli/blob/master/autocomplete/bash_autocomplete)), adds the completion to the shell
- A `--generate-<shell>-completion` function that outputs the inline subcommands for the above script.

I've enabled the second part (it's just one line), but the first would need to be distributed in some way along with the CLI. Since I don't know your install methods, any insight here would be appreciated.

For an example of how this can be done in practice, see [here](https://github.com/vapor-ware/synse-cli/blob/master/utils/shellcompletion.go)

If approved, `zsh` completion can easily be added along with `bash`.

References:
 - https://github.com/keybase/keybase-issues/issues/147
 - https://github.com/keybase/keybase-issues/issues/519

### CODE REVIEW

**Comment by timfallmk** [comment]
bump?

**Comment by patrickxb** [comment]
@timfallmk thanks for this PR.  

Shell completion would be nice.  Do you know if there's a way to support subcommands?

I see that (if installed) this would complete `keybase t` + `TAB` to `keybase team` but it doesn't look like it will do `keybase team add` + `TAB` to `keybase team add-member`.

**Comment by timfallmk** [comment]
@patrickxb That's a good point.

The default [completion command](https://github.com/urfave/cli/blob/master/help.go#L156) is pretty limited. It _should_ be pretty trivial to write a completion function that descends through any subcommand trees as well. If that's of interest I'd be happy to look into it.

**Comment by timfallmk** [comment]
@patrickxb Actually I might be wrong. It's possible that this works as intended already. I'll double check and report back.

**Comment by timfallmk** [comment]
🆙

**Comment by patrickxb** [comment]
That's cool.

When I tried it, it only generated completions for the root commands.  Can you show me the generated file with the subcommands?

**Comment by timfallmk** [comment]
@patrickxb Source pulled directly from [here](https://github.com/urfave/cli#bash-completion). Added to `~/.bash_profile` via

```shell
PROG=keybase source /path/to/bash_autocomplete
```
keybase autocomplete 2

**Comment by timfallmk** [comment]
If this isn't of any interesting, I'll close out the PR.

**Comment by espoelstra** [comment]
A slightly easier way to get the completion per the CLI library's directions now that the `--generate-bash-completion` has been merged is below.

```
wget https://github.com/urfave/cli/raw/master/autocomplete/bash_autocomplete -O keybase.completion
sudo mv keybase.completion /etc/bash_completion.d/keybase
# '. ~/some-file' and 'source ~/some-file' are equivalent, but 'source' only exists in Bash
. /etc/bash_completion.d/keybase
# or source your .bashrc
# . ~/.bashrc
```

The reason I prefer to use the `/etc/bash_completion.d/` directory rather than `/usr/share/bash-completion/` is that `/etc` is for user configurations, while `/usr/share` is typically for files provided by packages. Just try `ls /etc/bash_completion.d/` and `ls /usr/share/bash-completion` to see the evidence of this.

**Comment by jasonkarns** [comment]
Not for homebrew users of bash-completion2: drop the keybase script in `/usr/local/etc/bash_completion.d` and it'll automatically be sourced without modification to your bashrc.

**Pull request merged**
