### PR TITLE
Process kill after delay in case Electron quit fails

### PR DESCRIPTION
**Pull request by gabriel**
I've seen a browser crash on exit leave the app in a bad state (with no services).
We can use process.exit() after a delay as a failsafe.

### CODE REVIEW

**Comment by gabriel** [comment]
@MarcoPolo 

cc @keybase/react-hackers

**Comment by gabriel** [comment]
I tested this by manually (by making app.exit no op)...

**Comment by MarcoPolo** [comment]
What's the difference between process.exit and app.exit?

**Comment by gabriel** [comment]
`app.exit` calls into Electron: https://github.com/electron/electron/blob/master/atom/browser/browser.cc#L51

If there is an error trying to shutdown, it won't necessarily exit. I'm pretty sure this is what happened to coyne when his browser crashed on exit.

`process.exit` tells node to terminate the process:
https://nodejs.org/api/process.html#process_process_exit_code

We might even prefer calling `process.exit` instead of `app.exit` since there isn't anything critical to cleanup on exit in our app (e.g. services)?

**Comment by gabriel** [comment]
Also I think you've seen multiple popups running cause `app.exit` to fail right?

These do seem like Electron bugs that we could look into fixing, but we could avoid all this and `process.exit` anyway?

**Comment by gabriel** [comment]
OK, I did some testing and sanity checking and I think this is the right thing to do.

Unfortunately `app.exit` isn't guaranteed to exit (which seems like a bug in Electron), so I think for now until that gets better, doing `process.exit` after a delay is ok.

I tested on linux and windows (simulating `app.exit` no-oping by commenting that out, so the process exit runs) and nothing bad happens.

**Comment by MarcoPolo** [comment]
:shipit:

**Pull request merged**
