### PR TITLE
Ship and install git-remote-keybase on macOS

### PR DESCRIPTION
**Pull request by cjb**
@keybase/react-hackers 

This needs more testing, and there's a FIXME line to swap out before hitting the merge button.

This PR:

* builds git-remote-keybase as part of doing a KBFS build (the code lives in the KBFS repo)
* codesigns it
* copies it into the Keybase.app/SharedSupport/bin/ dir inside the bundle being created
* checks that the codesign validates
* bumps the installer version
* asks the installer/helper to install /usr/local/bin/git-remote-keybase at the same time it's installing /usr/local/bin/keybase
* tells the build scripts to pull this newer version of the installer

The installer, unlike almost everything else, is not actually *built* as part of the build process.  It's just downloaded from a tarball on S3.  It's meant to be built, signed and uploaded locally.  That's why this PR bumps the installer version number.  I'm able to build/sign/upload it on my laptop.

It looks like there are changes that have been merged to the macOS installer but not built/shipped (!) that were merged as part of the split installer merge.  That might explain some of the bugs we've been seeing -- perhaps they're fixed with this code that's been merged but not shipped -- but it also means we should be extra cautious about these changes, since they're larger than we expected.

### CODE REVIEW

**Comment by maxtaco** [comment]
There's also the Sourcetree issue to content with: https://keybase.atlassian.net/browse/DESKTOP-5047

**Comment by maxtaco** [comment]
@chrisnojima: properly functioning software like Github Desktop and regular git seem to respect `$PATH`, but Sourcetree doesn't (as mentioned above). So dropping a symlink in `/Applications/Xcode.app/Contents/Developer/usr/libexec/git-core` will fix Sourcetree if you run with system git. It won't fix Sourcetree under the default settings (embedded git), which needs a symlink dropped in `/Applications/Sourcetree.app/Contents/Resources/git_local/libexec/git-core/`. @cjb's point that these symlinks will disappear after an upgrade is the biggest problem. Same goes for if these packages are installed after keybase.

**Comment by chrisnojima** [comment]
yeah thats the git exec stuff i was mentioning. ok lets ignore that entire path for now and just do the path thing

**Comment by chrisnojima** [comment]
ok so, this code looks fine to me. lets remove the todo and build and get this ready for testing through our regular tooling

**Comment by cjb** [comment]
@chrisnojima Pushed another commit (4d7cd57d).. the ObjC installer code is only called when there was an error reported by the Go installer code, so we have to try to install from Go first.

**Pull request merged**
