### PR TITLE
WIP: tracker shows red on refollow

### PR DESCRIPTION
**Pull request by chrisnojima**
@keybase/react-hackers this updates the state from a warning to normal which causes it to be red. we should discuss fixing up these types of problems in a better way by doing a real re-identify and bookkeeping the previous state or something instead of synthesizing the new state

### CODE REVIEW

**Comment by MarcoPolo** [comment]
I vaguely remember removing this a while ago because a re-identify was suppose to do this anyways, and if it didn't that was a bug.

Why aren't we doing a re-id?

**Comment by chrisnojima** [comment]
unclear. i think we want to clean this up when we saga-ize the tracker actions. should we just get this 1 liner in?

**Comment by MarcoPolo** [comment]
A note from the meeting:

This might be related to us not clearing pending identifies when we finish a tracker popup id.

**Comment by chrisnojima** [comment]
Investigating this further. we're not handling user/tracking changed correctly. also core is not sending userchanged on untrack (ticketed). we have timing issues w/ how we sign up for notify so that's being cleaned up as well.

**Comment by chrisnojima** [comment]
replaced by https://github.com/keybase/client/pull/4436

**Pull request closed without merging**
