### PR TITLE
Ensure /etc/paths.d (on Sierra)

### PR DESCRIPTION
**Pull request by gabriel**
It's possible that /usr/local/bin and /etc/paths.d are not available.
On fresh Sierra install /etc/paths.d wasn't available.

In this case we should log warning instead of erroring otherwise we'll show this error on every app start.

In the future, we should show a UI to tell the user (once?) that they can manually add keybase to their path.

### CODE REVIEW

**Comment by gabriel** [comment]
@keybase/react-hackers

**Comment by chrisnojima** [comment]
In settings we can add some page to install the cli. @malgorithms ?

**Comment by malgorithms** [comment]
> In settings we can add some page to install the cli. @malgorithms ?

so if you do a fresh sierra install, keybase won't work from the CLI...what would the settings screen do to fix this, and can't we just do it during the install?

**Comment by chrisnojima** [comment]
is there some process which actually makes /etc/paths.d ? why isn't it doing it when keybase is installed? can we find another place to install instead? (add a line to their bash_profile?)

**Comment by gabriel** [comment]
On fresh install... Terminal will load `/etc/profile`, which uses path_helper:

```
if [ -x /usr/libexec/path_helper ]; then
	eval `/usr/libexec/path_helper -s`
fi
```

```
The path_helper utility reads the contents of the files in the directo-
 ries /etc/paths.d and /etc/manpaths.d and appends their contents to the
 PATH and MANPATH environment variables respectively.
```

But a lot of people create a `.bash_profile` in which case, `/etc/profile` is not used... but hopefully in this case they have `/usr/local/bin` in their path, and we also try to put a symlink in `/usr/local/bin`.

I've filled an issue with Apple about /etc/paths.d not existing on Sierra, seems like a regression.
We could also create this directory, which would require a helper tool update since it requires a root privilege.

So currently, `keybase` is in you path if:

- You use default system `/etc/profile`. You don't have custom .bash_profile
- You have `/usr/local/bin` in you PATH

It seems like (anecdotally) 99% of users fall into those 2 categories.

If not, we probably wan't to show an message with link to online doc about how to add `keybase` to your path.

I don't think we can edit your .bash_profile (what if you don't have one, or don't use bash)?

**Comment by gabriel** [comment]
If Sierra GM still doesn't have `/etc/paths.d` we should consider a fix where we create it.

Because we can't cover 100% of PATH scenarios, I've created this:
https://keybase.atlassian.net/browse/DESKTOP-1799

**Comment by gabriel** [comment]
Ok I've changed the PR to create `/etc/paths.d` if missing, in the helper tool. Instead of working around the error, this will fix it, so people on fresh installs will have `keybase` in their path on Sierra.

Instead of incrementing the version, I'm including a build number in the helper tool, which we can increment for changes (like this) that aren't required updates.

**Comment by gabriel** [comment]
BTW, I've have a VM Sierra snapshot (vmware) that I test stuff like this on, repeatably.

**Comment by gabriel** [comment]
bump

**Comment by malgorithms** [comment]
this sounds good to me, although someone other than me should review your code. @chrisnojima  is out today, so if you want it today, maybe grab someone in your office?

**Comment by chromakode** [comment]
:+1:

**Comment by chrisnojima** [comment]
@maxtaco

**Pull request merged**
