### PR TITLE
Rest of tweaks on chat

### PR DESCRIPTION
**Pull request by cecileboucheron**
@keybase/react-hackers

### CODE REVIEW

**Comment by keybase-ci-visdiff** [comment]
The commits a2f36dd041e5...f68fc370a66b introduce visual changes on linux. <details><summary>:mag_right: 31 changed</summary>

 * Changed: **Text_Message-sent_You** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Text_Message-sent_You-a2f36dd041e5.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Text_Message-sent_You-f68fc370a66b.png)  
   Text_Message-sent_You comparison
 * Changed: **Text_Message-sent_Not_Following** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Text_Message-sent_Not_Following-a2f36dd041e5.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Text_Message-sent_Not_Following-f68fc370a66b.png)  
   Text_Message-sent_Not_Following comparison
 * Changed: **Text_Message-sent_Following** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Text_Message-sent_Following-a2f36dd041e5.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Text_Message-sent_Following-f68fc370a66b.png)  
   Text_Message-sent_Following comparison
 * Changed: **Text_Message-sent_Broken** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Text_Message-sent_Broken-a2f36dd041e5.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Text_Message-sent_Broken-f68fc370a66b.png)  
   Text_Message-sent_Broken comparison
 * Changed: **Text_Message-pending_You** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Text_Message-pending_You-a2f36dd041e5.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Text_Message-pending_You-f68fc370a66b.png)  
   Text_Message-pending_You comparison
 * Changed: **Text_Message-pending_Not_Following** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Text_Message-pending_Not_Following-a2f36dd041e5.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Text_Message-pending_Not_Following-f68fc370a66b.png)  
   Text_Message-pending_Not_Following comparison
 * Changed: **Text_Message-pending_Following** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Text_Message-pending_Following-a2f36dd041e5.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Text_Message-pending_Following-f68fc370a66b.png)  
   Text_Message-pending_Following comparison
 * Changed: **Text_Message-pending_Broken** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Text_Message-pending_Broken-a2f36dd041e5.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Text_Message-pending_Broken-f68fc370a66b.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Text_Message-pending_Broken.png)
 * Changed: **Text_Message-from_revoked_device** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Text_Message-from_revoked_device-a2f36dd041e5.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Text_Message-from_revoked_device-f68fc370a66b.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Text_Message-from_revoked_device.png)
 * Changed: **Text_Message-failed_You** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Text_Message-failed_You-a2f36dd041e5.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Text_Message-failed_You-f68fc370a66b.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Text_Message-failed_You.png)
 * Changed: **Text_Message-failed_Not_Following** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Text_Message-failed_Not_Following-a2f36dd041e5.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Text_Message-failed_Not_Following-f68fc370a66b.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Text_Message-failed_Not_Following.png)
 * Changed: **Text_Message-failed_Following** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Text_Message-failed_Following-a2f36dd041e5.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Text_Message-failed_Following-f68fc370a66b.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Text_Message-failed_Following.png)
 * Changed: **Text_Message-failed_Broken** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Text_Message-failed_Broken-a2f36dd041e5.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Text_Message-failed_Broken-f68fc370a66b.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Text_Message-failed_Broken.png)
 * Changed: **Stacked_Text_Message-Stacked_two_messages** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Stacked_Text_Message-Stacked_two_messages-a2f36dd041e5.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Stacked_Text_Message-Stacked_two_messages-f68fc370a66b.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Stacked_Text_Message-Stacked_two_messages.png)
 * Changed: **Stacked_Text_Message-Stacked_someone_else_two_sent** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Stacked_Text_Message-Stacked_someone_else_two_sent-a2f36dd041e5.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Stacked_Text_Message-Stacked_someone_else_two_sent-f68fc370a66b.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Stacked_Text_Message-Stacked_someone_else_two_sent.png)
 * Changed: **Stacked_Text_Message-Stacked_one_sent_one_pending** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Stacked_Text_Message-Stacked_one_sent_one_pending-a2f36dd041e5.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Stacked_Text_Message-Stacked_one_sent_one_pending-f68fc370a66b.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Stacked_Text_Message-Stacked_one_sent_one_pending.png)
 * Changed: **Stacked_Text_Message-Stacked_one_sent_one_failed** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Stacked_Text_Message-Stacked_one_sent_one_failed-a2f36dd041e5.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Stacked_Text_Message-Stacked_one_sent_one_failed-f68fc370a66b.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Stacked_Text_Message-Stacked_one_sent_one_failed.png)
 * Changed: **Chat_Conversations_List-Selected_Normal** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Chat_Conversations_List-Selected_Normal-a2f36dd041e5.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Chat_Conversations_List-Selected_Normal-f68fc370a66b.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Chat_Conversations_List-Selected_Normal.png)
 * Changed: **Chat_Conversations_List-Selected_Muted** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Chat_Conversations_List-Selected_Muted-a2f36dd041e5.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Chat_Conversations_List-Selected_Muted-f68fc370a66b.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Chat_Conversations_List-Selected_Muted.png)
 * Changed: **Attachment_Message-Basic_Uploading** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Attachment_Message-Basic_Uploading-a2f36dd041e5.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Attachment_Message-Basic_Uploading-f68fc370a66b.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Attachment_Message-Basic_Uploading.png)
 * Changed: **Attachment_Message-Basic_Preview_Image_Pending** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Attachment_Message-Basic_Preview_Image_Pending-a2f36dd041e5.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Attachment_Message-Basic_Preview_Image_Pending-f68fc370a66b.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Attachment_Message-Basic_Preview_Image_Pending.png)
 * Changed: **Attachment_Message-Basic_Preview_Image_Not_Downloaded** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Attachment_Message-Basic_Preview_Image_Not_Downloaded-a2f36dd041e5.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Attachment_Message-Basic_Preview_Image_Not_Downloaded-f68fc370a66b.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Attachment_Message-Basic_Preview_Image_Not_Downloaded.png)
 * Changed: **Attachment_Message-Basic_Preview_Image_Failed** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Attachment_Message-Basic_Preview_Image_Failed-a2f36dd041e5.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Attachment_Message-Basic_Preview_Image_Failed-f68fc370a66b.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Attachment_Message-Basic_Preview_Image_Failed.png)
 * Changed: **Attachment_Message-Basic_Preview_Image_Downloaded** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Attachment_Message-Basic_Preview_Image_Downloaded-a2f36dd041e5.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Attachment_Message-Basic_Preview_Image_Downloaded-f68fc370a66b.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Attachment_Message-Basic_Preview_Image_Downloaded.png)
 * Changed: **Attachment_Message-Basic_Not_loaded** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Attachment_Message-Basic_Not_loaded-a2f36dd041e5.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Attachment_Message-Basic_Not_loaded-f68fc370a66b.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Attachment_Message-Basic_Not_loaded.png)
 * Changed: **Attachment_Message-Basic_Generic_File_sent** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Attachment_Message-Basic_Generic_File_sent-a2f36dd041e5.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Attachment_Message-Basic_Generic_File_sent-f68fc370a66b.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Attachment_Message-Basic_Generic_File_sent.png)
 * Changed: **Attachment_Message-Basic_Generic_File_Uploading** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Attachment_Message-Basic_Generic_File_Uploading-a2f36dd041e5.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Attachment_Message-Basic_Generic_File_Uploading-f68fc370a66b.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Attachment_Message-Basic_Generic_File_Uploading.png)
 * Changed: **Attachment_Message-Basic_Generic_File_Failed** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Attachment_Message-Basic_Generic_File_Failed-a2f36dd041e5.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Attachment_Message-Basic_Generic_File_Failed-f68fc370a66b.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Attachment_Message-Basic_Generic_File_Failed.png)
 * Changed: **Attachment_Message-Basic_Generic_File_Downloading** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Attachment_Message-Basic_Generic_File_Downloading-a2f36dd041e5.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Attachment_Message-Basic_Generic_File_Downloading-f68fc370a66b.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Attachment_Message-Basic_Generic_File_Downloading.png)
 * Changed: **Attachment_Message-Basic_Generic_File_Downloaded** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Attachment_Message-Basic_Generic_File_Downloaded-a2f36dd041e5.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Attachment_Message-Basic_Generic_File_Downloaded-f68fc370a66b.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Attachment_Message-Basic_Generic_File_Downloaded.png)
 * Changed: **Attachment_Message-Basic_Downloading** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Attachment_Message-Basic_Downloading-a2f36dd041e5.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Attachment_Message-Basic_Downloading-f68fc370a66b.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1484782700872-a2f36dd041e5-f68fc370a66b-linux/Attachment_Message-Basic_Downloading.png)
</summary>

**Comment by MarcoPolo** [comment]
just to be sure, these diffs are correct?

**Comment by cecileboucheron** [comment]
Yes!

**Comment by MarcoPolo** [comment]
👍

**Pull request merged**
