### PR TITLE
Add Mobile version info and Status to logsend

### PR DESCRIPTION
**Pull request by MarcoPolo**

### CODE REVIEW

**Comment by cjb** [comment]
@MarcoPolo do you have a sample of the "status" output? am curious which of the fields from `keybase status` it has, was assuming it would be all of them

**Comment by MarcoPolo** [comment]
`keybase status` is a separate command that's built into the client side go code. I'm just including some data we get from our bootstrap ,`getConfig`, and `getExtendedStatus`

**Comment by MarcoPolo** [comment]
If there's anything else you want in there, I'm happy to add it. but for a duplicate of `keybase status` I think it might make more sense to have a core ticket to implement that as an rpc, then have both us and the cli use it like that

**Comment by MarcoPolo** [comment]
Sample:

```
{
   "username": "pkt1",
   "uid": "72d1c6948356fa9253c0c76270e57f19",
   "deviceID": "5b7bace28ba768bb0fb124f3efef4018",
   "config": null,
   "extendedStatus": null,
   "platform": "ios",
   "version": "1.0.21-20170427231925+8b9c1d5",
   "appVersionName": "1.0.0",
   "appVersionCode": "114"
}
```

Not sure why state.config.{config,extendedStatus} is null. I'm just reading those from the store

**Pull request merged**
