### PR TITLE
Desktop and mobile confirmation screens

### PR DESCRIPTION
**Pull request by chromakode**
Here's the confirmation screens! I factored the layout in the existing device revoke component into a common `<Confirm>` component and tweaked it to match the style guide.

### outstanding issues / questions

* Text wrapping on native can break mid-name and awkwardly orphan commas. [Like this](https://cloud.githubusercontent.com/assets/16893/15695942/cc5f8930-2760-11e6-9437-9313fece16d0.png). I'm not sure how to control wrapping here. Any ideas?
* Style reuse [via export](https://github.com/keybase/client/blob/d2841af6c9b2a855d3c5514f8b7f5c3a17b0338c/shared/common-adapters/confirm.native.js#L82) seems like an inelegant way to standardize the style of native confirmation screens. I considered making a component, but it seemed rather trivial. These styles seemed too specific to throw in the global style guide. Open to suggestions.
* I duplicated some of @MarcoPolo's work w/ the icons to get everything screenshot-ready. I figure this can be resolved / thrown away once the icon updates patch lands.

:eyeglasses: @keybase/react-hackers 

### mobile screenshots

[device revoke](https://cloud.githubusercontent.com/assets/16893/15695937/cc48c5e2-2760-11e6-8034-26a3cc96d474.png)
[ignore private](https://cloud.githubusercontent.com/assets/16893/15695938/cc56ad38-2760-11e6-8012-0378c9b29592.png)
[ignore public](https://cloud.githubusercontent.com/assets/16893/15695939/cc5cdfc8-2760-11e6-8677-caaed9612794.png)
[delete private](https://cloud.githubusercontent.com/assets/16893/15695940/cc5d8248-2760-11e6-84d1-db77581d5943.png)
[delete public](https://cloud.githubusercontent.com/assets/16893/15695941/cc5f0280-2760-11e6-925a-672d1e518947.png)
[clear history private](https://cloud.githubusercontent.com/assets/16893/15695944/cc6480b6-2760-11e6-8737-54445b85fadd.png)
[clear history public](https://cloud.githubusercontent.com/assets/16893/15695943/cc64811a-2760-11e6-99f7-4da40451a4fc.png)
[clear history long name](https://cloud.githubusercontent.com/assets/16893/15695942/cc5f8930-2760-11e6-9437-9313fece16d0.png) -- :warning: **note the wrapping here!**

### CODE REVIEW

**Comment by keybase-ci-visdiff** [comment]
:mag_right: :zap: These commits introduced some visual changes:
 * Added: **Folders_Ignore_Confirmation-Normal_Public**  
   Folders_Ignore_Confirmation-Normal_Public rendered
 * Added: **Folders_Ignore_Confirmation-Normal_Private**  
   Folders_Ignore_Confirmation-Normal_Private rendered
 * Added: **Folders_Delete_Confirmation-Normal_Public**  
   Folders_Delete_Confirmation-Normal_Public rendered
 * Added: **Folders_Delete_Confirmation-Normal_Private**  
   Folders_Delete_Confirmation-Normal_Private rendered
 * Added: **Folders_Clear_History_Confirmation-Normal_Public**  
   Folders_Clear_History_Confirmation-Normal_Public rendered
 * Added: **Folders_Clear_History_Confirmation-Normal_Private**  
   Folders_Clear_History_Confirmation-Normal_Private rendered
 * Added: **Folders_Clear_History_Confirmation-Long_Name_Public**  
   Folders_Clear_History_Confirmation-Long_Name_Public rendered
 * Changed: **Device_Revoke-Normal** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1464746986821-2a099bae722e-e99c5f5a81ff/Device_Revoke-Normal-2a099bae722e.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1464746986821-2a099bae722e-e99c5f5a81ff/Device_Revoke-Normal-e99c5f5a81ff.png) [(diff)](http://keybase-app-visdiff.s3.amazonaws.com/1464746986821-2a099bae722e-e99c5f5a81ff/Device_Revoke-Normal.png)
 * Changed: **Device_Revoke-Current** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1464746986821-2a099bae722e-e99c5f5a81ff/Device_Revoke-Current-2a099bae722e.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1464746986821-2a099bae722e-e99c5f5a81ff/Device_Revoke-Current-e99c5f5a81ff.png) [(diff)](http://keybase-app-visdiff.s3.amazonaws.com/1464746986821-2a099bae722e-e99c5f5a81ff/Device_Revoke-Current.png)

**Comment by keybase-ci-visdiff** [comment]
:mag_right: :zap: These commits introduced some visual changes:
 * Added: **Folders_Ignore_Confirmation-Normal_Public**  
   Folders_Ignore_Confirmation-Normal_Public rendered
 * Added: **Folders_Ignore_Confirmation-Normal_Private**  
   Folders_Ignore_Confirmation-Normal_Private rendered
 * Added: **Folders_Delete_Confirmation-Normal_Public**  
   Folders_Delete_Confirmation-Normal_Public rendered
 * Added: **Folders_Delete_Confirmation-Normal_Private**  
   Folders_Delete_Confirmation-Normal_Private rendered
 * Added: **Folders_Clear_History_Confirmation-Normal_Public**  
   Folders_Clear_History_Confirmation-Normal_Public rendered
 * Added: **Folders_Clear_History_Confirmation-Normal_Private**  
   Folders_Clear_History_Confirmation-Normal_Private rendered
 * Added: **Folders_Clear_History_Confirmation-Long_Name_Public**  
   Folders_Clear_History_Confirmation-Long_Name_Public rendered
 * Changed: **Device_Revoke-Normal** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1464747867252-2a099bae722e-87b21c1e6522/Device_Revoke-Normal-2a099bae722e.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1464747867252-2a099bae722e-87b21c1e6522/Device_Revoke-Normal-87b21c1e6522.png) [(diff)](http://keybase-app-visdiff.s3.amazonaws.com/1464747867252-2a099bae722e-87b21c1e6522/Device_Revoke-Normal.png)
 * Changed: **Device_Revoke-Current** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1464747867252-2a099bae722e-87b21c1e6522/Device_Revoke-Current-2a099bae722e.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1464747867252-2a099bae722e-87b21c1e6522/Device_Revoke-Current-87b21c1e6522.png) [(diff)](http://keybase-app-visdiff.s3.amazonaws.com/1464747867252-2a099bae722e-87b21c1e6522/Device_Revoke-Current.png)

**Comment by chrisnojima** [comment]
re: icons. totally fine. we'll have a ticket to clean this up
re: header style. i think this component maybe should be more structured. instead of taking in children as the body, then making sure the first child is this header, instead it should just take a header / body prop and make the header be a child of an internal header box. something ala: https://github.com/keybase/client/blob/master/shared/common-adapters/list-item.js.flow
so we'd end up with
```
const header = (
    <Box style={headerBoxStyle}>
        <Icon type={icon} />
        <Text type='Body' style={stylesName}>{name}</Text>
      </Box>
)

const body = (
    <Text type='Header' style={{textAlign: 'center'}}>Are you sure you want to revoke {currentDevice ? 'your current device' : name}?</Text>
)

return (
    <Confirm 
        theme='public' danger 
        submitLabel='Yes, delete it' 
        onSubmit={() => onSubmit({deviceID, name, currentDevice})} 
        onCancel={onCancel}
        header={header}
        body={body} />
```

**Comment by chromakode** [comment]
Thanks @chrisnojima, done!

**Comment by keybase-ci-visdiff** [comment]
:mag_right: :zap: These commits introduced some visual changes:
 * Added: **Folders_Ignore_Confirmation-Normal_Public**  
   Folders_Ignore_Confirmation-Normal_Public rendered
 * Added: **Folders_Ignore_Confirmation-Normal_Private**  
   Folders_Ignore_Confirmation-Normal_Private rendered
 * Added: **Folders_Delete_Confirmation-Normal_Public**  
   Folders_Delete_Confirmation-Normal_Public rendered
 * Added: **Folders_Delete_Confirmation-Normal_Private**  
   Folders_Delete_Confirmation-Normal_Private rendered
 * Added: **Folders_Clear_History_Confirmation-Normal_Public**  
   Folders_Clear_History_Confirmation-Normal_Public rendered
 * Added: **Folders_Clear_History_Confirmation-Normal_Private**  
   Folders_Clear_History_Confirmation-Normal_Private rendered
 * Added: **Folders_Clear_History_Confirmation-Long_Name_Public**  
   Folders_Clear_History_Confirmation-Long_Name_Public rendered
 * Changed: **Device_Revoke-Normal** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1464822925385-b6a91d2e82f5-4592b3a25e78/Device_Revoke-Normal-b6a91d2e82f5.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1464822925385-b6a91d2e82f5-4592b3a25e78/Device_Revoke-Normal-4592b3a25e78.png) [(diff)](http://keybase-app-visdiff.s3.amazonaws.com/1464822925385-b6a91d2e82f5-4592b3a25e78/Device_Revoke-Normal.png)
 * Changed: **Device_Revoke-Current** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1464822925385-b6a91d2e82f5-4592b3a25e78/Device_Revoke-Current-b6a91d2e82f5.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1464822925385-b6a91d2e82f5-4592b3a25e78/Device_Revoke-Current-4592b3a25e78.png) [(diff)](http://keybase-app-visdiff.s3.amazonaws.com/1464822925385-b6a91d2e82f5-4592b3a25e78/Device_Revoke-Current.png)

**Comment by chrisnojima** [comment]
👍

**Pull request merged**
