### PR TITLE
bring back some important logging to the upload

### PR DESCRIPTION
**Pull request by zanderz**
had a user report of something going wrong when they tried to add Dokan, but zilch in the logs.
The new log thing is very confusing, I don't think we really need all that on desktop, do we? It mixes periodic loggers, which write to the log file every minute (in separate sections apparently, so the entries are not in order) with ring loggers that hold a max of 1000 things and only write to file on log upload, so any logger.info() entries are likely lost, for example.
@keybase/react-hackers

### CODE REVIEW

**Comment by chrisnojima** [comment]
The whole point is so we can have different levels which do different things. If we need each item you can log to that level. If there's a thing that's just for a log send it can be another level

**Comment by zanderz** [comment]
@chrisnojima is this what you mean? I don't really understand why you would want to upload something that wasn't also written locally, or why you would want to discard log entries just because more than 5000 of them happened within 10 minutes, etc.

**Comment by chrisnojima** [comment]
not really. i'm saying 'error' and 'debug' and etc mean something. we don't need an additional one i think.
there are tons of things we want in a log send but not written all the time. there are things we always want to see, etc.

**Comment by zanderz** [comment]
ok, then I do not know what kind of a change you were suggesting with your first comment, I thought that's what I did.

**Comment by zanderz** [comment]
it would be nice to get this log line back @keybase/react-hackers

**Comment by zanderz** [comment]
thanks. In general, I don't see what is to be gained on desktop with this memory buffer thing - a normal, buffered file handle should be fine, right? I can see filtering out some stuff but that is so much easier and clearer at log time vs. upload time.

**Comment by chrisnojima** [comment]
its about the data. theres a large class of things we don't need

**Pull request merged**
