### PR TITLE
Identify2 returns ProofSets too

### PR DESCRIPTION
**Pull request by maxtaco**
Needed for CORE-2311

### CODE REVIEW

**Comment by maxtaco** [comment]
Though CORE-2311 isn't until M2.1, I went through with making these tweaks to identify2 so that we actually can extra a ProofSet from the identify process.

**Comment by maxtaco** [comment]
@patrickxb can you take a look?

**Comment by patrickxb** [comment]
LGTM

**Comment by patrickxb** [comment]
@maxtaco just reminding you about this PR...looks good to me.

**Comment by maxtaco** [comment]
thanks for the reminder!

**Pull request merged**
