### PR TITLE
Update image picker

### PR DESCRIPTION
**Pull request by gabriel**
Fixes a bug where the image picker wouldn't come up after giving permissions on Android.

I also needed to upgrade the react-native-camera package too.

There are other fixes we are picking up too. We should merge this after our release so we can do more testing (only tested on iOS and Android simulators).

https://keybase.atlassian.net/browse/DESKTOP-3790

### CODE REVIEW

**Comment by gabriel** [comment]
@keybase/react-hackers

**Comment by gabriel** [comment]
bump

**Comment by chrisnojima** [comment]
Can you test to make sure QR code scanning still works on device

**Comment by gabriel** [comment]
Yup works on device.

**Comment by gabriel** [comment]
Going to remerge from here after next build:
https://github.com/keybase/client/pull/7116

**Pull request merged**
