### PR TITLE
restore participants to small team view

### PR DESCRIPTION
**Pull request by mmaxim**
@keybase/react-hackers 

Adds participant list back to small team info pane.

cc @cecileboucheron @malgorithms

### CODE REVIEW

**Comment by mmaxim** [comment]
image

**Comment by zanderz** [comment]
Just curious what happened to the new design that called for removing these?

**Comment by mmaxim** [comment]
Being re-done, there is a design ticket for it.

**Comment by cecileboucheron** [comment]
@zanderz Designs never showed participants for small teams, we'd link to the team page - but we've decided to put them back

**Pull request merged**
