### PR TITLE
show no conversation selected screen on right. updated some assets

### PR DESCRIPTION
**Pull request by chrisnojima**
@keybase/react-hackers

### CODE REVIEW

**Comment by chrisnojima** [comment]
The image changes are just me re-encoding the largest images w/ imageOptim quick while i added a couple of new ones i needed

**Comment by chrisnojima** [comment]
doh, @cjb fixed

**Comment by cjb** [comment]
Just curious, what situations other than a null conversationList would leave you with no conversation selected?  (Don't hold up merging on the q.)

**Comment by chrisnojima** [comment]
We could theoretically support a 'nothing selected' mode if you do something like delete your current conversation or some such.

**Pull request merged**
