### PR TITLE
optimize UID->Username mapper

### PR DESCRIPTION
**Pull request by maxtaco**
- include a hardcoded list of all UID/username exceptions, for which Hash(username) != uid
- use a batch lookup interface to grab many Usernames in one round trip
- make sure we check the server's work
- use mem and disk caching

### CODE REVIEW

**Comment by mmaxim** [comment]
So this guy is unused right now?

**Comment by maxtaco** [comment]
Yeah, unused except it's tested in unit tests

**Comment by mmaxim** [comment]
Ok I think it would be like a 1 line change to use this in chat, so that is great!

**Comment by maxtaco** [comment]
Cool, thanks @mmaxim. Yeah it should be pretty speedy.

**Comment by maxtaco** [comment]
@mmaxim all ready to go, sorry it took so long to get through CI and merging.

**Comment by mmaxim** [comment]
Thanks! I tried to use this, but it looks like something on prod is missing. Will try tomorrow.

**Comment by maxtaco** [comment]
it needed fresh code. launching that now.

**Comment by maxtaco** [comment]
ok, done

**Pull request merged**
