### PR TITLE
Cleanup devel flags

### PR DESCRIPTION
**Pull request by gabriel**
When developing tracker stuff, I wanted to use delegate ui in prod build for testing. Also made some other tweaks.

- Add HideUsage setting for the bool flag (in devel).
- Renaming to --ui.
- Moving signup flags into cmd_signup
- Replace two spaces after period cause my OCD kicked in this morning

### CODE REVIEW

**Comment by gabriel** [comment]
cc @maxtaco or @patrickxb

**Comment by patrickxb** [comment]
I'd prefer to keep those signup flags completely out of the production build.

**Comment by gabriel** [comment]
It would be impossible to trigger them in a production build since that bool would always evaluate to false... but I guess you mean you don't want some bad merge or weird refactor to have them accidentally get in? cool

**Comment by gabriel** [comment]
K moved signup flags back out

**Comment by patrickxb** [comment]
LGTM

**Pull request merged**
