### PR TITLE
Update vendored go-codec library

### PR DESCRIPTION
**Pull request by akalin-keybase**

### CODE REVIEW

**Comment by akalin-keybase** [comment]
Interesting CI failure: `Original msgpack data didn't match re-encoded version: `, will have to dig in.

**Comment by akalin-keybase** [comment]
This is finally ready for review.

Note that the CircleCI failure is expected, and will go away once client and kbfs are both using the new go-codec.

**Comment by maxtaco** [comment]
@akalin-keybase can you point me to a summary of the changes?

**Comment by akalin-keybase** [comment]
Will do, let me dig through the commits...

**Comment by akalin-keybase** [comment]
Did a pass over the changes since the last vendor. Here are the ones that caught my eye:

Bug fixes:
- omitempty tag now handles all comparable types (had to fix kbfs for this to preserve old behavior)

Other changes:
- Supposed performance improvements, but I didn't test for this.
- encode signed integers as signed (had to revert this in a patch -- will see if upstream will take a flag for this)
- error messages now include position info (had to change some tests expecting errors to test suffixes)

New features:
- recursive omitEmpty (only as a global flag -- will see if upstream will take a tag for this)
- Raw type -- enables 'partial' encoding/decoding
- Time encoding (via msgpack's timestamp extension) (probably don't want to use this, though)
- Partial decoding, e.g. it'll now expose how many bytes were read during decoding

**Comment by maxtaco** [comment]
Should we expect any differences in the way we are encoding or decoding things? It seems like "no", but I wanted to verify...

**Comment by akalin-keybase** [comment]
No, there should be no differences now, unless I missed something.

(BTW, I'll merge this and the other vendor PRs only when I come back from vacation on Jul. 16)

**Comment by maxtaco** [comment]
Ok great. Then I am :+1: !

Thanks for the information about what’s changed.

**Pull request merged**
