### PR TITLE
Better handling of error creating channel as implied admin

### PR DESCRIPTION
**Pull request by patrickxb**
With this patch, implied admin trying to create a channel gets this:

```
> kbcl -d=0 chat create-channel haaa.sub hhoohh
Failed to create the channel "hhoohh"

To edit haaa.sub's channels, you must join the team.
Try `keybase team add-member haaa.sub --user=wool --role=admin`

```

Also, this fixes bug where creator of subteam tries (and fails) to send a chat notification after the team is created.

And some general cleanup of this command...

### CODE REVIEW

**Comment by patrickxb** [comment]
Oh, one more thing:  previously CLI sent a text message to a channel in order to create the channel.  Now it uses NewConversation, the same as GUI.

**Comment by keybase-ci-visdiff** [comment]
The commits 86c8932fd58b...893d570194df introduce visual changes on linux. <details><summary>:mag_right: 1 changed</summary>

 * Changed: **Markdown-emoji** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1505490261212-86c8932fd58b-893d570194df-linux/Markdown-emoji-86c8932fd58b.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1505490261212-86c8932fd58b-893d570194df-linux/Markdown-emoji-893d570194df.png)  
   Markdown-emoji comparison
</summary>

**Comment by patrickxb** [comment]
So is this frozen?

**Comment by patrickxb** [comment]
If desktop build hasn't gone out, it would be nice to have this in.

**Comment by maxtaco** [comment]
no go merge! 👍

**Comment by mmaxim** [comment]
Let me try it locally really quick

**Comment by patrickxb** [comment]
(i merged...i did try it locally)

**Pull request merged**
