### PR TITLE
Return error for frontend use when uri signature fails

### PR DESCRIPTION
**Pull request by patrickxb**

### CODE REVIEW

**Comment by cjb** [comment]
@patrickxb Looks like this doesn't compile:
```
# github.com/keybase/client/go/stellar/stellarsvc
../../../go/src/github.com/keybase/client/go/stellar/stellarsvc/service.go:630:5: not enough arguments to return
	have (error)
	want (*stellar1.ValidateStellarURIResultLocal, *stellarnet.ValidatedStellarURI, error)
```

**Comment by patrickxb** [comment]
huh...how did that happen.  ok...

**Comment by patrickxb** [comment]
Fixed, sorry about that.

**Comment by patrickxb** [comment]
Failing test in CI is skipped in master, merging.

**Pull request merged**
