### PR TITLE
Updated react-native in hopes of fixing displaying messages in Huawei

### LINKED ISSUE #8542: Upgrade react-native to the latest one (at leats 0.48)
I have a Huawei P10 Lite and I have to ignore the android app because I can't see chat messages there sadly. It was hard to figure out the reason, but it's a Huawei + Android7 bug (as it seems).

References:
Starting point: https://github.com/FaridSafi/react-native-gifted-chat/issues/536
react-native PR: https://github.com/facebook/react-native/pull/14646 (was merged one month ago)
mention on RN version: https://github.com/expo/react-native-invertible-scroll-view/issues/47

(I hope it fixes the issue. If you have a test build, ping me and I can install it and verify if it works or not)

### PR DESCRIPTION
**Pull request by Skarlso**
Closes #8542.

### CODE REVIEW

**Comment by Skarlso** [comment]
Uh, can anyone check what the error is please?

**Comment by Skarlso** [comment]
Hello?

**Comment by buoyad** [comment]
@Skarlso We are working on getting this in internally, we've got to handle it a bit delicately so as to not make any regressions. Thanks for the PR! Closing this now.

**Comment by Skarlso** [comment]
Thanks very much @bouyad for taking the time to answer.

Good luck! :-)

**Pull request closed without merging**
