### PR TITLE
simplify the protocol to better match the wireframes...

### PR DESCRIPTION
**Pull request by maxtaco**
- we previously had a lot of fields that will be cumbersome to load,
  and that we don't really need.

### CODE REVIEW

**Comment by maxtaco** [comment]
@patrickxb can you take a look?  I've simplified the protocols to make it easier to write the server.  The server is sadly a beast.

**Comment by keybase-ci-visdiff** [comment]
:mag_right: No visual changes found as a result of these commits.

**Comment by keybase-ci-visdiff** [comment]
:mag_right: No visual changes found as a result of these commits.

**Comment by patrickxb** [comment]
LGTM

**Comment by keybase-ci-visdiff** [comment]
:mag_right: No visual changes found as a result of these commits.

**Comment by keybase-ci-visdiff** [comment]
:mag_right: No visual changes found as a result of these commits.

**Comment by keybase-ci-visdiff** [comment]
:mag_right: No visual changes found as a result of these commits.

**Comment by maxtaco** [comment]
This protocol now matches what I have implemented.  As you can see, I changed things up a bunch. I'm shipping solution KIDs instead of solution Devices, but it's easy enough to convert from KID to device on the client side.  What do you think?

**Comment by keybase-ci-visdiff** [comment]
:mag_right: No visual changes found as a result of these commits.

**Comment by keybase-ci-visdiff** [comment]
:mag_right: No visual changes found as a result of these commits.

**Comment by patrickxb** [comment]
Sounds good.

**Pull request merged**
