### PR TITLE
switch revoke to use key/multi endpoint

### PR DESCRIPTION
**Pull request by mlsteele**
Switch revoke to use `key/multi` in preparation for posting multiple sigs for shared DH.

This change could go under `Env.GetEnableSharedDH()` if you think that'd be better.

### CODE REVIEW

**Comment by patrickxb** [comment]
I don't know about the `key/multi` endpoint being able to handle revokes, so will delegate to @maxtaco

**Comment by maxtaco** [comment]
I does!

**Comment by maxtaco** [comment]
LGTM -- are there tests that cover this?

**Comment by mlsteele** [comment]
There are test that use it to revoke self-device and paper keys in `revoke_test.go`, `login_test.go`, and chat. But I was just noticing not finding one for other real devices. I'll add one.

**Pull request merged**
