### PR TITLE
Fix reset account history

### PR DESCRIPTION
**Pull request by MarcoPolo**
@keybase/react-hackers

### CODE REVIEW

**Comment by cjb** [comment]
CC @mmaxim

**Comment by chrisnojima** [comment]
Can't we use the b64 lib we already have

**Comment by chrisnojima** [comment]
Also do we have to handle this in multiple cases or should we just make a new function we call once. Like will other code call this and now do the wrong thing

**Comment by mmaxim** [comment]
Agree, maybe the safer change is to just un-base64 the convID's on the supersedes fields. I am pretty sure that is the only time this will happen. Seems like a less risky change.

**Pull request closed without merging**
