### PR TITLE
Adding pre-commit support for running our global eslint/flow

### PR DESCRIPTION
**Pull request by chrisnojima**
@keybase/react-hackers 
This just points to our own hooks repo and runs eslint / flow using an assumed global install. to test this out

```
brew install pre-commit (or follow http://pre-commit.com/#install)
(cd into client root dir)
pre-commit install
```

then when you commit stuff it should eslint/flow check it

### CODE REVIEW

**Comment by gabriel** [comment]
We might want to add go stuff?

https://github.com/gabriel/pre-commit-golang

**Comment by chrisnojima** [comment]
i'd prefer if core added their own stuff, i just need eslint / flow

**Comment by chrisnojima** [comment]
@keybase/react-hackers bump

**Comment by MarcoPolo** [comment]
:+1: although I would like having go stuff too in case I ever touch go and push something, we can set that up in a separate PR.

Is there a way I can add the golang stuff for myself in the mean time? @gabriel

**Comment by chrisnojima** [comment]
i'll add it since you and gabriel asked for it, update soon

**Comment by chrisnojima** [comment]
I added go hooks. @gabriel i forked your repo so it'll all be under keybase. your config has the meta checking but its not described in your readme, so should we include it or not?

**Comment by gabriel** [comment]
we don't need the metalinter hook (haven't got around to fixing it)... the regular vet and lint is fine

:ship:

**Pull request merged**
