### PR TITLE
Avatar cache fixes

### PR DESCRIPTION
**Pull request by zapu**
This PR introduces the following changes:
1) Fixes a bug in `populateCacheWorker` where HTTP response was not properly disposed of. On some platforms it might have caused a resource leak.
2) Added a new method to `avatars.Source` interface: `OnCacheCleared`. It's called after DB nuke and gives a chance to avatar source to clean up after cache database has been cleared. `FullCachingSource` removes all avatar files from cache directory. Other sources don't have to do anything.
3) Moved avatar cache storage path to `avatars/` subdirectory (instead of main keybase cache dir). `FullCachingSource` will ensure this dir exists when it's initialized. Old cached avatars will continue to live on old path but new ones will be put in new path. Avatars from old directory will be slowly phased out with cache eviction.

### CODE REVIEW

**Comment by mmaxim** [comment]
Can this also just delete all the avatars from the old directory? It isn't so bad if we just start from scratch.

**Comment by zapu** [comment]
Because it stores paths in leveldb, it would just resave avatars to old directory if we only deleted files.

So we would have to either go through leveldb and clean old entries up, or make it ignore old paths
in e.g. `commitAvatarToDisk` https://github.com/keybase/client/pull/12752/files#diff-2f8f36b16ddaa8bf55e3faca35d46568L182

**Comment by mmaxim** [comment]
Can we just change that to an `Open` call? I'm not sure why I used `OpenFile`

**Comment by zapu** [comment]
and then make it go ahead the tempfile route if it can't open? sounds good!

**Pull request merged**
