### PR TITLE
simple standalone saltpack signer

### PR DESCRIPTION
**Pull request by maxtaco**
- can specify an encrypted EdDSA secret key via env variables (and encryption key)

### CODE REVIEW

**Comment by maxtaco** [comment]
Sample usage:

```bash
export PASSPHRASE="..."
export PUBLIC_KEY="..."
export SECRET_KEY="..."

ssss ./keybase.exe
```

**Comment by zanderz** [comment]
Which of the 3 can live on disk, again? Hopfully just the passphrase needs to be typed in at every reboot? or what's the plan?

Also, don't go tools belong under go/tools ?

**Comment by maxtaco** [comment]
All but the PASSPHRASE should live on disk.  Is it more convenient to specify the keys as files rather than environment variables in that case?

**Comment by zanderz** [comment]
not really, no big deal.

Another question: OK to make both slaves do this, so they can run all the same scripts? or should this be made a special case for the non-SF slave?

**Comment by maxtaco** [comment]
It's probably better if both run the same way, good idea.

**Comment by zanderz** [comment]
tell you what, I'll change the scripts and make an installer from this branch and we'll see if it can be updated to

**Comment by maxtaco** [comment]
ok, now g2g.  lemme know if you to merge or hold off on the merge

**Comment by zanderz** [comment]
@maxtaco Go ahead and merge this in, I stripped out my changes to go in separately

**Pull request merged**
