### PR TITLE
Version bumps post release

### PR DESCRIPTION
**Pull request by cjb**
@keybase/react-hackers

### CODE REVIEW

**Comment by mmaxim** [comment]
Hmm we should have done this before the release. We released 1.0.47 last time.

**Comment by mmaxim** [comment]
Maybe next time this could also be made like 2.0.0, I think @maxtaco wanted something like that.

**Comment by mmaxim** [comment]
We should add this version number thing to the check list I think.

**Comment by cjb** [comment]
@mmaxim Sounds right.  A thumb, though?

**Pull request merged**
