### PR TITLE
Clipboard paste image support

### PR DESCRIPTION
**Pull request by gabriel**
Clipboard data is notoriously difficult to deal with via HTML5 APIs. This uses the Electron clipboard API to get the image filename, and then use getAsFile() to read the data and save to temp directory. I wasn't able to use the Electron clipboard API to read the data cause unfortunately you can only get string/rtf/html or image, and the image is a NativeImage (which only supports png and jpg) and we want animated gifs of course. This is probably an oversight someone will eventually get to.

### CODE REVIEW

**Comment by gabriel** [comment]
@keybase/react-hackers

**Comment by chrisnojima** [comment]
What is the file name? Something it makes up or it only works when it understands I sourced it from a file?

**Comment by chrisnojima** [comment]
Also I don't think we need to support pasting of gifs. Does that even work in most messengers? I recall trying this and it usually not working

**Comment by gabriel** [comment]
Yeah the clipboard always comes through as png for any image. It's pretty locked down. Changed to use the electron clipboard readImage and 'image.png' for the name.

**Pull request merged**
