### PR TITLE
putting in exact matches in package.json. removing dep on react-flexbox

### PR DESCRIPTION
**Pull request by chrisnojima**
@keybase/react-hackers

### CODE REVIEW

**Comment by cjb** [comment]
What about react-native/'s package.json?

**Comment by chrisnojima** [comment]
i'll ticket it. let's revisit when we go back to mobile

**Comment by chrisnojima** [comment]
https://keybase.atlassian.net/browse/DESKTOP-652

**Comment by cjb** [comment]
But aren't they used during the desktop build too?  The desktop build does npm i inside react-native, and our react components import from it.  I don't see how we could claim that the desktop no longer has fuzzy imports without changing react-native too.

**Comment by cjb** [comment]
(Maybe I'm wrong that the desktop build uses the modules it installs from react-native/package.json? If so, I'm happy with this PR being enough for now.)

**Comment by chrisnojima** [comment]
Desktop does not rely on react native at all (or should not)

**Comment by MarcoPolo** [comment]
:+1:

**Comment by cjb** [comment]
Ahhh cool, okay. :thumbsup:

**Comment by chrisnojima** [comment]
@keybase/react-hackers i added shrinkwrap, wanna pull and rm -rf node_modules ; npm i to sanity check

**Comment by cjb** [comment]
Did pull, rm -rf node_modules, npm i, all seems to work.  :thumbsup:

**Pull request merged**
