### PR TITLE
allow dest filename for fs mv

### PR DESCRIPTION
**Pull request by zanderz**
I had tweaked the logic for this in ls, but forgot to do so in mv

### CODE REVIEW

**Comment by patrickxb** [comment]
Are there tests for the CLI commands?

**Comment by zanderz** [comment]
Just what's in client/simplefs_test.go. Plus there are tests on the kbfs side. I thought doing a whole mock of the RPC wasn't worth it, it would be hard to keep up to date, but maybe I'm wrong.

**Comment by maxtaco** [comment]
I agree with patrick that we could use some integration tests. They'd have to be `kbfsdocker` tests but worth it.

**Comment by zanderz** [comment]
OK, I'll merge this in for now and make a ticket for kbfsdocker integration tests.

**Pull request merged**
