### PR TITLE
Update design of Settings->Notifications and Settings->Chat

### PR DESCRIPTION
**Pull request by cjb**
@keybase/react-hackers @keybase/design 

* Move security and sound settings from Settings->Notifications to Settings->Chat
* Fix scrolling on mobile
* Make section dividers full-width
* Redesigned unfurl whitelist view, single dividers instead of a full border, and more spacing
* Lots of text copy updates

Still to come in separate PRs:

* Removing the save buttons from Settings->Chat
* Copy changes to the notification toggles, those are server-side
* Phone push notifications setting

After:

Desktop notifications:

Screen Shot 2020-04-22 at 8 10 08 PM

Desktop chat:

Screen Shot 2020-04-22 at 8 10 03 PM

iPad notifications:

Screen Shot 2020-04-22 at 8 11 10 PM

iPad chat:

Screen Shot 2020-04-22 at 8 11 27 PM

iPhone SE notifications top/bottom:

Screen Shot 2020-04-22 at 8 13 30 PM

Screen Shot 2020-04-22 at 8 13 32 PM

iPhone SE chat top/bottom:

Screen Shot 2020-04-22 at 8 13 43 PM

Screen Shot 2020-04-22 at 8 13 46 PM

### CODE REVIEW

**Comment by cecileboucheron** [comment]
@cjb 
• This list of websites should still stand in a scrollable container, otherwise they expand the page too much
• Can we hide this list when another option than "Only for some websites" is checked?
• Website rows' height is too high now - maybe do `padding: 8px 16px` on the rows instead of `padding: 16px`
• Website rows should have a max-width, we can take the same one as the Email address/phone numbers rows under Your account. 
• I know it's a bit off-ticket but could we align the Files title (Finder integration) with all the other titles on desktop? Currently it's the only one that jumps.

**Comment by cjb** [comment]
@cecileboucheron Okay!  The unfurl whitelist container doesn't look scrollable on Zeplin because there's no border.  Could you describe more about how it should work.. should it have a full border the way the current one in the app does?  If there's no border, is there any way to see that it's scrollable?

**Comment by cjb** [comment]
@cecileboucheron Thanks! Made all of these changes, ready for another look.

Screen Shot 2020-04-28 at 10 48 42 PM

Screen Shot 2020-04-28 at 10 48 36 PM

Screen Shot 2020-04-28 at 10 48 25 PM

Screen Shot 2020-04-28 at 10 48 19 PM

Screen Shot 2020-04-28 at 10 47 15 PM

Screen Shot 2020-04-28 at 10 46 59 PM

**Comment by cecileboucheron** [comment]
Looks great. 
2 tweaks:
• it looks like you applied the max width to the divider as well. It's fine, but it's not consistent with the other tabs where dividers go edge-to-edge.
• Can we add a "Delete" tooltip when hovering the trash icon?

**Comment by cjb** [comment]
@cecileboucheron Thanks for catching that! Fixed all the settings dividers and added the tooltip.

**Pull request merged**
