### PR TITLE
DZ2: More pinentry fixes

### PR DESCRIPTION
**Pull request by cjb**
@keybase/react-hackers @cecileboucheron 

screenshot from 2016-03-03 13-45-41

- [x] Wrong spacings around the passphrase field, around the top sentence and around the bottom button. Should follow the spacing rules on this sheet (first popup): https://zpl.io/Z2bBA6P
- [x] Wrong font on top sentence: should be Lato.
- [x] Top sentence should be centered, and left/right paddings around should be 30px.
- [ ] Copy should say "Enter your passphrase to unlock the secret key for Work Computer."
- [ ] Name of device should not have any quotes around and be Semibold italic, see rules at the end of this board: https://zpl.io/Z1bvOTg
- [x] Color of placeholder text should be black10 (Black 10%)
- [x] Top Keybase logo is now 24x24, asset can be found here in 1x and 2: https://zpl.io/Z2p7znWx.
- [x] Continue button should be disabled by default (styling here: https://zpl.io/2rqNgg) and get back to enabled after user starts typing.

I'll open a new JIRA story for the text copy, since it comes from the CORE and we'll need more design work too (there are different strings for different situations).

### CODE REVIEW

**Comment by chrisnojima** [comment]
:+1:

**Comment by cjb** [comment]
New story for copy: DESKTOP-622

**Comment by cecileboucheron** [comment]
Looking good! 

I forgot 2 or 3 little things in the above list:
• Color of the checkbox label should be the usual black75 (unless it's disabled, in which case the box borders should be black10):
screen shot 2016-03-03 at 4 06 06 pm
• Color of the bottom border on the input should be black10 when not selected (now it looks like a darker grey)
screen shot 2016-03-03 at 4 06 26 pm
• my own username (here, cjb) should also be Lato Semibold Italic: 
screen shot 2016-03-03 at 4 05 13 pm

**Comment by cjb** [comment]
@cecileboucheron Both fixed, take another look:

screenshot from 2016-03-03 16-36-04

**Comment by cjb** [comment]
(The text copy isn't fixed because we're going to do that in a different story.)

**Comment by cecileboucheron** [comment]
Looks good! Thanks!

**Pull request merged**
