### PR TITLE
Check device names against sanitized list

### PR DESCRIPTION
**Pull request by gabriel**
Device names are checked against existing device names in a canonical form (only a-z0-9).

Also device names have to be length >= 3 and <= 64.

### CODE REVIEW

**Comment by gabriel** [comment]
@keybase/react-hackers

**Comment by gabriel** [comment]
Since this check happens in real time (which is nice), there is a bit of lag introduced by hitting an RPC which doesn't do anything (in core) other than check a regex.

So we'd be introducing some performance lag, in order to minimize some minor duplication? I don't think it's worth it?

**Comment by keybase-ci-visdiff** [comment]
The commits e5ac86527acb...78f91593dfc1 introduce visual changes on linux. <details><summary>:mag_right: 1 changed</summary>

 * Changed: **Tracker-New_user_Scroll_1** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1498500758483-e5ac86527acb-78f91593dfc1-linux/Tracker-New_user_Scroll_1-e5ac86527acb.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1498500758483-e5ac86527acb-78f91593dfc1-linux/Tracker-New_user_Scroll_1-78f91593dfc1.png)  
   Tracker-New_user_Scroll_1 comparison
</summary>

**Comment by gabriel** [comment]
And , this code introduced here in this PR for the existing device name check is not duplicated on the go side. We could move this all to the go side, but it's nice to have it here for reasons above.

**Comment by chrisnojima** [comment]
🚢

**Pull request merged**
