### PR TITLE
make sure the service knows we are in the foreground when navigating through push notification

### PR DESCRIPTION
**Pull request by mmaxim**
@keybase/react-hackers 

Otherwise we can attempt to load the thread and we think we are in the background. The symptom is that you get the gray "Disconnected" banner (and an out of date thread).

### CODE REVIEW

**Comment by chrisnojima** [comment]
is this just a race? like you'll eventually get this message?

**Comment by mmaxim** [comment]
It is a race, and it seems we lose it about 40% of the time.

**Comment by mmaxim** [comment]
I think it became more common to be on the losing side of this race when this code was changed to use `selectConversation`. Before that I think it had to churn a little more before it actually issued the `GetThreadLocal` call and the service had probably heard about being in the foreground on the normal channel.

**Comment by chrisnojima** [comment]
k, this is a short term fix. can we add a comment about this cause it really shouldn't do this and is incorrect but its better short term

**Comment by mmaxim** [comment]
Maybe putting the RPC call first here would also help:
```
  return Saga.sequentially([
    Saga.put(AppGen.createChangedFocus({appFocused})),
    Saga.call(RPCTypes.appStateUpdateAppStateRpcPromise, {state}),
  ])
```

**Pull request merged**
