### PR TITLE
Use 0 for sessionID in delegated secret ui calls

### PR DESCRIPTION
**Pull request by patrickxb**
r? @maxtaco 

(wanted to get in the travis line...testing locally as well)

### CODE REVIEW

**Comment by maxtaco** [comment]
is there any chance this will break something else?  i can't think of anything, but just checking...

**Comment by patrickxb** [comment]
i checked my logs and before the change it only used 0.

i'm building desktop locally to check that it fixes this bug.

**Comment by patrickxb** [comment]
built desktop locally, restarted service, everything worked as before.

**Comment by patrickxb** [comment]
@maxtaco I'm pretty sure it was only ever zero before, otherwise this electron bug would have shown up earlier.

**Comment by maxtaco** [comment]
👍

**Pull request merged**
