### PR TITLE
WIP fix logger?

### PR DESCRIPTION
**Pull request by chrisnojima**

### CODE REVIEW

**Comment by akalin-keybase** [comment]
Hmmm...I still see a stack in the console on desktop. Tried to set breakpoints but it wouldn't fire -- not sure where it's coming from!

**Comment by chrisnojima** [comment]
Restart hot sever

**Comment by chrisnojima** [comment]
Restart hot server

**Comment by akalin-keybase** [comment]
Yeap, that fixed it, thanks

**Pull request merged**
