### PR TITLE
avoid overwriting unexpected error types in Identify2

### PR DESCRIPTION
**Pull request by oconnor663**
r? @patrickxb

### CODE REVIEW

**Comment by maxtaco** [comment]
I worry we rely on the broken behavior somewhere, so let's be extra-certain about it.

**Comment by oconnor663** [comment]
Tests passed locally. Will wait for CI.

**Comment by oconnor663** [comment]
Hmm, I see `[test_windows_go] --- FAIL: TestProvisionGPGSign (0.57s)`. Is there any way to confirm that there isn't another error in the log that I missed?

**Comment by maxtaco** [comment]
is the error due to a bad GPG signature?

**Comment by oconnor663** [comment]
Last two CI runs failed with unrelated errors. I'm going to push it in.

**Pull request closed without merging**
