### PR TITLE
Hack to detect if we have a scrollbar and tweak header's absolute pos…

### PR DESCRIPTION
**Pull request by MarcoPolo**
…itioning 

@keybase/react-hackers 

Open to better ideas than this hack.

For this ticket: https://keybase.atlassian.net/secure/RapidBoard.jspa?rapidView=8&projectKey=DESKTOP&view=detail&selectedIssue=DESKTOP-1501

Originally reported for windows, actually affect all platforms that'll show a fixed with scroll bar.

### CODE REVIEW

**Comment by keybase-ci-visdiff** [comment]
:mag_right: The commits 2068d5c4f9d5...6a0ebc3269c2 introduced some visual changes on linux:
 * Changed: **Tracker-You_track_them** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468963567408-2068d5c4f9d5-6a0ebc3269c2-linux/Tracker-You_track_them-2068d5c4f9d5.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468963567408-2068d5c4f9d5-6a0ebc3269c2-linux/Tracker-You_track_them-6a0ebc3269c2.png)  
   Tracker-You_track_them comparison
 * Changed: **Tracker-Unfollowed** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468963567408-2068d5c4f9d5-6a0ebc3269c2-linux/Tracker-Unfollowed-2068d5c4f9d5.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468963567408-2068d5c4f9d5-6a0ebc3269c2-linux/Tracker-Unfollowed-6a0ebc3269c2.png)  
   Tracker-Unfollowed comparison
 * Changed: **Tracker-New_user_follows_me** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468963567408-2068d5c4f9d5-6a0ebc3269c2-linux/Tracker-New_user_follows_me-2068d5c4f9d5.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468963567408-2068d5c4f9d5-6a0ebc3269c2-linux/Tracker-New_user_follows_me-6a0ebc3269c2.png)  
   Tracker-New_user_follows_me comparison
 * Changed: **Tracker-New_user_Scroll_2** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468963567408-2068d5c4f9d5-6a0ebc3269c2-linux/Tracker-New_user_Scroll_2-2068d5c4f9d5.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468963567408-2068d5c4f9d5-6a0ebc3269c2-linux/Tracker-New_user_Scroll_2-6a0ebc3269c2.png)  
   Tracker-New_user_Scroll_2 comparison
 * Changed: **Tracker-New_user_Scroll_1** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468963567408-2068d5c4f9d5-6a0ebc3269c2-linux/Tracker-New_user_Scroll_1-2068d5c4f9d5.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468963567408-2068d5c4f9d5-6a0ebc3269c2-linux/Tracker-New_user_Scroll_1-6a0ebc3269c2.png)  
   Tracker-New_user_Scroll_1 comparison
 * Changed: **Tracker-New_user** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468963567408-2068d5c4f9d5-6a0ebc3269c2-linux/Tracker-New_user-2068d5c4f9d5.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468963567408-2068d5c4f9d5-6a0ebc3269c2-linux/Tracker-New_user-6a0ebc3269c2.png)  
   Tracker-New_user comparison
 * Changed: **Tracker-Logged_out** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468963567408-2068d5c4f9d5-6a0ebc3269c2-linux/Tracker-Logged_out-2068d5c4f9d5.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468963567408-2068d5c4f9d5-6a0ebc3269c2-linux/Tracker-Logged_out-6a0ebc3269c2.png)  
   Tracker-Logged_out comparison
 * Changed: **Tracker-Followed** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468963567408-2068d5c4f9d5-6a0ebc3269c2-linux/Tracker-Followed-2068d5c4f9d5.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468963567408-2068d5c4f9d5-6a0ebc3269c2-linux/Tracker-Followed-6a0ebc3269c2.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1468963567408-2068d5c4f9d5-6a0ebc3269c2-linux/Tracker-Followed.png)
 * Changed: **Tracker-Changed_Broken_proofs_user_you_dont_follow** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468963567408-2068d5c4f9d5-6a0ebc3269c2-linux/Tracker-Changed_Broken_proofs_user_you_dont_follow-2068d5c4f9d5.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468963567408-2068d5c4f9d5-6a0ebc3269c2-linux/Tracker-Changed_Broken_proofs_user_you_dont_follow-6a0ebc3269c2.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1468963567408-2068d5c4f9d5-6a0ebc3269c2-linux/Tracker-Changed_Broken_proofs_user_you_dont_follow.png)
 * Changed: **Tracker-Changed_Broken_proofs** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468963567408-2068d5c4f9d5-6a0ebc3269c2-linux/Tracker-Changed_Broken_proofs-2068d5c4f9d5.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468963567408-2068d5c4f9d5-6a0ebc3269c2-linux/Tracker-Changed_Broken_proofs-6a0ebc3269c2.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1468963567408-2068d5c4f9d5-6a0ebc3269c2-linux/Tracker-Changed_Broken_proofs.png)

**Comment by chromakode** [comment]
Is the "You have now tracked foo" text still centered after this change? It appears to be nudged off center in the visdiff.

**Comment by chromakode** [comment]
:+1: Hack looks sensible. I spent some time with this dragon on the profile sticky scroll UI and found a different workaround that isn't applicable here. I would find a reusable component that does this measurement logic useful. This seems like a challenge that will crop up in other places too.

**Comment by MarcoPolo** [comment]
It's centered in the available screen space, before it was centered assuming the scrollbar width was available.


This only comes up if we have something that overlays where a scrollbar would normally be, which doesn't happen that often (I hope). Let's hold off on making it reusable until we see another need for this elsewhere.

**Comment by keybase-ci-visdiff** [comment]
:mag_right: The commits 2068d5c4f9d5...6a0ebc3269c2 introduced some visual changes on linux:
 * Changed: **Tracker-You_track_them** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468981039460-2068d5c4f9d5-6a0ebc3269c2-linux/Tracker-You_track_them-2068d5c4f9d5.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468981039460-2068d5c4f9d5-6a0ebc3269c2-linux/Tracker-You_track_them-6a0ebc3269c2.png)  
   Tracker-You_track_them comparison
 * Changed: **Tracker-Unfollowed** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468981039460-2068d5c4f9d5-6a0ebc3269c2-linux/Tracker-Unfollowed-2068d5c4f9d5.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468981039460-2068d5c4f9d5-6a0ebc3269c2-linux/Tracker-Unfollowed-6a0ebc3269c2.png)  
   Tracker-Unfollowed comparison
 * Changed: **Tracker-New_user_follows_me** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468981039460-2068d5c4f9d5-6a0ebc3269c2-linux/Tracker-New_user_follows_me-2068d5c4f9d5.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468981039460-2068d5c4f9d5-6a0ebc3269c2-linux/Tracker-New_user_follows_me-6a0ebc3269c2.png)  
   Tracker-New_user_follows_me comparison
 * Changed: **Tracker-New_user_Scroll_2** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468981039460-2068d5c4f9d5-6a0ebc3269c2-linux/Tracker-New_user_Scroll_2-2068d5c4f9d5.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468981039460-2068d5c4f9d5-6a0ebc3269c2-linux/Tracker-New_user_Scroll_2-6a0ebc3269c2.png)  
   Tracker-New_user_Scroll_2 comparison
 * Changed: **Tracker-New_user_Scroll_1** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468981039460-2068d5c4f9d5-6a0ebc3269c2-linux/Tracker-New_user_Scroll_1-2068d5c4f9d5.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468981039460-2068d5c4f9d5-6a0ebc3269c2-linux/Tracker-New_user_Scroll_1-6a0ebc3269c2.png)  
   Tracker-New_user_Scroll_1 comparison
 * Changed: **Tracker-New_user** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468981039460-2068d5c4f9d5-6a0ebc3269c2-linux/Tracker-New_user-2068d5c4f9d5.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468981039460-2068d5c4f9d5-6a0ebc3269c2-linux/Tracker-New_user-6a0ebc3269c2.png)  
   Tracker-New_user comparison
 * Changed: **Tracker-Logged_out** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468981039460-2068d5c4f9d5-6a0ebc3269c2-linux/Tracker-Logged_out-2068d5c4f9d5.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468981039460-2068d5c4f9d5-6a0ebc3269c2-linux/Tracker-Logged_out-6a0ebc3269c2.png)  
   Tracker-Logged_out comparison
 * Changed: **Tracker-Followed** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468981039460-2068d5c4f9d5-6a0ebc3269c2-linux/Tracker-Followed-2068d5c4f9d5.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468981039460-2068d5c4f9d5-6a0ebc3269c2-linux/Tracker-Followed-6a0ebc3269c2.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1468981039460-2068d5c4f9d5-6a0ebc3269c2-linux/Tracker-Followed.png)
 * Changed: **Tracker-Changed_Broken_proofs_user_you_dont_follow** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468981039460-2068d5c4f9d5-6a0ebc3269c2-linux/Tracker-Changed_Broken_proofs_user_you_dont_follow-2068d5c4f9d5.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468981039460-2068d5c4f9d5-6a0ebc3269c2-linux/Tracker-Changed_Broken_proofs_user_you_dont_follow-6a0ebc3269c2.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1468981039460-2068d5c4f9d5-6a0ebc3269c2-linux/Tracker-Changed_Broken_proofs_user_you_dont_follow.png)
 * Changed: **Tracker-Changed_Broken_proofs** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468981039460-2068d5c4f9d5-6a0ebc3269c2-linux/Tracker-Changed_Broken_proofs-2068d5c4f9d5.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468981039460-2068d5c4f9d5-6a0ebc3269c2-linux/Tracker-Changed_Broken_proofs-6a0ebc3269c2.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1468981039460-2068d5c4f9d5-6a0ebc3269c2-linux/Tracker-Changed_Broken_proofs.png)

**Comment by chrisnojima** [comment]
Let's discuss before this goes in. Instead of messing with this we were going to use the WebKit scroll bar overrides

**Pull request closed without merging**
