### PR TITLE
Try focusing input and window Linux - Does not work

### PR DESCRIPTION
**Pull request by MarcoPolo**
For: https://keybase.atlassian.net/browse/DESKTOP-301

Does not fix it. :(

### CODE REVIEW

**Comment by MarcoPolo** [comment]
This is meant to show off, not to merge.

@keybase/react-hackers

**Comment by chrisnojima** [comment]
Does isfocused() return false?

**Comment by chrisnojima** [comment]
What about autofocus flag on a plain input tag (not material Ui)

**Comment by MarcoPolo** [comment]
`browserwindow.isFocused()` returns false, even after calling `browserwindow.focus()`

**Pull request closed without merging**
