### PR TITLE
fix log file location for devel mode

### PR DESCRIPTION
**Pull request by maxtaco**
- It's `~/Library/Logs/KeybaseDevel` for devel now
- It's `~/LibraryLogs/` for prod now.

### CODE REVIEW

**Comment by patrickxb** [comment]
This is only used with the combination of `--log-file` and `--split-log-output`, correct?

**Comment by maxtaco** [comment]
No, it gets there by default if you use `--auto-fork`

**Comment by patrickxb** [comment]
Does this relate at all to this:  https://github.com/keybase/client/pull/1880

**Comment by maxtaco** [comment]
it should be orthogonal

**Comment by patrickxb** [comment]
LGTM.  

auto-fork on darwin seems like a rare case to me, however.

I think we need some better documentation on log files and where they go and under which situations.  Currently unclear.

**Pull request merged**
