### PR TITLE
Kill DZ1

### PR DESCRIPTION
**Pull request by cjb**
Here's a big PR to totally remove DZ1, not intended for merge for a couple days:

- [x] Update components to always call render2(), remove all render1()
- [x] Update common adapters to no longer take a dz2 prop, always render dz2 version
- [x] Remove Noto Sans
- [x] In general, rename e.g. 'styles2' to just 'styles'. 
- [x] Kill current `on{Re,Un}follow` actions, rename `on{Re,Un}follow2` to be the new `on{Re,Un}follow`.
- [x] Move `globalStyles.DZ2.font` to just be `globalStyles.font`
- [x] Remove the DZ1 style sections from the style sheet page
- [x] Check styling of updater popup (was DZ1)
- [x] Check styling of menubar widget (was DZ1)

### CODE REVIEW

**Comment by cjb** [comment]
@keybase/react-hackers

**Comment by chrisnojima** [comment]
just make updater 'sane' we're restyling to dz2 this week

**Comment by cjb** [comment]
yup

**Comment by chrisnojima** [comment]
:+1:

**Comment by cjb** [comment]
Closing in favor of a new branch.

**Pull request closed without merging**
