### PR TITLE
jenkinsfile: Only cascade master builds

### PR DESCRIPTION
**Pull request by jzila**

### CODE REVIEW

**Comment by mmaxim** [comment]
My comment here is the same as on the server repo, but it especially applies here. Given that we don't do any releases without both a pass from client and KBFS, then any failure triggered by client on kbfs-server will show up in kbfs-server tests, and the release will be blocked. But bad PRs will potentially show up since we aren't running the tests on them. So it seems you get the worst of all worlds here, where bad commits will break kbfs-server master, *and* you get a higher chance of a kbfs-server flake blocking releases.

**Comment by jzila** [comment]
@mmaxim: kbfs-server flakes should basically not happen any more. I've increased the retries to 5 on all integration tests.

Additionally, in this repo it's even more important than in kbweb to have master cascade, since we build the kbfs container from the merged client container.

**Comment by jzila** [comment]
@mmaxim: maybe we can have PRs run kbfs only (and not kbfs-server)?

**Comment by mmaxim** [comment]
I thought KBFS repo just used mocks for everything, so there wasn't much chance client could affect it? Either way, I'm fine with this, just wanted to bring up the point from above.

**Pull request merged**
