### PR TITLE
Use go-updater

### PR DESCRIPTION
**Pull request by gabriel**
Updater was moved using these commands:
https://gist.github.com/gabriel/48aef98359e6c983150b

These changes were done by running:
```
git checkout -b gabriel/move-updater
git rm -rf updater
# Rewrite all github.com/keybase/client/go/updater
govendor add github.com/keybase/go-updater
govendor add github.com/keybase/go-updater/sources
```

This is the same as saltpack move.

### CODE REVIEW

**Comment by gabriel** [comment]
cc @maxtaco @cjb

**Comment by cjb** [comment]
took a look with max, LGTU

**Comment by gabriel** [comment]
@maxtaco @cjb

**Comment by maxtaco** [comment]
yes, see comment above! "LGTU" = "looks good to us" ;)

**Pull request merged**
