### PR TITLE
more incoming cleanup: notifications + settings

### PR DESCRIPTION
**Pull request by chrisnojima**
@keybase/react-hackers

### CODE REVIEW

**Comment by chrisnojima** [comment]
@keybase/react-hackers bump

**Comment by zanderz** [comment]
Sanity checked on windows and mac. Mac one never got past loading screen if I start it without prod keybase already running, but windows one seemed to ok.

**Comment by chrisnojima** [comment]
its not really safe to run mulitple copies at the same time. ui calls get all messed up

**Comment by zanderz** [comment]
whoops, my mistake, that case doesn't work on master either for Mac. Does on windows though.
But I've always run them side by side, usually it's fine? how do you run it otherwise?

**Comment by chrisnojima** [comment]
some stuff works side by side but some calls (like delegation of ui stuff) the daemon only allows one thing to be registered

**Pull request merged**
