### PR TITLE
key_manager: don't error when key gen is too big

### PR DESCRIPTION
**Pull request by strib**
There was an iteam migration race that could have left the `LatestKeyGeneration` of the migrated MD too small.  Instead of erroring in that case, just print a message and let later code take care of the error if the key really doesn't exist.

Issue: KBFS-3774

### CODE REVIEW

**Comment by strib** [comment]
Merging unreviewed with @songgao's permission.

**Comment by songgao** [comment]
Could you explain the race a little bit? I think I’m lacking some context to understand the fix.

**Comment by strib** [comment]
@songgao did you read the bulleted explanation in the linked JIRA issue?  https://keybase.atlassian.net/browse/KBFS-3774

**Comment by songgao** [comment]
Oh I opened the ticket on my phone and it had the description collapsed, so I only read the comment. The ticket body looks helpful thanks!

**Pull request merged**
