### PR TITLE
move make gen-deps

### PR DESCRIPTION
**Pull request by joshblum**

### CODE REVIEW

**Comment by joshblum** [comment]
@jzila why not just generate per os when we need this file as noted in the TODO? i don't know perl and wanted to get this fix out so builds aren't breaking.. also any idea why master has passed on my recent tweaks to this but then PRs start failing? i thought any change to the jenkins file would trigger a full build

**Comment by jzila** [comment]
@joshblum because master builds don't depend on `make gen-deps`, and neither do Jenkinsfile changes.

**Comment by jzila** [comment]
I'm off this week but I can take a look tonight. I'd roll back to the previous `make gen-deps` situation, and I'll make it all work tonight.

**Comment by joshblum** [comment]
oops i misspoke before i meant my PRs with the changes pass but then subsequent prs fail

**Comment by jzila** [comment]
We can't call per-OS as is right now because only Linux machines have perl installed. Running per-OS loses a lot more parallelism since we'll have a bunch of Linux cores unused during dep calculation, and we'll have the slow macos machines busy working calculating dependencies.

**Pull request closed without merging**
