### PR TITLE
Fix flag parsing

### PR DESCRIPTION
**Pull request by patrickxb**

### CODE REVIEW

**Comment by maxtaco** [comment]
What sort of error message do you get if you invite a user over email as an admin?

**Comment by patrickxb** [comment]
none.  only owner is prevented:

```> kbcl -d=0 team add-member hheeyy -e pcrosby@gmail.co -r owner
▶ WARNING Running in devel mode
▶ WARNING not exportable error: invalid role for invitation (*errors.errorString)
▶ ERROR invalid role for invitation```

**Comment by maxtaco** [comment]
We should fix this so it looks good. @malgorithms will definitely want it

**Comment by maxtaco** [comment]
`You can't invite an owner to a group over email` or some such

**Comment by patrickxb** [comment]
Isn't there a ticket for fixing all the error messages?

**Comment by maxtaco** [comment]
Not really, chris has been making error messages as he sees them.  I'd fix it here.

**Comment by maxtaco** [comment]
If you want to grab that ticket next, you can fold it in.

**Pull request merged**
