### PR TITLE
Vendor rpc library and update imports

### PR DESCRIPTION
**Pull request by akalin-keybase**
Also vendor cldr library.

Remove unused go.iced script.

### CODE REVIEW

**Comment by akalin-keybase** [comment]
I built the protocol files with a local version with https://github.com/keybase/node-avdl-compiler/pull/8 . Then I guess when you do the npm push we could peg to that version?

**Comment by akalin-keybase** [comment]
Okay, also bumped avdl-compiler to 1.3.9.

**Comment by maxtaco** [comment]
👍

**Comment by akalin-keybase** [comment]
circleci failure is expected (since it depends on kbfs)

**Pull request merged**
