### PR TITLE
Hook up proof revoke on mobile

### PR DESCRIPTION
**Pull request by cjb**
@keybase/react-hackers 

Just reuses the desktop component, and fixes a crash if you have the popup menu open while proofs are reloading in the background.

### CODE REVIEW

**Comment by keybase-ci-visdiff** [comment]
The commits f59fbd24c1d4...de19c59b45e4 introduce visual changes on linux. <details><summary>:mag_right: 13 changed</summary>

 * Changed: **Revoke_Proof-https_website** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490133250536-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-https_website-f59fbd24c1d4.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490133250536-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-https_website-de19c59b45e4.png)  
   Revoke_Proof-https_website comparison
 * Changed: **Revoke_Proof-Zcash** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490133250536-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Zcash-f59fbd24c1d4.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490133250536-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Zcash-de19c59b45e4.png)  
   Revoke_Proof-Zcash comparison
 * Changed: **Revoke_Proof-Website** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490133250536-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Website-f59fbd24c1d4.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490133250536-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Website-de19c59b45e4.png)  
   Revoke_Proof-Website comparison
 * Changed: **Revoke_Proof-Twitter_Waiting** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490133250536-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Twitter_Waiting-f59fbd24c1d4.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490133250536-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Twitter_Waiting-de19c59b45e4.png)  
   Revoke_Proof-Twitter_Waiting comparison
 * Changed: **Revoke_Proof-Twitter_Error** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490133250536-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Twitter_Error-f59fbd24c1d4.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490133250536-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Twitter_Error-de19c59b45e4.png)  
   Revoke_Proof-Twitter_Error comparison
 * Changed: **Revoke_Proof-Twitter** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490133250536-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Twitter-f59fbd24c1d4.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490133250536-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Twitter-de19c59b45e4.png)  
   Revoke_Proof-Twitter comparison
 * Changed: **Revoke_Proof-Reddit** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490133250536-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Reddit-f59fbd24c1d4.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490133250536-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Reddit-de19c59b45e4.png)  
   Revoke_Proof-Reddit comparison
 * Changed: **Revoke_Proof-Hacker_News** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490133250536-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Hacker_News-f59fbd24c1d4.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490133250536-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Hacker_News-de19c59b45e4.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490133250536-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Hacker_News.png)
 * Changed: **Revoke_Proof-Git_Hub** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490133250536-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Git_Hub-f59fbd24c1d4.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490133250536-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Git_Hub-de19c59b45e4.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490133250536-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Git_Hub.png)
 * Changed: **Revoke_Proof-Facebook** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490133250536-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Facebook-f59fbd24c1d4.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490133250536-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Facebook-de19c59b45e4.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490133250536-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Facebook.png)
 * Changed: **Revoke_Proof-DNS** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490133250536-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-DNS-f59fbd24c1d4.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490133250536-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-DNS-de19c59b45e4.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490133250536-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-DNS.png)
 * Changed: **Revoke_Proof-Coinbase** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490133250536-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Coinbase-f59fbd24c1d4.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490133250536-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Coinbase-de19c59b45e4.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490133250536-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Coinbase.png)
 * Changed: **Revoke_Proof-Bitcoin** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490133250536-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Bitcoin-f59fbd24c1d4.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490133250536-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Bitcoin-de19c59b45e4.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490133250536-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Bitcoin.png)
</summary>

**Comment by keybase-ci-visdiff** [comment]
The commits f59fbd24c1d4...de19c59b45e4 introduce visual changes on linux. <details><summary>:mag_right: 13 changed</summary>

 * Changed: **Revoke_Proof-https_website** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490194699900-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-https_website-f59fbd24c1d4.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490194699900-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-https_website-de19c59b45e4.png)  
   Revoke_Proof-https_website comparison
 * Changed: **Revoke_Proof-Zcash** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490194699900-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Zcash-f59fbd24c1d4.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490194699900-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Zcash-de19c59b45e4.png)  
   Revoke_Proof-Zcash comparison
 * Changed: **Revoke_Proof-Website** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490194699900-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Website-f59fbd24c1d4.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490194699900-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Website-de19c59b45e4.png)  
   Revoke_Proof-Website comparison
 * Changed: **Revoke_Proof-Twitter_Waiting** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490194699900-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Twitter_Waiting-f59fbd24c1d4.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490194699900-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Twitter_Waiting-de19c59b45e4.png)  
   Revoke_Proof-Twitter_Waiting comparison
 * Changed: **Revoke_Proof-Twitter_Error** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490194699900-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Twitter_Error-f59fbd24c1d4.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490194699900-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Twitter_Error-de19c59b45e4.png)  
   Revoke_Proof-Twitter_Error comparison
 * Changed: **Revoke_Proof-Twitter** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490194699900-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Twitter-f59fbd24c1d4.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490194699900-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Twitter-de19c59b45e4.png)  
   Revoke_Proof-Twitter comparison
 * Changed: **Revoke_Proof-Reddit** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490194699900-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Reddit-f59fbd24c1d4.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490194699900-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Reddit-de19c59b45e4.png)  
   Revoke_Proof-Reddit comparison
 * Changed: **Revoke_Proof-Hacker_News** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490194699900-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Hacker_News-f59fbd24c1d4.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490194699900-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Hacker_News-de19c59b45e4.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490194699900-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Hacker_News.png)
 * Changed: **Revoke_Proof-Git_Hub** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490194699900-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Git_Hub-f59fbd24c1d4.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490194699900-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Git_Hub-de19c59b45e4.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490194699900-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Git_Hub.png)
 * Changed: **Revoke_Proof-Facebook** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490194699900-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Facebook-f59fbd24c1d4.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490194699900-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Facebook-de19c59b45e4.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490194699900-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Facebook.png)
 * Changed: **Revoke_Proof-DNS** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490194699900-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-DNS-f59fbd24c1d4.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490194699900-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-DNS-de19c59b45e4.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490194699900-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-DNS.png)
 * Changed: **Revoke_Proof-Coinbase** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490194699900-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Coinbase-f59fbd24c1d4.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490194699900-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Coinbase-de19c59b45e4.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490194699900-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Coinbase.png)
 * Changed: **Revoke_Proof-Bitcoin** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490194699900-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Bitcoin-f59fbd24c1d4.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490194699900-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Bitcoin-de19c59b45e4.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490194699900-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Bitcoin.png)
</summary>

**Comment by keybase-ci-visdiff** [comment]
The commits f59fbd24c1d4...de19c59b45e4 introduce visual changes on linux. <details><summary>:mag_right: 13 changed</summary>

 * Changed: **Revoke_Proof-https_website** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490200259597-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-https_website-f59fbd24c1d4.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490200259597-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-https_website-de19c59b45e4.png)  
   Revoke_Proof-https_website comparison
 * Changed: **Revoke_Proof-Zcash** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490200259597-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Zcash-f59fbd24c1d4.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490200259597-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Zcash-de19c59b45e4.png)  
   Revoke_Proof-Zcash comparison
 * Changed: **Revoke_Proof-Website** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490200259597-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Website-f59fbd24c1d4.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490200259597-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Website-de19c59b45e4.png)  
   Revoke_Proof-Website comparison
 * Changed: **Revoke_Proof-Twitter_Waiting** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490200259597-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Twitter_Waiting-f59fbd24c1d4.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490200259597-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Twitter_Waiting-de19c59b45e4.png)  
   Revoke_Proof-Twitter_Waiting comparison
 * Changed: **Revoke_Proof-Twitter_Error** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490200259597-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Twitter_Error-f59fbd24c1d4.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490200259597-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Twitter_Error-de19c59b45e4.png)  
   Revoke_Proof-Twitter_Error comparison
 * Changed: **Revoke_Proof-Twitter** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490200259597-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Twitter-f59fbd24c1d4.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490200259597-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Twitter-de19c59b45e4.png)  
   Revoke_Proof-Twitter comparison
 * Changed: **Revoke_Proof-Reddit** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490200259597-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Reddit-f59fbd24c1d4.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490200259597-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Reddit-de19c59b45e4.png)  
   Revoke_Proof-Reddit comparison
 * Changed: **Revoke_Proof-Hacker_News** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490200259597-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Hacker_News-f59fbd24c1d4.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490200259597-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Hacker_News-de19c59b45e4.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490200259597-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Hacker_News.png)
 * Changed: **Revoke_Proof-Git_Hub** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490200259597-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Git_Hub-f59fbd24c1d4.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490200259597-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Git_Hub-de19c59b45e4.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490200259597-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Git_Hub.png)
 * Changed: **Revoke_Proof-Facebook** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490200259597-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Facebook-f59fbd24c1d4.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490200259597-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Facebook-de19c59b45e4.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490200259597-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Facebook.png)
 * Changed: **Revoke_Proof-DNS** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490200259597-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-DNS-f59fbd24c1d4.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490200259597-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-DNS-de19c59b45e4.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490200259597-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-DNS.png)
 * Changed: **Revoke_Proof-Coinbase** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490200259597-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Coinbase-f59fbd24c1d4.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490200259597-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Coinbase-de19c59b45e4.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490200259597-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Coinbase.png)
 * Changed: **Revoke_Proof-Bitcoin** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490200259597-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Bitcoin-f59fbd24c1d4.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490200259597-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Bitcoin-de19c59b45e4.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490200259597-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Bitcoin.png)
</summary>

**Comment by keybase-ci-visdiff** [comment]
The commits f59fbd24c1d4...de19c59b45e4 introduce visual changes on linux. <details><summary>:mag_right: 13 changed</summary>

 * Changed: **Revoke_Proof-https_website** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490206073765-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-https_website-f59fbd24c1d4.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490206073765-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-https_website-de19c59b45e4.png)  
   Revoke_Proof-https_website comparison
 * Changed: **Revoke_Proof-Zcash** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490206073765-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Zcash-f59fbd24c1d4.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490206073765-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Zcash-de19c59b45e4.png)  
   Revoke_Proof-Zcash comparison
 * Changed: **Revoke_Proof-Website** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490206073765-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Website-f59fbd24c1d4.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490206073765-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Website-de19c59b45e4.png)  
   Revoke_Proof-Website comparison
 * Changed: **Revoke_Proof-Twitter_Waiting** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490206073765-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Twitter_Waiting-f59fbd24c1d4.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490206073765-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Twitter_Waiting-de19c59b45e4.png)  
   Revoke_Proof-Twitter_Waiting comparison
 * Changed: **Revoke_Proof-Twitter_Error** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490206073765-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Twitter_Error-f59fbd24c1d4.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490206073765-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Twitter_Error-de19c59b45e4.png)  
   Revoke_Proof-Twitter_Error comparison
 * Changed: **Revoke_Proof-Twitter** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490206073765-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Twitter-f59fbd24c1d4.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490206073765-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Twitter-de19c59b45e4.png)  
   Revoke_Proof-Twitter comparison
 * Changed: **Revoke_Proof-Reddit** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490206073765-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Reddit-f59fbd24c1d4.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490206073765-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Reddit-de19c59b45e4.png)  
   Revoke_Proof-Reddit comparison
 * Changed: **Revoke_Proof-Hacker_News** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490206073765-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Hacker_News-f59fbd24c1d4.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490206073765-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Hacker_News-de19c59b45e4.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490206073765-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Hacker_News.png)
 * Changed: **Revoke_Proof-Git_Hub** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490206073765-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Git_Hub-f59fbd24c1d4.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490206073765-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Git_Hub-de19c59b45e4.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490206073765-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Git_Hub.png)
 * Changed: **Revoke_Proof-Facebook** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490206073765-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Facebook-f59fbd24c1d4.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490206073765-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Facebook-de19c59b45e4.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490206073765-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Facebook.png)
 * Changed: **Revoke_Proof-DNS** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490206073765-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-DNS-f59fbd24c1d4.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490206073765-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-DNS-de19c59b45e4.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490206073765-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-DNS.png)
 * Changed: **Revoke_Proof-Coinbase** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490206073765-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Coinbase-f59fbd24c1d4.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490206073765-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Coinbase-de19c59b45e4.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490206073765-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Coinbase.png)
 * Changed: **Revoke_Proof-Bitcoin** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490206073765-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Bitcoin-f59fbd24c1d4.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490206073765-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Bitcoin-de19c59b45e4.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490206073765-f59fbd24c1d4-de19c59b45e4-linux/Revoke_Proof-Bitcoin.png)
</summary>

**Comment by cjb** [comment]
@keybase/react-hackers bump

**Comment by cjb** [comment]
@keybase/react-hackers bump

**Pull request merged**
