### PR TITLE
Box2: flexShrink 0. alignSelf props. Text center prop

### PR DESCRIPTION
**Pull request by chrisnojima**
@keybase/react-hackers this adds some props that are commonly needed which force us to pass custom styles to Box2 and Text

you can now do
```
<Box2 direction='vertical'>
  <Box2 direction ='horizontal' alignSelf='flex-start'>
```

or

```
<Text type='Header' center={true}>SOMETHING</Text>
```

cc: @cecileboucheron @adamjspooner

### CODE REVIEW

**Comment by chrisnojima** [comment]
Maybe text should also be shrink 0

**Comment by buoyad** [comment]
And ellipsize by default? It'd be nice if the adapters made that easier, I think making it the default would break more than it fixes though.

**Comment by chrisnojima** [comment]
k i'm switching this to be opt in easier, i'll add shrink={false}

**Comment by chrisnojima** [comment]
@keybase/react-hackers @buoyad updated. also applied center={true} to a ton of text

**Pull request merged**
