### PR TITLE
ignore sharing before signup for metadata

### PR DESCRIPTION
**Pull request by chrisnojima**
Fixes an issue @patrickxb found

@keybase/react-hackers

### CODE REVIEW

**Comment by keybase-ci-visdiff** [comment]
The commits 973da137e216...2727bb36a9e4 introduce visual changes on linux. <details><summary>:mag_right: 10 new, 19 changed</summary>

 * Added: **Chat_Side_Panel-Normal**  
   Chat_Side_Panel-Normal rendered
 * Added: **Chat_Side_Panel-Empty**  
   Chat_Side_Panel-Empty rendered
 * Added: **Chat_List-Normal**  
   Chat_List-Normal rendered
 * Added: **Chat_List-Empty**  
   Chat_List-Empty rendered
 * Added: **Chat_Input-Normal**  
   Chat_Input-Normal rendered
 * Added: **Chat_Input-Empty**  
   Chat_Input-Empty rendered
 * Added: **Chat_Header-Normal**  
   Chat_Header-Normal rendered
 * Added: **Chat_Header-Empty** [(view)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479752368438-973da137e216-2727bb36a9e4-linux/Chat_Header-Empty-2727bb36a9e4.png)
 * Added: **Chat_Conversations_List-Normal** [(view)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479752368438-973da137e216-2727bb36a9e4-linux/Chat_Conversations_List-Normal-2727bb36a9e4.png)
 * Added: **Chat_Conversations_List-Empty** [(view)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479752368438-973da137e216-2727bb36a9e4-linux/Chat_Conversations_List-Empty-2727bb36a9e4.png)
 * Changed: **Search-Chat_enabled** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479752368438-973da137e216-2727bb36a9e4-linux/Search-Chat_enabled-973da137e216.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479752368438-973da137e216-2727bb36a9e4-linux/Search-Chat_enabled-2727bb36a9e4.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479752368438-973da137e216-2727bb36a9e4-linux/Search-Chat_enabled.png)
 * Changed: **Profile-Your_Profile_Proof_Menu** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479752368438-973da137e216-2727bb36a9e4-linux/Profile-Your_Profile_Proof_Menu-973da137e216.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479752368438-973da137e216-2727bb36a9e4-linux/Profile-Your_Profile_Proof_Menu-2727bb36a9e4.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479752368438-973da137e216-2727bb36a9e4-linux/Profile-Your_Profile_Proof_Menu.png)
 * Changed: **Profile-Your_Profile_Pending_Proof_Menu_HN** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479752368438-973da137e216-2727bb36a9e4-linux/Profile-Your_Profile_Pending_Proof_Menu_HN-973da137e216.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479752368438-973da137e216-2727bb36a9e4-linux/Profile-Your_Profile_Pending_Proof_Menu_HN-2727bb36a9e4.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479752368438-973da137e216-2727bb36a9e4-linux/Profile-Your_Profile_Pending_Proof_Menu_HN.png)
 * Changed: **Profile-Your_Profile_Pending_Proof_Menu_DNS** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479752368438-973da137e216-2727bb36a9e4-linux/Profile-Your_Profile_Pending_Proof_Menu_DNS-973da137e216.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479752368438-973da137e216-2727bb36a9e4-linux/Profile-Your_Profile_Pending_Proof_Menu_DNS-2727bb36a9e4.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479752368438-973da137e216-2727bb36a9e4-linux/Profile-Your_Profile_Pending_Proof_Menu_DNS.png)
 * Changed: **Profile-Your_Profile_Pending_Proof_Menu** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479752368438-973da137e216-2727bb36a9e4-linux/Profile-Your_Profile_Pending_Proof_Menu-973da137e216.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479752368438-973da137e216-2727bb36a9e4-linux/Profile-Your_Profile_Pending_Proof_Menu-2727bb36a9e4.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479752368438-973da137e216-2727bb36a9e4-linux/Profile-Your_Profile_Pending_Proof_Menu.png)
 * Changed: **Profile-Your_Profile_No_Proofs** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479752368438-973da137e216-2727bb36a9e4-linux/Profile-Your_Profile_No_Proofs-973da137e216.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479752368438-973da137e216-2727bb36a9e4-linux/Profile-Your_Profile_No_Proofs-2727bb36a9e4.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479752368438-973da137e216-2727bb36a9e4-linux/Profile-Your_Profile_No_Proofs.png)
 * Changed: **Profile-Your_Profile_Empty** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479752368438-973da137e216-2727bb36a9e4-linux/Profile-Your_Profile_Empty-973da137e216.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479752368438-973da137e216-2727bb36a9e4-linux/Profile-Your_Profile_Empty-2727bb36a9e4.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479752368438-973da137e216-2727bb36a9e4-linux/Profile-Your_Profile_Empty.png)
 * Changed: **Profile-Your_Profile_Broken_Proof_Menu** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479752368438-973da137e216-2727bb36a9e4-linux/Profile-Your_Profile_Broken_Proof_Menu-973da137e216.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479752368438-973da137e216-2727bb36a9e4-linux/Profile-Your_Profile_Broken_Proof_Menu-2727bb36a9e4.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479752368438-973da137e216-2727bb36a9e4-linux/Profile-Your_Profile_Broken_Proof_Menu.png)
 * Changed: **Profile-Your_Profile_Broken** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479752368438-973da137e216-2727bb36a9e4-linux/Profile-Your_Profile_Broken-973da137e216.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479752368438-973da137e216-2727bb36a9e4-linux/Profile-Your_Profile_Broken-2727bb36a9e4.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479752368438-973da137e216-2727bb36a9e4-linux/Profile-Your_Profile_Broken.png)
 * Changed: **Profile-Your_Profile** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479752368438-973da137e216-2727bb36a9e4-linux/Profile-Your_Profile-973da137e216.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479752368438-973da137e216-2727bb36a9e4-linux/Profile-Your_Profile-2727bb36a9e4.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479752368438-973da137e216-2727bb36a9e4-linux/Profile-Your_Profile.png)
 * Changed: **Profile-Unfollowed_Scrolled** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479752368438-973da137e216-2727bb36a9e4-linux/Profile-Unfollowed_Scrolled-973da137e216.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479752368438-973da137e216-2727bb36a9e4-linux/Profile-Unfollowed_Scrolled-2727bb36a9e4.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479752368438-973da137e216-2727bb36a9e4-linux/Profile-Unfollowed_Scrolled.png)
 * Changed: **Profile-Unfollowed_Profile_page** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479752368438-973da137e216-2727bb36a9e4-linux/Profile-Unfollowed_Profile_page-973da137e216.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479752368438-973da137e216-2727bb36a9e4-linux/Profile-Unfollowed_Profile_page-2727bb36a9e4.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479752368438-973da137e216-2727bb36a9e4-linux/Profile-Unfollowed_Profile_page.png)
 * Changed: **Profile-Unfollowed_Folders_Expanded** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479752368438-973da137e216-2727bb36a9e4-linux/Profile-Unfollowed_Folders_Expanded-973da137e216.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479752368438-973da137e216-2727bb36a9e4-linux/Profile-Unfollowed_Folders_Expanded-2727bb36a9e4.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479752368438-973da137e216-2727bb36a9e4-linux/Profile-Unfollowed_Folders_Expanded.png)
 * Changed: **Profile-Unfollowed_Few_Folders** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479752368438-973da137e216-2727bb36a9e4-linux/Profile-Unfollowed_Few_Folders-973da137e216.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479752368438-973da137e216-2727bb36a9e4-linux/Profile-Unfollowed_Few_Folders-2727bb36a9e4.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479752368438-973da137e216-2727bb36a9e4-linux/Profile-Unfollowed_Few_Folders.png)
 * Changed: **Profile-Unfollowed** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479752368438-973da137e216-2727bb36a9e4-linux/Profile-Unfollowed-973da137e216.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479752368438-973da137e216-2727bb36a9e4-linux/Profile-Unfollowed-2727bb36a9e4.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479752368438-973da137e216-2727bb36a9e4-linux/Profile-Unfollowed.png)
 * Changed: **Profile-Followed** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479752368438-973da137e216-2727bb36a9e4-linux/Profile-Followed-973da137e216.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479752368438-973da137e216-2727bb36a9e4-linux/Profile-Followed-2727bb36a9e4.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479752368438-973da137e216-2727bb36a9e4-linux/Profile-Followed.png)
 * Changed: **Profile-Changed_Scrolled** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479752368438-973da137e216-2727bb36a9e4-linux/Profile-Changed_Scrolled-973da137e216.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479752368438-973da137e216-2727bb36a9e4-linux/Profile-Changed_Scrolled-2727bb36a9e4.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479752368438-973da137e216-2727bb36a9e4-linux/Profile-Changed_Scrolled.png)
 * Changed: **Profile-Changed** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479752368438-973da137e216-2727bb36a9e4-linux/Profile-Changed-973da137e216.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479752368438-973da137e216-2727bb36a9e4-linux/Profile-Changed-2727bb36a9e4.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479752368438-973da137e216-2727bb36a9e4-linux/Profile-Changed.png)
 * Changed: **Folders_Clear_History_Confirmation-Long_Name_Public** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479752368438-973da137e216-2727bb36a9e4-linux/Folders_Clear_History_Confirmation-Long_Name_Public-973da137e216.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479752368438-973da137e216-2727bb36a9e4-linux/Folders_Clear_History_Confirmation-Long_Name_Public-2727bb36a9e4.png) [(diff)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479752368438-973da137e216-2727bb36a9e4-linux/Folders_Clear_History_Confirmation-Long_Name_Public.png)
</summary>

**Comment by keybase-ci-visdiff** [comment]
The commits 4022693e454e...e89d225f45a4 introduce visual changes on linux. <details><summary>:mag_right: 2 new, 5 changed</summary>

 * Added: **Chat_Side_Panel-Normal**  
   Chat_Side_Panel-Normal rendered
 * Added: **Chat_Side_Panel-Empty**  
   Chat_Side_Panel-Empty rendered
 * Changed: **Chat_Input-Normal** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479753486316-4022693e454e-e89d225f45a4-linux/Chat_Input-Normal-4022693e454e.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479753486316-4022693e454e-e89d225f45a4-linux/Chat_Input-Normal-e89d225f45a4.png)  
   Chat_Input-Normal comparison
 * Changed: **Chat_Input-Empty** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479753486316-4022693e454e-e89d225f45a4-linux/Chat_Input-Empty-4022693e454e.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479753486316-4022693e454e-e89d225f45a4-linux/Chat_Input-Empty-e89d225f45a4.png)  
   Chat_Input-Empty comparison
 * Changed: **Chat_Header-Normal** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479753486316-4022693e454e-e89d225f45a4-linux/Chat_Header-Normal-4022693e454e.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479753486316-4022693e454e-e89d225f45a4-linux/Chat_Header-Normal-e89d225f45a4.png)  
   Chat_Header-Normal comparison
 * Changed: **Chat_Header-Empty** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479753486316-4022693e454e-e89d225f45a4-linux/Chat_Header-Empty-4022693e454e.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479753486316-4022693e454e-e89d225f45a4-linux/Chat_Header-Empty-e89d225f45a4.png)  
   Chat_Header-Empty comparison
 * Changed: **Chat_Conversations_List-Normal** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479753486316-4022693e454e-e89d225f45a4-linux/Chat_Conversations_List-Normal-4022693e454e.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479753486316-4022693e454e-e89d225f45a4-linux/Chat_Conversations_List-Normal-e89d225f45a4.png)  
   Chat_Conversations_List-Normal comparison
</summary>

**Comment by keybase-ci-visdiff** [comment]
The commits 4022693e454e...e89d225f45a4 introduce visual changes on linux. <details><summary>:mag_right: 2 new, 5 changed</summary>

 * Added: **Chat_Side_Panel-Normal**  
   Chat_Side_Panel-Normal rendered
 * Added: **Chat_Side_Panel-Empty**  
   Chat_Side_Panel-Empty rendered
 * Changed: **Chat_Input-Normal** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479768563657-4022693e454e-e89d225f45a4-linux/Chat_Input-Normal-4022693e454e.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479768563657-4022693e454e-e89d225f45a4-linux/Chat_Input-Normal-e89d225f45a4.png)  
   Chat_Input-Normal comparison
 * Changed: **Chat_Input-Empty** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479768563657-4022693e454e-e89d225f45a4-linux/Chat_Input-Empty-4022693e454e.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479768563657-4022693e454e-e89d225f45a4-linux/Chat_Input-Empty-e89d225f45a4.png)  
   Chat_Input-Empty comparison
 * Changed: **Chat_Header-Normal** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479768563657-4022693e454e-e89d225f45a4-linux/Chat_Header-Normal-4022693e454e.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479768563657-4022693e454e-e89d225f45a4-linux/Chat_Header-Normal-e89d225f45a4.png)  
   Chat_Header-Normal comparison
 * Changed: **Chat_Header-Empty** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479768563657-4022693e454e-e89d225f45a4-linux/Chat_Header-Empty-4022693e454e.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479768563657-4022693e454e-e89d225f45a4-linux/Chat_Header-Empty-e89d225f45a4.png)  
   Chat_Header-Empty comparison
 * Changed: **Chat_Conversations_List-Normal** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479768563657-4022693e454e-e89d225f45a4-linux/Chat_Conversations_List-Normal-4022693e454e.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1479768563657-4022693e454e-e89d225f45a4-linux/Chat_Conversations_List-Normal-e89d225f45a4.png)  
   Chat_Conversations_List-Normal comparison
</summary>

**Comment by gabriel** [comment]
The server could ignore it?

**Comment by chrisnojima** [comment]
Spoke to Coyne at length about this option and concluded this is the
easiest fix

**Comment by chrisnojima** [comment]
Basically he API server does broad validation of all inputs so if we had it
return nulls they'd have to give us a new endpoint. Other option was to
make sep. calls for each username but this should work fine also.

**Pull request merged**
