### PR TITLE
StandardScreen visual tweaks

### PR DESCRIPTION
**Pull request by chromakode**
Two small fixes:

 * Push down the close button when a notification is showing
 * Add padding to the bottom of the screen to maintain vertical centering if both a notification and back button are showing.

screen shot 2016-09-16 at 4 45 39 pm

:eyeglasses: @keybase/react-hackers

### CODE REVIEW

**Comment by keybase-ci-visdiff** [comment]
:mag_right: The commits dd890adca164...5c2ee693317c introduced some visual changes on linux:
 * Changed: **Update_Passphrase-Error_Wrong_Passphrase** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1474401830097-dd890adca164-5c2ee693317c-linux/Update_Passphrase-Error_Wrong_Passphrase-dd890adca164.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1474401830097-dd890adca164-5c2ee693317c-linux/Update_Passphrase-Error_Wrong_Passphrase-5c2ee693317c.png)  
   Update_Passphrase-Error_Wrong_Passphrase comparison
 * Changed: **Standard_Screen-Success_w_Custom_Notification_Element** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1474401830097-dd890adca164-5c2ee693317c-linux/Standard_Screen-Success_w_Custom_Notification_Element-dd890adca164.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1474401830097-dd890adca164-5c2ee693317c-linux/Standard_Screen-Success_w_Custom_Notification_Element-5c2ee693317c.png)  
   Standard_Screen-Success_w_Custom_Notification_Element comparison
 * Changed: **Standard_Screen-Normal** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1474401830097-dd890adca164-5c2ee693317c-linux/Standard_Screen-Normal-dd890adca164.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1474401830097-dd890adca164-5c2ee693317c-linux/Standard_Screen-Normal-5c2ee693317c.png)  
   Standard_Screen-Normal comparison
 * Changed: **Standard_Screen-Error_w_Back_Button** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1474401830097-dd890adca164-5c2ee693317c-linux/Standard_Screen-Error_w_Back_Button-dd890adca164.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1474401830097-dd890adca164-5c2ee693317c-linux/Standard_Screen-Error_w_Back_Button-5c2ee693317c.png)  
   Standard_Screen-Error_w_Back_Button comparison
 * Changed: **Standard_Screen-Error** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1474401830097-dd890adca164-5c2ee693317c-linux/Standard_Screen-Error-dd890adca164.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1474401830097-dd890adca164-5c2ee693317c-linux/Standard_Screen-Error-5c2ee693317c.png)  
   Standard_Screen-Error comparison
 * Changed: **Standard_Screen-Back_Button** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1474401830097-dd890adca164-5c2ee693317c-linux/Standard_Screen-Back_Button-dd890adca164.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1474401830097-dd890adca164-5c2ee693317c-linux/Standard_Screen-Back_Button-5c2ee693317c.png)  
   Standard_Screen-Back_Button comparison
 * Changed: **New_Proof_Website-DNS_or_File** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1474401830097-dd890adca164-5c2ee693317c-linux/New_Proof_Website-DNS_or_File-dd890adca164.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1474401830097-dd890adca164-5c2ee693317c-linux/New_Proof_Website-DNS_or_File-5c2ee693317c.png)  
   New_Proof_Website-DNS_or_File comparison
 * Changed: **New_Proof_PGP_import-Import_PGP** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1474401830097-dd890adca164-5c2ee693317c-linux/New_Proof_PGP_import-Import_PGP-dd890adca164.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1474401830097-dd890adca164-5c2ee693317c-linux/New_Proof_PGP_import-Import_PGP-5c2ee693317c.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1474401830097-dd890adca164-5c2ee693317c-linux/New_Proof_PGP_import-Import_PGP.png)
 * Changed: **New_Proof_PGP_generating-Generating_PGP** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1474401830097-dd890adca164-5c2ee693317c-linux/New_Proof_PGP_generating-Generating_PGP-dd890adca164.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1474401830097-dd890adca164-5c2ee693317c-linux/New_Proof_PGP_generating-Generating_PGP-5c2ee693317c.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1474401830097-dd890adca164-5c2ee693317c-linux/New_Proof_PGP_generating-Generating_PGP.png)
 * Changed: **New_Proof_PGP_add-One_Error_Email** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1474401830097-dd890adca164-5c2ee693317c-linux/New_Proof_PGP_add-One_Error_Email-dd890adca164.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1474401830097-dd890adca164-5c2ee693317c-linux/New_Proof_PGP_add-One_Error_Email-5c2ee693317c.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1474401830097-dd890adca164-5c2ee693317c-linux/New_Proof_PGP_add-One_Error_Email.png)
 * Changed: **New_Proof_PGP_add-Normal** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1474401830097-dd890adca164-5c2ee693317c-linux/New_Proof_PGP_add-Normal-dd890adca164.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1474401830097-dd890adca164-5c2ee693317c-linux/New_Proof_PGP_add-Normal-5c2ee693317c.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1474401830097-dd890adca164-5c2ee693317c-linux/New_Proof_PGP_add-Normal.png)
 * Changed: **New_Proof_PGP_add-Empty** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1474401830097-dd890adca164-5c2ee693317c-linux/New_Proof_PGP_add-Empty-dd890adca164.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1474401830097-dd890adca164-5c2ee693317c-linux/New_Proof_PGP_add-Empty-5c2ee693317c.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1474401830097-dd890adca164-5c2ee693317c-linux/New_Proof_PGP_add-Empty.png)
 * Changed: **New_Proof_PGP-Import_or_Generate** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1474401830097-dd890adca164-5c2ee693317c-linux/New_Proof_PGP-Import_or_Generate-dd890adca164.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1474401830097-dd890adca164-5c2ee693317c-linux/New_Proof_PGP-Import_or_Generate-5c2ee693317c.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1474401830097-dd890adca164-5c2ee693317c-linux/New_Proof_PGP-Import_or_Generate.png)
 * Changed: **Folders_Ignore_Confirmation-Normal_Public** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1474401830097-dd890adca164-5c2ee693317c-linux/Folders_Ignore_Confirmation-Normal_Public-dd890adca164.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1474401830097-dd890adca164-5c2ee693317c-linux/Folders_Ignore_Confirmation-Normal_Public-5c2ee693317c.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1474401830097-dd890adca164-5c2ee693317c-linux/Folders_Ignore_Confirmation-Normal_Public.png)
 * Changed: **Folders_Ignore_Confirmation-Normal_Private** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1474401830097-dd890adca164-5c2ee693317c-linux/Folders_Ignore_Confirmation-Normal_Private-dd890adca164.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1474401830097-dd890adca164-5c2ee693317c-linux/Folders_Ignore_Confirmation-Normal_Private-5c2ee693317c.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1474401830097-dd890adca164-5c2ee693317c-linux/Folders_Ignore_Confirmation-Normal_Private.png)
 * Changed: **Folders_Delete_Confirmation-Normal_Public** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1474401830097-dd890adca164-5c2ee693317c-linux/Folders_Delete_Confirmation-Normal_Public-dd890adca164.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1474401830097-dd890adca164-5c2ee693317c-linux/Folders_Delete_Confirmation-Normal_Public-5c2ee693317c.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1474401830097-dd890adca164-5c2ee693317c-linux/Folders_Delete_Confirmation-Normal_Public.png)
 * Changed: **Folders_Delete_Confirmation-Normal_Private** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1474401830097-dd890adca164-5c2ee693317c-linux/Folders_Delete_Confirmation-Normal_Private-dd890adca164.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1474401830097-dd890adca164-5c2ee693317c-linux/Folders_Delete_Confirmation-Normal_Private-5c2ee693317c.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1474401830097-dd890adca164-5c2ee693317c-linux/Folders_Delete_Confirmation-Normal_Private.png)
 * Changed: **Folders_Clear_History_Confirmation-Normal_Public** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1474401830097-dd890adca164-5c2ee693317c-linux/Folders_Clear_History_Confirmation-Normal_Public-dd890adca164.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1474401830097-dd890adca164-5c2ee693317c-linux/Folders_Clear_History_Confirmation-Normal_Public-5c2ee693317c.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1474401830097-dd890adca164-5c2ee693317c-linux/Folders_Clear_History_Confirmation-Normal_Public.png)
 * Changed: **Folders_Clear_History_Confirmation-Normal_Private** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1474401830097-dd890adca164-5c2ee693317c-linux/Folders_Clear_History_Confirmation-Normal_Private-dd890adca164.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1474401830097-dd890adca164-5c2ee693317c-linux/Folders_Clear_History_Confirmation-Normal_Private-5c2ee693317c.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1474401830097-dd890adca164-5c2ee693317c-linux/Folders_Clear_History_Confirmation-Normal_Private.png)
 * Changed: **Folders_Clear_History_Confirmation-Long_Name_Public** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1474401830097-dd890adca164-5c2ee693317c-linux/Folders_Clear_History_Confirmation-Long_Name_Public-dd890adca164.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1474401830097-dd890adca164-5c2ee693317c-linux/Folders_Clear_History_Confirmation-Long_Name_Public-5c2ee693317c.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1474401830097-dd890adca164-5c2ee693317c-linux/Folders_Clear_History_Confirmation-Long_Name_Public.png)
 * Changed: **Device_Revoke-Normal** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1474401830097-dd890adca164-5c2ee693317c-linux/Device_Revoke-Normal-dd890adca164.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1474401830097-dd890adca164-5c2ee693317c-linux/Device_Revoke-Normal-5c2ee693317c.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1474401830097-dd890adca164-5c2ee693317c-linux/Device_Revoke-Normal.png)
 * Changed: **Device_Revoke-Current** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1474401830097-dd890adca164-5c2ee693317c-linux/Device_Revoke-Current-dd890adca164.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1474401830097-dd890adca164-5c2ee693317c-linux/Device_Revoke-Current-5c2ee693317c.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1474401830097-dd890adca164-5c2ee693317c-linux/Device_Revoke-Current.png)

**Comment by keybase-ci-visdiff** [comment]
:mag_right: The commits dd890adca164...33985efb9e33 introduced some visual changes on linux:
 * Changed: **Update_Passphrase-Error_Wrong_Passphrase** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1474405398504-dd890adca164-33985efb9e33-linux/Update_Passphrase-Error_Wrong_Passphrase-dd890adca164.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1474405398504-dd890adca164-33985efb9e33-linux/Update_Passphrase-Error_Wrong_Passphrase-33985efb9e33.png)  
   Update_Passphrase-Error_Wrong_Passphrase comparison
 * Changed: **Standard_Screen-Success_w_Custom_Notification_Element** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1474405398504-dd890adca164-33985efb9e33-linux/Standard_Screen-Success_w_Custom_Notification_Element-dd890adca164.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1474405398504-dd890adca164-33985efb9e33-linux/Standard_Screen-Success_w_Custom_Notification_Element-33985efb9e33.png)  
   Standard_Screen-Success_w_Custom_Notification_Element comparison
 * Changed: **Standard_Screen-Normal** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1474405398504-dd890adca164-33985efb9e33-linux/Standard_Screen-Normal-dd890adca164.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1474405398504-dd890adca164-33985efb9e33-linux/Standard_Screen-Normal-33985efb9e33.png)  
   Standard_Screen-Normal comparison
 * Changed: **Standard_Screen-Error_w_Back_Button** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1474405398504-dd890adca164-33985efb9e33-linux/Standard_Screen-Error_w_Back_Button-dd890adca164.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1474405398504-dd890adca164-33985efb9e33-linux/Standard_Screen-Error_w_Back_Button-33985efb9e33.png)  
   Standard_Screen-Error_w_Back_Button comparison
 * Changed: **Standard_Screen-Error** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1474405398504-dd890adca164-33985efb9e33-linux/Standard_Screen-Error-dd890adca164.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1474405398504-dd890adca164-33985efb9e33-linux/Standard_Screen-Error-33985efb9e33.png)  
   Standard_Screen-Error comparison
 * Changed: **Standard_Screen-Back_Button** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1474405398504-dd890adca164-33985efb9e33-linux/Standard_Screen-Back_Button-dd890adca164.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1474405398504-dd890adca164-33985efb9e33-linux/Standard_Screen-Back_Button-33985efb9e33.png)  
   Standard_Screen-Back_Button comparison
 * Changed: **New_Proof_Website-DNS_or_File** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1474405398504-dd890adca164-33985efb9e33-linux/New_Proof_Website-DNS_or_File-dd890adca164.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1474405398504-dd890adca164-33985efb9e33-linux/New_Proof_Website-DNS_or_File-33985efb9e33.png)  
   New_Proof_Website-DNS_or_File comparison
 * Changed: **New_Proof_PGP_import-Import_PGP** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1474405398504-dd890adca164-33985efb9e33-linux/New_Proof_PGP_import-Import_PGP-dd890adca164.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1474405398504-dd890adca164-33985efb9e33-linux/New_Proof_PGP_import-Import_PGP-33985efb9e33.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1474405398504-dd890adca164-33985efb9e33-linux/New_Proof_PGP_import-Import_PGP.png)
 * Changed: **New_Proof_PGP_generating-Generating_PGP** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1474405398504-dd890adca164-33985efb9e33-linux/New_Proof_PGP_generating-Generating_PGP-dd890adca164.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1474405398504-dd890adca164-33985efb9e33-linux/New_Proof_PGP_generating-Generating_PGP-33985efb9e33.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1474405398504-dd890adca164-33985efb9e33-linux/New_Proof_PGP_generating-Generating_PGP.png)
 * Changed: **New_Proof_PGP_add-One_Error_Email** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1474405398504-dd890adca164-33985efb9e33-linux/New_Proof_PGP_add-One_Error_Email-dd890adca164.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1474405398504-dd890adca164-33985efb9e33-linux/New_Proof_PGP_add-One_Error_Email-33985efb9e33.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1474405398504-dd890adca164-33985efb9e33-linux/New_Proof_PGP_add-One_Error_Email.png)
 * Changed: **New_Proof_PGP_add-Normal** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1474405398504-dd890adca164-33985efb9e33-linux/New_Proof_PGP_add-Normal-dd890adca164.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1474405398504-dd890adca164-33985efb9e33-linux/New_Proof_PGP_add-Normal-33985efb9e33.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1474405398504-dd890adca164-33985efb9e33-linux/New_Proof_PGP_add-Normal.png)
 * Changed: **New_Proof_PGP_add-Empty** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1474405398504-dd890adca164-33985efb9e33-linux/New_Proof_PGP_add-Empty-dd890adca164.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1474405398504-dd890adca164-33985efb9e33-linux/New_Proof_PGP_add-Empty-33985efb9e33.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1474405398504-dd890adca164-33985efb9e33-linux/New_Proof_PGP_add-Empty.png)
 * Changed: **New_Proof_PGP-Import_or_Generate** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1474405398504-dd890adca164-33985efb9e33-linux/New_Proof_PGP-Import_or_Generate-dd890adca164.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1474405398504-dd890adca164-33985efb9e33-linux/New_Proof_PGP-Import_or_Generate-33985efb9e33.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1474405398504-dd890adca164-33985efb9e33-linux/New_Proof_PGP-Import_or_Generate.png)
 * Changed: **Folders_Ignore_Confirmation-Normal_Public** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1474405398504-dd890adca164-33985efb9e33-linux/Folders_Ignore_Confirmation-Normal_Public-dd890adca164.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1474405398504-dd890adca164-33985efb9e33-linux/Folders_Ignore_Confirmation-Normal_Public-33985efb9e33.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1474405398504-dd890adca164-33985efb9e33-linux/Folders_Ignore_Confirmation-Normal_Public.png)
 * Changed: **Folders_Ignore_Confirmation-Normal_Private** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1474405398504-dd890adca164-33985efb9e33-linux/Folders_Ignore_Confirmation-Normal_Private-dd890adca164.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1474405398504-dd890adca164-33985efb9e33-linux/Folders_Ignore_Confirmation-Normal_Private-33985efb9e33.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1474405398504-dd890adca164-33985efb9e33-linux/Folders_Ignore_Confirmation-Normal_Private.png)
 * Changed: **Folders_Delete_Confirmation-Normal_Public** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1474405398504-dd890adca164-33985efb9e33-linux/Folders_Delete_Confirmation-Normal_Public-dd890adca164.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1474405398504-dd890adca164-33985efb9e33-linux/Folders_Delete_Confirmation-Normal_Public-33985efb9e33.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1474405398504-dd890adca164-33985efb9e33-linux/Folders_Delete_Confirmation-Normal_Public.png)
 * Changed: **Folders_Delete_Confirmation-Normal_Private** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1474405398504-dd890adca164-33985efb9e33-linux/Folders_Delete_Confirmation-Normal_Private-dd890adca164.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1474405398504-dd890adca164-33985efb9e33-linux/Folders_Delete_Confirmation-Normal_Private-33985efb9e33.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1474405398504-dd890adca164-33985efb9e33-linux/Folders_Delete_Confirmation-Normal_Private.png)
 * Changed: **Folders_Clear_History_Confirmation-Normal_Public** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1474405398504-dd890adca164-33985efb9e33-linux/Folders_Clear_History_Confirmation-Normal_Public-dd890adca164.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1474405398504-dd890adca164-33985efb9e33-linux/Folders_Clear_History_Confirmation-Normal_Public-33985efb9e33.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1474405398504-dd890adca164-33985efb9e33-linux/Folders_Clear_History_Confirmation-Normal_Public.png)
 * Changed: **Folders_Clear_History_Confirmation-Normal_Private** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1474405398504-dd890adca164-33985efb9e33-linux/Folders_Clear_History_Confirmation-Normal_Private-dd890adca164.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1474405398504-dd890adca164-33985efb9e33-linux/Folders_Clear_History_Confirmation-Normal_Private-33985efb9e33.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1474405398504-dd890adca164-33985efb9e33-linux/Folders_Clear_History_Confirmation-Normal_Private.png)
 * Changed: **Folders_Clear_History_Confirmation-Long_Name_Public** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1474405398504-dd890adca164-33985efb9e33-linux/Folders_Clear_History_Confirmation-Long_Name_Public-dd890adca164.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1474405398504-dd890adca164-33985efb9e33-linux/Folders_Clear_History_Confirmation-Long_Name_Public-33985efb9e33.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1474405398504-dd890adca164-33985efb9e33-linux/Folders_Clear_History_Confirmation-Long_Name_Public.png)
 * Changed: **Device_Revoke-Normal** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1474405398504-dd890adca164-33985efb9e33-linux/Device_Revoke-Normal-dd890adca164.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1474405398504-dd890adca164-33985efb9e33-linux/Device_Revoke-Normal-33985efb9e33.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1474405398504-dd890adca164-33985efb9e33-linux/Device_Revoke-Normal.png)
 * Changed: **Device_Revoke-Current** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1474405398504-dd890adca164-33985efb9e33-linux/Device_Revoke-Current-dd890adca164.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1474405398504-dd890adca164-33985efb9e33-linux/Device_Revoke-Current-33985efb9e33.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1474405398504-dd890adca164-33985efb9e33-linux/Device_Revoke-Current.png)

**Comment by keybase-ci-visdiff** [comment]
:mag_right: The commits dd890adca164...d3070331d1c9 introduced some visual changes on linux:
 * Changed: **Update_Passphrase-Error_Wrong_Passphrase** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1474406161747-dd890adca164-d3070331d1c9-linux/Update_Passphrase-Error_Wrong_Passphrase-dd890adca164.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1474406161747-dd890adca164-d3070331d1c9-linux/Update_Passphrase-Error_Wrong_Passphrase-d3070331d1c9.png)  
   Update_Passphrase-Error_Wrong_Passphrase comparison
 * Changed: **Standard_Screen-Success_w_Custom_Notification_Element** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1474406161747-dd890adca164-d3070331d1c9-linux/Standard_Screen-Success_w_Custom_Notification_Element-dd890adca164.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1474406161747-dd890adca164-d3070331d1c9-linux/Standard_Screen-Success_w_Custom_Notification_Element-d3070331d1c9.png)  
   Standard_Screen-Success_w_Custom_Notification_Element comparison
 * Changed: **Standard_Screen-Normal** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1474406161747-dd890adca164-d3070331d1c9-linux/Standard_Screen-Normal-dd890adca164.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1474406161747-dd890adca164-d3070331d1c9-linux/Standard_Screen-Normal-d3070331d1c9.png)  
   Standard_Screen-Normal comparison
 * Changed: **Standard_Screen-Error_w_Back_Button** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1474406161747-dd890adca164-d3070331d1c9-linux/Standard_Screen-Error_w_Back_Button-dd890adca164.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1474406161747-dd890adca164-d3070331d1c9-linux/Standard_Screen-Error_w_Back_Button-d3070331d1c9.png)  
   Standard_Screen-Error_w_Back_Button comparison
 * Changed: **Standard_Screen-Error** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1474406161747-dd890adca164-d3070331d1c9-linux/Standard_Screen-Error-dd890adca164.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1474406161747-dd890adca164-d3070331d1c9-linux/Standard_Screen-Error-d3070331d1c9.png)  
   Standard_Screen-Error comparison
 * Changed: **Standard_Screen-Back_Button** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1474406161747-dd890adca164-d3070331d1c9-linux/Standard_Screen-Back_Button-dd890adca164.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1474406161747-dd890adca164-d3070331d1c9-linux/Standard_Screen-Back_Button-d3070331d1c9.png)  
   Standard_Screen-Back_Button comparison
 * Changed: **New_Proof_Website-DNS_or_File** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1474406161747-dd890adca164-d3070331d1c9-linux/New_Proof_Website-DNS_or_File-dd890adca164.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1474406161747-dd890adca164-d3070331d1c9-linux/New_Proof_Website-DNS_or_File-d3070331d1c9.png)  
   New_Proof_Website-DNS_or_File comparison
 * Changed: **New_Proof_PGP_import-Import_PGP** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1474406161747-dd890adca164-d3070331d1c9-linux/New_Proof_PGP_import-Import_PGP-dd890adca164.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1474406161747-dd890adca164-d3070331d1c9-linux/New_Proof_PGP_import-Import_PGP-d3070331d1c9.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1474406161747-dd890adca164-d3070331d1c9-linux/New_Proof_PGP_import-Import_PGP.png)
 * Changed: **New_Proof_PGP_generating-Generating_PGP** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1474406161747-dd890adca164-d3070331d1c9-linux/New_Proof_PGP_generating-Generating_PGP-dd890adca164.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1474406161747-dd890adca164-d3070331d1c9-linux/New_Proof_PGP_generating-Generating_PGP-d3070331d1c9.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1474406161747-dd890adca164-d3070331d1c9-linux/New_Proof_PGP_generating-Generating_PGP.png)
 * Changed: **New_Proof_PGP_add-One_Error_Email** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1474406161747-dd890adca164-d3070331d1c9-linux/New_Proof_PGP_add-One_Error_Email-dd890adca164.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1474406161747-dd890adca164-d3070331d1c9-linux/New_Proof_PGP_add-One_Error_Email-d3070331d1c9.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1474406161747-dd890adca164-d3070331d1c9-linux/New_Proof_PGP_add-One_Error_Email.png)
 * Changed: **New_Proof_PGP_add-Normal** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1474406161747-dd890adca164-d3070331d1c9-linux/New_Proof_PGP_add-Normal-dd890adca164.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1474406161747-dd890adca164-d3070331d1c9-linux/New_Proof_PGP_add-Normal-d3070331d1c9.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1474406161747-dd890adca164-d3070331d1c9-linux/New_Proof_PGP_add-Normal.png)
 * Changed: **New_Proof_PGP_add-Empty** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1474406161747-dd890adca164-d3070331d1c9-linux/New_Proof_PGP_add-Empty-dd890adca164.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1474406161747-dd890adca164-d3070331d1c9-linux/New_Proof_PGP_add-Empty-d3070331d1c9.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1474406161747-dd890adca164-d3070331d1c9-linux/New_Proof_PGP_add-Empty.png)
 * Changed: **New_Proof_PGP-Import_or_Generate** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1474406161747-dd890adca164-d3070331d1c9-linux/New_Proof_PGP-Import_or_Generate-dd890adca164.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1474406161747-dd890adca164-d3070331d1c9-linux/New_Proof_PGP-Import_or_Generate-d3070331d1c9.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1474406161747-dd890adca164-d3070331d1c9-linux/New_Proof_PGP-Import_or_Generate.png)
 * Changed: **Device_Revoke-Normal** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1474406161747-dd890adca164-d3070331d1c9-linux/Device_Revoke-Normal-dd890adca164.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1474406161747-dd890adca164-d3070331d1c9-linux/Device_Revoke-Normal-d3070331d1c9.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1474406161747-dd890adca164-d3070331d1c9-linux/Device_Revoke-Normal.png)
 * Changed: **Device_Revoke-Current** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1474406161747-dd890adca164-d3070331d1c9-linux/Device_Revoke-Current-dd890adca164.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1474406161747-dd890adca164-d3070331d1c9-linux/Device_Revoke-Current-d3070331d1c9.png) [(diff)](https://keybase-app-visdiff.s3.amazonaws.com/1474406161747-dd890adca164-d3070331d1c9-linux/Device_Revoke-Current.png)

**Comment by chromakode** [comment]
@MarcoPolo visdiff exposed a few details I needed to fix around sizing the views. Could I please have a re-review? The first two commits are unchanged.

**Pull request merged**
