### PR TITLE
Fix pushAndroid.sh

### PR DESCRIPTION
**Pull request by akalin-keybase**
The exact location of the .apk file seems to vary.

### CODE REVIEW

**Comment by akalin-keybase** [comment]
Just curious, has anyone else run into this on Android? @songgao? I wonder if it's a new version of something...

**Comment by akalin-keybase** [comment]
`react-native run-android` has never worked for me. should it? I get:

```
Android project not found. Maybe run react-native android first?
```
(running from `shared`, `shared/react-native`, or `shared-react-native/android`)

Googling turns up https://github.com/facebook/react-native/issues/9312, which says to run `react-native upgrade`, but doing all led to further errors.

**Comment by chrisnojima** [comment]
k, anyways i don't use this command so i shoulnd't review this

**Comment by akalin-keybase** [comment]
hey @songgao mind looking at this?

**Comment by mmaxim** [comment]
Nice! I had just been creating a symlink to workaround this.

**Pull request merged**
