### PR TITLE
Tweaks on Reset option

### PR DESCRIPTION
**Pull request by cecileboucheron**
@keybase/react-hackers 
@malgorithms @buoyad I changed it so that the Reset button is there right away:

image

### CODE REVIEW

**Comment by keybase-ci-visdiff** [comment]
The commits 0afb68ae4761...9353a2573019 introduce visual changes on linux. <details><summary>:mag_right: 2 changed</summary>

 * Changed: **Select_Other_Device-Normal** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1512699747315-0afb68ae4761-9353a2573019-linux/Select_Other_Device-Normal-0afb68ae4761.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1512699747315-0afb68ae4761-9353a2573019-linux/Select_Other_Device-Normal-9353a2573019.png)  
   Select_Other_Device-Normal comparison
 * Changed: **Select_Other_Device-No_User_Pass_Login** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1512699747315-0afb68ae4761-9353a2573019-linux/Select_Other_Device-No_User_Pass_Login-0afb68ae4761.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1512699747315-0afb68ae4761-9353a2573019-linux/Select_Other_Device-No_User_Pass_Login-9353a2573019.png)  
   Select_Other_Device-No_User_Pass_Login comparison
</summary>

**Comment by malgorithms** [comment]
looks good to me

**Comment by mmaxim** [comment]
Maybe could be blue or green or something so it doesn’t look like main CTA on the screen?

**Comment by malgorithms** [comment]
I like that it feels dangerous, even if it does draw attention. but ok no matter what

**Comment by mmaxim** [comment]
sounds good

**Comment by cecileboucheron** [comment]
@MarcoPolo I actually changed the button to be a red link (less in your way). Need approval again, thanks!

**Comment by keybase-ci-visdiff** [comment]
The commits 0afb68ae4761...287d53a882be introduce visual changes on linux. <details><summary>:mag_right: 2 changed</summary>

 * Changed: **Select_Other_Device-Normal** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1512775628833-0afb68ae4761-287d53a882be-linux/Select_Other_Device-Normal-0afb68ae4761.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1512775628833-0afb68ae4761-287d53a882be-linux/Select_Other_Device-Normal-287d53a882be.png)  
   Select_Other_Device-Normal comparison
 * Changed: **Select_Other_Device-No_User_Pass_Login** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1512775628833-0afb68ae4761-287d53a882be-linux/Select_Other_Device-No_User_Pass_Login-0afb68ae4761.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1512775628833-0afb68ae4761-287d53a882be-linux/Select_Other_Device-No_User_Pass_Login-287d53a882be.png)  
   Select_Other_Device-No_User_Pass_Login comparison
</summary>

**Pull request merged**
