### PR TITLE
Display log send errors in Feedback dialog

### PR DESCRIPTION
**Pull request by akalin-keybase**

### CODE REVIEW

**Comment by akalin-keybase** [comment]
example:

image

**Comment by zanderz** [comment]
LGTM. What are they supposed to do with this, though - hit "send" again? send us a screen cap? Likely discussed elsewhere already.

**Comment by akalin-keybase** [comment]
Well, short term this is to diagnose the problem @jzila's running into. But I wonder if we should tell them to e-mail screenshots to someplace, or post a GitHub issue with screenshots, or something...

**Comment by chrisnojima** [comment]
Ok we need to ensure this flow works no matter what. I don't want a bunch
of ux around what we do if this thing doesn't work

**Pull request merged**
