### PR TITLE
NOMERGE: Hotfix 212

### PR DESCRIPTION
**Pull request by chrisnojima**
- [x] New gregor key for exploding
- [x] Better tapping dismissal
- [x] Send NewChatActivityWithEphemeralPurge on ephemeral 
- [x] UnboxError for erasablekvstore

### CODE REVIEW

**Comment by chrisnojima** [comment]
cc: @cjb @mmaxim @buoyad @joshblum

**Comment by mmaxim** [comment]
👍

**Comment by chrisnojima** [comment]
circle doesn't understand local kbfs so its failing due to kbfs/client incompatibility

**Comment by chrisnojima** [comment]
- [ ] tag when done

**Comment by chrisnojima** [comment]
- [ ] need new ephemeral fix
- [ ] need new gregor fix

**Comment by chrisnojima** [comment]
@joshblum @mmaxim @buoyad

**Comment by chrisnojima** [comment]
- [ ] waiting on a kbfs hotfix off of `c76e9b9ab00631d01e5d841175e9033da50da92f` from @strib

**Comment by chrisnojima** [comment]
closing as we've released and tagged

**Pull request closed without merging**
