### PR TITLE
Better startup

### PR DESCRIPTION
**Pull request by gabriel**
Showing a splash screen until we show the right UI.

### CODE REVIEW

**Comment by gabriel** [comment]
@keybase/react-hackers

**Comment by MarcoPolo** [comment]
👍

**Comment by keybase-ci-visdiff** [comment]
:mag_right: The commits 20072926e78c...3ea79e2685a8 introduced some visual changes on linux:
 * Changed: **Intro-User_who_just_revoked_device** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468627718662-20072926e78c-3ea79e2685a8-linux/Intro-User_who_just_revoked_device-20072926e78c.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468627718662-20072926e78c-3ea79e2685a8-linux/Intro-User_who_just_revoked_device-3ea79e2685a8.png)  
   Intro-User_who_just_revoked_device comparison
 * Changed: **Intro-First_time_user** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468627718662-20072926e78c-3ea79e2685a8-linux/Intro-First_time_user-20072926e78c.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468627718662-20072926e78c-3ea79e2685a8-linux/Intro-First_time_user-3ea79e2685a8.png)  
   Intro-First_time_user comparison

**Comment by keybase-ci-visdiff** [comment]
:mag_right: The commits 20072926e78c...1682508b960f introduced some visual changes on linux:
 * Added: **Intro-Splash**  
   Intro-Splash rendered
 * Changed: **Intro-User_who_just_revoked_device** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468628582706-20072926e78c-1682508b960f-linux/Intro-User_who_just_revoked_device-20072926e78c.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468628582706-20072926e78c-1682508b960f-linux/Intro-User_who_just_revoked_device-1682508b960f.png)  
   Intro-User_who_just_revoked_device comparison
 * Changed: **Intro-First_time_user** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468628582706-20072926e78c-1682508b960f-linux/Intro-First_time_user-20072926e78c.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468628582706-20072926e78c-1682508b960f-linux/Intro-First_time_user-1682508b960f.png)  
   Intro-First_time_user comparison

**Pull request merged**
