### PR TITLE
Storybook - asset input box and barebones Input2 component

### PR DESCRIPTION
**Pull request by buoyad**
r? @keybase/react-hackers

### CODE REVIEW

**Comment by adamjspooner** [comment]
Storyshots?

**Comment by buoyad** [comment]
@adamjspooner yep! I'm going to refactor this `Input2` actually, so I'll make another PR when that's done.

**Comment by buoyad** [comment]
I'll do the input refactor in a separate PR actually, opening this again @keybase/react-hackers !

**Comment by buoyad** [comment]
Ok @keybase/react-hackers, I got rid of `Input2` and swapped it out for `NewInput` in the story. Ready for review

**Pull request merged**
