### PR TITLE
flip help screen design improvements

### PR DESCRIPTION
**Pull request by mmaxim**

### CODE REVIEW

**Comment by mmaxim** [comment]
Ok moved it all up to the top, let me know what you think!

**Comment by mmaxim** [comment]
image

**Comment by mmaxim** [comment]
cc @malgorithms

**Comment by mmaxim** [comment]
@adamjspooner any thoughts on this? It looks pretty good to me.

**Comment by mmaxim** [comment]
One caveat is the blog link is below the fold, @malgorithms might want it to be viewable with no scroll.

**Comment by adamjspooner** [comment]
@mmaxim, should we send the title to the frontend (instead of hard-coding it)?

**Comment by mmaxim** [comment]
Sure

**Pull request merged**
