### PR TITLE
Start/stop via ctl should install/uninstall services

### PR DESCRIPTION
**Pull request by gabriel**
See https://keybase.atlassian.net/browse/DESKTOP-1756

Currently we are leaving behind launchd plists on stop. This makes it so it stops the services and removes the plists.

The PR makes some install/uninstall methods public and uses them in ctl start/stop on macOS.

Also:
- Adds removal of fuse and helper to `keybase uninstall`
- Lowers launchd status delay from 1s to 200ms
- Don't log that we're stopping a service that doesn't exist
- Bump installer version

### CODE REVIEW

**Comment by gabriel** [comment]
@patrickxb or @maxtaco 

cc @keybase/react-hackers

**Comment by patrickxb** [comment]
So `ctl stop` also means "uninstall launch agents"?

Just trying to think if there's a case where you quit keybase menubar (which runs `ctl stop`) but you are expecting it to start when you reboot...I guess not.

**Comment by gabriel** [comment]
We moved app start to use System Preferences (login item)... So the services no longer start the app (the app starts services on start, and stops them on quit). This simplified everything too.

**Comment by gabriel** [comment]
And yeah, `ctl stop` means stop (and uninstall) services.

**Comment by patrickxb** [comment]
Ok, LGTM

**Pull request merged**
