### PR TITLE
Fix packaging scripts to work on other platforms

### PR DESCRIPTION
**Pull request by gabriel**
These fixes allow these scripts to work under windows.

### CODE REVIEW

**Comment by keybase-ci-visdiff** [comment]
:mag_right: No visual changes found as a result of these commits.

**Comment by MarcoPolo** [comment]
are the quotes needed to get it working on windows or just general cleanup?

**Comment by MarcoPolo** [comment]
👍

**Comment by zanderz** [comment]
Yeah the quotes are necessary when the path contains spaces I believe.

I assume codesigning could be added - otherwise these aren't useful for production, just a dev convenience?

LGTM :thumbsup:

**Comment by gabriel** [comment]
yeah, we codesign go binaries in OS X just as a nice thing to have.. it's not required

**Pull request merged**
