### PR TITLE
Use (legacy) API for updater (v1)

### PR DESCRIPTION
**Pull request by gabriel**
- Copied code for KeybaseUpdateSource from v2 updater
- Remove "main" channel, since default should be empty ""

@keybase/updater-hackers @maxtaco

### CODE REVIEW

**Comment by maxtaco** [comment]
What should the API server reply with if no update is necessary?

**Comment by cjb** [comment]
20:30:18 ../vendor/github.com/keybase/go-updater/sources/keybase.go:38: undefined: util in util.RandString

**Comment by gabriel** [comment]
It can return a 404 on no update

**Comment by gabriel** [comment]
ok build should be fixed... i'm checking 404 now and returning "no update" in that case

**Comment by maxtaco** [comment]
on it

**Comment by cjb** [comment]
Let's hold off until we have a clear ordering in a deployment plan per https://keybase.atlassian.net/browse/DESKTOP-1182

**Comment by maxtaco** [comment]
👍

**Pull request merged**
