### PR TITLE
Add waiting for response in login sagas

### PR DESCRIPTION
**Pull request by MarcoPolo**
@keybase/react-hackers

### CODE REVIEW

**Comment by MarcoPolo** [comment]
hmm so the slow part is between incoming calls? I can change it to that

**Comment by MarcoPolo** [comment]
Now we do both.

**Comment by MarcoPolo** [comment]
This does leave the state in a waiting state after the finished saga, I don't think it matters since any other incoming call would set it to false.

**Comment by cjb** [comment]
@chrisnojima want to take another look? perhaps you could even merge it in, if it looks good

**Comment by chrisnojima** [comment]
looking now

**Comment by cjb** [comment]
tested some desktop provisioning, worked well

**Comment by chrisnojima** [comment]
this looks ok. when i enter my username and am waiting for the device list it seems to now make it spin, but the big one (after entering my device name) does have a waiting state, so this fixes that. lets do it

**Pull request merged**
