### PR TITLE
Fix crash

### PR DESCRIPTION
**Pull request by patrickxb**

### CODE REVIEW

**Comment by maxtaco** [comment]
cc: @mmaxim, I thought the API I called always returns a non-`nil` pointer?

**Comment by mmaxim** [comment]
Yeah this change should be unneeded, that function should never return `nil`.

**Comment by patrickxb** [comment]
@maxtaco the ticket was still in TODO, so i did this this morning.  Didn't see your change.

**Comment by maxtaco** [comment]
Urg, sorry @patrickxb ! My bad for not moving the ticket over.

**Comment by patrickxb** [comment]
No problem...was about 5 seconds of work...

**Pull request closed without merging**
