### PR TITLE
fix showing inbox when coming from push / previous load

### PR DESCRIPTION
**Pull request by chrisnojima**
@keybase/react-hackers this fixes you seeing the inbox when you start up and land on a prev convo or come from a push
I added a new action for this. I do want to clean this action and the switch route def (already ticketed) when we deprecate nav1

### CODE REVIEW

**Comment by buoyad** [comment]
1. Be at inbox > convo > info panel & background
2. Tap push
3. End up at inbox > convo > convo

**Comment by chrisnojima** [comment]
@buoyad updated
cc: @mmaxim i made it so when we create a new convo , we never make a meta delete. if its a brand new convo we'd make it and then immediately delete

**Comment by mmaxim** [comment]
I'm a touch worried about that change, I can't remember if the service filters out empty conversations before you get to that point. If it doesn't, then you could be showing random blank convos that people are creating against you.

**Comment by chrisnojima** [comment]
strangely if you go through the new team building flow it seems to never happen but if you go through the profile chat it does. i'll have to see why

**Pull request merged**
