### PR TITLE
Move facebook visibility animation into Icon layout

### PR DESCRIPTION
**Pull request by chromakode**
:eyeglasses: @keybase/react-hackers @cjb

### CODE REVIEW

**Comment by keybase-ci-visdiff** [comment]
:mag_right: The commits 88282e4865e5...8984de2abc34 introduced some visual changes on linux:
 * Changed: **Icon-Icon_Image** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1474655378711-88282e4865e5-8984de2abc34-linux/Icon-Icon_Image-88282e4865e5.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1474655378711-88282e4865e5-8984de2abc34-linux/Icon-Icon_Image-8984de2abc34.png)  
   Icon-Icon_Image comparison

**Comment by chromakode** [comment]
This needs to be updated after https://github.com/keybase/client/pull/4414 lands.

**Comment by chromakode** [comment]
Updated! Ready for review, @keybase/react-hackers!

**Comment by keybase-ci-visdiff** [comment]
:mag_right: The commits bffa8b5dc55a...a43c23015bc9 introduced some visual changes on linux:
 * Changed: **Icon-Icon_Image** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1474922133643-bffa8b5dc55a-a43c23015bc9-linux/Icon-Icon_Image-bffa8b5dc55a.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1474922133643-bffa8b5dc55a-a43c23015bc9-linux/Icon-Icon_Image-a43c23015bc9.png)  
   Icon-Icon_Image comparison

**Pull request merged**
