### PR TITLE
Bust passphrase stream cache if it's outdated in places prone to failure

### PR DESCRIPTION
**Pull request by pzduniak**
Depends on https://github.com/keybase/keybase/pull/3885

Fixes a ppgen assertion bug where an outdated cached passphrase stream would result in failing kex2 provisions / paperkey generations.

### CODE REVIEW

**Comment by maxtaco** [comment]
this looks good, but how does this login_test pass if the Web endpoint hasn't been merged?  I would expect the tests to fail on that endpoint 404'ing

**Comment by pzduniak** [comment]
my phone UI says the last CI never finished

**Comment by maxtaco** [comment]
build 4 and 3 worked, but the engine tests seemed to work

i reran for you since it seems like build 4 flaked

**Comment by pzduniak** [comment]
lmk if i should merge, everything passes locally

**Comment by maxtaco** [comment]
:+1: to merge

**Pull request merged**
