### PR TITLE
cut over to avdl2json in iced; recompiles and tests

### PR DESCRIPTION
**Pull request by maxtaco**

### CODE REVIEW

**Comment by maxtaco** [comment]
r? @patrickxb and @chrisnojima ?

my tests show JSON equivalence of the old compiler and the new.  Wasn't sure how to test the JS side of things.

**Comment by chrisnojima** [comment]
The js code gens off of the json files so if those are the same the js code will be fine

**Comment by maxtaco** [comment]
Cool, of course the order of keys in JSON dictionaries is different, but the order of arrays are the same...

**Comment by chrisnojima** [comment]
I have another live pr which changes our output to be sorted so it won't matter soon. The diff on the js side is expected since the merkle stuff want compiled yet :+1:

**Comment by patrickxb** [comment]
generated go code looks the same, so LGTM

**Pull request merged**
