### PR TITLE
Packaging: clean up prior run node_modules before install

### PR DESCRIPTION
**Pull request by cjb**
@keybase/react-hackers CC @gabriel

### CODE REVIEW

**Comment by chrisnojima** [comment]
we actually need to clean up the other node_modules, not just under shared.
During the build process we create desktop/dist desktop/build desktop/release. All those should be wiped

**Comment by gabriel** [comment]
I think we clear those out in the build script already, so I think this is ok

**Comment by cjb** [comment]
Checked that after a local build run there are no files left over inside the client/ dir.  (There are some in /tmp though.)

**Comment by cjb** [comment]
@chrisnojima Here's where we del() those dirs at the start of a new run:

https://github.com/keybase/client/blob/master/shared/desktop/package.js#L55

https://github.com/keybase/client/blob/master/shared/desktop/package.js#L56

https://github.com/keybase/client/blob/master/shared/desktop/package.js#L120

**Comment by chrisnojima** [comment]
the problem is those paths interfere with RN so they also need to be cleaned before that is ran

**Comment by cjb** [comment]
@chrisnojima Huh.  Are you sure? That doesn't make much sense -- our macOS build runs on an entirely different machine to our iOS/Android builds.  This isn't mentioned in the ticket, either.  Could you give more info about the symptom you're seeing?

**Comment by chrisnojima** [comment]
if this doesn't happen on the actual build machines we can close.
this happens locally

**Pull request merged**
