### PR TITLE
Badge new team rows and add crowns

### PR DESCRIPTION
**Pull request by buoyad**
cc @keybase/y2ksquad

### CODE REVIEW

**Comment by buoyad** [comment]
@jakob223 that looks like the branch before I rebased

**Comment by buoyad** [comment]
@jakob223 but even on latest it doesn't match the designs exactly, yeah we'd need a new asset. It's in a rounded box container instead

**Comment by jakob223** [comment]
Want to start a conversation with design about that asset?

**Comment by buoyad** [comment]
Yep I did, Cécile helped with how it looks currently

**Pull request merged**
