### PR TITLE
disable follow button until response

### PR DESCRIPTION
**Pull request by zanderz**
Could it be this simple?
@keybase/react-hackers

### CODE REVIEW

**Comment by zanderz** [comment]
I'm confused, I thought I did use an existing waiting prop?

**Comment by chrisnojima** [comment]
Button itself has a waiting prop

**Comment by junderw** [comment]
Couldn't these 3 commits have been squashed? (sorry for being a nit picking clean freak :-P )

Just some constructive criticism moving forward for simple changes that rewrite the same line based on review multiple times.

I love that even these tiny changes are reviewed, approved, and merged though. Very easy to follow this way.

**Comment by chrisnojima** [comment]
? This was squashed and merged right. It's one commit in master

**Pull request merged**
