### PR TITLE
actions/fs: don't do driver refreshes on linux

### PR DESCRIPTION
**Pull request by jakob223**
(cc @jzila since you reviewed the previous version of this)

Issue: KBFS-4084

### CODE REVIEW

**Comment by jzila** [comment]
OH wait actually

**Comment by jzila** [comment]
You can make the `Saga.chainAction` not do anything on Linux.

**Comment by jakob223** [comment]
@jzila how do I do that?

**Comment by jzila** [comment]
@jakob223: guard this line with an `if (!isLinux)`:
https://github.com/keybase/client/blob/9206032e1df1cd133c84e2b1e76f02afbb9be121/shared/actions/fs/platform-specific.desktop.js#L388-L391

**Comment by jakob223** [comment]
Heh - I kinda forgot that was actual JS code - I tend to think of it as boilerplate in some mysterious language that looks a lot like JS but only has one variety of statement.

**Pull request merged**
