### PR TITLE
CLI: Use Examples instead of Description

### PR DESCRIPTION
**Pull request by mlsteele**
Make Examples a first class citizen of Command. Now we don't have to write repetitive descriptions to get examples in.

Fun fact: If you fumble the the template text it will _panic_.

```
$ kbu team remove-member cn3team3 -h
NAME:
   keybase team remove-member - Remove a user from a team.

USAGE:
   keybase team remove-member [command options] <team name> --user=<username>

EXAMPLES:
   Remove a user from the team:
       keybase team remove-member acme --user roadrunner
   Cancel an email invite:
       keybase team remove-member acme --email roadrunner@acme.com
   Cancel a secret token invite (like sms):
       keybase team list-members acme --show-invite-id # to get the invite ID
       keybase team remove-member acme --invite-id 9cfd13f927bcd1f6832fefa084bb2127

OPTIONS:
   -u, --user   username
   --email      cancel a pending invite by email address
   --invite-id  cancel a pending invite by ID
   -f, --force  don't ask for confirmation
```

### CODE REVIEW

**Comment by patrickxb** [comment]
Just make sure that it isn't hidden with an empty `Description`.  Pretty sure that it's an empty `Usage` that hides it, but can you make sure `remove-member` shows up in `keybase team -h` with this change?

**Comment by mlsteele** [comment]
I tested with `remove-member` and `EXAMPLES` is visible even if `Description` is empty (which it is). I also tried with empty `Usage` and it is still visible. Also `USAGE` does not come from `Usage`.

**Comment by mlsteele** [comment]
Also an empty `Usage` does not hide `remove-member` from the subcommand list of `keybase team`. Is there something to do with an empty usage that there might be a bug with?

**Comment by patrickxb** [comment]
Hmm.  I thought leaving `Usage` empty was how we hid commands in the past.  Whatever...

**Pull request merged**
