### PR TITLE
Revert osx mountpoint changes

### PR DESCRIPTION
**Pull request by strib**
We'll do the root mountpoint redirector instead.

I tested "upgrading" to this build from the current admin build, and it looks like things just work magically.  At some point, if we update the helper process and bump it's version again, admin users might need to uninstall and reinstall it explicitly.

r? @maxtaco.

Issue: KBFS-2774

### CODE REVIEW

**Comment by maxtaco** [comment]
@strib who did the original review?  maybe they should review the revert?

**Comment by strib** [comment]
> @strib who did the original review? maybe they should review the revert?

Ok, I'll add them.  Wasn't really looking for a code review since this is just a literal revert of the three involved commits, just wanted a thumb from you that this revert is approved in general.  But will get another thumb too.

**Comment by maxtaco** [comment]
Ah ok!!! Then I'm a 👍 

thanks

**Comment by strib** [comment]
> are there any KBFS side commits that need to be reverted also?

Nope, not to my knowledge.

**Pull request merged**
