### PR TITLE
respond to the service about handling the shutdown rpc

### PR DESCRIPTION
**Pull request by mmaxim**
@keybase/react-hackers 

Otherwise the service waits around for 4 seconds before giving up and shutting down. cc @maxtaco

### CODE REVIEW

**Comment by mmaxim** [comment]
What exactly does `remote.app.quit(true)` do? Does Electron just die then? It just seemed natural to stick it at the end in case anyone adds more stuff to that function and doesn't notice it.

**Comment by chrisnojima** [comment]
Us retuning the value to the service shouldn't affect anything

**Comment by mmaxim** [comment]
All right if you want it to be the first line, I will move it.

**Comment by chrisnojima** [comment]
Id say us returning should happen early in general unless there is some processing we want to control. In this instance (and in general) we should reply early

**Pull request merged**
