### PR TITLE
Update user after tracking and being notified

### PR DESCRIPTION
**Pull request by MarcoPolo**
@keybase/react-hackers 

We want the latest state after a user hits track.

The most obvious approach is asking the service the about the user (through identify) after the user hits track. But that's racy because their is a whole notify flow that happens on the service side and so the latest info isn't available as soon as `track` returns.

Instead we wait for `NotifyUsers.usersChanged` and update the tracker information from there. 

Edit: meant to put this in here:

before before
after after

### CODE REVIEW

**Comment by cjb** [comment]
Does usersChanged come from the 60 second timer or somewhere else? What's the approx usual latency between clicking Track and having the popup change?

**Comment by MarcoPolo** [comment]
@cjb forgot to add the gifs

**Comment by MarcoPolo** [comment]
I may have found a bug in the identify / notify stuff, or may be misunderstanding it.

but if I run `KEYBASE_RUN_MODE=staging ./keybase untrack max && KEYBASE_RUN_MODE=staging ./keybase id --ui max`

a couple of times without restarting the service, the identify call I make after being notified of a user change doesn't do any of the identify_ui calls like reportLastTrack or proof lists.

If I restart the service in between untrack and showing the tracking popup it works like the gifs above.

When it breaks, it looks like this (not updating any user state):
after_broken

@patrickxb  / @maxtaco 

Can I rely on being able to call `identify.identify2` after receiving `keybase.1.NotifyUsers.userChanged`, or is there some other way I should be asking for the latest user info?

**Comment by maxtaco** [comment]
@MarcoPolo it might be a question of caching, does that seem right?  If the identification is cached, then it short-circuits the whole spew of messages you might be expecting. What if you set `needProofSet=true`?

**Comment by MarcoPolo** [comment]
@maxtaco even with `needProofSet=true` (also tried `forceRemoteCheck=true` just in case), but neither of those call any messages on the delegate UI.

Shouldn't I be at least getting the `reportLastTrack` message even if it short circuits?

I do get the user plus keys after the identify call though, but I need the other stuff.

**Comment by maxtaco** [comment]
that's a surprise. urg

**Comment by maxtaco** [comment]
Can you show me a service log from when this is happening?

**Comment by chrisnojima** [comment]
Definitely have to figure out this lag, but the electron code looks fine :+1:

**Pull request merged**
