### PR TITLE
Copy emoji images too in packaging

### PR DESCRIPTION
**Pull request by MarcoPolo**
@keybase/react-hackers 

We weren't copying emoji image sheets.

### CODE REVIEW

**Comment by keybase-ci-visdiff** [comment]
The commits b1e1e72a02cd...6f44265d92d3 introduce visual changes on linux. <details><summary>:mag_right: 1 changed</summary>

 * Changed: **Chat_Input-Emoji_Open** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1481048054429-b1e1e72a02cd-6f44265d92d3-linux/Chat_Input-Emoji_Open-b1e1e72a02cd.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1481048054429-b1e1e72a02cd-6f44265d92d3-linux/Chat_Input-Emoji_Open-6f44265d92d3.png)  
   Chat_Input-Emoji_Open comparison
</summary>

**Comment by cjb** [comment]
@MarcoPolo I wonder why the visdiff still showed up partially if the icons are now bundled..

**Comment by MarcoPolo** [comment]
I think there is a timing issue on CI when loading the images

**Comment by cjb** [comment]
@chromakode what do you think?

**Pull request merged**
