### PR TITLE
Installer: Break up privileged and services install

### PR DESCRIPTION
**Pull request by gabriel**
Changes the installer to run in 2 stages. The native installer runs for privileged tasks. Then we run `keybase -d install` from Electron.

### CODE REVIEW

**Comment by gabriel** [comment]
@chromakode @cjb 

cc @keybase/react-hackers

**Comment by gabriel** [comment]
This works around the NSTask installer hang. Also good to break up the install tasks this way.

**Comment by chromakode** [comment]
Admittedly I don't have the greatest familarity with this code. These changes appear to (to check my own comprehension):

 * Check the system mount index for our fuse mount rather than using the keybase binary.
 * Not install the service, kbfs, and updater using the helper (these get installed by the `keybase install` command, which installs any which are missing).
 * Make the electron app call `keybase install` on startup.

:+1:

**Comment by cjb** [comment]
I agree with this as the best way to do it, but I don't want to merge it in and just mask the hang.  I'm worried the hang will hit us again and we should root cause it.  I don't think we know of any reason why the way we're doing it now *should* cause any hang.  So let's make this change independent from the hang fix, if possible (and merge it after the hang's fixed).  Thanks!

**Pull request closed without merging**
