### PR TITLE
87.8 -> 87.9

### PR DESCRIPTION
**Pull request by maxtaco**

### CODE REVIEW

**Comment by maxtaco** [comment]
r? @adamjspooner  / @cecileboucheron ?

even points on the dial are usually all static!

**Comment by hyperobject** [comment]
Seems like it might be a little weird to claim that we have a station that could actually exist?

**Comment by adamjspooner** [comment]
Yeah, I think that was part of the joke (this station doesn't exist).

**Comment by maxtaco** [comment]
My immediate association is "static"

**Comment by cecileboucheron** [comment]
I wanted to pick something that doesn't exist. How about 87.7?

**Comment by cecileboucheron** [comment]
👍

**Pull request merged**
