### PR TITLE
dummy PR for CI

### PR DESCRIPTION
**Pull request by oconnor663**
Hmm, I still haven't figured out whether I need to open my own PR to trigger these.

https://github.com/keybase/client/pull/8830

### CODE REVIEW

**Comment by steev** [comment]
Why is it only building Android as well?  Is it set up to expect arm/arm64 builds to be Android/iOS?

**Comment by oconnor663** [comment]
Rerunning once more. Hopefully third time's the charm.

@steev do you mean our CircleCI builds? We only use that for mobile, and we use Jenkins for desktop.

**Comment by oconnor663** [comment]
We have some ongoing CI issues not related to this PR. Will have to fix those first. Sorry for the delay.

**Comment by jzila** [comment]
I just fixed CI and kicked off a rebuild of this PR.

**Pull request closed without merging**
