### PR TITLE
More automated installer building

### PR DESCRIPTION
**Pull request by zanderz**
Jenkins is building + signing installers now. Still need to decide what best to do with the build products, and the workflow of making sure a signed in session is maintained on the build machine. But once this is merged, I can set jenkins to build master instead of this branch. @maxtaco @cjb

### CODE REVIEW

**Comment by maxtaco** [comment]
:+1:

**Comment by cjb** [comment]
@zanderz Does it make sense to commit the Jenkins build config in this PR too?

**Comment by zanderz** [comment]
whoops, I had Max's thumbs up there so I merged. I'll look into exporting it.

**Comment by cjb** [comment]
No worries, you can do a separate PR for it, just thought it'd be good to get it backed up.  Perhaps it should go in the keybase/devops repo.

**Pull request merged**
