### PR TITLE
chat input names: fix self chat and sbs names

### PR DESCRIPTION
**Pull request by songgao**
Examples:

Message to yourself
Message to +1(123)456-789
Message to alice@example.com
Message to AndrewYang@twitter

### CODE REVIEW

**Comment by joshblum** [comment]
@songgao what about the difference between mobile and desktop wrt the teamname being shown or not

**Comment by songgao** [comment]
> @songgao what about the difference between mobile and desktop wrt the teamname being shown or not

Hmm are you suggesting we could similarly check length there and show full team name if it's short?

**Comment by joshblum** [comment]
I just think it should be consistent. Maybe a better question for design but I thought it was odd the team name was missing on mobile

**Comment by chrisnojima** [comment]
Desktop and mobile can be different

**Pull request merged**
