### PR TITLE
Filtering and sort order for team list

### PR DESCRIPTION
**Pull request by buoyad**
cc @keybase/y2ksquad

### CODE REVIEW

**Comment by heronhaye** [comment]
Might be easier to do this in go

**Comment by buoyad** [comment]
@heronhaye this doesn't seem too bad to me

**Comment by jakob223** [comment]
Should I review this or do we wanna do it in go instead

**Comment by buoyad** [comment]
@jakob223 review away

**Comment by buoyad** [comment]
@keybase/react-hackers bump

**Comment by buoyad** [comment]
I put a mobile style fix in #23669, check that out if testing mobile.

**Pull request merged**
