### PR TITLE
Bump emoji vendor

### PR DESCRIPTION
**Pull request by joshblum**
https://github.com/kyokomi/emoji/compare/2e9a9507333f3ee28f3fab88c2c3aba34455d734...eba9a9d7bfd64dcfe6e90fb3d53b2f3357a015c3

updates emoji lib which powers desktop notifications/cli

### CODE REVIEW

**Comment by mmaxim** [comment]
What inspired this?

**Comment by joshblum** [comment]
nothing specific, when I was doing the reacjibar i saw the lib imported and wanted to check for any updates

**Comment by joshblum** [comment]
@mmaxim this address the issue of newer emojis not showing up in the reacji bar: 
image

**Comment by joshblum** [comment]
(flake unrelated)

**Pull request merged**
