### PR TITLE
emoji picker works

### PR DESCRIPTION
**Pull request by songgao**
* reafactor data caching
* add the desktop bookmark bar for jumping to different sections
* make custom emojis work with filtering
* other fixes and tweaks

### CODE REVIEW

**Comment by mmaxim** [comment]
This just throws a JS error for me, I'll fix.

**Comment by mmaxim** [comment]
Problem is that if a custom emoji is in the frequent list

**Comment by chrisnojima** [comment]
this will work eventually right

**Comment by mmaxim** [comment]
Going to merge this since it allows me to use the picker again for customs (master is broken for me). But @songgao, there needs to be code in here to make it so the frequent section can pick up customs.

**Pull request merged**
