### PR TITLE
[WIP] shrinkpack

### PR DESCRIPTION
**Pull request by chromakode**
:warning: For testing, please do not merge!

### CODE REVIEW

**Comment by chromakode** [comment]
@keybase/react-hackers 

Ok, so I've completed this experiment and it's ready for discussion.

This branch uses [shrinkpack](https://github.com/JamieMason/shrinkpack) to vendor the npm dependencies of the desktop client. I've removed the tarballs from this branch so that you can easily view the diff. Findings:

 * It is possible to achieve an npm install with no http requests, but there were a couple annoying blockers I had to fix:
    * `electron-prebuilt` needed a patch to make it download packages from a local directory.
    * `node-gyp` and `node-pre-gyp` annoyingly require command line arguments to prevent them from making requests: `--build-from-source --tarball=`pwd`/vendor/node-`node -v`-headers.tar.gz`. This feels  gross and brittle.

 * Shrinkpack works well. It seems about as convenient as an npm vendoring tool could be. It requires no consideration on part of package consumers -- once you run `shrinkpack` in the code directory, people who clone the repo just need to `npm install`. This works by rewriting the `npm-shrinkwrap.json` file to point to local tarballs checked into the repository. It would be a great solution if all we had to vendor was npm packages.

 * The filesizes are feasible to store in git, but would slow down the initial fetch significantly. Deps clock in at 19mb of npm packages, 79mb of electron binaries and node headers. This is a lot better than I expected!

 * This doesn't address installing eslint globally from a vendored source. That should be doable, but I hit my timebox on it.

 * This doesn't prevent unknown (or newly introduced) external requests from being made.

 * This doesn't address other parts of our build chain, like `go get`s and whatever packages are downloaded by mobile builds. I think it's important for a solution to include everything eventually. This means finding a more general approach or lots of specific vendoring tweaks like in this branch.

My original goal in this exploration was to find a way to vendor external dependencies so that:

 * Attempts to reproduce a build have the exact same set of dependencies to start with -- ideally all information to produce a build can be expressed in a few repositories.
 * We have an audit trail of dependencies as they change
 * Builds don't depend upon external services we don't run

This work gets part of the way there, but it's clear that doing vendoring on a case-by-case basis will be intensive for tools that weren't designed with thought for this use case. I think with some elbow-grease we could fully vendor everything with similar approaches, but I'm wary of running into rabbit holes for each case like electron and gyp above.

One thing I'd like to try that might be a short cut would be to write an HTTP proxy that redirects external requests to cached copies checked into a git repo. All of the package managers which we use support HTTP proxy configuration. The theory is that the URLs packages exist at should be slow to change, since package managers need to be stable for a long time. It looks like [goproxy](https://github.com/elazarl/goproxy/blob/master/examples/goproxy-sslstrip/sslstrip.go) is a good candidate for hacking on this. I think it'd be worth a little exploratory work to see whether this is feasible for intercepting npm and other package managers.

**Comment by chrisnojima** [comment]
eslint isn't part of the build so i don't think it has to be a part of this story. the ultimate point is to ensure what we deliver is what we intend

**Comment by chrisnojima** [comment]
afaik we entirely vendor our go stuff so it shouldn't ever go get anything

**Comment by gabriel** [comment]
https://git-lfs.github.com/?utm_source=github_site&utm_medium=blog&utm_campaign=gitlfs

**Pull request closed without merging**
