### PR TITLE
custom scrollbars. dark aware scrollbars. obtrusive aware scrollbars

### PR DESCRIPTION
**Pull request by chrisnojima**
This PR enables

1. Detection of osx auto hide scrollbar behavior
1. Custom css for dark mode scrollbars

cc: @adamjspooner

### CODE REVIEW

**Comment by hyperobject** [comment]
Looks mostly good to me, a few potential issues:
* In dark mode with autohiding scrollbar, the scrollbar thumb doesn't seem like it's the right color: Screen Shot 2019-09-27 at 10 50 51 AM
* after starting app in dark mode + autohiding scrollbar, changing the system to not autohiding scrollbar causes the app's scrollbars to be in light mode

**Comment by chrisnojima** [comment]
@hyperobject we don't (and can't believe) control the auto hiding scroll bars colors at all. in this PR we don't attempt to

**Comment by heronhaye** [comment]
Looks great. Autohide is only on osx?

**Comment by chrisnojima** [comment]
i believe so, but the code is agnostic

**Pull request merged**
