### PR TITLE
Encode # as %23

### PR DESCRIPTION
**Pull request by MarcoPolo**
@keybase/react-hackers

### CODE REVIEW

**Comment by chrisnojima** [comment]
👍

**Comment by gabriel** [comment]
Are there any other characters?

You can test on command line by creating file in a tlf with those chars:

```sh
# Doesn't work
open file:///keybase/public/gabrielh/test#foo.txt
# Works
open file:///keybase/public/gabrielh/test%23foo.txt
```

**Comment by gabriel** [comment]
👍

**Comment by gabriel** [comment]
I'm guessing # might be the only char since it probably uses an url parser but when getting the file path chooses to ignore the anchor part which is probably in the url spec even for files.

**Comment by MarcoPolo** [comment]
You can also test by making a folder `/keybase/private/you#other`

**Comment by chromakode** [comment]
Why not use `encodeURIComponent`?

**Comment by MarcoPolo** [comment]
`encodeURIComponent` encodes everything so `/keybase/private/foo,bar#baz` becomes `"%2Fkeybase%2Fprivate%2Ffoo%2Cbar%23baz"`

Which `open ...` does not handle well

**Comment by chrisnojima** [comment]
Let's just keep this simple. This fix works and our urls are never more
complicated than this

**Comment by chromakode** [comment]
Sounds good :+1:

**Pull request merged**
