### PR TITLE
use the /usr/lib64 prefix for the Firefox native messaging manifest

### PR DESCRIPTION
**Pull request by oconnor663**
This should fix https://github.com/keybase/client/issues/8754.

r? @maxtaco 

@shazow do you have a moment to eyeball this? Let me know if you remember dealing with the same issue in a different way.

### CODE REVIEW

**Comment by shazow** [comment]
Looks like a plausible improvement.

If we want to trade off some cleanliness for brute forcing, could potentially install it into all possible paths. :P But I'd try this for a while first.

**Comment by oconnor663** [comment]
I was worried about installing in both, because I don't know how well package managers will deal with the situation where one of the directories is symlinked to the other. If I was confident they wouldn't choke on it, I would've preferred to install both, as insurance against a change in Firefox behavior if nothing else.

**Comment by oconnor663** [comment]
Ugh, Arch isn't happy with the current approach:

```
error: failed to commit transaction (conflicting files)
keybase-git: /usr/lib64 exists in filesystem
Errors occurred, no packages were upgraded.
```

I'll try replacing this change with one that only applies in RPM packaging. (Though maybe Debian needs the path change too? Will play with it.)

**Comment by oconnor663** [comment]
Ok, current fix seems to work on Rawhide and doesn't affect non-RPM systemd.

**Pull request closed without merging**
