### PR TITLE
Make tab content flex styled & views manage scroll

### PR DESCRIPTION
**Pull request by awendland**
Apply only `display: flex` and `flex: 1` (therefore, remove `overflow: auto`) to containers in meta navigator and tab-bar. This will expose a view to the child that is the full, available screen size that they can play with, no extra overflow attached. If the child needs to overflow, it can wrap it's contents in a normal Box/Div that has `scrollable: auto` (provided as `globalStyles.scrollable`). This separates the concerns of child overflow management away from the tab bar and meta navigator and provides more power to the children to maintain their scroll behavior/layout behavior in a marginally impactful SLOC manner. This also brings parity to how layouts are handled on native.

I attempted to fix all views that would be impacted by this change, the main ones being the dumb sheet, settings page, and devices list.

This arose out of a conversation with @MarcoPolo around layout goals and isolation of tab bar and meta navigator.

Ideally there would be no visual diffs, looking forward to what visdiff has to bring us.

@keybase/react-hackers

### CODE REVIEW

**Comment by keybase-ci-visdiff** [comment]
:mag_right: These commits introduced some visual changes:
 * Changed: **Menubar-Public_Truncated** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1465864699339-fda98dee6d7e-a0d2b6ff4cd0/Menubar-Public_Truncated-fda98dee6d7e.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1465864699339-fda98dee6d7e-a0d2b6ff4cd0/Menubar-Public_Truncated-a0d2b6ff4cd0.png)  
   Menubar-Public_Truncated comparison
 * Changed: **Menubar-Public_Normal** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1465864699339-fda98dee6d7e-a0d2b6ff4cd0/Menubar-Public_Normal-fda98dee6d7e.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1465864699339-fda98dee6d7e-a0d2b6ff4cd0/Menubar-Public_Normal-a0d2b6ff4cd0.png)  
   Menubar-Public_Normal comparison
 * Changed: **Menubar-Public_Menu_Showing** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1465864699339-fda98dee6d7e-a0d2b6ff4cd0/Menubar-Public_Menu_Showing-fda98dee6d7e.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1465864699339-fda98dee6d7e-a0d2b6ff4cd0/Menubar-Public_Menu_Showing-a0d2b6ff4cd0.png)  
   Menubar-Public_Menu_Showing comparison
 * Changed: **Menubar-Private_Truncated** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1465864699339-fda98dee6d7e-a0d2b6ff4cd0/Menubar-Private_Truncated-fda98dee6d7e.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1465864699339-fda98dee6d7e-a0d2b6ff4cd0/Menubar-Private_Truncated-a0d2b6ff4cd0.png)  
   Menubar-Private_Truncated comparison
 * Changed: **Menubar-Private_Normal** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1465864699339-fda98dee6d7e-a0d2b6ff4cd0/Menubar-Private_Normal-fda98dee6d7e.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1465864699339-fda98dee6d7e-a0d2b6ff4cd0/Menubar-Private_Normal-a0d2b6ff4cd0.png)  
   Menubar-Private_Normal comparison
 * Changed: **Menubar-Private_Menu_Showing** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1465864699339-fda98dee6d7e-a0d2b6ff4cd0/Menubar-Private_Menu_Showing-fda98dee6d7e.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1465864699339-fda98dee6d7e-a0d2b6ff4cd0/Menubar-Private_Menu_Showing-a0d2b6ff4cd0.png)  
   Menubar-Private_Menu_Showing comparison

**Comment by keybase-ci-visdiff** [comment]
:mag_right: These commits introduced some visual changes:
 * Changed: **Menubar-Public_Truncated** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1465864811090-fda98dee6d7e-a0d2b6ff4cd0/Menubar-Public_Truncated-fda98dee6d7e.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1465864811090-fda98dee6d7e-a0d2b6ff4cd0/Menubar-Public_Truncated-a0d2b6ff4cd0.png)  
   Menubar-Public_Truncated comparison
 * Changed: **Menubar-Public_Normal** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1465864811090-fda98dee6d7e-a0d2b6ff4cd0/Menubar-Public_Normal-fda98dee6d7e.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1465864811090-fda98dee6d7e-a0d2b6ff4cd0/Menubar-Public_Normal-a0d2b6ff4cd0.png)  
   Menubar-Public_Normal comparison
 * Changed: **Menubar-Public_Menu_Showing** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1465864811090-fda98dee6d7e-a0d2b6ff4cd0/Menubar-Public_Menu_Showing-fda98dee6d7e.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1465864811090-fda98dee6d7e-a0d2b6ff4cd0/Menubar-Public_Menu_Showing-a0d2b6ff4cd0.png)  
   Menubar-Public_Menu_Showing comparison
 * Changed: **Menubar-Private_Truncated** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1465864811090-fda98dee6d7e-a0d2b6ff4cd0/Menubar-Private_Truncated-fda98dee6d7e.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1465864811090-fda98dee6d7e-a0d2b6ff4cd0/Menubar-Private_Truncated-a0d2b6ff4cd0.png)  
   Menubar-Private_Truncated comparison
 * Changed: **Menubar-Private_Normal** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1465864811090-fda98dee6d7e-a0d2b6ff4cd0/Menubar-Private_Normal-fda98dee6d7e.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1465864811090-fda98dee6d7e-a0d2b6ff4cd0/Menubar-Private_Normal-a0d2b6ff4cd0.png)  
   Menubar-Private_Normal comparison
 * Changed: **Menubar-Private_Menu_Showing** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1465864811090-fda98dee6d7e-a0d2b6ff4cd0/Menubar-Private_Menu_Showing-fda98dee6d7e.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1465864811090-fda98dee6d7e-a0d2b6ff4cd0/Menubar-Private_Menu_Showing-a0d2b6ff4cd0.png)  
   Menubar-Private_Menu_Showing comparison

**Comment by awendland** [comment]
I'm looking into why the menubar now has a scrollbar, and how to revert this regression.

**Comment by awendland** [comment]
Bump @keybase/react-hackers

**Comment by chrisnojima** [comment]
code seems fine. did you verify all the popups (tracker, pinentry, etc)

**Comment by awendland** [comment]
@chrisnojima, I verified some but I forgot about tracker. I'll double check those again.

**Comment by awendland** [comment]
@chrisnojima I've run through tracker, pinentry, the menubar, the login/registration flow, the settings screen, devices screen, folders screen, stylesheet, and dumb sheet and they all appear to be working fine now.

**Comment by awendland** [comment]
I'm rerunning visdiff to see if the aforementioned regressions have been fixed

**Comment by chrisnojima** [comment]
code looks fine, if visdiff looks good :shipit:

**Comment by awendland** [comment]
Yeehaw!
*Visdiff output:*
screen shot 2016-06-14 at 3 17 10 pm

**Pull request merged**
