### PR TITLE
Chat fixed config rpc

### PR DESCRIPTION
**Pull request by mlsteele**

### CODE REVIEW

**Comment by mmaxim** [comment]
What is this for?

**Comment by mlsteele** [comment]
https://keybase.atlassian.net/browse/DESKTOP-7039

**Comment by mmaxim** [comment]
@buoyad just make sure the JS doesn't just spam this RPC for every message it is iterating over.

**Comment by mmaxim** [comment]
Also can we use the word `Static` instead of `Fixed`? I thought this was fixing something.

**Comment by buoyad** [comment]
@mmaxim ok, it won't

**Comment by mlsteele** [comment]
I thought 'static' might be trampling on language keywords since it lit up in my editor. But I'll try it and if it compiles I guess it's fine.

**Comment by mmaxim** [comment]
Just take your editor out of C++ mode :)

**Pull request merged**
