### PR TITLE
Image url needs quote wrapping

### PR DESCRIPTION
**Pull request by chrisnojima**
else paths with spaces get unhappy

@keybase/react-hackers

### CODE REVIEW

**Comment by MarcoPolo** [comment]
:+1:

**Comment by cjb** [comment]
@maxtaco called it!

**Comment by cjb** [comment]
hm, wait, this is just svgfoldericon.

Other icons I saw that were broken: signup invite code page, top left cross to close pinentry.

**Comment by chrisnojima** [comment]
@keybase/react-hackers this is fixed now

**Comment by MarcoPolo** [comment]
Why do you only have to do `fix` when resolving as url?

**Comment by chrisnojima** [comment]
@MarcoPolo because fix is doing things like changing the separators and encoding it as a uri, which won't work when talking about it as a file path

**Pull request merged**
