### PR TITLE
updated avatar sizes

### PR DESCRIPTION
**Pull request by chrisnojima**
@keybase/react-hackers

### CODE REVIEW

**Comment by keybase-ci-visdiff** [comment]
:mag_right: :zap: These commits introduced some visual changes:
 * Changed: **Tracker-You_track_them** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1464705877871-3c328a63b964-dfc20da401f2/Tracker-You_track_them-3c328a63b964.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1464705877871-3c328a63b964-dfc20da401f2/Tracker-You_track_them-dfc20da401f2.png)  
   Tracker-You_track_them comparison
 * Changed: **Tracker-Whatevz** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1464705877871-3c328a63b964-dfc20da401f2/Tracker-Whatevz-3c328a63b964.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1464705877871-3c328a63b964-dfc20da401f2/Tracker-Whatevz-dfc20da401f2.png)  
   Tracker-Whatevz comparison
 * Changed: **Tracker-Unfollowed** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1464705877871-3c328a63b964-dfc20da401f2/Tracker-Unfollowed-3c328a63b964.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1464705877871-3c328a63b964-dfc20da401f2/Tracker-Unfollowed-dfc20da401f2.png)  
   Tracker-Unfollowed comparison
 * Changed: **Tracker-Only_one_proof** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1464705877871-3c328a63b964-dfc20da401f2/Tracker-Only_one_proof-3c328a63b964.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1464705877871-3c328a63b964-dfc20da401f2/Tracker-Only_one_proof-dfc20da401f2.png)  
   Tracker-Only_one_proof comparison
 * Changed: **Tracker-New_user_follows_me** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1464705877871-3c328a63b964-dfc20da401f2/Tracker-New_user_follows_me-3c328a63b964.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1464705877871-3c328a63b964-dfc20da401f2/Tracker-New_user_follows_me-dfc20da401f2.png)  
   Tracker-New_user_follows_me comparison
 * Changed: **Tracker-New_user** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1464705877871-3c328a63b964-dfc20da401f2/Tracker-New_user-3c328a63b964.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1464705877871-3c328a63b964-dfc20da401f2/Tracker-New_user-dfc20da401f2.png)  
   Tracker-New_user comparison
 * Changed: **Tracker-Logged_out** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1464705877871-3c328a63b964-dfc20da401f2/Tracker-Logged_out-3c328a63b964.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1464705877871-3c328a63b964-dfc20da401f2/Tracker-Logged_out-dfc20da401f2.png)  
   Tracker-Logged_out comparison
 * Changed: **Tracker-Followed** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1464705877871-3c328a63b964-dfc20da401f2/Tracker-Followed-3c328a63b964.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1464705877871-3c328a63b964-dfc20da401f2/Tracker-Followed-dfc20da401f2.png) [(diff)](http://keybase-app-visdiff.s3.amazonaws.com/1464705877871-3c328a63b964-dfc20da401f2/Tracker-Followed.png)
 * Changed: **Tracker-Changed_Broken_proofs_user_you_dont_follow** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1464705877871-3c328a63b964-dfc20da401f2/Tracker-Changed_Broken_proofs_user_you_dont_follow-3c328a63b964.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1464705877871-3c328a63b964-dfc20da401f2/Tracker-Changed_Broken_proofs_user_you_dont_follow-dfc20da401f2.png) [(diff)](http://keybase-app-visdiff.s3.amazonaws.com/1464705877871-3c328a63b964-dfc20da401f2/Tracker-Changed_Broken_proofs_user_you_dont_follow.png)
 * Changed: **Tracker-Changed_Broken_proofs** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1464705877871-3c328a63b964-dfc20da401f2/Tracker-Changed_Broken_proofs-3c328a63b964.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1464705877871-3c328a63b964-dfc20da401f2/Tracker-Changed_Broken_proofs-dfc20da401f2.png) [(diff)](http://keybase-app-visdiff.s3.amazonaws.com/1464705877871-3c328a63b964-dfc20da401f2/Tracker-Changed_Broken_proofs.png)
 * Changed: **Tracker-Barely_there** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1464705877871-3c328a63b964-dfc20da401f2/Tracker-Barely_there-3c328a63b964.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1464705877871-3c328a63b964-dfc20da401f2/Tracker-Barely_there-dfc20da401f2.png) [(diff)](http://keybase-app-visdiff.s3.amazonaws.com/1464705877871-3c328a63b964-dfc20da401f2/Tracker-Barely_there.png)
 * Changed: **Tracker-5_proofs** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1464705877871-3c328a63b964-dfc20da401f2/Tracker-5_proofs-3c328a63b964.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1464705877871-3c328a63b964-dfc20da401f2/Tracker-5_proofs-dfc20da401f2.png) [(diff)](http://keybase-app-visdiff.s3.amazonaws.com/1464705877871-3c328a63b964-dfc20da401f2/Tracker-5_proofs.png)

**Comment by chrisnojima** [comment]
those changes are expected, thanks visdiff bot!

**Comment by chrisnojima** [comment]
@keybase/react-hackers bump

**Comment by MarcoPolo** [comment]
🚢

**Comment by chromakode** [comment]
:ok_hand:

**Pull request merged**
