### PR TITLE
remove thumb build

### PR DESCRIPTION
**Pull request by chrisnojima**
@maxtaco @mmaxim I think this is the real fix

cc: @keybase/react-hackers

### CODE REVIEW

**Comment by chrisnojima** [comment]
this should fix the build issue we have. see https://stackoverflow.com/questions/23612499/ld-b-bl-blx-thumb2-branch-out-of-range-from etc

**Comment by chrisnojima** [comment]
i'm just going to merge this and kick a build and see if it works. i'll revert if its weird

**Comment by mmaxim** [comment]
I saw that, but see this:

https://stackoverflow.com/questions/8390606/is-there-a-way-to-compile-for-arm-rather-than-thumb-in-xcode-4

The code we get will be worse.

**Comment by mmaxim** [comment]
Not sure this is better than the PR I put up, which won't affect anything about code size/speed.

**Comment by chrisnojima** [comment]
its not clear what the perf impact will be so lets see

**Comment by mmaxim** [comment]
This also only affects code generated by the Xcode ObjC compiler during the build, it won't do anything to libraries we link against, or the Go code, so I'm not sure it is any sort of silver bullet.

**Comment by mmaxim** [comment]
I'm fine either way though.

**Comment by chrisnojima** [comment]
i reverted the build (but still have it going) so we can see what the perf is like

**Comment by mmaxim** [comment]
Think it will end up being just a size optimization, but not sure what runtime perf implications that has.

**Comment by mmaxim** [comment]
I'm running it now, perf seems fine. Looks like the size is only +2MB so probably a fine solution.

**Comment by chrisnojima** [comment]
lets chat 2moro (or on slack)

**Pull request merged**
