### PR TITLE
change CLI log level from INFO to NOTICE and use INFO in rpc/connection.go

### PR DESCRIPTION
**Pull request by songgao**
This depends on https://github.com/keybase/go-framed-msgpack-rpc/pull/132 . If everything looks good, I'll merge that first and update vendor to master here.

### CODE REVIEW

**Comment by maxtaco** [comment]
This might break something, no?  What if we're expecting, in some subcommand, for INFO to hit the console?

**Comment by songgao** [comment]
@maxtaco I was gonna change all INFO in service to NOTICE, but @patrickxb brought up a good point (in #kbfs) that commands shouldn’t rely on logging to print necessary information to terminal anyway, so it seemed best to just up the level first and see what happens. If any commands break we could change the logging calls from INFO to NOTICE.

**Comment by patrickxb** [comment]
Could the rpc package have an option to open its own log file?  We can change log send to upload another file (just did that for git).

Also, `AppConfig` has a `LocalRPCDebug` field for setting up the local rpc log options.  Can't something like that be used to log what you are interested in?  For example, we can change it in `bind/keybase.go` to "csvi" and see all kinds of RPC logging in mobile logs without touching anything else.

**Comment by maxtaco** [comment]
I am a :+1: if @patrickxb is

**Comment by patrickxb** [comment]
LGTM

**Pull request merged**
