### PR TITLE
Add autoCorrect for chat input

### PR DESCRIPTION
**Pull request by cjb**
@keybase/react-hackers 

Use autoCorrect={true} for the main Chat conversation input on mobile.

### CODE REVIEW

**Comment by MarcoPolo** [comment]
👍

**Comment by cjb** [comment]
Oops, @chrisnojima says this isn't uncontroversial to do.  I'll close the PR until we discuss it.

**Comment by cjb** [comment]
Reopening since I think we have a go now.

**Comment by keybase-ci-visdiff** [comment]
The commits 9a846ca050e1...ea14861cb180 introduce visual changes on linux. <details><summary>:mag_right: 2 changed</summary>

 * Changed: **Attachment_Message-Basic_Preview_Image_Downloading_Preview** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488382972544-9a846ca050e1-ea14861cb180-linux/Attachment_Message-Basic_Preview_Image_Downloading_Preview-9a846ca050e1.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488382972544-9a846ca050e1-ea14861cb180-linux/Attachment_Message-Basic_Preview_Image_Downloading_Preview-ea14861cb180.png)  
   Attachment_Message-Basic_Preview_Image_Downloading_Preview comparison
 * Changed: **Attachment_Message-Basic_Not_loaded** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488382972544-9a846ca050e1-ea14861cb180-linux/Attachment_Message-Basic_Not_loaded-9a846ca050e1.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488382972544-9a846ca050e1-ea14861cb180-linux/Attachment_Message-Basic_Not_loaded-ea14861cb180.png)  
   Attachment_Message-Basic_Not_loaded comparison
</summary>

**Comment by keybase-ci-visdiff** [comment]
The commits 9a846ca050e1...ea14861cb180 introduce visual changes on linux. <details><summary>:mag_right: 2 changed</summary>

 * Changed: **Attachment_Message-Basic_Preview_Image_Downloading_Preview** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488386453986-9a846ca050e1-ea14861cb180-linux/Attachment_Message-Basic_Preview_Image_Downloading_Preview-9a846ca050e1.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488386453986-9a846ca050e1-ea14861cb180-linux/Attachment_Message-Basic_Preview_Image_Downloading_Preview-ea14861cb180.png)  
   Attachment_Message-Basic_Preview_Image_Downloading_Preview comparison
 * Changed: **Attachment_Message-Basic_Not_loaded** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488386453986-9a846ca050e1-ea14861cb180-linux/Attachment_Message-Basic_Not_loaded-9a846ca050e1.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1488386453986-9a846ca050e1-ea14861cb180-linux/Attachment_Message-Basic_Not_loaded-ea14861cb180.png)  
   Attachment_Message-Basic_Not_loaded comparison
</summary>

**Pull request merged**
