### PR TITLE
Fix and unskip TestImplicitResetBadReadds

### PR DESCRIPTION
**Pull request by zapu**
Needs https://github.com/keybase/keybase/pull/2169 to pass

### CODE REVIEW

**Comment by zapu** [comment]
these calls are blocked by the server. Initially I was going to add checks to team player,but I decided not to. Do you think we need these tests?

**Comment by maxtaco** [comment]
What if the server is malicious?

**Comment by mlsteele** [comment]
@maxtaco In general if there is a client bug with an iteam membership change and the server is malicious, then the client can 'corrupt' the team by adding someone that shouldn't be there. But
1. Future `LookupImplicitTeam(name) -> team` calls will fail at the name assertion
2. In the racy/cache cases where that doesn't help and someone ends up encrypting to someone they didn't want to, it's basically because someone with admin status in the iteam hacked it, so they could've been publishing behind their back anyway.

**Comment by zapu** [comment]
It still have to be someone in the team signing them in, but with a different role. Honest server should not accept it, but I'd consider that stopping someone's buggy client rather than stopping someone's malicious intent. Also it would be only downgrading or upgrading someone in implicit team rather than bringing someone else in.

**Comment by maxtaco** [comment]
ok then 👍 , thx!

**Pull request merged**
