### PR TITLE
Allow backspacing across lines in terminal

### PR DESCRIPTION
**Pull request by heronhaye**
Linux Demo: https://asciinema.org/a/BfvzbZnYK4imPwKR0d4wVOzrg
Probably want to try on Mac and Windows too. I did some basic smoketesting and everything looks OK.

I don't think we can get support for Ctrl-U across lines, seems it only supports color codes.

We might be able to modify it to support an arbitrary width/height. By default its 80x24 with no option to set it anywhere, but width and height are internal variables. At that point it may be better to use another terminal library.

Also, if your terminal is smaller than 80 chars wide or you resize it, it's completely broken, but that was true before as well.

### CODE REVIEW

**Comment by heronhaye** [comment]
@patrickxb, are you familiar with this part?

**Comment by patrickxb** [comment]
doesn't this undo @AMarcedone work?  I never reviewed that stuff.  @maxtaco?

**Comment by heronhaye** [comment]
https://github.com/keybase/client/pull/12208

**Comment by mmaxim** [comment]
I reverted this to fix kbfs-server tests.

**Comment by mmaxim** [comment]
Also did anyone address @patrickxb's question?

https://github.com/keybase/client/pull/13476#issuecomment-416747003

**Pull request merged**
