### PR TITLE
add sync toggle for Files

### PR DESCRIPTION
**Pull request by songgao**

### CODE REVIEW

**Comment by jzila** [comment]
@songgao shouldn't this be guarded by a flag?

**Comment by songgao** [comment]
Yeah good call; will do before merging!

**Comment by songgao** [comment]
this needs more tweaks, so I'm untagging review for now.

**Comment by songgao** [comment]
actually the tweaks will be on kb.switch, so this is still ready for review.

**Comment by jakob223** [comment]
This works for me on desktop, but I'm getting the following confusing behavior on iOS. Not sure if this is due to a problem with the branch or a problem with my setup.

**Comment by jakob223** [comment]
Oops, image upload issue. Here it is.
image

**Comment by songgao** [comment]
Hmm just tried over here again and it worked for me. Presumably this is your test account? Is it in any teams?

**Comment by jakob223** [comment]
🤦‍♂️ thanks song.. my test account turns out not to be in any teams. Sorry for the false ⏰ ..

**Pull request merged**
