### PR TITLE
Desktop: getenv instead of process.env

### PR DESCRIPTION
**Pull request by gabriel**
So I set an env var to "1" and it silently failed. I found this getenv package which is tiny and allows you to get envvars by int, float, bool etc and errors nicely if a var is invalid or not set at all (required).

Basically if you mess up env vars at all this will catch it.

Also changing showDevTools to use different env var KEYBASE_SHOW_DEVTOOLS

### CODE REVIEW

**Comment by gabriel** [comment]
@keybase/react-hackers

**Comment by gabriel** [comment]
Cause my window was looking like:

2016-01-07 at 1 19 pm

**Comment by chrisnojima** [comment]
so this is fine BUT, we have to be super careful to not do this with process.env.NODE_ENV outside of webpack since we inject it with the define plugin so it'll only replace it if its of the form process.env.NODE_ENV and won't work with getenv('NODE_ENV') etc :+1:

**Comment by gabriel** [comment]
yep left `process.env.NODE_ENV` key in that spot untouched

**Comment by chrisnojima** [comment]
yup, you can merge

**Pull request merged**
