### PR TITLE
--json flags in keybase team list-requests and keybase id

### PR DESCRIPTION
**Pull request by pzduniak**

### CODE REVIEW

**Comment by pzduniak** [comment]
Quite dirty in `keybase id` but it was the simplest thing I could think of without massively reorganizing the code. Things to consider:
1) What should be the JSON output? This current one looks weird, although as simple in the code as possible.
2) From what I've seen other UI funcs only output to an error logger so stdout should stay clear, assuming that the error logger writes to stderr. Should we further clean them up?

**Comment by zapu** [comment]
@maxtaco can this be deferred to you? I think it should either use a new IdentifyUI and a way to switch them in UI based on command flags; or work with `cli.Identify2` return value instead and convert that to JSON.

Regarding 2) please make sure any `--json` commands do not print extra output to stdout, it should be pure json, and yes, additional info can go to stderr.

**Comment by maxtaco** [comment]
I agree it's cleaner to make a new identifyUI to handle this case.  It can probably be a lot simpler than the UI that's there since I wrote that very early in the project and think it's overly-complicated with hindsight

**Comment by zapu** [comment]
what would be a good way to switch between these UIs? I don't think there is such option right now

**Comment by maxtaco** [comment]
in `cmd_id.go:`

```go
type idCmdUIWrapper struct {
     origUI libkb.UI
}

func (i idCommandUIWrapper) GetIdentifyUI() libkb.IdentifyUI {
   // you write something here to either return the i.origUI.GetIdentifyUI() or a new one
}

// somewhere in run function if wanting json
g.UI = idCmdWrapperUI{ origUI : g.UI }
```

**Comment by pzduniak** [comment]
Oh wow, that sounds so obvious now. Done! Since I've totally replaced the UI, we don't have to worry about any additional stdout output. lmk if we want to keep this as-is or if it's ok @maxtaco

**Comment by zapu** [comment]
Another thing that's good to remember - not saying that it doesn't work or anything - but id should work in any combination of these states:
1) `--standalone` / service mode
2) user logged in / no user

**Comment by pzduniak** [comment]
Just checked, all 4 cases work ok.

**Comment by zapu** [comment]
wow this looks really neat now. thanks a lot!

I will take a closer look tomorrow though

**Comment by zapu** [comment]
line 88 in cmd_id.go: `v.G().UI.GetDumbOutputUI().Printf(msg)` can we change to `PrintfStderr` ?

**Comment by zapu** [comment]
Because it mostly plumbs our internals to json and prints it, some results might be hard to understand for callers, like:
```
                "proofId": 4,
                "proofResult": {
                    "state": 2,
                    "status": 150,
                    "desc": "503 Service Temporarily Unavailable"
                },
```

maybe it's not a big deal.

it's clear when you call it interactively, because you get this on stderr:
`▶ ERROR failed to identify "example": 1 followed proof failed`

or I guess callers can just look for "breaksTracking" field, but they would have to know that. Is there something we can do to make it easily discoverable?

**Comment by zapu** [comment]
Example output for anyone coming here to look:
```
{
    "username": "zapu",
    "lastTrack": null,
    "cryptocurrencies": null,
    "stellar": {
        "accountID": "GAG7JTRE6SZZXN5NDH7WTTQ7JKZL6TOGTXX5PODHIOPYEE6COWQGSRRE",
        "federationAddress": "zapu*keybase.io",
        "sigID": "42d5834dc479b682fa3ecf2224cfbbcb135b63b58bcc0c0c38a09fbdc8c8dce50f"
    },
    "identifyKey": {
        "pgpFingerprint": "RxwWc2vX57FdbZ2DrhdEqD33NWg=",
        "KID": "01164ae6a89ff102f68252d8cf84abadb3e6cabff734e01182265597d440f763046e0a",
        "breaksTracking": false,
        "sigID": "4077aafc30979db6d2460ad765ff60d756224b3203c2d58c1b15911d05d4cb410f"
    },
    "proofs": [
        {
            "proof": {
                "proofType": 1001,
                "key": "dns",
                "value": "zapu.net",
                "displayMarkup": "zapu.net",
                "sigID": "2f78af85d7fc6202c263d6d49d0f31452a9dd24b006e00ab10d0eb4a84638d890f",
                "mTime": 1519988121000
            },
            "result": {
                "proofId": 3,
                "proofResult": {
                    "state": 1,
                    "status": 1,
                    "desc": ""
                },
                "snoozedResult": {
                    "state": 1,
                    "status": 1,
                    "desc": ""
                },
                "torWarning": false,
                "tmpTrackExpireTime": 0,
                "hint": {
                    "remoteId": "dns://zapu.net",
                    "humanUrl": "dns://zapu.net",
                    "apiUrl": "dns://zapu.net",
                    "checkText": "keybase-site-verification=L3ivhdf8YgLCY9bUnQ8xRSqd0ksAbgCrENDrSoRjjYk"
                },
                "breaksTracking": false
            }
        },
        {
            "proof": {
                "proofType": 1000,
                "key": "https",
                "value": "zapu.net",
                "displayMarkup": "zapu.net",
                "sigID": "ec9ab8a8d6d307adf894d84d4306ab2ef3e09cf573f2acce95b8a25fe3a60a820f",
                "mTime": 1487195456000
            },
            "result": {
                "proofId": 2,
                "proofResult": {
                    "state": 1,
                    "status": 1,
                    "desc": ""
                },
                "snoozedResult": {
                    "state": 1,
                    "status": 1,
                    "desc": ""
                },
                "torWarning": false,
                "tmpTrackExpireTime": 0,
                "hint": {
                    "remoteId": "https://zapu.net/.well-known/keybase.txt",
                    "humanUrl": "https://zapu.net/.well-known/keybase.txt",
                    "apiUrl": "https://zapu.net/.well-known/keybase.txt",
                    "checkText": "hKRib2R5hqhkZXRhY2hlZMOpaGFzaF90eXBlCqNrZXnEIwEgrMqgvitII13oPQQx8yelDcYz5riMbWyP20ZVoKjju3wKp3BheWxvYWTFAu17ImJvZHkiOnsia2V5Ijp7ImVsZGVzdF9raWQiOiIwMTIwYWNjYWEwYmUyYjQ4MjM1ZGU4M2QwNDMxZjMyN2E1MGRjNjMzZTZiODhjNmQ2YzhmZGI0NjU1YTBhOGUzYmI3YzBhIiwiaG9zdCI6ImtleWJhc2UuaW8iLCJraWQiOiIwMTIwYWNjYWEwYmUyYjQ4MjM1ZGU4M2QwNDMxZjMyN2E1MGRjNjMzZTZiODhjNmQ2YzhmZGI0NjU1YTBhOGUzYmI3YzBhIiwidWlkIjoiZWU3MWRiYzhlNGUzZTY3MWUyOWE5NGNhZWY1ZTFiMTkiLCJ1c2VybmFtZSI6InphcHUifSwic2VydmljZSI6eyJob3N0bmFtZSI6InphcHUubmV0IiwicHJvdG9jb2wiOiJodHRwczoifSwidHlwZSI6IndlYl9zZXJ2aWNlX2JpbmRpbmciLCJ2ZXJzaW9uIjoxfSwiY2xpZW50Ijp7Im5hbWUiOiJrZXliYXNlLmlvIGdvIGNsaWVudCIsInZlcnNpb24iOiIxLjAuMTgifSwiY3RpbWUiOjE0ODcxOTU0NTYsImV4cGlyZV9pbiI6NTA0NTc2MDAwLCJtZXJrbGVfcm9vdCI6eyJjdGltZSI6MTQ4NzE5NTQ0MCwiaGFzaCI6IjgxZTliN2VmNzE2Y2U3OWMzNzRhZGY0ZDM0ZjMyMTBjNTY1MTUyZTY2M2RkOWRkY2U3NGFmZTM0ZjMwYmFiZmI4N2VkMmVhYWY3MTZlNTQ3MTgxNTk3YWRlZjRhOGU4OTE2NmY4MmU4ODE1YWFiNGM3ZDUyMDM1YjdkOGE0NTQ0Iiwic2Vxbm8iOjg5NDA1MX0sInByZXYiOiIzM2FmZDQ2YWFlODFjYTJiNTBkYWM5OWMwMjY1NjUxMDA0MTNkODA5OWVjMDhhMmYyZmRhM2E4YjhlMzBjYTdhIiwic2Vxbm8iOjIxLCJ0YWciOiJzaWduYXR1cmUifaNzaWfEQLisvmwu6dHEEZz7Og95d5pugvFoqnBaGT7gsoPQJJiGu4ZnT0eP9x8MeVSPDLgJOwGiapIQMU946mtmh9HYBw+oc2lnX3R5cGUgpGhhc2iCpHR5cGUIpXZhbHVlxCBTV9dPH8ASS8Y2F2/0PGxs/vqJJy0JV1F+0PVbBXJuz6N0YWfNAgKndmVyc2lvbgE="
                },
                "breaksTracking": false
            }
        },
        {
            "proof": {
                "proofType": 3,
                "key": "github",
                "value": "zapu",
                "displayMarkup": "zapu",
                "sigID": "b3dbcea3f1e09d5233813e5add214d6dbd291e9803b145862c7f7ddc112716300f",
                "mTime": 1487195324000
            },
            "result": {
                "proofId": 0,
                "proofResult": {
                    "state": 1,
                    "status": 1,
                    "desc": ""
                },
                "snoozedResult": {
                    "state": 1,
                    "status": 1,
                    "desc": ""
                },
                "torWarning": false,
                "tmpTrackExpireTime": 0,
                "hint": {
                    "remoteId": "bf98a6d8bd28f1488f0f0b0a51e8a1a1",
                    "humanUrl": "https://gist.github.com/bf98a6d8bd28f1488f0f0b0a51e8a1a1",
                    "apiUrl": "https://gist.githubusercontent.com/zapu/bf98a6d8bd28f1488f0f0b0a51e8a1a1/raw/b6e053997b041ad59e4785a2b8d8109ee342479a/keybase.md",
                    "checkText": "hKRib2R5hqhkZXRhY2hlZMOpaGFzaF90eXBlCqNrZXnEIwEgrMqgvitII13oPQQx8yelDcYz5riMbWyP20ZVoKjju3wKp3BheWxvYWTFAuV7ImJvZHkiOnsia2V5Ijp7ImVsZGVzdF9raWQiOiIwMTIwYWNjYWEwYmUyYjQ4MjM1ZGU4M2QwNDMxZjMyN2E1MGRjNjMzZTZiODhjNmQ2YzhmZGI0NjU1YTBhOGUzYmI3YzBhIiwiaG9zdCI6ImtleWJhc2UuaW8iLCJraWQiOiIwMTIwYWNjYWEwYmUyYjQ4MjM1ZGU4M2QwNDMxZjMyN2E1MGRjNjMzZTZiODhjNmQ2YzhmZGI0NjU1YTBhOGUzYmI3YzBhIiwidWlkIjoiZWU3MWRiYzhlNGUzZTY3MWUyOWE5NGNhZWY1ZTFiMTkiLCJ1c2VybmFtZSI6InphcHUifSwic2VydmljZSI6eyJuYW1lIjoiZ2l0aHViIiwidXNlcm5hbWUiOiJ6YXB1In0sInR5cGUiOiJ3ZWJfc2VydmljZV9iaW5kaW5nIiwidmVyc2lvbiI6MX0sImNsaWVudCI6eyJuYW1lIjoia2V5YmFzZS5pbyBnbyBjbGllbnQiLCJ2ZXJzaW9uIjoiMS4wLjE4In0sImN0aW1lIjoxNDg3MTk1MzI0LCJleHBpcmVfaW4iOjUwNDU3NjAwMCwibWVya2xlX3Jvb3QiOnsiY3RpbWUiOjE0ODcxOTUzMTksImhhc2giOiI2ZDUwZjFhMDQ4NWMwMTA3NzhlMjMwZjE5MDIyMTJmOTk2ZjVjOWE1NDVkMGI1NDM2OWYzMzI4OWYyNjJjMzgxMzBiZTY4OWQzZDZhYjVhZDNiYjk2NjFlOTU1NjYzN2Y2YzA3YTczYTRmMTVhY2E0YzBiZDY0YWNhZmMyMzMyZiIsInNlcW5vIjo4OTQwMzh9LCJwcmV2IjoiMTA1Yjc3NGY1ZjljZDQ5YjExYzU2MjE4N2VmNjc2NGQ0ZDE1NDY2Y2Y1NjNhMDM4NmEzYWJiYjU4MmU3OTQ3ZSIsInNlcW5vIjoyMCwidGFnIjoic2lnbmF0dXJlIn2jc2lnxEDPVZ1uv1yZcRTsMYEIUgqJAMoEtVk3UJcnjEE0Vy3/vCMqDNQd4B6huDcjU7pJS+arutTxAErqE76ceR5JglEJqHNpZ190eXBlIKRoYXNogqR0eXBlCKV2YWx1ZcQgkARip0wQnqR4KmwKFQBwjasBq3BiUTDJ5omsKcZPRx6jdGFnzQICp3ZlcnNpb24B"
                },
                "breaksTracking": false
            }
        },
        {
            "proof": {
                "proofType": 1000,
                "key": "https",
                "value": "zapu.keybase.pub",
                "displayMarkup": "zapu.keybase.pub",
                "sigID": "9b4b75cebfa7977e21ef4ba39f66d4bd1eeeca85bebf2647b1b49e0f91e95d590f",
                "mTime": 1488409819000
            },
            "result": {
                "proofId": 1,
                "proofResult": {
                    "state": 1,
                    "status": 1,
                    "desc": ""
                },
                "snoozedResult": {
                    "state": 1,
                    "status": 1,
                    "desc": ""
                },
                "torWarning": false,
                "tmpTrackExpireTime": 0,
                "hint": {
                    "remoteId": "https://zapu.keybase.pub/keybase.txt",
                    "humanUrl": "https://zapu.keybase.pub/keybase.txt",
                    "apiUrl": "https://zapu.keybase.pub/keybase.txt",
                    "checkText": "hKRib2R5hqhkZXRhY2hlZMOpaGFzaF90eXBlCqNrZXnEIwEgrMqgvitII13oPQQx8yelDcYz5riMbWyP20ZVoKjju3wKp3BheWxvYWTFAvV7ImJvZHkiOnsia2V5Ijp7ImVsZGVzdF9raWQiOiIwMTIwYWNjYWEwYmUyYjQ4MjM1ZGU4M2QwNDMxZjMyN2E1MGRjNjMzZTZiODhjNmQ2YzhmZGI0NjU1YTBhOGUzYmI3YzBhIiwiaG9zdCI6ImtleWJhc2UuaW8iLCJraWQiOiIwMTIwYWNjYWEwYmUyYjQ4MjM1ZGU4M2QwNDMxZjMyN2E1MGRjNjMzZTZiODhjNmQ2YzhmZGI0NjU1YTBhOGUzYmI3YzBhIiwidWlkIjoiZWU3MWRiYzhlNGUzZTY3MWUyOWE5NGNhZWY1ZTFiMTkiLCJ1c2VybmFtZSI6InphcHUifSwic2VydmljZSI6eyJob3N0bmFtZSI6InphcHUua2V5YmFzZS5wdWIiLCJwcm90b2NvbCI6Imh0dHBzOiJ9LCJ0eXBlIjoid2ViX3NlcnZpY2VfYmluZGluZyIsInZlcnNpb24iOjF9LCJjbGllbnQiOnsibmFtZSI6ImtleWJhc2UuaW8gZ28gY2xpZW50IiwidmVyc2lvbiI6IjEuMC4xOCJ9LCJjdGltZSI6MTQ4ODQwOTgxOSwiZXhwaXJlX2luIjo1MDQ1NzYwMDAsIm1lcmtsZV9yb290Ijp7ImN0aW1lIjoxNDg4NDA5NzQ2LCJoYXNoIjoiMGZjMmY4YmE0YmNmMGY0NDkwNGRjMmYxMTY4ZjZkYTIzYmZjYjg3ZjA3YjFjMDllYzUwMDNhZmQ0MjFlYjFiNTJhN2M3YmY5MWQ5ZWUxYmIxOTE2OGI2ZWU4MjBiODE1NTYyODM2OWZiZDJhNTQ0NWM4ZmNjMWRlODY1NWMyM2EiLCJzZXFubyI6OTMzMjYzfSwicHJldiI6IjcwNGVkMjJiMDRiZjU5ZjI0MTllNzJiNWVhM2Y0ZjcwZDk1OGNjZWYwYmFlZDYxMzJkY2ZiYWNmMWIwZjg5MDMiLCJzZXFubyI6MjcsInRhZyI6InNpZ25hdHVyZSJ9o3NpZ8RAHVgYTDfD35hz6JpjnUH/344CqvrvhZovLV7yT2PbTMe+DKsy6s/mM9PRcNxoxDvoOP7A2pcjc1UmuNmZV6egAKhzaWdfdHlwZSCkaGFzaIKkdHlwZQildmFsdWXEINjiTCeIFBTomvCTzEDhGRdE3JglH+BOOu6eWNIlgGgEo3RhZ80CAqd2ZXJzaW9uAQ=="
                },
                "breaksTracking": false
            }
        }
    ]
}
```

**Comment by pzduniak** [comment]
Which makes me think... maybe we should do some versioning here too? Just like we have a chat / wallet API, there should be a versioned "core" API, which we can version using flags / whatever we're doing now with these other APIs. If we don't do versioning then we might be stuck with old JSON outputs while the CLI UIs change and if we don't group them up together, we'll end up duplicating so much code / complicating the CLI to handle versioning.

**Comment by pzduniak** [comment]
Not necessarily related to the `keybase id` command but IMO rather than adding a --json command to list-requests, we should have it added to `keybase team api`.

**Comment by zapu** [comment]
it's fine to just have it in the command right now. it's much faster to extend the command rather than the api.

**Pull request merged**
