### PR TITLE
iOS share: go straight into chat for URL; allow back from target picker

### PR DESCRIPTION
**Pull request by songgao**

### CODE REVIEW

**Comment by mmaxim** [comment]
We should just do this for any share attempt, I have never shared anything into KBFS in the entire time I have used the app.

**Comment by songgao** [comment]
> We should just do this for any share attempt, I have never shared anything into KBFS in the entire time I have used the app.

I'd prefer keep it possible to share into KBFS. Otherwise it's hard to get multiple things into it easily. Perhaps we can add a button here in the chat convo pick screen, so we can just go straight to chat but still allow user to choose KBFS?

image

Another issue is this would eliminate the preview step, which design already has a mock up for: https://zpl.io/ad0zNpE

cc @cecileboucheron

**Comment by chrisnojima** [comment]
Please do not make sharing chat only

**Comment by mmaxim** [comment]
I didn't say make it chat only, but just make it the default path through instead of adding this other tap which is likely 90% of the time for chat.

**Comment by songgao** [comment]
@chrisnojima @mmaxim let's get this one in for now? I made a ticket for the next step https://keybase.atlassian.net/browse/HOTPOT-2513

**Pull request merged**
