### PR TITLE
Fix up chat icon spacing on native

### PR DESCRIPTION
**Pull request by buoyad**
Also transition `Usernames` to play nice with our style utils. r? @keybase/react-hackers cc @cecileboucheron 

screen shot 2018-05-15 at 11 20 17 am

### CODE REVIEW

**Comment by buoyad** [comment]
@keybase/react-hackers bump! lower flow coverage seems to be because of `styleSheetCreate` being untyped.

**Comment by chrisnojima** [comment]
i ticketed making that typing better, should be pretty easy actually

**Comment by buoyad** [comment]
@keybase/react-hackers bump

**Comment by buoyad** [comment]
@chrisnojima just added centering the typing indicator
before:
image
after:
image

**Pull request merged**
