### PR TITLE
Show public folders in logged out menubar

### PR DESCRIPTION
**Pull request by gabriel**
@keybase/react-hackers 
@cecileboucheron 

- Enables public folder thingy if logged out
- Make background white and icon red

2016-03-18 at 2 31 pm

Logged in view is unchanged

### CODE REVIEW

**Comment by cecileboucheron** [comment]
Looking good, just one thing bothering me: the placeholder in the input should be light grey, not black. It used to be good but it got messed up somehow... Also the 'new private' input field has the same issue.

**Comment by cjb** [comment]
@cecileboucheron For what it's worth, it's black because this is still a dz1 widget, and (as far as I remember) it was always black on dz1.  I was gonna leave it at dz1 until we have a dz2 widget for this screen, but we can change it.

**Comment by gabriel** [comment]
https://github.com/keybase/client/pull/2412

**Comment by cecileboucheron** [comment]
@cjb Hmm, I'm 99.9% sure it was grey some time, a few weeks ago...

**Comment by cjb** [comment]
Ah, okay, I believe you.  Last time I was touching it it was already black, so perhaps that's after it changed from grey.

**Pull request merged**
