### PR TITLE
add log tag for GetOrCreateLatestTeamEK

### PR DESCRIPTION
**Pull request by joshblum**
cc @keybase/hotpotatosquad

### CODE REVIEW

**Comment by mmaxim** [comment]
Hmm I don't know about this change, what inspired it? How does it affect the CLI?

**Comment by joshblum** [comment]
ah yeah not good for the CLI. @buoyad was getting some blackbars on logout, i think there were some chat calls in progress when logout was triggered and the errors bubbled up

**Comment by mmaxim** [comment]
That shouldn't happen if that RPC canceller stuff is working right. It's supposed to cancel any live RPCs on logout for chat.

**Comment by joshblum** [comment]
i think there is a race between the active device being cleared and the RPC cancelling. Iwonder why `ActiveDevice.Clear()` doesn't happen as one of the last steps https://github.com/keybase/client/blob/master/go/libkb/globals.go#L329

**Comment by mmaxim** [comment]
Ok if that is true, I think that is what we need to fix rather than swallowing these. I intended that squash function for stuff that is just clearly not a problem, like `context.Canceled` and company.

**Comment by joshblum** [comment]
yeah agreed, have a ticket to look into the race more closely

**Pull request merged**
