### PR TITLE
Fix up edit channel name/desc

### PR DESCRIPTION
**Pull request by cjb**
@keybase/react-hackers CC @akalin-keybase 

Commit da00b48248bb introduced a new algorithm for finding the channel name and description for a conversationID, described in a comment inside the commit.  The motivation is to allow the edit-channel component to be used from two different places: the info pane (channel is in inbox) and the manage channels page of a team (channel isn't in inbox, but is in teams store).  Here's the comment:

```js
  // If we're being loaded from the manage channels page, then
  // getChannelInfoFromConvID should return a non-null ChannelInfo
  // object. Otherwise, we're being loaded from the info pane of a
  // channel we belong to, so fetch the meta from the chat store
  // instead.
  const channelInfo =
    Constants.getChannelInfoFromConvID(state, teamname, conversationIDKey) ||
    getMeta(state, conversationIDKey)
```
This doesn't quite work, for two reasons.

1) If you have a channel that's only in your inbox, and you edit it through the info pane, the act of editing it writes a non-null ChannelInfo object into the teams store.  So if you go back to the edit channel dialog again from the info pane, we'll now use the teams store version.  But that ChannelInfo object is incomplete: if you change the name but not the description, then we don't record the description there at all.

2) If the teams store object exists in that case, it'll be an `I.Map()`, and you need to convert to an object or `channelInfo.description` (as opposed to `channelInfo.get('description')` will return undefined and the dialog will show up empty, which is what's happening on master.  It looks like it's usually an `I.Record()` in the case where you didn't just write it, so perhaps the use of `I.Map()` there is a bug?

So, this algorithm doesn't work.  How about if we reverse it -- prefer the inbox if it exists, then fall back to the teams store?

That *almost* works.  If the inbox row exists but is not yet unboxed, then the `description` will be blank -- we don't know what it is until we've unboxed.  Seems like we actually want "prefer the inbox if it exists and is unboxed, else fall back to the teams store", and that seems to cover every case.  That's what this PR does.

### CODE REVIEW

**Comment by chrisnojima** [comment]
I think we should just call the find rpc like my new conversation pr and not do this local hunting

**Comment by akalin-keybase** [comment]
Thinking about it, I think this PR doesn't quite cover every case. If we do "prefer the inbox if it exists and is unboxed, else fall back to the teams store", it's possible that the convo exists but is still boxed, and the teams store doesn't have the info. So we'd have to call `loadChannels` then anyway.

**Comment by mmaxim** [comment]
+1 in using FindConversations, should make this all much easier

**Comment by akalin-keybase** [comment]
@mmaxim I'm a bit confused...the `FindConversationsLocal` function in `server.go` doesn't seem to take a ConversationID, which is what I really want. There's a `FindConversationsByID` function in `helper.go`, but it's not exposed over an RPC. Can we expose that? Am I missing something?

**Comment by mmaxim** [comment]
Here is what you should be using in the different circumstances:

1.) if you have a conversation ID, you should run getInboxNonblock. There are a bunch of actions now in JS that will kick this off. There is also an RPC called GetInboxAndUnbox which does what GetInboxNonblock does, but without the two phased callbacks.
2.) if you have a team name and/or  channel name (that is you don’t have a conversation ID), you should call FindConversations to get the conversation ID. If this RPC’s interface is too annoying, I can make it simpler.

**Comment by akalin-keybase** [comment]
Unfortunately, it doesn't look like the info that `GetInboxAndUnbox` returns contains the channel description. It contains only the channel name (which I know already) and the channel participants, unless I'm missing something in `ConversationInfoLocal`. Am I missing something?

**Comment by mmaxim** [comment]
It's in there, but it's hard to get (you need to find a `HEADLINE` message in `maxMessages` in that structure). You can either do that, or I can change that RPC to give you back an `InboxUIItem` like `GetInboxNonblock` does. I guess `unboxRows` on the JS side is hard to just call randomly so I guess this is the best option.

**Comment by mmaxim** [comment]
https://github.com/keybase/client/pull/11942 adds a new RPC you can call `GetInboxAndUnboxUI` which will give you back `InboxUIItem`'s

**Comment by akalin-keybase** [comment]
thanks!

**Comment by akalin-keybase** [comment]
I think this is fixed in another PR

**Pull request closed without merging**
