### PR TITLE
Kill DZ1 again

### PR DESCRIPTION
**Pull request by cjb**
@keybase/react-hackers 

- [x] Update components to always call render2(), remove all render1()
- [x] Update common adapters to no longer take a dz2 prop, always render dz2 version
- [x] Remove Noto Sans
- [x] In general, rename e.g. 'styles2' to just 'styles'.
- [x] Kill current on{Re,Un}follow actions, rename on{Re,Un}follow2 to be the new on{Re,Un}follow.
- [x] Move globalStyles.DZ2.font to just be globalStyles.font
- [x] Move globalColorsDZ2 to just be globalColors
- [x] Remove the DZ1 style sections from the style sheet page
- [x] Check styling of menubar widget (was DZ1)

### CODE REVIEW

**Comment by chrisnojima** [comment]
logged out menu looks wonky:

screen shot 2016-03-08 at 1 27 57 pm

**Comment by cjb** [comment]
@chrisnojima thanks, fixed with 9ee35da:

screenshot from 2016-03-08 14-02-58

**Comment by chrisnojima** [comment]
would it hard to get the icons to be the old grey vs this dark black in the shots above, then :+1:

**Comment by chrisnojima** [comment]
screen shot 2016-03-08 at 4 14 11 pm

**Pull request merged**
