### PR TITLE
fix broken send dialog in save lastXLM

### PR DESCRIPTION
**Pull request by zanderz**
will figure it out later

### CODE REVIEW

**Comment by cjb** [comment]
It's okay with me to add the LastSentXLM payload to the SentPayment action, and then just fire SentPayment.  That seems like a short change that keeps everything working.

**Comment by zanderz** [comment]
Thanks @cjb , missed that comment. I see what you're saying but one possible issue now is if there is a send error. Still an improvement until we do something bigger, like Nojima suggests.

**Comment by cjb** [comment]
@zanderz That seems okay -- if the feature is to remember that you last sent XLM, and there was a send error, then you didn't actually last send XLM. :)

**Comment by zanderz** [comment]
Doesn't there have to be an action in order for the actual writing to take place, in actions/config/index.js? Or would that one just listen for sentPayment?

**Pull request merged**
