### PR TITLE
Add comments about versioned records

### PR DESCRIPTION
**Pull request by patrickxb**
As discussed in slack yesterday.

r? @mmaxim

### CODE REVIEW

**Comment by keybase-ci-visdiff** [comment]
:mag_right: The commits f4a2cfc30f90...e90ceb92c002 introduced some visual changes on linux:
 * Changed: **unlock_folders-Success** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1474475508694-f4a2cfc30f90-e90ceb92c002-linux/unlock_folders-Success-f4a2cfc30f90.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1474475508694-f4a2cfc30f90-e90ceb92c002-linux/unlock_folders-Success-e90ceb92c002.png)  
   unlock_folders-Success comparison
 * Changed: **unlock_folders-No_paperkeys** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1474475508694-f4a2cfc30f90-e90ceb92c002-linux/unlock_folders-No_paperkeys-f4a2cfc30f90.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1474475508694-f4a2cfc30f90-e90ceb92c002-linux/unlock_folders-No_paperkeys-e90ceb92c002.png)  
   unlock_folders-No_paperkeys comparison

**Comment by gabriel** [comment]
What are avdl variants?

**Comment by patrickxb** [comment]
https://github.com/keybase/node-avdl-compiler/pull/4

**Comment by patrickxb** [comment]
This might be more helpful:

https://keybase.atlassian.net/browse/CORE-3661

**Pull request merged**
