### PR TITLE
styling paperkey

### PR DESCRIPTION
**Pull request by chrisnojima**
@keybase/react-hackers 

screen shot 2016-03-14 at 6 00 34 pm

### CODE REVIEW

**Comment by chrisnojima** [comment]
@keybase/react-hackers bump

**Comment by cjb** [comment]
Looks like wrong font for the terminal selection and left-aligned instead of center-aligned body text.

:thumbsup:%C

**Comment by chrisnojima** [comment]
yeah, too rushed. now thats fixed and you can copy / paste the key, and also the pieces of the tracker cecile wanted. @cjb wanna look again since there's new func.

**Comment by cjb** [comment]
:thumbsup:

**Pull request merged**
