### PR TITLE
Restore hamburger menu on menubar

### PR DESCRIPTION
**Pull request by buoyad**
r? @keybase/react-hackers

### CODE REVIEW

**Comment by zanderz** [comment]
Could stand some more tweaking but the hamburger is back, definite improvement. LGTM
screen shot 2017-11-13 at 10 38 39 am

**Comment by chrisnojima** [comment]
We can do a better fix than this. Don't merge

**Comment by buoyad** [comment]
@chrisnojima I could redo with flexbox?

**Comment by chrisnojima** [comment]
either do that or just if (small) whatevr changes you need
the badges should be by the titles. the underlines don't need to be this big etc
it looks totally broken

**Comment by buoyad** [comment]
Oh I changed the badges in a563702, here's how it looks now:


and in the client:
image

**Comment by chrisnojima** [comment]
k looks better thanks!

**Pull request merged**
