### PR TITLE
Fix test: TestImplicitTeamUserReset

### PR DESCRIPTION
**Pull request by mlsteele**
1. Can no longer use `MemberRole` with implicit teams
2. Gregor goroutines were panicking. Fixed by having them shutdown

### CODE REVIEW

**Comment by mlsteele** [comment]
Oh. Does `func Reset` bring it back to life?

**Comment by mmaxim** [comment]
It does not, I'm curious what the panic looks like.

**Comment by mlsteele** [comment]
```
+ go test -v -run '^TestImplicitTeamUserReset$'
+ tee /tmp/test.log
=== RUN   TestImplicitTeamUserReset
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x449152a]

goroutine 501 [running]:
github.com/keybase/client/go/protocol/gregor1.IncomingClient.ConsumeMessage(0x0, 0x0, 0x5b7bca0, 0xc42001c148, 0x0, 0xc423b7b460, 0xc423b7b401, 0xc423c2a600)
        /Users/miles/go/src/github.com/keybase/client/go/protocol/gregor1/incoming.go:414 +0xca
github.com/keybase/client/go/protocol/gregor1.(*IncomingClient).ConsumeMessage(0xc423c181e0, 0x5b7bca0, 0xc42001c148, 0x0, 0xc423b7b460, 0xc423c203c0, 0x3b)
        <autogenerated>:1 +0x71
github.com/keybase/client/go/service.(*gregorHandler).DismissItem(0xc422620a00, 0x5b861a0, 0xc423c181e0, 0x5b77c20, 0xc423c2a520, 0x0, 0x0)
        /Users/miles/go/src/github.com/keybase/client/go/service/gregor.go:1496 +0x36d
github.com/keybase/client/go/service.(*teamHandler).exitTeam(0xc420412840, 0x5b7bca0, 0xc42001c140, 0x5b861a0, 0xc423c181e0, 0x5b81280, 0xc423b7ae20, 0xc4223fd290, 0x24)
        /Users/miles/go/src/github.com/keybase/client/go/service/team_handler.go:111 +0x49e
github.com/keybase/client/go/service.(*teamHandler).Create(0xc420412840, 0x5b7bca0, 0xc42001c140, 0x5b861a0, 0xc423c181e0, 0xc420133210, 0x9, 0x5b81280, 0xc423b7ae20, 0xc422f14380, ...)
        /Users/miles/go/src/github.com/keybase/client/go/service/team_handler.go:48 +0x1b3
github.com/keybase/client/go/service.(*gregorHandler).handleInBandMessageWithHandler(0xc422620a00, 0x5b7bca0, 0xc42001c140, 0x5b861a0, 0xc423c181e0, 0x5b7d0a0, 0xc423c180b0, 0x5b7c3a0, 0xc420412840, 0x1, ...)
        /Users/miles/go/src/github.com/keybase/client/go/service/gregor.go:923 +0xb5a
github.com/keybase/client/go/service.(*gregorHandler).handleInBandMessage(0xc422620a00, 0x5b7bca0, 0xc42001c140, 0x5b861a0, 0xc423c181e0, 0x5b7d0a0, 0xc423c180b0, 0x2, 0x0)
        /Users/miles/go/src/github.com/keybase/client/go/service/gregor.go:866 +0x43e
github.com/keybase/client/go/service.(*gregorHandler).broadcastMessageOnce(0xc422620a00, 0x5b7bca0, 0xc42001c140, 0x0, 0xc423642150, 0x0, 0x0)
        /Users/miles/go/src/github.com/keybase/client/go/service/gregor.go:802 +0x769
github.com/keybase/client/go/service.(*gregorHandler).broadcastMessageHandler(0xc422620a00)
        /Users/miles/go/src/github.com/keybase/client/go/service/gregor.go:834 +0xa0
created by github.com/keybase/client/go/service.(*gregorHandler).Init
        /Users/miles/go/src/github.com/keybase/client/go/service/gregor.go:217 +0x60
exit status 2
FAIL    github.com/keybase/client/go/systests   3.080s
```

When `team.exit` tries to `DismissItem`. Because the `cli` is nil. My theory is its a stale gregorHandler instance, because this test resets the device, whatever that means.
https://github.com/keybase/client/blob/master/go/service/team_handler.go#L111
`g.cli` is nil here: https://github.com/keybase/client/blob/master/go/service/gregor.go#L802
So it fails here not because `cli` is nil but because the thing inside it (hidden in interface) is nil: https://github.com/keybase/client/blob/master/go/service/gregor.go#L1496

**Comment by mmaxim** [comment]
Seems like the test needs to logout or otherwise kill the Gregor connection of the device on the reset account.

**Comment by mmaxim** [comment]
My strong preference is not change anything about `gregorHandler` for this test, with the possible exception of that ibm handler.

**Comment by mlsteele** [comment]
How about this little bit of sweeping the problem under the rug?

**Comment by mmaxim** [comment]
I just pushed a change to this branch that I think is a little better. I have a plan to clean this up, but I think I'd prefer this over having the `nil` checks spread out too much.

**Comment by mlsteele** [comment]
This just failed with a bad previous hash message. I think it's hitting this race https://keybase.atlassian.net/browse/CORE-6366
But I don't know why two parties would try to write team links at the same time in this test. Maybe the old gregors are still alive. I vote merging it despite being flaky and that race should get fixed soon

**Pull request merged**
