### PR TITLE
include the port with stringing an fmpURI

### PR DESCRIPTION
**Pull request by oconnor663**
Tiny review for @patrickxb, just to make sure we don't rely on leaving out the port anywhere.

### CODE REVIEW

**Comment by patrickxb** [comment]
LGTM (is anything relying on String() to connect or this is just to make sure it's never left out?)

**Comment by maxtaco** [comment]
This code has been moved into the msgpack library. We should make this change in the library and nix this code in favor of the code in the library!

**Comment by oconnor663** [comment]
Ah ok, I'll see if I can do that real quick.

**Comment by oconnor663** [comment]
Eh, there are a lot of build breaks when I revendor go-framed-msgpack-rpc. I think @akalin was working on this. I've pushed my one line fix upstream, but I'm going to punt on the vendoring for now.

**Comment by akalin-keybase** [comment]
Yeap, leave the vendoring to me.

**Pull request closed without merging**
