### PR TITLE
New Saga Utils: Part 11 (tracker, teambuilding, fs, unlock, users)

### PR DESCRIPTION
**Pull request by chrisnojima**

### CODE REVIEW

**Comment by chrisnojima** [comment]
@keybase/react-hackers this is ready
cc: @jzila @songgao for the new saga api (see confluence)

**Comment by zanderz** [comment]
Clicking on "private" in the files tab doesn't do anything in this branch.
Also, made a team from the chat tab and got a red bar on that dialog saying something about signature at position 1 (LMK if u want a log)

**Comment by chrisnojima** [comment]
@zanderz i fixed the routing things. the old code was like
```
Saga.all([
thing that returns], routeactions])
```

these can happen in parallel so i just do routeactions first, then the other stuff. actually makes fs after.

the red dialog is actually happening on master. 'sigchain link cannot be added at seqno: 1' right?

**Comment by chrisnojima** [comment]
This is ready for re review

**Comment by songgao** [comment]
Thanks for the heads up!

**Pull request merged**
