### PR TITLE
CLI: make self-encryption optional

### PR DESCRIPTION
**Pull request by maxtaco**
- plumb options through to engine
- tested successfully via the command line
- test in engine/

### CODE REVIEW

**Comment by maxtaco** [comment]
@akalin-keybase, this is a small follow-in to the previous PR, to plumb through (and test) no-self-mode

**Comment by akalin-keybase** [comment]
This looks mostly OK, but I take another look after you rebase? Looks like some other changes were picked up

**Comment by maxtaco** [comment]
I tried to rebase and force push but I guess I failed.  I will try again when I get home tonight.  It is just the last commit that matters.

**Comment by maxtaco** [comment]
Oh I see. The PR failed to update but the branch did.  I will make a new PR when I get to a computer.

**Comment by maxtaco** [comment]
ok, made a new PR, it was some bug in GitHub

**Pull request closed without merging**
