### PR TITLE
Add ForkType.LAUNCHD

### PR DESCRIPTION
**Pull request by zanderz**
Forgot this review comment from https://github.com/keybase/client/pull/1349

### CODE REVIEW

**Comment by maxtaco** [comment]
Great. We also need to plumb through --fork-launchd-mode or whatnot so that we can specify the flag when we launch the service

**Comment by zanderz** [comment]
So shall I merge this @maxtaco ?

**Comment by maxtaco** [comment]
Also need a fix in `ctl_restart` to let launchd do the restarting (as in watchdog-mode).

**Comment by zanderz** [comment]
OK I think that will do it

**Comment by maxtaco** [comment]
:+1:

**Pull request merged**
