### PR TITLE
Fix up attachments to work with local server

### PR DESCRIPTION
**Pull request by buoyad**
- [x] add loading state to share, which can take a while to download the file
  - very simple, could be improved for accuracy

### CODE REVIEW

**Comment by mmaxim** [comment]
@buoyad Heads up I rebased this against my branch again to pull something in.

**Comment by mmaxim** [comment]
Put in a few commits on this branch to fixup the upload flow.

**Comment by buoyad** [comment]
I put in a very simple loading indicator to the attachment preview when sharing (hooks into download progress flags). It could be improved by a lot, but I'd prefer to merge these in and work on that afterwards, since it's a bit of a refactor. r? @keybase/react-hackers

**Comment by mmaxim** [comment]
I’ve been running this for the last 48 hours ( not including the latest Danny commit) and it works very well. Should try to get it merged.

**Comment by buoyad** [comment]
@chrisnojima what do you think?

**Comment by chrisnojima** [comment]
sure, merge it

**Pull request merged**
