### PR TITLE
Make flow fail on warnings in jenkins_test.sh

### PR DESCRIPTION
**Pull request by akalin-keybase**
...as a workaround for https://github.com/facebook/flow/issues/5009 .

### CODE REVIEW

**Comment by akalin-keybase** [comment]
r? @keybase/react-hackers 

This should pass once https://github.com/keybase/client/pull/10038 is merged.

**Comment by chrisnojima** [comment]
Not clear to me we want this change. I think errors vs warnings is a useful thing. It's ok for us to have warnings. Is there a warning that we know of right now we want to treat as an error?

**Comment by akalin-keybase** [comment]
Yes, the unused flow suppression warning that #10038 fixes.

**Comment by akalin-keybase** [comment]
Also, we've gone this far without any flow warnings, seems like a shame to relax it now, until we run into a case where we want to keep a warning.

**Comment by chrisnojima** [comment]
With the lint aspect there are a bunch of things which flow can treat as warnings that we currently suppress. We can keep your pr but we might want to turn the lint warnings on and I don't really find the extra flow suppression's to be an error level event (we don't in eslint for example)

**Comment by akalin-keybase** [comment]
If we turn any one of the lint warnings on, we can treat them as errors and suppress them on a per-line basis. (This is what we want to do with these $FlowIssue warnings, except instead of suppressing them we delete the $FlowIssue comments.)

My objections to printing warnings and not treating them as errors is the usual one: they'll just clutter up the console/IDE output and create warning fatigue, i.e. make it easy to overlook warnings that signify a real problem. I have the same objection to how we treat eslint: we should either turn the sort keys warning off, or just bite the bullet and fix them, and treat them as errors from now on.

**Comment by chrisnojima** [comment]
I think this largely depends on the tool and the warnings. Many of the flow lint warnings are very sensitive and aren't something we would want to turn on and try to fix globally. Like I said I'm fine to move forward with this but I imagine a world where we might roll this back.

**Comment by akalin-keybase** [comment]
Forgot to revert dummy change for CI, will fix on master

**Pull request merged**
