### PR TITLE
Remove unused files.

### PR DESCRIPTION
**Pull request by adamjspooner**
It doesn't look like these are used. @chrisnojima? @patrickxb?

### CODE REVIEW

**Comment by chrisnojima** [comment]
We shouldn't just delete these files. We should update the protocol script to do this on every run

**Comment by patrickxb** [comment]
Why?  They don't get generated here anymore.

**Comment by chrisnojima** [comment]
Ok I wasn't sure if they were still part of the process. We don't use any
json files from this flow

**Comment by patrickxb** [comment]
Should we remove all the json files then?

**Comment by adamjspooner** [comment]
@chrisnojima, so, it's safe to remove these?

**Comment by adamjspooner** [comment]
These files aren't recreated after `make`ing. `protocol/bin/flow.js` uses the JSON files under `protocol/json/<thing>1/`, not the JSON files in `protocol/json/`.

**Comment by patrickxb** [comment]
Trash them!

**Comment by adamjspooner** [comment]
@chrisnojima, this is ready for another review.

**Pull request merged**
