### PR TITLE
better home/people cache split on home

### PR DESCRIPTION
**Pull request by maxtaco**
- back out previous PR
- use two caches
- cleaner logic even relative to first attempt

### CODE REVIEW

**Comment by maxtaco** [comment]
cc: @buoyad

**Comment by maxtaco** [comment]
OK, tested by hand, it does the right thing.

**Comment by buoyad** [comment]
Testing this; the nav badging for the follow row is consistent, but the follow suggestions refresh on each load now

**Comment by patrickxb** [comment]
Why does `MarkViewed` have to bust the home cache?  

There's also a path in `Get` where `markViewed` is true so the mark call has already happened, then the UI calls `MarkViewed` as well, which makes the call again, and then busts the cache.

It seems like that cache is going to be constantly busted...resulting in API calls every time you go to the people tab.  If that's the case, then is there any point in the home cache?

**Comment by maxtaco** [comment]
@patrickxb this was the cause of the bug that @buoyad saw yesterday.  `MarkViewed` is called, and the home page is reloaded, but the row is still badged.   We need to refresh home with the server the next time it's viewed.  I'm not worried about the extra load.

**Comment by maxtaco** [comment]
there probably isn't much use for the cache, as you say....

**Comment by maxtaco** [comment]
I guess the point of the cache is to be robust against electron bugs that spam the service with `homeGetScreen` RPC calls.  If there are no bugs, it's likely not an issue. But this way @buoyad can feel ok to issue as many `homeGetScreen` RPC calls as he needs.

The alternative solution is to have the service code look into the AVDL and unbadge, potentially, certain rows.  I worry this is error prone and moves badging logic back into the packaged client. It's nice instead to control as much as this stuff on the server-side, so we can fix bugs without waiting for the release cycle.

**Comment by maxtaco** [comment]
OK, you guys have convinced me, I'll fix...

**Comment by maxtaco** [comment]
ok @patrickxb  PTAL

**Comment by buoyad** [comment]
it all looks good now, the suggestions don't refresh for 10 minutes and I get new rows if I call `getHomeScreen` after calling `markViewed` with a badged row

**Comment by maxtaco** [comment]
Yeah, i think this fix is the best of both worlds. A call to `MarkViewed` forces a refresh only if the currently cached state has badged people rows.

**Pull request merged**
