### PR TITLE
Nojima/desktop go gc mem pressure

### PR DESCRIPTION
**Pull request by chrisnojima**
@keybase/react-hackers @patrickxb  @mmaxim

### CODE REVIEW

**Comment by chrisnojima** [comment]
If there's other things we should call we should put them in

**Comment by patrickxb** [comment]
Let me add a commit

**Comment by patrickxb** [comment]
This will need some testing, but I think that should be safe...

**Comment by chrisnojima** [comment]
- [ ] add android onLowMemory

**Comment by patrickxb** [comment]
Should we try this out?

**Comment by chrisnojima** [comment]
Lemme just sanity check it and let me add the call through for android

**Pull request merged**
