### PR TITLE
Avoid some unnecessary init at startup for the version command

### PR DESCRIPTION
**Pull request by zanderz**
@maxtaco @patrickxb

### CODE REVIEW

**Comment by gabriel** [comment]
So you are saying the service checking identifies in the background is slowing the `keybase version -S` call. I actually think it's good for identifies to be triggered immediately. I think a better fix would be to stagger the updater to check every 67 minutes or something prime like cicadas

**Comment by gabriel** [comment]
ok, doing some testing:

Tail the service log, then run:

```
keybase -d version -S
```

The log dumps a bunch of identify stuff. And I don't think it has to do with anything hourly.

I think this is the real issue and we should fix that instead? e.g. I don't think this PR would have any impact.

**Comment by maxtaco** [comment]
Is the claim that these background operations were stopping a foreground operation like getting the version? That would really surprise me!

**Comment by zanderz** [comment]
Huh, I don't get that same result - the service doesn't really do much for me in that case, but it does get a connection from the client running `version -S`, which is also unnecessary. I do get this:
```
C:\Users\Steve\AppData\Local\Keybase>keybase -debug version -S
2016-12-22T15:19:17.522902 - [DEBU keybase globals.go:325] 001 Created Identify2Cache, max age: 5m0s
2016-12-22T15:19:17.523408 - [DEBU keybase globals.go:328] 002 Created LinkCache, max size: 65536, clean dur: 1m0s
2016-12-22T15:19:17.524413 - [DEBU keybase globals.go:330] 003 Created CardCache, max age: 5m0s
2016-12-22T15:19:17.525426 - [DEBU keybase ui.go:561] 004 Can't set GPG_TTY; discover failed
2016-12-22T15:19:17.526413 - [DEBU keybase globals.go:308] 005 Keybase CLI 1.0.18
2016-12-22T15:19:17.527426 - [DEBU keybase globals.go:308] 006 - Built with go1.7
2016-12-22T15:19:17.527916 - [DEBU keybase globals.go:308] 007 - Visit https://keybase.io for more details
2016-12-22T15:19:17.528931 - [DEBU keybase main.go:147] 008 + configureProcesses
2016-12-22T15:19:17.529924 - [DEBU keybase main.go:245] 009 + configureLogging
2016-12-22T15:19:17.530925 - [DEBU keybase main.go:254] 00a Disabling log forwarding
2016-12-22T15:19:17.535943 - [DEBU keybase main.go:247] 00b - configureLogging
2016-12-22T15:19:17.536959 - [DEBU keybase main.go:149] 00c - configureProcesses -> <nil>
1.0.18
2016-12-22T15:19:17.539948 - [DEBU keybase out_of_date.go:14] 00d + PrintOutOfDateWarnings
2016-12-22T15:19:17.540463 - [DEBU keybase util.go:391] 00e + GetSocket
2016-12-22T15:19:17.541452 - [DEBU keybase util.go:392] 00f - GetSocket -> ok
2016-12-22T15:19:17.542470 - [DEBU keybase socket.go:73] 010 | empty socket wrapper; need a new one
2016-12-22T15:19:17.543458 - [DEBU keybase socket.go:88] 011 | DialSocket -> ok
2016-12-22T15:19:17.547969 - [DEBU keybase out_of_date.go:28] 012 Got OutOfDateInfo: keybase1.OutOfDateInfo{UpgradeTo:"", UpgradeURI:"", CustomMessage:"", CriticalClockSkew:0}
2016-12-22T15:19:17.548476 - [DEBU keybase out_of_date.go:44] 013 - PrintOutOfDateWarnings
2016-12-22T15:19:17.652306 - [DEBU keybase globals.go:360] 014 Calling shutdown first time through
2016-12-22T15:19:17.652733 - [DEBU keybase login_state.go:1046] 015 + Account "LoginState - Shutdown"
2016-12-22T15:19:17.653737 - [DEBU keybase login_state.go:959] 016 - LoginState: Leaving request loop
2016-12-22T15:19:17.653737 - [DEBU keybase login_state.go:1048] 017 - Account "LoginState - Shutdown"
2016-12-22T15:19:17.656244 - [DEBU keybase globals.go:417] 018 exiting shutdown code=0; err=<nil>
```

none of which really seems necessary at all; maybe we can shortcut all of that in a hardcoded special case for this command?

**Comment by maxtaco** [comment]
@zanderz: Agreed it should be OK to  special case this and just ask the client. 

@gabriel: what you probably noted is that: (1) with background identifying, we're going to be identifying people asynchronously in the background a lot more; and (2) when you run with `-d`, the client gets all of the service's debug dump, not just that debug stream contextually relevant for the client's RPCs.

**Comment by patrickxb** [comment]
I don't see how there would be any delay in getting the version, or how the background jobs could possibly be interfering.  

The GetConfig() handler (that `keybase version` calls) is just reading stuff from G.Env and putting it in a struct and returning.  None of the G.Env calls look like ones that should be blocking on anything.  The only one that might is the gpg canexec.

However, perhaps just adding a flag to client/cmd_version.go that just returns libkb.Version or libkb.VersionString() seems fine to me.

**Comment by gabriel** [comment]
Ah sorry, yeah, I think it was something background identifying and I was getting the log forwarding, it wasn't actually triggering anything... 

I did notice this in logs though, not sure if it's an issue: https://keybase.atlassian.net/browse/CORE-4300

**Comment by gabriel** [comment]
The `keybase version -S` command is making an RPC call to the service to get the "out of date warning", even though, it's -S means --no-service.

We might want to change that.

**Comment by gabriel** [comment]
Maybe we should avoid PrintOutOfDateWarnings if command is nofork? (Instead of special Usage.)

**Pull request closed without merging**
