### PR TITLE
make parent dirs before writing plist

### PR DESCRIPTION
**Pull request by maxtaco**
As mentioned [here](https://github.com/keybase/client/pull/1399#issuecomment-164810645)

### CODE REVIEW

**Comment by maxtaco** [comment]
@gabriel can you review and/or advise me on how best to test it?

**Comment by gabriel** [comment]
Yeah this is the right fix.... This should be very rare but on a completely empty OSX install this dir won't be there oops.

**Comment by maxtaco** [comment]
Cool.  Any thoughts on how to test it?  I haven't run a brew install in a while.

**Comment by maxtaco** [comment]
Actually, we'll hit it in normal DMG installs too

**Comment by gabriel** [comment]
yeah you'd have to remove the LaunchAgents directory but that would cause problems with other apps that have stuff installed there.... the only way to really test would be to install on a completely new OSX install... i'm confident this fix will work though so all good i think

**Pull request merged**
