### PR TITLE
dont use retry arg for team API calls

### PR DESCRIPTION
**Pull request by mmaxim**

### CODE REVIEW

**Comment by maxtaco** [comment]
i don't like

**Comment by maxtaco** [comment]
Can we keep as retry-able but just use a longer `initialTime`?

**Comment by maxtaco** [comment]
Actually I don't know... Hmmm

**Comment by mmaxim** [comment]
You think this should hang out for like 3 minutes if there is a problem?

**Comment by mmaxim** [comment]
Most API calls do not retry

**Comment by maxtaco** [comment]
ok, fine with me

**Pull request merged**
