### PR TITLE
Copy changes

### PR DESCRIPTION
**Pull request by MarcoPolo**
@keybase/react-hackers

### CODE REVIEW

**Comment by chrisnojima** [comment]
👍

**Comment by keybase-ci-visdiff** [comment]
:mag_right: These commits introduced some visual changes:
 * Changed: **Tracker-Nonuser_Link** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1465420726480-bceddb75a629-a0380624f41c/Tracker-Nonuser_Link-bceddb75a629.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1465420726480-bceddb75a629-a0380624f41c/Tracker-Nonuser_Link-a0380624f41c.png)  
   Tracker-Nonuser_Link comparison
 * Changed: **Intro-User_who_just_revoked_device** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1465420726480-bceddb75a629-a0380624f41c/Intro-User_who_just_revoked_device-bceddb75a629.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1465420726480-bceddb75a629-a0380624f41c/Intro-User_who_just_revoked_device-a0380624f41c.png)  
   Intro-User_who_just_revoked_device comparison
 * Changed: **Intro-First_time_user** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1465420726480-bceddb75a629-a0380624f41c/Intro-First_time_user-bceddb75a629.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1465420726480-bceddb75a629-a0380624f41c/Intro-First_time_user-a0380624f41c.png)  
   Intro-First_time_user comparison
 * Changed: **Files-You_can_unlock_Public** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1465420726480-bceddb75a629-a0380624f41c/Files-You_can_unlock_Public-bceddb75a629.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1465420726480-bceddb75a629-a0380624f41c/Files-You_can_unlock_Public-a0380624f41c.png)  
   Files-You_can_unlock_Public comparison
 * Changed: **Files-You_can_unlock_Private** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1465420726480-bceddb75a629-a0380624f41c/Files-You_can_unlock_Private-bceddb75a629.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1465420726480-bceddb75a629-a0380624f41c/Files-You_can_unlock_Private-a0380624f41c.png)  
   Files-You_can_unlock_Private comparison

**Comment by chrisnojima** [comment]
@chromakode why this visdiff?

**Comment by MarcoPolo** [comment]
@chrisnojima expected because I changed the text

**Comment by chrisnojima** [comment]
im' talking about the Files-You_can_unlock_Private stuff, you didn'dt change the dimensions of the dumb sheet

**Comment by chromakode** [comment]
@MarcoPolo @chrisnojima It looks like the text in the headers of those screens got longer, which caused the container to grow. Unless you style explicit dimensions, the visual diff code will determine the screenshot size by measuring the component.

**Comment by chrisnojima** [comment]
Sounds good Tnx

**Pull request merged**
