### PR TITLE
(WIP) Team buttons in chat inbox

### PR DESCRIPTION
**Pull request by cecileboucheron**
@adamjspooner I managed to add them in the empty state, but not to the end of the inbox.

### CODE REVIEW

**Comment by adamjspooner** [comment]
@keybase/react-hackers, this is ready for review.

**Comment by adamjspooner** [comment]
@thebearjew, mind taking another look? 🙏

**Comment by thebearjew** [comment]
@adamjspooner duplicated rows here... not sure why.
image

**Comment by thebearjew** [comment]
@adamjspooner It seem to be coming from the logic when the inbox is empty. To produce this screen I hid all my chats and left all my teams.

image

**Pull request merged**
