### PR TITLE
disable bserver on mobile

### PR DESCRIPTION
**Pull request by songgao**
cc @mmaxim

### CODE REVIEW

**Comment by strib** [comment]
@jzila: we don't fetch those blocks in mobile ("minimal") mode.  They're not needed since they only contain updated node info, and mobile has no nodes.

**Comment by songgao** [comment]
Admittedly I didn't think about the unembedded cases. So I looked around to learn more about it, and found this: https://github.com/keybase/kbfs/blob/ae841e710f644647dec2dafd7b6145d40217f035/libkbfs/init.go#L597 are those just fetches that run freely but not actually used in mobile code paths?

**Comment by songgao** [comment]
> This will break git management on mobile, so please don't merge unless we're ok with that. Creating/deleting repos requires being able to write blocks.

Hmm I thought repo creation/deletion was all core side work? If not, then it doesn't seem worth it to break that just to save a bserver connection on mobile.

**Comment by strib** [comment]
It definitely involves KBFS, to create a subdir and save a repo ID.

But I'm not 100% sure about the git breakage thing.  Each new service->kbfs git call creates a new Config object from scratch, so it might create new bserver connections for each of those calls, regardless of whether the main Config has them or not.  Someone would need to look at it / test it more.

**Comment by songgao** [comment]
Oh I see; I'll try it out in simulator then. Thanks for the explanation.

**Comment by songgao** [comment]
@strib I think your theory is correct: https://keybase.io/_/admin/logdump_viewer?14886141#b153e84317f3d45f323d251c It dialed the real bserver for git. What about the comment I linked above though?

**Comment by strib** [comment]
I already explained about the unembedded blocks, we don't fetch them.  I think that comment wasn't fixed after I made that change.  See https://github.com/keybase/kbfs/blob/ae841e710f644647dec2dafd7b6145d40217f035/libkbfs/md_util.go#L425-L432.

**Comment by songgao** [comment]
I see. I saw your explanation about not fetching them but then saw that contradictory comment which is why I was confused. I should've looked up the ticket.

I'll resolve that TODO as well then.

**Comment by songgao** [comment]
Hmm not sure if this is useful any more at all. Closing!

**Pull request closed without merging**
