### PR TITLE
Tiny tooltip tweaks

### PR DESCRIPTION
**Pull request by chromakode**
:eyeglasses: @keybase/react-hackers

### CODE REVIEW

**Comment by chrisnojima** [comment]
👍

**Comment by keybase-ci-visdiff** [comment]
:mag_right: The commits 33d5ac00a663...f0423b49a9db introduced some visual changes on linux:
 * Changed: **Search-Group_non_user_No_Avatar** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1470689208940-33d5ac00a663-f0423b49a9db-linux/Search-Group_non_user_No_Avatar-33d5ac00a663.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1470689208940-33d5ac00a663-f0423b49a9db-linux/Search-Group_non_user_No_Avatar-f0423b49a9db.png)  
   Search-Group_non_user_No_Avatar comparison
 * Changed: **Search-Group_non_user_Has_Invite** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1470689208940-33d5ac00a663-f0423b49a9db-linux/Search-Group_non_user_Has_Invite-33d5ac00a663.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1470689208940-33d5ac00a663-f0423b49a9db-linux/Search-Group_non_user_Has_Invite-f0423b49a9db.png)  
   Search-Group_non_user_Has_Invite comparison
 * Changed: **Search-Group_non_user** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1470689208940-33d5ac00a663-f0423b49a9db-linux/Search-Group_non_user-33d5ac00a663.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1470689208940-33d5ac00a663-f0423b49a9db-linux/Search-Group_non_user-f0423b49a9db.png)  
   Search-Group_non_user comparison

**Comment by chromakode** [comment]
Didn't expect the visual diff here. Working on a fix.

**Comment by chromakode** [comment]
@chrisnojima Could I please have a re-review? Needed to change my approach here to fix the visdiff above.

**Comment by chrisnojima** [comment]
:+1:

**Pull request merged**
