### PR TITLE
 fix rn 615

### PR DESCRIPTION
**Pull request by chrisnojima**
last pr was missing react native updating, just react , sigh

### CODE REVIEW

**Comment by buoyad** [comment]
Does this need a `pod install`?

**Comment by chrisnojima** [comment]
yeah, one sec

**Comment by chrisnojima** [comment]
actually lemme fix upsome other stuff

**Comment by chrisnojima** [comment]
@jakob223 @songgao @buoyad ok fixed some gradle/pod stuff

**Pull request merged**
