### PR TITLE
Move asset links to expanded view

### PR DESCRIPTION
**Pull request by cecileboucheron**
I moved the links to the expanded view and made them buttons. I kept the Exchange one to the right but I would gladly ditch it if Patrick agrees (I think it clutters the view).

image

It's a bit tight on iPhone SE though. It should be okay on bigger devices.
image

@keybase/react-hackers @patrickxb

### CODE REVIEW

**Comment by patrickxb** [comment]
If we're going to do this, the "Exchange" link under "0 USD" should go away and just have the button in the expanded view.

**Comment by patrickxb** [comment]
Ok, let's do this and remove the exchange link.

**Comment by patrickxb** [comment]
One more question:  now that they are buttons, is it easy to put a spinner on Deposit, Withdraw?  Not needed for Exchange.

**Comment by chrisnojima** [comment]
lets make another pr to fix this up

**Pull request merged**
