### PR TITLE
Fix defer trace calls

### PR DESCRIPTION
**Pull request by patrickxb**
Mainly wanted the UnboxBytes32Any one fixed, but found a few others.

r? @maxtaco

### CODE REVIEW

**Comment by patrickxb** [comment]
(found debugging https://keybase.atlassian.net/browse/KBFS-1101)

**Comment by maxtaco** [comment]
👍

**Comment by keybase-ci-visdiff** [comment]
:mag_right: No visual changes found as a result of these commits.

**Comment by keybase-ci-visdiff** [comment]
:mag_right: No visual changes found as a result of these commits.

**Pull request merged**
