### PR TITLE
Speed up ProofSuggestions

### PR DESCRIPTION
**Pull request by mlsteele**
Bring `ProofSuggestions` from ~600ms to ~200ms on my laptop. On all calls but the first in each run of the service, the bulk of the time is now in `libkb.LoadMe`, as it should be. Time was being spent parsing and loading services many times. Now that only happens after initial load if the merkley hash changes.

### CODE REVIEW

**Comment by mlsteele** [comment]
Not sure this really fixes the bug I saw though cause on my phone it can take 13s

**Comment by mlsteele** [comment]
that'd be cool. Is there a good spot to store the processed artifact

**Comment by joshblum** [comment]
not sure, just remember that was the other caller of this store. we could move into another ticket as well

**Comment by mlsteele** [comment]
skipping CI too many flakes

**Pull request merged**
