### PR TITLE
osx: simple multi-user KBFS support on macOS

### PR DESCRIPTION
**Pull request by strib**
Trying this again, this time with logic to remove a leftover /keybase mount, in case the previous application didn't properly remove it.

### CODE REVIEW

**Comment by strib** [comment]
This is the same as #10337 except for commit 8c430f5.

Can one of you give me a thumb for that commit?

I won't merge it until after we do the next desktop release (Monday?).

**Comment by jzila** [comment]
Maybe I'm missing something in how ObjC works, but shouldn't we fail out if either of the new steps fails?

**Comment by strib** [comment]
> Maybe I'm missing something in how ObjC works, but shouldn't we fail out if either of the new steps fails?

I don't think so.  If these steps fail, we'll just fall down to the portion that tries to create the symlink, which will also fail, resulting in the alert telling the user where their mountpoint is.  So if `/keybase` lingers around as some broken mountpoint, or if someone else has put a non-empty directory there, the user gets informed about where their mount really is and everything works as expected.

Later, if someone cleans up `/keybase` manually, the next user to restart KBFS will capture the symlink.

**Comment by strib** [comment]
Client CI is busted, core is looking into it, and it's unrelated to this PR.  So merging!

**Comment by strib** [comment]
Oops nevermind, I pushed from the wrong device.  Will push again with the latest fixes.

**Pull request merged**
