### PR TITLE
Team building animations

### PR DESCRIPTION
**Pull request by chrisnojima**
New animated team building filter bar
Uses reanimated and adds that plumbing

- [x] initial slide animation

### CODE REVIEW

**Comment by cecileboucheron** [comment]
@chrisnojima Reviewed again: 
* can we add a delay to the init animation? right now, because it starts when the whole screen begins to slide up, we can only see the bounce. 
* The tab icons don't look vertically centered when there's a group being built:
image
* Not sure if this PR introduced it but the tabs are harder to click. Like I need to click them twice to have them respond, the first click hiding the keyboard.

**Comment by chrisnojima** [comment]
@cecileboucheron updated

**Comment by chrisnojima** [comment]
@cecileboucheron can you take a look again

**Comment by cecileboucheron** [comment]
This version seems more laggy, I get stuck for a while in this state and the bar isn't that smooth. 
But if it's just a simulator performance thing, LGTM.

image

**Comment by chrisnojima** [comment]
@cecileboucheron i made a small change that maybe addresses that. i'm going to merge . lets play with it on device

**Pull request merged**
