### PR TITLE
remove the gconf dependency on Arch Linux

### PR DESCRIPTION
**Pull request by oconnor663**
This was suggested in https://aur.archlinux.org/packages/keybase-bin/#comment-723637.
I just tested it on my machine, and the Keybase client starts successfully without gconf.

---

f6bd8dc updates some stale metadata in the .SRCINFO file.
In the usual Arch Linux workflow, this is a generated file. However,
generating it requires the `makepkg` tool, which is difficult to run on
anything other than Arch Linux. To avoid that dependency, we've checked
in this generated file as another template. However, as a predictable
consequence, it's gotten out of sync with the PKGBUILD file it's
supposedly generated from. These changes bring it back into sync.

One alternative to this whole setup, would be to just run a Docker image
for Arch Linux, and to legitimately generate this file. If that would be
convenient in the current build environment, it's worth considering.

### CODE REVIEW

**Comment by eli-schwartz** [comment]
What distros do you currently use in the release toolchain?

**Comment by eli-schwartz** [comment]
gconf was removed from electron here: https://github.com/electron/electron/pull/19498

**Comment by oconnor663** [comment]
[It's been a while since I worked at Keybase, so I'll let someone who's up to speed on the build pipeline chime in.]

**Comment by Hattshire** [comment]
@oconnor663 I think you should also edit https://github.com/keybase/client/blob/8cb97f6c9d64ff1bb94a61739b4bf1424b9d4194/packaging/linux/test/keybase-arch-test/Dockerfile#L6
It would be great if you could make the modifications and run the tests for the ubuntu images (no ubuntu installation needed, [instructions here](https://github.com/keybase/client/blob/8cb97f6c9d64ff1bb94a61739b4bf1424b9d4194/packaging/linux/test/README.md))

**Comment by heronhaye** [comment]
Thanks!

**Comment by oconnor663** [comment]
I'll defer to folks who use the other distros to make those changes. I'm not very confident that I'd test things properly.

**Comment by oconnor663** [comment]
I've updated the keybase-git AUR package with the same change.

**Pull request merged**
