### PR TITLE
attach-to-chat 1: components and stories

### PR DESCRIPTION
**Pull request by songgao**
Some storybook screenshots:

image

image

image

### CODE REVIEW

**Comment by jzila** [comment]
@songgao wouldn't it be better if this acted more like the search for conversation, rather than the inbox browser?

**Comment by mmaxim** [comment]
Meta comment: I wonder if it would just be better and simpler to just do like what the mobile share extension does for this. Drop the whole small/big team deal here (its not important for this view), add a search bar, and sort the whole thing on recency (recency gets you what you want 99% of the time with chat). Otherwise, if I want to share into a conversation in the +2 more area (which on my account is +460 more), I have to know to tap there, scroll down to find it and then tap again. In fact, to integrate you could use the same API the mobile share extension uses, and avoid some messy integration with the chat Redux store. 

I know this is a design comment, but this seems in the early stages and maybe some stuff could be tweaked.

**Comment by mmaxim** [comment]
Is there something on Zeplin for this?

**Comment by jzila** [comment]
Yeah @songgao implemented pretty much exactly what's in Zeplin: https://app.zeplin.io/project/56b25ffc64fc91773a73aaf8/screen/5a95d343b034942dab54d67a

**Comment by jzila** [comment]
https://app.zeplin.io/project/56b25ffc64fc91773a73aaf8/screen/5a72122378046f597afa995e

**Comment by songgao** [comment]
@jzila @mmaxim Good points on the need for a search bar. I'm happy to make changes.

What do @keybase/design folks think?

**Comment by songgao** [comment]
Talked to Cécile offline. Will do what you guys suggest. I'm gonna close this for now and work on the new design. Thanks all!

**Pull request closed without merging**
