### PR TITLE
more forgiving timeouts for Appveyor

### PR DESCRIPTION
**Pull request by zanderz**
just testing, not submitting yet...

### CODE REVIEW

**Comment by zanderz** [comment]
ok now I'm submitting - AppVeyor tests just passed with this. Could be a coincidence but looks promising @maxtaco @jacobhaven

**Comment by jacobhaven** [comment]
lgtm

**Comment by zanderz** [comment]
Thanks Jacob. Max, we can change this back if it's wrong, but meanwhile I'm merging.

**Comment by maxtaco** [comment]
Forgot about that timeout.  Why is windows so slow!

LGTM

**Pull request closed without merging**
