### PR TITLE
Protocol for file status (for Finder extension)

### PR DESCRIPTION
**Pull request by gabriel**
This is an example of what RPCs are needed by the Finder extension.

### CODE REVIEW

**Comment by gabriel** [comment]
@maxtaco @strib @akalin 

cc @keybase/react-hackers 

Should we add a kbfs-hackers group?

**Comment by gabriel** [comment]
This is an example of protocol needed for Finder extension, I did not run make on these changes. This isn't for merging in this current state. (If we like this protocol, I can run make and merge.)

**Comment by strib** [comment]
@gabriel: I wrote up a proposal for this in https://keybase.atlassian.net/wiki/display/MP/File+edit+notifications, have you seen that?  (The sync part is unimplemented still.)

**Comment by strib** [comment]
(Not wedded to that proposal at all, just similar to what we have already for other stuff.)

**Comment by gabriel** [comment]
k.. i'll comment there

**Pull request closed without merging**
