### PR TITLE
Support non-basic value types in maps

### PR DESCRIPTION
**Pull request by mlsteele**
I'm going to need map types with non-basic values in a sec. This adds support for them to the avdl -> flow step. They're already supported in avdl.

avdl:
```
record BugBuster {
    map<PublicKey> m1; 
    map<TeamRole,PublicKey> m2; 
    map<TeamRole,array<PublicKey>> m3; 
  }
```

flow:
```
export type BugBuster = {
  m1: {[key: string]: PublicKey},
  m2: {[key: string]: PublicKey},
  m3: {[key: string]: ?Array<PublicKey>}, // was broken
}
```

### CODE REVIEW

**Comment by chrisnojima** [comment]
@react-hackers

**Comment by chrisnojima** [comment]
The types can be stronger. Like not string key

**Comment by mlsteele** [comment]
Ok something I didn't realize is we don't actually support serializing maps with non-string keys into json. So it might not so much matter what the type is, I just need to pass the flow check.

cc @maxtaco

**Comment by chrisnojima** [comment]
flow can type if it's an enum. We can start with this though

**Pull request merged**
