### PR TITLE
protocol: add kbfsRekey protocol

### PR DESCRIPTION
**Pull request by strib**
To be used by the service to find out whether a given folder needs a
rekey for the current logged-in user.

Issue: KBFS-936

### CODE REVIEW

**Comment by strib** [comment]
r @maxtaco?  cc @patrickxb.

This was requested as part of https://keybase.atlassian.net/browse/CORE-2826.  It's not 100% clear to me how this RPC will be used in practice, so let me know if you think the protocol should be different.

**Comment by maxtaco** [comment]
This discussion was long enough ago, that it's not 100% clear to me either.  My hunch is that the service would want to load all unkeyed folders to populate the screens that Cecile has drawn. With this RPC, it's unclear what the args should be.  OTOH, did we ever decide that we can route this information counter-clockwise rather than clockwise?

**Comment by maxtaco** [comment]
Help needed from @patrickxb too!

**Comment by strib** [comment]
Ah.  I don't recall ever explicitly deciding to abandon this plan, but if you think you can get all the needed info directly from `kbfstlfd`, I'm all for doing that instead.  In theory you should be able to figure that out.  I guess you also probably wouldn't need the MD_READ_SUCCESS notification I added in recently.  Let me know what you think.

**Comment by maxtaco** [comment]
We were definitely going in two diverging directions with this stuff and never closed either loop.  Give me some time to investigate.

**Comment by strib** [comment]
Oh, and the for the record, I thought this wasn't about badging, it was about deciding whether or not to show a paperkey prompt and red warning toolbar in the UI.  So I think it was supposed to be about looking up the rekey status of a specific folder, esp. after a restart of the service/kbfs.

**Comment by maxtaco** [comment]
Right, so that's sounding more familiar.  But I don't understand my earlier comment that we'd need this "on startup".

**Comment by strib** [comment]
Frankly I never really understood that either.  I assumed you were talking about the service persistently storing that a TLF was in a bad state, and re-verifying that at startup in order to tell the UI to draw the red warning.  But it would seem better to do that via `kbfstld` these days.

**Comment by patrickxb** [comment]
I can't say I understand why this is needed either.

Does the GUI want a list of folders that need rekeying and it is asking the service?

**Comment by maxtaco** [comment]
@patrickxb reading 2826, that's more like a follow-on feature that we're not building right away.

**Comment by patrickxb** [comment]
Yeah, I just don't see how this RPC relates to the original issue:

> From Chris Coyne:
ok, so this might be the simplest thing:
1. if 10 mins goes by without data being unlocked - or if the user tries to access data in < 10 minutes - popup the paperkey entry
2. if they don’t enter a paper key in step 1, subsequent access errors (not a timed loop) will get sent to an OS notification (one with a “enter paper key” and “close” button); if it’s a share the wording / possible buttons will be slightly different
3. in the menubar dialog, we have a red alert that allows the user to popup the paperkey entry, if needed
This issue it for the KBFS parts of steps 1 and 2. Right now the paper key is prompted for mindlessly every 10 minutes.

**Comment by maxtaco** [comment]
I think I was worried there was state we'd have to reconstruct on process restart.

**Comment by maxtaco** [comment]
The problem is that this simple solution degrades quickly into the general solution if we have to persist the state across reboot.

**Comment by strib** [comment]
Looks like we're abandoning this plan in favor of a service->KBFS notification when a paper key is unlocked.

**Pull request closed without merging**
