### PR TITLE
block global error from ever firing for current uses of dismissCategory

### PR DESCRIPTION
**Pull request by mmaxim**
@keybase/react-hackers 

Stop any black bars from showing up for dismiss category calls.

### CODE REVIEW

**Comment by chrisnojima** [comment]
i'd still prefer to understand if these are errors due to being offline vs real errors. this just kills all error reporting

**Comment by mmaxim** [comment]
It doesn't it is still in the logs. If you see a badge still on the screen, we can check the logs.

**Comment by mmaxim** [comment]
If its an actual problem for the user (which it won't be, the whole goal of this patch is so that users don't see any black bars from this whole flow), then they will see a badge stuck. If, somehow, this RPC call just stops functioning, someone will surely report that stuck badge and we can see in multiple log files this error occurred.

**Comment by cjb** [comment]
@chrisnojima @mmaxim Ideas on how to move forward with this one?  Mike's explanation makes sense to me.

**Comment by chrisnojima** [comment]
fine

**Comment by mmaxim** [comment]
@cjb you want to merge this one instead of yours?

**Pull request merged**
