### PR TITLE
Update to RN 0.27

### PR DESCRIPTION
**Pull request by MarcoPolo**
@keybase/react-hackers Please try running this on your devices to make sure it doesn't only work for me.

Big changes:

Update to RN 0.27
Update Android's barcode scanner to latest.
 
Little Changes:
Using our fork of react-native-camera that uses `react` from the react package and not `react-native`

### CODE REVIEW

**Comment by awendland** [comment]
On iOS (the iPhone 5s simulator w/ iOS 9.3) the login screen for re-logging-in is overflowing outside the width of the phone. This is not present on Android (Nexus 6, API 23).

login page overflows on ios

**Comment by awendland** [comment]
The devices screen is not scrollable on either of my simulators (Android and iOS). It's not scrollable when accessed from the tab bar after being logged in, and it's not scrollable when logging in.

devices not scrollable on all
devices not scrollable in login on all

**Comment by awendland** [comment]
The QR scanner is not centered on iOS. I don't know if this is related to this PR, but you mentioned that you updated the barcode scanning library, so here's the screenshot.
qr code indicator not centered in loggin on ios

**Comment by MarcoPolo** [comment]
Awesome! Thanks @awendland! I think these are mostly pre-existing issues. Not sure about the login screen though, but I think that can be handled in a future PR and shouldn't block this

**Comment by chrisnojima** [comment]
I don't think this is an existing issue

**Comment by MarcoPolo** [comment]
Which one?

The device screen doesn't use a scroll view, so it wouldn't have scrolled before.

Not sure about the qr code scanner.

Just checked an older build and the login screen funkiness is not an existing issue

**Comment by cjb** [comment]
:thumbsup: `react-native run-android` doesn't seem to be working for me on Linux, but I usually use Studio anyway

**Comment by MarcoPolo** [comment]
will merge as soon as CI passes

**Comment by MarcoPolo** [comment]
I was wrong, the login screen funkiness is pre-existing. QR issue is fixed.

**Pull request merged**
