### PR TITLE
Move chat1.local protocol to client

### PR DESCRIPTION
**Pull request by patrickxb**
@mmaxim as we discussed in slack, this moves the chat1.local protocol from gregor to client.  chat1.common still in gregor.  Fixes the vendoring issues.

### CODE REVIEW

**Comment by mmaxim** [comment]
👍 although CI failed for some reason

**Comment by patrickxb** [comment]
@keybase/react-hackers need some flow help here.  new protocol files for chat.

**Comment by chrisnojima** [comment]
fixing

**Comment by jzila** [comment]
Please rebase

**Comment by patrickxb** [comment]
I'm waiting on https://github.com/keybase/client/pull/3852 which is branched off of this branch

**Comment by patrickxb** [comment]
It should fix the flow errors.

**Pull request merged**
