### PR TITLE
delete incoming messages if they're of type delete

### PR DESCRIPTION
**Pull request by chrisnojima**
this is a very small fix to fix missing timestamps on messages that come after a deleted message. I think we could discuss handling of deletes differently in the future but i think thats a larger change that would require some care. there are flows where we get placeholders and we need to replace them with delete (or clean up in a different way). Short term (this pr) if we load a thread and get a deleted message we just toss it immediately and act as if it didn't exist. 

@keybase/react-hackers

### CODE REVIEW

**Comment by mmaxim** [comment]
Have you actually seen this happen? I don't think it should be possible.

**Comment by chrisnojima** [comment]
Yes 100%. Load Keybase#design ( see the jira ticket)

**Comment by mmaxim** [comment]
Ok please hold off on merging for a second, I want to try and understand what is going on here.

**Comment by chrisnojima** [comment]
- [ ] waiting on mike

**Comment by chrisnojima** [comment]
@mmaxim updated, can you test the flow you mentioned. i tried and it seemed to work but we should be more sure

**Pull request merged**
