### PR TITLE
Install app bundle, privileged with signed requirements check

### PR DESCRIPTION
**Pull request by gabriel**
This updates the installer to allow use of privileges to install a Keybase.app bundle, signed by us, even if user isn't admin or have ownership of the existing installed bundle. This allows the app to update properly if installed by non-admin user, or different user that the current one.

The following `keybase` CLI command can be run to install the source app bundle (from the updater):
```sh
keybase install --components=app --source-path=/path/to/Keybase.app
```

This calls the native installer:
```sh
KeybaseInstaller.app/Contents/MacOS/Keybase --app-path=/Applications/Keybase.app \
  --run-mode=prod --timeout=10 --install-app-bundle --source-path=/path/to/Keybase.app
```

Before copying the app bundle from source path to app (destination) path using the privileged helper tool, we do a `SecStaticCodeCheckValidityWithErrors` with the requirements that the bundle be signed by our certificate (issued by Apple) and correct identifier.

This prevents the install from installing a bundle it shouldn't. For example if you take a random app and do `keybase install --components=app --source-path=/some/Other.app` it will fail with an error message that the security check failed.

### CODE REVIEW

**Comment by gabriel** [comment]
@chromakode You've reviewed other install code in the past, maybe could review this?

cc @keybase/react-hackers

**Comment by gabriel** [comment]
Ok ready for review. Snuck in NULL check that was crashing for some people with weird Finder file list items (when adding ourselves).

**Comment by gabriel** [comment]
Bump

**Comment by chromakode** [comment]
Ah! Just saw this. I can take a look at it tomorrow. What are the ramifications of a different user that the current one updating the app? Anyone on the system can update the global privileged files to a signed version of the Keybase client? Does this work for downgrades too (could that be a security issue)?

**Comment by chromakode** [comment]
Oops, pressed the wrong button :blush:

**Comment by gabriel** [comment]
> Anyone on the system can update the global privileged files to a signed version of the Keybase client?

Yes, this is right. Basically the Keybase signed app can update to another Keybase signed app, and any user.

> Does this work for downgrades too (could that be a security issue)?

Yes, and this is a security issue with current setup too though. Probably the best way to deal with minimum versions is by preventing old clients from working with our servers, if we needed to do that.

**Pull request merged**
