### PR TITLE
Fix hardcoded brew path

### PR DESCRIPTION
**Pull request by gabriel**
Also remove some extraneous debug output

### CODE REVIEW

**Comment by oconnor663** [comment]
This looks good to me, but maybe one of the Brew users should take a look?

**Comment by patrickxb** [comment]
LGTM

**Comment by maxtaco** [comment]
It makes me a little nervous we're discarding a lot of output and messaging. Won't this make things harder to debug?

**Comment by auremoser** [comment]
Hi Keybase, This is still a problem for me, I have the same error as [#1882](https://github.com/keybase/keybase-issues/issues/1882). I have an existing keybase ID and now have a new machine, so I'd rather login than signup again with a new identity.

I can try the symlink suggestion but I wanted to flag this as still not fixed on a new MacBookAir, OSX El Capitan, unless I'm doing something wrong. Thank you for reading.

**Comment by maxtaco** [comment]
@auremoser thanks for your reply.  Can you post a log of your failure?  Also include `-d` so we can take a look to see what went wrong.

**Comment by auremoser** [comment]
surely, ran `keybase -d login`
result:
>10:17:25.181870 ▶ [DEBU keybase json.go:48] 001 + loading config file: /Users/aurelia/Library/Application Support/Keybase/config.json
10:17:25.182742 ▶ [DEBU keybase json.go:56] 002 No config file found; tried /Users/aurelia/Library/Application Support/Keybase/config.json
10:17:25.183333 ▶ [DEBU keybase config.go:114] 003 Config: mapping server -> 
10:17:25.185354 ▶ [DEBU keybase config.go:114] 004 Config: mapping socket_file -> 
10:17:25.185383 ▶ [DEBU keybase config.go:114] 005 Config: mapping home -> 
10:17:25.196837 ▶ [DEBU keybase ui.go:432] 006 Setting GPG_TTY to /dev/ttys002
10:17:25.197175 ▶ [DEBU keybase config.go:114] 007 Config: mapping timers -> 
10:17:25.197190 ▶ [DEBU keybase globals.go:186] 008 Keybase CLI 1.0.6-0
10:17:25.197466 ▶ [DEBU keybase globals.go:186] 009 - Built with go1.5.2
10:17:25.197477 ▶ [DEBU keybase globals.go:186] 00a - Visit https://keybase.io for more details
10:17:25.197766 ▶ [DEBU keybase main.go:100] 00b + configureProcesses
10:17:25.198018 ▶ [DEBU keybase install_osx.go:701] 00c + AutoInstall for launchd
10:17:26.322638 ▶ [DEBU keybase install_osx.go:466] 00d Using binPath: /usr/local/opt/keybase/bin/keybase
10:17:26.322729 ▶ [INFO keybase install_osx.go:467] 00e Checking service
10:17:26.322780 ▶ [DEBU keybase config.go:114] 00f Config: mapping home -> 
10:17:26.334695 ▶ [INFO keybase install_osx.go:469] 010 Service: Not Installed (Action: Install)
10:17:26.334781 ▶ [INFO keybase install_osx.go:471] 011 Installing Keybase service
10:17:26.345842 ▶ [DEBU keybase config.go:114] 012 Config: mapping home -> 
10:17:26.351632 ▶ [DEBU keybase util.go:195] 013 + Writing to /Users/aurelia/Library/LaunchAgents/homebrew.mxcl.keybase.plist
10:17:26.352243 ▶ [DEBU keybase util.go:197] 014 | Temporary file generated: /Users/aurelia/Library/LaunchAgents/homebrew.mxcl.keybase.plist.R3FF5BGJTVJRPM423FBZOCCV32I2QHL5
10:17:26.352290 ▶ [ERRO keybase standard.go:182] 015 Error installing Keybase service: open /Users/aurelia/Library/LaunchAgents/homebrew.mxcl.keybase.plist.R3FF5BGJTVJRPM423FBZOCCV32I2QHL5: no such file or directory
10:17:26.355600 ▶ [DEBU keybase install_osx.go:703] 016 - AutoInstall -> false, open /Users/aurelia/Library/LaunchAgents/homebrew.mxcl.keybase.plist.R3FF5BGJTVJRPM423FBZOCCV32I2QHL5: no such file or directory
10:17:26.355649 ▶ [DEBU keybase main.go:102] 017 - configureProcesses -> open /Users/aurelia/Library/LaunchAgents/homebrew.mxcl.keybase.plist.R3FF5BGJTVJRPM423FBZOCCV32I2QHL5: no such file or directory
10:17:26.355669 ▶ [DEBU keybase globals.go:231] 018 Calling shutdown first time through
10:17:26.358976 ▶ [DEBU keybase login_state.go:878] 019 + Account "LoginState - Shutdown"
10:17:26.359100 ▶ [DEBU keybase login_state.go:880] 01a - Account "LoginState - Shutdown"
10:17:26.359132 ▶ [DEBU keybase globals.go:271] 01b exiting shutdown code=0; err=<nil>
10:17:26.359427 ▶ [ERRO keybase main.go:47] 01c open /Users/aurelia/Library/LaunchAgents/homebrew.mxcl.keybase.plist.R3FF5BGJTVJRPM423FBZOCCV32I2QHL5: no such file or directory

Thank you for your help, let me know if the above should be edited for a public post.

**Comment by maxtaco** [comment]
Interesting.  All of this stuff is public and standard, so no need to worry about data disclosure.

What if you do `mkdir -p /Users/aurelia/Library/LaunchAgents` and then try again?

Thanks for your help!

**Comment by auremoser** [comment]
Thank you so much! That worked :). I need to device add via my other machine, howevs. 

A bit of an aside, but if I didn't store my public key on keybase in the browser, there's no way to `device add` for a new machine if you don't have access to the old one (to type in the generated passphrase)? Sorry if that doesn't make sense, just curious. Requiring the previous device or a paperkey seems analogous to having to tote your private key around as with reg gpg, but I guess there's no work-around if you're not willing to store your private key somewhere.

**Comment by maxtaco** [comment]
I'm glad it worked, I'll put in a fix to solve this issue for others automatically.

As for your second concern, I think you're right, that's an inherent cryptographic limitation.  However, this process will be much easier once our iPhone/Android apps are live, since they will have a device-specific key, and make provisioning as simple as taking a pic of a QR code.

Until that's ready, however, we have the ugly kludge of the paper key, or physically bringing two laptops together.

**Pull request merged**
