### PR TITLE
Tweak margins a bit to add confirm or pending on mobile

### PR DESCRIPTION
**Pull request by MarcoPolo**
@keybase/react-hackers 

Almost the exact same thing as the desktop version with some tweaks to margins.

Wait until @cjb's https://github.com/keybase/client/pull/3890 is merged since this uses platform icon.

Previews:

screen shot 2016-08-15 at 4 12 45 pm
screen shot 2016-08-15 at 4 08 34 pm
screen shot 2016-08-15 at 4 08 46 pm
screen shot 2016-08-15 at 4 08 57 pm
screen shot 2016-08-15 at 4 11 49 pm

### CODE REVIEW

**Comment by awendland** [comment]
The design calls for some padding above the notification banner that is consistent with the padding on screens with the cancel button. I think it would be easiest if you leveraged `StandardScreen` to handle it.

On a larger discussion point, I think the design calls for something that looks good on iOS but may not be as stellar on Android, because the Android system notification bar is a different color than the white spacing between it and the notification banner. But that will crop up with all of these use cases and therefore should be able to be fixed in a localized place if they all use StandardScreen.

**Comment by MarcoPolo** [comment]
Updated. It looks weird on both platforms I think.
screen shot 2016-08-15 at 4 39 43 pm
screen shot 2016-08-15 at 4 39 46 pm

**Comment by MarcoPolo** [comment]
Taking this to #design

**Comment by cjb** [comment]
@MarcoPolo PlatformIcon's merged in now (thanks for the review, applied your comments!), so you can proceed with this PR.

(:thumbsup: % design question)

**Pull request merged**
