### PR TITLE
more exact for types

### PR DESCRIPTION
**Pull request by chrisnojima**
@keybase/react-hackers some more exact in the generated code

### CODE REVIEW

**Comment by MarcoPolo** [comment]
We don't really gain anything when using exact for types without optional keys, because we'll always get an error if we miss something.

Adding $Exact is also not free, since it doesn't work well with intersection types. `Foo & $Exact<Bar>` is not the same as `Foo & Bar`.

Maybe we want to only use exact when there's an optional field?

Or maybe we should not even use optional fields and just make the values maybe.

**Comment by chrisnojima** [comment]
we'll never make intersections with these raw rpc types right

**Comment by keybase-ci-visdiff** [comment]
:mag_right: The commits 1828166cd535...a7915dfea35a introduced some visual changes on linux:
 * Changed: **unlock_folders-Paperkey_error_waiting** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1467313547142-1828166cd535-a7915dfea35a-linux/unlock_folders-Paperkey_error_waiting-1828166cd535.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1467313547142-1828166cd535-a7915dfea35a-linux/unlock_folders-Paperkey_error_waiting-a7915dfea35a.png)  
   unlock_folders-Paperkey_error_waiting comparison

**Comment by MarcoPolo** [comment]
I can't think of a case.

We can go with this and change later if it's problematic. 👍

**Comment by chrisnojima** [comment]
meh lets just not do this

**Pull request closed without merging**
