### PR TITLE
6-liner feature flag out-of-date banner

### PR DESCRIPTION
**Pull request by songgao**

### CODE REVIEW

**Comment by chrisnojima** [comment]
what is the plan here? are you working on this and we'll turn it on or ?

**Comment by songgao** [comment]
@chrisnojima Coyne requested to not release this until it's more responsive. Right now it just runs `keybase update check` behind the scene when "update now" is clicked. I have a ticket for next sprint to make it turn into something else and wait on the download until the update prompt pops up. Feature flagging is in case this gets released before that's done.

**Comment by chrisnojima** [comment]
lets just add its own feature flag and not tie it to admin

**Comment by chrisnojima** [comment]
lets just add its own feature flag and not tie it to admin

**Pull request merged**
