### PR TITLE
Kill Pods

### PR DESCRIPTION
**Pull request by MarcoPolo**
I don't think we need this

@keybase/react-hackers

### CODE REVIEW

**Comment by MarcoPolo** [comment]
retest this please

**Comment by chrisnojima** [comment]
i agree, i set it up as an example, but its easy enough to put back in 👍

**Comment by MarcoPolo** [comment]
retest this please

**Comment by keybase-ci-visdiff** [comment]
:mag_right: The commits 9c6469ca7b17...9f6ec5ffb934 introduced some visual changes on linux:
 * Changed: **unlock_folders-Success** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1467404751915-9c6469ca7b17-9f6ec5ffb934-linux/unlock_folders-Success-9c6469ca7b17.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1467404751915-9c6469ca7b17-9f6ec5ffb934-linux/unlock_folders-Success-9f6ec5ffb934.png)  
   unlock_folders-Success comparison

**Comment by chromakode** [comment]
:+1: :hocho:

**Pull request merged**
