### PR TITLE
Remove labeling from CI contexts

### PR DESCRIPTION
**Pull request by jzila**
r? @cjb @gabriel

### CODE REVIEW

**Comment by cjb** [comment]
@jzila there's a separate script that checks the contexts for Linux builds, grep for the same wait-ci calls

**Comment by jzila** [comment]
K should I leave this change though?

**Comment by cjb** [comment]
yep we should do your change in both places

**Comment by cjb** [comment]
:ship:

**Comment by jzila** [comment]
@cjb what's the workflow between landing keybase/release#15 and landing this change?

**Comment by cjb** [comment]
@jzila I think you can merge this one, then merge the client one, then say "!keybot build darwin" to test both

**Pull request merged**
