### PR TITLE
fix an infinite loop in promptRemoteName

### PR DESCRIPTION
**Pull request by oconnor663**
r? @patrickxb @akalin

### CODE REVIEW

**Comment by oconnor663** [comment]
We could write a test that just makes sure this doesn't infinite loop, but testing the correct retry logic for invalid usernames will be more involved. I'm tempted to put it off?

**Comment by keybase-ci-visdiff** [comment]
:mag_right: No visual changes found as a result of these commits.

**Comment by patrickxb** [comment]
Code is much easier to follow.  LGTM!

A test would be nice, but I think important to get this in as current state is completely busted if username not provided on command line.

**Comment by oconnor663** [comment]
Filed https://keybase.atlassian.net/browse/CORE-3156.

**Comment by akalin-keybase** [comment]
lgtm

**Pull request merged**
