### PR TITLE
add colon to getWordAtCursor separators

### PR DESCRIPTION
**Pull request by hyperobject**
fixes issues with opening emoji suggestors caused by changes to how getWordAtCursor works

### CODE REVIEW

**Comment by hyperobject** [comment]
the updated regex now also splits on colons followed by spaces so the suggestor box doesn't show after ending an emoji. ideally this regex wouldn't eat the last colon of emoji matches, but js doesn't support regex lookbehinds and i was already spending too much time wrangling regex

**Comment by buoyad** [comment]
`+1XLM@` suggestions in the middle of the message are also broken. What was the point of the original change?

**Comment by hyperobject** [comment]
> `+1XLM@` suggestions in the middle of the message are also broken. What was the point of the original change?

the change was to fix some weirdness with multi-word commands not behaving correctly (getWordAtCursor was splitting on all spaces which broke the suggestor list)

**Comment by hyperobject** [comment]
gonna close this pr since the actual fix is going to be something different

**Pull request closed without merging**
