### PR TITLE
Fix removeLocalTracks after storeRemoteTrack

### PR DESCRIPTION
**Pull request by patrickxb**
@maxtaco we discussed this in slack, I think this is the correct/intended logic here.

### CODE REVIEW

**Comment by keybase-ci-visdiff** [comment]
:mag_right: The commits 3c54cc36fe0a...9334a0c4014a introduced some visual changes on win32:
 * Changed: **user_search-Normal** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468344500179-3c54cc36fe0a-9334a0c4014a-win32/user_search-Normal-3c54cc36fe0a.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468344500179-3c54cc36fe0a-9334a0c4014a-win32/user_search-Normal-9334a0c4014a.png)  
   user_search-Normal comparison
 * Changed: **unlock_folders-No_paperkeys** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468344500179-3c54cc36fe0a-9334a0c4014a-win32/unlock_folders-No_paperkeys-3c54cc36fe0a.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468344500179-3c54cc36fe0a-9334a0c4014a-win32/unlock_folders-No_paperkeys-9334a0c4014a.png)  
   unlock_folders-No_paperkeys comparison

**Comment by maxtaco** [comment]
👍

**Comment by keybase-ci-visdiff** [comment]
:mag_right: The commits 3c54cc36fe0a...9334a0c4014a introduced some visual changes on win32:
 * Changed: **user_search-Normal** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468346256797-3c54cc36fe0a-9334a0c4014a-win32/user_search-Normal-3c54cc36fe0a.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468346256797-3c54cc36fe0a-9334a0c4014a-win32/user_search-Normal-9334a0c4014a.png)  
   user_search-Normal comparison
 * Changed: **unlock_folders-Single** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468346256797-3c54cc36fe0a-9334a0c4014a-win32/unlock_folders-Single-3c54cc36fe0a.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468346256797-3c54cc36fe0a-9334a0c4014a-win32/unlock_folders-Single-9334a0c4014a.png)  
   unlock_folders-Single comparison

**Comment by keybase-ci-visdiff** [comment]
:mag_right: The commits 3c54cc36fe0a...9334a0c4014a introduced some visual changes on win32:
 * Changed: **user_search-Normal** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468347894345-3c54cc36fe0a-9334a0c4014a-win32/user_search-Normal-3c54cc36fe0a.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468347894345-3c54cc36fe0a-9334a0c4014a-win32/user_search-Normal-9334a0c4014a.png)  
   user_search-Normal comparison
 * Changed: **unlock_folders-Paperkey_error** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468347894345-3c54cc36fe0a-9334a0c4014a-win32/unlock_folders-Paperkey_error-3c54cc36fe0a.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468347894345-3c54cc36fe0a-9334a0c4014a-win32/unlock_folders-Paperkey_error-9334a0c4014a.png)  
   unlock_folders-Paperkey_error comparison

**Pull request merged**
