### PR TITLE
Add channel to @ mention dialog

### PR DESCRIPTION
**Pull request by akalin-keybase**
...but not @here or @everyone.

Also add utility functions for these aliases, and
highlight @everyone properly.

### CODE REVIEW

**Comment by akalin-keybase** [comment]
screen shot 2018-01-22 at 1 36 25 pm

**Comment by akalin-keybase** [comment]
? @keybase/react-hackers

**Comment by dabura667** [comment]
Do we really need @here? The assumption is that @here is a less intrusive version of @channel where it will only ping people who are actively looking at the slack and are a member of the channel.

I think many people will see @here available and assume that people offline won't be pinged.

**Comment by akalin-keybase** [comment]
@dabura667 hmm good point. Let me see about @here...

**Comment by akalin-keybase** [comment]
(Blocked on backend change to remove `@here`)

**Comment by akalin-keybase** [comment]
Okay, unblocking this; just adding @channel to the list. PTAL @keybase/react-hackers 

screenshot from 2018-02-08 14-51-30

**Pull request merged**
