### PR TITLE
kbpki_client: add id->username cache

### PR DESCRIPTION
**Pull request by strib**
`folderBranchOps.GetNodeMetadata` gets the normalized username given an ID on every call, which results in a service RPC.  However, this mapping can be easily cached since it basically never changes. So this adds a small LRU cache for those mappings.

Issue: HOTPOT-877

### CODE REVIEW

**Comment by songgao** [comment]
What about in SBS case? Does normalized username still not change?

**Comment by strib** [comment]
> What about in SBS case? Does normalized username still not change?

This is only looking up normalized usernames from UIDs.  In this SBS case, there is no UID, so this function (and cache) won't be used.

**Comment by strib** [comment]
@songgao when I answered your question above, I was thinking about users (since that is the performance problem I'm solving here).  But it is true that _team_ names can change, both because of SBS resolutions and subteam renames.  I don't _think_ this particular cache would get hit much in those cases, but I just added a new commit (354e812) to invalidate the cache on team renames.  Thanks for the reminder.  Please take another look!

**Comment by songgao** [comment]
NP! Is team name change by SBS resolutions is because of implicit team name?

**Comment by strib** [comment]
> NP! Is team name change by SBS resolutions is because of implicit team name?

Both implicit teams containing SBS assertions, and subteam renames, can cause team name changes.

**Pull request merged**
