### PR TITLE
Fuse 3.5.2

### PR DESCRIPTION
**Pull request by gabriel**
New KBFuse 3.5.2 included in installer.

Also re-enables KBFS on Sierra.

### CODE REVIEW

**Comment by gabriel** [comment]
@strib @akalin @keybase/react-hackers

**Comment by cjb** [comment]
@gabriel Thanks! Is this signed?

I don't think we want to release this until we've worked out whether it breaks Time Machine.  So if merging this is equivalent to putting it in the next build, please no-one merge it yet.

**Comment by gabriel** [comment]
Yeah signed... Yeah we should hold off on merge until we're ok for testing...

I'm doing an app build for this branch, and will post link to that there for testing.

**Comment by cjb** [comment]
k, please keep the link private if there is significant suspicion that it's a link that will hose Time Machine backups.

**Pull request merged**
