### PR TITLE
retry on unexpected generation

### PR DESCRIPTION
**Pull request by heronhaye**
Bandaid. Since all actions happened on the same device.

### CODE REVIEW

**Comment by heronhaye** [comment]
cc @maxtaco. Tried for a bit to figure this out but couldn't. Will take another look in a few days

**Comment by heronhaye** [comment]
(This fails at the last AddMember with a serverside generation assertion error - expected 2, got 1)

**Comment by maxtaco** [comment]
@heronhaye out of curiosity, why were you making this test?  In the past, it might suffice to add errors to the list of those that are auto-retried, if this is a race that can happen with CLKRs requiring asynchronous team reloads.

**Comment by heronhaye** [comment]
@maxtaco This is another one of the flakes that was triggered in my metadata update systest. Should I add a case to RetryIfPossible?

**Comment by maxtaco** [comment]
Which error & error code is it?

**Comment by heronhaye** [comment]
```
"generation assertion failed processing team secret keys", sc.TEAM_BAD_GENERATION
```

**Comment by maxtaco** [comment]
Sure, I'd try to just add another retry condition....

**Comment by heronhaye** [comment]
@maxtaco ready for another look.

**Comment by heronhaye** [comment]
ok, I'm just merging this. CI constantly flakes on a chat test and mysterious grey orb.

**Pull request merged**
