### PR TITLE
Update font icons

### PR DESCRIPTION
**Pull request by chromakode**
Hopefully no visdiff!

Icomoon can export all of the project data to a .json file, which should make future updates easier. When I initially discovered the "svg" directory, its purpose was unclear to me -- I assumed we used the svgs directly as icons somewhere. I propose moving these files & related documentation to their own folder under "shared/images" to make their relation more obvious.

:eyeglasses: @keybase/react-hackers

### CODE REVIEW

**Comment by keybase-ci-visdiff** [comment]
:mag_right: The commits 7e6bebf43b64...9d462a9c3c82 introduced some visual changes:
 * Changed: **Tab_Bar-Custom_Buttons_1** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1466121133093-7e6bebf43b64-9d462a9c3c82/Tab_Bar-Custom_Buttons_1-7e6bebf43b64.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1466121133093-7e6bebf43b64-9d462a9c3c82/Tab_Bar-Custom_Buttons_1-9d462a9c3c82.png)  
   Tab_Bar-Custom_Buttons_1 comparison
 * Changed: **Tab_Bar-Custom_Buttons_0** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1466121133093-7e6bebf43b64-9d462a9c3c82/Tab_Bar-Custom_Buttons_0-7e6bebf43b64.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1466121133093-7e6bebf43b64-9d462a9c3c82/Tab_Bar-Custom_Buttons_0-9d462a9c3c82.png)  
   Tab_Bar-Custom_Buttons_0 comparison
 * Changed: **Profile-Changed** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1466121133093-7e6bebf43b64-9d462a9c3c82/Profile-Changed-7e6bebf43b64.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1466121133093-7e6bebf43b64-9d462a9c3c82/Profile-Changed-9d462a9c3c82.png)  
   Profile-Changed comparison
 * Changed: **App_Tab_Bar-Normal** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1466121133093-7e6bebf43b64-9d462a9c3c82/App_Tab_Bar-Normal-7e6bebf43b64.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1466121133093-7e6bebf43b64-9d462a9c3c82/App_Tab_Bar-Normal-9d462a9c3c82.png)  
   App_Tab_Bar-Normal comparison

**Comment by chromakode** [comment]
Not sure why the mobile phone icon moved -- I ran the font through fontsquirrel with "Auto-Adjust Vertical Metrics".

**Comment by keybase-ci-visdiff** [comment]
:mag_right: The commits 7e6bebf43b64...85d90a9f1eba introduced some visual changes:
 * Changed: **Tab_Bar-Custom_Buttons_1** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1466122040244-7e6bebf43b64-85d90a9f1eba/Tab_Bar-Custom_Buttons_1-7e6bebf43b64.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1466122040244-7e6bebf43b64-85d90a9f1eba/Tab_Bar-Custom_Buttons_1-85d90a9f1eba.png)  
   Tab_Bar-Custom_Buttons_1 comparison
 * Changed: **Tab_Bar-Custom_Buttons_0** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1466122040244-7e6bebf43b64-85d90a9f1eba/Tab_Bar-Custom_Buttons_0-7e6bebf43b64.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1466122040244-7e6bebf43b64-85d90a9f1eba/Tab_Bar-Custom_Buttons_0-85d90a9f1eba.png)  
   Tab_Bar-Custom_Buttons_0 comparison
 * Changed: **App_Tab_Bar-Normal** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1466122040244-7e6bebf43b64-85d90a9f1eba/App_Tab_Bar-Normal-7e6bebf43b64.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1466122040244-7e6bebf43b64-85d90a9f1eba/App_Tab_Bar-Normal-85d90a9f1eba.png)  
   App_Tab_Bar-Normal comparison

**Comment by keybase-ci-visdiff** [comment]
:mag_right: The commits 7e6bebf43b64...85d90a9f1eba introduced some visual changes:
 * Changed: **Tab_Bar-Custom_Buttons_1** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1466122911432-7e6bebf43b64-85d90a9f1eba/Tab_Bar-Custom_Buttons_1-7e6bebf43b64.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1466122911432-7e6bebf43b64-85d90a9f1eba/Tab_Bar-Custom_Buttons_1-85d90a9f1eba.png)  
   Tab_Bar-Custom_Buttons_1 comparison
 * Changed: **Tab_Bar-Custom_Buttons_0** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1466122911432-7e6bebf43b64-85d90a9f1eba/Tab_Bar-Custom_Buttons_0-7e6bebf43b64.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1466122911432-7e6bebf43b64-85d90a9f1eba/Tab_Bar-Custom_Buttons_0-85d90a9f1eba.png)  
   Tab_Bar-Custom_Buttons_0 comparison
 * Changed: **App_Tab_Bar-Normal** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1466122911432-7e6bebf43b64-85d90a9f1eba/App_Tab_Bar-Normal-7e6bebf43b64.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1466122911432-7e6bebf43b64-85d90a9f1eba/App_Tab_Bar-Normal-85d90a9f1eba.png)  
   App_Tab_Bar-Normal comparison

**Comment by chrisnojima** [comment]
mmmm, its possible the tools can have some wiggle i guess. doens't seem so messed up it'd matter. i didn't look on mobile but does it look ok? if so
👍

**Comment by keybase-ci-visdiff** [comment]
:mag_right: The commits 97dbe3edccac...2b9c360d63b4 introduced some visual changes:
 * Changed: **Tab_Bar-Custom_Buttons_1** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1466186515107-97dbe3edccac-2b9c360d63b4/Tab_Bar-Custom_Buttons_1-97dbe3edccac.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1466186515107-97dbe3edccac-2b9c360d63b4/Tab_Bar-Custom_Buttons_1-2b9c360d63b4.png)  
   Tab_Bar-Custom_Buttons_1 comparison
 * Changed: **Tab_Bar-Custom_Buttons_0** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1466186515107-97dbe3edccac-2b9c360d63b4/Tab_Bar-Custom_Buttons_0-97dbe3edccac.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1466186515107-97dbe3edccac-2b9c360d63b4/Tab_Bar-Custom_Buttons_0-2b9c360d63b4.png)  
   Tab_Bar-Custom_Buttons_0 comparison
 * Changed: **App_Tab_Bar-Normal** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1466186515107-97dbe3edccac-2b9c360d63b4/App_Tab_Bar-Normal-97dbe3edccac.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1466186515107-97dbe3edccac-2b9c360d63b4/App_Tab_Bar-Normal-2b9c360d63b4.png)  
   App_Tab_Bar-Normal comparison

**Comment by chromakode** [comment]
Thanks, just ran through iOS and Android and didn't notice any glaring differences. Some font icons appear to be misaligned vertically in both master and this new branch. Proceeding with the merge.

**Comment by keybase-ci-visdiff** [comment]
:mag_right: The commits 97dbe3edccac...0d1cc69e457f introduced some visual changes:
 * Changed: **Tab_Bar-Custom_Buttons_1** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1466195165825-97dbe3edccac-0d1cc69e457f/Tab_Bar-Custom_Buttons_1-97dbe3edccac.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1466195165825-97dbe3edccac-0d1cc69e457f/Tab_Bar-Custom_Buttons_1-0d1cc69e457f.png)  
   Tab_Bar-Custom_Buttons_1 comparison
 * Changed: **Tab_Bar-Custom_Buttons_0** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1466195165825-97dbe3edccac-0d1cc69e457f/Tab_Bar-Custom_Buttons_0-97dbe3edccac.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1466195165825-97dbe3edccac-0d1cc69e457f/Tab_Bar-Custom_Buttons_0-0d1cc69e457f.png)  
   Tab_Bar-Custom_Buttons_0 comparison
 * Changed: **App_Tab_Bar-Normal** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1466195165825-97dbe3edccac-0d1cc69e457f/App_Tab_Bar-Normal-97dbe3edccac.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1466195165825-97dbe3edccac-0d1cc69e457f/App_Tab_Bar-Normal-0d1cc69e457f.png)  
   App_Tab_Bar-Normal comparison

**Comment by keybase-ci-visdiff** [comment]
:mag_right: The commits f66a99283e10...43203a7c6339 introduced some visual changes:
 * Changed: **Tab_Bar-Custom_Buttons_1** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1466208005140-f66a99283e10-43203a7c6339/Tab_Bar-Custom_Buttons_1-f66a99283e10.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1466208005140-f66a99283e10-43203a7c6339/Tab_Bar-Custom_Buttons_1-43203a7c6339.png)  
   Tab_Bar-Custom_Buttons_1 comparison
 * Changed: **Tab_Bar-Custom_Buttons_0** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1466208005140-f66a99283e10-43203a7c6339/Tab_Bar-Custom_Buttons_0-f66a99283e10.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1466208005140-f66a99283e10-43203a7c6339/Tab_Bar-Custom_Buttons_0-43203a7c6339.png)  
   Tab_Bar-Custom_Buttons_0 comparison
 * Changed: **App_Tab_Bar-Normal** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1466208005140-f66a99283e10-43203a7c6339/App_Tab_Bar-Normal-f66a99283e10.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1466208005140-f66a99283e10-43203a7c6339/App_Tab_Bar-Normal-43203a7c6339.png)  
   App_Tab_Bar-Normal comparison

**Pull request merged**
