### PR TITLE
PICNIC-942 - Ctrl/Cmd tabbing from crypto tab fix

### PR DESCRIPTION
**Pull request by thebearjew**
cc @keybase/picnicsquad

### CODE REVIEW

**Comment by patrickxb** [comment]
i thought @malgorithms wasn't into this solution?

**Comment by chrisnojima** [comment]
this isn't necessary, chat takes focus, yet still works

**Comment by thebearjew** [comment]
@chrisnojima `mousetrap` fixed it. Explain.

**Comment by thebearjew** [comment]
@cjb thanks fixed

**Comment by thebearjew** [comment]
https://github.com/ccampbell/mousetrap/blob/master/mousetrap.js#L973-L979

I would like to add this as a prop to `plain-input/index.desktop.tsx`.

**Comment by thebearjew** [comment]
Latest commit adds `mousetrap` class to all `textarea` and `input` elements. 

Source: https://craig.is/killing/mice

> By default all keyboard events will not fire if you are inside of a textarea, input, or select to prevent undesirable things from happening.
> 
> If you want them to fire you can add the class mousetrap to the element.

**Pull request merged**
