### PR TITLE
Popup HOC Component

### PR DESCRIPTION
**Pull request by MarcoPolo**
@keybase/react-hackers Please take a look and see if this is something that makes sense. Esp. @cjb since you have that open PR that could benefit from this.

The basics are:

There is now a new HOC called `RelativePopupHOC` it takes in two components a target component that will be drawn normally, and a popup component that will be drawn when the prop `open=true`

The signature of the HOC is:

```
type RelativePopupProps<TP, PP> = {
  open: boolean,
  onClose: () => void,
  position: Position,
  targetProps: TP,
  popupProps: PP,
}

function RelativePopupHoc<TP, PP>(
  TargetComponent: React.ComponentType<TP>,
  PopupComponent: React.ComponentType<PP>
): React.ComponentType<RelativePopupProps<TP, PP>> { ... }
```

### CODE REVIEW

**Comment by zanderz** [comment]
is this a bit like the menubar package?

**Comment by MarcoPolo** [comment]
menubar package?

**Comment by zanderz** [comment]
https://www.npmjs.com/package/menubar

**Comment by MarcoPolo** [comment]
No, this is for popups within the app, not outside them

**Comment by cjb** [comment]
@MarcoPolo Oh, does the version in the latest commit still work without using routes?  Need to use a non-routing version for tracker popups.  It looks like the previous prop code might have been replaced with routeProps code.

**Comment by cjb** [comment]
@MarcoPolo No worries, I figured it out, just needed to make a new wrapper.

**Pull request merged**
