### PR TITLE
prompt user to choose conversation for read/send

### PR DESCRIPTION
**Pull request by songgao**
```
[songgao@Song-ThinkPad keybase]$ ./keybase login
▶ WARNING Running in devel mode
▶ INFO Forking background server with pid=25504
[songgao@Song-ThinkPad keybase]$ ./keybase chat list
▶ WARNING Running in devel mode
[1]  t_alice,t_bob,test2  [test2 6m] msg for alice and bob                                                                     
[2]  t_alice,test2       [test2 17m] alice                                                                                     
[songgao@Song-ThinkPad keybase]$ ./keybase chat read
▶ WARNING Running in devel mode
There are 2 conversations. Please choose one:
[1] t_alice,t_bob,test2                                                                                                        
[2] t_alice,test2                                                                                                              
Please enter a number [1-2]: 2
fetching conversation t_alice,test2 ...

[1]  [test2 17m] alice                                                                                                         
[2]   [test2 2h] hi                                                                                                            

[songgao@Song-ThinkPad keybase]$ ./keybase chat send "msg for alice"
▶ WARNING Running in devel mode
There are 2 conversations. Please choose one:
[1] t_alice,test2                                                                                                              
[2] t_alice,t_bob,test2                                                                                                        
Please enter a number [1-2]: 1
sending to t_alice,test2 ... done!
[songgao@Song-ThinkPad keybase]$ ./keybase chat list
▶ WARNING Running in devel mode
[1] * t_alice,test2       [test2 6s] msg for alice                                                                             
[2]   t_alice,t_bob,test2 [test2 6m] msg for alice and bob                                                                     
[songgao@Song-ThinkPad keybase]$ ./keybase chat read
▶ WARNING Running in devel mode
There are 2 conversations. Please choose one:
[1] t_alice,test2                                                                                                              
[2] t_alice,t_bob,test2                                                                                                        
Please enter a number [1-2]: 1
fetching conversation t_alice,test2 ...

[1] * [test2 13s] msg for alice                                                                                                
[2]   [test2 18m] alice                                                                                                        
[3]    [test2 2h] hi                                                                                                           

[songgao@Song-ThinkPad keybase]$
```

r? @patrickxb @mmaxim Thanks!

### CODE REVIEW

**Comment by mmaxim** [comment]
Agree with ^^

**Comment by songgao** [comment]
Good point! PTAL?

**Comment by songgao** [comment]
```
songgao at Song-ThinkPad in ~GOPATH/src/github.com/keybase/client/go/keybase (songgao/CORE-3720)
$ ./keybase chat send test
▶ WARNING Running in devel mode
There are 7 conversations. Please choose one:
[1] t_bob,t_charlie,t_doug,test2                                                                                                                                                               
[2] t_bob,t_charlie,test2                                                                                                                                                                      
[3] t_doug,test2                                                                                                                                                                               
[4] t_charlie,test2                                                                                                                                                                            
[5] t_bob,test2                                                                                                                                                                                
[6] t_alice,test2                                                                                                                                                                              
[7] t_alice,t_bob,test2                                                                                                                                                                        
Please enter a number [1-7]: 1
Send to t_bob,t_charlie,t_doug,test2 (type 'YES' to confirm): oops
▶ ERROR Not confirmed

songgao at Song-ThinkPad in ~GOPATH/src/github.com/keybase/client/go/keybase (songgao/CORE-3720)
$ ./keybase chat send test
▶ WARNING Running in devel mode
There are 7 conversations. Please choose one:
[1] t_bob,t_charlie,t_doug,test2                                                                                                                                                               
[2] t_bob,t_charlie,test2                                                                                                                                                                      
[3] t_doug,test2                                                                                                                                                                               
[4] t_charlie,test2                                                                                                                                                                            
[5] t_bob,test2                                                                                                                                                                                
[6] t_alice,test2                                                                                                                                                                              
[7] t_alice,t_bob,test2                                                                                                                                                                        
Please enter a number [1-7]: 1
Send to t_bob,t_charlie,t_doug,test2 (type 'YES' to confirm): yes
sent!
```

**Comment by patrickxb** [comment]
Nice.

Probably want a question mark:

"Send to t_bob,t_charlie,t_doug,test2? (type 'YES' to confirm):"

But LGTM

**Comment by patrickxb** [comment]
LGTM

**Pull request merged**
