### PR TITLE
Make sigchain v2 default for cryptocurrency, track, untrack, and prove links

### PR DESCRIPTION
**Pull request by joshblum**
```
$ git grep GetDefaultSigVersion | grep -v test
engine/cryptocurrency.go:21:            tmp := keybase1.SigVersion(libkb.GetDefaultSigVersion(g))
engine/prove.go:37:             tmp := keybase1.SigVersion(libkb.GetDefaultSigVersion(g))
engine/track_token.go:33:               tmp := keybase1.SigVersion(libkb.GetDefaultSigVersion(g))
engine/untrack.go:27:           arg.SigVersion = libkb.GetDefaultSigVersion(g)
libkb/kbsig.go:470:func GetDefaultSigVersion(g *GlobalContext) SigVersion {
```

### CODE REVIEW

**Comment by mlsteele** [comment]
Do we want to sprinkle some entropy into these links ala https://github.com/keybase/client/pull/11117?

**Comment by maxtaco** [comment]
Hmm, well the original intent was bandwidth-savings, but we may as well allow for future blinding.

**Comment by mlsteele** [comment]
It would be great if https://keybase.atlassian.net/browse/CORE-7510 was _deployed_ first

**Comment by joshblum** [comment]
updated w/ entropy in links @maxtaco @mlsteele ptal!

**Comment by joshblum** [comment]
also we can wait to merge until after the deploy -- just let me know when it's out

**Pull request merged**
