### PR TITLE
DZ2 Tracker fix: username on proofs -> green2; badges on avatar -> green

### PR DESCRIPTION
**Pull request by cjb**
@keybase/react-hackers @keybase/design

After:

screen shot 2016-03-11 at 1 21 41 pm

### CODE REVIEW

**Comment by cbostrander** [comment]
This looks nice Chris! I think the social icons still need to be black 75%
though and not the lighter gray. But I think you have a ticket for that
right?

[image: Inline image 1]

**Comment by cjb** [comment]
@cbostrander Cool, thanks -- I see that ticket's in the backlog now, it's not part of the current sprint though.

**Comment by cecileboucheron** [comment]
The proofs are good, but not the badges on the avatar. Badges should be green, not green 2, and top KB username should be green2 (now it's green).

**Comment by cjb** [comment]
@cecileboucheron Oops, thanks -- one more try!

screen shot 2016-03-11 at 2 51 03 pm

**Comment by MarcoPolo** [comment]
Code changes, while extremely controversial, look good! :+1:

**Comment by cecileboucheron** [comment]
Looks good! Thank you!

**Pull request merged**
