### PR TITLE
Mobile markdown

### PR DESCRIPTION
**Pull request by chromakode**
It currently doesn't appear to be possible to style text-within-text with padding or border-radius, so the inline code styling falls short of our styleguide.

In order to render block styles on mobile, the parser needed to be reorganized a bit to differentiate "text blocks" from "code blocks" and "quote blocks". Since we can't put a `<Box>` inside of a `<Text>`, treating formatting contexts as blocks allows us to render these top-level containers as styled `<Box>` components.

:eyeglasses: @keybase/react-hackers

### CODE REVIEW

**Comment by keybase-ci-visdiff** [comment]
The commits 6c7f24ede1b4...7db87a3a7708 introduce visual changes on linux. <details><summary>:mag_right: 3 changed</summary>

 * Changed: **Markdown-links** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1487376301464-6c7f24ede1b4-7db87a3a7708-linux/Markdown-links-6c7f24ede1b4.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1487376301464-6c7f24ede1b4-7db87a3a7708-linux/Markdown-links-7db87a3a7708.png)  
   Markdown-links comparison
 * Changed: **Markdown-Normal** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1487376301464-6c7f24ede1b4-7db87a3a7708-linux/Markdown-Normal-6c7f24ede1b4.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1487376301464-6c7f24ede1b4-7db87a3a7708-linux/Markdown-Normal-7db87a3a7708.png)  
   Markdown-Normal comparison
 * Changed: **Markdown-Code_block** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1487376301464-6c7f24ede1b4-7db87a3a7708-linux/Markdown-Code_block-6c7f24ede1b4.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1487376301464-6c7f24ede1b4-7db87a3a7708-linux/Markdown-Code_block-7db87a3a7708.png)  
   Markdown-Code_block comparison
</summary>

**Comment by keybase-ci-visdiff** [comment]
The commits 6c7f24ede1b4...08ddafd79612 introduce visual changes on linux. <details><summary>:mag_right: 3 changed</summary>

 * Changed: **Markdown-links** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1487376333325-6c7f24ede1b4-08ddafd79612-linux/Markdown-links-6c7f24ede1b4.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1487376333325-6c7f24ede1b4-08ddafd79612-linux/Markdown-links-08ddafd79612.png)  
   Markdown-links comparison
 * Changed: **Markdown-Normal** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1487376333325-6c7f24ede1b4-08ddafd79612-linux/Markdown-Normal-6c7f24ede1b4.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1487376333325-6c7f24ede1b4-08ddafd79612-linux/Markdown-Normal-08ddafd79612.png)  
   Markdown-Normal comparison
 * Changed: **Markdown-Code_block** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1487376333325-6c7f24ede1b4-08ddafd79612-linux/Markdown-Code_block-6c7f24ede1b4.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1487376333325-6c7f24ede1b4-08ddafd79612-linux/Markdown-Code_block-08ddafd79612.png)  
   Markdown-Code_block comparison
</summary>

**Comment by keybase-ci-visdiff** [comment]
The commits 6c7f24ede1b4...024eae807849 introduce visual changes on linux. <details><summary>:mag_right: 3 changed</summary>

 * Changed: **Markdown-links** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1487376392722-6c7f24ede1b4-024eae807849-linux/Markdown-links-6c7f24ede1b4.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1487376392722-6c7f24ede1b4-024eae807849-linux/Markdown-links-024eae807849.png)  
   Markdown-links comparison
 * Changed: **Markdown-Normal** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1487376392722-6c7f24ede1b4-024eae807849-linux/Markdown-Normal-6c7f24ede1b4.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1487376392722-6c7f24ede1b4-024eae807849-linux/Markdown-Normal-024eae807849.png)  
   Markdown-Normal comparison
 * Changed: **Markdown-Code_block** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1487376392722-6c7f24ede1b4-024eae807849-linux/Markdown-Code_block-6c7f24ede1b4.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1487376392722-6c7f24ede1b4-024eae807849-linux/Markdown-Code_block-024eae807849.png)  
   Markdown-Code_block comparison
</summary>

**Comment by chromakode** [comment]
* [] Check that this doesn't consume blank lines

**Comment by keybase-ci-visdiff** [comment]
The commits 6c7f24ede1b4...73c00a72670c introduce visual changes on linux. <details><summary>:mag_right: 1 new, 3 changed</summary>

 * Added: **Markdown-Blank_lines**  
   Markdown-Blank_lines rendered
 * Changed: **Markdown-links** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1487381951708-6c7f24ede1b4-73c00a72670c-linux/Markdown-links-6c7f24ede1b4.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1487381951708-6c7f24ede1b4-73c00a72670c-linux/Markdown-links-73c00a72670c.png)  
   Markdown-links comparison
 * Changed: **Markdown-Normal** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1487381951708-6c7f24ede1b4-73c00a72670c-linux/Markdown-Normal-6c7f24ede1b4.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1487381951708-6c7f24ede1b4-73c00a72670c-linux/Markdown-Normal-73c00a72670c.png)  
   Markdown-Normal comparison
 * Changed: **Markdown-Code_block** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1487381951708-6c7f24ede1b4-73c00a72670c-linux/Markdown-Code_block-6c7f24ede1b4.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1487381951708-6c7f24ede1b4-73c00a72670c-linux/Markdown-Code_block-73c00a72670c.png)  
   Markdown-Code_block comparison
</summary>

**Comment by keybase-ci-visdiff** [comment]
The commits 6c7f24ede1b4...49801b799973 introduce visual changes on linux. <details><summary>:mag_right: 1 new, 3 changed</summary>

 * Added: **Markdown-Blank_lines**  
   Markdown-Blank_lines rendered
 * Changed: **Markdown-links** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1487382421574-6c7f24ede1b4-49801b799973-linux/Markdown-links-6c7f24ede1b4.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1487382421574-6c7f24ede1b4-49801b799973-linux/Markdown-links-49801b799973.png)  
   Markdown-links comparison
 * Changed: **Markdown-Normal** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1487382421574-6c7f24ede1b4-49801b799973-linux/Markdown-Normal-6c7f24ede1b4.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1487382421574-6c7f24ede1b4-49801b799973-linux/Markdown-Normal-49801b799973.png)  
   Markdown-Normal comparison
 * Changed: **Markdown-Code_block** [(before)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1487382421574-6c7f24ede1b4-49801b799973-linux/Markdown-Code_block-6c7f24ede1b4.png) [(after)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1487382421574-6c7f24ede1b4-49801b799973-linux/Markdown-Code_block-49801b799973.png)  
   Markdown-Code_block comparison
</summary>

**Comment by chrisnojima** [comment]
@chromakode lost the emoji in visdiff?

**Pull request merged**
