### PR TITLE
human readable perf log

### PR DESCRIPTION
**Pull request by joshblum**
cc @chrisnojima

### CODE REVIEW

**Comment by mmaxim** [comment]
What is this for? A UI display?

**Comment by joshblum** [comment]
@mmaxim yes, some events would get plumbed to the UI for a visual indication of what is happening

**Comment by mmaxim** [comment]
Might have been nice to integrate this with the runtime stats thing that is in there, could have a UI ready to go.

**Comment by joshblum** [comment]
I think @chrisnojima was planning to re-use where the runtime stats are displayed with this info

**Comment by mmaxim** [comment]
Sure, I think it makes sense to just plumb these events internally into that Go code, and then have it flow up through the existing notification.

**Comment by mmaxim** [comment]
We should talk more about this in person, I am skeptical its going to yield anything in the UI that is useful.

**Comment by joshblum** [comment]
@mmaxim this is ready

**Pull request merged**
