### PR TITLE
surya/core 5625/userorteamid validation

### PR DESCRIPTION
**Pull request by modalduality**
Some discussion regarding using `IsUser` and related:

Current behavior is to return True if it is a valid user ID, False if anything else, including invalid ID.
This runs into issues with if/else statement code like in teams/proofs.go:
```
if p.a.leafID.IsUser() {
    ret = leaf.Public
} else {
    ret = leaf.Private
}
```
which is not quite correct in the case that leafID happens to be invalid. I went through a few different ideas on what IsUser should return with Jack but that cleanest seemed to be that we should make some sort of enum VariantID(UID(...) | TeamID(...) |SubteamID(...)), and immediately parse a server's UserOrTeamID into a VariantID before it goes anywhere else. Then we don't have to worry about any potential errors or cornercases later on. Thoughts?

cc @oconnor663 @patrickxb

### CODE REVIEW

**Comment by maxtaco** [comment]
Doesn't compile. Also, can you fix `GetShard`? Thx

**Comment by maxtaco** [comment]
@modalduality did you have a fix for `GetShard`?  If so, ready to approve this PR once that's done.

**Comment by modalduality** [comment]
https://github.com/keybase/client/pull/7699/files#diff-77a916effb7c2a53cc526b18d3c74361R1283

This just does a check to see if it's any Valid ID, but it's pretty fragile without enums in the case that someone adds a new type of ID.

**Comment by maxtaco** [comment]
ok great, thanks!

**Comment by maxtaco** [comment]
wait @modalduality where is that commit?

**Comment by maxtaco** [comment]
oh there it is

**Pull request merged**
