### PR TITLE
workaround shutdown deadlock in rekey

### PR DESCRIPTION
**Pull request by maxtaco**
r? @patrickxb

### CODE REVIEW

**Comment by patrickxb** [comment]
The other option would be to make interruptCh buffered.

**Comment by maxtaco** [comment]
I thought about that, but that will likely require changing all of the tests.

**Comment by patrickxb** [comment]
Ok, LGTM then.

**Comment by maxtaco** [comment]
To be a little less flip, we don't need everything to be async (which buffering would achieve), just these two interrupts, since they're the only two that I think might deadlock the rekey loop.

**Pull request merged**
