### PR TITLE
Remove notification that startup failed and send log

### PR DESCRIPTION
**Pull request by MarcoPolo**
@keybase/react-hackers 

This was firing quite often, so let's remove this.

### CODE REVIEW

**Comment by cjb** [comment]
@MarcoPolo Do you think it's just a race, where the GUI might start up just before the service is listening?

**Comment by MarcoPolo** [comment]
That might be one case. That one has been handled by reconnecting. Although it shouldn't be firing messages until it has a connection to the service, righ?

Another case is when you start up while disconnected from the internet. Making a network request that the service needs fail, so `getConfig` fails. That is handled by redoing startup when we get internet.

There also seems to be a timeout error from the service, we currently aren't handling that, I'll make a ticket.

**Comment by cjb** [comment]
> That one has been handled by reconnecting. 

But does the error path fire before we successfully reconnect?

**Comment by cjb** [comment]
Well, either way, :thumbsup:

**Pull request merged**
