### PR TITLE
update go-ps

### PR DESCRIPTION
**Pull request by zanderz**
@taruti

### CODE REVIEW

**Comment by keybase-ci-visdiff** [comment]
:mag_right: The commits 6fd1b8714510...1bceaa4b28ef introduced some visual changes on linux:
 * Changed: **unlock_folders-Success** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468255477638-6fd1b8714510-1bceaa4b28ef-linux/unlock_folders-Success-6fd1b8714510.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468255477638-6fd1b8714510-1bceaa4b28ef-linux/unlock_folders-Success-1bceaa4b28ef.png)  
   unlock_folders-Success comparison

**Comment by keybase-ci-visdiff** [comment]
:mag_right: The commits d2ac63bfe8c1...46130cd5b845 introduced some visual changes on win32:
 * Changed: **Username_Email_Login-Name_Error** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468262336258-d2ac63bfe8c1-46130cd5b845-win32/Username_Email_Login-Name_Error-d2ac63bfe8c1.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468262336258-d2ac63bfe8c1-46130cd5b845-win32/Username_Email_Login-Name_Error-46130cd5b845.png)  
   Username_Email_Login-Name_Error comparison
 * Changed: **unlock_folders-Single** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1468262336258-d2ac63bfe8c1-46130cd5b845-win32/unlock_folders-Single-d2ac63bfe8c1.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1468262336258-d2ac63bfe8c1-46130cd5b845-win32/unlock_folders-Single-46130cd5b845.png)  
   unlock_folders-Single comparison

**Comment by taruti** [comment]
This is missing a git add after go vendor?

**Comment by taruti** [comment]
LGTM after CI passes.

**Pull request merged**
