### PR TITLE
Add listener for logUi.log method

### PR DESCRIPTION
**Pull request by MarcoPolo**
@keybase/react-hackers

### CODE REVIEW

**Comment by chrisnojima** [comment]
in addition we should add it to incomingMaps for all rpcs in case you don't handle it for a back and forth service call. we can just inject it in engine.js

**Comment by MarcoPolo** [comment]
What if we make a call map middleware that one can apply to a call map? I'm just a bit hesitant in mutating all call maps.

It could live here alongside the other call-map-middlewares: https://github.com/keybase/client/blob/master/react-native/react/engine/call-map-middleware.js

**Comment by chrisnojima** [comment]
My thinkig it was just a default one that would be overridden if you set one, its just a fallback

**Comment by MarcoPolo** [comment]
Sounds good, I added it

**Comment by chrisnojima** [comment]
:+1:

**Pull request merged**
