### PR TITLE
Nav2 Provisioning

### PR DESCRIPTION
**Pull request by MarcoPolo**
@keybase/react-hackers Upgrades login flows to support the new nav model.

Adds support for `customOnBack` in navigation param which will be used when supplied instead of the default onBack in headers.

I needed this customOnBack because just going back one level is broken in the login flow, it's only really valid to go all the way back to the start.

todo (in another PR maybe?)
- [ ] Cancel provision rpc when the user goes back (it works fine without this, but might be nice to clean things up)

### CODE REVIEW

**Comment by chrisnojima** [comment]
I didn't look at the code but I think for floes like this we want a replace vs a push

**Comment by MarcoPolo** [comment]
O interesting. That makes sense, I'll change that now

**Comment by MarcoPolo** [comment]
@chrisnojima updated

**Comment by chrisnojima** [comment]
We should make a routetree actiknfor replace. Or add a flag to append

**Comment by MarcoPolo** [comment]
I thought the goal was to remove routetree stuff eventually?

**Comment by MarcoPolo** [comment]
And remove the idea of us dispatching to affect navigation

**Comment by chrisnojima** [comment]
Eventually but short term we'll have actions that will affect nav. Longer term maybe all the actions go away. More likely the api will shrink. While we support both it makes sense to support the old actions but when we deprecate that system we can type it better and drop old concepts (like parent path and arrays in path)

**Comment by chrisnojima** [comment]
Either way we should dispatch some action instead of using _getnavigator in sagas

**Comment by chrisnojima** [comment]
i made a getRouteProps helper in util/container that we can use

**Comment by MarcoPolo** [comment]
Killing this in favor of the single PR

**Pull request closed without merging**
