### PR TITLE
avoid the ComputedKeyInfo.KID field

### PR DESCRIPTION
**Pull request by oconnor663**
It looks like the KID in the Info struct can be empty. Avoid using it as
a workaround, though I'm not sure yet why it's happening. It looks like
my own chain links are getting unmarshalled from the chain links cache
with these KIDs already empty.

r? @maxtaco

### CODE REVIEW

**Comment by maxtaco** [comment]
Thanks Jacko. Leaving for a bit so need to review on mobile if at all.  Qq:
is there a test that could catch this bug? Seems like a simple one from
your description.

**Comment by oconnor663** [comment]
We could also consider putting repair code for this in the chain link unpacking code?

**Comment by oconnor663** [comment]
I'm unable to repro after I nuke my own cache. It's possible that the bug that got bad data into our chain link caches isn't around anymore? But I could definitely add more checks during export to make sure there aren't any empty kids ending up in the output?

**Comment by maxtaco** [comment]
I think I recently added that field come to think of it. Let's discuss on Monday.

**Comment by oconnor663** [comment]
Oh yes, that's totally it. Any cached chain link from before June 7 is going to have an empty KID field in all of its computed key infos. https://keybase.slack.com/archives/C1WGAFMBM/p1498328539146077 I reviewed that code too :p

**Pull request merged**
