### PR TITLE
change text of success screen. send rpc on closing window

### PR DESCRIPTION
**Pull request by chrisnojima**
@keybase/react-hackers 
@maxtaco this fixes CORE-3320

### CODE REVIEW

**Comment by keybase-ci-visdiff** [comment]
:mag_right: The commits 56aad2dcff2e...b30b079abb86 introduced some visual changes on linux:
 * Changed: **unlock_folders-Success** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1467731044075-56aad2dcff2e-b30b079abb86-linux/unlock_folders-Success-56aad2dcff2e.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1467731044075-56aad2dcff2e-b30b079abb86-linux/unlock_folders-Success-b30b079abb86.png)  
   unlock_folders-Success comparison

**Comment by keybase-ci-visdiff** [comment]
:mag_right: The commits 379a4de8554f...c34ccf64b188 introduced some visual changes on linux:
 * Changed: **unlock_folders-Success** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1467731604254-379a4de8554f-c34ccf64b188-linux/unlock_folders-Success-379a4de8554f.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1467731604254-379a4de8554f-c34ccf64b188-linux/unlock_folders-Success-c34ccf64b188.png)  
   unlock_folders-Success comparison

**Comment by chrisnojima** [comment]
@malgorithms this ok? https://keybase-app-visdiff.s3.amazonaws.com/1467731044075-56aad2dcff2e-b30b079abb86-linux/unlock_folders-Success-b30b079abb86.png

**Comment by malgorithms** [comment]
looks great to me, although "check back in a bit" is a bit vague - where should they be checking?

Maybe it should say

```
Success!
Your paper key is now rekeying folders for this computer.
It takes just a couple minutes but lasts forever, like the decision to have a child.
```

**Comment by chromakode** [comment]
:+1:

**Comment by chrisnojima** [comment]
retest this please

**Comment by keybase-ci-visdiff** [comment]
:mag_right: The commits f39d5099ef39...558c6693c532 introduced some visual changes on linux:
 * Changed: **unlock_folders-Success** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1467818422943-f39d5099ef39-558c6693c532-linux/unlock_folders-Success-f39d5099ef39.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1467818422943-f39d5099ef39-558c6693c532-linux/unlock_folders-Success-558c6693c532.png)  
   unlock_folders-Success comparison

**Pull request merged**
