### PR TITLE
Process conversation update status changes

### PR DESCRIPTION
**Pull request by jakob223**
Which will be sent by the server when you block a conversation.

cc @keybase/y2ksquad

### CODE REVIEW

**Comment by jakob223** [comment]
first commit is already merged, this PR is about the second one.

**Comment by mmaxim** [comment]
Couple things:

1.) As mentioned to @joshblum, should use the existing `SetStatus` method on `Inbox`.
2.) That new RPC should be in the chat protocol, not gregor.

**Comment by zapu** [comment]
cc @maxtaco we wanted the server to drive the blocking, so you'd just call one API: SetBlocks, and it will deal with everything

**Comment by mmaxim** [comment]
Is that a reply to me?

**Comment by zapu** [comment]
Yes. Maybe I'm misunderstanding the comment about using SetStatus on Inbox. The original intent here was that the client shouldn't be worrying about this.

**Comment by mmaxim** [comment]
This PR is the client's response of removing the conversations from the inbox display. It has to care about it, I am saying they should use an existing function in there instead of modifying the one they did.

**Pull request closed without merging**
