### PR TITLE
dont throttle desktop store updates anymore

### PR DESCRIPTION
**Pull request by chrisnojima**
@keybase/react-hackers this is a kind of scary change but i think we should do it.
if you have an existing chat and do a new conversation to that same person when you send to it it should select the new convo immediately. instead you see the new convo screen flash quickly. i think this is due to a race w/ the store updating / mapStateToProps not updating at the right time.
By changing the throttle this problem goes away. This makes it match what native does

### CODE REVIEW

**Comment by chrisnojima** [comment]
@keybase/react-hackers this affects things globally but we should likely get this in sooner rather than later

**Comment by chrisnojima** [comment]
- [ ] merge after release

**Comment by chrisnojima** [comment]
@keybase/react-hackers bump

**Comment by mmaxim** [comment]
Can we merge this? I get the flicker behavior on desktop a lot, would be nice to see if this fixes it.

**Comment by chrisnojima** [comment]
Was just waiting for the desktop release and ci is weird on this pr

**Pull request merged**
