### PR TITLE
use the right function for validation for team names

### PR DESCRIPTION
**Pull request by mmaxim**
@keybase/react-hackers 

We need to get this into the hotfix, otherwise it is not possible to create subteams.

### CODE REVIEW

**Comment by buoyad** [comment]
Using that function was deliberate, you can still crate sub teams via `create subteam` in the team page

**Comment by mmaxim** [comment]
Yeah I just came to this realization, this seems like a mistake though. 

cc @cecileboucheron @malgorithms what is the logic behind just straight blocking creating subteams with their full names? Is it because we didn't know how to make a good error message? Seems off to me.

**Comment by mmaxim** [comment]
Like don't these subteams look like something I might be able to create by clicking that button?

image

**Comment by buoyad** [comment]
Iirc the dialog became this way because of a ticket from a user trying to create a team named after a domain ‘something.io’ and getting an error ‘root team does not exist’.

**Comment by mmaxim** [comment]
I think a neat way to do this would be as soon as the user types a `.` it switches to the subteam dialog.

**Comment by malgorithms** [comment]
yeah, agreed about the errors.  what I'm seeing in the app right now doesn't really make sense. I think I'm ok with either thing:

- allowing subteam creation with fully qualified names from the top level, but clear errors when you try to put in foobar.com
- not allowing subteam creation from the top level, and rather only from inside a team, but a clear error message that says that.

whatever we choose, the user needs to understand why what they tried didn't work. Right now it gives a message about legal characters, even though the bad one they typed is right below in the list, like mike says.

**Pull request closed without merging**
