### PR TITLE
Darken inbox background.

### PR DESCRIPTION
**Pull request by adamjspooner**
@keybase/react-hackers, this is ready for review. This darkens the inbox's background (and hover states) so we can remove the border between the inbox and the thread.

cc @cecileboucheron

### CODE REVIEW

**Comment by adamjspooner** [comment]
Thanks, @jzila! Will do. I won't merge this until Cécile has time to offer some feedback too.

**Comment by adamjspooner** [comment]
I think I'm sold. I've been using this since yesterday and really like it.

**Comment by cecileboucheron** [comment]
Hmm it looks a bit dark and very blue to me, I think a tone somewhere in between and less saturated would work best? We can create a new "lightGreyBlue" tone maybe. So we can keep blue4 as the hover state.

Also one thing, we should re-export the shh and the lock icons with the new colors:
image
image

**Comment by cecileboucheron** [comment]
I like what Jira does for instance:
image

**Comment by adamjspooner** [comment]
Works for me! I just went with the colors we already have.

**Comment by adamjspooner** [comment]
The only problem I foresee is that `blue4` will be too faint for a discernible hover state.

**Comment by cecileboucheron** [comment]
@adamjspooner ^ What do you think?

**Comment by adamjspooner** [comment]
The contrast between the inbox and thread is really nice. I think the inbox hover state is too faint. Otherwise, I'm going to use this today and see if it grows on me.

**Comment by cecileboucheron** [comment]
@adamjspooner I ended up creating a new `blue6` color for the inbox hover. Let me know what you think.

**Comment by cecileboucheron** [comment]
@adamjspooner In the end I'm creating 2 new swatches: greyBlue1 and greyBlue2, it's simpler. I updated the wallet tab with these 2 colors as well (and removed the right border there too). 
We could update the Settings page as well with the same coloring in the left pane some time.

**Comment by cecileboucheron** [comment]
@keybase/react-hackers ok ready for review!

**Comment by cecileboucheron** [comment]
@jzila Mind taking another look?

**Pull request merged**
