### PR TITLE
Refactor part 5 - redux-saga typing

### PR DESCRIPTION
**Pull request by chrisnojima**
Should fix issues w/ select/call/all/etc

### CODE REVIEW

**Comment by chrisnojima** [comment]
@keybase/react-hackers

**Comment by patrickxb** [comment]
I can't find the comment, but yes we should fix session -> sessionID.

**Comment by patrickxb** [comment]
(in the avdl file)

**Comment by patrickxb** [comment]
Fix is here: https://github.com/keybase/client/pull/9414

**Comment by chrisnojima** [comment]
reopening against gen-1
https://github.com/keybase/client/pull/9416

**Pull request closed without merging**
