### PR TITLE
Test adding etime with no max uses

### PR DESCRIPTION
**Pull request by zapu**
should this be possible in sigchain player?

server blocks it

### CODE REVIEW

**Comment by heronhaye** [comment]
Probably not

**Comment by zapu** [comment]
still good to have this check to ensure it stays not erroring

**Comment by zapu** [comment]
note to self, this will break `TestTeamPlayerBadUsedInvites` test

**Comment by zapu** [comment]
OK let's allow this for now but add more tests and a note in a comment.

**Pull request merged**
