### PR TITLE
Allow install/uninstall to work for staging/devel

### PR DESCRIPTION
**Pull request by gabriel**
I put in things to prevent install for staging and devel but it's really useful, so this make install work for those run modes.

I do disable `log send` for staging and devel because we used fixed log paths for that. And also might be confusing to get log sends for non-prod environments.

@patrickxb

### CODE REVIEW

**Comment by keybase-ci-visdiff** [comment]
:mag_right: The commits a9d56a0fba7a...88460367d425 introduced some visual changes on linux:
 * Changed: **unlock_folders-Success** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1467766010964-a9d56a0fba7a-88460367d425-linux/unlock_folders-Success-a9d56a0fba7a.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1467766010964-a9d56a0fba7a-88460367d425-linux/unlock_folders-Success-88460367d425.png)  
   unlock_folders-Success comparison

**Comment by patrickxb** [comment]
I think log send useful in stage, devel. It goes to staging, devel API servers so it's not confusing.

**Comment by gabriel** [comment]
ok yeah, took out that log send check, it works in staging and devel

**Comment by patrickxb** [comment]
Cool, LGTM

**Pull request merged**
