### PR TITLE
fix "update now"; show "Updating ..."; check again after update

### PR DESCRIPTION
**Pull request by songgao**
The "check again" part is because user could hit "Ignore", and nothing would get updated. In this case we should not show the out-of-date banner any more. So ask service again and eventually update the store to reflect the fact that no update is needed anymore.

Tagging @keybase/kbfs-hackers for the first commit in Go, and @keybase/react-hackers for the second commit in GUI.

### CODE REVIEW

**Comment by chrisnojima** [comment]
I don't think this is how this should work. If there's an update we should show it. If they ignore we should let them override the snooze

**Comment by mmaxim** [comment]
Agree, I'm not sure why this snooze can't be overridden, but we should change it. I feel like it should only affect the auto updating aspect of the updater, but if I hit `keybase update check` or this out of date banner I should get the update regardless of my snooze state.

**Comment by songgao** [comment]
There's `KEYBASE_UPDATER_FORCE` env var but I don't think it differentiates snoozed update or real update. This is server controlled. I don't know where the code is but can try to dig out.

We can add a parameter for this banner as well as the `keybase update check` CLI so it ignores the snooze in these places, but still have the auto updater (if it's enabled) follow the snooze.

**Comment by mmaxim** [comment]
Yeah I know the server controls it, maybe @maxtaco can you point us in the right direction.

**Comment by songgao** [comment]
Cool thanks. I'm closing this PR so people don't start reviewing it. Will put it up again when it's ready!

**Pull request closed without merging**
