### PR TITLE
Link to the profile url if they click username or icon.

### PR DESCRIPTION
**Pull request by MarcoPolo**
Also implements the logic to convert into the profile url.
@keybase/react-hackers

### CODE REVIEW

**Comment by chrisnojima** [comment]
Does web work? Name is the name of the file?

**Comment by MarcoPolo** [comment]
web works. name and key are different depending on what the type is. When the type is web, name is the domain (i.e. `keybase.io`) and key is either `http` or `https`.

I tested against a couple users (max included) and everything works except dns. (Looking at web now at it looks like dns works, maybe I can add that)

**Comment by chrisnojima** [comment]
:+1:

**Comment by MarcoPolo** [comment]
DNS works now same logic as web :)

**Pull request merged**
