### PR TITLE
Early exit on error in loadPayments

### PR DESCRIPTION
**Pull request by akalin-keybase**
This fixes a red box on mobile (dev).

Also remove now-unneeded debug logging.

### CODE REVIEW

**Comment by akalin-keybase** [comment]
cc @buoyad who added this debug logging

**Comment by akalin-keybase** [comment]
Forgot to mention how I ran into this: just trying to link an already linked account on mobile.

**Comment by patrickxb** [comment]
that empty account stuff should be fixed, so feel free to remove anything you added in frontend trying to help figure that out.

**Comment by akalin-keybase** [comment]
Okay, removed that logging code

**Pull request merged**
