### PR TITLE
Handle opening folders from search

### PR DESCRIPTION
**Pull request by MarcoPolo**
@keybase/react-hackers 

This opens folders in search user group view.

Also handles the case where you type something in the search box, then click a service (it should search that thing on that service for you)

### CODE REVIEW

**Comment by keybase-ci-visdiff** [comment]
:mag_right: The commits 4d28183cf132...0c57b0e3eb7f introduced some visual changes on win32:
 * Changed: **user_group-Chat_enabled** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1467069876269-4d28183cf132-0c57b0e3eb7f-win32/user_group-Chat_enabled-4d28183cf132.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1467069876269-4d28183cf132-0c57b0e3eb7f-win32/user_group-Chat_enabled-0c57b0e3eb7f.png)  
   user_group-Chat_enabled comparison

**Comment by keybase-ci-visdiff** [comment]
:mag_right: The commits 4d28183cf132...0c57b0e3eb7f introduced some visual changes on linux:
 * Changed: **user_group-Chat_enabled** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1467069888606-4d28183cf132-0c57b0e3eb7f-linux/user_group-Chat_enabled-4d28183cf132.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1467069888606-4d28183cf132-0c57b0e3eb7f-linux/user_group-Chat_enabled-0c57b0e3eb7f.png)  
   user_group-Chat_enabled comparison

**Comment by awendland** [comment]
If I click "GitHub" then "Reddit", and the "Reddit" search returns first, then the "GitHub" results, will I be in a state where the results list shows "GitHub" but my selected tab is "Reddit"?

**Comment by MarcoPolo** [comment]
Probably, that should be fixed by the same logic that shows the latest search results in a debounced search input

**Comment by awendland** [comment]
:+1:

**Comment by keybase-ci-visdiff** [comment]
:mag_right: The commits d5ba28f8c33f...c52a394a28cf introduced some visual changes on win32:
 * Changed: **user_group-Chat_enabled** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1467140968393-d5ba28f8c33f-c52a394a28cf-win32/user_group-Chat_enabled-d5ba28f8c33f.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1467140968393-d5ba28f8c33f-c52a394a28cf-win32/user_group-Chat_enabled-c52a394a28cf.png)  
   user_group-Chat_enabled comparison

**Comment by keybase-ci-visdiff** [comment]
:mag_right: The commits fa3d944539a0...ecfb0f7fae40 introduced some visual changes on linux:
 * Changed: **user_group-Chat_enabled** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1467145708437-fa3d944539a0-ecfb0f7fae40-linux/user_group-Chat_enabled-fa3d944539a0.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1467145708437-fa3d944539a0-ecfb0f7fae40-linux/user_group-Chat_enabled-ecfb0f7fae40.png)  
   user_group-Chat_enabled comparison

**Comment by keybase-ci-visdiff** [comment]
:mag_right: The commits fa3d944539a0...ecfb0f7fae40 introduced some visual changes on win32:
 * Changed: **user_group-Chat_enabled** [(before)](https://keybase-app-visdiff.s3.amazonaws.com/1467147651238-fa3d944539a0-ecfb0f7fae40-win32/user_group-Chat_enabled-fa3d944539a0.png) [(after)](https://keybase-app-visdiff.s3.amazonaws.com/1467147651238-fa3d944539a0-ecfb0f7fae40-win32/user_group-Chat_enabled-ecfb0f7fae40.png)  
   user_group-Chat_enabled comparison

**Pull request merged**
