### PR TITLE
Retry KBFSTLFInfoSource.Lookup

### PR DESCRIPTION
**Pull request by patrickxb**
To fix the rekey race in CORE-5231

### CODE REVIEW

**Comment by mmaxim** [comment]
I thought this was going to be specifically reacting to that bad key error?

**Comment by patrickxb** [comment]
I thought the error type was untyped, but I was wrong.  Pushed a fix.

**Comment by mmaxim** [comment]
Also, is backoff worth it here? It seems like all you really want is a maximum amount of time you want to get stuck here retrying, and then divide is up evenly?

**Comment by patrickxb** [comment]
Ok, PTAL

**Comment by mmaxim** [comment]
Is 1 second total retry time enough?

**Pull request merged**
