### PR TITLE
Reorder Services

### PR DESCRIPTION
**Pull request by MarcoPolo**
Ordering is important here.
@keybase/react-hackers

### CODE REVIEW

**Comment by chrisnojima** [comment]
Maybe better to just have an array you reduce to make this

**Comment by MarcoPolo** [comment]
I thought it had to be an object so that we could have a type on the keys? `export type ServiceIdWithContact = $Keys<typeof _services>` Let me check if we can do something similar with an array

**Comment by chrisnojima** [comment]
Oh yeah. But maybe it's not derived. Just a regular type. Then the const can be typed as array of that type

**Comment by MarcoPolo** [comment]
Lol, I'm pretty sure that's what it was at some point...
ah here it is: https://github.com/keybase/client/pull/13486/files/58c7b62932af774b69d115579bd4e1e2cf7908fc#r221350024

**Comment by chrisnojima** [comment]
I guess I'm a little worried about it getting broken again

**Comment by MarcoPolo** [comment]
yep, that's reasonable. I'll switch it to an ordered array

**Comment by chrisnojima** [comment]
https://flow.org/en/docs/types/generics/#toc-adding-types-to-generics

**Comment by MarcoPolo** [comment]
yeah, but nothing effectively changed about the code. This is likely the correct behavior, and there was some bug edge case when using $Keys<...>

**Pull request merged**
