### PR TITLE
Put userInfoMapper in request context

### PR DESCRIPTION
**Pull request by patrickxb**
The chat_local service handler uses userInfoMapper to avoid loading users, devices repeatedly.  

This PR puts it in the request context so that one userInfoMapper is used for the entire request.  Before it was possible for there to be several.  Also, the verifying of the sender's signing key was calling LoadUser and now it uses the userInfoMapper.

With this change, the number of LoadUser calls is drastically reduced.

### CODE REVIEW

**Comment by patrickxb** [comment]
@mmaxim @oconnor663 too

**Comment by mmaxim** [comment]
So this was the only thing slowing it down? I guess that makes sense since we weren't doing any identifies in the common case.

**Comment by patrickxb** [comment]
This was the big one.  I'm sure there's more to be done, but I was getting close to the 3pts.

**Comment by maxtaco** [comment]
Does the map in the cache need synchronization?

**Comment by patrickxb** [comment]
Not currently.

**Pull request merged**
