### PR TITLE
Use KBFuse 3.4.0

### PR DESCRIPTION
**Pull request by gabriel**
- Update to use branded osxfuse 3.4.0 to support Sierra
- Fix permissions bug for load_kbfuse (in Sierra)
- New helper 1.0.28
- New installer 1.0.32

The permissions issue, I fixed by using chmod function call instead of NSFileManager setAttributes. It seems like Cocoa in Sierra no longer supports changing suid permissions with NSFileManager (maybe for security reasons)? Or maybe just a bug.

Because there is a new helper tool, users who upgrade to this will have to enter their (admin) password.

### CODE REVIEW

**Comment by gabriel** [comment]
@keybase/react-hackers @patrickxb

**Comment by patrickxb** [comment]
LGTM

**Comment by gabriel** [comment]
@strib Are we ok using osxfuse 3.4.0? 

In my testing locally, seems to be working great

**Comment by strib** [comment]
If it passes KBFS CI on OS X, I'm good with it.  (I don't know how Jenkins installs osxfuse, but presumably you need to explicitly tell it what to install when it runs the tests?)

**Comment by gabriel** [comment]
@jzila how hard to update to use kbfuse or osxfuse 3.4.0 on jenkins machines? See https://keybase.atlassian.net/browse/KBFS-1291

**Comment by cjb** [comment]
@gabriel If we think this is going to work, I'd say just push it into master and CI will test it as an admin build for a few days before it goes public, what do you think?

**Pull request merged**
