### PR TITLE
Tweak username HeaderBig padding

### PR DESCRIPTION
**Pull request by cjb**
@keybase/react-hackers 

Before:

device-2017-03-07-132708

After:

device-2017-03-07-133213

### CODE REVIEW

**Comment by chrisnojima** [comment]
There's problems with text in general right, so maybe we close this specific one and fix it generally?

**Comment by chromakode** [comment]
Can this be closed in light of https://github.com/keybase/client/pull/6273?

**Comment by chromakode** [comment]
@cjb bump!

**Comment by cjb** [comment]
@chromakode Yep it can!

**Pull request closed without merging**
