### PR TITLE
Improve visdiff error handling

### PR DESCRIPTION
**Pull request by chromakode**
See a demo below. The last commit will be removed prior to merging.

:eyeglasses: @keybase/react-hackers

### CODE REVIEW

**Comment by keybase-ci-visdiff** [comment]
The commits 34227b3c1ae2...925224a31ff4 introduce visual changes on linux. <details><summary>:mag_right: </summary>

 * :no_entry: <span style="color:red">ERROR</span>: **Chat_Banner-Invite-ERROR**  
   Chat_Banner-Invite-ERROR rendered
 * :no_entry: <span style="color:red">ERROR</span>: **Chat_Banner-Info-ERROR**  
   Chat_Banner-Info-ERROR rendered
 * :no_entry: <span style="color:red">ERROR</span>: **Chat_Banner-Error-ERROR**  
   Chat_Banner-Error-ERROR rendered
 * :no_entry: <span style="color:red">ERROR</span>: **Chat_Banner-Broken_Tracker_3-ERROR**  
   Chat_Banner-Broken_Tracker_3-ERROR rendered
 * :no_entry: <span style="color:red">ERROR</span>: **Chat_Banner-Broken_Tracker_2-ERROR**  
   Chat_Banner-Broken_Tracker_2-ERROR rendered
 * :no_entry: <span style="color:red">ERROR</span>: **Chat_Banner-Broken_Tracker_1-ERROR**  
   Chat_Banner-Broken_Tracker_1-ERROR rendered
</summary>

**Comment by keybase-ci-visdiff** [comment]
The commits 34227b3c1ae2...1e57db605694 introduce visual changes on linux. <details><summary>:mag_right: 6 errored</summary>

 * :no_entry: Error: **Chat_Banner-Invite-ERROR**  
   Chat_Banner-Invite-ERROR rendered
 * :no_entry: Error: **Chat_Banner-Info-ERROR**  
   Chat_Banner-Info-ERROR rendered
 * :no_entry: Error: **Chat_Banner-Error-ERROR**  
   Chat_Banner-Error-ERROR rendered
 * :no_entry: Error: **Chat_Banner-Broken_Tracker_3-ERROR**  
   Chat_Banner-Broken_Tracker_3-ERROR rendered
 * :no_entry: Error: **Chat_Banner-Broken_Tracker_2-ERROR**  
   Chat_Banner-Broken_Tracker_2-ERROR rendered
 * :no_entry: Error: **Chat_Banner-Broken_Tracker_1-ERROR**  
   Chat_Banner-Broken_Tracker_1-ERROR rendered
</summary>

**Comment by keybase-ci-visdiff** [comment]
Error rendering the commits 34227b3c1ae2...ae76fe73872a on linux. <details><summary>:mag_right: 6 errored</summary>

 * :no_entry: Error: **Chat_Banner-Invite-ERROR**  
   Chat_Banner-Invite-ERROR rendered
 * :no_entry: Error: **Chat_Banner-Info-ERROR**  
   Chat_Banner-Info-ERROR rendered
 * :no_entry: Error: **Chat_Banner-Error-ERROR**  
   Chat_Banner-Error-ERROR rendered
 * :no_entry: Error: **Chat_Banner-Broken_Tracker_3-ERROR**  
   Chat_Banner-Broken_Tracker_3-ERROR rendered
 * :no_entry: Error: **Chat_Banner-Broken_Tracker_2-ERROR**  
   Chat_Banner-Broken_Tracker_2-ERROR rendered
 * :no_entry: Error: **Chat_Banner-Broken_Tracker_1-ERROR**  
   Chat_Banner-Broken_Tracker_1-ERROR rendered
</summary>

**Comment by keybase-ci-visdiff** [comment]
Error rendering the commits 34227b3c1ae2...e0a7d1dc935b on linux. <details><summary>:mag_right: 6 errored</summary>

 * :no_entry: Error: **Chat_Banner-Invite-ERROR**  
   Chat_Banner-Invite-ERROR rendered
 * :no_entry: Error: **Chat_Banner-Info-ERROR**  
   Chat_Banner-Info-ERROR rendered
 * :no_entry: Error: **Chat_Banner-Error-ERROR**  
   Chat_Banner-Error-ERROR rendered
 * :no_entry: Error: **Chat_Banner-Broken_Tracker_3-ERROR**  
   Chat_Banner-Broken_Tracker_3-ERROR rendered
 * :no_entry: Error: **Chat_Banner-Broken_Tracker_2-ERROR**  
   Chat_Banner-Broken_Tracker_2-ERROR rendered
 * :no_entry: Error: **Chat_Banner-Broken_Tracker_1-ERROR**  
   Chat_Banner-Broken_Tracker_1-ERROR rendered
</summary>

**Comment by keybase-ci-visdiff** [comment]
:no_entry: Error rendering the commits 9b5d5e8dca1b...fa078138ae26 on linux. <details><summary>:mag_right: 1 errored, 1 removed</summary>

 * Error: **Chat_Banner-Info-ERROR**  
   Chat_Banner-Info-ERROR rendered
 * Removed: **Chat_Banner-Info** [(view original)](https://keybase-jenkins-visdiff.s3.amazonaws.com/1490919211885-9b5d5e8dca1b-fa078138ae26-linux/Chat_Banner-Info-9b5d5e8dca1b.png)
</summary>

**Comment by keybase-ci-visdiff** [comment]
:no_entry: Error rendering the commits db39797acf40...aacb2eb7bfbe on linux. <details><summary>:mag_right: 1 errored</summary>

 * Error in aacb2eb7bfbe: **Chat_Banner-Info-ERROR**  
   Chat_Banner-Info-ERROR rendered
</summary>

**Comment by cjb** [comment]
So good!

**Pull request merged**
