### PR TITLE
Windows pinentry fix desktop 991

### PR DESCRIPTION
**Pull request by MarcoPolo**
@keybase/react-hackers 

On Windows, when booting, we get to the code path that calls `.show()` on the pinentry window before Windows lets us actually show windows, so the call to `.show()` fails.

`isVisible` is correct though, so this creates a new function that will call `.show` every `delay` ms, and stop after the window is visible.

We use that new function on windows to make sure the pinentry (and any other remote components) get shown properly on startup.

@zanderz

### CODE REVIEW

**Comment by zanderz** [comment]
Too bad show() doesn't have a useful return value.
LGTM :thumbsup:

**Comment by chrisnojima** [comment]
Should we have a max number of loops or go forever

**Comment by zanderz** [comment]
I think forever is fine, like if the machine boots and the person doesn't log in for an hour - just in case that is one of the cases that reveals this problem, etc.

**Comment by cjb** [comment]
Could we open an Electron issue to see if this is expected? Just starting to see it recently is suspicious.

**Comment by MarcoPolo** [comment]
@cjb I don't think this is a recent thing, I just don't think we've really tested reboot cases, am I wrong @zanderz ?

**Comment by zanderz** [comment]
You are not wrong @MarcoPolo

**Comment by cjb** [comment]
I reboot my Windows PC every few days and it's never failed to show pinentry. We can at least ask them whether they expect this to be necessary. It should probably be in the docs somewhere.

**Comment by zanderz** [comment]
Are you logged in when you do so? This seems to specifically be the unlock
prompt, FWIW.

When the window is showing normally, this hack won't have any effect
anyway, right?

**Comment by cjb** [comment]
The one I see every time is the KBFS unlock prompt.

**Comment by MarcoPolo** [comment]
@cjb Issue here: #5384

**Comment by MarcoPolo** [comment]
I got a 👍 from @chrisnojima on slack

**Pull request merged**
