### PR TITLE
a simple idea for never blocking on ui.Log() in critical log loop

### PR DESCRIPTION
**Pull request by maxtaco**

### CODE REVIEW

**Comment by maxtaco** [comment]
@patrickxb what do you think?

**Comment by patrickxb** [comment]
I don't think this is necessary if shutdown changes to just close the channel.

But happy to add this if we want to leave the wait mechanism in place.

**Comment by maxtaco** [comment]
Is there a concern that some log lines will be dropped on shutdown? I was
guessing that motivated the current architecture.

**Comment by maxtaco** [comment]
let's chat via perch when you get in.

**Comment by patrickxb** [comment]
@maxtaco you can delete this PR now.

**Comment by maxtaco** [comment]
nuked

**Pull request closed without merging**
