### PR TITLE
nuke the leveldb file if we get an error indicating corruption CORE-3324

### PR DESCRIPTION
**Pull request by mmaxim**
@maxtaco r? (let me know if you want me to tag someone else)

The idea here is to just delete the LevelDB file if we get an error back indicating it is hosed, and just let the current operation seemingly succeed in that case.

### CODE REVIEW

**Comment by maxtaco** [comment]
how did you test this?

And for now, can we only run on windows?

**Comment by zanderz** [comment]
There's no chance of the word "corrupt" being localized, is there?

**Comment by mmaxim** [comment]
@maxtaco I just added random data into the LevelDB file to make sure I could trigger my new message. 

@zanderz good question, let me check. The relevant code is the following from the library:

```
if !pend1 || cerr == nil {
    cerr = fmt.Errorf("leveldb/storage: corrupted or incomplete %s file", fn)
}
```

**Comment by mmaxim** [comment]
This is what it looks like on startup:

```
2016-07-19T13:07:17.578020 ▶ [DEBU keybase util.go:386] 012 + gregorHandler#newGregorClient
2016-07-19T13:07:17.578125 ▶ [DEBU keybase gregor.go:203] 013 push handler: restoring state from leveldb
2016-07-19T13:07:17.578141 ▶ [DEBU keybase leveldb.go:38] 014 + LevelDb.open
2016-07-19T13:07:17.578160 ▶ [DEBU keybase leveldb.go:67] 015 data dir: /Users/mike/Library/Application Support/KeybaseDevel
2016-07-19T13:07:17.578178 ▶ [DEBU keybase leveldb.go:40] 016 | Opening LevelDB for local cache: &{<nil> /Users/mike/Library/Application Support/KeybaseDevel/keybase.leveldb {1 0} {0xc8201ba280}} /Users/mike/Library/Application Support/KeybaseDevel/keybase.leveldb
2016-07-19T13:07:17.586309 ▶ [DEBU keybase leveldb.go:53] 017 - LevelDb.open -> ok
2016-07-19T13:07:17.586428 ▶ [DEBU keybase leveldb.go:113] 018 LevelDB file corrupted, nuking database and starting fresh
2016-07-19T13:07:17.586442 ▶ [DEBU keybase leveldb.go:85] 019 Closing LevelDB local cache: /Users/mike/Library/Application Support/KeybaseDevel/keybase.leveldb
2016-07-19T13:07:17.587808 ▶ [DEBU keybase gregor.go:203] 01a push handler: restore local state failed: EOF
2016-07-19T13:07:17.587851 ▶ [DEBU keybase util.go:387] 01b - gregorHandler#newGregorClient -> ok
```

**Comment by mmaxim** [comment]
@maxtaco I also don't think this has anything to do with Windows, it just seems like it is easier for the file to get corrupted there.

**Comment by maxtaco** [comment]
ok, then 👍

**Comment by mmaxim** [comment]
Also one last bit of info, before my change this is what it looks like for me:

```
[mike@lisa-keybase]-[~/Library/Application Support/KeybaseDevel/keybase.leveldb] (master)$ kb id t_mike
▶ WARNING Running in devel mode
▶ WARNING Failed to load ff261e3b26543a24ba6c0693820ead19 from storage: leveldb/table: corruption on table-footer (pos=87828): bad magic number [file=000016.ldb]
▶ WARNING not exportable error: leveldb/table: corruption on table-footer (pos=87828): bad magic number [file=000016.ldb] (*errors.ErrCorrupted)
▶ ERROR leveldb/table: corruption on table-footer (pos=87828): bad magic number [file=000016.ldb]
```

**Pull request merged**
