### PR TITLE
Use black_75_on_white so emojis don't become transparent

### PR DESCRIPTION
**Pull request by MarcoPolo**
@keybase/react-hackers @cecileboucheron

### CODE REVIEW

**Comment by adamjspooner** [comment]
Do you want to include the fix for `.text_Body` too?

**Comment by MarcoPolo** [comment]
@adamjspooner are you talking about every case of `Body` type in text tags? I think that's a much bigger change and shouldn't be included here. This is just for the stellar send form

**Comment by adamjspooner** [comment]
Yeah, the emoji in chat messages are transparent as well. I wasn't sure if you wanted to clean that up with this PR.

**Comment by MarcoPolo** [comment]
Yeah that's a different issue. Fixed here: https://github.com/keybase/client/pull/14495

**Pull request merged**
