### PR TITLE
add test for loader bug that is fixed server-side

### PR DESCRIPTION
**Pull request by xgess**
this bug appears to be fixable by either this PR or https://github.com/keybase/keybase/pull/3464. neither is a slam dunk in my mind.

### CODE REVIEW

**Comment by heronhaye** [comment]
I think this is a much better solution but Miles and Max should comment

**Comment by xgess** [comment]
i think the right place to fix this is the server. the safer place is the client. we should discuss.

**Comment by heronhaye** [comment]
but you actually aren't in the team though

**Comment by mlsteele** [comment]
You have access to read the team. The value (not the presence) of `read_subteam_id` field is just telling the server something it already knows.

**Comment by xgess** [comment]
@mlsteele it also indicates to the server which links in the chain are actually necessary so the rest can be pruned.

**Comment by heronhaye** [comment]
>value (not the presence)
That makes sense

**Pull request closed without merging**
