### PR TITLE
Devices: Fix revoked color

### PR DESCRIPTION
**Pull request by cjb**
@keybase/react-hackers 

This ended up being a larger change, after talking to Cecile.  The revoked devices and ignored public folders had the wrong color, as a symptom of a larger problem: the background color for the entire of each tab was white100, but the background color for tabs with a list (devices, public folders) should be lightGrey, and then each element on top of that background should be set to white100, so that we can then use white40 for greyed out elements, and also have the background outside the list elements be lightGrey rather than white.  The devices tab matches up with Zeplin colors now.

Feel free to ask for a more coherent explanation!

### CODE REVIEW

**Comment by keybase-ci-visdiff** [comment]
:mag_right: The commits f5a47eaf82d5...f5243083ef14 introduced some visual changes:
 * Changed: **Menubar-Public_Truncated** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1466699834574-f5a47eaf82d5-f5243083ef14/Menubar-Public_Truncated-f5a47eaf82d5.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1466699834574-f5a47eaf82d5-f5243083ef14/Menubar-Public_Truncated-f5243083ef14.png)  
   Menubar-Public_Truncated comparison
 * Changed: **Menubar-Public_Normal** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1466699834574-f5a47eaf82d5-f5243083ef14/Menubar-Public_Normal-f5a47eaf82d5.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1466699834574-f5a47eaf82d5-f5243083ef14/Menubar-Public_Normal-f5243083ef14.png)  
   Menubar-Public_Normal comparison
 * Changed: **Menubar-Public_Menu_Showing** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1466699834574-f5a47eaf82d5-f5243083ef14/Menubar-Public_Menu_Showing-f5a47eaf82d5.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1466699834574-f5a47eaf82d5-f5243083ef14/Menubar-Public_Menu_Showing-f5243083ef14.png)  
   Menubar-Public_Menu_Showing comparison
 * Changed: **Menubar-Private_Truncated** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1466699834574-f5a47eaf82d5-f5243083ef14/Menubar-Private_Truncated-f5a47eaf82d5.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1466699834574-f5a47eaf82d5-f5243083ef14/Menubar-Private_Truncated-f5243083ef14.png)  
   Menubar-Private_Truncated comparison
 * Changed: **Menubar-Private_Normal** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1466699834574-f5a47eaf82d5-f5243083ef14/Menubar-Private_Normal-f5a47eaf82d5.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1466699834574-f5a47eaf82d5-f5243083ef14/Menubar-Private_Normal-f5243083ef14.png)  
   Menubar-Private_Normal comparison
 * Changed: **Menubar-Private_Menu_Showing** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1466699834574-f5a47eaf82d5-f5243083ef14/Menubar-Private_Menu_Showing-f5a47eaf82d5.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1466699834574-f5a47eaf82d5-f5243083ef14/Menubar-Private_Menu_Showing-f5243083ef14.png)  
   Menubar-Private_Menu_Showing comparison
 * Changed: **Folders_TLF-Normal_Public** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1466699834574-f5a47eaf82d5-f5243083ef14/Folders_TLF-Normal_Public-f5a47eaf82d5.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1466699834574-f5a47eaf82d5-f5243083ef14/Folders_TLF-Normal_Public-f5243083ef14.png)  
   Folders_TLF-Normal_Public comparison
 * Changed: **Folders_TLF-Normal_Private** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1466699834574-f5a47eaf82d5-f5243083ef14/Folders_TLF-Normal_Private-f5a47eaf82d5.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1466699834574-f5a47eaf82d5-f5243083ef14/Folders_TLF-Normal_Private-f5243083ef14.png) [(diff)](http://keybase-app-visdiff.s3.amazonaws.com/1466699834574-f5a47eaf82d5-f5243083ef14/Folders_TLF-Normal_Private.png)

**Comment by cjb** [comment]
(Fixed up height on menubar widget.  Thanks, visdiff!)

**Comment by keybase-ci-visdiff** [comment]
:mag_right: The commits f5a47eaf82d5...b2d73ab21495 introduced some visual changes:
 * Changed: **Menubar-Public_Normal** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1466700592000-f5a47eaf82d5-b2d73ab21495/Menubar-Public_Normal-f5a47eaf82d5.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1466700592000-f5a47eaf82d5-b2d73ab21495/Menubar-Public_Normal-b2d73ab21495.png)  
   Menubar-Public_Normal comparison
 * Changed: **Menubar-Public_Menu_Showing** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1466700592000-f5a47eaf82d5-b2d73ab21495/Menubar-Public_Menu_Showing-f5a47eaf82d5.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1466700592000-f5a47eaf82d5-b2d73ab21495/Menubar-Public_Menu_Showing-b2d73ab21495.png)  
   Menubar-Public_Menu_Showing comparison
 * Changed: **Folders_TLF-Normal_Public** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1466700592000-f5a47eaf82d5-b2d73ab21495/Folders_TLF-Normal_Public-f5a47eaf82d5.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1466700592000-f5a47eaf82d5-b2d73ab21495/Folders_TLF-Normal_Public-b2d73ab21495.png)  
   Folders_TLF-Normal_Public comparison
 * Changed: **Folders_TLF-Normal_Private** [(before)](http://keybase-app-visdiff.s3.amazonaws.com/1466700592000-f5a47eaf82d5-b2d73ab21495/Folders_TLF-Normal_Private-f5a47eaf82d5.png) [(after)](http://keybase-app-visdiff.s3.amazonaws.com/1466700592000-f5a47eaf82d5-b2d73ab21495/Folders_TLF-Normal_Private-b2d73ab21495.png)  
   Folders_TLF-Normal_Private comparison

**Comment by chrisnojima** [comment]
👍

**Pull request merged**
