### PR TITLE
add `keybase git list`

### PR DESCRIPTION
**Pull request by oconnor663**
r? @patrickxb 

cc @mmaxim 

Currently the output looks like this (edited to include new URL as suggested):

```
personal repos:
  badrepo  keybase://private/oconnor663/badrepo
team repos:
  miketestteam3/jacktest1  keybase://team/miketestteam3/jacktest1
```

### CODE REVIEW

**Comment by mmaxim** [comment]
Can it display URL?

**Comment by oconnor663** [comment]
Sure. What do you think, show it instead of the name, or next to it?

**Comment by patrickxb** [comment]
Yeah, URL would be nice for copy/paste.

**Comment by mmaxim** [comment]
Should just show both, no flag imo

**Comment by oconnor663** [comment]
edited above, let me know what you guys think

**Pull request closed without merging**
