### PR TITLE
LTPAK: avoid loading keys if team is public and we are not a member

### PR DESCRIPTION
**Pull request by zapu**
*(LoadTeamPlusApplicationKeys)*

This is the first push but maybe we are seeking something different for public teams.

Let's wait for @strib 

cc @maxtaco

### CODE REVIEW

**Comment by strib** [comment]
@zapu what do you need from me?

**Comment by maxtaco** [comment]
@strib  -- are public KBFS teams encrypted, and if so with what key?

**Comment by strib** [comment]
>  are public KBFS teams encrypted, and if so with what key?

Do you mean public team TLFs?  They're encrypted with the zero key.  We don't need the team application keys for public teams.

**Comment by maxtaco** [comment]
OK, great, that answers the question.

**Pull request merged**
