### PR TITLE
Stellar available-to-send wording

### PR DESCRIPTION
**Pull request by mlsteele**

### CODE REVIEW

**Comment by Gobiner** [comment]
Nooooo, don't take away my available to send!

**Comment by akalin-keybase** [comment]
chatted with @cecileboucheron, 'available to send' is used in some other places, but agreed that in this context it's still weird enough to change.

**Comment by cecileboucheron** [comment]
Why ditching the `.`? 
:'(

**Comment by akalin-keybase** [comment]
Ah, yes, we should keep that!

**Pull request merged**
