### PR TITLE
Don't wait forever when dialing the server on Windows

### PR DESCRIPTION
**Pull request by zanderz**
Had this backwards, thought we wanted to wait forever for some reason (even looked for the convo in Slack, couldn't find it)
@maxtaco @patrickxb

### CODE REVIEW

**Comment by maxtaco** [comment]
What does the error look like when it fails to connect?

**Comment by zanderz** [comment]
c:\work\src\github.com\keybase\client\go\keybase>keybase ctl stop
- WARNING Running in devel mode
- ERROR Timed out waiting for pipe '\\.\pipe\kbservice\Users\Steve\AppData\Roaming\KeybaseDevel\keybased.sock' to come available

**Comment by maxtaco** [comment]
Ok great.

**Comment by zanderz** [comment]
Merging without travis because this is windows only

**Pull request merged**
