### PR TITLE
Fix version restart

### PR DESCRIPTION
**Pull request by gabriel**
@patrickxb @maxtaco

### CODE REVIEW

**Comment by patrickxb** [comment]
LGTM

@maxtaco you too?

**Comment by patrickxb** [comment]
appveyor failed, however...

**Comment by gabriel** [comment]
k fixing

**Comment by maxtaco** [comment]
Why do we need this? Isn't it good enough to just stop the service and have launchd restart it?

**Comment by gabriel** [comment]
ctl.Stop calls launchd remove (which tells launchd not to keep it started)

this is correct, except we expect it to not do this in versionfix

**Comment by gabriel** [comment]
ctl.Stop calling launchd remove was a change we made last friday:
https://github.com/keybase/client/commit/1dc4db531dc11029808e40666ae92fdb37590bde

**Comment by maxtaco** [comment]
Makes sense.  So we introed a bug last week.  Drats! Sorry about that.

Ok with this fix, ship!

Thanks.

**Comment by maxtaco** [comment]
Yeah I remember it well.  Sorry I didn't catch this in review!!!!!

**Pull request merged**
