### PR TITLE
Menubar fixes

### PR DESCRIPTION
**Pull request by MarcoPolo**
Handle the resizing of the menubar window.
Fix styling issue.
Don't fetch folders if not logged in.

@keybase/react-hackers

### CODE REVIEW

**Comment by chrisnojima** [comment]
@MarcoPolo i get that same visual issue with the menu in this branch. i also get this warning
```
Warning: flattenChildren(...): Encountered two children with the same key, `.0:$test12`. Child keys must be unique; when two children share a key, only the first child will be used.
```

**Comment by MarcoPolo** [comment]
Do you have two favorited folders with the same name? the key is the folder name.

**Comment by cjb** [comment]
@MarcoPolo The error says the key is ".0:$test12", does that help?

**Comment by cjb** [comment]
:thumbsup:

**Pull request merged**
