### PR TITLE
add noCache argument to loadUserPlusKeys

### PR DESCRIPTION
**Pull request by songgao**
r? @maxtaco @patrickxb thanks!

### CODE REVIEW

**Comment by maxtaco** [comment]
Can you call this `ForcePoll`?  Also, how will it be used?

**Comment by songgao** [comment]
Did you mean `ForcePull`?

It'd be used only for rekeys. Every time KBFS processes a rekey, it'd set this flag. Other operations will leave this flag as `false`. Sounds reasonable?

**Comment by songgao** [comment]
Or is it actually a poll on server? What would it poll on? is there any side-effect if no key has changed?

**Comment by maxtaco** [comment]
I'm confused because I thought we decided we didn't need this behavior.

**Comment by songgao** [comment]
We talked on slack/hangout. Closing!

**Pull request closed without merging**
