### PR TITLE
strip go binaries on mobile

### PR DESCRIPTION
**Pull request by heronhaye**
https://blog.filippo.io/shrink-your-go-binaries-with-this-one-weird-trick/

### CODE REVIEW

**Comment by joshblum** [comment]
@heronhaye any reason not to do this on other desktop platforms?

**Comment by heronhaye** [comment]
nope, just wanted to see on one first. there used to

**Comment by joshblum** [comment]
I tried an iOS sim build and it seemed fine, I think it’s worth trying for
some admin builds

**Comment by heronhaye** [comment]
The thing to make sure is if we get a segfault we still have full stacktrace in logs. It might be different on simulator vs real device too. Maybe we can make a panic button?

**Comment by heronhaye** [comment]
Also, KBFS prints some traces from goroutines in their logs - should check those too.

**Comment by joshblum** [comment]
will try this out:
```
$ git diff
diff --git a/go/keybase/main.go b/go/keybase/main.go
index 433fc4aa05..987da684ff 100644
--- a/go/keybase/main.go
+++ b/go/keybase/main.go
@@ -47,6 +47,17 @@ func keybaseExit(exitCode int) {
 }

 func main() {
+       go func() {
+               select {
+               case <-time.After(time.Second * 15):
+                       debug.PrintStack()
+               }
+               select {
+               case <-time.After(time.Second * 15):
+                       panic("panic")
+               }
+       }()
+
        // Preserve non-critical errors that happen very early during
        // startup, where logging is not set up yet, to be printed later
        // when logging is functioning.
```

**Comment by joshblum** [comment]
log id `d9562ca381b476889c90ea1c`

**Comment by heronhaye** [comment]
@jzila CI changes ok?

**Pull request merged**
