### PR TITLE
Wait for Jenkins CI when building app, instead of Travis/Appveyor

### PR DESCRIPTION
**Pull request by gabriel**
@cjb

### CODE REVIEW

**Comment by gabriel** [comment]
Tested this on another branch and worked... 

```
release wait-ci --repo="client" --commit=updaterv1api --context="Jenkins - Linux" --context="Jenkins - Windows" --context="Jenkins - OS X" --context="ci/circleci"
```

**Comment by gabriel** [comment]
@cjb if you want to make the status context labels look like all the other ones they could be:

jenkins/windows
jenkins/linux
jenkins/osx

but up to you

**Comment by cjb** [comment]
Okay, sure.  Will change now.

**Comment by cjb** [comment]
Actually.. I like them as they are because it easily allows a human reading to see which build failed, makes sense to optimize for humans first and our CI scripts second.  :)

**Comment by cjb** [comment]
Oh wait.  I think the labels you'll get from the master branch are different to the labels you'll get from a PR.  Let's wait until we have master passing and see what we get.

**Comment by gabriel** [comment]
sg2m

**Comment by gabriel** [comment]
These are the 2 labels so far on master:
- client-windows-master-only/label=windows
- client-linux-master-only/label=master

And I'm guessing:
- client-osx-master-only/label=osx

Although linux's label is master, not linux

**Comment by cjb** [comment]
:ship:

**Pull request merged**
