### PR TITLE
injecting menus for the app

### PR DESCRIPTION
**Pull request by chrisnojima**
@keybase/react-hackers

### CODE REVIEW

**Comment by chrisnojima** [comment]
@cjb wanna test this on linux

**Comment by MarcoPolo** [comment]
Do we not have to do this for the main window?

**Comment by MarcoPolo** [comment]
:+1: % question

**Comment by cjb** [comment]
@chrisnojima What exactly should I test on Linux?  Nothing's broken, but nothing's visibly changed either, because you don't seem to add menus to any windows with menubars on Linux.

**Comment by chrisnojima** [comment]
@cjb does copy / paste work

**Comment by cjb** [comment]
In pinentry?  Yeah, it worked before (on master right now) and continues to work on this branch.

**Comment by chrisnojima** [comment]
@cjb i injected this into the main window, can you test that it shows in the main window?

**Comment by cjb** [comment]
Ah.  It doesn't, I don't think.. the main window on Linux already had a standard Electron menubar with edit menu and I don't think it's changed.  Can recheck later.

**Comment by chrisnojima** [comment]
ok, maybe let's put this in and make a ticket to make this work in windows/linux

**Comment by chrisnojima** [comment]
made desktop-197/198

**Pull request merged**
