### PR TITLE
give some notification that the remote user's attachment upload is st…

### PR DESCRIPTION
**Pull request by zanderz**
…ill pending

I know this stuff is changing, too, but is this the right approach?

### CODE REVIEW

**Comment by mmaxim** [comment]
It is probably simpler to just have a state for "attachment not here yet", which I think is already basically represented. We could just show a spinner on the gray box if the client has received an attachment message, but doesn't yet have the attachment uploaded. I don't think you need to distinguish the "uploader has finished" from "download not finished" state. 

Would be good to get something in for this though, the user experience is pretty rough receiving attachments.

**Comment by mmaxim** [comment]
I guess it comes down to "any place you would have shown the gray placeholder box, draw a spinner instead"

**Comment by zanderz** [comment]
The ticket said to show it uploading on the sender side. Downloading has a progress bar, but we don't seem to have progress for the remote uploading. Maybe we need a more explicit design before this can be worked on.

**Comment by chrisnojima** [comment]
i know mike wants to change how this works but we can make this work short term

**Comment by zanderz** [comment]
anyone? @keybase/react-hackers ?

**Comment by mmaxim** [comment]
I think the text "sender uploading" isn't what we want here, maybe "waiting..." is better.

**Pull request merged**
