### PR TITLE
enable zooming on desktop

### PR DESCRIPTION
**Pull request by chrisnojima**
@malgorithms should we just turn this on?

### CODE REVIEW

**Comment by malgorithms** [comment]
hell yeah

**Comment by chrisnojima** [comment]
@keybase/react-hackers this turns on command +/- for zooming in desktop. use at your own risk

**Comment by adamjspooner** [comment]
Is there a `cmd+0` (return to normal) option?

**Comment by chrisnojima** [comment]
yes that works

**Pull request merged**
