### PR TITLE
Hook up deeplinks.tsx to the startupLink handler

### PR DESCRIPTION
**Pull request by pzduniak**
cc @keybase/y2ksquad

### CODE REVIEW

**Comment by cjb** [comment]
@pzduniak Looks okay, but do you also need to disable the willingness of the existing deeplinks handler (in actions/deeplinks.tsx) to route before getting to this spot?  At the moment I think it will try to nav you even if you're not logged in.

**Comment by pzduniak** [comment]
@cjb The deeplinks stuff does not happen during startup, they only listen to _new_ deeplink events (or however that stuff works).

**Comment by zapu** [comment]
I'm busy with few things right now so I haven't tried it yet, but is it OK if the deep link handler runs multiple times? I looked at call hierarchy of `DeeplinksGen.createLink` and I'm not sure that some code paths lead to it being dispatched multiple times.

**Comment by zapu** [comment]
For reference, call graph of the deeplink createLink

image

**Pull request merged**
