### PR TITLE
Only run visual diffs on pull requests

### PR DESCRIPTION
**Pull request by chromakode**
Currently breaking master by attempting to comment on a nonexistent issue.

### CODE REVIEW

**Comment by keybase-ci-visdiff** [comment]
:mag_right: No visual changes found as a result of these commits.

**Comment by cjb** [comment]
:thumbsup:, please merge straight away

**Comment by cjb** [comment]
actually, not sure this works

**Comment by cjb** [comment]
.. no, it's good, was thinking through the cd logic.  (I agree pushd would help!)

**Comment by chromakode** [comment]
Merged https://github.com/keybase/client/commit/d1fb8e75273baebdad8d605b2dd2be3abc93ff45

**Pull request closed without merging**
