### PR TITLE
de-dup invites and reset users in team.Details

### PR DESCRIPTION
**Pull request by mmaxim**
cc @buoyad

### CODE REVIEW

**Comment by buoyad** [comment]
This might be an edge case because I've reset `dannytest3` 10 times by now. I just reset both of these users in a team, and haven't provisioned anything for either. This is what the member list looks like
image
same deal in `list-members` via cli.

The master client shows this:
image

**Comment by zapu** [comment]
The only issue I see is that it wouldn't dedup if old version of user has a different role than one being added.

**Comment by buoyad** [comment]
Yeah my comment is a severe edge case that I'd argue is okay to leave

**Comment by zapu** [comment]
At some point we will have to support these edge cases when people's teams grow bigger and different situations might ensue. But it's fine to get there in incremental steps

**Comment by mmaxim** [comment]
Hah!

**Pull request merged**
