### PR TITLE
Bump version to 1.1.0 for impending release

### PR DESCRIPTION
**Pull request by cjb**
@keybase/react-hackers CC @mmaxim @maxtaco 

What do we think about a large version bump before the next release?

### CODE REVIEW

**Comment by chrisnojima** [comment]
In my mind these versions mean nothing semantically therefore this decision is meaningless

**Comment by mmaxim** [comment]
Yes please make it 2.0.0

**Comment by chrisnojima** [comment]
I just mean I have no idea what criteria is used to make this decision so /shrug

**Comment by maxtaco** [comment]
I personally would find it helpful if we had something like `1.1.0` for full releases, and `1.1.1` for hotfixes.

**Comment by cjb** [comment]
Moved it up to 2.0.0

**Pull request merged**
